### ISSUE TITLE
Support Paged Reward Payouts

### ISSUE THREAD

**Issue by Ank4n** [polkadot-js/apps#10004]
We will soon have paged rewards once https://github.com/paritytech/polkadot-sdk/pull/1189 makes it to the runtime upgrade. Creating this ticket to add support for this to Polkadot-js app.
Similar to: https://github.com/paritytech/polkadot-staking-dashboard/issues/1586

Changes are not reflected in rust docs yet but linking to the documentation and relevant structs in the code.

Changes:
**3 new Storage items:** 
- ErasStakersOverview ([doc](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/staking/src/pallet/mod.rs#L442) and [value struct](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/primitives/staking/src/lib.rs#L406))
- ErasStakersPaged ([doc](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/staking/src/pallet/mod.rs#L489) and [value struct](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/primitives/staking/src/lib.rs#L374))
- ClaimedRewards ([doc](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/staking/src/pallet/mod.rs#L509))

**Following storage items are deprecated**. 
(Note: Once these changes are in a runtime, all the new era exposure will go to new storage items above while the following storage items will still keep historical era information (looking to make this info easy to get via a runtime api). In 84 eras after the release, all these storage items will be empty and can be removed from runtime code.)
- [ErasStakers](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/staking/src/pallet/mod.rs#L419)
- [ErasStakersClipped](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/staking/src/pallet/mod.rs#L471)
- [Ledger::claimed_rewards](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/staking/src/lib.rs#L489) (not called legacy_claimed_rewards in the runtime code)

**Extrinsics to payout rewards:**
[payout_stakers](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/staking/src/pallet/mod.rs#L1545): can be called multiple times for an era and validator stash, paying out one page of exposure at a time.
[payout_stakers_by_page](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/staking/src/pallet/mod.rs#L1866): can be used to payout rewards for a particular page of exposure.

Feel free to add any useful runtime api requests to [issue#426](https://github.com/paritytech/polkadot-sdk/issues/426) to help with this.

**Comment by Ank4n** [comment]
Any updates to this? The changes are live on westend.

**Comment by TarikGul** [comment]
https://github.com/polkadot-js/api/pull/5813 fixes the erasStakersClipped issue

**Comment by TarikGul** [comment]
Completed in the API via: https://github.com/polkadot-js/api/pull/5815

**Comment by kukabi** [comment]
Hi,

There seems to be something wrong with the new `Staking.ErasStakersPaged` storage item on Kusama.

When I query the keys of the storage item for the current era 6522 it gives 1000 keys. Two of those pages belong to `GUw3gm93T85i9Syb4hA3NotNMFgCB56p7osxi3hnoqforMj`, which seems to have over 700 active stakers. So that means the storage contains the exposure data for only 999 validators.

And when I checked it against the active validator list, the storage item doesn't give the exposure for validator `GhGzv1S37MxmUFszHvx2M69ka3xTq4PBQZ4Ck8RzQ9TZ77u`. And it seems the same problem exists for `Staking.ErasStakersOverview`.

It looks like there's no storage item where I can get the exposure for `GhGzv1S37MxmUFszHvx2M69ka3xTq4PBQZ4Ck8RzQ9TZ77u`. Could you please confirm?

Thanks in advance.

**Comment by Ank4n** [comment]
@kukabi 
`Gh...7u` seems to have no exposure except its own. If you query `ErasStakersOverview` you will see it returns 

```json
{
  total: 6,999,998,586,259,297
  own: 6,999,998,586,259,297
  nominatorCount: 0
  pageCount: 0
}
```
This is why you do not see any entry for `Gh..7u` in `ErasStakersPaged`.

**Comment by Ank4n** [comment]
Not sure if you meant there is some issue with `GU...Mj` as well. I queried `ErasStakersOverview` and `ErasStakersPaged` for it and seems alright to me.

```js
console.log((await api.query.staking.erasStakersOverview(6522, 'GUw3gm93T85i9Syb4hA3NotNMFgCB56p7osxi3hnoqforMj')))
console.log((await api.query.staking.erasStakersPaged.keys(6522, 'GUw3gm93T85i9Syb4hA3NotNMFgCB56p7osxi3hnoqforMj')).length)
console.log((await api.query.staking.erasStakersPaged(6522, 'GUw3gm93T85i9Syb4hA3NotNMFgCB56p7osxi3hnoqforMj', 0)).unwrap().others.length)
console.log((await api.query.staking.erasStakersPaged(6522, 'GUw3gm93T85i9Syb4hA3NotNMFgCB56p7osxi3hnoqforMj', 1)).unwrap().others.length)
```

Output:
```
{"total":"0x00000000000000000019adfbb107f3a0","own":10000063083922,"nominatorCount":716,"pageCount":2}
2
512
204
```

**Comment by kukabi** [comment]
@Ank4n That probably was the issue, thanks. And no there's no issue with `GU...Mj`, just meant it had two pages of data.

**Comment by TarikGul** [comment]
Completed via https://github.com/polkadot-js/apps/pull/10554
