### ISSUE TITLE
Delegating through Accounts tab uses old Democracy Pallet

### ISSUE THREAD

**Issue by filippoweb3** [polkadot-js/apps#10037]
Delegating votes through the "Accounts" tab uses the old `democracy` pallet. As a consequence users will create locks that are 4x longer than those created with `convictionVoting` pallet.

![Screenshot 2023-11-16 at 14 43 55](https://github.com/polkadot-js/apps/assets/110459737/73201b7f-0d75-4fb5-acbf-b0b883af5197)

![Screenshot 2023-11-16 at 14 21 33](https://github.com/polkadot-js/apps/assets/110459737/8148181c-e5d2-402b-a30f-084f6cca5999)

**Comment by jacogr** [comment]
That is 100% expected - that is a democracy delegation function, not an OpenGov function. (So if a chain has a democracy pallet, the delegation there delegates those votes. The new style goverance as handled elsewhere.)

As the democracy pallet is dropped on-chain, the above functionality won't be available. Where chains have both pallets, the dual functionality remains.

**Comment by filippoweb3** [comment]
@jacogr thanks for explaining. Not nice for users, as I got people now with 4x longer locks. That feature should be hidden somewhere, and not accessible through the Accounts tab IMO 👍
