### ISSUE TITLE
Error Encountered Viewing Pending Payouts After Latest Westend Upgrade (Version: westend/104000)

### ISSUE THREAD

**Issue by Nick-1979** [polkadot-js/apps#10067]
* **I'm submitting a ...**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

After the latest upgrade, and presumably with the introduction of erasStakersPaged, we encountered an error while trying to view the pending payouts of an account in Westend.

<img width="1492" alt="Screenshot 2023-11-30 at 3 01 25 at night" src="https://github.com/polkadot-js/apps/assets/46442452/bb20d3c6-2f49-45c2-abc4-bb5a698b971e">

<img width="791" alt="Screenshot 2023-11-30 at 3 02 10 at night" src="https://github.com/polkadot-js/apps/assets/46442452/f5aa6b42-0500-4570-8e0c-abbf82b62ef7">

* **Please tell us about your environment:**

  - Version: westend/104000
  - Environment: Westend chain

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

**Comment by jacogr** [comment]
Will disable the route in https://github.com/polkadot-js/apps/pull/10108

(BTW, certainly not a bug report, this is a rewrite)
