### ISSUE TITLE
just before debuj

### ISSUE THREAD

**Issue by asggWa** [polkadot-js/apps#10107]
after appears menu.
its try rococo buts attach polkadot

**Comment by asggWa** [comment]
![IMG_20231218_150504.jpg](https://github.com/polkadot-js/apps/assets/79282759/b5d02ba6-b652-44aa-b0e8-6cbcd098aa53)

**Comment by asggWa** [comment]
![IMG_20231218_150853.jpg](https://github.com/polkadot-js/apps/assets/79282759/4d877025-b647-4818-92d1-31e280b81f93)




que después sobra algo y es que debería.
cuando necesites...

**Comment by jacogr** [comment]
This is not Parity UI.

**Comment by asggWa** [comment]
Yo soportaré la herramienta si es necesarío y pondré un caballito al alert poara capturar  esa exceptición si es necesario.
esa interface es polkadot parity y ademas rococoó y de lo contrario será reportada como amenaza al equipo de desarrollo de la comunidad ubuntu.
encarguensé, por favor. 
Yo no necesito porque proceder.
Si esa herramienta no es de páriti, tiene demasiada semejanza ya que soy token holder y es qwue en otor caso no quierpo ni los token, desbloquearía y sacaría a mercado. pero si la amenaza no es vuestra, yo no pienso pasar por sospechoso.
Entonces, existe y espero que sea revisada y al mismo tiempo trate de hacer buena labor. en otro caso supngo que ya debería haber sido reportada pero está interfiriendo en mi entorno polkadot. 
Entiende, gracias.
