### ISSUE TITLE
Provide static build

### ISSUE THREAD

**Issue by ZettaScript** [polkadot-js/apps#10157]
* **I'm submitting a feature request**

* **What is the current behavior and expected behavior?**

There is currently no way to serve Polkadot-JS easily and efficiently, i.e. using only a file-based web server (Apache, Nginx).

Since yarn is probably serving static files, it should be possible to provide an archive containing static web files, and a command to build them.

* **What is the motivation for changing the behavior?**

  * Yarn is hard to make working properly (e.g. the Debian package is broken, and I regularly encounter unexpected errors or version problems when building Node-related things), and re-building a yarn package at each server restart is very inefficient.
  * Some people may also not use Docker for various reasons.
  * Extracting the static files from an existing hosted Polkadot-JS does not work perfectly, and it's a dirty solution.
  * The Electron appimage build is not suited for a server, and inefficient for a desktop. Static files would be even more portable and versatile than the appimage.

**Comment by jacogr** [comment]
Static outputs (as served) is here - https://github.com/polkadot-js/apps/tree/gh-pages

**Comment by ZettaScript** [comment]
Thank you!

This branch was not mentioned in the README and I did not know branches could be used like this.
