### ISSUE TITLE
Settings / Developer page should have link to the documentation of the type definition syntax 

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#1017]
Assuming there is a type definition syntax page, it should be linked in the developer page so people can read it there.

If there isn't one, we need one.

**Comment by jacogr** [comment]
100%, good point - I actually missed this case in my “male help available everywhere” issue.

**Comment by jacogr** [comment]
Extend, properly link, make into HelpOverlay (?) - https://docs.substrate.dev/docs/substrate-runtime-recipes#section-polkadot-ui

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/apps/pull/1068
