### ISSUE TITLE
Staking page is missing in Westend 

### ISSUE THREAD

**Issue by BulatSaif** [polkadot-js/apps#10193]
Staking page is missing in Westend polkadot.js.org/apps

* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

**Expected behavior / old behavior:**
![image](https://github.com/polkadot-js/apps/assets/24387396/bda35f68-15d1-4913-a0d0-7b5af1e70e53)

**Current behavior:**
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend-rpc.polkadot.io#/staking
![image](https://github.com/polkadot-js/apps/assets/24387396/cab34461-629d-4852-bc9f-a7dcbb52a64b)

**Comment by jacogr** [comment]
It is on purpose, it is not supported with the new staking changes. (There is an issue logged for it, at some point hopefully a PR will come in to fix it)
