### ISSUE TITLE
Can not read account's identity on Westend!

### ISSUE THREAD

**Issue by AMIRKHANEF** [polkadot-js/apps#10211]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
Account's identity do not display on Westend!

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**
Browser

  - Version:
  - Environment:

    - [ ] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by AMIRKHANEF** [comment]
maybe this helps!


![image](https://github.com/polkadot-js/apps/assets/75857984/14a75622-36b1-4013-a4de-c3e2300bbb21)

**Comment by albertov19** [comment]
Hey, I believe this is a general issue across many chains with identity pallet. We are seeing the same problem in Tanssi's Testnet and in Moonbeam.

**Comment by TarikGul** [comment]
@AMIRKHANEF This is because the identity chain data has been moved to the "People Chain" for westend and Rococo: https://github.com/paritytech/polkadot-sdk/pull/2281
