### ISSUE TITLE
Visible sidebar scrollbar on Firefox even when not needed

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1025]
The image says it all. On chrome the sidebar is hidden (explicitly with a `::-webkit-scrollbar`)

![image](https://user-images.githubusercontent.com/33178835/56229119-7dd60c80-6079-11e9-8079-b23a964c433e.png)

**Comment by Stefie** [comment]
Which OS are you on? I'm just trying to reproduce the original bug but I don't see the scrollbar in Firefox on MacOS.

That screenshot was taken on FF 66.0.3
<img width="704" alt="Screenshot 2019-04-17 at 14 10 57" src="https://user-images.githubusercontent.com/125398/56286738-c85b9580-611a-11e9-922b-b20cb3a0685b.png">

**Comment by Stefie** [comment]
Could you provide steps to reproduce?

**Comment by Tbaut** [comment]
I'm on Linux Mint (ubuntu based), there isn't anything specific to do to reproduce other than opening the app in Firefox (using v66 atm)

**Comment by Stefie** [comment]
Ah, Linux, ok. No wonder that I can't reproduce! Jaco approved it already anyways. Do you have merge permissions here?

**Comment by Tbaut** [comment]
yes :)

**Comment by jacogr** [comment]
Didn’t see this before the PR - but Mac hides all bars by default.
