### ISSUE TITLE
Incompatibilities with Async Backing

### ISSUE THREAD

**Issue by timbrinded** [polkadot-js/apps#10283]
* **I'm submitting a ...**

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

When looking at an async backing enabled chain, there are a few issues.

### Blocks count down not up
![countdown](https://github.com/polkadot-js/apps/assets/79199034/1fbdfac5-69de-4b1a-827a-5f8d9717d5f1)

### Exts being linked to blocks incorrectly
![linkage](https://github.com/polkadot-js/apps/assets/79199034/2c20badf-0fe8-489c-b8d1-80559c30fd9c)

* **What is the motivation for changing the behavior?**

To support async backing

* **Please tell us about your environment:**

- `api` v10.11.2
- `apps` v0.133.2-86

**Comment by timbrinded** [comment]
countdown seems fixed in **apps** `v0.133.2-96`, the invalid issue and linking still appears active

**Comment by david9991** [comment]
> countdown seems fixed in **apps** `v0.133.2-96`, the invalid issue and linking still appears active

No the countdown has not yet been fixed, this issue only happens at beginning of each epoch that BABE has to generate epoch randomness for VRF to reelection leaders of each slots, so it still need to take 12s for backing and including the block produced in first slot even you have async backing enabled.

**Comment by timbrinded** [comment]
We've now deployed async backing to public testnet, you can see the defects at:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss.api.moonbase.moonbeam.network#/explorer

**Comment by IkerAlus** [comment]
@timbrinded are you sure the second issue is related to async backing and consistently happening? 

I see new extrinsics being linked to the right block in the interface when connected to the mentioned public testnet.

**Comment by timbrinded** [comment]
@IkerAlus it looks to be fixed in latest version published :+1:
