### ISSUE TITLE
PJS browser app is not listing all on-chain Governance->Preimages 

### ISSUE THREAD

**Issue by acatangiu** [polkadot-js/apps#10288]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

For some chains (saw this on PolkadotCollectives and Kusama, but possibly others), PJS is not showing all `Preimages` that are still on-chain.

For example, this preimage was submitted to Collectives: https://collectives.statescan.io/#/extrinsics/3201877-2
and on-chain preimage `0x953d2a661349cbbf2f7f14af56bad37393a54d1878b593fc4ee9e893bd7eb1ba` is not showing up in `Governance -> Preimages`.

Doing a bit of debugging, it seems that PJS is:

only listing the items found using deprecated [pallet_preimage::StatusFor](https://github.com/paritytech/polkadot-sdk/blob/9bf1a5e23884921498b381728bfddaae93f83744/substrate/frame/preimage/src/lib.rs#L173) storage

![Screenshot 2024-02-22 at 17 01 05](https://github.com/polkadot-js/apps/assets/31917973/0572808d-293d-479e-b72b-1455c263df3c)

and not listing items found using new [pallet_preimage::RequestStatusFor](https://github.com/paritytech/polkadot-sdk/blob/9bf1a5e23884921498b381728bfddaae93f83744/substrate/frame/preimage/src/lib.rs#L178C18-L178C34) storage item.

![Screenshot 2024-02-22 at 17 01 22](https://github.com/polkadot-js/apps/assets/31917973/4c5b825d-ae7d-4c4c-a8d5-1e22e68ceeaa)

* **What is the motivation for changing the behavior?**

Preimages should show up in the PJS GUI for a number of reasons:
- it allows easy listing
- it allows easy decoding and inspection of preimages
- it allows easy access to un-note and refund deposit once it is no longer needed
- governance proposals using preimages will correctly render the inner call (when PJS can find and decode the preimage)

* **Please tell us about your environment:**

  - Version: `apps v0.133.2-87`
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

**Comment by TarikGul** [comment]
Fixed via: https://github.com/polkadot-js/apps/pull/10310
