### ISSUE TITLE
Avail Goldberg Testnet website page https://goldberg.avail.tools lacks a lot 

### ISSUE THREAD

**Issue by wnhedaxx** [polkadot-js/apps#10295]
![Screenshot (116)](https://github.com/polkadot-js/apps/assets/70830772/6e56b96d-b81b-405a-a29c-df7ed0dfe179)
it takes alot of time to use Avail Goldberg Testnet please insure to make it fast and reliable 
.....
also i am unable to see my staked amount of avail tokens in pool page

**Comment by TarikGul** [comment]
> it takes alot of time to use Avail Goldberg Testnet please insure to make it fast and reliable

The speed of the RPC node does not have anything to do with this application but the node itself. 

> also i am unable to see my staked amount of avail tokens in pool page

The nomination pools tab is querying ALOT of data therefore it does take a few seconds even on a faster rpc node which is why it's taking you a long time to load them.

**Comment by wnhedaxx** [comment]
Thanks alot for your valuable reply
