### ISSUE TITLE
Browser fork option is persist accross site visits

### ISSUE THREAD

**Issue by peetzweg** [polkadot-js/apps#10305]
While I was playing with the new "Fork Locally" feature I stumbled upon a few ux issues which broke my flow working with the pjs console.

Usually I have multiple tabs open each on different pages of the console for the same chain. Using the "Fork Locally" feature each of my browsers tabs of the same network have their own fork. So if I fund "Demo Account" in Tab A, it's not funded in Tab B.

https://github.com/polkadot-js/apps/assets/839848/49cc7600-01cc-4a23-b4d5-a4248a4352f7

The other hiccup I had with this feature is that the console persists the option to "Fork Locally" even when I visit a completely different chain. So when I was on POlkadot and did "Fork Locally", and than open a link pointing to PJs console using Kusama it will do the local fork thing. Which is most likely not what the user wants.

https://github.com/polkadot-js/apps/assets/839848/fa77f5ab-7771-40d7-96cd-7bf412f12606

All in all I think this "Fork Locally" mode should not be persisted between console visits.

**Comment by adamsteeber** [comment]
I'm going to dog pile on this issue by mentioning the "Fork Locally" button **should not** be where the "Switch" button used to be. I keep clicking it out of muscle memory and it bricks my computer because Chopsticks is very resource intensive. The "Fork Locally" button should be less conspicuous and moved somewhere else.

**Comment by qiweiii** [comment]
> Using the "Fork Locally" feature each of my browsers tabs of the same network have their own fork. So if I fund "Demo Account" in Tab A, it's not funded in Tab B.

@peetzweg right now we use a web worker for chopsticks instance in browser, so it only works in one window. Maybe we can experiment with shared worker instead so it will work across tabs under the same origin.

> persists the option to "Fork Locally" even when I visit a completely different chain

the local fork state is save in browser localstorage, so it persists after you refresh. To stop using local fork, you can just click on the `Switch` button again.

For switch chains, I didn't think abt user doing it by changing url directly, if you switch chain using the UI, you can use `Switch` button to quit local fork mode, but this case can be fixed though, we can make it go back to normal mode when the rpc endpoint is changed

**Comment by qiweiii** [comment]
@adamsteeber 
How about switch the `Switch` and `Fork Locally` buttons, will that be better? so `Switch` button will go back to its old position. 
Or maybe add a secondary dropdown next to switch button and put fork button inside.

Any other suggestion is welcomed. @TarikGul

**Comment by peetzweg** [comment]
> > Using the "Fork Locally" feature each of my browsers tabs of the same network have their own fork. So if I fund "Demo Account" in Tab A, it's not funded in Tab B.
> 
> @peetzweg right now a chopsticks instance only work in one window. Maybe we can experiment with shared worker to make it work across tabs under the same origin.

This would be nice! Bit confusing that each tab has it's own reality.



> > persists the option to "Fork Locally" even when I visit a completely different chain
> 
> the local fork state is save in browser localstorage, so it persists after you refresh. To stop using local fork, you can just click on the `Switch` button again.
> 
> For switch chains, I didn't think abt user doing it by changing url directly, if you switch chain using the UI, you can use `Switch` button to quit local fork mode, but this case can be fixed though, we can make it go back to normal mode when the rpc endpoint is changed

I would disagree, if I open a link to pjs apps from any site I it will fork it, if I have used for before. I don't think it should be persisted at all. **What's the benefit to persist it?**  More often than not I think I would rather want to be connected to the live chain instead of a fork. That has always been the default before this feature as there was no fork option. 

Yes for developing this feature it might have been annoying always to click the fork button again and again for new sessions, but I still think I would 9/10 times would rather by default work with the live version.

**Comment by ermalkaleci** [comment]
If you want to have one fork open in multiple windows then start your fork on your terminal using `npx @acala-network/chopsticks -c acala` and then your endpoint is `ws://localhost:8000`

**Comment by TarikGul** [comment]
> @adamsteeber How about switch the `Switch` and `Fork Locally` buttons, will that be better? so `Switch` button will go back to its old position. Or maybe add a secondary dropdown next to switch button and put fork button inside.
> 
> Any other suggestion is welcomed. @TarikGul

@qiweiii  Hey Sorry I didn't comment earlier after merging your PR (Thank you for it). What you did with putting the switch back to it's original spot was perfect. I think the `Fork Locally` button being at the top left is totally acceptable as long as the switch button is back where it is. (Which your PR fixed)

In terms of the fork locally persisting after reopening the browser, I agree with @peetzweg. It would be ideal if it didn't persist after closing the browser. Currently with the most recent PR that went in https://github.com/polkadot-js/apps/pull/10308, it ensures persisting doesn't happen when the rpc has changed even if its the same chain (I would say step in the right direction). But it would probably be nice for it to not persist at all if the session has ended regardless of the url.

Thoughts?

**Comment by peetzweg** [comment]
@qiweiii thanks, this feels resolved for me. 🙏
