### ISSUE TITLE
Whitelist tab have all rows saying `No preimage bytes found`

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/apps#10312]
Currently the `WhiteList` tab under Governance shows `No preimage bytes found` for all rows. I am not super familiar with the whitelist calls, but am more familiar with preimages and was able to root out the cause where the [`optBytes`](https://github.com/polkadot-js/apps/blob/master/packages/react-hooks/src/usePreimage.ts#L235) option is None. Like I said I am not completely in tune with whitelisting but this deserves some investigation. 

![Screenshot 2024-02-29 at 8 46 42 PM](https://github.com/polkadot-js/apps/assets/47201679/2bceaf54-35be-4b29-81a1-0b9ffb617fd0)

Apps version v0.133.2-105

**Comment by TarikGul** [comment]
cc: @ryanleecode

**Comment by ryanleecode** [comment]
![image](https://github.com/polkadot-js/apps/assets/21375952/438627fe-0db6-487e-a7bd-1ffff630ed0b)

Seems legit. On the polkadot network there is 1 that has a pre-image -- so we know it works. I think its just the hash of whitelisted calls but optionally you have the have the pre-image aka the call itself so you know what actually got whitelisted.

**Comment by TarikGul** [comment]
> ![image](https://private-user-images.githubusercontent.com/21375952/311086828-438627fe-0db6-487e-a7bd-1ffff630ed0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NzIyMzgsIm5iZiI6MTcwOTg3MTkzOCwicGF0aCI6Ii8yMTM3NTk1Mi8zMTEwODY4MjgtNDM4NjI3ZmUtMGRiNi00ODdlLWE3YmQtMWZmZmY2MzBlZDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA0MjUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NjkyYjljMjQ3MWVmZDQwYjM0Y2M2YTg0YzhlNDU4MjVmYTViMTQzNjJiNWQzYjdjZGIzYmVmZGMwZDUzZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ew5H--mOPimlPki8mFceKDJBVf3RMiA0PO5_LC4b1lM)
> 
> Seems legit. On the polkadot network there is 1 that has a pre-image -- so we know it works. I think its just the hash of whitelisted calls but optionally you have the have the pre-image aka the call itself so you know what actually got whitelisted.

Aweomse, thanks so much for investigating this, going to close since it seems expected.
