### ISSUE TITLE
Collator list cannot be fetched in Collators page for some parachains.

### ISSUE THREAD

**Issue by david9991** [polkadot-js/apps#10322]
Collator list cannot be fetched in Collators page for some parachains with newer version of pallet-collator-selection being used.
The getter name has been changed to `candidate_list` instead of old `candidates`.
<img width="599" alt="Screenshot 2024-03-02 at 12 52 51" src="https://github.com/polkadot-js/apps/assets/123219/9bb3d3b3-25d1-42e8-a193-87ab1979b93c">

  - [x] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
Collator list should be displayed by trying both `candidate_list` and `candidates`.

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
hey @david9991, 

Could you provide some parachains this is active on so I can test it against them.

**Comment by david9991** [comment]
You can reproduce it using my testnet:  https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fplcc-parachain.g.pocograph.com#/collators

**Comment by david9991** [comment]
And also AssetHub / BridgeHub under rococo testnet which using latest version of polkadot-sdk:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-asset-hub-rpc.dwellir.com#/collators
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-bridge-hub-rpc.polkadot.io#/collators

This change was made under the file cumulus/pallets/collator-selection/src/lib.rs in [this commit](https://github.com/paritytech/polkadot-sdk/commit/7d735fc8ae8c9dde906457e27c9d2694892adc8b#diff-3cb37537b3ef3fc69f3328fcea23c8c80ad71eb9a3fc2b77a111da8ba28a6514)
