### ISSUE TITLE
`syncstate.genSyncSpec` throw  "Cannot read properties of null (reading 'toHuman')" error

### ISSUE THREAD

**Issue by chungquantin** [polkadot-js/apps#10339]
<img width="1512" alt="Screenshot 2024-03-07 at 18 13 17" src="https://github.com/polkadot-js/apps/assets/56880684/bbc51b35-ae8b-449a-b123-b78c7b36e8a5">

`syncstate.genSyncSpec` RPC calls throws on call
```
Cannot read properties of null (reading 'toHuman')
```
This can be expected that the output returned from the method is undefined and it is unable to generate the synced specification of the chain (my case is Polkadot Relaychain ) but we should do something with the error returned. 

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version: 122.0.6261.94 (Official Build) (arm64)
  - Environment: Google Chrome Browser

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
Thanks for reporting the issue, i was able to reproduce it. I need to look further to see what the core of the issue is.

**Comment by Imod7** [comment]
Same error reported in issue #9723
