### ISSUE TITLE
Allow signing from any account once in "Local Fork More" (Chopsticks pt2)

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/apps#10333]
What would be very useful is to also provide an easier way to fake any account once you click into that button. I am looking into the code to see if the CS instance is executed with `mock-signature-host` or not, but even if yes, atm I need to hack my way around. Ideally, the UI would facilitate this and allow you to:

1. Add any account you wish merely by the public key
2. (fake) Sign with all of your accounts.  

Without too much manual work needed.

_Originally posted by @kianenigma in https://github.com/polkadot-js/apps/issues/9903#issuecomment-1978555648_

**Comment by TarikGul** [comment]
@qiweiii Is this currently achievable with our current setup?

**Comment by qiweiii** [comment]
Yes, this should be achievable with

https://github.com/polkadot-js/apps/blob/53a178e7fcbafae6fc6f416437cc4caa4af821c1/packages/react-api/src/Api.tsx#L243

we can setStorage for all accounts by default

**Comment by qiweiii** [comment]
@TarikGul Where do you think we should place this feature, I'm think maybe add an input field in Accounts page, or maybe expose the chopsticks fork and its methods in JS page if possible

**Comment by TarikGul** [comment]
> I'm thinking maybe add an input field in Accounts page

Yea this makes sense. The inpute field would only be visible if the `Local Fork` is active right?
