### ISSUE TITLE
Issue with Identity due to out of date `@polkadot/api`

### ISSUE THREAD

**Issue by albertov19** [polkadot-js/apps#10354]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Some Identity-related features are broken. 

![image](https://github.com/polkadot-js/apps/assets/64150856/29192abc-0252-473a-844d-626fc155b16e)

Updating to `@polkadot/api` version `10.12.2` fixes the issue (I tried with a  local branch)

![image](https://github.com/polkadot-js/apps/assets/64150856/91291dfd-58f8-4318-9a80-0e6b5093c1fd)

I could push a PR to upgrade all `10.11.2` instances to `10.12.2` but I'm unsure about the implications.

* **Please tell us about your environment:**

The official Polkadot.js Apps instance is running against Dancebox, the Tanssi Testnet.

Then I ran Polkadot.js Apps locally with Node V20.11.0

**Comment by TarikGul** [comment]
Should be fixed with 0.134.1.
