### ISSUE TITLE
Copy button or download button for outputs

### ISSUE THREAD

**Issue by ryanleecode** [polkadot-js/apps#10391]
* **I'm submitting a ...**

  - [ ] Bug report
  - [X] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
To copy something as simple as the metadata, there should be a button. i shouldnt need to scroll down, press the `END` key on my keyboard, select some text and then press `HOME`.

https://www.loom.com/share/6ef675991db64eb5b3dd33432f5e47de?sid=5885693e-667c-4606-a1d6-2919ca8c1a79

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [X] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
The functionality already exists in apps we just need to add it to the Output. Ref: https://github.com/polkadot-js/apps/pull/7235
