### ISSUE TITLE
Extraneous bytes in `call` encoding breaks using contracts

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/apps#1040]
Yeah, its a little complicated if this is the first time you are touching contracts, but let me try to explain as best as I can.

Within the contracts language, I can print the "input" coming into the contract

the input we are getting at the contract is a 5 byte buffer plus the rest of the call, we expect a 4 byte buffer at the beginning, and the issue is this 0xff extra byte

the 4 byte buffer in the beginning is the contract function selector

the goal would be to see where this is coming from, using the contract apps

Quickly take a look at this output:

```
Runtime: Input: [38, 187, 29, 228, 255, 212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125]
Runtime: Erc20::balance_of(owner = Address([255, 212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162])) = 0
```

Here you can see the "input" has 4 bytes, which is the message selector: `38, 187, 29, 228`

Then it has `255`, which comes from nowhere

then the address:
`212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125`

You can see that the next line interprets the address wrong, because of the extra bytes:
`255, 212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162`

you can see the 125 was dropped at the end

and 255 was put at the begginning

**Comment by xlc** [comment]
0xff is part of the address encoding. it means the address format is the AccountId format instead AccoundIndex format. 
Either contract side need to support the address encoding so it can works with the short index format, or apps needs to use the AccoundId encoding.

**Comment by shawntabrizi** [comment]
@xlc I did not know this, and is super good info :)

It does not seem to make sense for ink! to have to interpret AccountIndex as that would cause some major overhead between the contracts layer and the Substrate runtime.

I think instead, it would be a fair assumption to make sure the apps UI always provides the AccountId encoding, without this special format.

**Comment by shawntabrizi** [comment]
The problem here is NOT with the UI, which is amazing. It was with our generated JSON file:

```
        {
            "name": "balance_of",
            "selector": 3827153702,
            "mutates": false,
            "args": [
                {
                    "name": "owner",
                    "type": "Address"
                }
            ],
            "return_type": "Balance"
        },
```

The ink! was using the term `Address` synonymously with `AccountId` which @xlc pointed out is very different.

All we need to do is put `AccountId` instead of `Address` and the problem is resolved. We will probably rename all instance of `Address` in ink! to `AccountId` to prevent any further confusion.

Thanks all
