### ISSUE TITLE
Be able to send the max amount

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1043]
I'd like to be able to send the maximum amount of Units possible considering the fees.
Not only useful for transfer but also for bonding / unbounding
This could take the form of a max button that could look like the following.

![image](https://user-images.githubusercontent.com/33178835/56726311-cca53580-674e-11e9-93bb-ba1db2d6d5df.png)

**Comment by jacogr** [comment]
This is quite tricky to get right _everywhere_ - transfer is relatively easy, bonding _may_ be, generally though the rules for the different calls in terms of fees are different and not 100% "cheap" (and honestly I don't believe we have full coverage yet, e.g. contracts surely does have 0%). 

So would need to do this on a per-app basis where we are full confident we have all the fees down 100%.
