### ISSUE TITLE
Overview of your accounts

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1044]
I've needed to have an overview of all my accounts and see their balance at glance. Right now `Accounts` doesn't allow this, `Staking` does ironically.

Here is an idea. ~~We could show an "Edit" button on mouse over to keep the screen lighter.~~ edit: add the ability to edit the name inline.
Additionnaly, we could add filters similar to what we have in the `Staking` app. (#971)

![image](https://user-images.githubusercontent.com/33178835/56729015-789d4f80-6754-11e9-9c23-9c5ea08e522b.png)

**Comment by jacogr** [comment]
Same with addresses. Additionally, currently we have different types of displays in different areas, i.e. staking vs accounts - should be aligned.

**Comment by jacogr** [comment]
Edit is (currently) only for name - that can actually be done in-line, i.e. click on it, it becomes an edit box, unclick, it saves.

Forget/Backup/Password we can probably do with appear buttons - maybe even gray buttons that show their colors when the card is active, that way there is not much jumping going on

**Comment by nczhu** [comment]
Caught up with @Tbaut on this last week. Put some of what we brainstormed down to Sketch. Keen to hear your feedback on this, in light of providing a more beginner-friendly UI for upcoming testnet(s).

1st draft includes:
- Breakdown of types of balances: free (avail, lock, vesting) vs reserved
- Inline edit icon
- Tags
- An empty state related to #1006 

![1  Accounts: empty state](https://user-images.githubusercontent.com/23445933/57706471-1a360380-7666-11e9-844b-864c841a4afc.png)

![2  Accounts: overview](https://user-images.githubusercontent.com/23445933/57706459-1609e600-7666-11e9-9bb1-51bcee2b1286.png)

![3  Accounts: overview 2](https://user-images.githubusercontent.com/23445933/57706484-1e622100-7666-11e9-964c-35c8dde82e4c.png)

**Comment by Tbaut** [comment]
Lots of great ideas. I think it's worth putting this on a meta issue to discuss further. (this one is specific for a first step implementation that I'm actually working on).
