### ISSUE TITLE
Recent metadata update introduced several UI problems on Kusama

### ISSUE THREAD

**Issue by CoinStudioDOT** [polkadot-js/apps#10482]
After a recent metadata update, there are several UI issues on Kusama:

1. Network - Staking - Overview: Other stake field empty
2. Network - Account: Staking accounts showing all nominations as invalid and all nominated validators as Inactive (confirmed they are in Active set)
3. Network - Payout - Own stashes: Empty - no account displayed

**Comment by TarikGul** [comment]
rel: https://github.com/polkadot-js/apps/issues/10396 https://github.com/polkadot-js/apps/issues/10004 https://github.com/polkadot-js/apps/issues/10388

**Comment by CoinStudioDOT** [comment]
Thanks, appreciate your work on this understanding there is a lot in line. The challenge here is operational limitation to payout staking rewards from stash or have full control of nominating accounts.
