### ISSUE TITLE
Converting on unit change is unexpected

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1049]
In any "balance" input field, if anything else than 0 is typed in, and the unit (DOT/Kilo/Giga..) subsequently changed, the input field will automatically convert the value.

This surprises me as a user every time. When I want to send a Mega, but forget to select the unit before typing in the input field, although I know a Mega is 1 000 000, I prefer to type `1` and then select "Mega". With the current behaviour, I have to remove the `0.` that automatically appeared. 

Logging this to see if this is only me, or if this happens to others and should be changed.

**Comment by jacogr** [comment]
It certainly is new since the rework (much needed I may add) that was done on the input component. I've had to adjust my workflow a bit as well - don't have a preference either way, but the original behavior (as you described), may be less surprising.

@kwingram25 your thoughts?

**Comment by Tbaut** [comment]
Great, I feared it was a feature that I simply couldn't get use to hence wanted to share my thoughts.

**Comment by kwingram25** [comment]
I think it's a safeguard against accidentally entering too high or too low a value which (I imagine) could happen if someone enters a value and then changes the unit without thinking - but if it becomes a common confusion/complaint it might be good to remove it

**Comment by Tbaut** [comment]
Although the original idea was good, it acts as safeguard in one direction (dividing), but also as a threat in the other e.g if you want to send 1 mili, you type `1`, select mili -> it'll multiply by 1000, so that users might end up sending much more than expected.

**Comment by jacogr** [comment]
I believe we should probably remove the conversion. Let the user rather be explicit in what he/she wants.
