### ISSUE TITLE
please add icon to the coretime chain

### ISSUE THREAD

**Issue by the-right-joyce** [polkadot-js/apps#10511]
hi, non-dev here :)

attaching the logos for the coretime chain, please add it to Kusama
and also update the AH one

![coretime_icon_black](https://github.com/polkadot-js/apps/assets/98593770/3d2bc73e-6217-4179-be68-54e63fa2d7b3)
![assethub_icon_black](https://github.com/polkadot-js/apps/assets/98593770/99276063-7496-4fd6-b959-90794ad7b7ec)

thanks upfront! :)

**Comment by itsbirdo** [comment]
these icons look pretty low quality. Can we use the icons listed in #10549 instead ? @TarikGul

**Comment by TarikGul** [comment]
Can you explain what is low quality about them? The bridgehub logo that is up for Kusama is the same. It's best to stick with the current theme that is set for a chain. On Kusama its Black and White. We had also discussed already in the water cooler that the Logos in the PR you linked are best fit for polkadot.
