### ISSUE TITLE
Explorer not Decoding Blocks with Some Asset Transfers

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#10516]
See: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fstatemint-rpc-tn.dwellir.com#/explorer/query/0x7d65959208005cfe4295a619a3f0c2344c1d53c02e3c58b04fba49db292433d7

Block https://assethub-polkadot.subscan.io/block/6141506

**Comment by TarikGul** [comment]
rel: https://github.com/polkadot-js/api/issues/5867

**Comment by TarikGul** [comment]
Found the source of the issue, we just need to update apps, and all the upstream packages with the most recent version (patch) of the api that adds the correct typing for `ChargeAssetTxPayment`

**Comment by TarikGul** [comment]
All fixed now.
