### ISSUE TITLE
Bug report - Network>Staking>Payouts - Own Stash not loading

### ISSUE THREAD

**Issue by the-nodelab** [polkadot-js/apps#10512]
Tangle Node v1.0.0
api v11.0.1
apps v0.136.2-3

Running on Windows 11, Brave Browser (shield disabled) - also tried on Edge, Firefox and Chrome and On Brave on an Android device

Network>Staking>Payouts 
When switching to 'Own Stashes' from 'Own Validators' the list of stashes will not load.

I would expect the list of stashes to load up to allow payouts.

**Comment by bee344** [comment]
This is a known issue and is related to #10503 , which is being actively worked on by @TarikGul . The fix is planned to go into the next release. Sorry for the inconvenience.

**Comment by TarikGul** [comment]
Yea this is a general issue I will finish up once I am back from my OOO on May 5th. Bad timing in terms of the runtime upgrade with the all the breaking changes, and my time off...

**Comment by Adamtruong6868** [comment]
yes, we got it for some mainnet and testnet validators

**Comment by farukyasar** [comment]
yes, same issue

**Comment by TarikGul** [comment]
This is fixed via https://github.com/polkadot-js/apps/pull/10552
