### ISSUE TITLE
Staking Interface Not Appearing in SORA

### ISSUE THREAD

**Issue by WRRicht3r** [polkadot-js/apps#10523]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
The Staking view does not appear within the Network menu for the SORA Substrate network. All live networks on Polkadot.js do not have this feature displayed apart from Tangle

* **What is the motivation for changing the behavior?**
Nominators and Validators are unable to access this interface normally, and is affecting validator payouts,

* **Please tell us about your environment:**

  - Version: 0.137.1
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
Duplicate: https://github.com/polkadot-js/apps/issues/10513

**Comment by TarikGul** [comment]
As a note, I will be working on making it backwards compatible when I am back from being OOO.

**Comment by WRRicht3r** [comment]
Thanks I'll follow the original issues
