### ISSUE TITLE
Active Tasks UI

### ISSUE THREAD

**Issue by SBalaguer** [polkadot-js/apps#10547]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
   * Current behavior: Since Cortime is live on Kusama, the distinction between parathreads and parachains is not longer needed. Currently we see teams that have active cores (not part of their legacy leases) as parathreads that constantly produce blocks. This can be seen in the [parathreads tab](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.ibp.network%2Fkusama#/parachains/parathreads) on paraIDs 2015, 2088, 2092, amongst others. The reason why this happens is because the `lifecycle` of  these paraIDs is currently `Parathread` (you can query `paras.parasLifecycle(paraID)` to check this), and that will be the case for every single paraID in the future. 
   * Expected behavior: Clearly differentiate between those paraIDs (tasks) that have an active core and those that don't. A suggestion could be to do the distinction not by querying the `paras` pallet, but rather by querying the `coretimeAssingmentProvider` pallet.

* **What is the motivation for changing the behavior?**
   * Coretime will be the de-facto way of consuming Polkadot cores and this should be shown more clearly.

* **Please tell us about your environment:**
   * Not a bug, this is directly from the UI.

**Comment by TarikGul** [comment]
Once coretime is live on Polkadot, we will replace the parathreads page with a Coretime page. This is the PR that creates that page. https://github.com/polkadot-js/apps/pull/10383

**Comment by SBalaguer** [comment]
Thanks @TarikGul, I also just saw [#10285](https://github.com/polkadot-js/apps/issues/10285) which goes in the same direction as what I said before. I'll close this issue in favor of that one.
