### ISSUE TITLE
Set Identity fails on account page

### ISSUE THREAD

**Issue by Nick-1979** [polkadot-js/apps#10540]
![208014287ea2e17a18eaec463fd4ea5a936550cf](https://github.com/polkadot-js/apps/assets/46442452/db5aa2c1-8571-451e-bbe0-12d43ca10369)

**Comment by tymat** [comment]
```
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

e is undefined
73501/Ge</<@https://polkadot.js.org/apps/page.9fec71c6e501ec4a.js:43:12596
os@https://polkadot.js.org/apps/modu.a73333ada4998f0e.js:2:107879
Bu@https://polkadot.js.org/apps/modu.a73333ada4998f0e.js:2:128003
52967/Cu/<@https://polkadot.js.org/apps/modu.a73333ada4998f0e.js:2:124605
E@https://polkadot.js.org/apps/modu.7c3b262d6289bfdf.js:2:63844
I@https://polkadot.js.org/apps/modu.7c3b262d6289bfdf.js:2:64375
```

Confirmed.

**Comment by Nick-1979** [comment]
I have the same issue when click on the "set identity" on account page as shown below
<img width="1728" alt="Screenshot 2024-05-14 at 10 48 04" src="https://github.com/polkadot-js/apps/assets/46442452/b1045af9-03bb-4ed6-95a0-afc3509de677">
<img width="1728" alt="Screenshot 2024-05-14 at 10 49 38" src="https://github.com/polkadot-js/apps/assets/46442452/15277996-2fd8-4679-90ee-39b6b4089c4a">

**Comment by TarikGul** [comment]
Ahh this issue happens when you try to set an identity to an account which already has an identity attached to it.
