### ISSUE TITLE
Navigating to App -> Settings -> Metadata breaks

### ISSUE THREAD

**Issue by enthusiastmartin** [polkadot-js/apps#10564]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

After new Basilisk's upgrade on Rococo, when loading app tab Settings -> Metadata, if fails with the following error::

`Uncaught error. Something went wrong with the query and rendering of this component.`

In the console:

`code length overflow. (70836>18672)`

You can observe and reproduce the behavior here: [Polkadot.js](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbasilisk-rococo-rpc.play.hydration.cloud#/settings/metadata)

Similar issue: https://github.com/polkadot-js/apps/issues/10334

Based on this bug report - i believe this is similar one.

**Comment by TarikGul** [comment]
Have you tried to decreasing the size of the Basilisk image? That was how the last issue was resolved for Paseo.

**Comment by enthusiastmartin** [comment]
> Have you tried to decreasing the size of the Basilisk image? That was how the last issue was resolved for Paseo.

Looks good to us:

```
subwasm info https://basilisk-rococo-rpc.play.hydration.cloud
🏋️  Runtime size:              1.328 MB (1,392,406 bytes)
🗜  Compressed:                 Yes, 80.23%
✨ Reserved meta:                OK - [6D, 65, 74, 61]
🎁 Metadata version:            V14
🔥 Core version:                basilisk-114 (basilisk-0.tx1.au1)
🗳️  system.setCode hash:               0x676f659a3f4afc527712cc9051c550f00e28738547e80214fc266e2cc611a3bc
🗳️  authorizeUpgrade hash:     0x4afa90bfbbde1f92ee945820f517df670f2040c6c51bd134e35d0db68bb7c8b1
#️⃣  Blake2-256 hash:           0x7dff109135c277975fb1ee357bb172be01e14ffbe099342a0908b0594d764ca5
📦 IPFS:                        https://www.ipfs.io/ipfs/QmX6zAMX3LK2QcECuFEeztNEFKacVU6PibCeCShszE2npD
```

or is it the metadata size that causes an issue ?  I haven't looked at that yet.

**Comment by enthusiastmartin** [comment]
no longer an issue. After upgrading the mainnet, the issue is no longer present.
