### ISSUE TITLE
Extra padding for non-header apps

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#1060]
Goal:

Consistency.

Background:

The spacing looks off where there are apps without a header. The content is too close to the actual tabs. Compare an app with header to one without:

<img width="651" alt="Polkadot:Substrate Portal 2019-04-30 18-30-09" src="https://user-images.githubusercontent.com/1424473/56977725-273af900-6b76-11e9-8215-1c571840ecaa.png">
<img width="648" alt="Polkadot:Substrate Portal 2019-04-30 18-29-28" src="https://user-images.githubusercontent.com/1424473/56977726-27d38f80-6b76-11e9-93dd-a17bcbe20f1f.png">

Actions:

- Adjust for consistent spacing, with or without

**Comment by ltfschoen** [comment]
@jacogr ok to close this?
