### ISSUE TITLE
Faulty example

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#1061]
The `Get chain state Info` example throws:
```
TypeError: blockPeriod.toNumber is not a function
    at eval (eval at Playground.runJs (webpack-internal:///../app-js/src/Playground.tsx), <anonymous>:17:54)
```
![image](https://user-images.githubusercontent.com/738724/56985406-8e61a900-6b88-11e9-92f1-0e7e8b338426.png)

**Comment by chevdor** [comment]
This one as well:
![image](https://user-images.githubusercontent.com/738724/56985528-d97bbc00-6b88-11e9-90ea-e4e8c6925384.png)

**Comment by jacogr** [comment]
Dangit. Those were changed with the timePeriod changes. (And is an option now - however it is deprecated. So should be swapped)
