### ISSUE TITLE
Large increase of polkadot public rpc connections

### ISSUE THREAD

**Issue by stakeworld** [polkadot-js/apps#10620]
- [ ] (Possible) Bug report

Hello polkadot.js devs,

Since a few days (seems started this saturday around 12h) a group of public RPC providers are seeing a large increase in concurrent connections on their servers which sometimes overloaded their connection capacity leading to errors. Of course adjustments are made but we are searching for what is causing this. Could there be an update in polkadot.js (like #10612 , #10616 ?) which introduces an increase in connections from polkadot,.js users?

Also I notice a relatively high number of unavailable chain endpoint in the [issues ](https://github.com/polkadot-js/apps/issues), maybe related?

It happens especially on polkadot and parachains, not on kusama. These are rpc connections on an polkadot-assethub node. A lot of calls are "system_health".
![image](https://github.com/polkadot-js/apps/assets/106294967/63165549-8141-406d-92f5-07ea9f7e2af1)

These are for connections on an active public rpc polkadot node (first graph is connections per second, second is current requests):
![image](https://github.com/polkadot-js/apps/assets/106294967/0de7a13c-5621-430b-b88b-b914e1962cbd)

To be clear, we are not sure it comes from polkadot.js. But since a lot of traffic is coming from polkadot.js it is a likely candidate.

**Comment by TarikGul** [comment]
It is very possible if the RPC providers that are seeing an increase in traffic are Westend People, or Kusama People chains. All identities for relay and system parachains are being queried from the Peoples chains. 

Other than that I am not sure what else from the polkadot.js side could have contributed to the increase.

**Comment by stakeworld** [comment]
I thought of that but the increase seems to be focused on polkadot and parachains, so that doesn't seem to be te case. Thanks for taking a look.
