### ISSUE TITLE
Stop using `system_accountNextIndex`

### ISSUE THREAD

**Issue by bkchr** [polkadot-js/apps#10641]
Pjs should stop using the Rpc and instead switch to the runtime api. The rpc requires that the node is aware of the accountid, which contradicts the "omni node future".

This has one downside, the rpc is adjusting the nonce based on the content in the local transaction pool. However, this will also not really work for light clients as they only keep their own transactions and not external transactions. Users are expected to not use their account from different devices/apps at once.

**Comment by bkchr** [comment]
@TarikGul do you know if there is any way to skip this RPC right now?

**Comment by TarikGul** [comment]
If Im not mistaken this needs to be adjusted in the api layer. I am doing a release of the api tomorrow - It's a must need urgent release. I will try and get this adjusted as well!

If I am not mistaken all that needs to be changed is the rpc call needs to be replaced with the runtime api call?

**Comment by TarikGul** [comment]
Completed via https://github.com/polkadot-js/api/pull/5915
