### ISSUE TITLE
Potentially incorrect calculation of the "reserved deposit" for registering a parachain state and code to use coretime

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/apps#10655]
- [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

When you [Register Parachain State and Code](https://wiki.polkadot.network/docs/learn-guides-coretime-parachains#register-parachain-state-and-code) the Polkadot-JS Apps UI incorrectly calculates the "reserved deposit" as mentioned here
https://substrate.stackexchange.com/questions/11588/how-to-calculate-required-reserved-deposit-to-register-a-parachain-on-kusama-w, which causes the user to experience an error, and then they have to manually try and calculate what reserved deposit they need, which could prevent them from knowing how much KSM they need to register a parachain to use their coretime, which is supposed to be a priority in 2024.

* **What is the motivation for changing the behavior?**

The Polkadot-JS Apps UI currently appears to incorrectly calculate the "reserved deposit" amount that is necessary for users that wants to register their parachain to use coretime, and then gives them a message indicating that they don't have an adequate balance, even if they actually do have a larger transferable balance than the amount they are led  to believe they need for the "reserved deposit" amount.

* **Please tell us about your environment:**

  - Version: 
Parity Polkadot v1.12.0
api v11.1.1
apps v0.138.2-9

  - Environment:
    - [X] Browser - Brave [Version 1.66.110 Chromium: 125.0.6422.60 (Official Build) (arm64)](https://brave.com/latest/)

**Comment by TarikGul** [comment]
I think this is rel: https://github.com/polkadot-js/apps/issues/9988

**Comment by TarikGul** [comment]
Completed via https://github.com/polkadot-js/apps/pull/10671
