### ISSUE TITLE
Incorrect Deposit value displayed - Parathread registration

### ISSUE THREAD

**Issue by DrW3RK** [polkadot-js/apps#10668]
Due to the issue discussed here https://github.com/paritytech/polkadot-sdk/pull/2372 the deposit needed defaults to MAX_CODE_SIZE https://github.com/paritytech/polkadot-sdk/pull/3020

The fee for this transaction is hefty, with around 5 KSM and 40 DOT simply lost because the UI shows a lower value. More info here https://substrate.stackexchange.com/questions/11588/how-to-calculate-required-reserved-deposit-to-register-a-parachain-on-kusama-w

<img width="2166" alt="image" src="https://github.com/polkadot-js/apps/assets/86818441/45ca6a17-f56b-432d-8545-c2779c668714">

**Comment by DrW3RK** [comment]
That is correct.

**Comment by TarikGul** [comment]
Okay, cool thanks for the input, will get this adjusted!

**Comment by DrW3RK** [comment]
On a closer look, the MAX_CODE_SIZE applies only to wasm. The genesis state length can vary. https://github.com/paritytech/polkadot-sdk/blob/ae0b3bf6733e7b9e18badb16128a6b25bef1923b/polkadot/runtime/common/src/paras_registrar/mod.rs#L682
