### ISSUE TITLE
Payout displays eras already paid

### ISSUE THREAD

**Issue by Juanma0x** [polkadot-js/apps#10677]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Payout should only display unpaid, pending staking rewards.

* **What is the motivation for changing the behavior?**

Avoid allowing users to issue extrinsics for reward claims that will fail because the rewards have already been claimed.

* **Please tell us about your environment:**

https://polkadot.js.org/apps/#/staking/payout

  - Version:
Parity Polkadot v1.13.0
api v11.1.1
apps v0.138.2-21

  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

- **Example**:
Random staker: 15rkXKWsDfwPreMDyTyt3riPGkeyj4fvfGeHhkorhqU7MsWQ

Polkadot-JS UI
![image](https://github.com/polkadot-js/apps/assets/120041850/a82f551d-eb94-45be-b4f1-913226cfb727)

[Subscan](https://polkadot.subscan.io/nominator/15rkXKWsDfwPreMDyTyt3riPGkeyj4fvfGeHhkorhqU7MsWQ?tab=reward)
![image](https://github.com/polkadot-js/apps/assets/120041850/87fdacb3-2e3b-4b24-b7a9-df26a856c655)

- Related:
https://github.com/polkadot-js/apps/issues/10513
https://github.com/polkadot-js/apps/pull/10552

**Comment by TarikGul** [comment]
So the issue here is with `RANDOM_STAKER`? It might have to do with this comment [here](https://github.com/polkadot-js/api/issues/5859#issuecomment-2099519074), and if I had to take a guess might be resolved once we pass 84 eras since the breaking changes with staking.

**Comment by Juanma0x** [comment]
> So the issue here is with `RANDOM_STAKER`? [...]

I observed the same issue for any nominator. The `RANDOM_STAKER` is just that, a random nominator I used as an example. You can check the issue using any other nominator.

> [...] if I had to take a guess might be resolved once we pass 84 eras since the breaking changes with staking.

I hope it's solved, as you commented. There are quite a few failed transactions (`alreadyClaimed`) because of it:
- https://polkadot.subscan.io/extrinsic?page=1&time_dimension=date&signed=all&module=utility&call=batch
- https://polkadot.subscan.io/extrinsic?page=1&time_dimension=date&signed=all&module=staking&call=payout_stakers

**Comment by Leouarz** [comment]
It's the same for us at avail, and there's not legacy reward since the chain started after the staking breaking change.

**Comment by dcolley** [comment]
This is still a problem on polkadot:
![image](https://github.com/user-attachments/assets/1cf62a4d-629a-43d1-a48d-4f40b6a91a5f)

**Comment by TarikGul** [comment]
Yes, this is definitely still an issue and since the big breaking changes in staking this is one of the last nits I haven't been able to pin point. I don't have the bandwidth to solve this currently I have assigned it as an open issue that should be tackled in the team. Hopefully it gets picked up!

**Comment by jonasW3F** [comment]
I also just ran into that issue. It would be nice if it could be fixed, because people might spend a lot of fees claiming rewards that are already claimed (there is no error message that the rewards were already claimed).

**Comment by Ank4n** [comment]
I understand that showing unclaimed eras in a backward compatible does not scale well.

**Context**: Previously, we had a single vec of claimed rewards, but with rewards now being paginated, we could not longer store claimed rewards in bounded vector anymore. Currently, they are stored under different keys for each era, which means the UI must now make up to 84 queries instead of just 1 to accurately determine which eras have unclaimed rewards.

Could we instead update UI to display this differently? For example: we could add a button that scans for the last 10 eras at a time?

Additionally, at minimum, before issuing the payout extrinsic, we should check that the era still needs to be paid out to avoid failed fees.

Please refer the runtime api `pending_rewards` ([1](https://paritytech.github.io/polkadot-sdk/master/pallet_staking_runtime_api/trait.StakingApi.html#method.pending_rewards), [2](https://github.com/paritytech/polkadot-sdk/pull/4301#issue-2264329077)).

**Comment by TarikGul** [comment]
If I remember correctly, the biggest issue remains where all the data is coupled and aggregated in the api using the api-derive package - sent to the UI and filtered through a stack of Components.

> Could we instead update UI to display this differently? For example: we could add a button that scans for the last 10 eras at a time?

This could be fine but the above issue still remains, and things need to be heavily decoupled (which I am not sure how it will affect the rest of the functionality).

Im assigning myself to this as a second task for me to get done. For now I am just going to try and track down the bug, and fix it with what we have. IMO it will be a bit easier, and less of a headache.

**Comment by TarikGul** [comment]
Finally have this fixed locally, but it requires a release in the api, which eases the pain in fixing this - so it will be released upstream into apps next week!
