### ISSUE TITLE
Staking Payout Should use `forceBatch`

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#10712]
Right now, the "Payout All" button creates a `batch` of staking payouts. However, if one of them (let's say the first) gets an error (like `AlreadyClaimed`), then the batch stops executing. I don't see any reason that later staking payouts depend on earlier ones in the batch. It'd be better to use `forceBatch` and try them all.

**Comment by rzadp** [comment]
Proposed https://github.com/polkadot-js/apps/pull/10736.
