### ISSUE TITLE
Inconsistent capitalisation of tab menu item names

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/apps#1073]
The vertical position of tab menu items from the top of the page should be same whether there's just a single tab item or if there are multiple tab menu items.

1) Goal: Consistency
2) Background:

app-staking has tabs 'Staking **O**verview' and 'Account **A**ctions', whereas other apps have only the first letter of the first word capitalized, i.e. in app-transfer the tab is 'Balance transfer' instead of 'Balance **T**ransfer'

3) Actions:

* **QUESTION** Establish whether tab menu item titles should only have the first letter of the first word capitalized, or not 
* Adjust for consistent capitalisation of tab menu items across different apps

**Comment by jacogr** [comment]
Staking in the odd man out - so would adjust that to be consistent and read a bit more like a sentence.
