### ISSUE TITLE
"Fork locally" breaks UI completely

### ISSUE THREAD

**Issue by nazar-pc** [polkadot-js/apps#10738]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Try to open https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-0.gemini-3h.subspace.network%2Fws#/explorer or https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-1.gemini-3h.subspace.network%2Fws#/explorer and click "Fork Locally".

Not quite sure what that is, but after that the whole UI turns into blank white screen and I see following in the console:
```
panicked at src/task.rs:131:6:
called `Result::unwrap()` on an `Err` value: RuntimeVersion(RuntimeVersionDecode)

Stack:

we/e.wbg.__wbg_new_abda76e883ba8a5f@https://polkadot.js.org/apps/dyna.51a85f1e8a072e3a.js:2:14711
@https://polkadot.js.org/apps/dyna.51a85f1e8a072e3a.js line 2 > WebAssembly.Module:wasm-function[1118]:0x19865d
@https://polkadot.js.org/apps/dyna.51a85f1e8a072e3a.js line 2 > WebAssembly.Module:wasm-function[1354]:0x1a1281
@https://polkadot.js.org/apps/dyna.51a85f1e8a072e3a.js line 2 > WebAssembly.Module:wasm-function[1234]:0x19dfde
@https://polkadot.js.org/apps/dyna.51a85f1e8a072e3a.js line 2 > WebAssembly.Module:wasm-function[113]:0xb8361
@https://polkadot.js.org/apps/dyna.51a85f1e8a072e3a.js line 2 > WebAssembly.Module:wasm-function[645]:0x17344c
@https://polkadot.js.org/apps/dyna.51a85f1e8a072e3a.js line 2 > WebAssembly.Module:wasm-function[1482]:0x1a2772
se@https://polkadot.js.org/apps/dyna.51a85f1e8a072e3a.js:2:9812
a@https://polkadot.js.org/apps/dyna.51a85f1e8a072e3a.js:2:17978

RuntimeError: unreachable executed
```

This seems to come from Polkadot.js apps itself (likely somewhere in WASM) and possibly caused by the fact that we have an extra field in our `RuntimeVersion` data structure, but it worked before and I don't understand why would it break the whole UI completely.

Opening another tab doesn't help, the only thing that helps is to specify a different endpoint of some chain in URL manually so it "forgets" what it was trying to do.

At very least I would have expected for UI to not break irrecoverably.

* **Please tell us about your environment:**

- Version: apps v0.141.2-1
- Environment:
  - [ ] Node.js
  - [x] Browser
  - [ ] Other (limited support for other environments)

**Comment by TarikGul** [comment]
I don't have a huge in depth knowledge of chopsticks, so I am not completely sure why it is failing. cc @qiweiii 

That being said happy to add a disable option for Fork Locally if that would help.

**Comment by qiweiii** [comment]
Could be need to update its version.

I should add some tests so this can be detected in ci.

**Comment by qiweiii** [comment]
Update chopsticks version did not work, but fortunately local forks still work for other chains. 

May need to take some time to fix this issue. Meanwhile @nazar-pc to recover from white screen, another solution is to remove localFork field in dev tool -> application -> localStorage

So there are 2 things to fix/check

- On chopsticks side, make sure it works for subspace
- on pjs app, make sure local fork failure is recoverable

**Comment by nazar-pc** [comment]
Right, I think that is the smallest issue, we have a completely different consensus that wouldn't work with Smalldot anyway, so disabling that feature for such chains makes sense to me.
