### ISSUE TITLE
Identity (Set_identity) failed

### ISSUE THREAD

**Issue by kaichaosun** [polkadot-js/apps#10745]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
Identity (Set_identity) failed with `CallFiltered`
Set identity should be compatible with latest runtime.

* **What is the motivation for changing the behavior?**

Set identity is a critical features used by the cosystem.

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [x] Other

**Comment by TarikGul** [comment]
Closing since https://github.com/polkadot-js/apps/pull/10747 is merged.
