### ISSUE TITLE
Can't connect account

### ISSUE THREAD

**Issue by claravanstaden** [polkadot-js/apps#10795]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

I cannot see any of my accounts in PolkadotJS, using PolkadotJS or Talisman extension. I have updated my metadata on PolkadotJS and my Chrome extensions, made no difference.I am adding a screenshot here:
![Screenshot 2024-07-31 at 11 00 00](https://github.com/user-attachments/assets/cd45542f-b26a-4679-87f1-d0905cf02318)

I am expecting to see my accounts.

* **What is the motivation for changing the behavior?**

It is not working. It worked well before but after prompting to update my metadata (think it was last week), I can't see my accounts.

* **Please tell us about your environment:**

I am connecting to AssetHub but the same thing happens on the Relay chain on Polkadot.

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser - Chrome 126.0.6478.183 (Official Build) (arm64)
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by IkerAlus** [comment]
I was expecting this to be related to https://github.com/polkadot-js/extension/issues/1416 so only only affecting PJS extension accounts, but I am surprised you also mentioned Talisman.

**Comment by TarikGul** [comment]
When you open up the PJS extension - do you see a `Connected` at the top? - if so can you click on that and confirm your accounts are connected.

**Comment by claravanstaden** [comment]
Ah, that fixed it for me thanks @TarikGul! 🙏🏻 It was `Connected` but my account was not selected.
