### ISSUE TITLE
All nominations show up as "waiting"

### ISSUE THREAD

**Issue by michalisFr** [polkadot-js/apps#10804]
* **I'm submitting a ...**

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Under Staking > Accounts, nominator accounts have all their nominations shown as "Waiting" even though in reality they have "Active" and "Inactive" ones as well. This started after the recent changes to the staking pallet and the `erasStakers` storage items.

<img width="1594" alt="Screenshot 2024-08-05 at 5 06 47 PM" src="https://github.com/user-attachments/assets/583c34f8-580b-49ef-9c4c-6f476a41a940">

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version: apps v0.142.2-10
  - Environment: Chrome Version 127.0.6533.89

    - [ ] Node.js
    - [X] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by LukeWheeldon** [comment]
Affected by this as well. staking.polkadot.cloud shows validators as active, but polkadot.js.org shows as inactive. This has been going on for many weeks, if not months.

**Comment by TarikGul** [comment]
Focus will be put on this soon. Just a little backed up on issues at the moment, but there will be a large focus on apps soon which will help clean up a lot of the hanging fruit that is open for fixing.
