### ISSUE TITLE
Uncaught error. e.call.metadata.metadataAtVersion is not a function (/settings/metadata [Neuroweb])

### ISSUE THREAD

**Issue by AngryCryptocoiner** [polkadot-js/apps#10802]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

When I switch to Neuroweb parachain and go to /settings/metadata I get the following error:

Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

e.call.metadata.metadataAtVersion is not a function
32785/D</<@/apps/page.88ed6e2c7392079b.js:220:3854
os@/apps/modu.a73333ada4998f0e.js:2:107879
Bu@/apps/modu.a73333ada4998f0e.js:2:128003
52967/Cu/<@/apps/modu.a73333ada4998f0e.js:2:126743
Cu@/apps/modu.a73333ada4998f0e.js:2:126808
uu@/apps/modu.a73333ada4998f0e.js:2:120564
$o@/apps/modu.a73333ada4998f0e.js:2:61292
52967/ou/<@/apps/modu.a73333ada4998f0e.js:2:117969

* **What is the motivation for changing the behavior?*** 

I can't send NEURO because of it.

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
I have a fix working for this - it will be addressed soon.

**Comment by TarikGul** [comment]
The extension just needs to be released before I can update this which will be today. Then I can do the necessary updates to ensure all the deps are aligned

**Comment by AngryCryptocoiner** [comment]
This error is still present when trying to send NEURO (this must be the case since they haven't implemented the new ledger app). 

Here's console output:
Signing with Ledger address [REMOVED]
```
comm.37b5596646059060.js:4119 signAndSend: error: TypeError: this[#r].call.metadata.metadataAtVersion is not a function
    at k.getMetadataProof (comm.37b5596646059060.js:4088:3258)
    at k.signPayload (comm.37b5596646059060.js:4088:3888)
    at async r.__internal__signViaSigner (modu.25323ea2adf9f61f.js:1:110702)
    at async modu.25323ea2adf9f61f.js:1:109301
```

So there must some warning or more human readable error. Btw, I added this wallet using "From Ledger" button (I have also one address on the extension)

```
WS endpoint= wss://neuroweb-rpc.dwellir.com
modu.25323ea2adf9f61f.js:1 web3Enable: Enabled 1 extension: polkadot-js/0.51.1
modu.25323ea2adf9f61f.js:1 web3Accounts: Found 2 addresses
comm.37b5596646059060.js:1 chain: NeuroWeb (Live), {"isEthereum":false,"ss58Format":101,"tokenDecimals":[12],"tokenSymbol":["NEURO"]}
comm.37b5596646059060.js:1 derive.staking.account :: Error: Unable to find api.derive.staking.account
    at i (modu.08fd18b367b90613.js:2:431555)
    at h.getApiMethod (comm.37b5596646059060.js:1:9038)
    at h.subscribe (comm.37b5596646059060.js:1:9473)
```

**Comment by TarikGul** [comment]
Yea I would say that is expected because for the checkMetadataHash to work in needs the V15 metadata which is accessed through `call.metadata.metadataAtVersion` that being said, I think the error handling here could definitely be imrpoved.
