### ISSUE TITLE
dotapps.io is redirecting to 'https://dotapps-io.ipns.dweb.link/' but it's not working

### ISSUE THREAD

**Issue by Polkadot-is-dead** [polkadot-js/apps#10811]
@TarikGul

#10810

Is this fucking nonsense for you, grifter?

**Comment by TarikGul** [comment]
<img width="1581" alt="Screenshot 2024-08-07 at 6 26 09 AM" src="https://github.com/user-attachments/assets/102b4c37-99ed-4108-bfa5-4f341051ac9a">


?
