### ISSUE TITLE
Clicking on "yay" actually makes you vote "nay"

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1083]
on Substrate, didn't try on Alexander you can see in the modal and on the graph:
![](https://i.imgur.com/LSFrmkS.gif)

**Comment by jacogr** [comment]
Sheiße, introduced here and I must have been drunk when I checked -  https://github.com/polkadot-js/apps/pull/1023/files#diff-9ea1956c2d649bb9a8d2369b24f39afaR31

The good news is that it is a simple fix, swap the 0 and -1
