### ISSUE TITLE
Set identity option missing on the accounts tab

### ISSUE THREAD

**Issue by btwiuse** [polkadot-js/apps#10868]
I'm submitting a 

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

The accounts tab on [Vara Network](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.vara.network#/accounts) used to provide the option to set onchain identity, but now the option is gone:

![image](https://github.com/user-attachments/assets/0dbf3b51-5986-45e0-8506-b982140002a4)

The identity pallet has been part of the Vara Network runtime since day one.

  - Version: api v12.4.2 / apps v0.143.3-5
  - Environment: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.vara.network#/accounts

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
PR to fix the issue is up: https://github.com/polkadot-js/apps/pull/10869

Having identity switch from the relay to the people chain has brought some bumps in the road, so apologies for any inchonvieneces.
