### ISSUE TITLE
Teleport amount input buggy on Kusama

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#10864]
- [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Type `1` in the field and the following shows up:
<img width="661" alt="image" src="https://github.com/user-attachments/assets/f6d7a88e-f6ef-4633-9052-20b7034c459b">

Type `10<bs>` and the following shows up:
<img width="661" alt="image" src="https://github.com/user-attachments/assets/9f064431-7005-433d-a07e-c9543f56521d">

* **What is the motivation for changing the behavior?**

Being able to use teleport.

* **Please tell us about your environment:**

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.dwellir.com#/extrinsics

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by chevdor** [comment]
"Send funds" shows the same buggy behavior.

**Comment by chevdor** [comment]
Same issue in developer/extrinsic.

**Comment by ShankarWarang** [comment]
Looks like all the chains are affected by this bug. 
If 'n' is the decimals of a specific chain, hitting backspace/ delete key after entering any value for token transfer/teleport, it adds (n-1) times 0s in the input field.

**Comment by TarikGul** [comment]
Yea I can confirm this is an issue! Looking into it now.

**Comment by TarikGul** [comment]
Caused by https://github.com/polkadot-js/apps/pull/10862

Reverting.
