### ISSUE TITLE
Kusama accounts showing incorrect amount of KSM

### ISSUE THREAD

**Issue by laboon** [polkadot-js/apps#10907]
I have tried this on several different endpoints and get the same result. It appears to only happen on Kusama, not Polkadot.

The majority (surprisingly, not all) of my accounts are showing much more KSM than I actually have. Specifically it is showing 1000x as much which makes me think this is a decimal placement issue. For example, this account has 0.509 KSM ( https://kusama.subscan.io/account/J9eWsRZZMJRKzfNjvq77PxoiBj5W7mZzyegBSxTf6PyYbJ7 ). However, Polkadot-JS App shows it having 509.5167 KSM.

<img width="637" alt="Screenshot 2024-09-10 at 15 10 35" src="https://github.com/user-attachments/assets/22b6eb8b-3003-4d14-90cf-93329294a41f">

**Comment by laboon** [comment]
All elements (e.g. transferrable, locked for referenda, etc.) also show up as 1000x the amount but the tooltip shows the correct amount.
![Screenshot 2024-09-10 at 15 13 47](https://github.com/user-attachments/assets/14821812-8fb4-48a6-9d56-3b4f43fa7822)
![Screenshot 2024-09-10 at 15 13 51](https://github.com/user-attachments/assets/82d99faa-4338-49dc-8cb0-83419d873754)

**Comment by TarikGul** [comment]
Thanks for reporting this, I will check this today. I'll try and confirm this with my KSM accounts in a second. Are you using the IPFS version or polkadot js org version?

**Comment by laboon** [comment]
@TarikGul Thanks for looking into it so quickly. I am using the polkadot js org version.

Radha has checked and it is the same issue for him - some accounts show normally, others show as 1000x.

**Comment by TarikGul** [comment]
Okay I can confirm it is doing the same thing for me!

I will get this fixed shortly!

**Comment by michalisFr** [comment]
Another case is where transferable and total is correct, but locked is 1000x (although the tooltip shows the correct 0.2 KSM)
<img width="266" alt="Screenshot 2024-09-10 at 4 42 54 PM" src="https://github.com/user-attachments/assets/0bdf40a0-4a71-43f6-9487-0820ddb1822a">

**Comment by TarikGul** [comment]
Yea I just found the source of the issue!
