### ISSUE TITLE
[NEUROWEB] 1011: Unknown Transaction Validity: UnknownTransaction::CannotLookup (Ledger account)

### ISSUE THREAD

**Issue by AngryCryptocoiner** [polkadot-js/apps#10905]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

When I switch to Neuroweb and connect my ledger using "From Ledger" button (I can't do it using polkadot js extension since there's no Neuroweb network in the option list when connecting ledger) I'm trying to send NEURO and get this error (in the right top corner) after signing transaction: "1011: Unknown Transaction Validity: UnknownTransaction::CannotLookup". I updated metadata and such and still get the error.

* **What is the motivation for changing the behavior?**
I can't send or unvest NEURO tokens.

* **Please tell us about your environment:**

  - Version:
NeuroWeb v1.5.0
api v12.4.2
apps v0.143.3-21

  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by Khan-arsh** [comment]
@AngryCryptocoiner Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by TarikGul** [comment]
Hmm, not exactly sure what the issue is. Is neuroweb using the metadataHash as part of the runtime? Are you using the Generic App, Migration App, or Legacy app?

**Comment by AngryCryptocoiner** [comment]
> Hmm, not exactly sure what the issue is. Is neuroweb using the metadataHash as part of the runtime? Are you using the Generic App, Migration App, or Legacy app?

Sure it is: https://dashboards.data.paritytech.io/metadata.html ({'id': 553, 'type': {'path': ['frame_metadata_hash_extension', 'CheckMetadataHash'], 'params': [{'name': 'T', 'type': None})
I'm using Generic App 100.0.8 
Are you not able to reproduce the issue?

**Comment by AngryCryptocoiner** [comment]
Now the error is gone. The problem was they hadn't completely rolled out the ledger support.
