### ISSUE TITLE
Matrix handle and other identity fields not shown in PJS-UI

### ISSUE THREAD

**Issue by michalisFr** [polkadot-js/apps#10927]
* **I'm submitting a ...**

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

It seems that after the migration of identities to People chain the Matrix handle in the identity is not shown in the sidebar when clicking on an account. 

This could be further improved by showing all identity fields that have a value.

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version: apps v0.143.3-30, Chrome Version 129.0.6668.59
  - Environment:

    - [ ] Node.js
    - [X] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by piggydoughnut** [comment]
Great catch 😊  Will investigate 🤓

**Comment by piggydoughnut** [comment]
Will be fixed with this https://github.com/polkadot-js/apps/pull/10959

**Comment by piggydoughnut** [comment]
The fix is deployed 🚀
