### ISSUE TITLE
[Contracts - Call] Page must be refreshed after call to make different message call 

### ISSUE THREAD

**Issue by laboon** [polkadot-js/apps#1093]
DESCRIPTION:
After calling a message and seeing the success of the extrinsic, the page does not refresh.  One would think that one could make a different call by selecting the pulldown to a different message, based on the UI display.  However, a second call of the original type will be made.

A workaround is available, see below.

REPRODUCTION STEPS:
Load the sample "Flipper" app (from the Substrate Contracts workshop)
Navigate to [Contract-Calls]
Make a "get" call
Do not refresh page
Select "flip" from message pulldown - do not modify any other page data
Make a "flip" call

EXPECTED BEHAVIOR:
Makes a "flip" call.

OBSERVED BEHAVIOR:
Makes a "get" call.  This can be confirmed by seeing the following output in the logs:
Runtime: Storage Value: false 

(Note: Storage Value may be true or false depending on if state was successfully flipped earlier)

WORKAROUND:
Refresh page after every contract call.

**Comment by jacogr** [comment]
Fix already done and incoming in #1092
