### ISSUE TITLE
Paseo Relay Chain is not showing identities.

### ISSUE THREAD

**Issue by hbulgarini** [polkadot-js/apps#10955]
Hello! 

We have migrated all the identities to PeopleChain and we have also make the necessary changes on the testingRelayPaseo.ts endpoint but we are still not able to see the identities displayed from PolkadotJS Apps:

https://github.com/paseo-network/apps/blob/7dfd1109333ee5334a12743c1eb3af9e3dc651d6/packages/apps-config/src/endpoints/testingRelayPaseo.ts#L256

We would appreciate some help in debugging the configuration to see if there is anything missing.

**Comment by piggydoughnut** [comment]
Hi @hbulgarini !

It looks like its a tiny naming issue 😅 
Will be solved after merging this https://github.com/polkadot-js/apps/pull/10973

**Comment by piggydoughnut** [comment]
Closing, as the fix has been deployed

**Comment by hbulgarini** [comment]
hey @piggydoughnut ! indeed it was small but not quite easy to find! thank you very much :)
