### ISSUE TITLE
Error on connection to `LAOS` networks

### ISSUE THREAD

**Issue by asiniscalchi** [polkadot-js/apps#10954]
all `laos` network are experiencing the following error on connection:
```
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

createType(AccountId):: Invalid AccountId provided, expected 32 bytes, found 20

Error: createType(AccountId):: Invalid AccountId provided, expected 32 bytes, found 20
at o (https://polkadot.js.org/apps/modu.6724c4c4ec0fc7a7.js:1:87040)
at J.createType (https://polkadot.js.org/apps/modu.d704469d4359a33d.js:2:48759)
at Array.<anonymous> (https://polkadot.js.org/apps/comm.bf3973086a259e8c.js:693:1230)
at D (https://polkadot.js.org/apps/comm.bf3973086a259e8c.js:693:1820)
at P (https://polkadot.js.org/apps/comm.bf3973086a259e8c.js:693:2176)
at https://polkadot.js.org/apps/comm.bf3973086a259e8c.js:743:195
at Object.zi [as useState] (https://polkadot.js.org/apps/modu.bd8f3266470441f0.js:2:80363)
at https://polkadot.js.org/apps/modu.bd8f3266470441f0.js:2:223782
at https://polkadot.js.org/apps/comm.bf3973086a259e8c.js:743:189
at _i (https://polkadot.js.org/apps/modu.bd8f3266470441f0.js:2:77446)
```

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Flaos-rpc.dwellir.com#/accounts
![image](https://github.com/user-attachments/assets/5250ca7b-9605-4e00-a763-4abd298bc862)

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.laossigma.laosfoundation.io#/accounts
![image](https://github.com/user-attachments/assets/411f23b9-2223-4855-be59-4318c2b560ec)

**Comment by asiniscalchi** [comment]
it seems it's the **api** the problem:
I run locally polkadot.js and it works with the following:
![image](https://github.com/user-attachments/assets/113d5072-20ba-460b-b77d-652687e63b30)

but the one published is not working with:
![image](https://github.com/user-attachments/assets/1cc47333-f36a-48d7-85db-3ed8e51f8aef)

---
So it seems 
v10.12.6 working.
**v13.2.1 not working**.

**Comment by asiniscalchi** [comment]
find out that we are missing some metadata LAOS side:
`2024-09-26 11:26:37 PORTABLEREGISTRY: Unable to determine runtime Call type, cannot inspect sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic
`

**Comment by asiniscalchi** [comment]
the error was exposed by this delta : https://github.com/polkadot-js/api/compare/v13.0.1...v13.1.1

It should be the usage of metadata V15.

**Comment by piggydoughnut** [comment]
Thank you for such a great debug 🙏🏽 The update to [v15 is in the works](https://github.com/polkadot-js/api/pull/5987). So hopefully soon all will be 🚀  😊

**Comment by asiniscalchi** [comment]
Hi @piggydoughnut is there any tool that could check if our metadata is correct ?
I really scared that the problem is our side but I dunno how to verify it.

**Comment by piggydoughnut** [comment]
Hey @asiniscalchi, sorry for delay, this will solve crashing explorer - https://github.com/polkadot-js/apps/pull/10967 Should be up soon.

Investigating the format issue now.

**Comment by tonimateos** [comment]
![image](https://github.com/user-attachments/assets/fbc528c0-8c4f-4788-886e-cc13e8fcc680)
![image](https://github.com/user-attachments/assets/bab93a67-e020-4dff-b72d-17d822a91d8a)
![image](https://github.com/user-attachments/assets/2ba59700-d788-4ce1-8c67-7af042d14624)

Hi @piggydoughnut, thanks for your help on this issue! The patch solved the crash issue. In case it helps, these are the final issues still remaining:

- impossible to add an H160 address in the address-book tab (see screenshot, the save button is always disabled)
- balances not shown (see screenshots)

Let us know if there's anything we can help with. The LAOS team would definitely prioritise helping.

Thanks!
Toni

**Comment by piggydoughnut** [comment]
Hai @tonimateos  !
Thanks a lot for providing the information about the other issues - it certainly helped :) 
All the fixes are pushed now, everything should work fine after the next api deployment which should be soonish (2 weeks max)

P.S. Here are sneak peeks of the fixes 😉 

<img width="995" alt="Screenshot 2024-10-01 at 20 38 55" src="https://github.com/user-attachments/assets/8091a58e-01f9-402e-a9f8-f22eb816966f">


<img width="1401" alt="Screenshot 2024-10-01 at 20 38 31" src="https://github.com/user-attachments/assets/ce8243d4-c17b-42a7-8e4b-2191c675f57d">

**Comment by asiniscalchi** [comment]
Hi @piggydoughnut , I just realized the new version was deployed and the parsing of the addresses seems to be fixed.
However another problem arised: Subwallet and Talisman are unable to sign transaction and fail with the following error:
![image](https://github.com/user-attachments/assets/28313837-6f15-42ef-89e9-80e163284368)
-----
- Is a problem from their side?
- Why the other H160 parachians ( Moonbeam, Darwinia ) do not have this kind of behavior ? What's different by our side ?

**Comment by piggydoughnut** [comment]
@asiniscalchi I suspect it is still on our side, will check and let you know asap.

**Comment by TarikGul** [comment]
Hey @asiniscalchi 

We found the source of the issue. To get straight to the point, the most straightforward solution would be if Laos adds the runtime api metadata to V15 Metadata. 

The issue is that there is a runtime call [here](https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/tx/signingInfo.ts#L33) being called in the api when signing happens. Laos has support for it, but because  its not in the metadata it requires the api to use the hardcoded generation [here](https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/system/runtime.ts#L15) which resolves to using `AccountId` which is `Accountid32`.

**Comment by asiniscalchi** [comment]
We'll code an hotfix as soon as possible.
Thanks a lot for your help.

**Comment by asiniscalchi** [comment]
We have a fix: 
https://github.com/freeverseio/laos/pull/821

**Comment by asiniscalchi** [comment]
hotfix deployed in LAOS mainnet ... all is working. Thanks for the help.
