### ISSUE TITLE
[Contracts] - Doesn't Navigate to Instantiate After deploy

### ISSUE THREAD

**Issue by yjkimjunior** [polkadot-js/apps#1096]
on polkadot.js.org and with substrate-ui.parity.io, connected to dev chain.

**expected**
After deploying a contract, a new tab to instantiate should appear, prefilled with latest deployed contract information.

**actual**
nothing happens

**Comment by jacogr** [comment]
Certainly cannot replicate after fixes for https://github.com/polkadot-js/apps/issues/1037 went in this morning.

**Comment by jacogr** [comment]
(substrate-ui.parity.io has not been deployed yet, only apps - the former will only be much later today)

**Comment by yjkimjunior** [comment]
🧠💨
