### ISSUE TITLE
Transferable balance includes reserved balance allowing users to spend their reserved balance

### ISSUE THREAD

**Issue by the-nodelab** [polkadot-js/apps#10987]
I'm submitting a Bug report

The transferable balance shown includes the reserved balance (which should be locked and non-transferable), allowing a user to sign transactions that put their transferable balance below the reserved balance, stopping them from signing any future transactions (until they bring the transferrable balance back above the reserved balance).

Instead, change the transferable balance to exclude the reserved balance.

This will stop users from accidentally transferring coins that put their transferable balance below the reserved balance and locking them out of signing transactions (as there is no balance for fees)

api v13.2.1
apps v0.144.2-11

Running on Brave Browser (shields off)

**Comment by TarikGul** [comment]
The formula and changes on the api level were reflected in this PR: https://github.com/polkadot-js/api/pull/5957 which does take into account the reserved, so it might be an issue on the UI side. But I will double check these values.

**Comment by TarikGul** [comment]
The transferable balance does not show the reserve as seen below:

<img width="413" alt="Screenshot 2024-10-30 at 5 34 59 PM" src="https://github.com/user-attachments/assets/29693b16-0add-4843-942c-02438221df29">

Same with the UI for sending a transfer.
