### ISSUE TITLE
Treasury Page No Longer Available

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/apps#11031]
Currently with the most recent calls that have been removed from runtime 1003003 (ex: `tx.treasury.proposeSend`), it has caused the treasury page from no longer being available since app routing requires the above example tx. 

In addition to that, there is a weird issue currently where when I get the page up and running again, it fails to persist the data it originally gets. For example, it will get all the proposals and render them correctly, but on the next subscribed call it makes it gets back no data, and empties the page of all proposals. I can't narrow down the issue exactly just yet, but it feels like to me it somehow is hitting: https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/treasury/proposals.ts#L97-L101

That being said, `const totalProposals = useCall<BN>(api.query.treasury.proposalCount);` is also returning zero which is incorrect.

**Comment by sesh92** [comment]
@TarikGul 

This change breaks chains that do not have treasury pallet.

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fexplorer-rpc-ws.mainnet.stages.humanode.io#/treasury

<img width="1434" alt="image" src="https://github.com/user-attachments/assets/d5032efa-df3b-47ae-a4ba-92fcadc9ff18">
