### ISSUE TITLE
Cannot run it on Firefox

### ISSUE THREAD

**Issue by weezy20** [polkadot-js/apps#11065]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
Firefox should be able to run apps on `master`. It runs on chrome based browsers but on firefox I get uncaught runtime exceptions.
![image](https://github.com/user-attachments/assets/15b93740-20e6-4b02-a94b-a3fedbd577c1)

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**
Using on Ubuntu 24.10 and Firefox version 132.0

I have used this on Edge and Chrome and it works without issues. I build it using yarn.
  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
> Firefox should be able to run apps on master

Everything works fine for me locally, maybe its a cache issue etc but you can also just exit out of that error and continue your dev environment. Its in no way a blocker.

**Comment by weezy20** [comment]
@TarikGul wdym exit out of that error? I'm trying to locally run it using `yarn` and when I open `localhost:3000` on both chrome and firefox, chrome runs fine but my firefox shows this. For sanity check I reverted to commit 315781ea30 and am able to use it on firefox as well. So maybe some recent commit might've introduced some sort of incompatibility.

**Comment by weezy20** [comment]
I think you were right about the cache. Something was wrong on my end. After reverting back to master from the aforementioned commit I was able to use it on Firefox with latest head.
