### ISSUE TITLE
Staking page broken?

### ISSUE THREAD

**Issue by bkchr** [polkadot-js/apps#11061]
![image](https://github.com/user-attachments/assets/a6a72241-6c4b-42a6-9967-670461adc41e)

It only shows `0/500` validators. When opening the page it first showed 499/500, but then switched to 0. Also the list of validators is not loading. The ERA information on the right side also looks like something is off?

**Comment by TarikGul** [comment]
Okay so the source of the issue seems to be this upstream PR in the api: https://github.com/polkadot-js/api/pull/5997

Looking into it!

**Comment by radiumb** [comment]
FYI the issue is seen in kusama staking page too so probably many other chains too

**Comment by TarikGul** [comment]
This would affect every staking page. We found the source of the issue - going to add it to the api then apply the changes here.

**Comment by radiumb** [comment]
Wonderful, we came across this issue when we were doing some infrastructure upgrades and noticed this issue with our endpoint  as a part of our qualification steps. We first worried it was something on our end but then noticed its pervasive and rpc provider agnostic hence pinged @bkchr .

**Comment by TarikGul** [comment]
Nice, well thank you for identifying. As back story we discovered some long standing memory issues as part of the RPC infrastructure in PJS as part of some tech debt. So we are aiming to improve it - there was one issue with the default capacity that was applied in the rpc-core in the api. So as a patch I am going to increase it but then also add an api option to increase it based on the client or users needs (basically an escape hatch)

**Comment by TarikGul** [comment]
This is fixed, and pushed to polkadot.js.org/apps
