### ISSUE TITLE
Pending payouts are not displayed in the payout page

### ISSUE THREAD

**Issue by Leouarz** [polkadot-js/apps#11071]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Pending payout should be displayed in the payouts tab.
Few weeks ago, the payout section was showing eras already paid. This issue was tracked [here](https://github.com/polkadot-js/apps/issues/10677)
It was recently closed, as a fixed was pushed and deployed.
Now no eras is shown in the payout page.

Before the fix, the bug was indeed there, eg. in here, eras 212 and 215 are already claimed and still showing:
![image](https://github.com/user-attachments/assets/b40febbf-4ffc-4223-8c7c-5e929e215698)

After the fix, no era is displayed:
![image](https://github.com/user-attachments/assets/e6ddccb2-7d42-472c-9dae-32c932c1c9fe)

In comparison, in the staking dashboard, we have this:
![image](https://github.com/user-attachments/assets/3b59cd3a-1507-42d7-b556-5937f67be59c)

To reproduce, here is the required data on Avail testnet:
- RPC: wss://turing-rpc.avail.so/ws
- Account used (a random nominator with pending payouts): 5CDGXH8Q9DzD3TnATTG6qm6f4yR1kbECBGUmh2XbEBQ8Jfa5
- Our fork of the explore with the old version: https://explorer.avail.so/#/staking/payout
- The recently updated official explorer: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fturing-rpc.avail.so%2Fws#/staking/payout
- Our fork of the staking dashboard: https://staking.avail.tools/#/nominate

Don't hesitate in case you need any other information.

* **What is the motivation for changing the behavior?**

Allowing users to claimed some era rewards or all of them.

* **Please tell us about your environment:**

  - Version:
    - API: v14.2.3
    - Apps: v0.145.2-15
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
Interesting, must be a parsing issue in apps. The api now returns a `isClaimed` field in each of the rewards. I will check this out.

**Comment by the-nodelab** [comment]
This is also happening with the Tangle RPC (wss://rpc.tangle.tools).
Example account is tgGv1ckHJRCzpggcPyZxeyK2T9PugDogZSd9X9q4jFWWZLVJS

**Comment by TarikGul** [comment]
Thank you @Leouarz for the extra info - it definitely helped narrow it down faster. The problem was indeed that line. PR in the api: https://github.com/polkadot-js/api/pull/6026

Hopefully this will resolve the issue! I need to release it in the api first then propogate it to apps later in the week.

**Comment by Leouarz** [comment]
Hey @TarikGul, just tested the changes by applying them manually, they seem to work as expected, thank you ! Waiting for the release.
