### ISSUE TITLE
Polkadot JS GUI doesn't disable "validate/nominate" button when being validator

### ISSUE THREAD

**Issue by talfco** [polkadot-js/apps#1108]
My validator is in validating mode (shown in the stacking tab) but the Account Actions Tab, shows it as non-validating and shows the Validate- and Nominate button. This glitch was first seen today 8.5.2019. Telemetry and Validator log looks fine.
![image](https://user-images.githubusercontent.com/1431626/57380910-2d4e5c80-71aa-11e9-9749-cb0e898ae823.png)

**Comment by Stefie** [comment]
That should also be fixed with the latest API version, it was also broken because of the missing linked map support. 
![Screenshot 2019-05-08 at 16 26 26](https://user-images.githubusercontent.com/125398/57384075-33473c00-71b0-11e9-8b57-abc07d2f8568.png)

**Comment by Tbaut** [comment]
I can confirm it's solved live (on polkadot-js.org) for me :)
