### ISSUE TITLE
Event data is not updating

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/apps#1114]
I created a simple "adder" module to show the error here.

This module simply adds one to a number and emits an event with the new number.

```rust
use support::{decl_module, decl_storage, decl_event, StorageValue, dispatch::Result};
use system::ensure_signed;

pub trait Trait: system::Trait {
	type Event: From<Event<Self>> + Into<<Self as system::Trait>::Event>;
}

decl_storage! {
	trait Store for Module<T: Trait> as TemplateModule {
		MyNumber get(my_number): u32;
	}
}

decl_module! {
	pub struct Module<T: Trait> for enum Call where origin: T::Origin {

		fn deposit_event<T>() = default;

		pub fn add_one(origin) -> Result {
			let who = ensure_signed(origin)?;

			let my_number = Self::my_number();
			let my_new_number = my_number.checked_add(1).ok_or("Overflow")?;

			<MyNumber<T>>::put(my_new_number);
			Self::deposit_event(RawEvent::NewNumber(my_new_number, who));
			Ok(())
		}
	}
}

decl_event!(
	pub enum Event<T> where AccountId = <T as system::Trait>::AccountId {
		NewNumber(u32, AccountId),
	}
);
```

When I call this function multiple times, I get multiple events, but the data in the events are not updated:

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/1860335/57457399-c1cec280-726f-11e9-8cc8-fb2f845088ab.png">

If I refresh the page, and then call the event again, I get the right number... but then that value repeats...

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/1860335/57457556-065a5e00-7270-11e9-94ce-396e0923ccdf.png">

Let me know if you need help reproducing.

**Comment by jacogr** [comment]
Also happens with something simple such as sessions on a dev chain.

<img width="425" alt="Polkadot:Substrate Portal 2019-05-12 08-43-18" src="https://user-images.githubusercontent.com/1424473/57578722-0d60b680-7492-11e9-8d1c-c40e7d771075.png">

**Comment by jacogr** [comment]
Bumped to P1, since same-type events were _always_ displayed with the wrong info.
