### ISSUE TITLE
Add all dev account for dev and local chains

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#1117]
Currently, running a local chain, I see in the UI the following accounts:
![image](https://user-images.githubusercontent.com/738724/57477349-cb205500-7298-11e9-89b7-44d95b881d62.png)

Ideally, it should also contain the Stash and Session for Charlie, D, E and F.

While probably not really an issue on `--dev`, this is especially useful on `--chain local` in order to test validators coming in and out. Bringing either Alice or Bob is risky and stops the chain.

Tested on:
![image](https://user-images.githubusercontent.com/738724/57478387-0cb1ff80-729b-11e9-956d-c6494e3c3721.png)

**Comment by jacogr** [comment]
TL;DR Make sure the "Development" seed type is also available on `--local`

**Comment by chevdor** [comment]
In the meantime, if needed here are the missing pieces:
- seed is always `bottom drive obey lake curtain smoke basket hold race lonely fit walk`
- Bob Stash:  sr25519 / `//Bob//stash`
- Bob Session: ed25519 / `//Bob` 
- ...

**Comment by jacogr** [comment]
So I am confused - don't you have the "Development" option for `--chain local` chain? I certainly do -

<img width="1440" alt="Polkadot:Substrate Portal 2019-05-10 16-56-00" src="https://user-images.githubusercontent.com/1424473/57536484-936ee700-7344-11e9-8581-dba4a58a4ed0.png">

I'm not overly excited to add all the sessions and all the stashes to the addresses. They are easy to add (once-off with the above option) and for the most part will just add more. Possibly could look at `//Bob//stash` and maybe the session for the first one (or two), but not much more than that.

**Comment by chevdor** [comment]
I don´t see it as a critical issue now that I know how to add them. Feel free to just close if you think not adding them is in the interest of the users (the devs in that case).

You can see it for yourself using:
`wget https://gist.githubusercontent.com/chevdor/be461d11c56baecb0e7bbcb920e964fb/raw/855b75b18a2e8f05b19633b2bbd8f00887aa9300/dcp-polkadot-5nodes-ui.yml -O /tmp/dcp-local.yml && docker-compose -f /tmp/dcp-local.yml up --force-recreate` and opening http://localhost:80/

**Comment by jacogr** [comment]
Ok, so back to my question - do you have the "Development" option in the seed type selection? (It is relatively new, but since you have built very recently, it _should_ be there)

**Comment by chevdor** [comment]
Yes it is there

**Comment by jacogr** [comment]
Ok, still pondering - leaning towards adding alice_session & bob_stash as a more expansive array of accounts to https://github.com/polkadot-js/common/blob/master/packages/keyring/src/testing.ts#L13

(But there is obviously a fine line between being useful to 99.9% and spamming with too much - just trying to find that balance, since it is easy to add any additional accounts via the `Development` seed setting)
