### ISSUE TITLE
JS app needs some layout improvement

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#1120]
![Screen Shot 2019-05-10 at 1 54 01 PM](https://user-images.githubusercontent.com/1201310/57497345-66620a80-732b-11e9-8d6d-fcec37e69ac8.png)

The buttons are blocking me

**Comment by jacogr** [comment]
Suggest moving the buttons out of the content areas. (We lose some vertical space, but in most cases the scripts are on the smaller side.)

**Comment by Stefie** [comment]
@xlc I can have a quick look

**Comment by xlc** [comment]
Fixed by #1128
