### ISSUE TITLE
Democracy app crashes on Referendum vote

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1121]
Using a somewhat old substrate node and master
```
Uncaught TypeError: vote.ltn is not a function
at democracy_referendumVotesFor.reduce.voteCount (Referendum.tsx?98e4:60)
```

How to reproduce (happened to @Stefie but disappeared magically):

- submit a proposal (in my case with Extrinsic but shouldn’t matter if "Submit proposal" is used)
- in democracy vote on the referendum
- it crashed on click on `yay` or `nay`

**Comment by jacogr** [comment]
Probably causes by this - https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/democracy/votes.ts#L17

Why? No idea.

**Comment by jacogr** [comment]
Re-open if the API fix does not solve.

**Comment by Stefie** [comment]
Hmm, not sure if that was the cause. I had the same error message yesterday, checked it on @kwingram25 's and @Tbaut 's computer with the latest apps master and the error didn't occur. It didn't show up on my computer anymore after I made a completely fresh install of apps and API...

But if that solves the issue, we really need to optimize our API testing procedure...
