### ISSUE TITLE
False negative to verify signatures for sr25519 accounts

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1126]
Either I haven't understood the concept, or something's not right here:

in `/#/toolbox/sign`
- using `Alice`
- data: `bla`
- signature: `0x789751a608ad71...`

Now delete and type `bla` again --> the signature is now totally different.
I would expect to have the same signature for the same message.

Verifying the signature tells it's not signed from `Alice` either.

edit:
the different signature for the same message is expected but the verify signature should work.

**Comment by jacogr** [comment]
Expected. sr25519 signatures are non-deterministic.

**Comment by jacogr** [comment]
Yeap, bug - it always used ed25519 to verify

https://github.com/polkadot-js/apps/blob/master/packages/app-toolbox/src/Verify.tsx#L140

For those, it should just use the keypair verify function (like it does on sign).

**Comment by Tbaut** [comment]
Thanks modifying the title and overall message as the signing isn't the problem.

**Comment by jacogr** [comment]
Ahhh, dangit. So, this is the issue -

- for built-in accounts, it can use the keypair verify 
- for addresses, it cannot do that.

So what I'm suggesting here -

- verify via sr25519 (which we don't do), if fine, show ok and do nothing more
- verify via ed25519, if fine, show ok
- show error if none of the above 2 passes
