### ISSUE TITLE
Voting in a referendum causes white screen crash

### ISSUE THREAD

**Issue by kwingram25** [polkadot-js/apps#1129]
![Screenshot from 2019-05-10 13-46-05](https://user-images.githubusercontent.com/879755/57525433-010e1980-732b-11e9-9c41-026dc3d0947a.png)

![Screenshot from 2019-05-10 13-54-31](https://user-images.githubusercontent.com/879755/57525491-2b5fd700-732b-11e9-87e3-708a93bf93f8.png)

**Comment by jacogr** [comment]
Pull master, `yarn install`, retry.

**Comment by kwingram25** [comment]
Seems fixed!
