### ISSUE TITLE
Error when opening `nominate` modal

### ISSUE THREAD

**Issue by Stefie** [polkadot-js/apps#1134]
How to reproduce:
- Create a stash account and a controller
- Click the `Nominate` button

<img width="1662" alt="Screenshot 2019-05-10 at 15 18 58" src="https://user-images.githubusercontent.com/125398/57530300-3caee080-7337-11e9-8583-0106759ef636.png">

**Comment by jacogr** [comment]
Cannot replicate, also on dev - https://youtu.be/WCpMfixrskM

**Comment by Stefie** [comment]
Could you reload the page and try again?

**Comment by jacogr** [comment]
Remember that when you just start the local dev, the fist load of `yarn start` is actually and old cached version for some reason.... so could very well be a local issue. (Not saying there is no issue, but have been refreshing like crazy...)

**Comment by Stefie** [comment]
I have this issue since yesterday and did quite a few fresh installs since then (everything @beta). But it doesn't happen on.... https://polkadot.js.org/apps/#/staking/actions

**Comment by Stefie** [comment]
And i just looked at your screencast. 
You don't see any errors in the UI, it's just the console that is getting spammed with error messages on load.
Everything is working fine once the dropdown component received the `isMultiple` prop. But that doesn't happen on load which throws the console error.

**Comment by jacogr** [comment]
Ahhh... ok, now I see it.
