### ISSUE TITLE
Can't sign a message with an ed25519

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1139]
As I was testing https://github.com/polkadot-js/apps/pull/1131#pullrequestreview-236200522 I encountered the mentioned bug.

When selecting an account created with `ed25519` the signature field disappears, the dropdown for accounts switches back to `Alice`

**Comment by Tbaut** [comment]
I'm happy to take a look at that as it's not super urgent and probably not super hard. Will have questions though :)

**Comment by jacogr** [comment]
Are we sure it is not absolutely terrible UX here? When selecting a locked account, the "sign" button disappears, and is replaced with an unlock account button. So you first need to unlock before you can sign

**Comment by Tbaut** [comment]
>Are we sure it is not absolutely terrible UX here? When selecting a locked account, the "sign" button disappears, and is replaced with an unlock account button. So you first need to unlock before you can sign

Oh I didn't know this flow (and still havn't because of the bug). Good to know so that I'll know right away what we're talking about we digging into it :)

**Comment by jacogr** [comment]
That explains the disappearance of the signature (can only be done in real-time when unlocked) -

![image](https://user-images.githubusercontent.com/1424473/57546564-49dec600-735d-11e9-92a1-61706050aac7.png)

However, cannot select accounts here properly - all all. So there is some dropdown issue.

So for the above, maybe the signature itself can show, be disabled and have a placeholder that says "account needs to be unlocked". Dunno, whatever works and look much better, would be happy with that. (This stuff has not been properly looked at in ages, it is always on the list and never gotten to - but needs to work 100%)
