### ISSUE TITLE
Hide the `Developer` tab on basic operation mode

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1140]
In light of https://github.com/polkadot-js/apps/issues/941

It would be certainly advisable to hide the `Developer` tab in the Setting app if the interface operation mode is set to "basic" so that beginner users aren't overwhelmed with options they don't need yet.

advanced / basic
![image](https://user-images.githubusercontent.com/33178835/57545122-ac35c780-7359-11e9-9c99-ffda3fa8e3f1.png)

![image](https://user-images.githubusercontent.com/33178835/57545110-a344f600-7359-11e9-830e-630056e1390a.png)

**Comment by jacogr** [comment]
Should probably end up along the same lines as this - https://github.com/polkadot-js/apps/pull/1133/files#diff-3ded779475a1b745238cbf9615d3f8e3R53
