### ISSUE TITLE
Error: Local apps, Invalid Transaction.

### ISSUE THREAD

**Issue by jiangfuyao** [polkadot-js/apps#1148]
localhost:3000 app,  
Alexander Polkadot node, or local node.  

Make Transfer, Echo error:  

![深度截图_选择区域_20190513125608](https://user-images.githubusercontent.com/34789555/57596701-a7059200-757e-11e9-824c-959e35b27ca6.png)

**Comment by xlc** [comment]
Error code 3 means no money to pay for tx fee
