### ISSUE TITLE
Brainstorming on a clearer account restoration

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1153]
Accounts can be restored via:
- Seed, on account creation
- Backup file + password

This is quite weird for new users because:
- We never say the seed can be used as a backup, yet it's a (arguably bad?) standard in crypto
- The Backup tab in `Accounts` doesn't cater for seed backups, users must edit the account creation seed.
- Backup from a file don't allow to change the name of the account (need to edit later on)

Suggestions:
- Make the seed read only at account creation (and add a refresh button to create a new seed with a new identicon)
- Allow users to either select a backup file or paste their seed
- Allow users to change the account name

Account restoration suggestion:

![image](https://user-images.githubusercontent.com/33178835/57617486-38760380-7581-11e9-8257-f920b1e5b424.png)

Not super happy with the separation all over the place and the 2 steps clearly marked.
I thought about having 2 different screens: one for the restoration type and another one for the account name (with a "next" button in between) but it really seems overkill and also prevents the user from seeing the account to restore before step 2...

Other ideas?

**Comment by jacogr** [comment]
For the JSON - no need to specify the name, it is part of the metadata in the JSON.

For the seed, you need the derivation path as well as the type of crypto, plus the password to encrypt, so you end up with something the same information as create at the end of the day :(

**Comment by jacogr** [comment]
I believe the only way is to go full-hog with a step-by-step process. (And gather additional information as required, since seeds are always going to be more complex than JSON)

**Comment by kwingram25** [comment]
So a modal with several steps? I'm trying to remember if there are any apps where the steps take place just on the page area itself

**Comment by jacogr** [comment]
No we don't have either - either a step-by-step app or a step-by-step modal. However modal could probably fit, i.e. if we have the accounts in a grid, we can just have an "add button" that walks you through. (In a modal of "full-screen" modal - whatever works)

Maybe, thinking about that, should see what pops out of https://github.com/polkadot-js/apps/issues/1044 - it may be that we can get rid of all the tabs for the rest.

**Comment by Tbaut** [comment]
Yes removing those tabs and having action buttons on accounts (for backup/send) and general buttons (for adding / restoring accounts) could be great. I'll start working on #1044 asap.

**Comment by Tbaut** [comment]
Closing this, I'll rather follow up in this issue https://github.com/polkadot-js/apps/issues/1164
