### ISSUE TITLE
Better display of accounts/others in storage

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#116]
i.e. currently a list of accounts will show the addresses, however probably should be expanded to show the actual identitycon as well.

Where param names as displayed, it can be "_paramName_ = paramValue"

Basically take what we have and turn it from a "text-dump" into something that actually looks and feels usable

**Comment by ltfschoen** [comment]
Existing functionality when I go to the Storage tab at http://localhost:3000/#/storage and select session > validators(), or staking > intentions(), it returns a text dump comma separated list of Array<AccountId>. This is similar to the Example page at http://localhost:3000/#/example, Tut002.

Proposed new functionality with the identitycon is a shown in Tut005, Tut006, and Tut007 of Example page at http://localhost:3000/#/example
