### ISSUE TITLE
Method: cannot decode value 'undefined' of type undefined

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1160]
On apps/master in the toolbox>RPC:

points to https://github.com/polkadot-js/api/blob/master/packages/types/src/primitive/Method.ts#L126

![image](https://user-images.githubusercontent.com/33178835/57654350-3d17d780-75d4-11e9-9af9-73a6b7458f3f.png)

![image](https://user-images.githubusercontent.com/33178835/57655393-9c76e700-75d6-11e9-87e4-703089e3b6d7.png)

**Comment by Stefie** [comment]
As it stands, the bug-score for the RPC methods in the toolbox app is:

API 2: 1 Apps

The one you initially reported was also caused in the api, not in apps.
So we could move it back to `api` or just leave it here....
