### ISSUE TITLE
Rework Unlocking modal in Toolbox > Sign

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1161]
The modal visible in Toolbox > Sign > Unlock account is not consistent with other modals we have in Apps. Similar to the work done here https://github.com/polkadot-js/apps/pull/1143

This modal probably needs to present the account on the left (with names etc..) and the description text on the right.

![image](https://user-images.githubusercontent.com/33178835/57682983-2359ad00-7633-11e9-8dfa-0d32c6cda866.png)

**Comment by jacogr** [comment]
And, boy, o, boy, is that one ugly.
