### ISSUE TITLE
Enter key submits the form

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1162]
Goal:
Make sure modals and common forms can be submitted with `enter` keys.

Background:
In many cases users that needed to type something as the last parameter of a form, e.g an amount or password, their hand are on the keyboard and they hit the `enter` / `return` key to submit the form to save a couple seconds.

Actions:
- Staking > Bond / BondExtra / Unbond / Set Session 
- Transfer
- Account > Edit / Create / Restore
- Address book > Edit / Create
- Chain state
- Extrinsics
- Toolbox > Unlock

I probably forgot many, but that'd be a start

**Comment by jacogr** [comment]
This could be useful for some cases - https://github.com/polkadot-js/apps/blob/master/packages/ui-app/src/Input.tsx#L31 (Added it recently for the submission of the block query on the explorer)
