### ISSUE TITLE
Rework addresses with card layout from #1044

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#1168]
Goal:

Consistency

Background:

The accounts pages are being reworked as part of #1044 , pull in the same layout into addresses. (Probably would have been simpler to start with addresses since there are less moving parts)

Actions:

- Complete one, do the other

**Comment by Tbaut** [comment]
Doing this one in parallel with https://github.com/polkadot-js/apps/issues/1044

First getting the overview screen with Name edition.
