### ISSUE TITLE
Copy the address from the short address with a click

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1176]
I think what makes users so confused is:
1. they see the address (part of it) but can't copy it
2. although the cursor has a (+) above the cursor, not only is this very unusual, but users also don't necessarily associate the icon with the address.

I propose to make the following change:
Simple yet super effective, a tooltip + mouse pointer indicates with a mouse over the address that it can be copied. Users naturally come with the mouse on the address when they want to copy it.  The feedback "copied" is also very important.

![image](https://user-images.githubusercontent.com/33178835/57956302-d4449e00-78f8-11e9-8c0b-250da830ec03.png) ![image](https://user-images.githubusercontent.com/33178835/57956305-d7d82500-78f8-11e9-87d5-e61ac7a25286.png)

We can reuse what was done in Fether, e.g: https://github.com/paritytech/fether/blob/649d6bf09259e494f006f5507774c9ff0cf31d48/packages/fether-ui/src/AccountHeader/AccountHeader.js#L28

The `ClickToCopy` component (TS) is here: https://github.com/paritytech/fether/blob/649d6bf09259e494f006f5507774c9ff0cf31d48/packages/fether-ui/src/ClickToCopy/ClickToCopy.js

edit: I guess it could be useful (yet less intuitive to have it on the name) for when we don't show the address

**Comment by rossbulat** [comment]
I definitely think the top right notifications (that need redesigning anyway) are overkill for copy-to-clipboard notifications.

Although subjective, I would lean towards 

* Just having an icon that can transition in upon hovering over copy-able content. 
* Another confirmation prompt for verifying the copy was successful.
* [This](https://www.npmjs.com/package/react-copy-to-clipboard) npm package does exactly what fether re-implemented. Would resort to tried and tested packages without re-inventing the wheel where we can.

A global icon would also remove the need for customised messages like "Copy address", "Copy X", and not confuse the text with a tooltip - the purpose of which are different from simple feedback.

The other issue here is that the user may want to view the full address without copying it - right now there is no way to do so (without viewing source). If we are to move in a direction where *only* user icons are displayed, having a function to reveal the full address would be very useful.

**Comment by jacogr** [comment]
I’m not in favour of this at all. So understand the confusion 100% (since I normally deal with answering them), but not going to extend the UI for this on short with more “you need to move your mouse to see” functionality. 

Will re-ads the copy button as we had and close this one.

**Comment by rossbulat** [comment]
@jacogr oh yes, if a copy button can be placed next to the text instead of hovering in, then that would be even better, and friendlier for mobile devices.

But overall I would favour an icon more than the text "Copy Address"

**Comment by Tbaut** [comment]
Right, getting back the copy button is also a solution. I wrongly guessed it had been removed for other reasons (because it's yet another button visible all the time but rarely used?) and wouldn't want to get it back.

>Just having an icon that can transition in upon hovering over copy-able content.

I thought about this, but I thought the icon is more a representation of the address, it could be used to show a QR code rather than copying the address. But I guess @jacogr might also not like the idea too much :)

>Would resort to tried and tested packages without re-inventing the wheel where we can.

While I agree it makes sense for some functionalities, in this specific case, as simple as this, it might be overkill (and unnecessarily broaden the attack surface of the app)

**Comment by jacogr** [comment]
Well, didn't see the comment around other packages - not interested in either -

- more external imports, or
- copy code from elsewhere

We have the `react-copy-to-clipboard` in already (in `CopyButton`), so that is what should be used. Whatever way it ends up being used.

Yes, the address copy was removed when the `IdentityIcon` got the copy functionality - specifically to streamline and not have stuff all-over. However, it a solution is tooltips or having to move around to discover anyway, just stick with the button. (Plus, believe the grayscale, show on hover, will tone down the UI, so it can't be all bad - if just applied everywhere)

**Comment by rossbulat** [comment]
> (because it's yet another button visible all the time but rarely used?) and wouldn't want to get it back.

I agree with that. I think the icon needs to be subtle as to not get in the way.

> Plus, believe the grayscale, show on hover, will tone down the UI, so it can't be all bad - if just applied everywhere

Yes, perhaps something like a white circle with a light grey copy icon in the middle would be subtle enough, and suitable as a global copy icon.
