### ISSUE TITLE
Submit extrinsics error in Polkadotjs dashboard

### ISSUE THREAD

**Issue by ansonla3** [polkadot-js/apps#1184]
I was trying to create a council motion by using the superuser (Alice).

![Screenshot 2019-05-19 at 10 39 04 PM](https://user-images.githubusercontent.com/4705997/58121815-d41b0a00-7c3a-11e9-914d-46da60def65d.png)

After I click "submit transacton", I got the following errors.

![Screenshot 2019-05-19 at 10 39 15 PM](https://user-images.githubusercontent.com/4705997/58121817-d41b0a00-7c3a-11e9-92ac-f456d7d69e19.png)

I guess there is a problem in react side ?

**Comment by Tbaut** [comment]
Do you happen to remember what method you used?
I couldn't reproduce with what is presented in your screenshot (concilMotions > propose > balances > setBalance)

![image](https://user-images.githubusercontent.com/33178835/58160228-57118400-7c7e-11e9-8b9e-fdf20defb8ad.png)

**Comment by Tbaut** [comment]
Closing as stale. council motions are being reworked in #1358
