### ISSUE TITLE
Document the rx- components interfaces

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#119]
These are cool to use, easy to setup, however it is not known unless you actually read the sources. Libraries should be properly documented throughout.

Dovetails on 

~~https://github.com/polkadot-js/dev/issues/132~~
https://github.com/polkadot-js/api/issues/108

**Comment by ltfschoen** [comment]
Still in progress in https://github.com/polkadot-js/api/issues/154

**Comment by jacogr** [comment]
Closed, duplicate of issue in shared components, https://github.com/polkadot-js/ui/issues/9
