### ISSUE TITLE
Form centric UX element proposals

### ISSUE THREAD

**Issue by rossbulat** [polkadot-js/apps#1199]
`[rossbulat: polkadot JS milestone 1 proposals]`

#### Goal
UX Elements to fill voids in Polkadot form management and general design across packages.

#### Nature of Work
Iterative form development 

#### Specifications
- [x] All elements are designed to be responsive for all screen sizes
- [x] All elements are structural components; all can be `ui-app` components to be imported elsewhere in apps
- [x] `styled-components` styling comes first, least reliance on external styles to prevent bloat
- [x] Designed to be fully typed with generic typing where appropriate

#### Discussion Goals
Positive consensus for each element, additions or amendments where agreed upon. Where one does not support an element, offer an alternative solution.

## Address Input `AddressInput`
A account selection element that allows searching for account + filter local stored accounts with the name or address of the account.

<img width="1033" alt="AddressInput" src="https://user-images.githubusercontent.com/13929023/58312922-8ec32c00-7e36-11e9-8e34-c43212561608.png">

#### Justification
Cannot rely on local storage addresses only. Current textbox designs do not facilitate an address icon, and do not allow one to search for an additional address.

#### Functional Notes
- Relies on RPC call to retrieve address on chain
- Ability to persist addresses in local storage once successfully retrieved

#### Styling Considerations
- Fits parent container width by default, that width property can overwrite
- Local account list vertically justified to center
- Icon transitions from searching to completed.
- Address fade in as local storage is updated

## Asset Transfer `AssetTransfer`
A dedicated interface for handling the transferring of assets.

<img width="919" alt="AssetTransfer" src="https://user-images.githubusercontent.com/13929023/58313302-730c5580-7e37-11e9-99aa-ca8680d670da.png">

#### Justification
The app does not yet have UX for sending assets. This proposed design is fully responsive, suitable for modals or sub-sections of a page, as well as a full page design. 
Relies on previous `AddressInput` element for recipient

#### Functional Notes
- To or from address can be disabled and set upon initialisation, removing the need for an address input

#### Styling Considerations
- Relies heavily on a flex box layout, with two rows
- First row taking up majority of screen height, and split into three columns for the two address icons and value input.
- Second row for validation messages and call-to-action button. Height is dependent on amount of validation messages.
- Validation messages transition appropriately.

## Full Screen Modal `FullModal`
A bare-bones element to overlay content on a full screen basis, with access to the glossary.

<img width="868" alt="FullScreenModal" src="https://user-images.githubusercontent.com/13929023/58313411-b5ce2d80-7e37-11e9-9104-6dd4129c04f7.png">

#### Justification
Current modal is ugly, does not reach design standards and is overly complicated in the amount of classes being attached to it.

#### Styling Considerations
- Flex box-based layout where header and footer are fixed, (footer optional for call-to-action).
- Ability to call the glossary, as tooltips are also present inside modals.
- Close button situated on left side to not interfere with glossary and main content

## Menu Popup `MenuPopup`
An overlaying element for bringing up a list of items or information where details need to be expanded. Friendly for smaller devices and larger devices in space sensitive areas.

<img width="715" alt="MenuPopup" src="https://user-images.githubusercontent.com/13929023/58317929-fed6af80-7e40-11e9-835b-4f840653d259.png">

#### Justification
There is currently no mechanism in place to expand actions and meta details. Instead, additional buttons and other data is squeezed into small spaces, sacrificing consistency and readability.

#### Functional Notes
- If time permits, experiment with a draggable function to swipe to close menu. 
- Menu items are generic, and therefore can accept any renderable class

#### Styling Considerations
- Fixed to the bottom of the window, the menu pops up. Max width will be introduced to ensure a tap-able / clickable area to close the menu.
- Initially fix height of items.

## Account Address UI `AccountAddress`
Tidy up how accounts are displayed. Have icon at forefront and expand to see address.

<img width="505" alt="AddressUI" src="https://user-images.githubusercontent.com/13929023/58313613-2ecd8500-7e38-11e9-8d8a-919e9f937da7.png">

#### Justification
Current display of accounts is confusing; two ways to copy the address, with no way to see the full address on screen. Various fonts are used to show the actual address underneath the icon, looking messy.

#### Functional Notes
- Would be cool to display an address in the form of `xxx … xxx` below the address name *on fully featured mode*, and totally remove on light mode.

#### Styling Considerations
- First-child button to be centered to the right of address icon. Second child placed above, third placed below. Maximum 3 buttons
- The action button size needs to be calculated in relation to the icon. A minimum width needs to ensure they are clickable / tap-able at the highest priority.

## UI Toggle Switch `ToggleSwitchMulti`
A toggle switch UI element to replace dropdowns where it is better suited.

<img width="541" alt="SwitchToggle" src="https://user-images.githubusercontent.com/13929023/58313692-5e7c8d00-7e38-11e9-9baa-58ed4cc08537.png">

#### Justification
Simplifies input, where the dropdown alternative a) hides the options and b) requires two interactions instead of 1. Can be used to streamline input and make forms more user friendly. Element is not offered by frameworks like SUI (personal opinion that frameworks bloat the app beyond bootstrapping, would adopt bare-bones approach).

#### Functional Notes
- Selecting items will simply toggle an underlying hidden form value

#### Styling Considerations
- Highlighted active option that will transition to new selections
- Centered content with moderate spacing for optimal readability.

## Slide-out Glossary & Tooltip Expansion
Expand glossary and help tooltips with the following enhancements:

1. Theming and styling for better headings, spacing and separation of terms
2. Load via React Suspense
3. Option to filter terms 
4. Replace scrollbar to fade out rather than stay there ([smooth scrollbar](https://www.npmjs.com/package/smooth-scrollbar))
5. API that opens the glossary at a particular term
6. Integrate a glossary link into the tooltip, and / or embed glossary links into text with an underlined style to reflect it is a glossary term.

**Comment by jacogr** [comment]
Please split these into indv. parts. Easier to comment on each. (Otherwise it gets very messy)
