### ISSUE TITLE
User-walkthrough on wiki (incorporating README)

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#120]
https://github.com/polkadot-js/apps/issues/101

This is really moving up the chain, need gaps to expand - docs are lacking, seriously lacking :(

**Comment by ltfschoen** [comment]
As discussed, we'll put this on the Polkadot JS website as you suggested

**Comment by ltfschoen** [comment]
As discussed, I've created as relevant Debugging, DRAFT Governance Overview, Governance Create View "Council" Proposals, and Troubleshooting sections so far at the Polkadot-JS Wiki https://github.com/polkadot-js/apps/wiki

**Comment by ltfschoen** [comment]
I've added some draft tutorials on substrate.readme.io:
* Deploying a Smart Contract on Substrate Node - https://substrate.readme.io/v1.0.0/docs/deploying-a-smart-contract-on-substrate-node
* Governance "Public" Mechanism with a Substrate Chain Node - https://substrate.readme.io/v1.0.0/docs/governance-public-mechanism-with-a-substrate-chain-node
* Validator Nodes and Nominators on Substrate chains - https://substrate.readme.io/v1.0.0/docs/validator-nodes-and-nominators-on-substrate-chains

**Comment by jacogr** [comment]
Closing, to be addressed in #101 for in-repo instructions.
