### ISSUE TITLE
UX proposal - Asset Transfer

### ISSUE THREAD

**Issue by rossbulat** [polkadot-js/apps#1200]
`[rossbulat: polkadot JS milestone 1 proposals]`

#### Goal
UX Elements to fill voids in Polkadot form management and general design across packages.

#### Nature of Work
Iterative form development 

#### Specifications
- [x] All elements are designed to be responsive for all screen sizes
- [x] All elements are structural components; all can be `ui-app` components to be imported elsewhere in apps
- [x] `styled-components` styling comes first, least reliance on external styles to prevent bloat
- [x] Designed to be fully typed with generic typing where appropriate

#### Discussion Goals
Positive consensus for each element, additions or amendments where agreed upon. Where one does not support an element, offer an alternative solution.

## Asset Transfer `AssetTransfer`
A dedicated interface for handling the transferring of assets.

<img width="919" alt="AssetTransfer" src="https://user-images.githubusercontent.com/13929023/58313302-730c5580-7e37-11e9-99aa-ca8680d670da.png">

#### Justification
The app does not yet have UX for sending assets. This proposed design is fully responsive, suitable for modals or sub-sections of a page, as well as a full page design. 
Relies on previous `AddressInput` element for recipient

#### Functional Notes
- To or from address can be disabled and set upon initialisation, removing the need for an address input

#### Styling Considerations
- Relies heavily on a flex box layout, with two rows
- First row taking up majority of screen height, and split into three columns for the two address icons and value input.
- Second row for validation messages and call-to-action button. Height is dependent on amount of validation messages.
- Validation messages transition appropriately.

**Comment by jacogr** [comment]
"The app does not yet have UX for sending assets." - the PR was actually open when this got logged, i.e. . https://github.com/polkadot-js/apps/pull/1193. (Subsequently merged) 

As discussed, we are replacing the transfer app with a "send from" and then on addresses a "send to". (The first part handled, the second part to be done as part of https://github.com/polkadot-js/apps/issues/1168)

So the new transfer modal caters for exactly that with the ability -

- when instantiated from accounts - pre-populates the from (cannot change), to is selectable
- when instantiated from addresses - pre-populated the to (cannot change), from is selectable
