### ISSUE TITLE
UX proposal - Popup Menu

### ISSUE THREAD

**Issue by rossbulat** [polkadot-js/apps#1202]
`[rossbulat: polkadot JS milestone 1 proposals]`

#### Goal
UX Elements to fill voids in Polkadot form management and general design across packages.

#### Nature of Work
Iterative form development 

#### Specifications
- [x] All elements are designed to be responsive for all screen sizes
- [x] All elements are structural components; all can be `ui-app` components to be imported elsewhere in apps
- [x] `styled-components` styling comes first, least reliance on external styles to prevent bloat
- [x] Designed to be fully typed with generic typing where appropriate

#### Discussion Goals
Positive consensus for each element, additions or amendments where agreed upon. Where one does not support an element, offer an alternative solution.

## Menu Popup `MenuPopup`
An overlaying element for bringing up a list of items or information where details need to be expanded. Friendly for smaller devices and larger devices in space sensitive areas.

<img width="715" alt="MenuPopup" src="https://user-images.githubusercontent.com/13929023/58317929-fed6af80-7e40-11e9-835b-4f840653d259.png">

#### Justification
There is currently no mechanism in place to expand actions and meta details. Instead, additional buttons and other data is squeezed into small spaces, sacrificing consistency and readability.

#### Functional Notes
- If time permits, experiment with a draggable function to swipe to close menu. 
- Menu items are generic, and therefore can accept any renderable class

#### Styling Considerations
- Fixed to the bottom of the window, the menu pops up. Max width will be introduced to ensure a tap-able / clickable area to close the menu.
- Initially fix height of items.

**Comment by jacogr** [comment]
Where is this to be used? Once again, feels like a solution to a problem that we don't have atm - or rather worked hard to avoid. Certainly don't want to extend too much in terms of more menus?

So would prefer - "functionality xyz" would benefit from this.

**Comment by jacogr** [comment]
Closing since we don't currently have any functionality in need of this component. However, should it be needed, sui's Dropdown or Menu can be used for this (depending on the exact functionality requirements) -

https://react.semantic-ui.com/modules/dropdown/
https://react.semantic-ui.com/collections/menu/

**Comment by rossbulat** [comment]
Well it *is* needed to fulfil expanded menus for my other address proposal. SUI element would not suffice for this. Given the restrictive nature of what UX is accepted into the project, I do not have confidence producing either at this moment.
