### ISSUE TITLE
UX proposal - Account Address UI

### ISSUE THREAD

**Issue by rossbulat** [polkadot-js/apps#1204]
`[rossbulat: polkadot JS milestone 1 proposals]`

#### Goal
UX Elements to fill voids in Polkadot form management and general design across packages.

#### Nature of Work
Iterative form development 

#### Specifications
- [x] All elements are designed to be responsive for all screen sizes
- [x] All elements are structural components; all can be `ui-app` components to be imported elsewhere in apps
- [x] `styled-components` styling comes first, least reliance on external styles to prevent bloat
- [x] Designed to be fully typed with generic typing where appropriate

#### Discussion Goals
Positive consensus for each element, additions or amendments where agreed upon. Where one does not support an element, offer an alternative solution.

## Account Address UI `AccountAddress`
Tidy up how accounts are displayed. Have icon at forefront and expand to see address.

<img width="505" alt="AddressUI" src="https://user-images.githubusercontent.com/13929023/58313613-2ecd8500-7e38-11e9-8d8a-919e9f937da7.png">

#### Justification
Current display of accounts is confusing; two ways to copy the address, with no way to see the full address on screen. Various fonts are used to show the actual address underneath the icon, looking messy.

#### Functional Notes
- Would be cool to display an address in the form of `xxx … xxx` below the address name *on fully featured mode*, and totally remove on light mode.

#### Styling Considerations
- First-child button to be centered to the right of address icon. Second child placed above, third placed below. Maximum 3 buttons
- The action button size needs to be calculated in relation to the icon. A minimum width needs to ensure they are clickable / tap-able at the highest priority.

**Comment by jacogr** [comment]
I like the move of the copy button. 

Some comments -

- don't see the value in displaying the full address expand button, some technical users do want to see it, but never going to cater for all, especially not in the context of adding more things on-screen. 

- The address-removal for light probably won't happen. However, we should certainly play with the AccountIndex vs AccountId display, in all cases it is not 100% clear which is which.

- I believe all the auto-sizing here is just overkill. We stick to one size throughout for the sake of consistency

**Comment by jacogr** [comment]
Rework for AddressRow as currently used, with current issues identified from use, logged in https://github.com/polkadot-js/apps/issues/1232

Closing this one since we only want to use one component consistently across. (And AddressRow needs a full re-think, re-work for both mini and large card modes)
