### ISSUE TITLE
Save Snippets to local storage broken

### ISSUE THREAD

**Issue by Stefie** [polkadot-js/apps#1271]
It is not possible to save code snippets to the local storage in the JS App anymore.
The last time I used it is probably 3-4 weeks ago, so it broke sometime in between.

![save](https://user-images.githubusercontent.com/125398/58877797-fd737580-86d1-11e9-80b1-26c4826e7b10.gif)

**Comment by Stefie** [comment]
Most likely it was this change to the `ActionButtons.tsx` file: https://github.com/polkadot-js/apps/pull/1170/files#diff-26345404691f374286acb17b59e55086

The buttons used in the JS-App have nothing to do with transfers. They are just used as an UI element, all functionality comes from within the App-JS component.

**Comment by jacogr** [comment]
Ummm.... yes, not sure the Tx thing should be applied there at all. (Even if it doesn't fix the issue, it is not needed there at all)

**Comment by Stefie** [comment]
Yeah, that's what I meant, it shouldn't be used there. 

@kwingram25 was there an explicit reason for putting it there?
