### ISSUE TITLE
Overlap in staking with Firefox

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1294]
The `whitespace: nowrap` from the balances (left) allows to push the right column outside its boundaries:

![image](https://user-images.githubusercontent.com/33178835/59483256-d86ac980-8e6c-11e9-91b1-213c68300300.png)

**Comment by Tbaut** [comment]
I am tempted to hack the css for the staking overview to have e.g `min-width: 42rem; max-width: 85rem;`  on `.ui--Card`. This also requires some hack on the spacers placed higher in the tree...

**Comment by jacogr** [comment]
So, been looking at this. I think we can use the standard AccountCard -

- address for it is the stash
- buttons passed via `buttons` prop
- details/children, 2 columns - controller & session & all the other info

This way we get around to using standard layouts and components. The only thing we lose is "stash" as a header, which is ok.

**Comment by Tbaut** [comment]
ok, I'll see what I can do with that.

**Comment by jacogr** [comment]
It won't solve the above overlap immediately, however what it will allow us to do is make adjustments for consistency in possibly a single place.

These are slightly longer, can go for `Set Session` or `Session Key` as a label and the current sizing may work. (Without a loss of info here. May still need slight tweaks `rem` or so to the base sizes)

**Comment by jacogr** [comment]
That overlap seems gone. However 2 funnies remain:

1. There is an extra blank line after the name here (assuming it is the icon there). Basically would assume that the available would follow the name directly.

<img width="622" alt="Polkadot:Substrate Portal 2019-06-16 00-09-07" src="https://user-images.githubusercontent.com/1424473/59556878-082fe380-8fcb-11e9-9d6a-4e5b1c36c5a0.png">

2.
<img width="904" alt="Polkadot:Substrate Portal 2019-06-16 00-08-50" src="https://user-images.githubusercontent.com/1424473/59556879-082fe380-8fcb-11e9-8262-63419818f993.png">

**Comment by Tbaut** [comment]
closing as this was mitigated
