### ISSUE TITLE
Add ability for the submission of Option<Type>

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#1307]
Currently via the Params, both in extrinsics and RPC. `Option<Type>` is handled as `Type`.

Basically -

- Toggle selects if this is optional (top right, allow value by default)
- Params encoded as per normal `Option`

**Comment by jacogr** [comment]
Done.

**Comment by repetny** [comment]
Hi, so how exactly do we pass optional param in extrinsics/RPC using polkadot-js api?
