### ISSUE TITLE
Substrate 2.x "Yay" votes don't work

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#1315]
This is actually applicable to the API, but logging it here. Since it has UI impacts (conviction) as well as API impacts (not just a i8 anymore)

https://github.com/paritytech/substrate/blob/master/srml/democracy/src/lib.rs#L145

**Comment by Stefie** [comment]
Is there actually anything left to do here or is that already solved by the api PR's https://github.com/polkadot-js/api/issues/1034? 

I tried hard to replicate the issue, but voting `yay` on 2.0 works for me. 

<img width="763" alt="Screenshot 2019-07-22 at 10 36 29" src="https://user-images.githubusercontent.com/125398/61618267-c69af400-ac6c-11e9-8f4d-3eb4f51ea5f1.png">

**Comment by jacogr** [comment]
It quite possibly is fixed just by the API changes since it was meant to be backwards compatible - we just need to verify against 1.x and 2.x (check both the votes in the actual state via a query and the display (as above) - the display _may_ also be wrong.)

But it _seems_ (without having the state checked), ok then based on the above. Which is really good news.

**Comment by Stefie** [comment]
Ok, I verified that it's working on substrate 1.0 and 2.0.
For both versions, the app is showing the correct results and a direct api query to 
`api.query.democracy.voteOf([referendumID, accountID])`
 is returning the correct `bool` results.
