### ISSUE TITLE
Add container for Treasury/Democracy to DRY-up

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#1336]
As mentioned in https://github.com/polkadot-js/apps/pull/1324#discussion_r296439472 and also found in https://github.com/polkadot-js/apps/pull/1338

I think democracy is an issue here, the Item->something indirection makes it difficult to create a card and pass -

- the header
- the buttons
- the children

(Which is what the container should do - it just gets those props and renders it in a consistent fashion)

**Comment by jacogr** [comment]
@kwingram25 I believe we can close this now?

**Comment by kwingram25** [comment]
Added with #1358
