### ISSUE TITLE
Adding srml_assets can't derive type for AssetId

### ISSUE THREAD

**Issue by retotrinkler** [polkadot-js/apps#1339]
Using `srml_assets` of substrate v1.0 branch https://github.com/paritytech/substrate/blob/v1.0/srml/assets/src/lib.rs to a [substrate node](https://github.com/blockchain-makerspace/cpi-chain/commit/d9b0dbfdb81969b238c50ced5c1a8b3fe94c9012)

returns the following erorr:
 
![image](https://user-images.githubusercontent.com/13721565/59964780-9e04ca80-9505-11e9-8dae-ea0c6ec3c91b.png)

this is likely related to `AssedId` type being declared outside of `trait` https://github.com/paritytech/substrate/blob/v1.0/srml/assets/src/lib.rs#L26-L34

which is [not the case](https://github.com/paritytech/substrate/blob/master/srml/assets/src/lib.rs#L138-L148) on main branch. I.e. might not be an issue on main branch

**Comment by retotrinkler** [comment]
Adding type using developer tab works
![image](https://user-images.githubusercontent.com/13721565/59964999-f7222d80-9508-11e9-8fb8-ce8f6badee3c.png)

Closing as not an issue.

**Comment by jacogr** [comment]
The good news is that these will go away - it is a horror, but there is ongoing work to actually convey the actual Rust types along with metadata. So it is still an . issue, but will go away. Not next week, but work is actively ongoing in this area.

**Comment by retotrinkler** [comment]
Great to hear. Thanks for your response
