### ISSUE TITLE
Staking overview is unbearably slow, non-responsive

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#1343]
On Alex.

Same with the actions (to an extent). The delayed loading is fine, however it seems like the UI is freezing while waiting. Either we are doing something stupid in `withCall` or just something stupid overall.

One things to check, alongside ops -

https://github.com/polkadot-js/apps/blob/master/packages/apps/src/Content/index.tsx#L103

If the above is re-enabled (basically loading the nominators/validators up-front - a very very expensive experience, is there impact on the load to the node? i.e. Are we keeping things in-check?)

Additionally... well, need to look, something is up here and it is not getting better as the numbers increase.

**Comment by Tbaut** [comment]
In my tests, I found that `derive.staking.controllers` takes extremely long to answer on Alexander (average >8s) and is the main source of lag.

See example [here](https://polkadot.js.org/apps/#/js/share/qgGIYXBpLnJwYy5hdXRob3IucGVuZGluZ0V4dHJpbnNpY3MoKGUVDCgpID0+IHsKICBpZh0WNC5sZW5ndGggPT09IDApAR9wICBjb25zb2xlLmxvZygnTm8gcGVuZGluZyBleHQNWDQnKTsKICAgIHJldHVybgEMBH0KNjgAAGUVLBQpOwp9KTs=)

with the code:
```js
const timer = Date.now();

const data = await api.derive.staking.controllers();
console.log('data',data);

const timeTaken = Date.now() - timer
console.log('timeTaken (ms)',timeTaken);
```

**Comment by jacogr** [comment]
Yes.

The issue is that those are linked lists, so there is no way around getting each one, one at a time.

We need to play to re-enable this - https://github.com/polkadot-js/apps/blob/master/packages/apps/src/Content/index.tsx#L103

I actually believe it won't add more RPC connections, since the WS connection should be shared. So we just need to check that.

(I'm almost of the opinion of just enabling that, testing and putting it up).

**Comment by jacogr** [comment]
Closing. Rework done on UI and API layers.
