### ISSUE TITLE
in staking page,after clicking set session key button, the right up corner's status hint is still circling

### ISSUE THREAD

**Issue by supercoder123456** [polkadot-js/apps#1355]
![image](https://user-images.githubusercontent.com/52454483/60512175-7a603200-9d06-11e9-9591-b96cb192b892.png)

**Comment by Tbaut** [comment]
Can you confirm that you are on Alexander and that you refreshed the page?

I can't reproduce. I tried with changing the session and setting it (with a group of accounts that had no session key before) and both succeeded. I'm on Chrome on Alexander.

![image](https://user-images.githubusercontent.com/33178835/60514399-b29d4b80-9cd9-11e9-98cd-9ce97ee35c88.png)

**Comment by supercoder123456** [comment]
After upgrading polkadot js, it works well!

**Comment by Tbaut** [comment]
Glad to read.
