### ISSUE TITLE
Allow stash account to set and remove proxy

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1360]
As per https://github.com/paritytech/substrate/blob/9f814b1fb140bc62d46c46dacfdba99510c34d85/srml/democracy/src/lib.rs#L547 Stash account can set a proxy account that will be able to vote on their behalf.

This is part of the democracy module, and only concerns stash accounts. I'm on the fence to add this as another menu entry in Staking>Action as it's not related to staking / nominating. On the other hand I hardly see it live in Account.

**Comment by jacogr** [comment]
We have this logged. (Also Not sure where to put it, I was leaning to democracy as a top-level option, not against accounts, but almost see that as an “also” instead of “only”)

**Comment by Tbaut** [comment]
> We have this logged. 

I've seen the delegation https://github.com/polkadot-js/apps/issues/940 but proxys are slightly different. Proxys are solely for stash accounts that should expose their key as little as possible. A proxy allows to use another key for voting whereas delegation is for an accounts A to delegate their vote to another account B. Any time A votes, it gets the stake weight of B added (at least that's my understanding).

> I was leaning to democracy as a top-level option

We could manage delegation and proxy in a tab in Democracy, that's probably the best you're right.

**Comment by jacogr** [comment]
Yes, was valid, but was actually replaced by the general proxy module.
