### ISSUE TITLE
Swap bonder to labelExtra

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#1368]
Pictures -

This one

![image](https://user-images.githubusercontent.com/1424473/60847358-b43ba780-a1e2-11e9-830b-bcc5791f9b22.png)

Should look like this one for the extra labels

![image](https://user-images.githubusercontent.com/1424473/60847380-c7e70e00-a1e2-11e9-8086-8fa1ac54bd96.png)

**Comment by Tbaut** [comment]
Do we want to cater for multi-line `labelExtra` or simply reduce the amount of given info to `available` or `bonded`? I keep `available` if I had to choose.

**Comment by jacogr** [comment]
On desktops, we can do `available 999.999E, bonded 123.456k` - on small screens, all bets are off...
