### ISSUE TITLE
Allow query of constants

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#1369]
Currently it is just a blob of data somewhere in the API. Propose that we add a new tab here "Constants" that allows you to select the constants.

![image](https://user-images.githubusercontent.com/1424473/60872313-bfb7be80-a234-11e9-95f2-a30312805f8c.png)

This obviously only shows when `Object.keys(api.consts).length > 0`

**Comment by Tbaut** [comment]
done in #1419
