### ISSUE TITLE
Warning: Encountered two children with the same key

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1370]
I get the following error on Firefox every time a dropdown with accounts is displayed:
>Warning: Encountered two children with the same key, `5GNJqTPyNqANBkUVMN1LPPrxXnFouWXoe2wNSmmEoLctxiZY`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

**Comment by Tbaut** [comment]
False alert, I had Alice key as an address book entry :confounded: 
This raises the question: should we prevent users to add an address that's already present in their keyring?

**Comment by jacogr** [comment]
Yes, we should (not allow) - additionally, be more clever on the keyring filtering, so when it, shouldn't return it. account/contract > address
