### ISSUE TITLE
Chain State breaks when viewing custom module

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/apps#1375]
I had built a dead simple module using Substrate v1.0, and everything works except trying to view the Chain State.

When I go into the Chain State, and select my module, the screen goes white and console shows this error:

```
react.e862f4ea.js:24 TypeError: Cannot read property 'myValue' of undefined
    at transform (main.75ef1a57.js:107)
    at t.default.onChange (main.75ef1a57.js:27)
    at t.default.componentDidUpdate (main.75ef1a57.js:27)
    at Bi (react.e862f4ea.js:24)
    at Vi (react.e862f4ea.js:24)
    at react.e862f4ea.js:24
    at Object.t.unstable_runWithPriority (main.75ef1a57.js:72)
    at _l (react.e862f4ea.js:24)
    at Ol (react.e862f4ea.js:24)
    at Tl (react.e862f4ea.js:24)
di @ react.e862f4ea.js:24
n.callback @ react.e862f4ea.js:24
ri @ react.e862f4ea.js:24
ni @ react.e862f4ea.js:24
Bi @ react.e862f4ea.js:24
Vi @ react.e862f4ea.js:24
(anonymous) @ react.e862f4ea.js:24
t.unstable_runWithPriority @ main.75ef1a57.js:72
_l @ react.e862f4ea.js:24
Ol @ react.e862f4ea.js:24
Tl @ react.e862f4ea.js:24
Al @ react.e862f4ea.js:24
Tn @ react.e862f4ea.js:24
react.e862f4ea.js:24 Uncaught TypeError: Cannot read property 'myValue' of undefined
    at transform (main.75ef1a57.js:107)
    at t.default.onChange (main.75ef1a57.js:27)
    at t.default.componentDidUpdate (main.75ef1a57.js:27)
    at Bi (react.e862f4ea.js:24)
    at Vi (react.e862f4ea.js:24)
    at react.e862f4ea.js:24
    at Object.t.unstable_runWithPriority (main.75ef1a57.js:72)
    at _l (react.e862f4ea.js:24)
    at Ol (react.e862f4ea.js:24)
    at Tl (react.e862f4ea.js:24)
transform @ main.75ef1a57.js:107
onChange @ main.75ef1a57.js:27
componentDidUpdate @ main.75ef1a57.js:27
Bi @ react.e862f4ea.js:24
Vi @ react.e862f4ea.js:24
(anonymous) @ react.e862f4ea.js:24
t.unstable_runWithPriority @ main.75ef1a57.js:72
_l @ react.e862f4ea.js:24
Ol @ react.e862f4ea.js:24
Tl @ react.e862f4ea.js:24
Al @ react.e862f4ea.js:24
Tn @ react.e862f4ea.js:24
```

Here is my minimal module code which causes this problem:

```
/// Single Value Storage

use support::{ensure, decl_module, decl_storage, StorageValue, dispatch::Result};
use system::ensure_signed;

pub trait Trait: system::Trait {}

decl_storage! {
	trait Store for Module<T: Trait> as SingleValue {
        MyValue: u32;
	}
}

decl_module! {
	pub struct Module<T: Trait> for enum Call where origin: T::Origin {
		fn set_value(origin, value: u32) -> Result {
            // check sender signature to verify permissions
            let sender = ensure_signed(origin)?; 
            <MyValue<T>>::put(value);
            Ok(())
        }
	}
}
```

As you can see, `myValue` is just a u32, so I dunno whats going on.

**Comment by jacogr** [comment]
You did add the custom types for your module?

**Comment by Stefie** [comment]
Yes, he did. He was sitting next to me, he added the types and tried with two different custom srml modules, it failed for both of them but it was working with a (much) older local version of apps that he still had on his computer.

**Comment by jacogr** [comment]
Well, types above doesn't make sense anyway, it is just a `u32`. So the only other thing left if possibly the number of entries? But no changes have gone into the InputSelector for storage lately, so f* knows. (The stack trace doesn't help)

**Comment by jacogr** [comment]
Probably here - https://github.com/polkadot-js/apps/blob/master/packages/ui-app/src/InputStorage/SelectKey.tsx#L32

So method is `myValue`, `value.section` is not defined.

**Comment by jacogr** [comment]
@shawntabrizi Still clueless, however please try latest - cleanup up the selection components somewhat, probably won't fix, but worth a shot in the dark.

**Comment by shawntabrizi** [comment]
@jacogr you have fixed the UI breaking, but I think I have discovered a hint to the root cause.

The option selector for custom substrate modules does not show their name when you select them in chain state:

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/1860335/61038361-338ccf00-a3cd-11e9-8030-9e7653593f05.png">

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/1860335/61038352-296ad080-a3cd-11e9-8bc5-544a4251cbd1.png">

It seems whatever value it is looking for is null or something?

Of all the custom modules in my chain, the two which are imported as "rust modules inline with the runtime" are broken, the others work.

More explicitly, this missing name error only occurs on my runtime with `module1` and `template`, but not `substrateModuleTemplate`... but I do not expect these specifics to make sense to you unless you wanna chat in person.

**Comment by jacogr** [comment]
Cool! Yes, can fix that - not sure why, but we seem to be doing something stupid.

So my night PR helped, at least now we can see wtf.
