### ISSUE TITLE
substrate 2.x, session/era doesn't calculate properly

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#1385]
Probably a derive bug

On Alex - 
![image](https://user-images.githubusercontent.com/1424473/61111918-fdae2000-a48a-11e9-92d4-9838ea1d3e9f.png)

On 2.x -
![image](https://user-images.githubusercontent.com/1424473/61111934-069ef180-a48b-11e9-842c-405d3be782b3.png)

**Comment by jacogr** [comment]
Ok, not an issue I don't believe - the settings are just very long on the dev chain. So will run for a bit, at least the eras show up now.

**Comment by jacogr** [comment]
Not sure it is a bug - the sessionLengths are just not available, not sure where they are hiding atm or if it is even possible to get them.

**Comment by jacogr** [comment]
Moving down a notch since it is not completely f-ed, we are just missing some info - so at least it does count up, so the new derive for the counters are all-ok.

![image](https://user-images.githubusercontent.com/1424473/61124444-2cd28a80-a4a7-11e9-8eca-3ebf456653d8.png)

This is what creates the issue - 

- https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/session/info.ts#L57
- https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/session/info.ts#L61

We have none of those, a there may just be nothing that can be done.

**Comment by Stefie** [comment]
Sorry, didn't see your comment, I got distracted by the failing `staking.info` tests.
But did that ever work after 0.94? The some values needed to calculate like session length were always empty after that https://github.com/polkadot-js/api/commit/ea991e4ccc85007cd27c3df9205a3113ecc9ac7c#diff-b8b8cf4dd7f97af29a616ef35ea1a337R55

**Comment by jacogr** [comment]
Yes, because it got moved and we didn't have constants - the issue now however is that we do have constants... but... well, they still don't have the values we had. (Too many changes all at once - the refactor of the session/aura is alongside, so well, you need to have your wits about you to try and figure out.)

**Comment by jacogr** [comment]
Have the info now via constants on babe, will tackle this in derive and pull in.
