### ISSUE TITLE
substrate 2.x, active validators don't show

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#1386]
i.e. new chain has Alice, none display

![image](https://user-images.githubusercontent.com/1424473/61085292-26ed9280-a430-11e9-88e2-36594fc080cd.png)

Probably related to #1378

**Comment by jacogr** [comment]
Also possibly related, active validators moved to aura - https://github.com/polkadot-js/api/pull/1108

**Comment by Tbaut** [comment]
Indeed, `derive.staking.info` is never returned and I get the following error `DRR: TypeError: "arg[0] is undefined"` which originates from api.
