### ISSUE TITLE
substrate 2.x, cannot bond

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#1387]
![image](https://user-images.githubusercontent.com/1424473/61085428-89df2980-a430-11e9-9d01-6c8e3783e155.png)

Selected -

- Bob_stash
- Bob as controller

**Comment by Tbaut** [comment]
Can you double check? the existential deposit is not super high (100*10^12) = 100 Tera. I had the following message in the node cli 
>Runtime: can not bond with value less than minimum balance

It worked with 101 Tera

**Comment by jacogr** [comment]
Ahhh.... didn't check. Yes, saw the stuff just being crazy on transfers.

Thanks for the sanity check here.
