### ISSUE TITLE
Next column isn't sorted by balance in Staking > overview

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1395]
In Alexander as well as v2.0
![image](https://user-images.githubusercontent.com/33178835/61170814-e9dbea00-a56e-11e9-9bba-de9a024580a4.png)

**Comment by jacogr** [comment]
Just marked it refactor/enhancement although technically a bug. (Just because it is not broken functionality, but rather more along the "o, this is nice" train).

**Comment by Tbaut** [comment]
Agreed, also it's a quite big refactor for what it brings, lowered the prio.

**Comment by jacogr** [comment]
Closing. The next is not actually having any balances. (If need arrises, e.g. with staking improvements on the lists, can re-visit - however probably not sone until there is in-browser phragmen)
