### ISSUE TITLE
substrate 2.x, can't see the chosen session account before validating

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#1408]
Reported by @Tbaut

**Comment by Tbaut** [comment]
This needs additional exposed info https://github.com/paritytech/substrate/issues/3148

**Comment by jacogr** [comment]
I'm going to take this one over to close out staking.

**Comment by jacogr** [comment]
Needs https://github.com/polkadot-js/api/pull/1266 for proper nextSessionId extraction
