### ISSUE TITLE
Tutorials in app-example display a proposal count of 0 after creating a proposal 

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/apps#143]
Comment by @ltfschoen in the Conversation of this PR shows how encountered issue: https://github.com/polkadot-js/apps/pull/137/files

Possible causes include the Storage tab > democracy > votingPeriod(), that is set to 20, which causes Storage tab > democracy > proposalCount() to reset to `unknown`, but in the Tutorial app-example pages it does not show any proposal count, but on my machine no proposals are shown in either locations

**Comment by jacogr** [comment]
Closing as not-going-to-fix in the current iteration. 

The app-example to be re-done with the new `withObservable` calls in https://github.com/polkadot-js/apps/issues/237. (And will probably take a different track)
