### ISSUE TITLE
Substrate 2.0: Propose council motion broken

### ISSUE THREAD

**Issue by Stefie** [polkadot-js/apps#1436]
It's currently not possible to submit a council motion on:
https://polkadot.js.org/apps/#/council/motions

**Comment by kwingram25** [comment]
I have encountered this with the console error ```Runtime: proposer not a member``` even for accounts that are council members.

**Comment by jacogr** [comment]
So the issue is the following -

- Council extends collective
- Tech Comittee extends collective
- metadata returns 2 collective structures (no names, just "collective")
- ... end result, we overwrite first with second

Substrate metadata guys are looking at getting a fix in.
