### ISSUE TITLE
Accounts displayed as if already validating - recent v2

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1445]
How to reproduce
in Staking > Actions
- create a new stake w/ Bob_stash and Bob and enough to stake, 100Peta
- look at the results, it's displayed as if Bob was validating already

![image](https://user-images.githubusercontent.com/33178835/61881806-8bf8bc00-aef7-11e9-9606-b8e81c2f0464.png)

**Comment by jacogr** [comment]
Just need to figure out if the derive is broken or if we do something weird now in the UI.

Either way, the info is not consistent between old & new :(

**Comment by Tbaut** [comment]
> if we do something weird now in the UI

it's this one :) I had a very dodgy
```js
const isStashValidating = !!validatorPrefs && !validatorPrefs.isEmpty && !isStashNominating;
```
Supposing that the `validatorPrefs` were empty when not validating, which they probably were back in the days. I'll fix that.
