### ISSUE TITLE
New GenericAsset app

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#1451]
New GenericAsset app for [srml-generic-asset module](https://github.com/paritytech/substrate/blob/master/srml/generic-asset)

Similar to transfer one, but add new field for user to set asset id.

Depends on https://github.com/polkadot-js/api/issues/1228

**Comment by xlc** [comment]
I will be working on this.

**Comment by jacogr** [comment]
The latest api is pulled into master, so it should have support.

**Comment by jacogr** [comment]
Merged.
