### ISSUE TITLE
Improve passing endpoint via url

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#1474]
url: https://polkadot.js.org/apps/#/settings?rpc=wss://mx-bryan-substrate.ap1.onfinality.io
From networking tool I can see it is connecting to the correct endpoint. but in UI it still says Alex. This is confusing.
And if I navigate to explorer and back to settings, the url become https://polkadot.js.org/apps/#/settings and no way I can tell from UI it is not connecting to Alex.

<img width="1450" alt="Screen Shot 2019-08-04 at 10 15 18 PM" src="https://user-images.githubusercontent.com/1201310/62422359-75c3da80-b705-11e9-9c8e-275805d637c5.png">

Also it will be useful to somehow generate url with custom endpoint. There are no way for others to know this feature exists without reading the code or changelog.

**Comment by jacogr** [comment]
Marking as P5, someday.

**Comment by jacogr** [comment]
Closing this. The network selector top-right always shows the name of the chain connected to, the logo, the chain version and the highlight color (if configured). So there is not "getting lost" or not knowing as in the past.
