### ISSUE TITLE
substrate 2.x, display multiple session icons

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#1487]
Because rotateKeys come into play, the actual display for a single key as we have it is non-sensical. Either display the icons/short, or just drop (3 in the case of substrate, 4 in the case of polkadot)

**Comment by Tbaut** [comment]
May I ask for more info, as I'm not familiar with `rotateKeys`.
What do you mean exactly with 
> Either display the icons/short, or just drop (3 in the case of substrate, 4 in the case of polkadot)

**Comment by jacogr** [comment]
Sessionkeys for substrate & polkadot has changed quite a bit -

https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/session/definitions.ts#L16-L18

There is no more single key, but an . opaque list of a number of (variable) keys.

Basically, when you call `setKeys` now, there is no "select the accounts" option. The node does not have a `--keys` option anymore, rather keys are generated automatically on the node. To get access to the session keys, you would so

`curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "author_rotateKeys", "params":[]}' http://localhost:9933`

which yields something of this form

`{"jsonrpc":"2.0","result":"0x24b99a36e77afbf2fc64a704d951de4f71973cf9ed7ef44710e17a40aae3bac97a5b30a4a22eca850ddf8166ba50f7ba4de286249c954b6ea2d98fe9b8a18e70521369a7df87a4b687303bb4a4a996a9715ddf525baeb0c35f20377e7efd4e217c2c20109c6fb08f1efda7e6a7699f74b635173e77e6129ff478b9c428b9d775","id":1}`

That long hex string is a concatenation of the public keys, these are passed to the setKeys command. (Important, the above _only_ on a local node)
