### ISSUE TITLE
Hide validator prefs when not validating

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1500]
double bug here, Validators prefs shouldn't show up if not set, or not a validator intention. The "Change validator preferences" Menu is `0`:
![image](https://user-images.githubusercontent.com/33178835/62948907-8a7b2f00-bde5-11e9-856f-f6d7f14f6377.png)

Saw that on Polkadot master.

**Comment by jacogr** [comment]
Dangit, I have not seen that one.

**Comment by Tbaut** [comment]
I should have seen/fixed that together with the isValidator/isNominator refactoring some time ago, but missed it. Those validator prefs used to be empty.

**Comment by Tbaut** [comment]
> "Change validator preferences" Menu is 0

^ this one had just been introduced by me in the PR I was doing, so not actually a bug in master :)
