### ISSUE TITLE
Expand storage referendums

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#153]
Currently it shows details for a single by index. It is preferable if the whole available list is shown.

**Comment by ltfschoen** [comment]
Just to clarify, currently if you want to retrieve details of a specific refereundum, you choose **democracy > referendumInfoOf(referendum)** it prompts the user to enter the referendum index in the input field, as shown below:

![screen shot 2018-07-30 at 3 33 07 pm](https://user-images.githubusercontent.com/6226175/43400409-e92f7338-940d-11e8-8a97-fba51830af0d.png)

Is the objective to convert the input field into a selection box that is populated with all the available referendum indexes (i.e. 0 to democracy.referendumCount() - 1), so the user can easily just choose one that's available?
