### ISSUE TITLE
Check bonded amount for nomination

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#1565]
Right now, the controller account has active buttons for nominate and validate, even when there are zero funds bonded. Should be a check for that.

Also need to check if it actually allows you to nominate with zero funds, since that could be an issue in Substrate.

**Comment by Tbaut** [comment]
Thanks, here is how it can look like, 0 Unit bonded, can still validate:
![image](https://user-images.githubusercontent.com/33178835/64033338-8de41980-cb4c-11e9-8f77-76a320173556.png)

**Comment by Tbaut** [comment]
the extrinsic actually succeeds, logged here https://github.com/paritytech/substrate/issues/3521

**Comment by Tbaut** [comment]
Circling back from the conversations in Substrate repo, we should prevent the buttons from being clicked if bonded is 0 because nothing will happen.
