### ISSUE TITLE
Unable to bond KSM: "1010: Invalid Transaction" - No Password Field?

### ISSUE THREAD

**Issue by soc1c** [polkadot-js/apps#1570]
OS: MacOS and Linux
Browser: Chrome, Firefox, Opera, and Safari

![Screenshot at 2019-09-01 17-51-23](https://user-images.githubusercontent.com/47772477/64079043-c9b0e780-cce2-11e9-9bcd-f3af1c750381.png)

This error you get when trying to bond KSM on Kusama using https://polkadot.js.org/apps/#/staking/actions with the default Kusama nodes hosted by Parity.

![Screenshot_2019-09-01 Polkadot Substrate Portal](https://user-images.githubusercontent.com/47772477/64079046-d33a4f80-cce2-11e9-940a-ca139ee62973.png)

I noticed the password field is missing, that might be the issue? How to sign the transaction without unlocking the account?

:wave:

**Comment by soc1c** [comment]
Also happens on "set session key" and "start validating"

Apparently, it's random and it seems to work in 1 out of 10 tries.

**Comment by EvgenRad81** [comment]
Win 10.1903, Opera 63.0.3368.53
Same problem.

**Comment by jacogr** [comment]
Something has gone seriously wrong with a merge - tracking it.

**Comment by jacogr** [comment]
Sorry about this, something went seriously wrong in the deps - and generally they are not as impactful (Sadly I screwed up the testing an only e2e tested with the extension in this case.) 

As of now the update has been merged and available on https://polkadot.js.org/apps/#/staking/actions

... passwords are properly prompted for again.
