### ISSUE TITLE
Can't unlock extension-based account from toolbox/sign

### ISSUE THREAD

**Issue by JoshOrndorff** [polkadot-js/apps#1592]
Steps to reproduce
1. Install [polkadot extension](https://github.com/polkadot-js/extension) version 0.8.2
2. Create new account in the extensions carefully noting the password
3. Navigate to https://polkadot.js.org/apps/#/extrinsics and confirm that the new account can make transfers successfully
3. Navigate to https://polkadot.js.org/apps/#/toolbox/sign
4. Select account from step 2 and click unlock
5. Enter password using the eye icon to confirm it is correct
6. Click the "Unlock" button and observe the password field turns red and the modal dialog remains

**Comment by jacogr** [comment]
Same with the new Parity Signer accounts. It is somewhere between a bug and an enhancements - a new feature that has not been fully catered for across.

**Comment by jacogr** [comment]
Done.

**Comment by JoshOrndorff** [comment]
Works for me. Thanks!
