### ISSUE TITLE
Transfer "Max" does not work

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/apps#1599]
When trying to submit a balance transfer with the "max" button, I get an extrinsic failure.

If I reduce the amount, the transaction succeeds.

My guess is that the calculations around fees have changed in Substrate, but not in the UI.

**Comment by jacogr** [comment]
Yes, indeed they have - PR to align is here - https://github.com/polkadot-js/apps/pull/1590

**Comment by jacogr** [comment]
Duplicate of https://github.com/polkadot-js/apps/issues/1561
