### ISSUE TITLE
Deeplinks or uri scheme for dashboard?

### ISSUE THREAD

**Issue by yangwao** [polkadot-js/apps#1663]
While we are an on-going reimplementation React to Vue.js, I was dreaming of having some sort of deep-links.

It could have beneficial use cases for apps like https://walletconnect.org or another potential. Thinking out loud.

Examples:
- for validators, they can redirect holders of assets to directly provide staking at some scenario
- democracy/governance accessibility UX, directly play with embedded voting from different apps
- it could have the potential for DeFi products and games too.
- in moderating some sort of social content (audio/video/photos/chats), which could be linkable as well.

Is there any **Polkadot Improvement Proposals**? I just dig through Parity repositories and did not find any.

**Comment by jacogr** [comment]
The TL;DR version 

- all Polkadot enhancements are driven through the W3F - I'm not aware of any
- nn a wallet-connect like level the uos support (although itself currently limited), is something that we are aiming for 100% compat (obviously Polkadot/Substrate only)
- would accept any PRs that move things forward (actual code above all else)

**Comment by jacogr** [comment]
Closing, can have an explicit issue around this when the applicable PSPs are introduced.
