### ISSUE TITLE
Exception when setting RPC via query params

### ISSUE THREAD

**Issue by jeluard** [polkadot-js/apps#1707]
An exception is thrown when reloading page with custom RPC set via query params.

e.g.
* browse https://polkadot.js.org/apps/?rpc=ws://127.0.0.1:9944
* URL becomes https://polkadot.js.org/apps/?rpc=ws://127.0.0.1:9944#/explorer
* refresh
* an exception is thrown: `Failed to construct 'WebSocket': The URL contains a fragment identifier ('/explorer'). Fragment identifiers are not allowed in WebSocket URLs.`

Reproduced in chrome

**Comment by jacogr** [comment]
Which OS? (Doesn't happen on MacOS, so while I use this quite a bit, it is the . first time I've actually seen it . breaking)
