### ISSUE TITLE
Testing Nominate in the edgeware testnet can select +20 Validators but after sign get 16

### ISSUE THREAD

**Issue by iammelea** [polkadot-js/apps#1716]
https://polkadot.js.org/apps/#/staking/actions
![Screenshot from 2019-10-11 08-40-57](https://user-images.githubusercontent.com/38863192/66629714-e6560e80-ec02-11e9-9ee3-3bffb486bea5.png)

then 
![Screenshot from 2019-10-11 08-41-56](https://user-images.githubusercontent.com/38863192/66629738-008fec80-ec03-11e9-85e4-5dbb8134359c.png)

then

![Screenshot from 2019-10-11 08-42-31](https://user-images.githubusercontent.com/38863192/66629785-16051680-ec03-11e9-83fd-4946da3c570a.png)

here

![Screenshot from 2019-10-11 08-42-54](https://user-images.githubusercontent.com/38863192/66629811-23220580-ec03-11e9-9830-480812d2c083.png)

Thanks

**Comment by jacogr** [comment]
There is a limit on the substrate side with a max 16 based on this - https://github.com/paritytech/substrate/blob/master/srml/staking/src/lib.rs#L283

Thank you, was not aware of this limit, will adjust the UI to only allow up to a max.
