### ISSUE TITLE
Unable to select "Set Session Key" when creating New Stake

### ISSUE THREAD

**Issue by Mitchell-Grimes** [polkadot-js/apps#1729]
Occasionally when setting the session key on a new stake, the "Set Session Key" is not intractable. However, if I select the stash account account that is associated with the stake to produce a refresh resulting in "For fund security, your session key should not match your stash key." and **RESELECT** the original session account, the "Set Session Key" is now able to be selected.

![PolkUIBug](https://user-images.githubusercontent.com/52660893/66862667-5ea03500-ef5f-11e9-92a4-0c1e8c794414.PNG)

**Comment by jacogr** [comment]
Thank you. I’ve seen something similar over the weekend with bonding a new account, it is probably related.

**Comment by jacogr** [comment]
As logged, looking through the code, this is Alexander-only. (Not present in the latest substrate 2.x versions)
