### ISSUE TITLE
Modal QrSignature scanner does not resolve/reject as expected

### ISSUE THREAD

**Issue by yjkimjunior** [polkadot-js/apps#1741]
Earlier this week this was working but now on scanning signature it does not send the extrinsic or even reject it. It just redirects the modal back to the first step and the txQueue remains untouched.

Sanity check with a clearly invalid signature QR (from myCrypto), does the same thing as above with no error message anywhere.

| Valid Signature        | Definitely invalid signature
| ------------- |:-------------:|
| ![DXXdkHv11f](https://user-images.githubusercontent.com/10432070/67091957-525de700-f1ae-11e9-8adf-d35a1596b5ba.gif)      | ![SAS5isYuDC](https://user-images.githubusercontent.com/10432070/67091914-365a4580-f1ae-11e9-917e-6681c75201f2.gif) |

Developer Console:
![Screenshot 2019-10-18 at 13 49 46](https://user-images.githubusercontent.com/10432070/67091909-322e2800-f1ae-11e9-9d16-ace1405b7c6d.png)

**Comment by jacogr** [comment]
I removed that this is a bug, at most it is an enhancement - and certainly low on the priority list. As long as the QR is valid, it will accept what you provide it. It is up to the signer to provide a valid sig. 

The UI does not even know what key type is presented - signature verification is left to the node.

**Comment by yjkimjunior** [comment]
The thing is that Signer hasn't changed how it signs, the same qr signature scanned into apps from this commit `3f0d3eea2e65d5f6284941d6e6c6f91234215be0` and prior will get an error `1010: Invalid Transaction: Payment` as expected from the node

**Comment by jacogr** [comment]
Make sure you update to a node that has commit included https://github.com/paritytech/substrate/pull/3817

(It has not made it to Polkadot master as of yet. there was a bug in Substrate where rejections weren't being passed through)
