### ISSUE TITLE
UI Error ?  couldn't redeem unbounded KSM.

### ISSUE THREAD

**Issue by kaitoukidd** [polkadot-js/apps#1765]
I unbounded some KSM 6 days ago, and when the lock  icon displayed as the screenshot.
So,  i tried to clicked the lock icon, but the available balance didn't change, and error message displayed. 
![image](https://user-images.githubusercontent.com/8613602/67615062-57501580-f802-11e9-9431-b8e218bb11e5.png)
![image](https://user-images.githubusercontent.com/8613602/67615128-16a4cc00-f803-11e9-98f3-7251298eef28.png)

**Comment by jacogr** [comment]
Which error message? It shows success?

**Comment by jacogr** [comment]
Tested with redeemed values, the display now does update as expected. (Same as when bonding, for a brief period we did have an very weird issue with refreshes in these case)
