### ISSUE TITLE
error in displaying available balance

### ISSUE THREAD

**Issue by illlefr4u** [polkadot-js/apps#1781]
It seems to me that at polkadot-ui there is an error in displaying the free balance. In the screenshot you can see the display of the same account at polkadot-ui and at polkascan, and it seems to me that at polkascan the free balance is displayed correctly.
![ui_bug1](https://user-images.githubusercontent.com/21253681/67643671-a4161800-f8f8-11e9-9e82-b838682e491f.png)

acc from the screen: FfNdRaFrP9vniLi4esANpug14AE9Q25DcR8Vz6fzFrYKSNB

**Comment by jacogr** [comment]
The UI does not display the freeBalance. 

Available - free - reserved

(The above is somewhat simplified, the vested calculations are also taken into account, as is locked)

“Free” is not actually spendable, eg. Cannot all be sent, hence the calculations to to numbers that are usable.

**Comment by jacogr** [comment]
There is a locked balance on . this account, i.e.

![image](https://user-images.githubusercontent.com/1424473/67669368-08c18900-f972-11e9-8e69-f5abc8319c7a.png)

However, the UI should really be displaying the locked totals (and until when), will enable that by default, not 100% sure why it is off by default.
