### ISSUE TITLE
Allow paste + enter to select pasted address

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#1786]
Currently you need to select via mouse

**Comment by LukeSugiura** [comment]
Can you describe the steps to produce this scenario?

**Comment by jacogr** [comment]
So what happens - 

- the user pastes an address into eg. Recipient for transfer
- the input box adds the address, but you need to physically select it from the drop down (it gets added as a “recent”)

Ideally what should happen is that the address is pasted and just automatically either selected or when pressing enter, it is selected.

**Comment by LukeSugiura** [comment]
Ah! Now I know what you mean. Thank you.
Let me try fixing this tomorrow.

**Comment by LukeSugiura** [comment]
It seems that when a user pastes an address and hit enter, state updates with the pasted address. Then somehow another state change happens with the old address. Thus it looks like hitting enter doesn't update state. The same thing happens when a user hits arrow keys.

**Comment by LukeSugiura** [comment]
Commenting out this line fixes the issues but I'm not confident to remove the useEffect hook.

https://github.com/polkadot-js/apps/blob/master/packages/react-components/src/Dropdown.tsx#L65

**Comment by jacogr** [comment]
Will take a peek as well, and see what the negatives could be. 

 Thanks you very much for the investigation and investment of time.

**Comment by jacogr** [comment]
Not sure about the above change at all - so on any changes (real changes), it should alert the parent. It is exceptionally weird that that "makes it work", sadly I think we are going to chase breakages elsewhere then where forms rely on this behavior :(

The good news is that it probably brings us one step closer understanding, and that is good.

**Comment by LukeSugiura** [comment]
I don't fully understand why the Dropdown component needs to hold any state in the first place. Usually, all form states should be managed by a form level component not filed level component.

**Comment by jacogr** [comment]
So the `InputAddress` does a couple of things that you certainly don't want to delegate to all upper-layer forms -

- it keeps tracks of the last used per type, so for instance if you selected a "from account", the next time the component renders that is the default
- it handles stuff like recently users lists for addresses, i.e. when a new address is entered, it gets added to "recents"

**Comment by LukeSugiura** [comment]
I feel like #1930 will give us a same result that you described above. Let me know if I missed some details.
