### ISSUE TITLE
Ledger integration (missing minimal features)

### ISSUE THREAD

**Issue by jleni** [polkadot-js/apps#1789]
Ledger Nano S/X integration still requires a few additional features to be complete:

- It should be possible to trigger "Show address in screen". The purpose is to confirm that the address shown in the screen corresponds with the device. A reference integration test can be found [here](https://github.com/ZondaX/ledger-polkadot-js/blob/4013c4ea1c7f65779d9111cfa20e9beb0ac81f44/tests/basic.ispec.js#L32)

- At the moment, the UI only allows accessing a single address. The app actually supports a BIP44 [derivation path](https://github.com/ZondaX/ledger-polkadot-js/blob/master/tests/basic.ispec.js#L21) so it is possible to have multiple addresses in a single device. The UI should allow users to retrieve multiple addresses from the same device.

**Comment by brenzi** [comment]
endorsing the above multiple-address request. For privacy reasons, one may want to use an every-day account and a stash account separately, without publicly transacting between the two.

**Comment by jacogr** [comment]
We should have catered for all now. (After the bump last night the long-outstanding derivation support went in for accounts & addresses)
