### ISSUE TITLE
setApprovals(votes, index) is not usable

### ISSUE THREAD

**Issue by liuchengxu** [polkadot-js/apps#180]
<img width="853" alt="2018-08-03 6 45 54" src="https://user-images.githubusercontent.com/8850248/43640199-9ab34b20-9751-11e8-94d3-699f41b8c9ac.png">

From the Riot channel, anything with Array inputs are not available yet, but still hope there is a quick fix for this one :).

**Comment by jacogr** [comment]
Closed in #441 (next branch)
