### ISSUE TITLE
Staking Page Should Display Inflation Information

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#1818]
The Staking page should display:

- Current yearly inflation rate
- Approximate Era rewards

This _should_ be easy, as you already display `total_issuance` and the amount bonded per validator. The calculation is to sum all the bonded amounts and divide it by the total issuance to get the staking rate. The calculation is defined [here](https://research.web3.foundation/en/latest/polkadot/Token%20Economics/#inflation-model).

![image](https://user-images.githubusercontent.com/25483142/67942227-aff32a00-fbd7-11e9-83d2-299aa5a48b2f.png)

**Comment by jacogr** [comment]
Not really easy -

- we need to iterate the full map as retrieved (with balances being async, to not kill RPC)
- add additional info

This is probably suite for a api.derive, P5 so when I get . to it eventually.

**Comment by ansonla3** [comment]
so this would be showing real-time staking rate?  if real-time, I do not think that's an easy especially it has to make the UI smooth and keep the bonding rate up-to-date

**Comment by joepetrowski** [comment]
What is "real time"? The way I thought about this problem is that the staking rate is set for an entire era by the phragmen election and era-to-era changes in total issuance are very small (with the exception of black-swan slashing events). "Real time" should be one change per era (day).
