### ISSUE TITLE
Show more doc text on extrinsic submission

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#1826]
The description of dispatchable functions is quite far to the right and gets cut off. Ideally, hovering on longer documentation should show the complete text.

![image](https://user-images.githubusercontent.com/25483142/68032198-7dbbf800-fcbd-11e9-85e2-cb53705fe078.png)

**Comment by jacogr** [comment]
Have you tried hovering over (?)

![image](https://user-images.githubusercontent.com/1424473/68033823-caed9900-fcc0-11e9-82ec-5608e91f0165.png)
