### ISSUE TITLE
Kusama: Problems staking tokens. The application bonded more tokens than I had in my balance

### ISSUE THREAD

**Issue by avalverdero** [polkadot-js/apps#1830]
Hi, 

trying to configure our Kusama validator node we found a strange behaviour. 

Doing the KSM bond step from polkadot.js.org, I executed the staking transfer to bond 100 milliKSM but after the transaction was validated I saw that all the tokens that I had in the balance have been bonded. At this moment I can't do anything more because all the actions need pay fees. 

This is the error that I received when I am trying nominate, unbound or setting session keys.

`staking.nominate
submitAndWatchExtrinsic (extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: BadProof`

Also is strange because the transaction shows that I transferred more tokens than I had in my balance. 

What I can do to solve it? I could receive more tokens? 

This is the [Transaction](https://polkascan.io/pre/kusama-cc2/transaction/0x86362972a4fd7ee0a03b3bd0ceb44231b818c75c9e1c7fa195e495981131b122
)

Thanks in advance. Kind Regards!

**Comment by jacogr** [comment]
Ok, so there are 2 layers here -

- the UI
- the node

The UI is only responsible for the submission. When the node gets a bond, it will bond it to the `min(freeBalance, requestedBalance)` - so when requesting more than available, it will be allowed, but capped to the amount available.

Strangely, unlike the bonding of extra funds, there is (currently) no check for request > free - this should be added to warn.

**Comment by jacogr** [comment]
Sorry, I didn't answer the second part of the question -

So at this point, the transactions are failing since there are no funds available to pay the transaction fee. Transfers will be unlocked on Kusama soon, that will allow you to send a small amount (enough to cover fees) to the account.

**Comment by avalverdero** [comment]
It makes sense. Thanks to the fast answer. 

I am sure that I executed the transaction to bond 100 milliKSM instead of 100 KSM. Can you check this behaivour to ensure there isn't additional bug? 

Anyway, actually I don't have more KSM tokens. What do you recommend me to do in this case? 

I could not do unbond or get new tokens, so I can't help to maintain the network neither be able to do test before the launch of Polkadot mainnet.

**Comment by jacogr** [comment]
All is not lost. Along with transfers, there will be a faucet available. So once should be enough to cover any fees.

We have a reworked version of the input component available with a number of issues fixed - https://github.com/polkadot-js/apps/pull/1820 - we have already added this to a checklist there.

**Comment by avalverdero** [comment]
Ok, @jacogr thanks for all !!

**Comment by jacogr** [comment]
@avalverdero If you are on Riot and have a gap, please send me a message on there.

**Comment by jacogr** [comment]
Closing after #1820 (tested InputNumber against mili -> KSM) & #1832 (additional warnings for amounts)
