### ISSUE TITLE
Set session keys no longer on dropdown in staking account actions

### ISSUE THREAD

**Issue by lsaether** [polkadot-js/apps#1844]
Previously it was possible to change session keys on the dropdown in the Staking -> Account Actions page. Now the option is gone. Was this intentional and should we change the guides?

![image](https://user-images.githubusercontent.com/25539605/68200949-2bcae900-ffc1-11e9-9bac-c03d50528590.png)

**Comment by jacogr** [comment]
The rotate session keys item.

**Comment by lsaether** [comment]
My only complaint is that `rotateKeys` refers to the RPC request while `setKeys` refers to the extrinsic in the Session module. Here "rotate session keys" actually means `Session::setKeys`.

**Comment by jacogr** [comment]
Changed to a less confusing "Change session keys" in https://github.com/polkadot-js/apps/commit/3cbcff60651385b88159230bab32ecfc04f05637
