### ISSUE TITLE
Set validator preferences (commission) only works with pico units

### ISSUE THREAD

**Issue by derfredy** [polkadot-js/apps#1884]
The box misbehaves when you try to set your validator commission in any unit but the pico.
It fills the box with zeros

Jaco, it is very difficult to find a bug, and this one is a minor one. That's an amazing work.

**Comment by jacogr** [comment]
I was swearing just now... for the public benefit, I won't swear in here...

We recently revamped the Input component there, and we seem to have some issues still. Will take a look ASAP, since if it affects there, it is in a lot of places.

**Comment by jacogr** [comment]
Ok, verified - I fixed a similar thing today earlier elsewhere, fix incoming.

**Comment by derfredy** [comment]
lightning fast!!  as usual  :-)  Thanks mate!
