### ISSUE TITLE
Can't set validaotor reward to zero in the GUI but can with extrinsic 

### ISSUE THREAD

**Issue by artkaseman** [polkadot-js/apps#1912]
Trying to adjust the validator payments to zero under staking -> account actions https://polkadot.js.org/apps/#/staking/actions 

It shows the zero amount as invalid (red box) but allows the user to continue without error.  

The next screen retains the prior (current) value instead of the new zero value, and that is what will be submitted to the chain.  

Submitting an extrinsic directly from https://polkadot.js.org/apps/#/extrinsics works as intended and the rewards are set to zero.

**Comment by jacogr** [comment]
Sorry the component props has changed recently, where previously it allowed zero by default, it not disallow it by default (where balances come into play)
