### ISSUE TITLE
Can not send validate transaction

### ISSUE THREAD

**Issue by williamrockx** [polkadot-js/apps#1917]
![WechatIMG2089](https://user-images.githubusercontent.com/55967005/69229906-4efcb780-0bc1-11ea-83b0-9d256af908ab.png)

**Comment by jacogr** [comment]
Which chain?

**Comment by williamrockx** [comment]
> Which chain?

Kusama CC2

**Comment by jacogr** [comment]
Can you please walk me through the steps as to where it breaks? Would like to replicate.

**Comment by williamrockx** [comment]
> Can you please walk me through the steps as to where it breaks? Would like to replicate.

under Staking -> Account Actions, click validate, pop up shown up, 
fill up relevant information, then click validate, error appears

**Comment by jacogr** [comment]
Ok, it seems a recent PR broke things here, will revert that - https://github.com/polkadot-js/apps/pull/1916

Sorry about this, not sure how this slipped through the cracks.
