### ISSUE TITLE
"last block" displaying incorrect times

### ISSUE THREAD

**Issue by phillux** [polkadot-js/apps#1921]
Running polkadot-js in Chromium 78.0.3904.97.
Affects both hosted and local nodes. Tested on Kusama CC2, Edgeware mainnet, Alexander.

"Last block" doesn't reset to 0.0 seconds, instead resets to 8-10 seconds, then shows blocks being produced every 15/16 seconds or so.

![image](https://user-images.githubusercontent.com/6450379/69341015-0567a780-0c69-11ea-9266-871ba152929a.png)

**Comment by jacogr** [comment]
You local PC time is not in sync. These are only done based on the underlying block timestamps, not your local time.
