### ISSUE TITLE
[DOC] Unable to register a parachain

### ISSUE THREAD

**Issue by damianoazzolini** [polkadot-js/apps#1944]
I'm following the instructions at https://wiki.polkadot.network/docs/en/build-deploy-parachains#deploying-the-parachain. However, under the tab democracy -> propose(proposal,value) -> parachains there isn't the option registerParachain(id,code,initial_head_data). How can i register a parachain using the UI?

**Comment by jacogr** [comment]
The documentation is outdated and doesn't actually reflect the current master of polkadot. You are looking for this -

![image](https://user-images.githubusercontent.com/1424473/69547752-6c050200-0f96-11ea-900d-48290cc98548.png)
