### ISSUE TITLE
No response on UI when calling smart contract function

### ISSUE THREAD

**Issue by satyamakgec** [polkadot-js/apps#1952]
_Environment running-_ 
Running substrate latest version from master
Using the latest ink!

I am trying to run the simple contract that lives here https://github.com/paritytech/ink/blob/master/examples/lang2/runtime-storage/src/lib.rs

By looking into the UI console it shows the error `this.rpcContractsCall is not a function`
![Screen Shot 2019-11-27 at 6 45 31 PM](https://user-images.githubusercontent.com/14581509/69726846-5aaf2780-1147-11ea-820c-2b16fabd9712.png)

**Comment by ascjones** [comment]
Custom substrate nodes need to wire up the contracts RPC: https://github.com/gautamdhameja/substrate-runtime-contract-sample/pull/2

**Comment by jacogr** [comment]
Thanks for the effort, happy that is actually works with this. 

We still have a UI issue where the specific functionality should not be show at all when not available.

**Comment by jacogr** [comment]
Functionality disabled now when no RPC is available.
