### ISSUE TITLE
Validator stats show 0 blocks produced for validators who authored the last block.

### ISSUE THREAD

**Issue by Mitchell-Grimes** [polkadot-js/apps#1954]
This account is good example. 
https://polkadot.js.org/apps/#/staking/query/EPehck28w8fjRZCqZ3VZA7XpwGeipuVU4ETSwv7GkF5BdcG

- Session 340 -> Start at block	770848 -> End at block	773197 
https://polkascan.io/pre/kusama-cc2/block/773197 That last block, they authored it.

- Session 357 -> Start at block	810845 -> End at block	813218
https://polkascan.io/pre/kusama-cc2/block/813218 They also authored it.

Another example
![image](https://user-images.githubusercontent.com/52660893/69735092-1d727780-10fe-11ea-8fe5-e3b609231916.png)

In theory, you can use polkascan to check sessions for their starting and ending block. Find who authored the last block and then search them on polkadot.js.org to see if they have the same 0 authored blocks. This happens on every of the 5 random older sessions I looked at. 

Is this a bug? It's somewhat misleading for anyone who looks at our validator. At first glance it looks like it's offline. 

Also the Storage chainstate appears to be affected (but I assume that the validator stats page uses the same query)
![bug](https://user-images.githubusercontent.com/52660893/69735555-de90f180-10fe-11ea-95d9-7d089ca25bd3.png)

**Comment by jacogr** [comment]
The UI only reports what the state reports. In that case, since the imOnline state reports 0, it would mean that it is deemed "offline".

**Comment by Mitchell-Grimes** [comment]
> The UI only reports what the state reports. In that case, since the imOnline state reports 0, it would mean that it is deemed "offline".

If that's the case, how can a validator author blocks within a session but still get credited to 0 blocks produced. For example: https://polkadot.js.org/apps/#/staking/query/GhoRyTGK583sJec8aSiyyJCsP2PQXJ2RK7iPGUjLtuX8XCn

Session in question is 369. 

- Start at block | 839009 -- | -- End at block | 841398

https://polkascan.io/pre/kusama-cc2/block/839009

The same validator even authored the first block, which would be at least 1, would it not?

**Comment by jacogr** [comment]
I really cannot comment as to why the `imOnline` does not count the first block produced, neither as to the background to the  first account. As suggested, the UI only displays what is in the chain state, specifically `imOnline`.

If imOnline counts incorrectly (as you seem to suggested for some accounts), the best place to log it would be the substrate repo.

**Comment by Mitchell-Grimes** [comment]
> If imOnline counts incorrectly (as you seem to suggested for some accounts), the best place to log it would be the substrate repo.

Will do, appreciate the information.
