### ISSUE TITLE
Vote for current candidates no update my votes when change the account.

### ISSUE THREAD

**Issue by iammelea** [polkadot-js/apps#1975]
need vote for council 

https://polkadot.js.org/apps/#/council

![Screenshot from 2019-12-02 15-20-03](https://user-images.githubusercontent.com/38863192/69966731-47210980-1517-11ea-99ac-7eed53f33580.png)

I have 2 accounts 
* MELEA
* MELEA-VALIDATOR
I want to vote with the **MELEA-VALIDATOR** account.

select that account but still is  the Councils votes on my screen for **MELEA** account.
![Screenshot from 2019-12-02 15-22-07](https://user-images.githubusercontent.com/38863192/69966901-9cf5b180-1517-11ea-8f3a-c5b329c22f2b.png)

if close and open again then open my vote list.

![Screenshot from 2019-12-02 15-23-31](https://user-images.githubusercontent.com/38863192/69966953-b72f8f80-1517-11ea-9f09-47081e4d079a.png)

Thanks for this UI is awesome.

**Comment by jacogr** [comment]
This was fixed, but not closed. The voting dialog now populates as the account is changed with the votes for that account.
