### ISSUE TITLE
Add user notifications

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/apps#199]
As users create an account, backup an account, or restore an account, they may like consistent notifications, such as a toaster, or similar equivalent (i.e. successfully downloaded JSON file, failed to download JSON file due to xyz, etc). Currently we are using [React Semantic UI](https://react.semantic-ui.com/),which offers Messages, etc

**Comment by jacogr** [comment]
Extends the toaster display we already have (e.g. for tx submission) to cater for this.

**Comment by jacogr** [comment]
Closed in #391
