### ISSUE TITLE
Staking/Account Actions: Can neither start nor stop validating

### ISSUE THREAD

**Issue by soc1c** [polkadot-js/apps#1990]
The account `Dab4bfYTZRUDMWjYAUQuFbDreQ9mt7nULWu3Dw7jodbzVe9` can neither start nor stop validating.

![photo5418050894458629025](https://user-images.githubusercontent.com/47772477/70039197-cd8e2780-15b9-11ea-84b5-62f0a5b784f7.jpg)

We tried resetting the session key but it does not allow us to start validating.

Also, it's not entirely clear why this account is neither a validator nor a candidate.

**Comment by jacogr** [comment]
It doesn't detect the session keys it would seem :( And if you tried setting them, even weirder.

**Comment by jacogr** [comment]
There are no keys set for the account -

![image](https://user-images.githubusercontent.com/1424473/70040592-1810a380-15bc-11ea-9e8c-2cd9216dbc96.png)

So not sure why your set session keys doesn't work here? Did the tx fail for those?

**Comment by soc1c** [comment]
Yeah it failed.

![photo5418050894458629028](https://user-images.githubusercontent.com/47772477/70041317-3aef8780-15bd-11ea-8e2d-3995f6782390.jpg)

The key is `0x117a6efbb511bb4162648fd9ae1dfa31c34b05d788d34b20b71f84514f854c9bb422b8ee2fdbf76a682a8c15473deedc92c6fbfac12f9888a31e97ce18d35744b2d0b1545ee243edd0ec31bb107181ca9c24dfa18246d6746829275ad30982457a63ae0ae47d34808c7177b04676b58768cf8b055c50095ceb887b69f495e27e`

I guess what happened is the node had issues for 2-3 hours and was removed from the validator set, but I am having a hard time getting it back in...

**Comment by jacogr** [comment]
The last tx I see on Polkascan is this one - https://polkascan.io/pre/kusama-cc3/transaction/0x5bc51af550b66b9f7bc2ca0848e42a8edf50d55d8bf06c38cb46352b0b79a46c

The last key doesn't seem to be set. And indeed, breaking it down there are only 4 keys -

```0x
117a6efbb511bb4162648fd9ae1dfa31c34b05d788d34b20b71f84514f854c9b
b422b8ee2fdbf76a682a8c15473deedc92c6fbfac12f9888a31e97ce18d35744
b2d0b1545ee243edd0ec31bb107181ca9c24dfa18246d6746829275ad3098245
7a63ae0ae47d34808c7177b04676b58768cf8b055c50095ceb887b69f495e27e
```

**Comment by soc1c** [comment]
Oooooooooh that's my fault. I'm sorry. I accidentally rotated the keys with the wrong version of polkadot :( - Sorry.

Thanks for pointing that out!
