### ISSUE TITLE
Browser console error `Cannot read property 'publicProps' and 'nextTally' of undefined`

### ISSUE THREAD

**Issue by jimmychu0807** [polkadot-js/apps#1991]
After fixing #1986, when I run a custom substrate node on `master` branch (against substrate 
 rev:368318c9b11c07596cde5dc37220258cfa7dfa76), it is reading these two undefined variables.

**Comment by jacogr** [comment]
As long as it doesn't break the UI. It is expected, it assumes a full-featured chain. PRs to the api-derive welcome, sadly won't get there anytime shortly since Kusama is priority.

**Comment by jimmychu0807** [comment]
sure. Let's keep a record here, and if time permits, will take a look at this also.
