### ISSUE TITLE
Certain functionality appears disabled in account actions page 

### ISSUE THREAD

**Issue by joshua-mir** [polkadot-js/apps#1992]
When modifying my "stash settings" on the account actions page in staking, certain functionality, such as adding additional bond or changing my controller account, seems to be disabled in error. 
![Screenshot_20191203_124528](https://user-images.githubusercontent.com/43032097/70050890-4a2c0080-15d0-11ea-896e-018cc1186ab9.jpg)

I have confirmed that I can manually increase my bond in extrinsics. After doing so, the issue seemed to have resolved itself with the functionality becoming re-enabled.

**Comment by jacogr** [comment]
So the code does the following -

```js
// only show a "Bond Additional" button if this stash account actually doesn't bond everything already
    // staking_ledger.total gives the total amount that can be slashed (any active amount + what is being unlocked)
    const canBondExtra = balances_all && balances_all.freeBalance.gtn(0);

    return (
      <Menu
        vertical
        text
        onClick={this.toggleSettingPopup}
      >
        {canBondExtra &&
          <Menu.Item
            disabled={!isOwnStash}
            onClick={this.toggleBondExtra}
          >
            {t('Bond more funds')}
          </Menu.Item>
        }
...
```

So it checks `freeBalance`. So not sure how it disables it if you have balance.

**Comment by joshua-mir** [comment]
I don't know how I can get back to the broken state, unfortunately.

**Comment by jacogr** [comment]
Closing until it is re-producible. Would love a bit, however as it stands it is just on of those things hanging about.
