### ISSUE TITLE
the doublemap value allways return 0 or null

### ISSUE THREAD

**Issue by wjy19990622** [polkadot-js/apps#2007]
there are my doublemap in substrate:
TokenInfo: double_map T::AccountId, blake2_256(Vec) => Vec<u8>;
TokenInfo: double_map T::AccountId, blake2_256(Vec) => u32;

i update the doublemap's key and value successful. but in https://polkadot.js.org/apps/#/chainstate, my doublemap values can't show correctly, allway 0x00. then i change the value type to u32, it allway return 0.
but on the console, return correct Vec or u32.

tell me what can i do? thanks.

**Comment by jacogr** [comment]
As an example on Kusama for -

```
		/// For each session index, we keep a mapping of `T::ValidatorId` to the
		/// number of blocks authored by the given authority.
		AuthoredBlocks get(fn authored_blocks): double_map SessionIndex,
			blake2_256(T::ValidatorId) => u32;
```

![image](https://user-images.githubusercontent.com/1424473/70324682-72b23580-1830-11ea-8946-cc375a1cd1a6.png)

**Comment by wjy19990622** [comment]
> As an example on Kusama for -
> 
> ```
> 		/// For each session index, we keep a mapping of `T::ValidatorId` to the
> 		/// number of blocks authored by the given authority.
> 		AuthoredBlocks get(fn authored_blocks): double_map SessionIndex,
> 			blake2_256(T::ValidatorId) => u32;
> ```
> 
> ![image](https://user-images.githubusercontent.cowhtm/1424473/70324682-72b23580-1830-11ea-8946-cc375a1cd1a6.png)

but  why my struct value allways uncorrect? Vec<u8>   cause ？

**Comment by jacogr** [comment]
So what is Vec in this case? That is not a valid Rist type unless an alias. (You need type info for a vector)

**Comment by wjy19990622** [comment]
> So what is Vec in this case? That is not a valid Rust type unless an alias. (You need type info for a vector)

i use u8 in vec

**Comment by wjy19990622** [comment]
> > So what is Vec in this case? That is not a valid Rust type unless an alias. (You need type info for a vector)
> 
> i use u8 in vec

i  am sure that vec \<u8\> be used for the second key in doublemap, the value can't show correctly in Chain state.  there are my code  [https://github.com/TransactionX/TransX/blob/master/bin/node/runtime/src/register.rs](url).

**Comment by wjy19990622** [comment]
> > > So what is Vec in this case? That is not a valid Rust type unless an alias. (You need type info for a vector)
> > 
> > 
> > i use u8 in vec
> 
> i am sure that vec <u8> be used for the second key in doublemap, the value can't show correctly in Chain state. there are my code [https://github.com/TransactionX/TransX/blob/master/bin/node/runtime/src/register.rs](url).

when use 'TokenInfo: double_map T::AccountId, blake2_256(u32) => Vec\<u8\>;' replace 'TokenInfo: double_map T::AccountId, blake2_256(Vec\<u8\>) => Vec\<u8\>;' , it show correctly value.

**Comment by jacogr** [comment]
So my confusion was around this above - `TokenInfo: double_map T::AccountId, blake2_256(Vec) => Vec;` - the `Vec` there has no type info. 

So in all cases the variable-length items are encoded (in SCALE), with a length prefix. It could very well be that for storage keys one side does not apply it with the prefix, so could be missing in the API or on the node side. (I(n which case items suck as `[u8; 16]` would not show the issue.)

Since this requires customisation of entries to replicate, cannot promise I'll be able to take a look immediately, but added to the queue to look at as soon as there is an open spot to customize and build.

**Comment by wjy19990622** [comment]
> So my confusion was around this above - `TokenInfo: double_map T::AccountId, blake2_256(Vec) => Vec;` - the `Vec` there has no type info.
> 
> So in all cases the variable-length items are encoded (in SCALE), with a length prefix. It could very well be that for storage keys one side does not apply it with the prefix, so could be missing in the API or on the node side. (I(n which case items suck as `[u8; 16]` would not show the issue.)
> 
> Since this requires customisation of entries to replicate, cannot promise I'll be able to take a look immediately, but added to the queue to look at as soon as there is an open spot to customize and build.

so if i think that the value can show correctly,  the doublemap key should use array replace Vec\<u8\>?

**Comment by wjy19990622** [comment]
> > So my confusion was around this above - `TokenInfo: double_map T::AccountId, blake2_256(Vec) => Vec;` - the `Vec` there has no type info.
> > So in all cases the variable-length items are encoded (in SCALE), with a length prefix. It could very well be that for storage keys one side does not apply it with the prefix, so could be missing in the API or on the node side. (I(n which case items suck as `[u8; 16]` would not show the issue.)
> > Since this requires customisation of entries to replicate, cannot promise I'll be able to take a look immediately, but added to the queue to look at as soon as there is an open spot to customize and build.
> 
> so if i think that the value can show correctly, the doublemap key should use array replace Vec<u8>?

thanks very much.  i use [u8;16] replace it,    show correctly.

**Comment by jacogr** [comment]
Glad you are sorted.

We will still have to investigate, since something is weird here - as soon as there is a gap, will delve in deep.
