### ISSUE TITLE
Add Flexbox Layout to StakeList

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/apps#201]
See https://github.com/polkadot-js/apps/commit/278ca138125c8828e63bf600437db8368dcda052#diff-ddaf983336b46f755e89de55b0451493R20

**Comment by jacogr** [comment]
Please just expand issue with -

1. Labels, i.e. the area impacted
2. What it actually does, "Flexbox layout" can be anywhere, be more specific, i.e. area in app in label

**Comment by jacogr** [comment]
Closing, non-critical. Can be re-looked when staking gets reworked.
