### ISSUE TITLE
Sudo calls result in an error and blank screen

### ISSUE THREAD

**Issue by vkandy** [polkadot-js/apps#2020]
When submitting a dispatchable call, for e.g., sudo, the following error is thrown and the page goes blank:

> react.5465a6b4.js:17 TypeError: Cannot read property 'toString' of undefined
    at t.TypeRegistry.findMetaCall (main.a904619e.js:88)
    at t.default (main.a904619e.js:93)
    at hi (react.5465a6b4.js:17)
    at _l (react.5465a6b4.js:17)
    at Bs (react.5465a6b4.js:17)
    at Ns (react.5465a6b4.js:17)
    at ws (react.5465a6b4.js:17)
    at react.5465a6b4.js:17
    at t.unstable_runWithPriority (main.a904619e.js:80)
    at Xa (react.5465a6b4.js:17)

Full error is attached here
![polkadot](https://user-images.githubusercontent.com/77166/70444064-8343f500-1a56-11ea-9488-32328350d3ef.png)

**Comment by jacogr** [comment]
1. Which node type?
2. Which chain?
3. Which proposal?

**Comment by vkandy** [comment]
@jacogr here's some info you asked:
1. On substrate default 
2. dev chain
3. I used `technicalMembership` `addMember` but I think any proposal shows the same error

```
$ ./target/release/substrate --chain=dev
2019-12-09 09:31:22 Substrate Node
2019-12-09 09:31:22   version 2.0.0-1c7e65fa3-x86_64-linux-gnu
2019-12-09 09:31:22   by Parity Technologies, 2017-2019
2019-12-09 09:31:22 Chain specification: Development
2019-12-09 09:31:22 Node name: fast-father-7524
2019-12-09 09:31:22 Roles: FULL
2019-12-09 09:31:23 Initializing Genesis block/state (state: 0xe436…96bc, header-hash: 0x5847…2969)
2019-12-09 09:31:23 Loading GRANDPA authority set from genesis on what appears to be first startup.
2019-12-09 09:31:23 Loaded block-time = BabeConfiguration { slot_duration: 3000, epoch_length: 200, c: (1, 4), genesis_authorities: [(Public(d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...)), 1)], randomness: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], secondary_slots: true } seconds from genesis on first-launch
2019-12-09 09:31:23 Creating empty BABE epoch changes on what appears to be first startup.
2019-12-09 09:31:23 Highest known block at #0
2019-12-09 09:31:23 Using default protocol ID "sup" because none is configured in the chain specs

```

**Comment by jacogr** [comment]
Thank you, will check - these are typically specific to a call, hence asking. One of the fields are not rendered correctly.

**Comment by jacogr** [comment]
Ok, now this is weird. Not showing the same on mine, master as of a couple of hours ago, submitted and all fine. 

Will look at what happens with the extrinsic input as to which can cause it to have "toString of undefined".

**Comment by vkandy** [comment]
Also, I am on substrate commit `7d7e74fb77b6bee2ce9d6ebafcae09caff2d0e50`

**Comment by jacogr** [comment]
Since you get the same console errors are the node-template users, I'm assuming you are using that. The above PR may improve things, well at least it will fail slightly more gracefully. (Generally only test against the full node in Substrate & the full nodes in Polkadot)

**Comment by vkandy** [comment]
Thanks @jacogr We have a substrate based project that's running on this commit. So I'll have to stay on this for a while. I'll pull and test.

**Comment by vkandy** [comment]
FYI I see a different set of errors now:

```
main.01d3c059.js:135786 Uncaught TypeError: Cannot read property 'map' of undefined
    at Call (main.01d3c059.js:135786)
    at renderWithHooks (react.e5b651d2.js:36033)
    at mountIndeterminateComponent (react.e5b651d2.js:38567)
    at beginWork$1 (react.e5b651d2.js:39935)
    at HTMLUnknownElement.callCallback (react.e5b651d2.js:20109)
    at Object.invokeGuardedCallbackDev (react.e5b651d2.js:20158)
    at invokeGuardedCallback (react.e5b651d2.js:20213)
    at beginWork$$1 (react.e5b651d2.js:45553)
    at performUnitOfWork (react.e5b651d2.js:44471)
    at workLoopSync (react.e5b651d2.js:44444)
```
```
The above error occurred in the <Call> component:
    in Call (created by Context.Consumer)
    in StyledComponent (created by Call)
    in Call (created by withI18nextTranslation(Call))
    in withI18nextTranslation(Call) (created by Proposal)
    in div (created by Bare)
    in Bare (created by Context.Consumer)
    in StyledComponent (created by Bare)
    in Bare (created by Proposal)
    in Proposal (created by Param)
    in Param (created by withI18nextTranslation(Param))
    in withI18nextTranslation(Param) (created by ParamComp)
    in div (created by ParamComp)
    in ParamComp (created by Params)
    in div (created by Params)
    in div (created by Params)
    in Params (created by Context.Consumer)
    in StyledComponent (created by src)
    in src (created by withI18nextTranslation(src))
    in withI18nextTranslation(src) (created by Call)
    in div (created by Call)
    in Call (created by Context.Consumer)
    in StyledComponent (created by Call)
    in Call (created by withI18nextTranslation(Call))
    in withI18nextTranslation(Call) (created by Transaction)
    in div (created by ModalContent)
    in ModalContent (created by Transaction)
    in Transaction (created by withI18nextTranslation(Transaction))
    in withI18nextTranslation(Transaction) (created by Signer)
    in div (created by Modal)
    in RefFindNode (created by Ref)
    in Ref (created by Modal)
    in div (created by Modal)
    in RefFindNode (created by Ref)
    in Ref (created by PortalInner)
    in PortalInner (created by Portal)
    in Portal (created by Modal)
    in Modal (created by Modal)
    in Modal (created by Signer)
    in Signer (created by WithObservable)
    in WithObservable (created by Context.Consumer)
    in WithApi (created by withI18nextTranslation(WithApi))
    in withI18nextTranslation(WithApi) (created by Signer)
    in Signer (created by Apps)
    in div (created by Apps)
    in Apps (created by Context.Consumer)
    in StyledComponent (created by Apps)
    in Apps (created by Context.Consumer)
    in ThemeProvider (created by Context.Consumer)
    in Router (created by HashRouter)
    in HashRouter (created by Context.Consumer)
    in Events (created by Context.Consumer)
    in BlockAuthors (created by Context.Consumer)
    in Api (created by Context.Consumer)
    in Queue
    in Suspense

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```
```
Uncaught TypeError: Cannot read property 'map' of undefined
    at Call (main.01d3c059.js:135786)
    at renderWithHooks (react.e5b651d2.js:36033)
    at mountIndeterminateComponent (react.e5b651d2.js:38567)
    at beginWork$1 (react.e5b651d2.js:39935)
    at HTMLUnknownElement.callCallback (react.e5b651d2.js:20109)
    at Object.invokeGuardedCallbackDev (react.e5b651d2.js:20158)
    at invokeGuardedCallback (react.e5b651d2.js:20213)
    at beginWork$$1 (react.e5b651d2.js:45553)
    at performUnitOfWork (react.e5b651d2.js:44471)
    at workLoopSync (react.e5b651d2.js:44444)
```

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in BlockAuthors (created by Context.Consumer)
    in Api (created by Context.Consumer)
    in Queue
    in Suspense
```

**Comment by jacogr** [comment]
Ok, tested this now against both Substrate master and . an older Polkadot (before Sudo was dropped). I am clueless as to why this happens on this specific node. It is like it cannot decode the extrinsic properly or at all.

**Comment by jacogr** [comment]
Which additional types have you injected? And can you share your runtime/lib.rs config?

**Comment by maxsam4** [comment]
> Which additional types have you injected? And can you share your runtime/lib.rs config?

https://github.com/PolymathNetwork/Polymesh
https://github.com/PolymathNetwork/Polymesh/blob/master/polymesh_schema.json
https://github.com/PolymathNetwork/Polymesh/blob/master/runtime/src/runtime.rs

**Comment by maxsam4** [comment]
After the last update to polkadot-js, I am getting a different set of errors
![Screenshot from 2019-12-10 12-02-24](https://user-images.githubusercontent.com/7436022/70501789-14919500-1b45-11ea-9b46-424dc0582a41.png)

ps IdentityId is defined as `"IdentityId": "[u8;32]"` in the schema.

**Comment by jacogr** [comment]
There are a couple of overrides I can see that are missing due to the chain being old, from 24 Sep (this one is still on the previous extrinsic version, v3, also visible in the extrinsic in your screenshot) -

- Keys needs to be specified explicitly (it is defined in the chain as having 3 keys, the Substrate defaults in 5)
- ValidatorPrefs needs to be adjusted (the Substrate default is for commission, the chain variant is payment)
- Types for LinkedKeyInfo, OffChainSignature, PermissionedValidator are not defined at all

The other areas that generally give issues, such as Index, BlockNumber, Balance are all ok.

The underlying reason why the sudo calls do fail however, is this definition -

```json
"Proposal": {
        "title": "Vec<u8>",
        "info_link": "Vec<u8>",
        "choices": "Vec<Vec<u8>>"
    },
```

In Substrate `type Proposal = Call` and that is what gets wrapped inside the sudo transaction. So the API is instructed to override the `Proposal` type with the above, and cannot decode this into a `Call`-variant of the `Proposal`

**Comment by maxsam4** [comment]
Thanks @jacogr , renaming the proposal type fixed the immediate issue. 

>Keys needs to be specified explicitly (it is defined in the chain as having 3 keys, the Substrate defaults in 5)

How does one go about specifying keys in polkadot-js?

>ValidatorPrefs needs to be adjusted (the Substrate default is for commission, the chain variant is payment)

Can you please give some more details about this?

>Types for LinkedKeyInfo, OffChainSignature, PermissionedValidator are not defined at all

We'll add details about the missing types.

Thanks for the help!

**Comment by jacogr** [comment]
So for the various keys & prefs, refer to this API CHANGELOG entry - https://github.com/polkadot-js/api/blob/master/CHANGELOG.md#0971

So in your case it would be `"Keys": "SessionKeys3"` (I believe I saw 3 keys) & `"ValidatorPrefs": "ValidatorPrefsTo196"`

It is tricky, the API and UI always tracks the latest Substrate master in terms of types.

At some point the metadata will actually return all the types (as opposed to just the calls), which will make these issues non-existent. (Barring human-error along the way).
