### ISSUE TITLE
one validator shown twice in the nomination list

### ISSUE THREAD

**Issue by illlefr4u** [polkadot-js/apps#2037]
One validator shown twice in the nomination list with and without filter. If start to nominate one of them, another one change status too.
![jsorg1](https://user-images.githubusercontent.com/21253681/70728368-0deb5500-1ce0-11ea-83a4-46db184c0d38.png)
![jsorg2](https://user-images.githubusercontent.com/21253681/70728369-0deb5500-1ce0-11ea-967c-bd24b03575c3.png)

**Comment by jacogr** [comment]
Thank you. Weird. 

Was this one of yours favorites before, or just a duplicate that shows up?

Will take a peek, weird and def. an issue, not quite sure what the cause is off-hand, but should be easy to track and fix.

**Comment by illlefr4u** [comment]
Was not one of my favorite, just duplicate with filter and without too (cant show, cause they are not in one screen without filter).

**Comment by jacogr** [comment]
Perfect, thanks. 

Will dive in and take a peek and get a fix in, the info comes from different sources, so obviously missed a combine sources trick somewhere.

**Comment by illlefr4u** [comment]
I hope I caught when this happens. The validator appears twice in the list if it is currently on the waiting list, it will become a validator in the next era, and you dont nominate this validator know.
