### ISSUE TITLE
Add option to show amount nominating in current session

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#2085]
The Staking > Account Actions page shows a list of all accounts that you are nominating with their self stake. It would be nice to have an option to see how much of your stake is nominating each account in the current session instead of the self stake of each nominee.

Ideally you could choose to display "total stake", "self stake", or "my current nominating stake" as options on this page.

For example, here I am nominating Federico with 30.858:
![image](https://user-images.githubusercontent.com/25483142/71342531-5961f680-255d-11ea-8b22-71f6adb50656.png)

Staking > Actions should show 30.858 under Federico here:
![image](https://user-images.githubusercontent.com/25483142/71342597-82828700-255d-11ea-9c95-bacbf81946c8.png)

**Comment by Tbaut** [comment]
Do you know if this information is available in the storage state anywhere? Couldn't find it.

**Comment by jacogr** [comment]
The exposure for the validator has this info. So for each validator in the list -

- query the exposure
- the `others` field contains the specific values
