### ISSUE TITLE
cant unvote council candidate which is no longer a candidate

### ISSUE THREAD

**Issue by illlefr4u** [polkadot-js/apps#2087]
If you have now vote for a candidate which is no longer a candidate to the council, then you can't remove the vote for him in ui (see screenshots)

![council1](https://user-images.githubusercontent.com/21253681/71587212-913be180-2afb-11ea-93af-c20b12596c10.png)
![council2](https://user-images.githubusercontent.com/21253681/71587213-913be180-2afb-11ea-8941-e502178e749a.png)
![council3](https://user-images.githubusercontent.com/21253681/71587214-913be180-2afb-11ea-9c19-93434037085d.png)

**Comment by jacogr** [comment]
Sorry https://github.com/polkadot-js/apps/pull/2193 took so long to get to - it really should have been 18 minutes, not 18 days.
