### ISSUE TITLE
Indicate non-active validations

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#2094]
https://github.com/paritytech/substrate/pull/4553

**Comment by rphmeier** [comment]
A bit more elaboration - ```rust
let mut nominations = <Staking as Store>::Nominators::get(&nominator_stash).unwrap();
let last_slash = |validator_stash| <Staking as Store>::SlashingSpans::get(&validator_stash).unwrap().last_start();
let submitted_in = nominations.submitted_in;

let active = nominations.targets.retain(|validator_stash| submitted_in >= last_slash(validator_stash));
```

**Comment by jacogr** [comment]
Closing. Active and Inactive are being indicated now.
