### ISSUE TITLE
More predictable ordering in the Accounts and AddressBook apps

### ISSUE THREAD

**Issue by kirushik** [polkadot-js/apps#2101]
As far as I understand, currently accounts in those lists are ordered by their public key when loaded from storage, but by their creation order when the new ones are added?

This is really unpredictable and confusing; any evident and reliable ordering (lexicographically by their names, by creation date etc) will be a huge improvement in my experience in those dialog windows.

**Comment by jacogr** [comment]
Currently sorting by created date, at least in accounts. As per the staking returns it would be good to have sorting on any column. (Name as well as balances here is async and problematic)

**Comment by jacogr** [comment]
Closing this. 

Like any urgent vs important discussion (which is how the next-up it prioritized), this doesn't mean it it won't add value, but rather that it won't get any focus. So the options are to have it sit gathering more dust or just be honest that based on capacity and focus-wise it will not get addressed.

If there is appetite for PRs to move things in the direction intended here, they will always be welcome.
