### ISSUE TITLE
Clicking in some areas of the icon in the address book triggers editing the account's name

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#2108]
This minor annoyance concerns almost no one...
This occurs only in the address book when clicking the following account if you are a registrar...

![image](https://user-images.githubusercontent.com/738724/72227613-0c42d480-359f-11ea-87cc-1929a493e619.png)

If you click in some areas of the icon, my guess is: where the icon is white/transparent, instead of opening the registrar popup, it triggers the editing of the accounts name.

**Comment by chevdor** [comment]
Similar in https://polkadot.js.org/apps/#/toolbox/verify
Clicking the account does not open the popup. That would be here very useful.

**Comment by jacogr** [comment]
Closing this. The SideBar removed this approach.
