### ISSUE TITLE
Warning about using non-added vanitygen accounts

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#2119]
I heard feedback from people using the vanity address generator, copying the address to receive funds and .... that's it. 
So without the private keys stored locally they no longer can spend the funds.

I would suggest to prevent any click on the icon or selection of the address in this page.
Any click in this area should show a popup saying that it is a very bad idea and the recommended way is to click on the + to store the account first. Or maybe directly do that for the user...

Unfortunately, for this app we HAVE to show the address otherwise the purpose of a vanity address generator would be limited.

**Comment by jacogr** [comment]
The click actually breaks my workflow and is inconsistent with the rest of the UI. Can certainly do with a warning there though.
