### ISSUE TITLE
Confusing 'transferrable' amount

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#2120]
By not taking the fee into account, the UI gives a false feedback.

In the screenshot below, it looks legit that what I am doing is OK:
![image](https://user-images.githubusercontent.com/738724/72359538-bb41f600-36ee-11ea-97b4-8b140e35b968.png)
However this will never work because what I can transfer is not the `transferrable` but `transferrable - fee`.

The fee shows on the next screen but then the `transferrable` value no longer. As a result, the user loses the fee and no transaction is done.

**Comment by jacogr** [comment]
This is a wontfix - since it needs to be added to all tx's actually. The only logical place is the signer, not all dialogs and trying to keep those in-check. Additionally, since these are no-more a local calc trying to do it (like in the past), on changes is a DDOS vector.

**Comment by chevdor** [comment]
I don't have better options either...

**Comment by jacogr** [comment]
To be incorporated in https://github.com/polkadot-js/apps/issues/2120

**Comment by jacogr** [comment]
Supposed to link to https://github.com/polkadot-js/apps/issues/2196
