### ISSUE TITLE
Judgements count error

### ISSUE THREAD

**Issue by lurpis** [polkadot-js/apps#2132]
Judgement not provided are also counted

![image](https://user-images.githubusercontent.com/4971052/72509227-16582200-3882-11ea-88b9-9464b95204b8.png)

**Comment by jacogr** [comment]
Umm, that first one is def wrong. Thanks.

**Comment by chevdor** [comment]
Many thanks for opening the issue @lurpis 

In this example, the data is:
```
"judgements": [
    [
      0,
      {
        "FeePaid": 25000000000000
      }
    ],
    [
      1,
      {
        "Reasonable": null
      }
    ]
  ],...
```

The problem is that FeePaid is counted as a judgement which is a little confusing.

**Comment by jacogr** [comment]
Yes, the enum with all the states are not correctly handled, I'm on it (it was on the list todo, this issue just bumped it to  P1 priority)
