### ISSUE TITLE
Unable to copy disabled fields on FF

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#2140]
![image](https://user-images.githubusercontent.com/1424473/72611328-14499e00-392a-11ea-814f-afcdec025791.png)

**Comment by Lowhearth** [comment]
After doing some research I've found out that there is a 16 years old discussion regarding this behaviour:  https://bugzilla.mozilla.org/show_bug.cgi?id=253870

It looks like they are making disabled inputs selectable for the next Firefox version.

We might want to swap disabled input to readonly if you dont mind the text cursor showing off @jacogr

**Comment by jacogr** [comment]
Welcome back! :)

Yes, there are 2 options -

- readonly (which works, we may adjust the cursor, will need to see what it looks like)
- swapping to a styled div

The first is the better approach, imho.

**Comment by jacogr** [comment]
So would just wait for the next release, browser update anyway. So would just forgo doing anything at all.

**Comment by jacogr** [comment]
Still an issue on 75.0 (for me). Will re-test when the next one rolls around.

**Comment by Tbaut** [comment]
Still an issue on 77. I'd actually love to address, it's been bothering me for so long :D !
Alternatively, I'd even propose to add a little "copy to clipboard" button on the right of the field. To do this well I guess it would mean creating a new "CopiableField" react-component and use it for the image hash.

lmk what you think @jacogr

**Comment by jacogr** [comment]
Just turn it into a static field with the correct styling. Don't want to wait another 16 years. Te copy-buttons is a slippery slope, where to add, where not to add, so not something that we really want to do.
