### ISSUE TITLE
Simplify specification of custom endpoint list

### ISSUE THREAD

**Issue by philipstanislaus** [polkadot-js/apps#2155]
# Description

Currently, endpoints are defined in node_modules/@polkadot/ui-settings. It would be great if there was an easy way to overwrite the default endpoint and endpoint list. 

# Usecase

At Centrifuge, we have 3 testnets, each with multiple nodes. It would be great if we could have these different endpoints in the dropdown, as opposed to having to copy paste the URLs. Ideally this change would comprise as little code modifications as possible, since we want to be able to simply upgrade to new releases of polkadot apps.

Many thanks!

**Comment by jacogr** [comment]
@philipstanislaus Would love your feedback on what is there now - any additional ideas welcome.

**Comment by philipstanislaus** [comment]
Sorry for my late reply, @jacogr – got knocked down by a nasty flu.

I just tried it out and it works like charm, thanks a ton! 👍 🎉

**Comment by jacogr** [comment]
Hope you are better. As always, if you think of ways to make it easier, let me know.
