### ISSUE TITLE
Add first-class council tip support

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#2167]
Some ideas from @chevdor & @emielvanderhoek

emiel [polkascan]
It could perhaps be a similar feature as how we deal with canceling slashes.

Jaco
Happy to hear ideas as to how to make tipping easier atm - it is on the list, but have not really dove in to make it easy yet.

Chevdor / Will
My 2 cents would be:

see in the UI how many 'todos' I have (similar to the council motions, referenda, tips, ...)
ideally, it excludes or show the remaining todos (todos can be aggregated council, referenda, tips, ... or not aggregated) such as TIPS: 2/7 (meaning, there are 7 tips open and I should take actions on 2 of them)
clicking on the todo shows a summary of the todos (tips, council motions, etc...) and the list
clicking on an item shows the current details (what is the thing, who did already take action, etc..)
it also shows a call to action to quickly make a decision
Tips make it tricky because I don't think you can actively ignore them.

emiel [polkascan]
Does this require a new storageFunction to list all open tip hashes at the very least in order for Polkadot JS Apps to deal with this?

Chevdor / Will
Since we expect Polkadot users to be active citizen, I think there should be the information on the landing page whether they have something to do or not, and if so, a link to a dedicated 'TODO' page where people can see how they can actively participate.
The current motion tab works pretty good. When I visit the page, if I dont see the little red badge, I just move on. On the other hand, if this little red number shows up, I know I have to check out the content and spend a little more time checking out what is to be done. Same for the referenda btw. The only thing missing IMO is to exclude or show differently when I have nothing more to do (in the case where I already voted on all referenda for instance)
I am sure the fact that it is missing is known and that it is only a matter of time...

**Comment by emielvanderhoek** [comment]
Current cumbersome steps are:

The following describes the cumbersome a council member could current apply:

## Creating new tips
1. Submit transaction `treasury`.`tip_new`
This transaction type can only be submitted by a council member.
Example: https://polkascan.io/pre/kusama-cc3/transaction/0xc935351527b558f7365b137e978fbc830bfcd03239c0a9b831854a0c5cd07ec0
A tip was created by Gav of 50 KSM.
![image](https://user-images.githubusercontent.com/14069142/72884126-e1c2eb00-3d05-11ea-9b16-016dbd0efc51.png)

2.  Submit transaction `treasury`.`report_awesome`
This transaction type can be submitted by anyone.
Example: https://polkascan.io/pre/kusama-cc3/transaction/0xdb3e1876db63ce7a5ba6646493edd29799413f6d07cbcba0ac315ac7b91c1a75
This signals something worthy of tipping by the council.
![image](https://user-images.githubusercontent.com/14069142/72884253-1d5db500-3d06-11ea-8349-d7c0e8c5e097.png)

## Identifying tips
Both options that create a new tip emit an event called: `treasury`.`NewTip`.

1. The following Polkascan page lists all new proposed tips: https://polkascan.io/pre/kusama-cc3/event?module=treasury&event=NewTip&page=1
![image](https://user-images.githubusercontent.com/14069142/72884765-f2279580-3d06-11ea-9f1c-eb6e1745bb6d.png)

2. If you click on the details of an event, you will find one event-attribute that identifies the tip's `hash`. 
Example: https://polkascan.io/pre/kusama-cc3/event/714498-5
![image](https://user-images.githubusercontent.com/14069142/72884824-12efeb00-3d07-11ea-9d54-7ced271e52c6.png)

## Tipping on open tips by council members 
You use this hash (example: 0x3a8576a1d7f9110e5d13d512bb8374bc0843da026dead68707462bb7f3e448b1) to tip by sending an extrinsic with `treasury`.`tip`(`hash`,`amount`). Please note that this action does not emit any new event.
![image](https://user-images.githubusercontent.com/14069142/72885169-b3460f80-3d07-11ea-8509-80264b56669c.png)

## Result of the action
This should result in a successful tip.
Example: https://polkascan.io/pre/kusama-cc3/transaction/0x4aad96037259c41aebac489f1fc6d0c3e4f2f871976efd93d2e6e448d97af79b
![image](https://user-images.githubusercontent.com/14069142/72885240-cb1d9380-3d07-11ea-8bd5-cf1e532a42a1.png)

## Primary objectives
Improve user experience for council members to tip on open tips as described above.
- Ease of identification of new tips.
- Ease of tipping.

**Comment by xlc** [comment]
I want to add that we also need a UI to call reportAwesome and it should tell user how much KSM will be reserved (1 + 0.01 * reason_length).
