### ISSUE TITLE
No error message during sign transaction by wrong password

### ISSUE THREAD

**Issue by edanilov** [polkadot-js/apps#2174]
<img width="984" alt="Screenshot 2020-01-16 at 01 50 28" src="https://user-images.githubusercontent.com/1274876/72974140-95e47480-3ddf-11ea-9301-0a9a739ff2b8.png">
If user sign transaction with incorrect password - no error message

**Comment by jacogr** [comment]
This is logged in the wrong repo, a duplicate onhttps://github.com/polkadot-js/extension/issues/211 (in the correct repo)
