### ISSUE TITLE
Bad UX for the transfer & fee

### ISSUE THREAD

**Issue by edanilov** [polkadot-js/apps#2175]
<img width="465" alt="Screenshot 2020-01-16 at 02 49 18" src="https://user-images.githubusercontent.com/1274876/72974318-db08a680-3ddf-11ea-85d5-7d521ca157f3.png">

I'm sending 1 KSM and it looks like 1.000 KSM
fee = 10.000m KSM is confusing as well
is better to use 0.1 KSM

**Comment by jacogr** [comment]
Fees are always displayed in milli. (And micro for Polkadot, in that case 3 decimals will not work.)

**Comment by edanilov** [comment]
but we are using numbers w/o decimals in amount fields -- just 1 KSM
why we are using different formats at one page?
