### ISSUE TITLE
transfer funds - no information about the current balance

### ISSUE THREAD

**Issue by edanilov** [polkadot-js/apps#2176]
<img width="887" alt="Screen Shot 2020-01-23 at 13 05 54" src="https://user-images.githubusercontent.com/1274876/72975021-2079a380-3de1-11ea-8d30-4d3c6a509bee.png">

No information about the current balance during transfer funds

**Comment by jacogr** [comment]
The info is only displayed on the actual transfer dialog, not the signer. (At this point, there is no context as to type of transaction or info thereof)

![image](https://user-images.githubusercontent.com/1424473/72976979-cd4d2400-3dd3-11ea-87cf-11962e41ec85.png)
