### ISSUE TITLE
Transfer funds - no amount validation

### ISSUE THREAD

**Issue by edanilov** [polkadot-js/apps#2177]
<img width="890" alt="Screen Shot 2020-01-23 at 13 06 52" src="https://user-images.githubusercontent.com/1274876/72975155-60d92180-3de1-11ea-833f-ecd64f26c91d.png">

I can put any numbers and press "make transfer"
it's not checking my current balance

expected:
impossible to add the sum that greater than my current balance minus fee

**Comment by jacogr** [comment]
Superseded. Re-adding the existing functionality for all relevant checks in https://github.com/polkadot-js/apps/issues/2196
