### ISSUE TITLE
Transfer funds - you can paste any text to amount field

### ISSUE THREAD

**Issue by edanilov** [polkadot-js/apps#2178]
if you have 0 or any other number in the amount field
you can paste from clipboard any text after this number (for example some scripts) and then delete this number.

<img width="894" alt="Screen Shot 2020-01-23 at 13 11 24" src="https://user-images.githubusercontent.com/1274876/72977727-28881200-3de6-11ea-9d05-f8849b20e786.png">

then you can press "Make Transfer" w/o any error messages
<img width="887" alt="Screen Shot 2020-01-23 at 13 05 54" src="https://user-images.githubusercontent.com/1274876/72977788-45244a00-3de6-11ea-898d-207e79460019.png">

**Comment by jacogr** [comment]
Actually not transfer related, this is anywhere where the InputBalance component is used. Low priority, nothing breaks. (Although we will need to sort out the paste handling at some point)

**Comment by jacogr** [comment]
Closing this. 

Like any urgent vs important discussion (which is how the next-up it prioritized), this doesn't mean it it won't add value, but rather that it won't get any focus. So the options are to have it sit gathering more dust or just be honest that based on capacity and focus-wise it will not get addressed.

If there is appetite for PRs to move things in the direction intended here, they will always be welcome.
