### ISSUE TITLE
Final approval of utility as_multi leads to error in events

### ISSUE THREAD

**Issue by philipstanislaus** [polkadot-js/apps#2179]
I'm playing around with multisigs right now, but when I do the final approval, I see this error in the events: 

`Uncaught error. Something went wrong with the data extraction, resulting in an error log.`

Steps to reproduce: 

1. Run: `docker run -p 9933:9933 -p 9944:9944 -p 30333:30333 parity/substrate:2.0.0-14720148 --ws-external --rpc-external --dev`
2. Submit the first multisig extrinsic:
<img width="1552" alt="Bildschirmfoto 2020-01-22 um 16 28 28" src="https://user-images.githubusercontent.com/6912756/72977872-a7c11a00-3dd5-11ea-9814-0a93b090ec03.png">
3. Inspect the events to find the AccountId of the "2 of Alice, Bob" multisig by inspecting the events, here `5F3QVb...MCh4Ch`: 
<img width="1552" alt="Bildschirmfoto 2020-01-22 um 16 30 20" src="https://user-images.githubusercontent.com/6912756/72977975-dd660300-3dd5-11ea-8b90-48dea2c2e155.png">
4. Send funds to that AccountId: 
<img width="1552" alt="Bildschirmfoto 2020-01-22 um 16 30 42" src="https://user-images.githubusercontent.com/6912756/72977999-e8b92e80-3dd5-11ea-9f60-9237947935fc.png">
5. Submit the second (final) multisig extrinsic:
 <img width="1552" alt="Bildschirmfoto 2020-01-22 um 16 31 42" src="https://user-images.githubusercontent.com/6912756/72978034-f5d61d80-3dd5-11ea-9aae-990978f9d9ed.png">
6. Find the error in the logs: 
<img width="1552" alt="Bildschirmfoto 2020-01-22 um 16 32 19" src="https://user-images.githubusercontent.com/6912756/72978068-07b7c080-3dd6-11ea-979e-0b7dec90358e.png">

Many thanks for helping resolving this!

**Comment by jacogr** [comment]
Brilliant! Thanks for the detailed report. This could very well be related to having an old implementation of DispatchError where the UI currently only supports the latest.

Will however follow along and attempt it on a current Substrate master.

**Comment by jacogr** [comment]
Just one question - do you have overrides for DispatchError in your types?

**Comment by philipstanislaus** [comment]
No, I’m actually running the substrate default node and the deployed Polkadot Apps. 

Thanks for the blazing fast turnaround! 🚀

**Comment by jacogr** [comment]
So 2 issues here -

1. The actual Error metadata for utility is not exposed, this is fixed here - https://github.com/paritytech/substrate/pull/4721
2. When finding non-existent (as above), the UI will now fallback to displaying the module/error struct (aka manual lookup) - https://github.com/polkadot-js/apps/pull/2182

**Comment by philipstanislaus** [comment]
Awesome, thanks!
