### ISSUE TITLE
It will be nice to have transfer funds page instead of modal window

### ISSUE THREAD

**Issue by edanilov** [polkadot-js/apps#2180]
It will be nice to have transfer funds page instead of modal window
+ history of your transactions
+ ability to repeat transactions

<img width="187" alt="Screen Shot 2020-01-23 at 13 13 22" src="https://user-images.githubusercontent.com/1274876/72978050-c2e85580-3de6-11ea-919a-ccf483be3578.png">

<img width="1338" alt="Screen Shot 2020-01-23 at 13 46 54" src="https://user-images.githubusercontent.com/1274876/72978108-dbf10680-3de6-11ea-9091-3963ef3600b2.png">

**Comment by jacogr** [comment]
We had an app, it was converted to a modal. For historic info, you need to refer to Polkascan, we don't have a DB, so we don't play the role of archiver with historic info. 

(Having said that, the acocunts page will get some very recent activity, but not in the form of transactions)
