### ISSUE TITLE
user can use the one address as to & from

### ISSUE THREAD

**Issue by edanilov** [polkadot-js/apps#2181]
<img width="917" alt="Screen Shot 2020-01-23 at 13 50 15" src="https://user-images.githubusercontent.com/1274876/72978380-69ccf180-3de7-11ea-9803-8148f60cd454.png">

Users can send funds from the current address to the same address.

Expected:
Close this ability
or inform users that they just will lose fee for this transaction

**Comment by jacogr** [comment]
There is nothing that disallows this, it is a valid transaction, so the UI won't block here.
