### ISSUE TITLE
remote node visible in https://polkadot.js.org/apps

### ISSUE THREAD

**Issue by stanieltron** [polkadot-js/apps#2185]
Hello,
first of all I would like to appologize for my lack of knowledge, but after 2 days of googling I am unable to move forward. Is there a manual what needs to be done for my node to be visible in "remote node/endpoint to connect to" wss://publicip:9944/ ,not localhost, so others can see my node?

**Comment by jacogr** [comment]
@iammelea has a document around the setup https://medium.com/@meleacrypto/kusama-polkadot-connect-ui-with-our-node-593d790f39f0

(Sadly, I have not done this myself, all I know is node -> proxy for ssl -> UI)

**Comment by stanieltron** [comment]
Thank you for answer. went through the steps and it still doesn't work. Compared to the document, I am not seeing 
![image](https://user-images.githubusercontent.com/16833434/73012499-c3004980-3e16-11ea-9d6a-56da45a78a29.png)
but 
![Capture](https://user-images.githubusercontent.com/16833434/73012579-eb884380-3e16-11ea-8628-e596d2451c2d.JPG)
Am I missing a prerequisite regarding websockets?

**Comment by jacogr** [comment]
I honestly cannot help - I would suggest asking for help in the Riot channels. 

As I stated above, I have never done this setup myself, nor run any setup like this. All I know is that the nodes needs an SSL proxy... How to go about that, no idea.

**Comment by iammelea** [comment]
> Thank you for answer. went through the steps and it still doesn't work. Compared to the document, I am not seeing
> ![image](https://user-images.githubusercontent.com/16833434/73012499-c3004980-3e16-11ea-9d6a-56da45a78a29.png)
> but
> ![Capture](https://user-images.githubusercontent.com/16833434/73012579-eb884380-3e16-11ea-8628-e596d2451c2d.JPG)
> Am I missing a prerequisite regarding websockets?

ping me on riot for help. :)

**Comment by jacogr** [comment]
Closing this as non-app related. (And really hop you get this sorted with the correct help)
