### ISSUE TITLE
Fix Tooltip component for server side rendering

### ISSUE THREAD

**Issue by mell-old** [polkadot-js/apps#2188]
At Subsocial we use apps components during server side rendering to have good SEO.
This requires React components to not use such browser objects as `window` and `document`.

In the next pull requests we fix this issue.
Could you please update the next tags and master?
- v0.34.1 -> https://github.com/mell-old/dappforce-subsocial-ui-apps/tree/fix-ssr-v0.34.2
- v0.37.1 -> https://github.com/mell-old/dappforce-subsocial-ui-apps/tree/fix-ssr-v0.37.2
- master -> https://github.com/mell-old/dappforce-subsocial-ui-apps/tree/fix-ssr-master

**Comment by jacogr** [comment]
Happy to apply PRs when made to this repo.

**Comment by siman** [comment]
I cannot make the corresponding PRs to certain versions of the apps, because versions (v0.34 and v0.37) are tags. It's not possible to create a PR for a tag on GitHub.

**Comment by siman** [comment]
The PR to master branch is here: https://github.com/polkadot-js/apps/pull/2265

**Comment by jacogr** [comment]
Closed in #2265
