### ISSUE TITLE
Support multi signature 

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#2200]
Cc @philipstanislaus

(Sorry, this was meant to be logged, not sure why it fell through the cracks)

**Comment by joshua-mir** [comment]
(let me know if this should be in a different issue) 

this seems relevant:

![Screenshot_20200414_223832](https://user-images.githubusercontent.com/43032097/79271945-f647f700-7ea0-11ea-8b8d-7db1535fffc5.jpg)

**Comment by jacogr** [comment]
Different issue ;)

**Comment by jacogr** [comment]
Done. Have multisigs in-place.

**Comment by philipstanislaus** [comment]
That's awesome, thanks @jacogr 🚀

**Comment by jacogr** [comment]
Should have closed this a couple of weeks ago.... :)
