### ISSUE TITLE
ANY transaction results in ExtrinsicStatus:: 1010: Invalid Transaction: 0

### ISSUE THREAD

**Issue by drandreaskrueger** [polkadot-js/apps#2205]
(While it worked months ago) anything I do now on https://polkadot.js.org/apps/ results in a RED

> ExtrinsicStatus:: 1010: Invalid Transaction: 0

For example, sending 55 DEV from Alice to Bob:

> balances.transfer
> submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: 0

I have tried the same with the 

> cd ../substratechainhammer-ui/
> yarn install
> yarn run dev
> http://localhost:8000/ --> Gav's Substrate UI

and it works just fine, on the exact same running node. I could transfer 888888 units from Alice to Bob.

In YOUR https://polkadot.js.org/apps/  it seems as if READ access works fine, e.g. 

> balances.freeBalance: Balance(Bob)
> 888888

but WRITE access fails.  Always.

My substrate node is based on this [repo branch v1.0](https://github.com/substrate-developer-hub/substrate-package/tree/v1.0), and it shows this status in your polkadot.js.org/apps : 

```
substrate-node v1.0.0
api v1.0.0-beta.26
apps v0.39.0-beta.104
```

Please help. Thanks.

**Comment by jacogr** [comment]
The deployed apps UI does not support Substrate V1 anymore. I would suggest updating to 2.x.

**Comment by jacogr** [comment]
Alternatively you may have success with http://substrate-ui.parity.io/#/explorer (It runs a very old version, which still has V1 support)
