### ISSUE TITLE
Improve contracts UX

### ISSUE THREAD

**Issue by Robbepop** [polkadot-js/apps#2230]
Original issue: https://github.com/paritytech/ink/issues/304
Proposal: https://github.com/paritytech/ink/issues/304#issuecomment-581351679

Problem: Many users suffer a great deal of confusions around contracts that are immediately evicted due to too few endownment upon instantiation.

Idea: It should be made more transparent to users if a contract was restored or evicted. The Polkadot JS Apps contracts UI can make use of the newly introduced events for restoration and eviction of contracts in order to improve the UX in this regard.

**Comment by jacogr** [comment]
Closing. Contracts UI re-done. (Any additional specifics may still be needed)
