### ISSUE TITLE
Extrinsics apps layout issue with `Option<Option<T>>` type

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#2233]
<img width="1305" alt="Screen Shot 2020-02-05 at 11 28 28 AM" src="https://user-images.githubusercontent.com/1201310/73793143-a39bf000-480a-11ea-9b70-c192302cf640.png">

Two include/exclude option button are generated which is correct but they are completely overlapped.

Try it here https://apps.acala.network/#/extrinsics

**Comment by adamdossa** [comment]
@jacogr one of the linked issues #8236 looks like maybe it is mis-classified - I left a comment on that issue, but noting here as #8236 has been closed, so not sure if it is still being monitored.
