### ISSUE TITLE
Council members specified in chain spec do not show up in Portal

### ISSUE THREAD

**Issue by philipstanislaus** [polkadot-js/apps#2235]
We have 5 council members specified in our chain spec that do neither show up in the UI: 

<img width="1011" alt="Bildschirmfoto 2020-02-05 um 14 37 03" src="https://user-images.githubusercontent.com/6912756/73846691-3b0e3c80-4825-11ea-9b71-9db7b1f2c91b.png">

Nor do the council members have activated buttons to propose motions.

But the members are showing up when querying the council members directly, and council members can also submit external proposals manually through the extrinsics tab: 

<img width="1011" alt="Bildschirmfoto 2020-02-05 um 14 36 57" src="https://user-images.githubusercontent.com/6912756/73846716-46616800-4825-11ea-9810-1fc7bd3ec181.png">

Here's our chain spec: https://raw.githubusercontent.com/centrifuge/centrifuge-chain/f32cb89e9da6186b8ce18c2e88b0981c66f66c3d/res/amber-spec.json

Any idea why this might be?

**Comment by philipstanislaus** [comment]
Version information: 

```
api v1.1.0-beta.14
apps v0.40.0-beta.4
```

**Comment by jacogr** [comment]
The UI only reports what is in `api.query.council.members()` - if it is not in there, it is not shown.

**Comment by philipstanislaus** [comment]
That's the thing, it is in the `api.query.council.members()` call, but it does not show up in the UI: 

<img width="1027" alt="Bildschirmfoto 2020-02-05 um 15 14 02" src="https://user-images.githubusercontent.com/6912756/73849431-38621600-482a-11ea-9331-94fd43d4035f.png">

**Comment by jacogr** [comment]
Then... we have a bug :( Marked as such, will take a look.

**Comment by jacogr** [comment]
Do you have elections or electionsPhragmen on your chain? (I was actually incorrect, we query those for the members - which should match once an election has taken place)

**Comment by philipstanislaus** [comment]
Got it. Yes, we have electionsPhragmen. But since we are currently in the first term, there were no elections yet. 

The current implementation implies that Polkadot Apps will never show a council and never allow council motions with the genesis council – until elections have take place, right?

**Comment by jacogr** [comment]
Yes. The linked PR will solve that bootstrapping.

**Comment by philipstanislaus** [comment]
Awesome, appreciate the very fast turnaround.
