### ISSUE TITLE
Account balances not visible for one account

### ISSUE THREAD

**Issue by philipstanislaus** [polkadot-js/apps#2236]
The account tab shows no balances for one of our accounts (weirdly, it works for other accounts on the same chain): 

<img width="1208" alt="Bildschirmfoto 2020-02-05 um 14 44 00" src="https://user-images.githubusercontent.com/6912756/73847223-1d8da280-4826-11ea-9826-9f80c0dc7813.png">

Querying the chain state directly shows the right balances: 

<img width="1208" alt="Bildschirmfoto 2020-02-05 um 14 44 42" src="https://user-images.githubusercontent.com/6912756/73847242-27afa100-4826-11ea-9b37-a199f2a69bd6.png">

Here are a few other calls in case that is relevant: 

<img width="1208" alt="Bildschirmfoto 2020-02-05 um 14 45 50" src="https://user-images.githubusercontent.com/6912756/73847291-4150e880-4826-11ea-8bed-c180200e4d81.png">

Versions: 
```
api v1.1.0-beta.14
apps v0.40.0-beta.4
```

**Comment by jacogr** [comment]
BalanceLock seems problematic since t is `<unknown>`. So the Ui/API tracks the latest substrate which has gotten rid of free & reserved balances, there is ow only `balances.account`. So in this case, I think the adjusted BalancesLock is messing things up.

Add this to your types `BalanceLock: 'BalanceLockTo212'`

**Comment by philipstanislaus** [comment]
That does indeed work, thanks!

<img width="1027" alt="Bildschirmfoto 2020-02-05 um 15 15 58" src="https://user-images.githubusercontent.com/6912756/73849562-72cbb300-482a-11ea-9330-d006cc257ef0.png">

**Comment by jacogr** [comment]
When you update to latest, ensure to remove them. I am honestly not always sure where/how/when to communicate these. (I do manage it for Kusama, always checking what goes in and what comes out, but that doesn't always help others)
