### ISSUE TITLE
Checkboxes in nominating are not available from android

### ISSUE THREAD

**Issue by TriplEight** [polkadot-js/apps#2239]
https://polkadot.js.org/apps/#/staking/actions -> set nominees
Checkboxes in a pop-up do not work on mobile.

**Comment by jacogr** [comment]
Yes, not quite sure we actually support mobile atm. Certainly don't have capacity for anything that is not stock-standard. So I am closing this one, not because it is not a one-day-maybe issue, but rather to keep focus on what is actually important.
