### ISSUE TITLE
Allow type overwrites through packages/app-settings/src/available/types.ts

### ISSUE THREAD

**Issue by philipstanislaus** [polkadot-js/apps#2242]
It would be great if we could overwrite types similarly to endpoints and languages through a file in `packages/app-settings/src/available/types.ts`. 

What do you think about that?

Many thanks

Philip

**Comment by jacogr** [comment]
We actually already do that in the API - eg. It has types specifically for chains such as Edgeware. 

It certainly is not an exclusive club, any substrate chain can actually add their types there. (Same with endpoints actually as well - happy to support any non-fly-by-night. )

(Will find a link to the exact types location in api in a short while, just on-the-go)

**Comment by jacogr** [comment]
Here we go - https://github.com/polkadot-js/apps/tree/master/packages/react-api/src/overrides

**Comment by philipstanislaus** [comment]
Awesome, thanks for the reply. Any chance we can add the places for overwrites in the README so it's easier for teams using apps/portal to find them?

**Comment by jacogr** [comment]
PRs welcome for both making your own life easier by adding types and the lives of other easier ;)

**Comment by philipstanislaus** [comment]
PR is here: #2268 , closing this. Thanks!
