### ISSUE TITLE
First endpoint in `packages/app-settings/src/available/endpoints.ts` should be the default node

### ISSUE THREAD

**Issue by philipstanislaus** [polkadot-js/apps#2243]
We have a custom list of endpoints in https://github.com/centrifuge/polkadot-js-apps/blob/master/packages/app-settings/src/available/endpoints.ts , but the Portal still loads flaming fir as the default node. 

It would be great if the default node would be the first entry in `packages/app-settings/src/available/endpoints.ts` instead. 

You can see this behaviour on https://portal.chain.centrifuge.io/

**Comment by jacogr** [comment]
Build with `NODE_ENV=production WS_URL=wss://<my url> yarn build` and it should pull in the default as specified as part of the `WS_URL` environment.

Need a better solution there.

**Comment by jacogr** [comment]
The above probably won't work, just took a peek - it _will_ work, but seem to always default to that URL then. Which, well, it not optimal, doesn't seem to be change-able.

**Comment by philipstanislaus** [comment]
@jacogr thanks, I meant actually something like this: https://github.com/polkadot-js/apps/pull/2250

**Comment by jacogr** [comment]
Should be fixed with this - https://github.com/polkadot-js/apps/blob/master/packages/apps/src/initSettings.ts#L21

**Comment by jacogr** [comment]
@philipstanislaus Could you please give it a play-through to see if it indeed does what it is supposed to? Hopefully got it right.

**Comment by philipstanislaus** [comment]
Just verified – works as expected. Many thanks!
