### ISSUE TITLE
Apps only includes Alice et al accounts on "Local Testnet"

### ISSUE THREAD

**Issue by JoshOrndorff** [polkadot-js/apps#2248]
When using a network named "Local Testnet" or "Development", the accounts for Alice, Bob, etc are pre-populated in the UI. This is great for demos and for workshops.

However, if the network name is changed (for example in the chainspec), then the Alice accounts no longer show up. This is a problem because changing the network name allows one to have a dedicated page in [telemetry](https://telemetry.polkadot.io).

Concretely, If I host a workshop in Denver, I want to send my participants to https://telemetry.polkadot.io/#list/Denver%20Testnet, but I still want them to have the Alice accounts pre-populated.

**Comment by jacogr** [comment]
the development flag is purposefully limited to, well, development networks. For instance we actually did have people using Alice as their accounts on Krumme Lanka...

You can certainly tweak it without own instances, but doubt that I am willing to open a door to known accounts for random networks here.

**Comment by JoshOrndorff** [comment]
One thought I had was to detect the network based on the `id` rather than the network `name`. Would that alleviate your concern?

For example, my chainspec might look like:
```json
{
  "name": "My Specific Testnet",
  "id": "local_testnet",
  ...
}
```

By still giving it `id: local_testnet` I indicate that it's safe to display the dev accounts, and by giving it a custom name I still get its own telemetry page.

Feel free to close if this is still out of scope.

**Comment by jacogr** [comment]
So you don’t receive the id via RPC (unless I am missing a trick, which is possible)

**Comment by JoshOrndorff** [comment]
Ah, you're correct.

My final thought is whether it makes sense to expose a setting on the settings page. Something like "Force inclusion of development accounts". It could be accompanied by an appropriately scary warning about how to accounts aren't at all secret when it is enabled.
