### ISSUE TITLE
Add a warning to prevent staking all the funds.

### ISSUE THREAD

**Issue by tomusdrw** [polkadot-js/apps#2261]
When user attempts to stake all possible funds and have set the rewards to be staked as well, we should warn them that they will need extra funds to do any other operation in the future (like unstake).

**Comment by jacogr** [comment]
Ties in with https://github.com/polkadot-js/apps/issues/2196

**Comment by jacogr** [comment]
UI warns that only 95% is a safe number - user can still choose to ignore.
