### ISSUE TITLE
Suggest missing funds to cover fees on `InvalidTransaction: Payment` error.

### ISSUE THREAD

**Issue by tomusdrw** [polkadot-js/apps#2262]
Currently the UI will trigger this:
![image](https://user-images.githubusercontent.com/581548/74230399-97a9a580-4cc4-11ea-8440-34e3919a0a03.png)

It might be a good idea to suggest that it's most likely that the user does not have enough funds to cover the transaction fees and they need to to up the account.

**Comment by jacogr** [comment]
Ties in with https://github.com/polkadot-js/apps/issues/2196
