### ISSUE TITLE
Endpoints from `packages/app-settings/src/available/endpoints.ts` show up as custom endpoints

### ISSUE THREAD

**Issue by philipstanislaus** [polkadot-js/apps#2269]
Endpoints from `packages/app-settings/src/available/endpoints.ts` show up as custom endpoints. 

<img width="1156" alt="Bildschirmfoto 2020-02-11 um 16 33 16" src="https://user-images.githubusercontent.com/6912756/74251416-63e27600-4cec-11ea-96c0-052c1864ebc1.png">

Steps to reproduce: 

Go to http://35.198.185.220/ , choose one of the endpoints from the dropdown list, reload the page. They all show up as custom.

**Comment by jacogr** [comment]
Looking at this now. This is _exceptionally_ weird since in the apps repo all endpoints are defined in there :( So not sure what causes this at all.
