### ISSUE TITLE
Edgeware balance is blank

### ISSUE THREAD

**Issue by qqonline** [polkadot-js/apps#2288]
see this please:

![image](https://user-images.githubusercontent.com/1336978/74799160-bb936980-530a-11ea-8e58-159d2902f1a7.png)

is this a bug?

**Comment by jacogr** [comment]
Thanks. Will take a look - it is quite possible the lock types being mismatched (there was some changes in Substrate lately).

**Comment by jacogr** [comment]
What is the address for this account? Tested on Berlin (all ok there), so actually will need to look at a specific failure to see what is missing.

**Comment by qqonline** [comment]
the address: jpsNCAjVmVsJM6QmBj1YumrFrFUp7ENyR44MXvDaZwwo5MF

I have staked 10 + 90 EDG before.
