### ISSUE TITLE
Accounts, New Password extra field, for new password verification

### ISSUE THREAD

**Issue by BCpowerup** [polkadot-js/apps#2333]
When changing the Password of any account, you are presented with 2 fields:
One for the active Password
One for the new Password
then you can submit....
I believe that an extra field is needed to verity the New password before the transaction goes.

**Comment by jacogr** [comment]
The eye icon allows you to check the password. But yes, considering that we will have a lot more “quick and dirty” users, it adds extra protection. (Protecting people’s from themselves)

**Comment by BCpowerup** [comment]
yeah, I wondered when i clicked the eye and double check and still was scare of making a mistake or added a character, triple checked. 

no 1-800 number to call!
