### ISSUE TITLE
HELP: How to correctly import an account created with ed25519?

### ISSUE THREAD

**Issue by HiZhaoYun** [polkadot-js/apps#2340]
Two types of encryption are provided when creating an account. Then, when importing an account through **mnemonic**, do we still have to choose the keypair crypto type when creating the account to correctly get the address I created?

**Comment by jacogr** [comment]
On the account creation screen, when you supply your own mnemeonic - you still need to select the type. (Only when you have a .json file no specification is needed)

**Comment by HiZhaoYun** [comment]
Thank you, jacogr:

**Comment by HiZhaoYun** [comment]
It seems a bit difficult for users to remember the encryption type they chose when they created their account :)

**Comment by jacogr** [comment]
Yes, I understand that. However tried to help - since it displays the address (shortened) as the type changes.

The mnemonic is just used to create the private key, the type is not embedded in there. So you can actually use the same mnemonic on Ethereum or Bitcoin as well, and will create a keypair based on the crypto there.

The fact that we support multiple types, makes it slightly more tricky.

**Comment by jacogr** [comment]
@HiZhaoYun Just ne final note before I am closing this - the extension uses sr25519 keys only. (It is meant to be simple, so 

(a) there is no option to select type and probably never will be
(b) it is meant to be used as-is, so users shouldn't care about the types

(The apps UI does all these "type" things, if it had to be started anew, it would only do 1 - it is a catch-all with broad support, not really100% end-user friendly). 

Would be really happy if other wallets build a kick-ass user experience.

**Comment by HiZhaoYun** [comment]
Agree with that, users shouldn't care about the types. After considering we intend to use only sr25519 keys too. i will try my best to build a user-friendly Polkadot wallet, although i did not pass WEB3 GRANT, lol..

Thanks for you reply.
