### ISSUE TITLE
Display frozen funds from voting on Accounts tab

### ISSUE THREAD

**Issue by lsaether** [polkadot-js/apps#2369]
I was confused for some time today when I was trying to send a transaction from one of my accounts and kept getting failures with `LiqudityRestriction`. 

I found that my funds had misc frozen `everything` by querying chain state:

![image](https://user-images.githubusercontent.com/25539605/76418896-bb353e00-639f-11ea-8a56-a3a8f620cfd7.png)

Yet when I look at my balances in the Accounts tab I see "All available" which is confusing. 

![image](https://user-images.githubusercontent.com/25539605/76418985-e586fb80-639f-11ea-87e7-24011c7002bb.png)

I didn't understand why there was a mismatch until I realized it was due to the lock I made for conviction when voting on  a proposal for Democracy. The UI should support showing when tokens are locked due to voting on proposals.

EDIT: I notice that "Transferable" is indeed 0. But it would be nice if this was more explicit.

**Comment by jacogr** [comment]
locked - "all available", it says none. So not sure what else? Wording change on "all available"?

**Comment by jacogr** [comment]
Slipped in the text change in #2370
