### ISSUE TITLE
Make the identity pop-up display above cursor if at the bottom of the page

### ISSUE THREAD

**Issue by lsaether** [polkadot-js/apps#2371]
The default action for the hover pop-up for identity information is to display below the cursor. This means that the information is unreadable if located at the bottom of the page (see screenshot).

![image](https://user-images.githubusercontent.com/25539605/76442518-5985cb80-63c1-11ea-8e1f-77a14e636952.png)

**Comment by jacogr** [comment]
Marked as P5, PRs welcome but will probably end up as something done as a one-liner is some other PR.

**Comment by jacogr** [comment]
Slipped it in as part of something unrelated.
