### ISSUE TITLE
Account sidebar with details

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#2373]
I propose a sidebar like in Slack / Riot when clicking on an address (rather than direct copy to clipboard) which would open and show details about that account like:

- Identity info
- Address book info
- Balance
- Council member (Y/N)
- Technical Committee (Y/N)
- Address (with prefix dropdown)
- Registrars who confirmed this identity

**Comment by jacogr** [comment]
Only the icon copies. (That will not and should not change, it is part of the actual Polkadot interface guidelines)

The name/address itself is non-clickable. So turning that into a click would be appropriate.

The stuff on the list is useful, the "Address with prefix dropdown" however won't be done. It should only display for the current ss58 as per chain definitions. I understand why some users will want this, however balk at the idea of making things even more complex than they already are with these.

The only other missing piece is probably "add to address book" on that list, would be good to have.

**Comment by Swader** [comment]
Indeed, sounds good.

>  it is part of the actual Polkadot interface guidelines

Can you tell me more about this?

**Comment by jacogr** [comment]
WIP, initial draft by Gav (there is a Riot channel with the people doing UI-related stuff like wallets, extensions, etc) - https://hackmd.io/-vcRp12EQcuyC9nvfs3GNA

**Comment by jacogr** [comment]
Closed in #2563
