### ISSUE TITLE
Proxy vote should accept Conviction

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#2381]
Submit extrinsic > Democracy > Proxy Vote only accepts a referendum index and a vote (aye/nay). However, a vote is a struct of aye/nay and `Conviction`. This should be part of submission.
```rust
/// A number of lock periods, plus a vote, one way or the other.
#[derive(Copy, Clone, Eq, PartialEq, Default, RuntimeDebug)]
pub struct Vote {
	pub aye: bool,
	pub conviction: Conviction,
}

fn proxy_vote(origin, #[compact] ref_index: ReferendumIndex, vote: Vote) -> DispatchResult
```

![image](https://user-images.githubusercontent.com/25483142/76640350-10b04d00-6550-11ea-8dc3-9ff45a37a6ad.png)

**Comment by jacogr** [comment]
Invalid. What is there is correct as per the chain. It is rendered based on metadata. There are only 2 params.

**Comment by gavofyork** [comment]
`proxy_vote` has since been removed.
