### ISSUE TITLE
Council motion duration countdown

### ISSUE THREAD

**Issue by emielvanderhoek** [polkadot-js/apps#2394]
With the new Prime council member feature, inactive council members will give a default vote similar to the prime council member's vote at the end of the `CouncilMemberDuration` as set here: https://github.com/paritytech/polkadot/blob/c03658dc8483181a224c2bd48629a84adeb7b224/runtime/kusama/src/lib.rs#L342

It would be good to provide the (other) council members some indication that this duration is expiring. One suggestion would be a countdown from the start (block) of the motion.

Possible complications: 
- Currently the `CouncilMemberDuration` is hard-coded and set for 3 days [43200 blocks] in case of Kusama. Ideally this should be a runtime constant.
- It is unknown to me if it is easy to determine the block at which a motion was proposed. That block should serve as baseline from which the countdown starts.

**Comment by jacogr** [comment]
The new `Votes` structure has the end time for the proposal, https://github.com/paritytech/substrate/blob/master/frame/collective/src/lib.rs#L100

**Comment by emielvanderhoek** [comment]
ah thx. well then apart from the remark regarding `CouncilMemberDuration` not being a runtime constant this should not be too difficult to implement.
