### ISSUE TITLE
Show Adaptive Quorum Biasing in Democracy

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#2418]
Either when hovering over Aye or Nay, or as separate row / column permanently in the proposal's box, there should be AQB calculations present showing how much a certain side is really winning, with a "needs X to pass" or "needs X to fail" infoblip.

If this is too specific to be included in Apps UI, I'd be happy to develop it as a Chrome extension, though I think many would find it useful in this context.

**Comment by jacogr** [comment]
fk. BN.js breaks with sqrt inside prod. No idea.
