### ISSUE TITLE
Docker image is outdated

### ISSUE THREAD

**Issue by igorline** [polkadot-js/apps#2419]
I've tried using docker image for polkadot-ui but unfortunately it seems to be outdated.
This is what is being served from the image:
```
api v0.81.0-beta.3
apps v0.34.0-beta.7
```

UI is not connecting to substrate failing with several errors like:
![image](https://user-images.githubusercontent.com/1465430/77066381-51daae00-69e3-11ea-9b71-13b2a6bf2d6b.png)

I contacted @chevdor and agreed I'd open an issue to keep track on this.

**Comment by jacogr** [comment]
Would really suggest not even trying to use a pre-published image here - this is not built from CI. It will always be _way_ outdated.

The Dockerfile is there, rather build the docker image from a fresh opy.

**Comment by chevdor** [comment]
A solution would be to include the image building to the CI. But I also think this image is not optimum.
I am looking into it. If I can do a fix quickly, I will send a PR. Otherwise, it will have to wait a little longer.
The option to build the image locally is anyway always a good one and since the UI changes **very** frequently, that is likely the best pick for now.

**Comment by chevdor** [comment]
So if that helps I just builds and pushed `chevdor/polkadot-ui` but at the pace @jacogr works, this will likely be deprecated in a few hours at best :)

**Comment by chevdor** [comment]
The following will not improve the CI and automatic build of the image but it will help in the future for a more convenient image: https://github.com/polkadot-js/apps/pull/2421

**Comment by chevdor** [comment]
See also #2422

**Comment by chevdor** [comment]
See also https://github.com/polkadot-js/apps/pull/2450

**Comment by jacogr** [comment]
Ok, so with the stuff like IPFS & electron being published on release, we can actually do the docker at the same point.

**Comment by jacogr** [comment]
Closing. Docker images are now published via CI (release/stable).
