### ISSUE TITLE
Consistent styling, theme & colours throughout

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#245]
Basic SideBar styling introduced in https://github.com/polkadot-js/apps/pull/243. Extend this with a common style across the board, at this moment the actual apps feels somewhat misplaced with the default blue + blue styling.

**Comment by jacogr** [comment]
"help wanted" - need somebody with a good eye for detail and styling to help on what works as what doesn't.

**Comment by Tbaut** [comment]
What about something very simple with the same pink and black?
I'd be happy to help.
![image](https://user-images.githubusercontent.com/33178835/44406541-2fa95180-a55c-11e8-8370-88f51f3bc470.png)

**Comment by jacogr** [comment]
PRs are very welcome. I did play a bit with the dark grey buttons and it almost felt a bit too much and almost too dull since the text is exactly the same color. And pink is a highlight color, so should probably not be overused, i.e as links in my view it is too much, it may work as a primary button color, but will need to see what it actually does on-screen.

So what needs to be looked at -

- primary buttons (the current blue ones)
- negative buttons (the current red ones)
- vote (negative & positive) buttons (the current green & red ones)
- links
- not to be forgotten is the switch buttons (i.e. top of accounts, addresses, etc)

Overall it is not too involved, couple of styles to override `.primary`, `.secondary` (if needed), `.negative`, `.positive` & `a`

At this exact point I cannot quite spend time on it myself, the time vs outcome reward is just not there.

**Comment by Tbaut** [comment]
I'll give it a try and see what come out.
