### ISSUE TITLE
Submit button for redeemable funds causes unreadable funds info

### ISSUE THREAD

**Issue by laboon** [polkadot-js/apps#2484]
If you have funds to redeem, the "Submit" button causes the info in that section to be unreadable.  Resizing the browser window does not change this, no matter how big I made it.

<img width="305" alt="Screen Shot 2020-03-30 at 11 35 54 AM" src="https://user-images.githubusercontent.com/1417717/77899455-02b33980-727d-11ea-8e23-080be7250ed8.png">

This is solved by redeeming the funds.

<img width="236" alt="Screen Shot 2020-03-30 at 11 55 05 AM" src="https://user-images.githubusercontent.com/1417717/77899776-56be1e00-727d-11ea-9b4e-0b70bcbcdb35.png">

**Comment by jacogr** [comment]
Thank you. Aware of this, busy reworking this layout in https://github.com/polkadot-js/apps/tree/jg-bonding-display so should be in/adapted a bit later today.
