### ISSUE TITLE
Uncaught error. Something went wrong with the query and rendering of this component.

### ISSUE THREAD

**Issue by wjy19990622** [polkadot-js/apps#2500]
when i oprate the collective module of substrate, the error appear for example:
![Uploading 议会模块.png…]()

**Comment by jacogr** [comment]
You really need to be a bit more specific - what were you doing exactly?

**Comment by wjy19990622** [comment]
i pull the substrate code on March 20th，but today when i oprate the function what  "excute" and  "propose" in TechnicalCommittee or  Council, the error appear.

**Comment by wjy19990622** [comment]
![议会模块](https://user-images.githubusercontent.com/45120344/78146569-e70a8780-7464-11ea-9faa-39ca071548db.png)

**Comment by jacogr** [comment]
Thank you, ok that is a trail I could follow. PR open.
