### ISSUE TITLE
Enum type can't show all

### ISSUE THREAD

**Issue by wjy19990622** [polkadot-js/apps#2511]
in my substrate project, when i use the function "transfer" in balances module,  it allway show that should input AccountId but can't input AccountIndex. that is a bug? and what should i do.
![qianduan](https://user-images.githubusercontent.com/45120344/78346528-b6942c00-75d1-11ea-8589-2ae39c7de1cd.png)

**Comment by wjy19990622** [comment]
there is the "LookupSource":
`pub enum Address<AccountId, AccountIndex> where
	AccountId: Member,
	AccountIndex: Member,
{
	/// It's an account ID (pubkey).
	Id(AccountId),
	/// It's an account index.
	Index(AccountIndex),
}`

**Comment by jacogr** [comment]
It is intentional. LookupSource/Address/AccountId will always only allow you to select from the Address input. There is additional code, maintenance and support to allow selection from either the dropdown or an input.
