### ISSUE TITLE
Democracy tab issue

### ISSUE THREAD

**Issue by illlefr4u** [polkadot-js/apps#2517]
After [I voted](https://polkascan.io/pre/kusama/transaction/0x07dd6d74d8d0be4fd3b9bf039ebb06b23dde38d891b204a39503c8695c6aca3b) for referendum #44, on the "democracy" tab, I always started to receive the following error message (even on different computers): "Uncaught error. Something went wrong with the query and rendering of this component."
![js1](https://user-images.githubusercontent.com/21253681/78468168-627d6a80-76eb-11ea-9d7e-1f2cc6499d48.png)

**Comment by jacogr** [comment]
Sadly saw it and fixed it before I saw this. The display didn't cater for 6x (stoopid misalignment with underlying types) - should be all ok now :)
