### ISSUE TITLE
With no accounts, Extrinsics should not be allowed?

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#257]
Currently it does not render the accounts -

<img width="1440" alt="polkadot apps portal 2018-08-23 12-41-19" src="https://user-images.githubusercontent.com/1424473/44521006-e844d180-a6d1-11e8-84e6-07fb5a7ca754.png">

As opposed to this when there are accounts -

<img width="1440" alt="polkadot apps portal 2018-08-23 12-43-36" src="https://user-images.githubusercontent.com/1424473/44521100-38bc2f00-a6d2-11e8-9561-8c8d3dec8212.png">

Available options (one of) -

1. Render empty accounts (disabled, indicating adding needs to take place)
2. Don't allow access to the section

**Comment by marnibrewster** [comment]
Hi - I'm new here, hoping to get involved and hopefully help! I think I have a solution using option 1, which presents an 'Add Accounts' button if none are available, redirecting users to the Accounts page. Shall I create a PR?

**Comment by jacogr** [comment]
@marnibrewster Please do. Any PRs are welcome. I think it will make things much cleaner.

**Comment by jacogr** [comment]
Closed in #273
