### ISSUE TITLE
broadcasting pop-up does not close and shows continious loading

### ISSUE THREAD

**Issue by illlefr4u** [polkadot-js/apps#2576]
Broadcasting pop-up does not close and shows continious loading while sending extrinsics at substrate-network, but not in Kusama.

Extrinsics are executed and goes to the network. 

Console log:
![polkadot_js_error1](https://user-images.githubusercontent.com/53624542/79498158-3e7d2b80-7fff-11ea-8fab-2c12cf2ae444.png)
![polkadot_js_error2](https://user-images.githubusercontent.com/53624542/79498147-3c1ad180-7fff-11ea-8369-2c99bce20d3a.png)
The same behavior was on crowdcast today starting from https://www.crowdcast.io/e/Fiat-Collateralized-Stablecoin-with-Substrate

The same behavior was on [webinar today](https://www.crowdcast.io/e/Fiat-Collateralized-Stablecoin-with-Substrate) (starting from 35:40 minutes)

**Comment by jacogr** [comment]
https://polkadot.js.org/api/start/FAQ.html#using-a-non-current-master-node-i-have-issues-parsing-events

**Comment by illlefr4u** [comment]
but it works yesterday on IPCI-network definitely. Does this change anything?

**Comment by jacogr** [comment]
It went in this morning.
