### ISSUE TITLE
extrinsic call should allow for 0

### ISSUE THREAD

**Issue by GregTheGreek** [polkadot-js/apps#2592]
More of a nit, but would be nice.

If a user is interacting with an extrinsic of type int/uint the default value is `0` but the ui prevents the user from actually submitting that value, and you need to reset the input

**Comment by jacogr** [comment]
Checked the current against extrinsics containing balances, numbers (indexes) and others. Couldn't spot a specific case at this point that still has the issue. (Default substrate master chain & Polkadot)

Closing, feel free to re-open if there is a specific instance found that doesn't quite comply.
