### ISSUE TITLE
Cannot use return/enter to submit extrinsics 

### ISSUE THREAD

**Issue by phillux** [polkadot-js/apps#260]
Upon entering my password, it would be nice to be able to hit return to submit the extrinsic.

It would also improve the UI to make the 'cancel' button outlined and the 'submit' button heavy, so that the user can easily see which button is the default when pressing return.

![plk1](https://user-images.githubusercontent.com/6450379/44576218-47681c00-a78e-11e8-8e47-f08e8aa9153d.png)

**Comment by jacogr** [comment]
Additionally - the password needs to be auto-focussed when the modal opens.
