### ISSUE TITLE
Display real extrinsic costs when interacting with contracts

### ISSUE THREAD

**Issue by athei** [polkadot-js/apps#2608]
With an upcoming PR (https://github.com/paritytech/substrate/pull/5712) the weight and therefore the fees of any contract related extrinsic will reflect the real costs of that extrinsic. Previously the gas costs where on top as a completely separate matter. This distinction is gone.

That means the `TransactionPaymentApi::query_info` will take into account the `gas_limit` of an extrinsic (or the code length for `put_code`) and returns the complete costs for the sender as for any other extrinsic.

However, during my tests with the linked PR I noticed that for the contracts module the costs that the UI displayed when sending an extrinsic stays fixed no matter what gas limit I supply:
<img width="912" alt="Screenshot 2020-04-23 at 09 47 41" src="https://user-images.githubusercontent.com/2580396/80073918-c1930a00-8548-11ea-9fef-7783bdc4d4ce.png">

This is different from other modules where this fee seems to change when the weight of an extrinsic changes given another input. I guess that this behavior is somehow disabled in the contracts UI.

I suppose to display the fees as calculated by `TransactionPaymentApi::query_info`  when submitting a contract extrinsic as for any other extrinsic. However, we should change the wording slightly as those costs are a maximum and the rest is refunded. This is true for all extrinsics lately but contracts might be an extreme case. I propose something like this:

> According to (your entered gas limit | the length of the supplied wasm blob) fees of at most $UNIT Unit will be applied to the submission

**Comment by jacogr** [comment]
Please move this to substrate - the UI calls `query_paymentInfo` if incorrect, it is not returning the correct results.

**Comment by athei** [comment]
I cannot find a function with this name. Is this distinct from the `TransactionPaymentApi::query_info` I mentioned?

**Comment by jacogr** [comment]
https://polkadot.js.org/api/substrate/rpc.html#queryinfo-extrinsic-bytes-at-blockhash-runtimedispatchinfo

https://github.com/paritytech/substrate/blob/master/frame/transaction-payment/rpc/src/lib.rs#L33

**Comment by athei** [comment]
I did a little investigation. Everything is working as intended. I mistakenly thought that the weight contribution was not accounted for. In reality the numbers were just too small to notice it in the UI because of #2604. So nothing is to be done here.
