### ISSUE TITLE
Add warning dialogues when sending invalid transfers

### ISSUE THREAD

**Issue by phillux** [polkadot-js/apps#261]
Currently there are a few instances where a user is unable to perform an action. There should be warning messages to notify the user that they will be unable to send certain extrinsics.

- Sending amounts that are too low
- Unstaking or unnominating from accounts with too low of a balance

There are probably other cases, so please add them if you've come across them.

**Comment by jacogr** [comment]
Duplicate of - https://github.com/polkadot-js/apps/issues/71

(Additionally, prefer warning labels as to overwhelming with dialogs)

**Comment by phillux** [comment]
Duplicate of #71
