### ISSUE TITLE
wrong numbers at democracy tab

### ISSUE THREAD

**Issue by illlefr4u** [polkadot-js/apps#2616]
It looks to me that there are some problems with calculating/showing the total amount of "nay" votes. In the screenshot, I counted only 11.600 KSM votes "nay", while the UI shows 514,640.6 KSM.
![js_ui_nay1](https://user-images.githubusercontent.com/21253681/80148795-f2486300-858b-11ea-91d1-4bc77d23299e.png)

**Comment by jacogr** [comment]
So in all cases the top number is not calculated, it is rather what is in the state. I saw that, something goes wrong _somwhere_ and not sure what it is exactly. (What I didn't do was query the state entry for the total, which)

**Comment by illlefr4u** [comment]
As far as I saw, the sum of the votes "aye" was calculated correctly.

**Comment by jacogr** [comment]
So are you suggesting that you did query the state? And saw the displayed values not matching?

That top number should be displayed as exactly from the state, with the current democracy it does not get calculated, aka the columns is just a representation of what is retrieved. So what seemed to happen is that the 0.1x's were 1x's. Will try and replicate on a dev chain, really weird.

Agreed there is an issue _somewhere_, just not sure where.

**Comment by illlefr4u** [comment]
Unfortunatelly I didn't query the state. Therefore, the scope of the possibilities not yet diminished.

**Comment by jacogr** [comment]
As discussed, the numbers are correct, but atm the list does not show the delegations - will add those.
