### ISSUE TITLE
Contract UI RPC/Transaction toggle gets "stuck"

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/apps#2617]
When interacting with a contract, you can submit calls as "RPC" or as "Transaction" using a toggle.

For "read" calls, you have access to the toggle, to switch between these two options, however for "write" calls, the toggle is disabled.

"stuck" as RPC:
<img width="896" alt="image" src="https://user-images.githubusercontent.com/1860335/80157773-36a52480-85c7-11ea-8438-9a566b67d0a4.png">

"stuck" as transaction:
<img width="896" alt="image" src="https://user-images.githubusercontent.com/1860335/80157792-3f95f600-85c7-11ea-8b95-70d6ed6dfed9.png">

toggleable with a "read" call
<img width="896" alt="image" src="https://user-images.githubusercontent.com/1860335/80158102-f6927180-85c7-11ea-9bf1-73fbe8b2c440.png">

To reproduce, go into a "read" call where you can adjust the toggle, switch the toggle, then go into a "write" call, where the toggle is now locked in whatever position you left it.

In general the behavior of this toggle is weird since it does not make sense to make a transaction call when it is a read-only operation, and this is currently the function which enables the toggle. Toggle should be used for the mutable transactions instead.

I suggest the following behavior:

* non-mutable functions: Only allow RPC, never allow Transaction
* mutable functions: Enable Transaction by default, enable a user to do RPC instead with toggle

cc @Athei @robbepop

**Comment by jacogr** [comment]
Hopefully done after the rewrite of the contracts app. (Soon to be outdated because of the metadata updates)
