### ISSUE TITLE
Voting balance does not take treasury proposal bonds into account

### ISSUE THREAD

**Issue by emielvanderhoek** [polkadot-js/apps#2618]
Voting balance showed as ~348 KSM.
I tried to vote with the amount of 250 KSM with 1x conviction. It gave the 'insufficient funds' error.
![image](https://user-images.githubusercontent.com/14069142/80190731-097f6300-8615-11ea-9aa7-667c93d04858.png)

I suspect this had to to with the two bonds for the treasury proposals.
![image](https://user-images.githubusercontent.com/14069142/80191128-8f9ba980-8615-11ea-8b27-eb4e83a1b22c.png)

**Comment by jacogr** [comment]
Weird, will need to check. It should handle all locks as they appear.

**Comment by jacogr** [comment]
Ok, it does not appear in balances.locks, so it is not taken into account.

**Comment by Tbaut** [comment]
Taking a look at this one.

**Comment by jacogr** [comment]
There has actually been an adjustment in the API for this already. To make a long story short -

- the voting balance is free + reserved for council
- for democracy it is free

So the API always had votingBalance as free+reserved. (Actually the above now is fixed, however council under-reports voting balance now... I think)

**Comment by Tbaut** [comment]
Yes that's not an issue anymore :tada:. Closing.

**Comment by Tbaut** [comment]
> However council under-reports voting balance now... I think

Checking this, will open an issue + PR if that's the case.
