### ISSUE TITLE
txpool display application

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#262]
- show list of extrinsics in the pool (Extrinsic decoding component)
- requires proper pendingExtrinsics decoding on the API
- for Extrinsic decoding, it is already done in app-explorer in the block view

It could possibly be combined into the explorer?

**Comment by ltfschoen** [comment]
@jacogr I've made an initial attempt at this. I've pushed polkadot-js/apps changes to branch ["luke-262-txpool"](https://github.com/polkadot-js/apps/compare/luke-262-txpool?expand=1). I've pushed polkadot-js/api changes to branch ["luke-apps-issue-262-txpool"](https://github.com/polkadot-js/api/compare/luke-apps-issue-262-txpool?expand=1).
However when see if it works and go to http://localhost:3000/#/explorer, it gives me browser console error: 

```
observable.tsx?065d:77 withObservable:subscribe pendingExtrinsics RangeError: Maximum call stack size exceeded
    at ApiCombined.pendingExtrinsics (Combined.js?87b1:138)
```

**Comment by jacogr** [comment]
To be included in https://github.com/polkadot-js/apps/issues/568
