### ISSUE TITLE
Fix sample 'Listen to balance changes'

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#2635]
Content:
```
const ALICE = '5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY';

// Retrieve the initial balance.
let previous = await api.query.balances.freeBalance(ALICE);

console.log('ALICE has a balance of ' + previous);
```

This is no longer valid and should be:

```
const ALICE = 'DbF59HrqrrPh9L2Fi4EBd7gn4xFUSXmrE6zyMzf3pETXLvg';

// Retrieve the initial balance.
let previous = await api.query.system.account(ALICE);

console.log('ALICE has a balance of ' + previous.data.free);
...
```

**Comment by jacogr** [comment]
It is valid on some chains ;) so each one of the 3 locations may be valid depending on chain config -

- System.account
- Balances.account
- Balances.freeBalance

(The UI actually does detection for each for display, any can work and may be valid)

So the example should be extended to cater for all 3, via detection (like the api derives does), or just removed.

**Comment by chevdor** [comment]
Even without detection, having the 3 examples and a little comment explaining that 2 will likely not work would be already a good start.
