### ISSUE TITLE
Treasury overview: proposals & approved counts flipped?

### ISSUE THREAD

**Issue by bjornwgnr** [polkadot-js/apps#2646]
![Screenshot 2020-04-28 at 10 33 42](https://user-images.githubusercontent.com/17831185/80465850-06011a00-893c-11ea-9129-d6023375a076.png)

**Comment by jacogr** [comment]
Slipped a fix in alongside something else https://github.com/polkadot-js/apps/pull/2647/commits/845e0d94cbc848852f90ce2d01b2ceabf0c7007a
