### ISSUE TITLE
Cannot nominate any non-intention address

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#266]
Using polkadot-js-ui v0.19.51

I have an account that wants to nominate :)

I can pretty much nominate any address (I tested a few):
![image](https://user-images.githubusercontent.com/738724/44718634-f2474580-aac0-11e8-8753-49a81ccc1bf1.png)
If you need to copy/paste , this is the address: `5END82tfD39fvgwxe9qCkZJxtyQCtFJXzeSnBXpAR2D7vhZT `

The next however, does not work!
![image](https://user-images.githubusercontent.com/738724/44718646-fc694400-aac0-11e8-8d43-7c5ee8bc3ddf.png)
The address is `5HMeowwuJACuZwRLFbNMxgdKKKKGKjiFVUFrPF2tayK5e3rT `

So @Tbaut I am sorry, I cannot nominate you!

The addresses have the same length:
```
OK       5END82tfD39fvgwxe9qCkZJxtyQCtFJXzeSnBXpAR2D7vhZT
NOT OK   5HMeowwuJACuZwRLFbNMxgdKKKKGKjiFVUFrPF2tayK5e3rT
```

**Comment by jacogr** [comment]
You can only nominate those in the intentions list - 

`5Hmeowj4H5JzbWqWDY7cy7ZxF2Ka6hiewxaJrMqJCSkpciA4` is the correct/current address.

(Reporting errors are missing there)

**Comment by jacogr** [comment]
We should just display a helpful error message, e.g.

- address is invalid (not in this case, but possible)
- address is not intending to stake (in this case)
