### ISSUE TITLE
Can't add an address to the address book if already known (but not saved manually)

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#268]
I wanted to add Chevdor to my address book, but I had looked up his address in the past, so it got automatically saved, for instance in extrinsics:
![image](https://user-images.githubusercontent.com/33178835/44837753-bc2dd100-ac3a-11e8-8559-adf8ecb6b05e.png)

When I want to add it to the address book using `add address` tab, the save button remains disabled. This only happens for "ever used" addresses. The workaround is to go to `edit address` tab where I can find his address under "recent", it had been saved automatically with an empty name. I think it can be confusing.

A suggestion:
- merge `edit` and `add` by:
  - showing a list of saved addresses instead of a drop-down to have a better overview
  - have an edit button for each entry on mouse over (as shown below)
  - have a button to add an address at the top
  - show a field similar to what we have at the top of the window upon editing/adding an entry (see below)
  - if the user wants to add an address that is known, switch from "adding" to "editing" mode by showing the name the that is already used.

Overview with edit/forget on mouse over
![image](https://user-images.githubusercontent.com/33178835/44840435-509b3200-ac41-11e8-8799-029b579752db.png)

Upon adding a new address
![image](https://user-images.githubusercontent.com/33178835/44840270-fd28e400-ac40-11e8-8684-c49e5373babd.png)

**Comment by jacogr** [comment]
The validation needs to show the results -

1. Address invalid
2. Address already in addressbook

(Not just fail silently)
