### ISSUE TITLE
ChainState shows default values rather than "no entry" when looking up vacant entries in maps

### ISSUE THREAD

**Issue by Sushisource** [polkadot-js/apps#2695]
When looking up entries in maps in storage using the ChainState/Storage page, the UI will return a default instance of whatever the value type of the map is if there is no entry in the map for that key.

This behavior is I think incredibly confusing, as for most datatypes the default value is one that many actual entries might reasonably take. The UI should simply indicate that nothing was found at the storage location rather than lying and producing the default.

Thanks!

**Comment by jacogr** [comment]
This is 100% the correct behavior. The metadata specifies the fallback value that should be used in all cases where the entry is not available. This aligns the behavior between what happens on the Rust side and the API side.

**Comment by Sushisource** [comment]
@jacogr OK, thanks for the info. Is there a reason why given somewhere? The actual rpc returns `null` - I guess I'm not sure why I'd need or want to make my map values `Option<T>` when that information is already embedded in the map. Seemingly the API is already giving you the information needed to tell if there was an entry or not, so it's not a matter of disguising that?

**Comment by jacogr** [comment]
Exactly as specified by the metadata. Here decoded as an example, the fallback determines what the API must return in the case of null.

```
              {
                "name": "Payee",
                "modifier": "Default",
                "type": {
                  "Map": {
                    "hasher": "Twox64Concat",
                    "key": "AccountId",
                    "value": "RewardDestination",
                    "linked": false
                  }
                },
                "fallback": "0x00",
                "documentation": [
                  " Where the reward payment should be made. Keyed by stash."
                ]
              },
```

Which is exactly what also happens on the Rust client. We cannot have different behavior on one side vs the other. Hence the use of the fallback.

**Comment by Sushisource** [comment]
@jacogr Thanks, I understand that the metadata is specifying the fallbacks. My question was really "why?", specifically "why hide that a fallback was used, and why *must* a fallback be specified?". I understand why you might like to specify a fallback, that makes perfect sense - but why not have the UI indicate that it used the fallback. (IE: There is no way to tell in the UI if a fallback value was used, or if the map actually had an entry in it equal to the fallback, without actually inspecting the reply).

This appears to be the docs I could find around this: https://polkadot.js.org/api/cookbook/storage.html#how-do-i-check-for-storage-existence and https://substrate.dev/docs/en/next/development/module/storage#default-value -- the runtime docs indicate you *can* specify a default, which sort of implies it's optional, but the type constraints force you to use a `Default` type. So defaults are required, but it'd be informative to understand why. 

Thanks!
