### ISSUE TITLE
Register parachain: initial head state

### ISSUE THREAD

**Issue by akru** [polkadot-js/apps#2712]
**Motivation**

I guess [initial head state](https://github.com/polkadot-js/apps/blob/master/packages/page-parachains/src/Overview/Register.tsx#L129) field should be a hex-string field instead of a file. In case of a file it will be prefixed by content length. As result it could not be parsed by collator.

**Proposal**

Replace file input by hex-string input.

**Comment by jacogr** [comment]
It should support both.

**Comment by akru** [comment]
Got it, unfortunately right now it’s file only.
I think so, is better to make it support both.

**Comment by jacogr** [comment]
Closing alongside https://github.com/polkadot-js/apps/issues/3396 (the inputfile hex is now properly detected, so the modal will work as expected with the file outputted as opposed to resorting to hex)
