### ISSUE TITLE
Multisigs & Staking Actions

### ISSUE THREAD

**Issue by emielvanderhoek** [polkadot-js/apps#2716]
Regarding this page: https://polkadot.js.org/apps/#/staking/actions

This page assumes the Polkadot JS Apps user controls both the Stash account and the Controller account. When using multisigs this does not work out very well.

We use the Polkascan multisig as stash account and a normal account as controller account.
After successfully bonding via a multisig transaction, the user that controls the normal controller account is not able to see the account under staking actions.

A simple solution to this problem would be to be able to add rows for multisig accounts to this page and take control via the actions on the UI. (even if the user controls one of both accounts).

Eventually there should perhaps be a redesign of this page to have a better separation of concerns between the Stash account actions and the Controller account actions. Especially with multisigs for either of the two types of accounts the current UI is unworkable.

**Comment by jacogr** [comment]
There has been some changes a while back where you should be able to control when you don't have the stash key. So both scenarios should work (with options on/off) -

- have stash, but not controller
- have controller, but not stash

This is however not something that gets thoroughly tested. Will take a peek, there is quite possibly something that slipped out along the way. (There are actually a number of users who don't have access to both, weirdly this is the first report that something broke recently)

**Comment by emielvanderhoek** [comment]
The stash is a multisig. That may be the thing that breaks it. One of us (as users) has control in the UI over both the multisig stash account and the normal controller account.

**Comment by jacogr** [comment]
UX here needs work.
