### ISSUE TITLE
Support claim statements

### ISSUE THREAD

**Issue by lsaether** [polkadot-js/apps#2725]
Statements were added to the Claims pallet in https://github.com/paritytech/polkadot/pull/1091 and will need to be supported in the UI. 

The UI should be able to detect if a Polkadot address needs to attest in which case it should also be able to present the user with the statement and allow them to submit the "attest" transaction easily. It would be great if functionality was obviously blocked or a notification was presented to a user when they have a Polkadot account that needs to attest in their wallet. 

The UI should also be able to present the user with the statement as part of the message to sign when making a claim, and use the `claims_attest` function instead of normal claim.

I will be able to help with this.

**Comment by jacogr** [comment]
So depending on where this goes - will either need to disable the claim functionality if not in and there is a chain that needs it, or get it done.

**Comment by amaurymartiny** [comment]
After a small chat with @Tbaut, here's the 1st direction we're going towards:

- If at least one account (incl those imported by extension) didn't sign the attestation, A op bar warning bar stays is shown
- We rename "Claim Tokens" to "Claim & Attest"
- The flow in page-claims will be:
  - step 1. account selection.
  - step 2. if NOT preclaimed account, show the paste ethereum signature step. If preclaimed account, skip this step.
  - step 3. Show the attestment.
  - step 4. Rename "Redeem" to:
      - for non-preclaimed account: "Redeem & Attest" (calls `claims.claimAttest`)
      - for preclaimed accounts: "Attest" (calls `claims.attest`)

**Comment by jacogr** [comment]
Don't rename. That breaks other chains that is also using the functionality and don't have attest (e.g. Darwinia, Kusama). As everything in the apps UI, it needs to be compatible with both old and new and via detection.

**Comment by jacogr** [comment]
Closing, done. (with and without statement support)
