### ISSUE TITLE
Old blocks fail to open in the explorer

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#2762]
Some blocks from ancient times make Apps throw errors. Example blocks this applies to: 201718, 201717, 201716, 201715, 201714, 201713, 201711, 201710, 201709, 201708, 201696, 201678, 201538, 201501, 100809, 100816, 100735...

![image](https://user-images.githubusercontent.com/1430603/82155905-59e68b00-9878-11ea-807f-30539bc158aa.png)

**Comment by jacogr** [comment]
Yes. It will happen. There is no “inject old types and metadata for old blocks”.

**Comment by Swader** [comment]
What's weird to me is how the block after and before an invalid one will work. The metadata and types should definitely be in those too. Is it just that the apps doesn't error if it doesn't try to decode something non-existent, aka, the block has to have a value incompatible with current metadata in order to fail, otherwise it's ok? If so, I would then propose adding an error page rather than failing in pending state.

**Comment by jacogr** [comment]
Yes, it can fail, may not fail, all depending on how the data is laid out. (But would mean data is decoded as bull when the types are wrong, just that the data was such that it didn't trigger an invalid considiton)

**Comment by jacogr** [comment]
Closing as-is. When the api has `.historic` support, this will be catered for. (As it stands, this behavior is expected since the API does not have support)
