### ISSUE TITLE
Emit 404s for invalid tabs

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#2767]
In the wiki, we have links to some parts of the Apps UI. Those sometimes change, as is the case with https://polkadot.js.org/apps/#/staking/returns - would it be possible to get such non-existent URLs to return 404s? I know they're hash URLs so it's hard to do natively, but maybe a redirect to a 404 page if a URL doesn't result in a component being loaded?

**Comment by jacogr** [comment]
When it cannot render something it should redirect to the default, i.e. explorer (or whatever is set as the default). However it is not on the top of the list, so atm it just renders the `Unknown` component.

**Comment by Swader** [comment]
I wanted 404 so our link-checker can detect it from CI of the wiki build, but it's just me being lazy

**Comment by jacogr** [comment]
Not doing 404's, sorry. The aliasses should help with movements, should have done that ages ago.
