### ISSUE TITLE
Publish on IPFS

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#2768]
It would be nice to make the UI available on IPFS.
I tested today and it works all fine. What is missing is CI integration.

The following is apps v0.42.0-beta.141:
https://ipfs.io/ipfs/QmedZec9DtF7mxTvqtR5WmZBNHvAPWyVMcSyZQDdvtbfor

Here is the how-to:
- [ ] build the project (see Dockerfile: `yarn install; NODE_ENV=production yarn build:www`)
- [ ] go to the build folder: `cd /packages/apps`
- [ ] publish on ipfs: `ipfs add -r build`
- [ ] update the ipns reference

The previous should not be done by hand but added as Github actions so it runs automatically for each new build.

There is a requirement for at least one IPFS server. I believe web3 is running one.

It then would be nice to have a way to inform the community about the command to run to pin the new version on their nodes.

It looks like:
```
ipfs pin add <hash>
```
and the `<hash>` is only known after the build has been published.

**Comment by Swader** [comment]
Fleek.co might also be a good option, they support auto-build from pushes on Github. They're basically CI for IPFS.

**Comment by jacogr** [comment]
Publish to Pinata via sdk, make hash available.

- apps redirect http://polkadot.js.org/apps/ipfs
- hash details https://polkadot.js.org/apps/ipfs/pin.json

Feel free to log additional issues for naming, etc, as it stands this is what there is time for. (And there is no actual managed domain, so DNS updates are non-applicable as it stands)
