### ISSUE TITLE
Assertion failed when estimation amount empty in staking targets

### ISSUE THREAD

**Issue by 0x7CFE** [polkadot-js/apps#2770]
tldr:

1. Go to https://polkadot.js.org/apps/#/staking/targets
2. Erase the "amount to use for estimation" field
3. UI crahses with the following message: "Uncaught error. Something went wrong with the query and rendering of this component. Assertion failed"

**Comment by jacogr** [comment]
Werid. Doesn't crash for me. Which browser are you using?

**Comment by 0x7CFE** [comment]
> Werid. Doesn't crash for me. Which browser are you using?

I was using Firefox 75.0 from Ubuntu 18.04.4 LTS. I was able to reproduce the bug several times then, but right now I could not reproduce it either :man_shrugging:

**Comment by jacogr** [comment]
My FF is a bit newer, also couldn't reproduced on it. (dev or deloyed) But where there is smoke, there is fire, so something is indeed weird somewhere - but a nightmare to track without an in-dev crash to see "where".

**Comment by jacogr** [comment]
Fixed in #2989
