### ISSUE TITLE
Add icon legend or an alt text

### ISSUE THREAD

**Issue by 0x7CFE** [polkadot-js/apps#2777]
<image src="https://user-images.githubusercontent.com/3784017/82414999-13747480-9aa2-11ea-9de2-18b3be145e9a.png" width="25%" height="25%" align="left">

Polkadot UI has a lot of icons.  Unfortunately, there's no obvious way to know their meaning.

An intuitive solution would be either to provide an alt. text to the image, or add something like a legend where one may see all available icons with their description.

**Comment by jacogr** [comment]
We had a tooltip, it was removed due to performance implications and it is not being put back.

Documentation is left to the wikis.
