### ISSUE TITLE
javascript, make transfer example error.

### ISSUE THREAD

**Issue by jiangfuyao** [polkadot-js/apps#2792]
https://polkadot.js.org/apps/#/js

example: `Make transfer and listen to events` -> running -> get error.

![屏幕快照 2020-05-22 上午10 48 46](https://user-images.githubusercontent.com/34789555/82626236-de8b2d80-9c19-11ea-8709-e901ea272b78.png)

**Comment by jacogr** [comment]
This has been fixed with the latest signer modal updates.
