### ISSUE TITLE
Identicon is not the correct one

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#280]
I am noticing the issue in 6e3b90d1.
The UI that is online works ok (polkadot-js-ui v0.19.54)

I am using a seed, say `0x11111` (it makes a nice one :))
 
The 'old' UI shows:
![image](https://user-images.githubusercontent.com/738724/45026136-b28ed980-b03d-11e8-98ef-bb59137ad889.png)

The new UI shows the correct address but another identicon:
![image](https://user-images.githubusercontent.com/738724/45026162-c8040380-b03d-11e8-8199-ee54982d1606.png)

**Comment by chevdor** [comment]
I forgot to update my deps.... all good.

**Comment by jacogr** [comment]
Phew :)
