### ISSUE TITLE
Support sudo_unchecked_weight in sudo app

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#2803]
Otherwise it cannot be used to perform runtime upgrade due to https://github.com/paritytech/substrate/issues/6117

**Comment by jacogr** [comment]
![image](https://user-images.githubusercontent.com/1424473/82782440-9d369000-9e5c-11ea-826d-e8f572b190c1.png)

![image](https://user-images.githubusercontent.com/1424473/82782457-a9bae880-9e5c-11ea-8c93-53410167db50.png)
