### ISSUE TITLE
injected account submit transfer error.

### ISSUE THREAD

**Issue by jiangfuyao** [polkadot-js/apps#2810]
https://polkadot.js.org/apps/#/accounts

**Network** : Kusama version 1062.

```
Parity Polkadot v0.7.33-9d61516e-x86_64-linux-gnu
api v1.16.0-beta.3
apps v0.43.0-beta.7
```

injected account(Google Chrome Polkadot{.js} ), send KSM to other account.
Click `Sign and Submit` get error:

![屏幕快照 2020-05-26 下午2 39 38](https://user-images.githubusercontent.com/34789555/82868163-c0496880-9f5e-11ea-89a3-31e06bbbe2f4.png)

```
authorize transaction:
Uncaught error. Something went wrong with the query and rendering of this component. n.paymentInfo is not a function
```

**Comment by jacogr** [comment]
Not injection related. This is weird though since it means the transactionInfo API is not available. Which RPC node?

**Comment by jiangfuyao** [comment]
@jacogr `Kusama (Polkadot Canary, hosted by Parity)`(wss://kusama-rpc.polkadot.io/)

**Comment by jiangfuyao** [comment]
changed to `Kusama (Polkadot Canary, user-run public nodes; see https://status.cloud.ava.do/)`
work now.

**Comment by jiangfuyao** [comment]
Changed back to `Kusama (Polkadot Canary, hosted by Parity)` work now.
strange :^)

**Comment by jacogr** [comment]
So honestly not sure what caused this, can only happen when the RPC is not available. But there is also a check for that.
