### ISSUE TITLE
New Council API (aka. ElectionsPhragmen)

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/apps#2822]
Changes introduced in 

- `report_defunct_voter `: Changed, but this is not supported by the UI, nor will it ever be IMO
- `submit_candidacy`: need to submit the count of candidates. 
- `renounce_candidacy `: need to provide a new enum based on role `Renouncing`. 
- `remove_member `: root call. Not supported by the UI.

**Comment by jacogr** [comment]
Thanks for logging, we have support for the candidacy submission (which is the only part used atm) - https://github.com/polkadot-js/apps/blob/f0f35614da7e6e1fbf0a0c3d92a01b9af1421ed2/packages/page-council/src/Overview/SubmitCandidacy.tsx#L48

(slightly hack to support both old and new, but does the trick)
