### ISSUE TITLE
Multiple custom endpoints

### ISSUE THREAD

**Issue by LukeWheeldon** [polkadot-js/apps#2826]
I assume many contributors will keep switching between Kusama, Polkadot and other Substrate networks, ideally using their own nodes. In that scenario, the current UX is not very practical as there is no way to save multiple custom endpoints.

A decent alternative is to use nginx with multiple "location" pointers so one only has to type/adjust the name of the network they want to connect to:
wss://1.2.3.4/polkadot
wss://1.2.3.4/kusama
[...]

Or probably simpler but not as easy to memorize, manually adjusting the port
ws://127.0.0.1:9944 (say Polkadot)
ws://127.0.0.1:9945 (say Kusama)
[...]

A low priority issue certainly, but one nonetheless.

**Comment by jacogr** [comment]
It is a very valid I issue. Been thinking for a while that we need “work on the customization of endpoints” (from a user perspective), your breakdown actually does help to frame it in terms of actual use. Thanks for that.

**Comment by ltfschoen** [comment]
@LukeWheeldon so when you have the "custom endpoint" toggle enabled at https://polkadot.js.org/apps/#/settings, it'll let you either add a new custom endpoint to a list of you favourite custom endpoints that you can choose from, and have an icon to remove any from the list. and that list would be stored in local storage

**Comment by Tbaut** [comment]
I'll have a look at this.

**Comment by Tbaut** [comment]
Thinking about something like this:
A save button appears when you type a custom endpoint:
![image](https://user-images.githubusercontent.com/33178835/90020344-09809d00-dcb0-11ea-9790-d93517315f03.png)

Clicking on this button saved the endpoint under a "Custom Endpoints" section:
![image](https://user-images.githubusercontent.com/33178835/90020867-b9eea100-dcb0-11ea-8517-59dd1619475a.png)

**Comment by jacogr** [comment]
That works.
