### ISSUE TITLE
DOT claim, selecting address fails with "Unable to retrieve keypair"

### ISSUE THREAD

**Issue by ascjones** [polkadot-js/apps#2829]
I mistakenly selected a contact address (rather than an account) from the "Select your Polkadot CC1 account" dropdown on `Claims`. Should this be allowed at all if there is no keypair for signing the claim? I think @0x7cfe may have reported something similar in Riot. At the very least it should not give the Whte Screen of Death.

Repro:

1. Add address as a contact in `Accounts > My contacts`
2. In `Claims`, select the address from the dropdown
3. The balance to be claimed together with the Ts&Cs are displayed
4. Click `I agree` and then the white screen of death. Error from the console: `Error: Unable to retrieve keypair '0x...`

**Comment by jacogr** [comment]
Didn't see any other issues logged here, so can't comment about the cause for other issues.

But yes, based on  #2734 the `type='account'` is missing in the dropdown.

**Comment by 0x7CFE** [comment]
> I think @0x7CFE may have reported something similar in Riot.

Yep, it was exactly that. I tried pasting claim address without adding it to the accounts. I was in the middle of writing the issue but you did it first :)
