### ISSUE TITLE
Incorrectly blocked from nominating with locked assets.

### ISSUE THREAD

**Issue by cjwhittle** [polkadot-js/apps#2832]
When trying to stake/nominate with locked assets, this action is prevented by the UI choosing the incorrect balance to show as available.

The available balance shown is the transferrable balance, but all DOTs, including locked DOTs should be available to stake (or take part in governance for that matter).

https://polkadot.js.org/apps/#/staking/actions

<img width="451" alt="Picture 1" src="https://user-images.githubusercontent.com/49903091/83023089-5dbaa000-a024-11ea-9d25-434cc1c3a6d5.png">

Here the 'value bonded' input shows as available the 'transferrable' figure (orange in my pic), when it should be showing the sum of 'locked' and 'vested' (green in my pic).

**Comment by jacogr** [comment]
Thanks fo the detail. Yes, here the display should show the free (not the transferrable).
