### ISSUE TITLE
Bundle into a WebExtension

### ISSUE THREAD

**Issue by DemiMarie-parity** [polkadot-js/apps#2842]
It should be possible to bundle the UI into an extension page, which is normally used by extensions to expose a settings UI.

**Comment by jacogr** [comment]
This is a won't fix. As explained this is not the goal as a distribution mechanism - https://github.com/polkadot-js/apps/issues/2841 it is fully-featured desktop-like. 

For extension-based wallets, there are other options -

- Enzyme
- SpeckleOs
- Metamask (soon)
