### ISSUE TITLE
Get the Electron app in distro package managers

### ISSUE THREAD

**Issue by DemiMarie-parity** [polkadot-js/apps#2843]
This will make it much easier to install.

**Comment by DemiMarie-parity** [comment]
I deleted “Linux” because someone might choose to add it to NetBSD’s pkgsrc or the Free/OpenBSD ports trees, although I consider this unlikely in the near term.

**Comment by jacogr** [comment]
It will only be published under releases (upon tagging) in a subset of the formats here - https://www.electron.build/ 

We are close on the electron package thanks to the work from the guys at Ethworks. 

Once the builds are being made available on release, will allow requests for specific extras that may not be available. Until then, wait for the initial availability.
