### ISSUE TITLE
what is the balance fields meaning?

### ISSUE THREAD

**Issue by xwartz** [polkadot-js/apps#2858]
```ts
export interface AccountData extends Struct {
  readonly free: Balance;
  readonly reserved: Balance;
  readonly miscFrozen: Balance;
  readonly feeFrozen: Balance;
}
```
I know the `free` stands for transferable balance, but what about the other fields,
`reserved`: ?
`miscFrozen`: ?
`feeFrozen`: ?

**Comment by jacogr** [comment]
Not sure how this relates to apps? Struggling to see the connect. 

For the specific storage structs, would refer to the substrate codebase where these are defined, most of the structs have descriptions for the specific fields and what fills them. 

https://github.com/paritytech/substrate/blob/master/frame/balances/src/lib.rs
