### ISSUE TITLE
Polkascan can't find the latest transaction(westend)

### ISSUE THREAD

**Issue by Wangmmx** [polkadot-js/apps#2870]
Is there a block explorer on the westend network now? 
I used https://polkascan.io/westend-m2, but the query result cannot be found based on the transaction hash. Is this the latest westend browser?

**Comment by jacogr** [comment]
Have no idea, I am really not tracking the explorers. Best would be to direct the query at Polkascan itself.

**Comment by jacogr** [comment]
Re-opened, the Westend link has apparently changed, so app UI links are wrong.
