### ISSUE TITLE
Support adding accounts from existing seed with password protection

### ISSUE THREAD

**Issue by dvdplm** [polkadot-js/apps#2874]
The "Add account" flow does not support using mnemonic seed phrases that were created with `subkey` and a password. In other words this doesn't work: "my fancy word list about nothing special at all///sikrit-password-here".

**Comment by jacogr** [comment]
You need to add the `///password` into the derivation options. (As you would with hard/soft)

![image](https://user-images.githubusercontent.com/1424473/83635165-08dad480-a5a4-11ea-93bd-5c3d4d5a32dc.png)
