### ISSUE TITLE
Enable import derived account from Parity Signer

### ISSUE THREAD

**Issue by hanwencheng** [polkadot-js/apps#2885]
It would be good to import the derived account from signer to polkadot.js app 

Related issue on Parity Signer [here](https://github.com/paritytech/parity-signer/issues/640)

Pokadot.js app has several ways for importing the keypairs from Keyrings of Polkadot.js/common , and there is [addFromSeed](https://github.com/polkadot-js/common/blob/master/packages/keyring/src/keyring.ts#L121-L135) function, but I am not sure if it use the SecretKey or MiniSecretKey, since in our case only SecretKey would fit, while the MiniSecretKey is used to generate for the root account (non-derivated account).

P.S I did some research on Substrate and I find [from_seed_slice](https://github.com/paritytech/substrate/blob/master/primitives/core/src/sr25519.rs#L486) could use SecretKey to generate Keypairs but it is not included in the Subkey tool AFAIK. The subkey tools can not `inspect` a SecretKey to keypairs.  The [seed](https://github.com/paritytech/substrate/blob/master/bin/utils/subkey/src/main.rs#L93) here actually refer to MiniSecretKey for generate the non-derivation account.

In addition to that, we could use `Add Via QR` button, if we find it is a QR representing a SecretKey hex , then add it to keyring and regard it as an internal account.

**Comment by jacogr** [comment]
Yes. The JS side only deals with minisecrets.

**Comment by hanwencheng** [comment]
Now I am updating Signer with miniSecretKey, will update here again when it is merged.
