### ISSUE TITLE
Address add is confusingly broken

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#290]
To reproduce -

1. Go to "Add address"
2. Add one (I just copied something from vanity)
3. Click "Save"

At this point the display has updated (so it looks like we are in "Edit"), however the tabs at the top is still on "Add Address".

<img width="444" alt="polkadot apps portal 2018-09-07 10-19-04" src="https://user-images.githubusercontent.com/1424473/45207216-b746ce00-b287-11e8-8a34-e8a29f852f6b.png">

It seems like the tabbar does not re-render in this case? Does the on-back work as expected here? The same happens on Accounts. (If I have to hazard a guess as to what broke it, possibly https://github.com/polkadot-js/apps/pull/267 - and this really should have been picked up)

Found as part of testing through #287

**Comment by ltfschoen** [comment]
@jacogr I've fixed this Address component issue in this PR https://github.com/polkadot-js/apps/pull/292. I've also previously fixed the Accounts component issue that you've mentioned in https://github.com/polkadot-js/apps/pull/202
