### ISSUE TITLE
QR content for offline signature is not String

### ISSUE THREAD

**Issue by RomeroYang** [polkadot-js/apps#2906]
I have a problem interacting with the QR for offline signature, The content of the QR seems to be Bytes, but the QR reader I used in polkawallet-flutter can only read Strings.

![image](https://user-images.githubusercontent.com/10572804/84138317-a5a7e100-aa80-11ea-92de-0c38a4d76074.png)

I just wonder if you could change the QR content to String?

**Comment by jacogr** [comment]
This is a tricky one... the uos spec says this needs to be the way it is. (Text encoding is just much bigger QR-wise). Calling in some views of the people in the know ...

@maciejhirsz @hanwencheng I am correct in the above?

**Comment by hanwencheng** [comment]
The raw data of the UOS is bytes in hex format, for decoding it and extract the extrinsic bytes, you may refer to the decode process on Parity Signer:
1. raw to U8a https://github.com/paritytech/parity-signer/blob/53f255ff43e06bb9d646bb36773b4efc706d443b/src/utils/decoders.ts#L54
2. u8a to extrinsic bytes: https://github.com/paritytech/parity-signer/blob/53f255ff43e06bb9d646bb36773b4efc706d443b/src/utils/decoders.ts#L100

**Comment by hanwencheng** [comment]
Back to the topic, as @jacogr said, Text encoding is much bigger, there is libraries in Flutter which could get the bytes from qr code, e.g [qrscan](https://pub.dev/packages/qrscan)

**Comment by RomeroYang** [comment]
> Back to the topic, as @jacogr said, Text encoding is much bigger, there is libraries in Flutter which could get the bytes from qr code, e.g [qrscan](https://pub.dev/packages/qrscan)

Thank you, I will try this qrscan lib.

**Comment by RomeroYang** [comment]
> The raw data of the UOS is bytes in hex format, for decoding it and extract the extrinsic bytes, you may refer to the decode process on Parity Signer:
> 
> 1. raw(hex) to U8a https://github.com/paritytech/parity-signer/blob/53f255ff43e06bb9d646bb36773b4efc706d443b/src/utils/decoders.ts#L54
> 2. u8a to extrinsic bytes: https://github.com/paritytech/parity-signer/blob/53f255ff43e06bb9d646bb36773b4efc706d443b/src/utils/decoders.ts#L100

Now I got the extrinsic bytes referring to the decode process on Parity Signer and I will sign the extrinsic next step.

It seems Parity Signer did the signature with `EthkeyBridge` of react-native here: https://github.com/paritytech/parity-signer/blob/9e8d654a7301a4520ad6c7c41d77446a49125eba/src/utils/native.ts#L253.
Could I sign the extrinsic with `polkadot-js/keyring`, and how?

**Comment by jacogr** [comment]
https://github.com/polkadot-js/apps/blob/master/packages/react-signer/src/signers/AccountSigner.ts#L22

**Comment by hanwencheng** [comment]
if you are using Flutter then it is not possible to revoke the wasm bindings from `polkadot-js/keyring`, you may try with this [flutter signing library](https://github.com/hanwencheng/substrate_sign_flutter)

**Comment by jacogr** [comment]
wasm-crypto has an asm.js fallback that is setup for RN - https://github.com/polkadot-js/wasm/blob/master/packages/wasm-crypto/package.json#L17

(If that works the same way in Flutter, no idea, may need an additional override. But since Polkawallet already uses it, I'm assuming the override is set already and it "just works")

**Comment by RomeroYang** [comment]
Thanks a lot, actually I run `polkadot-js/api` in an hidden webview in the app, and do all the codec things in js.

I use this `dataToSign`(https://github.com/paritytech/parity-signer/blob/7719560184f43007df6911c4522d8591685efdbe/src/stores/ScannerStore.ts#L341) to create an `ExtrinsicPayload` like this:
```javascript
const signed = registry.createType("ExtrinsicPayload", dataToSign, { version: 3 }).sign(keyPair);
```
and I got an error:
```text
createType(ExtrinsicPayload):: createType(ExtrinsicPayloadV3):: Invalid data passed to Mortal era
```
What could be the cause of this error?

**Comment by jacogr** [comment]
Wrong encoding. Make sure you don't pass the length prefix, it needs to be split before.

**Comment by RomeroYang** [comment]
I did some modifications on some Flutter packages so they can deal with bytes data for QR.
https://github.com/polkawallet-io/qr.flutter is modified for QR generating, and https://github.com/polkawallet-io/flutter_qr_reader is modified for QR reading.
Problem solved, and thanks for your help.
