### ISSUE TITLE
Can not select mutisig signatory from a list of my accounts

### ISSUE THREAD

**Issue by keorn** [polkadot-js/apps#2907]
![image](https://user-images.githubusercontent.com/7750981/84140049-467ea800-aa51-11ea-8a29-a3b7ac7f04d4.png)

The signatory dropdown has no values. When I try to paste in a correct signatory then no address appears and a password field appears (even though pasted in address was added with QR code from signer).

```
api v1.18.1
apps v0.44.0-beta.61
```

**Comment by jacogr** [comment]
Cases by unmatched ss58Format - now a re-encoding of the addresses occur on the signer, both for the dropdown and "other signatories".
