### ISSUE TITLE
Help (basic.md) is not internationalized

### ISSUE THREAD

**Issue by laurogripa** [polkadot-js/apps#2954]
Hey!

The help button (upper right corner) opens different markdown files, depending on context.
These markdown files are hardcoded in English.

IMHO, the import should be dynamic, based on current language.

**Comment by jacogr** [comment]
Sure, can look at it when we actually have maintained i18n translations for the app - before then, it is not something that will make it to the list. The issue with all this is that it is rapidly evolving, so translations today are outdated a week from now. Outdated content is worse than non-translated content.

**Comment by jacogr** [comment]
Another point which drives me crazy actually - even at places (staking comes to mind) the current English version is also outdated. This really need fixing and refreshing :(

**Comment by laurogripa** [comment]
@jacogr I feel you.

It would be nice to have some sort of `centralized glossary` or `source of truth` for common terms and concepts. I had some trouble translating some terms and sentences and they probably gonna need some maintenance in the future.

For instance, I saw someone was also translating Polkascan to portuguese. I reviewed the PR and invited her to our language-specific chat on Telegram, if I haven't done that, we would have very different translations for the same stuff.

Ps.: I don't this to sound like a critique, it's more like a feedback about the pain I felt. I'm not really sure where to share this kind of feedback :sweat_smile:

**Comment by jacogr** [comment]
Sure, saw that in Russian as well - the truth is that it won't be done-done when merged. So the i18n process here has a gap, i.e. when changed it doesn't reflect on the UI immediately, so it is difficult to see it is context. (Without effort and running it locally). So yes, it will require "tweaks" once in. 

PS: Not taking it as a critique, we are all after making the stuff we are interested in easier for others, so the end-goals are the same. Comments are taken in that context. (Bit off topic for this issue, but all fine)

**Comment by jacogr** [comment]
Closing this. 

Like any urgent vs important discussion (which is how the next-up it prioritized), this doesn't mean it it won't add value, but rather that it won't get any focus. So the options are to have it sit gathering more dust or just be honest that based on capacity and focus-wise it will not get addressed.

If there is appetite for PRs to move things in the direction intended here, they will always be welcome.
