### ISSUE TITLE
JS example outdated

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#2956]
The JS example `Get state metadata` seems to be outdated.
Running it outputs:

```
Magic number: 1635018093
TypeError: Cannot read property 'raw' of undefined
    at eval (eval at <anonymous> (https://polkadot.js.org/apps/main.68935168.js:351:228906), <anonymous>:13:38)
```

## Version data:
Parity Polkadot v0.8.8-b2c9c14-x86_64-linux-gnu
api v1.19.0-beta.3
apps v0.45.0-beta.29
chain: Kusama

**Comment by jacogr** [comment]
Not even sure how that one got in, even the code formatting is not up to spec.

You should _never_ access `.raw`. (This is why it breaks, it is not `_raw` to show intent that that is internal-only.)
