### ISSUE TITLE
Error when signing a nomination transaction

### ISSUE THREAD

**Issue by pomomoh** [polkadot-js/apps#3030]
Hi guys,
I finally just claimed my DOTs from eth wallet. When I sign a transaction to nominate with any bond amount, I get this error message "1010: Invalid Transaction: Transaction has bad error". Does anyone know why I'm getting this error and how to fix it?

Also, is there a way to send DOTs from my stash account to controller account? I get an error when I try to do this. How can I use separate stash and controller accounts if I can't send DOTs?

**Comment by jacogr** [comment]
Transfers and not enabled on Polkadot yet, as per the launch roadmap - https://polkadot.network/launch-roadmap/

How are you signing the transaction: via QR code, via built in account, via an account on an extension?

**Comment by pomomoh** [comment]
Thanks @jacogr 
Signing the transactions with Chrome browser extension + account password

**Comment by jacogr** [comment]
As long as you have 0.30.1 of the polkadot-js extension (latest version), it will/should not have any issues. If you see a request for a metadata update (red dot over "Settings", apply via the "Metadata" tab under settings), do apply it as well - although being slightly behind there won't be an issue.

**Comment by jacogr** [comment]
Closing.

**Comment by pomomoh** [comment]
Thanks
