### ISSUE TITLE
Running with `polkadot --dev` gives BadOrigin error when sending balances

### ISSUE THREAD

**Issue by DemiMarie-parity** [polkadot-js/apps#3033]
This could just as easily be a bug in Polkadot, but I am not certain, so I am reporting it here.

**Comment by jacogr** [comment]
It is expected, Polkadot does not have transfers yet. 

- Where BadOrigin comes from in Substrate - https://github.com/paritytech/substrate/blob/master/frame/support/src/dispatch.rs#L1924-L1926 
- Setup in Polkadot - https://github.com/paritytech/polkadot/blob/master/runtime/polkadot/src/lib.rs#L110

`--dev` uses the Polkadot runtime.

**Comment by DemiMarie-parity** [comment]
Nevertheless, the error message is really poor.  I had no idea that Polkadot had this block until someone explicitly told me.

We should really say something like “Transaction is prohibited at this time.  See <https://polkadot.network/explaining-the-polkadot-launch-process/ for more details.”

**Comment by jacogr** [comment]
Def the wrong repo to log that - the API just reports what the node gives it :)
