### ISSUE TITLE
I may be met a bug 

### ISSUE THREAD

**Issue by master-davidlee** [polkadot-js/apps#3056]

**Comment by master-davidlee** [comment]
I had a pallet in which a storage item named  OwnedKitties and it's a map the key is (T:: AccountId, Option<u32>) .when I try to use apps to query this chain state I found a button is weird.
![image](https://user-images.githubusercontent.com/49427668/85853940-fd1ab080-b7e5-11ea-846b-44204f32b79f.png)
and it's doesn't work I can't input an Option<> type number.

**Comment by jacogr** [comment]
There are two are fighting against each other -

- the map is default set to on (to allow single entry queries)
- the option is default set to off (exclude)
