### ISSUE TITLE
Display validator/nominator tags in account sidebar

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#3064]

**Comment by jhonalino** [comment]
![Screen Shot 2021-01-24 at 1 03 26 PM](https://user-images.githubusercontent.com/13143458/105643418-98d7d200-5e44-11eb-9e24-0fc5b73e2445.png)
would this be the account sidebar sir? 
and the validator/nominator tags would show around that "injected" tag area?

**Comment by jacogr** [comment]
Yes. Indeed. So to get the status we can just query the staking.nominators(address) and staking.validators(address) - it they exists (isEmpty on them is false) it is one of those.

**Comment by jhonalino** [comment]
![Screen Shot 2021-01-30 at 3 40 18 AM](https://user-images.githubusercontent.com/13143458/106355477-0a80a780-62ad-11eb-86d2-0506c9748bcc.png)
![Screen Shot 2021-01-30 at 3 39 58 AM](https://user-images.githubusercontent.com/13143458/106355478-0b193e00-62ad-11eb-901d-1394f77c55cc.png)


how do we look sir? 

also how would I test if the flags are working? I currently don't have a nominator or validator account

**Comment by jhonalino** [comment]
nvm I was able to test the validator/nominator by clicking the addressed on the staking tab. and it looks like its working! Imma pull request. please do let me know if there is a flaw in my logic. thank you very much!!!
