### ISSUE TITLE
Display fees alongside registration

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#3073]
Pulled from constants - overall & per field

**Comment by Tbaut** [comment]
Do you mean when setting identity in accounts, calculate the total based on the following ? 
![image](https://user-images.githubusercontent.com/33178835/89788022-c93de500-db1e-11ea-9505-9cd09d01d526.png)

**Comment by jacogr** [comment]
Yes. Just an overall summary of the values.
