### ISSUE TITLE
Display errors for non-filled fields on identity (& basic validation)

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#3074]
e.g. twitter needs to be `@<username>` (placeholder here as well)

**Comment by chevdor** [comment]
The issues I see the most are:
- users toggle a field (twitter, riot, ...) and leave the content empty
- users provide twitter as "handle" or "http://twitter.com/handle". Registrar #1 only accepts "@handle"
- web provided as "www.sample.com" where registrar #1 accepts only "http://www.sample.com" or "https://www.sample.com" 

* wherever I mentioned "registrar #1" is obviously opinionated and carries the weight of "history".

**Comment by chevdor** [comment]
the real regexp can get quite crazy but I can tell that 100% of the issues I have seen so far can be fixed today with trivial ones. Like:

- twitter: start with @ and has more than 2 chars
- riot: starts with @ or #, has a : and has more than 6 chars
- web: starts with https?:// and is has 'something' after
- legal/display: has at least one char
- email: has a @ and at least 3 chars
