### ISSUE TITLE
Combine expired democracy locks in display

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#3088]
Currently we have the following -

![image](https://user-images.githubusercontent.com/1424473/85977880-c0b1a500-b9dd-11ea-8cce-9634da2d2818.png)

Adjust the locks do it displays with grouping for expired and ongoing, something along these lines with the grouping using less space

```
#44 220 Locked 1x
#45 221 Locked 2x
#52 220 Locked 1x
  lock expired

#66 220 None
#67 221 Locked 1x
  ongoing referendum

#46 220 Locked6x
  expres in ...
```

**Comment by Tbaut** [comment]
I'll work on this to get me re-started :)

**Comment by jacogr** [comment]
fk, didn't see this - was travelling while doing #3093

**Comment by Tbaut** [comment]
All good, my solution wasn't as elegant. I'll review then :)
