### ISSUE TITLE
Layout breaks on Submit Preimage in Democracy

### ISSUE THREAD

**Issue by lucasvo** [polkadot-js/apps#3102]
This is running `apps v0.42.0-beta.100`

<img width="1257" alt="Screen Shot 2020-06-30 at 16 43 16" src="https://user-images.githubusercontent.com/31727/86140189-e67b9e80-baf0-11ea-891f-6a86922aa045.png">

**Comment by jacogr** [comment]
Thanks for the report.

The 0.42 is unsupported. This current.

![image](https://user-images.githubusercontent.com/1424473/86149120-d3220080-bafb-11ea-9781-a7b4304c95c1.png)

**Comment by lucasvo** [comment]
@jacogr this is still current on polkadot-js (I just tested something similar on https://polkadot.js.org/apps/#/democracy):

![screen_2020-07-08-12-20-08](https://user-images.githubusercontent.com/31727/86917954-7d5de180-c115-11ea-824b-370ebe13d2d9.png)

**Comment by jacogr** [comment]
On Chrome? I played on chrome, Safari, FF, Brave after you logged.

Which OS?

**Comment by jacogr** [comment]
Ok, _now_ (after #3293) I finally see what the problem is. Here is is somewhat less jarring -

![image](https://user-images.githubusercontent.com/1424473/88932349-3e3b3000-d27e-11ea-8f1d-edfedf1e98cf.png)

So, it is the combo that overflows.

Ok, sometimes I am just really, really slow.
