### ISSUE TITLE
Add automatic gas cost estimation

### ISSUE THREAD

**Issue by athei** [polkadot-js/apps#3132]
[Soon](https://github.com/paritytech/substrate/pull/6573) the json rpc `contracts_call` will return a field `gas_consumed` that indicates how much gas was consumed by a contract execution.

The UI should use that to (automatically) run a contract call as RPC in order to suggest a sensible gas limit to the user.

**Comment by jacogr** [comment]
Actually forgot about this one, but believe it was stuck somewhere in the back of my mind when I added the estimation. 

All, good, it is included in the UI.
