### ISSUE TITLE
Error in Accounts using Westend: Cannot read property 'votingOf' of undefined

### ISSUE THREAD

**Issue by mariopino** [polkadot-js/apps#3148]
Hi,

I'm getting this error at https://polkadot.js.org/apps/#/accounts using Westend:

```
Uncaught error. Something went wrong with the query and rendering of this component. Cannot read property 'votingOf' of undefined
```

**Comment by jacogr** [comment]
Introduced in https://github.com/polkadot-js/apps/pull/3122

Sorry, apparently my test-through sucked, really thought I checked that PR on Westend.
