### ISSUE TITLE
Support claiming with subkey

### ISSUE THREAD

**Issue by infinity0** [polkadot-js/apps#3152]
Hi, https://wiki.polkadot.network/docs/en/claims mentions two ways to sign attestations - online via the app or offline using the Parity Signer, which is mobile-only. However some of us don't trust our own phones to truly be offline and use `subkey` instead for signing.

It would be good if polkadot.js could support this use case. As far as I can tell, we simply need to be able to:

1. In addition to adding an account via QR code (which I assume does not include the secrets as that would defeat the purpose of using Parity Signer in the first place), we should be able to add an account via the address, or some other piece of information that `subkey` provides such as the public key / account id.

2. In addition to "Sign [claim] via QR", support a "sign externally" option that gives a hex-dump of the raw transaction that you can paste into `subkey`. Then the user can paste the signed hex-dump back into polkadot.js.

**Comment by jacogr** [comment]
Thanks for reporting, this is already being tracked at https://github.com/polkadot-js/apps/issues/2745
