### ISSUE TITLE
Add forums links for tips on the right side, next to "endorse" button

### ISSUE THREAD

**Issue by rrtti** [polkadot-js/apps#3157]
Add links for tips on the right side next to "endorse" button, in the same way we can see on any proposal. Polkassembly now included on-chain tips descriptions and discussions, allowing us to add the link to the tip in case more info is needed. We can add this link + Polkascan and Subscan. If Commonwealth includes this functionality we should add as well.

**Comment by Tbaut** [comment]
Thanks Raul, it def makes sense. We should note that tips have no id, but a hash. I think Polkassembly needs to first be able to request tips by hash before we can have a link. I'll log this.

**Comment by Tbaut** [comment]
Should be good now, I'll submit a PR soon.

**Comment by Tbaut** [comment]
totally forgot about this one sorry, will do it in the next days.
