### ISSUE TITLE
Unable to find Event with index

### ISSUE THREAD

**Issue by metmirr** [polkadot-js/apps#3169]
I am trying to query events from Kusama network.

Polkadot/api version `v1.24.0-beta.1`
Node https://polkadot.js.org/apps/#/explorer

```
Unable to decode storage system.events: createType(Vec<EventRecord>):: findMetaEvent: Unable to find Event with index 0xd684/[214,132]
2020-07-12 02:38:13        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: createType(Vec<EventRecord>):: findMetaEvent: Unable to find Event with index 0xd684/[214,132]
```

Note: _There is no error with the first two events._

**Comment by metmirr** [comment]
Ensuring metadata solves my problem https://github.com/polkadot-js/api/issues/845

**Comment by jacogr** [comment]
Yes, the apps UI will go in that direction at some point - historical blocks are problematic when crossing the upgrade boundaries. (Having said that, the frame developers are making strides making it less jarring, but metadata is for current and on older dragons lurk)
