### ISSUE TITLE
Error: createType(StakingLedger):: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by maxsam4** [polkadot-js/apps#3173]
Certain accounts (like 5% of the accounts) are triggering this error on the Accounts Action page after bonding tokens on the Polymesh Aldebaran Testnet.

The error is reproducible on chrome (after clearing cache) but not on Firefox (presumably due to Firefox's larger stack size for js).

Here's the stack trace:
```
Error: createType(StakingLedger):: Maximum call stack size exceeded
    at createTypeUnsafe (main.8e720866.js:24024)
    at Rpc._formatStorageSetEntry (main.8e720866.js:18141)
    at main.8e720866.js:18112
    at Array.forEach (<anonymous>)
    at Rpc._formatStorageSet (main.8e720866.js:18110)
    at Rpc._formatOutput (main.8e720866.js:18072)
    at Object.update [as callback] (main.8e720866.js:17998)
    at WsProvider.value (main.8e720866.js:18885)
    at WebSocket.value (main.8e720866.js:18820)
```

The error seems to originate from 
```js
return new _types.Option(this.registry, (0, _types.createClass)(this.registry, type), isEmpty ? null : (0, _types.createTypeUnsafe)(this.registry, type, [input], true));
```
`_formatStorageSetEntry` fn inside rpc-core. If the error is caught and `undefined` is passed instead of `input` to the function, it works fine (I guess the erroring type won't work properly).
i.e., the below line does not cause an error
```js
return new _types.Option(this.registry, (0, _types.createClass)(this.registry, type), isEmpty ? null : (0, _types.createTypeUnsafe)(this.registry, type, [undefined], true));
```

Please let me know if any other info will help you track down this problem.

**Comment by jacogr** [comment]
Check your StakingLedger types - they have changed quite a bit between the versions, i.e. on Kusama there has been a number (the `To***` tracks the Substrate spec version) - https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/kusama.ts (At least 3 versions there, API defaults to latest master version)

**Comment by maxsam4** [comment]
Thanks, setting the `StakingLedger` type to the correct one (`StakingLedgerTo240` in our case) fixed the problem.
