### ISSUE TITLE
Uncaught error for poll page when connecting to Kusama node

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#3180]
Open https://polkadot.js.org/apps/#/poll directly with previously selected Kusama network will result following error

> Uncaught error. Something went wrong with the query and rendering of this component. undefined is not an object (evaluating 'a.query.poll.totals')

Should gracefully handle this error and ask user to check their network.

People were confused by the error message when following the link shared by others.

**Comment by jacogr** [comment]
It applies to a lot of modules, e.g. go to democracy, switch to Westend. The truth is that there is no real "this module is not here generic handler". So it is something on the radar with no good ideas as to how to solve.
