### ISSUE TITLE
Add Bounty Spending mechanism functionality to Apps

### ISSUE THREAD

**Issue by rrtti** [polkadot-js/apps#3184]
Once ready, the bounty spending mechanism should be added to Apps - adding this as a reminder. 

The functionality might need its own full management section (to add: _tab in treasury_). This way each curator will be able to manage the bounty, all open bounties will be visible, with information about them. 

A button should be added:  **"+ Submit Bounty proposal"**. A window should open with all the needed entries, including `Proposer`, `Bounty reason`, `Curator`, `Value`.

**Comment by Tbaut** [comment]
Linked to https://github.com/paritytech/substrate/pull/5715

**Comment by jacogr** [comment]
Closing this. Although not done, the work is tracked via bounty - moving along nicely.
