### ISSUE TITLE
Add Proxy Functionality to Poll Vote

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#3190]
Right now, the only way to vote in the poll via proxy is to go to the extrinsics tab and submit a manually encoded array of votes. The Poll tab should have an option to vote via proxy.

![image](https://user-images.githubusercontent.com/25483142/87422449-f313f280-c5d8-11ea-9499-fada57291bac.png)

**Comment by jacogr** [comment]
PRs welcome to proxy detection for this short-lived type, https://github.com/polkadot-js/apps/blob/master/packages/react-signer/src/Address.tsx

**Comment by jacogr** [comment]
Closing, added alongside other proxy updates.
