### ISSUE TITLE
Total balance field shifted to the left

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#3191]
I tested on Westend, Polkadot and Kusama.

On Westend, it works fine: The total balance is in the balances column.
![image](https://user-images.githubusercontent.com/738724/87423363-76821380-c5da-11ea-9cfd-44226d0107c5.png)
It may be luck here though.

On the other chains, depending on the screen size, the field jumps right and left but is never aligned with the balances column.

Here are some examples on Kusama with various window size (width):
![image](https://user-images.githubusercontent.com/738724/87423548-ca8cf800-c5da-11ea-9567-3c1a99fe823b.png)
![image](https://user-images.githubusercontent.com/738724/87423573-d082d900-c5da-11ea-8eec-eb6b608caa7e.png)

**Comment by jacogr** [comment]
Which browser?

(The reason for asking, cannot replicate on my Chrome)
