### ISSUE TITLE
Electron version UI broken on Windows

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#3204]
![image](https://user-images.githubusercontent.com/1430603/87588816-93a30900-c6e4-11ea-8d32-ffe38bdca2d2.png)

![image](https://user-images.githubusercontent.com/1430603/87588834-9b62ad80-c6e4-11ea-87a2-8075e1fb7d30.png)

This is release 0.49.1, have not tested before.

**Comment by jacogr** [comment]
Weird, was def tested on Windows as well. Should not make any difference.

cc @krzysztof-jelski

**Comment by krzysztof-jelski** [comment]
For some reason the css files are loaded differently on Windows and were blocked by the recently added CSP header.

**Comment by jacogr** [comment]
Updated version will be in Monday's release.
