### ISSUE TITLE
Rework auto-download of JSON

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#3222]
Chrome now gives a warning.

**Comment by Tbaut** [comment]
Gave it a shot with chrome 84.0.4147.105 (Official Build) (64-bit) both on https://polkadot.js.org/apps/#/accounts and locally and the download started right away without any warning.

**Comment by jacogr** [comment]
This one is weird, I wanted to close it - I don't see it anymore on mine either. But def. did get a warning. Going to close it for now, accounts is getting a relook on modals.
