### ISSUE TITLE
Display sub accounts (when parent) in sidebar

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#3224]

**Comment by Tbaut** [comment]
I'll tackle this one next

**Comment by Tbaut** [comment]
Having a deeper look, I think the best way to do this is to add the property `childs?: [AccountId]` to the `DeriveAccountRegistration` type in the `api`. I'd add this right next to the parent retrieval [here](https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/accounts/info.ts#L85). Does that sound like the way you'd do that?

**Comment by jacogr** [comment]
Generally I would agree. In this case I would rather not and keep the call specific to the component/container. 

The issue atm is that we are already overloading due to the number of queries and the sheer volume of data. See for instance staking, where we add an additional subsOf for all 500 (currently) on Kusama.

If this is only used here, would rather just do the `identity.subsOf` call straight in the sidebar, as it gets opened.
