### ISSUE TITLE
AccountId display shows PublicKey, not address

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#323]
<img width="1261" alt="polkadot apps portal 2018-09-18 12-38-17" src="https://user-images.githubusercontent.com/1424473/45682143-c9562580-bb3f-11e8-89f8-cf439d3224e6.png">

I was quite sure we fixed this one with the changes to ui-app/Params/valueToText.ts -> accountToText

Basically the above displays as what looks like a u8a, instead of the actual encoded address. Either 

1. The logic above is wrong
2. An already-serialized string gets passed (some toString() that is out of place)
3. ...

Looking at it briefly, it seems this is due to a sequence of merges, i.e. the value is a u8a, however on L127 above we actually do a trim on it. (When it is _not_ a string)

**Comment by yjkimjunior** [comment]
Removing the .trim() in L127 seems to do the trick.

**Comment by yjkimjunior** [comment]
![screen shot 2018-09-18 at 2 00 16 pm](https://user-images.githubusercontent.com/10432070/45716261-3d49fb00-bb4b-11e8-87f7-db7c6c1e1e09.png)
