### ISSUE TITLE
Use unbonding amount in staking warning calculations

### ISSUE THREAD

**Issue by blxxd** [polkadot-js/apps#3232]
It is possible to handicap yourself with "Bond more funds" simply by submitting an amount that exceeds balance. It's even worse with polkadot, funds will be locked until balance transfers enabled.

**Comment by jacogr** [comment]
It does exactly that - for both bonding and bond-more it fill in defaults that is max - existential.

**Comment by blxxd** [comment]
I'm sorry for the poor technical details. 

The warning seems does not work right only if there are unbonding funds.
There will be a warning if `amount > transferrable + unbonding` but with a smaller amount no warning displayed. So it's possible to bond more  if `transferrable < amount < transferrable + unbonding` and get zero balance. Moreover, bond more default amount is `transferrable + unbonding` which automatically leads to balance zeroing since bondExtra does not impose any limitation on the amount that can be added.

You can reproduce by following these steps:
1. bond 0.25
2. unbond 0.25
3. bond more
- amount automatically filled with 0.43
- no warning displayed, submitting leads to balance zeroing
4. bond more
- amount filled with 0.24 despite transferrable is zero. no warning displayed
- submitting ends with error 1010: Invalid Transaction: Inability to pay some fees (e.g. account balance too low)

Here you can see steps 1-3 I've made https://westend.subscan.io/account/5FsUhof4goQdXAiuahKoXVYk9cLf4DEhJvFH2C3Z7sepyScN?tab=extrinsic
Balances:
transferrable 0.000 WND
locked 0.433 WND
bonded 0.183 WND
unbonding 0.250 WND

**Comment by jacogr** [comment]
Thanks for the details. So the issue is actually the unbonding amount that is not taken into account.
