### ISSUE TITLE
Staking "deposit" VERY misleading

### ISSUE THREAD

**Issue by freedomcoding** [polkadot-js/apps#3260]
Was just going through the process of learning to be a Staker for Kusama/polkadot went through all of the steps Via the polkadot-js interface. I bonded some KSM, then the "waiting nominations" and the "active nominations" popped up. Being new, I was unsure why some had been nominated and others had not been. I had read somewhere that they needed sufficent amount of stake in order become "active"... so i had assumed I should be "depositing" more to enable them to initiate. I clicked on the "waiting nomination" list and then clicked on one of those validators. New window on the right hand side pops up and says "deposit" so... this was a DIFFERENT word than the "send" in the non staking part of the interface, so I assumed that this was the right spot to "deposit" more funds, to get these "waiting nomination" validators to start.  I was later made aware I had just "deposited" funds to people, and this was the same as "sending" to them. So funds may be lost completely due to this miscommunication/misunderstanding. 

the different words "send" vs "deposit" is extremely misleading here. unsure why the staking part of the thing would utilize this word, where as in the other parts of the interface "send" seems to be the standard

**Comment by jacogr** [comment]
Thanks for logging. I do like your suggestion of aligning it (this means sidebar & contacts) if it help clear up confusion. 

"Deposit" actually does align 100% elsewhere with the interface, i.e. in contacts for all "non-owed accounts". Anything that does not belong to you you can deposit into, anything that does belong to you can can send from.

The sidebar you are referring to is not part of staking, it is part of the global interface, so anywhere an address is visible, you can click on it to get more details on an account, save it to your contacts (or remove it if already saved), be it on any page such as accounts, explorer, governance, society, treasury, etc.
