### ISSUE TITLE
Update the architecture doc on wiki

### ISSUE THREAD

**Issue by alexsednz** [polkadot-js/apps#3272]
The content of https://github.com/polkadot-js/apps/wiki/Architecture has become obsolete at least regarding to jsonrpc as of https://github.com/polkadot-js/api/commit/044efbc6de4980dbabb5461c9d802c9c91634280 and https://github.com/polkadot-js/api/commit/27cd9b1ca49e99a993a7b453bae55a7740b25e26

**Comment by jacogr** [comment]
Thank you. I've switched it off, it doesn't get maintained (nor actually looked at), so I always get reminded that it exists by it being completely outdated.
