### ISSUE TITLE
Allows CRUD multiple set of custom types JSON

### ISSUE THREAD

**Issue by jimmychu0807** [polkadot-js/apps#3279]
Right now it supports only one set of custom type JSON.

I can find time to work on this. Jaco, what is your thought on this?

**Comment by jacogr** [comment]
Closing this. 

Like any urgent vs important discussion (which is how the next-up it prioritized), this doesn't mean it it won't add value, but rather that it won't get any focus. So the options are to have it sit gathering more dust or just be honest that based on capacity and focus-wise it will not get addressed.

If there is appetite for PRs to move things in the direction intended here, they will always be welcome.
