### ISSUE TITLE
Account Menu Page Error (proxy related)

### ISSUE THREAD

**Issue by emielvanderhoek** [polkadot-js/apps#3298]
Account Menu Page is no longer working for Kulupu Network.
![afbeelding](https://user-images.githubusercontent.com/14069142/88970119-27163580-d2b2-11ea-81b1-6e528fbeb7c8.png)

**Comment by emielvanderhoek** [comment]
Edgeware too

![afbeelding](https://user-images.githubusercontent.com/14069142/88970693-26ca6a00-d2b3-11ea-8be0-f75af41a6c12.png)

**Comment by jacogr** [comment]
Actually just fixed it in https://github.com/polkadot-js/apps/pull/3297/commits/01ba78b757d8abae1ba64b92c450b53fbe0a750c
