### ISSUE TITLE
Proxy management seems to be broken

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#3324]
![image](https://user-images.githubusercontent.com/738724/89193423-3e9d3900-d5a6-11ea-9c43-aadb5c33c2eb.png)
The address is: `Fom9M5W6Kck1hNAiE2mDcZ67auUCiNTzLBUdQy4QnxHSxdn` (Kusama).

The account indeed has a proxy:
![image](https://user-images.githubusercontent.com/738724/89193515-61c7e880-d5a6-11ea-9823-ca548afad011.png)

but clicking on:
![image](https://user-images.githubusercontent.com/738724/89193543-6b515080-d5a6-11ea-87c2-8691e16cba42.png)

does not show the proxy address:
![image](https://user-images.githubusercontent.com/738724/89193569-76a47c00-d5a6-11ea-9b10-e50c96466c04.png)

**Comment by chevdor** [comment]
I figure out why.
It shows up blank like this for:
- an account in local storage (not in the extension)
- when you open the UI from an IPFS link

**Comment by Tbaut** [comment]
I'll try to reproduce and fix.

**Comment by Tbaut** [comment]
> It shows up blank like this for:

>    an account in local storage (not in the extension)
    when you open the UI from an IPFS link

@chevdor can you confirm that you have the problem when both conditions are met (and not either)?
I checked with a localstorage account and I couldn't reproduce, I'll see how to reproduce with a local IPFS
