### ISSUE TITLE
Display of balance and number of transactions on Account Page seems broken 

### ISSUE THREAD

**Issue by wischli** [polkadot-js/apps#3333]
### 1. Account Page

Balances and number of transactions are displayed quite randomly on the Account Page. I ran into this issue both locally and on Kusama. 

<img width="494" alt="Screenshot 2020-08-04 at 15 43 51" src="https://user-images.githubusercontent.com/26296386/89301093-7b7e3400-d669-11ea-9bae-9990e67475ef.png">

Let's say my Kusama account holds `X` KSM which was displayed correctly until like a week ago. The next morning I checked, my balance was displayed as ~ `2.1 * X` **Y** KSM with `10,041,119,524,951,949,317` transactions. Since then, I see completely different balances in the range of `[0.8, 2.2]` of my actual balance in **Y** KSM. However, when I double check with some external wallet, everything is fine.

### 2. Chain State Page

Moreover, the Chain State page displays 0 available balance even though there is some free balance:

##### 2.1 Using Chain State page
```js 
{
  free: 0,
  reserved: 0,
  miscFrozen: 0,
  feeFrozen: 0
}
```
 
##### 2.2 Manually querying the chain

The resulting numbers correctly **match the ones displayed at the Account Page except** for the transferable amount, which is 0 on the account page but in reality greater than 1. So this should mean the problem sits in the RPC? Sorry, I just discovered this. 

```javascript
{
    nonce: ***,
    refcount: 242,
    data: {
      free: ***46,
      reserved: ***23865286762091311496129835117314048,
      miscFrozen: ***823865286762091311496129835117336497,
      feeFrozen: ***49,
    },
  }
```

**Comment by jacogr** [comment]
Which RPC node are you connecting to?

**Comment by wischli** [comment]
> Which RPC node are you connecting to?

It happens for any of the Kusama ones (Parity/W3F) to me.

> On 2.1 you queried balances.account - balances are not stored there, only in system.account. (So it is expected and correct to be all 0)

Ah, good to know, thanks.

**Comment by jacogr** [comment]
Exceptionally weird - which browser are you using (not that it should make a difference), but for some reason the tokenDecimals is read as 0. (Hence the question about the RPC node)

**Comment by wischli** [comment]
Google Chrome Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by jacogr** [comment]
Ok, I think I see what happens. The reserved is what causes the issue and then applies to the transferrable - if you are on Element/Riot, please do send me a message, would love to know the account to dig into (won't ask for it on a public forum)

**Comment by jacogr** [comment]
Cleaning the cache helped - so it seems like a types issue (even when cleared) - my structure decoding and the above were completely different.

Need to investigate the dev settings here and make sure it is done correctly.

**Comment by jacogr** [comment]
Closing, resolved.
