### ISSUE TITLE
Seed warning button ordering inconsistent

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/apps#334]
(nitpick) 
The warning modal that reminds the user to backup their seed phrase shows "Cancel" on the right-hand side of "Continue".

<img width="874" alt="screen shot 2018-09-24 at 9 55 24 am" src="https://user-images.githubusercontent.com/6226175/45934362-d4e29a00-bfe0-11e8-90df-606405d581df.png">

Whereas normally we show "Cancel" on the left-hand side, i.e.

<img width="197" alt="screen shot 2018-09-24 at 10 02 24 am" src="https://user-images.githubusercontent.com/6226175/45934424-5cc8a400-bfe1-11e8-80c2-584b656ad37a.png">

<img width="479" alt="screen shot 2018-09-24 at 10 02 38 am" src="https://user-images.githubusercontent.com/6226175/45934426-6225ee80-bfe1-11e8-82df-72202cf1652b.png">

<img width="254" alt="screen shot 2018-09-24 at 10 02 55 am" src="https://user-images.githubusercontent.com/6226175/45934428-6520df00-bfe1-11e8-98e2-4de2fc0e5caf.png">

**Comment by jacogr** [comment]
It is a good nitpick though, we should stick to "positive action on the right".
