### ISSUE TITLE
Amber network icon is set incorrectly

### ISSUE THREAD

**Issue by 0x7CFE** [polkadot-js/apps#3372]
It's icon always matches the one of currently active network:

<image src="https://user-images.githubusercontent.com/3784017/89672992-cc16bb00-d90f-11ea-9bca-33467db1916c.png" width="50%" height="50%">

**Comment by jacogr** [comment]
Introduced in https://github.com/polkadot-js/apps/pull/3357

Info should probably be “centrifuge” since there is an icon for it
