### ISSUE TITLE
cannot connect to the local node in Polkdot-js

### ISSUE THREAD

**Issue by mizou1234** [polkadot-js/apps#3378]
You are not connected to a node. Ensure that your node is running and that the Websocket endpoint is reachable.
![2891596978612_ pic_hd](https://user-images.githubusercontent.com/60725031/89732982-fb9b0400-da84-11ea-8e9b-e620ee93272e.jpg)
Do anyone knows what the error means and how to deal with it?

**Comment by jacogr** [comment]
Your URL is wong - you need the port, which is 9944 (e.g. the same as what is in the network selector)

![image](https://user-images.githubusercontent.com/1424473/89733310-ed34f400-da54-11ea-9d14-844ebe28eaa5.png)

**Comment by mizou1234** [comment]
> Your URL is wong - you need the port, which is 9944 (e.g. the same as what is in the network selector)
> 
> ![image](https://user-images.githubusercontent.com/1424473/89733310-ed34f400-da54-11ea-9d14-844ebe28eaa5.png)

I changed the URL, then the error is like this
“You are connecting from a secure location to an insecure WebSocket (ws://127.0.0.0:9944/). Due to browser mixed-content security policies this connection type is not allowed. Change the RPC service to a secure 'wss' endpoint.”
![2911597057270_ pic_hd](https://user-images.githubusercontent.com/60725031/89776440-783ce980-db3c-11ea-8741-db7c6f1eec85.jpg)
so what can I do to change the RPC service to a secure 'wss' endpoint.”?
thanks for reply!

**Comment by jacogr** [comment]
So, I would really just suggest using the node selector dropdown here and let the defaults just be filled in for you. Click on the network name, select Local Node under development.

The IP you gave is not localhost. Localhost is 127.0.0.1 not 127.0.0.0

**Comment by mizou1234** [comment]
Sorry,I am so careless. But now, while I connect to the correct localhost port, it always shows "Initializing connection" on the screen.
![2921597059735_ pic_hd](https://user-images.githubusercontent.com/60725031/89779313-a07b1700-db41-11ea-9123-c57639813c14.jpg)

**Comment by jacogr** [comment]
It doesn't expose the correct RPCs needed as the logs suggest -

- system_chainType - https://github.com/paritytech/substrate/blob/master/client/rpc-api/src/system/mod.rs#L49
- rpc_methods - https://github.com/paritytech/substrate/blob/master/client/rpc-servers/src/lib.rs#L48

The node is not configured correctly, so the API cannot determine how to work with it.

**Comment by mizou1234** [comment]
So is there something wrong with my node package? Or something else？where should I modify to overcome the error？

**Comment by mizou1234** [comment]
Two months before I could successfully access to polkadot-js, and I have not change the code, but recently it fails. Is it possible that the problem happens due to the the network？

**Comment by jacogr** [comment]
There has been a lot of updates in the node to make ready for the substrate 2.0 release. Having said that, the API always tries to maintain some backwards compatibility, for instance the current Edgeware mainnet is still supported.

I don't have enough in-depth on configuring the runtime to be of help, all I can suggest is looking at the template to see who the RPCs are defined.

**Comment by mizou1234** [comment]
Ok, thanks as well. I'll try.
