### ISSUE TITLE
Payout all without waiting

### ISSUE THREAD

**Issue by derfredy** [polkadot-js/apps#3383]
Hi Jaco!

The **Payout all** buttom is greyed out until the network calculates for 2, 6, 18 or 84 eras rewards.
That is slow in Polkadot, and maddening in Kusama. Kind of waste of network node resources and bad for the user experience.

I'd suggest:
When you go to Payouts sections by default non of the options should be selected thus not forcing any network task.
Instead, the Payout button should be clickable and get the whole pending rewards without waiting nor asking anything.

Regards

**Comment by jacogr** [comment]
That is an extra click. So it only starts loading when you go to the page, no before. Additionally, it starts with the fastest 2-day option - even when changing options at this point it does not start from srcatch, rather it is only getting the ones it does not have already.

So for instance if it had 2 eras already and you change options, it will not re-get those 2.

**Comment by derfredy** [comment]
Thanks Jaco. I maybe wrong, but is it needed to load the fastest 2-day option to get your payouts?
I mean, I thought it was possible to trigger everything  with just 1 click, the **Payout all** button click.

**Comment by jacogr** [comment]
It needs to figure out which eras and for which validators you have rewards.

The call is per validator for a specific era. See https://polkadot.js.org/api/substrate/extrinsics.html#payoutstakers-validator-stash-accountid-era-eraindex

**Comment by jacogr** [comment]
Closing. The TL;DR here is that to have a lit of all info for stashes, it needs to query. Which is why there are flags such as eras to query (optimizing the number of queries) and recently allowing for validators only (optimizing the subset, ignoring any nominators the user may have).
