### ISSUE TITLE
Data driven UI/UX development with Mixpanel

### ISSUE THREAD

**Issue by yjkimjunior** [polkadot-js/apps#339]
@Tbaut we were talking about UX the other day and in my opinion in the medium-long term, we would want to see exactly what users' behaviors are on the application so we can iterate on exactly where confusions/frustrations lie rather than preemptively trying to imagine & anticipate what users are doing/thinking.

[Mixpanel](https://mixpanel.com/help/reference/javascript) is super useful for this, and is an industry standard for UI/UX development at centralized tech companies, both consumer and enterprise facing.

I personally think it'd give us a lot of insight into the gap between what's obvious/trivial for devs versus for regular users. It'd also show us exactly what prompts/actions/labels/errors/page navigations/component organizations are causing the most friction for people to follow through and ultimately complete a transaction of some sort through our UI.

On the other hand, it's also kind of against the whole ethos of not being creepy, not tracking everyone, etc. so I wanted to raise this issue to open the discussion.

What do you think?

**Comment by Tbaut** [comment]
>On the other hand, it's also kind of against the whole ethos of not being creepy, not tracking everyone, etc. so I wanted to raise this issue to open the discussion.

We've been pretty strict regarding such data collection in the past with Parity Ethereum and my opinion is that it should stay this way. We can perform UX studies without collecting data broadly, the key IMHO is to be very close to the community and keep good track about what is said/written.

**Comment by jacogr** [comment]
We should not enable any analytics. Apart from the GDPR (and the hoops we need to jump through if we collect anything in Europe), any kind of analytics does not play well with the crypto userbase, it is an immediate permanent black mark against the service.
