### ISSUE TITLE
Parachain registration is botched when uploading genesis state

### ISSUE THREAD

**Issue by JoshOrndorff** [polkadot-js/apps#3396]
When registering a cumulus parachain, the proceedure I'm familiar with is to use the Sudo tab to call `registrar` -> `register para`.

When choosing the "file upload" option to input the `initial_head_data` the extrinsic succeeds, but the registration is incorrect. The collator does not produce blocks and displays the messages:
```
2020-08-11 17:18:00 Could not decode Parachain header: Error("Error decoding field Digest.logs")
2020-08-11 17:18:00 Could not decode the head data: Error("Error decoding field HeadData.header")
```

However if you paste the contents of the genesis state into the textbox, the registration succeeds.

**Comment by jacogr** [comment]
What does the file look like?

**Comment by xlc** [comment]
I had same issue. Using extrinsic and enter hex value from node works.

**Comment by jacogr** [comment]
It is an issue purely on the UI side - support for hex was added ages ago specifically for this use-case and (I have not yet looked), it is either not working or was dropped along the way. Nothing to do with how it is output, the support is supposed to be there.
