### ISSUE TITLE
Account adding. Wrong account generation from Raw seed

### ISSUE THREAD

**Issue by StepanLavrentev** [polkadot-js/apps#3411]
**Detail description:**
For "Raw seed" the address is generated incorrectly when you specify a password in the derivation path

*Case:*

1. Go to accounts
2. Click add account
3. Choose mnemonic type - Raw seed
4. Fill in the required fields
5. Remember the address that was generated
6. Enter derivation path - "///password"

**Actual result:**
Address has not changed after entering ///password

<details>
  <summary>Spoiler!</summary>
  
![image](https://user-images.githubusercontent.com/40560660/90132518-ae65ad80-dd76-11ea-922e-79298db796b7.png)
![image](https://user-images.githubusercontent.com/40560660/90132537-b7567f00-dd76-11ea-8200-69f7fd6a5717.png)

</details>

**Comment by Tbaut** [comment]
I could reproduce, but the bug is rather that any derivation path should be ignored with a raw seed. In other words, not only `///password` should be ignored, but any derivation path like `/soft//hard///password`, the UI should probably hide this field altogether then. I'll dig a bit into that because this is only from memory, there used to be a mention about this in the kusama wiki, but I couldn't find it.

**Comment by Tbaut** [comment]
I found it, it's on substrate.dev about subkey: https://substrate.dev/docs/en/knowledgebase/integrate/subkey#password-protected-keys

> Note that the "Secret seed" is not password protected and can still recover the account. The "Secret phrase" however, is not sufficient to recover the account without the password.

The UI here mentions that a hex or a string is accepted for "raw seed". I imagine that this is for backward compatibility reasons.
![image](https://user-images.githubusercontent.com/33178835/90140370-f0dcb980-dd79-11ea-8360-a05e535a2df6.png)

@jacogr will surely know more about the why.

**Comment by jacogr** [comment]
Ok, that makes sense. Should at least error or show as invalid.

So `///password` is applied when converting from mnemonic to entropy.

**Comment by Tbaut** [comment]
From my tests, it looks like the UI is behaving exactly like `subkey` (this contradicts part of my first message, I edited it):
- derivation paths (hard and soft) have an incidence on both the mnemonic and the hex seed
- any `///password` is ignored for hex seed but taken into account for mnemonic (as the doc says)
```bash
subkey generate -w 12
  Secret phrase `trophy welcome benefit junk simple post still zoo athlete tape dove explain`
  Secret seed:        0xaad3d470d2070a72bf5e8afcd224c00c2053b522164a1bb99e59a8176d3f4ec1
  SS58 Address:       5FAFcqAAVReGD21HfqVuw6Qe7XPBiAhLQGu7WygbDWdNU16e

# inspect the account from the mnemonic and adding a hard path
subkey inspect "trophy welcome benefit junk simple post still zoo athlete tape dove explain//bla"
  SS58 Address:       5FRawdkLQTkvwMkSp9TVD3HdSZzZoNmHuCwYXiepJpWZpViq

# using the same hard path but with the hex seed results in the same
subkey inspect "0xaad3d470d2070a72bf5e8afcd224c00c2053b522164a1bb99e59a8176d3f4ec1//bla"         
  SS58 Address:       5FRawdkLQTkvwMkSp9TVD3HdSZzZoNmHuCwYXiepJpWZpViq

# using an additional "///pass" with the mnemonic outputs a new account
subkey inspect "trophy welcome benefit junk simple post still zoo athlete tape dove explain//bla///pass"
  SS58 Address:       5FnTW1wHrHLQVRyyaiQ7rcm7pyTuf1wUWMMLFy2FLBDo6CkD

# whereas the "///pass" is basically ignored with a hex seed, the address is the same as with "//bla" only
subkey inspect "0xaad3d470d2070a72bf5e8afcd224c00c2053b522164a1bb99e59a8176d3f4ec1//bla///pass"         
  SS58 Address:       5FRawdkLQTkvwMkSp9TVD3HdSZzZoNmHuCwYXiepJpWZpViq
```

So my suggestion would be to keep it as is, and just show a warning if we detect a `///` in the derivation path.

**Comment by jacogr** [comment]
Yes. Think we do that for soft in ed25519 - if not also squash that alongside. (Although I think that is in... or used to be)
