### ISSUE TITLE
[question] Why do I use the FormatBalance component to format the number of our tokens, the base is a thousand times smaller

### ISSUE THREAD

**Issue by yuhui1208** [polkadot-js/apps#3413]

**Comment by yuhui1208** [comment]
Tested on https://github.com/substrate-developer-hub/substrate-node-template
Same unit problem

**Comment by jacogr** [comment]
The `tokenDecimals` is set in the chain spec properties. when not specified the UI applies a default. If you want to be specific, update your chin spec to the value you want. (Some chains are on 10, 12, 15 or even 18)

**Comment by yuhui1208** [comment]
thank you for your great help!!!
