### ISSUE TITLE
Unit Test business logic to ease refactoring

### ISSUE THREAD

**Issue by yjkimjunior** [polkadot-js/apps#344]
nothing crazy since typescript linter does a lot of work already, but unit tests would complement `tsclint` and improve the current workflow of manually clicking about everywhere.

Mainly want to test for:
 * all components are rendering properly
 * public methods output and handle errors as expected
 * state transitions behave as expected

**Comment by jacogr** [comment]
Remove assignment while you are occupied elsewhere.

**Comment by jacogr** [comment]
Closing this. 

Not because it is not important, but rather since it is not going to get done in any kind of timeframe. Would love to have this in manageable chunks (probably only some time after the ongoing"all-component-rework"), but only if we actually have resourcing.
