### ISSUE TITLE
Unable to fetch balances

### ISSUE THREAD

**Issue by maxsam4** [polkadot-js/apps#3453]
App fails to process account balances
![Screenshot from 2020-08-20 13-07-45](https://user-images.githubusercontent.com/7436022/90730808-5f73c700-e2e6-11ea-87cc-6a9d1753c116.png)
and the console has these errors
![Screenshot from 2020-08-20 13-12-52](https://user-images.githubusercontent.com/7436022/90731131-e9239480-e2e6-11ea-86bc-3fcfe459a574.png)

System.account is present
```
system.account: AccountInfo
{
  nonce: 27,820,
  refcount: 0,
  data: {
    free: 99.651M POLYX,
    reserved: 0,
    miscFrozen: 0,
    feeFrozen: 0
  }
}
```

test rpc endpoint: `wss://alcyone-rpc.polymesh.live/`
schema (and code in same branch): https://github.com/PolymathNetwork/Polymesh/blob/alcyone/polymesh_schema.json

api v1.30.0-beta.0
apps v0.55.0-beta.13

Any idea what's going on here?

**Comment by jacogr** [comment]
No idea. The only way to track is to run locally, setup, connect and have an account to check (which has balances). If this happens on contacts as well and you can supply an address that I can add to contacts, may be able to take a look.

**Comment by jacogr** [comment]
Ok, connected, forgot that I can just query through to a validator - it tries to retrieve the vested amount as well, however the chain doesn't have vesting. So there is an extra condition that should be added for support for this specific chain configuration.

**Comment by jacogr** [comment]
Reopening until API pulled in.

**Comment by maxsam4** [comment]
Thanks @jacogr ! Lightning fast as always :1st_place_medal:
