### ISSUE TITLE
Menus are no longer responsive or are distorted on smaller screen sizes

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/apps#3457]
Yesterday when I used https://polkadot.js.org/apps it showed the menu on the left hand side of the screen (the way it has been for months) with an icon we could click to minimise the menu, as shown below

![Screen Shot 2020-08-21 at 8 01 05 am](https://user-images.githubusercontent.com/6226175/90830181-93052e80-e384-11ea-93aa-ec3cba88ab6f.png)

But today when I went there, the layout of the menu has changed so it only shows it at the top of the screen. It displays ok on large screen sizes, but it distorts on smaller screen sizes and on mobile.

![Screen Shot 2020-08-21 at 7 59 21 am](https://user-images.githubusercontent.com/6226175/90830395-ed05f400-e384-11ea-83b6-ab974bb97a13.png)

![Screen Shot 2020-08-21 at 7 59 39 am](https://user-images.githubusercontent.com/6226175/90830398-eecfb780-e384-11ea-80e3-6fe95e388498.png)

It's no longer responsive on mobile, as shown in the screenshot below:

![Screen Shot 2020-08-21 at 8 00 25 am](https://user-images.githubusercontent.com/6226175/90830399-ef684e00-e384-11ea-872a-62ea0b34c880.png)

The landscape feature is otherwise really good

**Comment by jacogr** [comment]
Replaced by #3467
