### ISSUE TITLE
Support AccountIndex related operations

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#3499]
The indices logic is heavily changed with https://github.com/paritytech/substrate/pull/4820
User is now able to claim, free & transfer arbitrary index.

I don't think it is currently possible to discovery indices directly from on-chain data (without iterate the whole map), but should at least allow user to manually input indices.

And maybe have a super slow discovery operation that does iterate the whole map and save relevant data in localStorage.

**Comment by jacogr** [comment]
Will keep it on ice, since it is a very niche thing. The assumption is that the people who know about the niche can claim themselves. If this gains wider traction, happy to add an option.

**Comment by xlc** [comment]
It is a nice feature to save tx fee, e.g. validators will want to have index to nominate to them can be cheaper.

Automatic lookup is indeed slow, but allow user to manually input the indices will solve the issue. Then people can use block explorer to discover indices and enter it into Polkadot apps and have it saved in contacts.

**Comment by jacogr** [comment]
Closing since as it apparent, people expect this to work as Indices lookups (none of the new generation chains define it that way, including Polkadot/Kusama). As a vanity indicator on these networks, users can add it themselves.
