### ISSUE TITLE
DRR: Error: createType(EraIndex):: Assertion failed

### ISSUE THREAD

**Issue by yuhui1208** [polkadot-js/apps#3500]
How can I solve such an error

**Comment by jacogr** [comment]
Without any information on what you are doing, I cannot be of assitance.

**Comment by yuhui1208** [comment]
When I called the interface of api.derive.staking.overview, an error was reported and the prompt message was `2020-08-24 15:15:36             DRR: Error: createType(EraIndex):: Assertion failed
    at createTypeUnsafe (/Users/yuhui/Documents/tsproject/crust-sdk/node_modules/@polkadot/types/create/createType.js:69:11)
    at createType (/Users/yuhui/Documents/tsproject/crust-sdk/node_modules/@polkadot/types/create/createType.js:81:10)
    at TypeRegistry.createType (/Users/yuhui/Documents/tsproject/crust-sdk/node_modules/@polkadot/types/create/registry.js:195:39)
    at /Users/yuhui/Documents/tsproject/crust-sdk/node_modules/@polkadot/metadata/Decorated/storage/fromMetadata/createFunction.js:189:283
    at /Users/yuhui/Documents/tsproject/crust-sdk/node_modules/@polkadot/metadata/Decorated/storage/fromMetadata/createFunction.js:165:109
    at ApiPromise._retrieveMapKeys (/Users/yuhui/Documents/tsproject/crust-sdk/node_modules/@polkadot/api/base/Decorate.js:424:21)
    at /Users/yuhui/Documents/tsproject/crust-sdk/node_modules/@polkadot/api/base/Decorate.js:342:76
    at Observable._subscribe (/Users/yuhui/Documents/tsproject/crust-sdk/node_modules/@polkadot/api-derive/util/memo.js:29:17)
    at Observable._trySubscribe (/Users/yuhui/Documents/tsproject/crust-sdk/node_modules/rxjs/src/internal/Observable.ts:238:19)
    at Observable.subscribe (/Users/yuhui/Documents/tsproject/crust-sdk/node_modules/rxjs/src/internal/Observable.ts:219:14)`

**Comment by jacogr** [comment]
On which chain/node combo?

**Comment by yuhui1208** [comment]
It is on our chain developed based on rc5, how to control this type of registration?

**Comment by jacogr** [comment]
So the above would mean there is a type mismatch between what you defined and what the chain provides. You would need to check the staking -related types and adjust as needed.

**Comment by yuhui1208** [comment]
Our chain did not modify the Index type, which of the apps should be modified?

**Comment by jacogr** [comment]
Did you change anything around the staking interfaces?

**Comment by yuhui1208** [comment]
We have made a lot of changes to the staking module, but it was able to run normally before, but the latest changes have caused this problem

**Comment by jacogr** [comment]
With the limited info you are providing, I can just suggest -

- look at all of the new types in Rust
- compare those to the JS versions
- adjust as needed

**Comment by yuhui1208** [comment]
thank you very much!

**Comment by jacogr** [comment]
`.toHuman` certainly should not be used inside derives. It, as the name suggests, is for display. So either currentEra o eraStakers is not as expected.

**Comment by yuhui1208** [comment]
I tried to register the type of EraIndex as Option<EraIndex>, but this will cause many other interfaces to be unusable

**Comment by jacogr** [comment]
It it an option in your chain?

**Comment by yuhui1208** [comment]
In addition, I can't find any way to solve the error of this method

**Comment by jacogr** [comment]
So, if you have a customized staking interface with the Substrate-default methods changed, it on't work with the derives o the UI as build. So in that case, you need to provide your own functions and modify the UI.

This is not something the apps repo here will built in out-of-the box support for. (In principle if there is a new type of staking module that is widely used, the apps UI itself will try and support both, e.g. like it does with old/new versions)

So as it stands, there is sadly not much help I can offer further since it very much is out of scope here.

**Comment by yuhui1208** [comment]
With the iteration of the version, this problem may no longer exist, thank you very much for your patient answer

**Comment by jacogr** [comment]
Closing.
