### ISSUE TITLE
Invalid Transaction: Transaction has a bad signature

### ISSUE THREAD

**Issue by yz89** [polkadot-js/apps#3504]
After forcing a refresh of polkadot-js/apps,  I meet this error when I  send funds using apps.

```
balances.transfer
1010: Invalid Transaction: Transaction has a bad signature
```
It's ok to send funds before I refresh it.

My chain developed base on v2.0.0-rc4.

**Comment by jacogr** [comment]
Without understanding your chains and the types involved and how adjustments are made to cater for those, cannot quite comment with the limited info above.

Is it node-template based? Substrate-full based? Have you added any type overrides? If so, which?

**Comment by yz89** [comment]
The chain is node-template based with version v2.0.0-rc4.
It's Substrate-full based.
I have added some types look like below and it worked fine before.
```
{
  "Address": "AccountId",
  "Url": "Bytes",
  "RefNum": "H256",
  "Result": "Bytes",
  "Model": {
    "account": "AccountId",
    "payment": "u32",
    "cid": "Bytes"
  }
...
}
```
I roll back my chain code to last release version and meet new errors when sent funds: 
```
polkadot.02.b9fcc847.js:1 2020-08-26 09:39:56        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature: RuntimeApi("Execution: Could not convert parameter `tx` between node and runtime: No such variant in

polkadot.02.b9fcc847.js:1 2020-08-26 09:39:56             DRR: Error: 1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature: RuntimeApi("Execution: Could not convert parameter `tx` between node and runtime: No such variant in

main.76575b0d.js:352 signAndSend: error: Error: 1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature: RuntimeApi("Execution: Could not convert parameter `tx` between node and runtime: No such variant in

polkadot.02.b9fcc847.js:1 2020-08-26 09:39:57        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature: RuntimeApi("Execution: Could not convert parameter `tx` between node and runtime: No such variant in
```

What can be done now？

**Comment by yz89** [comment]
I added some other accounts into the endowed_accounts vector.
``
pub fn local_testnet_config() -> ChainSpec {
	ChainSpec::from_genesis(
		"Local Testnet",
		"local_testnet",
		ChainType::Local,
		|| testnet_genesis(
			vec![
				authority_keys_from_seed("Alice"),
				authority_keys_from_seed("Bob"),
			],
			get_account_id_from_seed::<sr25519::Public>("Alice"),
			vec![
				get_account_id_from_seed::<sr25519::Public>("Alice"),
				get_account_id_from_seed::<sr25519::Public>("Bob"),
				get_account_id_from_seed::<sr25519::Public>("Charlie"),
				get_account_id_from_seed::<sr25519::Public>("Dave"),
				get_account_id_from_seed::<sr25519::Public>("Eve"),
				get_account_id_from_seed::<sr25519::Public>("Ferdie"),
				get_account_id_from_seed::<sr25519::Public>("Alice//stash"),
				get_account_id_from_seed::<sr25519::Public>("Bob//stash"),
				get_account_id_from_seed::<sr25519::Public>("Charlie//stash"),
				get_account_id_from_seed::<sr25519::Public>("Dave//stash"),
				get_account_id_from_seed::<sr25519::Public>("Eve//stash"),
				get_account_id_from_seed::<sr25519::Public>("Ferdie//stash"),
			],
                        ...
```

I don't know if it makes a difference.

**Comment by jacogr** [comment]
When adding `"Address": "AccountId",` you need to add `"LookupSource": "AccountId"` as well (The API has a FAQ entry with aditionl links that explains why - https://polkadot.js.org/api/start/FAQ.html#i-cannot-send-transactions-from-my-node-template-based-chain)

**Comment by yz89** [comment]
You solved my problem, thank you very much. 

Close this issue.
