### ISSUE TITLE
Feature: Error Context

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#3507]
Popup notifications should have a "learn more" button/link on them. This should summon a popup explaining a certain message in detail. One example that's very frequent right now in our support channels is the keepAlive error where a transfer fails. People don't see the ED as intuitive and are surprised that we're currently dusting anything below 1 DOT.

My proposal is:

- define a JSON file of message details matching errors, events, and extrinsics to long form messages.
- on popup event, check if the error name, event name, or extrinsic name appears as key in that JSON file.
- if so, show the "Learn more" link, or default to "Learn more" when clicking the notification.
- pop up the text bound to that key from the JSON file.

This has several advantages:

- a singular place in which to keep all such explanatory messages, easily enhance-able with links to in-depth resources like the wiki
- a single file which can be translated by community members so we can get easy translations of these explainers
- more context and fewer support questions in riot and elsewhere
- very easy to contribute to and does not interfere with the rest of the build process. Currently updating an individual component is complex for the uninitiated and not very intuitive, but a single file with key value pairs is simple for everyone.

**Comment by jacogr** [comment]
Transfers now by defauly uses the keep alive version. (No dusting unless wanted via toggle)

**Comment by jacogr** [comment]
Sure, happy to accept PRs for this. From `<module>.<error>` can map.

**Comment by jacogr** [comment]
Closing this. 

Like any urgent vs important discussion (which is how the next-up it prioritized), this doesn't mean it it won't add value, but rather that it won't get any focus. So the options are to have it sit gathering more dust or just be honest that based on capacity and focus-wise it will not get addressed.

If there is appetite for PRs to move things in the direction intended here, they will always be welcome.
