### ISSUE TITLE
12  SEED WORD GENERATING WRONG ADDRESSES .POLKADOT.JS/APPS

### ISSUE THREAD

**Issue by wilderbeast19** [polkadot-js/apps#3517]
Kindly assist in recovering my account, the 12 seed generates another address which is not even in polkastat, 
it also generates various addresses.

**Comment by jacogr** [comment]
The same mnemonic can generate different addresses based on the crypto type. Ensure you have the correct type (as initially use), set here in the add via seed -

![image](https://user-images.githubusercontent.com/1424473/91257359-f79c0100-e769-11ea-9160-8615bca48476.png)

**Comment by wilderbeast19** [comment]
Your group of developers will have to look at this case, something is wrong
, another person had the same issue, he mentioned it yesterday on the
telegram page for Kasuma.but he had no funds in the address and just
abandoned the address.
Now this is the history of sequence of events.

1, created account on polkadot.js/apps

2, did not do json backup

3, move funds to account

4, wanted to move funds to external wallet, password was rejected

5, tried to recover account with 12 word seed. different address pops up,
that are not on polkastat

6, checked my initial address funds are still there.

Please solving this issue is important for me.

Expect a solution reply from you.

thanks.

**Comment by jacogr** [comment]
Like I mentioned above, check the crypto type. Also ensure that the network prefix is correct in your settings. This is  user-issue, so trying to help you through it.

**Comment by wilderbeast19** [comment]
i don't think so , i have done all your suggestion, i am also communicating
with the official telegram admin. this is my third year in blockchain, this
have never happen to me, assuming i was in the same location as you, i will
hand my seed words and the real address and tell you to recover my funds.

**Comment by jacogr** [comment]
The only way the addresses are different -

- mnemonic is different
- crypto type is different
- different derivation path was used

As suggested the display (not underlying value) can be different if this UI setting uses a different prefix from what was originally used -

![image](https://user-images.githubusercontent.com/1424473/91283352-c849bc00-e78a-11ea-9ae9-7a9b7e6df58c.png)

**Comment by wilderbeast19** [comment]
ok, i will try all the suggestions, i really cannot remember the exact
parameters, but i will try all the options.

thanks for your  assistance and patience.

**Comment by wilderbeast19** [comment]
i have tried, please what is the policy concerning sending my 12 seed and
address , so that my funds are safe, it may not be much for some, but its a
lot to me .KSM 300.

**Comment by jacogr** [comment]
I can't do anything different to what you are doing since there are no mnemonic loopholes. The steps that anybody would take would be -

- select the existing mnemonic
- copy & paste new mnemonic into box (overriding above)
- enter correct crypto type and derivation path (if changed from defaults)
- match address

**Comment by jacogr** [comment]
Still trying to help, this time I'm trying to understand your initial comments -

1. "did not do json backup" - The create UI forces you to download the `.json` file. If you click cancel there, you are taken back to the create screen (so it cannot be bypassed). Please check your downloads folder.

2. "password was rejected" - Do you have any transactions from this account? If you entered the password twice correctly to create, not sure how it can be forgotten unless it is a caps issue.

**Comment by wilderbeast19** [comment]
1, it does not take you back to create screen. i did not backup json.you
can do any experiment now.

2, Please read this very well,

      a, assuming i have the wrong 12 seed, the system will not accept it

      b, how come, the system accepts the 12 seed , then generate an
address or addresses that is not on polkastat, blockchain this is very
fundamental.

      c, out of all the addresses generated by the 12 seed, the only one
visible in polkastat is the initial address with my funds, which i do not
have access to.

     d, please do not brush this aside, this is why i am willing to take
the risk and send the 12 seed and the original address.

     e, there is an issue.

**Comment by jacogr** [comment]
Polkastats only shows addresses where transactions has already been done. The local generation creates a keypair with secrets can can sign. Once a tx is made, the explorers will show it.

Please see the creation flow where you it does not allow you to continue without backing up (cancel takes you to the create screen, no account created) -

![screencast 2020-08-26 13-49-25](https://user-images.githubusercontent.com/1424473/91300221-37cba580-e7a3-11ea-9ed5-dc4fb3ac489b.gif)

**Comment by wilderbeast19** [comment]
below is the initial address with my funds.


Hpuv8pE1iabbfU4UC5kw7hnnArbFm2ECJTzvjpFGGagH7Nh

below is the current address the seed generates, which is not in polkastat


DTNZvMfdhZAiN6yBD69S6JX4pq17FGBd4VVisfmbkTJq694


And, if i make changes to derivation, different address pop up which are
not in polkastat


i believe something happen a bug maybe, while i was creating the account.

**Comment by wilderbeast19** [comment]
i clicked on create and back up, it takes you to your download , in your
computer, 2 options appear, save or cancel, i clicked cancel, it will then
take you to the main portal with your account created,
try it again, click create and backup, it will take your to your folders
and download, it will then request your save or cancel, cancel it, the
account will be created with saving the json file'

**Comment by jacogr** [comment]
Yes, as explained earlier is it 100% correct that changes in derivation would change the address - any hard or soft derivation modifies the keypair, so a new address is expected. (It allows you to use the same mnemonic with different derivation paths to have multiple accounts)

**Comment by wilderbeast19** [comment]
its like . i am on my own in this matter, but, i did not misplace my
password or seed phase.

ihave the right seed phase and password and i cannot access my funds.

**Comment by rryter** [comment]
I have the same problem, although it's $KLP related, I'll try all the suggestions.

**Comment by wilderbeast19** [comment]
Another gentleman,  had too, but was yet to fund the account.

**Comment by rryter** [comment]
Just to be clear, I assume I have lost a substantial amount of money here.

**Comment by jacogr** [comment]
Closing, nothing the UI can do here. It is up to the user to make sure he has the correct details as the account was created with.
