### ISSUE TITLE
Support Ethereum PairType

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/apps#3519]
CRYPTOS needs to include
```
{
  info: 'ethereum',
  text: 'Ethereum (BTC/ETH compatible)',
  value: 'ethereum'
}
```
(and ECDSA needs to remove the `(BTC/ETH compatible)`

**Comment by crystalin** [comment]
It also needs to be supported there:
https://github.com/polkadot-js/apps/blob/562e11dc06c656da92ec957cf9de063ebb507cb6/packages/react-components/src/util/toAddress.ts#L16

This is failing when using the ethereum type.

**Comment by jacogr** [comment]
Closing thanks to the tireless effort by @joelamouche
