### ISSUE TITLE
Staking inline help can't be closed

### ISSUE THREAD

**Issue by dvdplm** [polkadot-js/apps#3538]
Slight UI problem with the inline help and the "tab bar" on top: the close button (`x`) is hidden. On pages where the main content area has more content than fits on screen it's enough to scroll down a little to make the top tab bar get hidden and the `x` to close the help pane appears. However on short pages such as `Payouts` this is not possible and the user has no way of closing the help pane.

![image](https://user-images.githubusercontent.com/18515/91439618-9198a200-e86d-11ea-800f-cc8f4bbe9ac5.png)

**Comment by jacogr** [comment]
Erk.
