### ISSUE TITLE
Languages on polkadot js org

### ISSUE THREAD

**Issue by giacoro** [polkadot-js/apps#3544]
Hi i wanted to be a translator and i asked to add italian as a language. I wanted to know if this language can be added or approved

**Comment by jacogr** [comment]
Perfect! Yes. Certainly something that we can add and it would be really appreciated. For this work, we can also create a bounty on Gitcoin. So if you are interested in doing this, we can also add a bounty there.

Translations can be done in parts, so for instance if you only do accounts fist, we can already merge that as-is, without waiting for 100% completion on everything.

**Comment by jacogr** [comment]
Please see https://github.com/polkadot-js/apps/issues/3549 - feel free to apply, would be really happy to see these additions. We have a nice active community in Italy.

**Comment by jacogr** [comment]
I am closing this one @fomod-in has done an unbelievable job in updating the translations for Italian.

Grazie mille!
