### ISSUE TITLE
Add Parity Signer compatibility

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#355]
[Parity Signer](https://wiki.parity.io/Parity-Signer-Mobile-App) is an app that manages a user's keys and is able to sign data without the device containing the keys having to be online. This data is transferred by QR code.

Parity Signer will support ed25519 after https://github.com/paritytech/parity-signer/issues/155

Regarding the integration in the UI, from a conversation with @jacogr the following is needed:

- keyring needs to have the concept of external account added (i.e. keys managed elsewhere)
- account add needs to be able to do the whole scan/import dance to add external
- signer, when external, just displays QR

**Comment by maciejhirsz** [comment]
Should be first tackled in https://github.com/parity-js/qr-signer

**Comment by jiangfuyao** [comment]
If I want to Integrated offline signature function in mobile wallet sames Parity Signer,  can I use:
- Hot wallet to show the QR, the data is:  
```javascript
api.tx.balances
    .transfer(toAddress, AMOUNT)
//and the Nonce by `const nonce = await api.query.system.accountNonce(fromAddress);`.
```
- Then use the Cold wallet to scan the QR, get data, then to Sign, and to show the Sign data QR:  
```javascript
const nonce = QRdata.nonce;
QRdata.Transfer.sign(alicePair, { nonce })
//Then to show the QR: `QRdata.Transfer.sign(alicePair, { nonce })`
```
- Use the Hot wallet to scan the Sign QR, then to send this Transfer: 
```javascript
QRdata.send(...)
```
Is that going to be enough to get the parity singer offlline sign functionality done? Or what's the difference?
