### ISSUE TITLE
Can not add an account 

### ISSUE THREAD

**Issue by netmebtc** [polkadot-js/apps#3552]
version 0.55.1
when add an account, there is an error:
Uncaught error. Something went wrong with the query and rendering of this component. @polkadot/wasm-crypto has not been initialized

**Comment by jacogr** [comment]
Where are you trying it? Via polkadot.js.org/apps, dotapps.io, docker or the Electron app?

**Comment by netmebtc** [comment]
Hello, I use this one：  https://github.com/polkadot-js/apps/releases/download/v0.55.1/Polkadot-JS-Apps-0.55.1.exe

**Comment by jacogr** [comment]
Thank you - and just the default account type?

**Comment by jacogr** [comment]
Ok, can confirm.

**Comment by jacogr** [comment]
Ok, have a fix, it will be in Monday's release for 0.56.1 - really sorry about this, the recent security tie-down on the Electron app disallowed any WASM execution, which means that sr25519 keys stopped working.

**Comment by netmebtc** [comment]
That’s great news, your problem solving speed is really fast, it’s commendable
