### ISSUE TITLE
to understand how and where see the remaining days of a democracy lock

### ISSUE THREAD

**Issue by dbpatty** [polkadot-js/apps#3556]
in this moment i can't  find any info to calculate the remaining days for a democracy lock ( in any sections or js), the only info that i found is the tx creation date.
It should be very helpfull to have this info on account section near the lock info or js to do that.

**Comment by mariopino** [comment]
Definitely useful IMO!

**Comment by jacogr** [comment]
It shows on the UI -

![image](https://user-images.githubusercontent.com/1424473/91555833-06351480-e932-11ea-8845-a964a7468c27.png)

(There is a gap where for delegated accounts it doesn't show, no an intentional miss, just missed)

**Comment by dbpatty** [comment]
i have this:
![image](https://user-images.githubusercontent.com/1618184/91559529-8d858680-e938-11ea-98af-a5374d9e02c8.png)

**Comment by jacogr** [comment]
On which chain? Edgeware I'm assuming?

**Comment by jacogr** [comment]
Do you have a specific address for me? Can check against that one if it is possible to detect these old/previous-generation locks and make a menu entry available.

**Comment by dbpatty** [comment]
it is kusama, I'll send to you riot , the address is not mine.

**Comment by dbpatty** [comment]
done

**Comment by jacogr** [comment]
On the account, there is not really anything the UI can do, the info it has is the following -

- `{"Direct":{"votes":[],"delegations":{"votes":0,"capital":0},"prior":[0,0]}}` - the votes made, from here expired votes (which will show) can be used to unlock, there is no info
- `[{"id":"0x64656d6f63726163","amount":"0xffffffffffffffffffffffffffffffff","reasons":"Misc"}]` - the balances locks, democracy is full locked

The issue with democracy.unlock is that it needs referendum ids. So it can be tried with id 0 and see if it unlocks.

**Comment by jacogr** [comment]
Closing, the UI sadly has no additional info here on the old locks. However, for anybody else facing this on ancient votes, try `democracy.unlock(target)` (callable by anybody, as above, doesn't need to be the actual account)
