### ISSUE TITLE
Vested funds should also show countdown

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#3561]
Right now vested funds do not show the remaining blocks until fully vested. Finding out how many tokens per block are vested is also only possible through checking chain state. I recommend adding this information to the Accounts UI: the information popup should contain the "X per block" value on the "vested" row, and "Until block 3000000 on Aug 1st 2023" on the "locked" row.

**Comment by jacogr** [comment]
Glad somebody is mentioning vested for a change, I am never sure what is useful to others. For my personal use (aka my vested stuff) I'm always just interested on what is available. 

Will add it to the queue.

**Comment by jacogr** [comment]
Closing, done in #3587
