### ISSUE TITLE
author_rotateKeys method not found

### ISSUE THREAD

**Issue by vikiival** [polkadot-js/apps#3576]
Hey, 

i'm playing with staking api and to add new validator you have to call `author_rotateKeys`.
However, when I call that method I get `-32601: Method not found` 

<img width="1920" alt="Screen Shot 2020-08-30 at 16 37 06" src="https://user-images.githubusercontent.com/22471030/91661927-64ebc100-eadf-11ea-883c-fc4019ae635c.png">

**Comment by jacogr** [comment]
It is an unsafe RPC, check your node flags (`--help`) for exposing unsafe RPCs.

**Comment by vikiival** [comment]
https://substrate.dev/docs/en/tutorials/start-a-private-network/customchain#first-participant-starts-a-bootnode

> The optional --rpc-methods=Unsafe flag has been added. As the name indicates, this flag is not safe to use in a production setting

Thanks for help.
