### ISSUE TITLE
HAVE JSON FILE BUT YET LOCATE PASSWORD, ANY HELP OR WHAT CAN I DO TO GET MY FUNDS

### ISSUE THREAD

**Issue by wilderbeast19** [polkadot-js/apps#3583]
Hi, need assistance on how to access my funds, have the json file, but the password, i am yet to remember.

**Comment by jacogr** [comment]
You need to remember the password to unlock the JSON file, no way around it.

**Comment by jacogr** [comment]
Closing, nothing that the UI can add or do when a user forgets the password.
