### ISSUE TITLE
Unable to restore ECDSA accout

### ISSUE THREAD

**Issue by akru** [polkadot-js/apps#3589]
![restore](https://user-images.githubusercontent.com/786394/91863228-91d2dc00-ec77-11ea-9cdd-596bcbcaf7f0.png)

**Description**

Unfortunately on the latest PolkadotJS Apps ECDSA JSON account restoring is broken, the button isn't activated but import available pressing ENTER. Probably somewhere missed `ecdsa` key type.

**Comment by jacogr** [comment]
Ok, that seems small, but a bug...

**Comment by akru** [comment]
Yes, just visual but confuses many users.
