### ISSUE TITLE
TypeError: e.number.unwrap is not a function when submitting candidacy on ~~master~~ kusama

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#3595]
Launching my master node with `--chain kusama-dev --pruning archive --alice` on 0.8.23-e2ebf25b-x86_64-linux-gnu

When I go to Council > Submit candidacy > Submit

I get the following type error in the console:
> TypeError: e.number.unwrap is not a function

When Signing the extrinsic, the notification mentions:
> signAndSend: error: TypeError: e.number.unwrap is not a function

**Comment by Tbaut** [comment]
oh, I just realized that it's also happening on the current Kusama. Not 100% sure if it's in apps or the api.

**Comment by jacogr** [comment]
You'll need to point to the place it happens. There has been election fixes, I'm assuming the interfaces are now different, so probably need yet-another old/new check.

**Comment by Tbaut** [comment]
Here is one:
https://github.com/polkadot-js/apps/blob/master/packages/react-query/src/Events.tsx#L55

**Comment by jacogr** [comment]
![image](https://user-images.githubusercontent.com/1424473/92001132-97dfc000-ed3e-11ea-8bd4-b8ba23570e40.png)

![image](https://user-images.githubusercontent.com/1424473/92001162-a29a5500-ed3e-11ea-8ac0-dade44ace148.png)

**Comment by Tbaut** [comment]
Interesting, I get this using apps https://polkadot.js.org/apps/#/council on kusama and polkadot live.
Here is the origin of the other one https://github.com/polkadot-js/api/blob/e5c2c6a22849a1582df161a358060f104e7fad23/packages/api-derive/src/tx/signingInfo.ts#L36

**Comment by jacogr** [comment]
Check your added types.

**Comment by Tbaut** [comment]
Found the problem, I had custom types that were overriding the previous ones
