### ISSUE TITLE
When I use the keyring component to send transactions, it will produce a stutter of about 1s. I found that this may be caused by the encryption and decryption of the account. How can I avoid this situation?

### ISSUE THREAD

**Issue by yuhui1208** [polkadot-js/apps#3638]

**Comment by jacogr** [comment]
There is a pkbdf used on the keyring since `@polkadot/keyring` 3.0 to increase security of accounts. So an decryption delay is to be expected.

**Comment by jacogr** [comment]
Closing. As much as I also hte this extra delay, it was done for security purposes after an audit/review. It optimizes it as much as possible by using WASM, but yes, still noticable.
