### ISSUE TITLE
Include option for arbitrary accounts as a reward destination

### ISSUE THREAD

**Issue by jack-kearney** [polkadot-js/apps#3642]
I noticed recently that Substrate now allows staking rewards to be redeemed to [arbitrary accounts](https://github.com/paritytech/substrate/blob/fd2c136866b81a42f5a12e7afc0dc41cd69af44b/frame/staking/src/lib.rs#L428). However, it looks like this feature hasn't yet been rolled out into polkadot.js.org/apps.

If I understand the logic correctly, seems like [this](https://github.com/polkadot-js/apps/blob/c35081f6c77c03422557690b46bc739bbaf6ccb9/packages/page-staking/src/Actions/constants.tsx) is the only place that would need to be updated.

Is there something else preventing this? If not, I can submit a PR to introduce the new value

**Comment by jacogr** [comment]
Logged as https://github.com/polkadot-js/apps/issues/3354 so closing this as duplicate.

It needs detection for the different networks since not all support it, which is the only tricky bit.

**Comment by jack-kearney** [comment]
Gotcha - makes sense!

**Comment by jacogr** [comment]
So did add support for at least displaying it in the account action page today (and changing when already set). But as of this moment, the best way to set it via the Extrinsics app. Once set though, can be managed.

**Comment by jacogr** [comment]
@jack-kearney Just FYI, enabled it today globally since it went live on Polkadot (and it already available on Kusama). So will create slight issues with older chains where not available... Not a perfect solutions, but can set it anywhere now.

**Comment by jack-kearney** [comment]
@jacogr Thanks! Super helpful to have in there. No clean solution for detecting the chain is jumping out at me. Will think on this though
