### ISSUE TITLE
Unable to use same wallet in both, kusama and polkadot

### ISSUE THREAD

**Issue by derfredy** [polkadot-js/apps#3643]
Minor issue with low impact / importance

How to reproduce it:

Create an account in one of the chains.  Give it a name. Save the json and import it on the other chain. It will appear with its name.
But if you go back to the original chain it was created you will see it has disapeared from the list. If you repeat you will notice it only can exist on one chain at the same time.

I know it is not a good practice to have the same account on various networks. I only did it because this is the account I use for my auto-payout validators scripts on both chains.

**Comment by jacogr** [comment]
Toggle the "tie to network" option. Any created account (unless on a dev chain) defaults to that chain -

![image](https://user-images.githubusercontent.com/1424473/92576609-04504700-f28a-11ea-92e3-fc3dc46ed7e5.png)

**Comment by derfredy** [comment]
That switch effectively solves the issue. You only can not give it different names on each chain.
Tanks Jaco.
