### ISSUE TITLE
Potential problem with using the "/" inside password part in DP

### ISSUE THREAD

**Issue by stepanLav** [polkadot-js/apps#3647]
Potential problem with using the "/" symbol the password part for the derivation path.
When creating an account in the secret derivation path we can specify a hard, soft path as well as a password and after entering 3 characters "/" - everything is considered as a password but the user is not notified of this.

For example:

<details>
  <summary>On subkey app</summary>
  <img src="https://user-images.githubusercontent.com/40560660/92646138-a1dd6200-f2ee-11ea-9444-821dd9d1349b.png" data-canonical-src="https://user-images.githubusercontent.com/40560660/92646138-a1dd6200-f2ee-11ea-9444-821dd9d1349b.png" width="800" height="100" />
</details>

<details>
  <summary>On JS app</summary>
  <img src="https://user-images.githubusercontent.com/40560660/92645962-604cb700-f2ee-11ea-9fa7-573fcd22757a.png" data-canonical-src="https://user-images.githubusercontent.com/40560660/92645962-604cb700-f2ee-11ea-9fa7-573fcd22757a.png" />
</details>

**Case 1:**

1. User creating account
2. Set derivation path with password and make a mistake - type 4 characters "/"
(////password)

**Result:**
Account creation with password - "/password", but user wanted to create an account with "password"

----
**Case 2:**

1. User creating account
2. Set derivation path - "///password/soft//hard"

**Result:**
Account creation with password - "password/soft//hard"

----

Maybe should limit the entry of the "/" symbol or give a more detailed description?

**Comment by stepanLav** [comment]
@kirushik

**Comment by jacogr** [comment]
On the 2 -

- The first makes total sense that the password is `/password` since that is exactly what is supplied
- The second could probably do with a warning since he may intend hard & soft (I guess the first as well would be caught with an "after password check")

So apps UI will never get in your way, but will try and guide you in areas where there are common mistakes. Guidance without being overly prescriptive or limiting. So a warning on paths that _may_ be unintended (where the second is a good example) could be useful.

**Comment by kirushik** [comment]
I suggest both cases working as they probably should — we just treat everything after `///` as a password and make no other assumptions or splitting attempts there.
I would propose us documenting this behaviour explicitly somewhere where the rest of the derivation format is specified — to reduce potential confusion and ensure third-party implementations would share this implementation approach.

I agree that having a warning for the second case might be beneficial, though — but in the worst case the "treat it all as a password" approach wouldn't actually reduce user's security, even if being a bit unexpected. (Again, things might go weird if this is not implemented consistently across different implementations.)

**Comment by Tbaut** [comment]
I'll make a PR to add a warning as soon as a `/` is detected in a password. This will catch both cases as Jaco said.
