### ISSUE TITLE
Error on Multisig Transaction

### ISSUE THREAD

**Issue by jack-kearney** [polkadot-js/apps#3649]
I've been trying to initiate a transaction from a newly generated multisig account and am running into an error with the UI.

<img width="553" alt="Screen Shot 2020-09-09 at 7 58 58 PM" src="https://user-images.githubusercontent.com/1410750/92669858-b31f7200-f2e0-11ea-814a-44e6f684eda0.png">

After clicking "Sign and Submit" the operation appears to be in a pending state but never completes or is cancelled. When I refresh the page it has disappeared

**Comment by jacogr** [comment]
So after a refresh  the error did not persist and the Rx went through?

Not sure why it tries to get a block for and empty hash there, or why either.

**Comment by jack-kearney** [comment]
For context, the extrinsic wouldn't go through before. Just tried again and all seems well. Thanks for the quick fix!
