### ISSUE TITLE
Make derivation errors translatable

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#3662]
I suppose when the error gets thrown we use an index string and then a lookup on the UI alongside the translatable text.

As seen in https://github.com/polkadot-js/apps/pull/3660/files#diff-a07a1ad3dc171e647cb05d98c01a53eeR60

**Comment by Tbaut** [comment]
Ah totally, tackling that now.

**Comment by jacogr** [comment]
Sure it is not the only place, I fixed some yesterday that I found on my travels (for an options dropdown). The errors are generally trickier, but if found, may as well log and attempt.
