### ISSUE TITLE
Fix "Query Ledger" button in Firefox

### ISSUE THREAD

**Issue by anjaw3f** [polkadot-js/apps#3665]
As Ledger user reported that the Query Ledger button on polkadot.js is unactive/non-responsive in Firefox. He was able to access his ledger by switching to chrome, where the button works.

**Comment by jacogr** [comment]
That is probably a WebUsb issue. Indeed, no support - https://developer.mozilla.org/en-US/docs/Web/API/USB

Since we only have WebUsb support, should disable it completely in FF.
