### ISSUE TITLE
Add ical export for event calendar

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#3685]

**Comment by wirednkod** [comment]
Just implemented an idea on the (per event) export:
![export](https://user-images.githubusercontent.com/5408605/100148357-537b4080-2ea5-11eb-858b-f36d607e1ecc.png)

**Comment by wirednkod** [comment]
PR #4068 if ok can close this

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/apps/pull/4068
