### ISSUE TITLE
Make sure council members are aware about the acceptance/rejection of a treasury

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#3686]
It's written quite clearly, 
![image](https://user-images.githubusercontent.com/33178835/93227039-44289a00-f774-11ea-813b-424b80ea3535.png)

But the fact that some have approved may trick your mind into "approving", you may not read that part, and end up approving the rejection of a proposal without noticing.
I think that some red/green could help. Any opinion / idea on how this could look like?

**Comment by Tbaut** [comment]
Understood, that's a won't fix then I guess.

> This is actually a good showcase for why auto-close may be a bad idea

I never thought about that. Although I think the "close" was rather introduced to put less pressure on the runtime (no need to check for every vote if it's a closing one). I imagine the council member that will vote last will most likely close right away without the other voters being involved (and think twice about their votes).

**Comment by jacogr** [comment]
Generally most members actually vote _without_ closing :)
