### ISSUE TITLE
Direct link to validator stats redirects to /staking on first visit

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#3687]
Example link: http://polkadot.dotapps.io.ipns.localhost:8080/#/staking/query/15fU523Wq5BCt2NWAmrCU6p8nFB29uVifeG7bwYJHbw5Mmd9

Resolved page: http://polkadot.dotapps.io.ipns.localhost:8080/#/staking

If on the same tab we re-enter `http://polkadot.dotapps.io.ipns.localhost:8080/#/staking/query/15fU523Wq5BCt2NWAmrCU6p8nFB29uVifeG7bwYJHbw5Mmd9` it will open the specific validator.

**Comment by jacogr** [comment]
Applies to all staking tabs.
