### ISSUE TITLE
manage hardware connections setting not working on firefox

### ISSUE THREAD

**Issue by lucasshenv** [polkadot-js/apps#3689]
![Screenshot 2020-09-15 091153](https://user-images.githubusercontent.com/1643232/93236658-f2601f80-f733-11ea-818d-e21aa02fc6a1.png)

Left hand side is firefox. I don't have option to attach my ledger device. Chrome on the right. Worked as expected. 

dot app:
Parity Polkadot v0.8.23-d327000a
api v1.34.0-beta.3
apps v0.59.0-beta.6

device: ledger nano x, firmware: 1.2.4-4
ledger live: 2.10
polkadot app: 4.18

The issue applies to both my Mac and Windows machine.

**Comment by Swader** [comment]
Explained in #3665

**Comment by lucasshenv** [comment]
Got it.

**Comment by jacogr** [comment]
It is a nightmare - Ledger deprecated u2f. WebUSB is only on Chrome.

So yes, it sucks.
