### ISSUE TITLE
Can't set-on chain identity on Edgeware 

### ISSUE THREAD

**Issue by yangwao** [polkadot-js/apps#3695]
Whenever I'm connected on Edgeware mainnet and try to set on-chain identity from Accounts. Is there other way around to set on-chain identity, through Developer>Extrinsics>Identity>setIdentity I guess?

```
TypeError: Cannot destructure property 'basicDeposit' of 'l.consts.identity' as it is undefined.
TypeError: t.query.democracy.votingOf is not a function
```

![image](https://user-images.githubusercontent.com/5887929/93332546-477a5f00-f822-11ea-8623-9ccedef52999.png)

**Comment by jacogr** [comment]
You can always go through the extrinsics tab.

Once Edgeware has upgraded to a recent version of Substrate, it should be better.

**Comment by jacogr** [comment]
Closing. (However, did make the constant retrieval optional in a commit, so it _should_ already behave slightly better)
