### ISSUE TITLE
Can't connect on local running Substrate node

### ISSUE THREAD

**Issue by yangwao** [polkadot-js/apps#3696]
Maybe it's because insecure content?

From Chrome 
![image](https://user-images.githubusercontent.com/5887929/93336443-0e44ed80-f828-11ea-8358-f0bdef275bfe.png)

From Safari
```
[Log] WS endpoint= – "ws://127.0.0.1:9944" (main.6de5d3ab.js, line 1)
[Log] web3Enable: Enabled 0 extensions:  (polkadot.02.31e3a8be.js, line 1)
[Warning] [blocked] The page at https://polkadot.js.org/apps/#/explorer was not allowed to run insecure content from ws://127.0.0.1:9944/. (polkadot.01.f616c0a7.js, line 1)

[Error] Unhandled Promise Rejection: [object Event]
	(anonymous function)
	rejectPromise
	rejectPromiseWithFirstResolvingFunctionCallCheck
	(anonymous function) (polkadot.01.f616c0a7.js:1:109635)
	(anonymous function) (other.01.847a8481.js:18:53884)
	value (polkadot.01.f616c0a7.js:1:111404)
	(anonymous function) (other.01.847a8481.js:18:53884)
	value (polkadot.01.f616c0a7.js:1:348246)
	value (polkadot.01.f616c0a7.js:1:348767)
```

Apparently it looks it's running and listening

```
❯ lsof -nP -iTCP:9944 | grep LISTEN
substrate 2809  wao   69u  IPv4 0x826872434d790d23      0t0  TCP *:9944 (LISTEN)
```

**Comment by yangwao** [comment]
Even adding allowing insecure content doesn't help 
![image](https://user-images.githubusercontent.com/5887929/93337203-194c4d80-f829-11ea-9f91-501ede764d3e.png)

**Comment by yangwao** [comment]
ok, setting to ws://0.0.0.0:9944 works now. 
But strange, I haven't changed anything in my environment, still using substrate-2.0.0-rc4

**Comment by jacogr** [comment]
Yes, it is a browser config issue. By default the localhost WS should be allowed (mixed-content to localhost), however it is touch-and-go depending on browser versions.

**Comment by jacogr** [comment]
Closing.
