### ISSUE TITLE
Add ENS support

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#3700]
[ENS now supports DOT and KSM](https://github.com/w3f/polkadot-wiki/pull/973). Adding ENS support would let people send tokens with `mydomain.eth` addresses. Leading by example, Apps support would encourage other wallets to embrace ENS support as well.

Integration guide: https://medium.com/the-ethereum-name-service/how-to-integrate-ens-multi-coin-support-into-your-wallet-for-developers-8d3a8a37d1eb

**Comment by jacogr** [comment]
Really not going to make calls to resolvers on Ethereum at this point. Will very happily support it on EVM-based chains in the Polkadot ecosystem.

**Comment by jacogr** [comment]
Sadly, as of now (really hoping this will change in the medium-term) closing this as a won't fix.
