### ISSUE TITLE
createType(Call):: Struct: failed on 'args':: Struct: failed on 'keys':: Invalid AccountId provided, expected 32 bytes, found 1

### ISSUE THREAD

**Issue by yuhui1208** [polkadot-js/apps#3708]
When I call the interface api.tx.session.setkeys, this error will be reported

**Comment by jacogr** [comment]
How are you calling it? On which network? Is your Keys structure set correctly for the chain (assuming it is customised)

**Comment by yuhui1208** [comment]
On the chain we developed, but I did not modify the type of keys, I called it on polkadot-js/apps

**Comment by jacogr** [comment]
For eg. Polkadot where there are 5 keys i the structure, this override is applied - https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/polkadot.ts#L8

(That type is just a Tuple of AccountId's, in that case referring to 5, the default in substrate is 4. The type is just a helper with 3, 4, 5 for combinations)

**Comment by yuhui1208** [comment]
In polkadot-js/apps, should I define my own type in app-config/api/spec?

**Comment by jacogr** [comment]
Indeed, if it is not the standard Substrate type, it needs to be supplied to match the chain.

**Comment by jacogr** [comment]
Closing.
