### ISSUE TITLE
api.query.identity.identityOf()

### ISSUE THREAD

**Issue by ironoa** [polkadot-js/apps#3710]
This question is related to both the UI and the API.

A BIT OF CONTEXT:

Here in https://polkadot.js.org/apps/#/chainstate is possible to select 'identity' and then 'identityOf': if I toggle OFF the 'include option' flag and then trigger the call (leaving the accountId empty), the response will be and array of **Option\<Registration\>, exactly what I'm looking at.**

![image](https://user-images.githubusercontent.com/25957738/93565931-76144900-f98c-11ea-90ff-d4658ffed4a7.png)

I assume that under the hood the UI is leveraging the .identityOf() @polkadot/api call from https://polkadot.js.org/api/substrate/storage.html#identityof-accountid-option-registration
 

THE QUESTION:

In my nodejs application (even from https://polkadot.js.org/apps/#/js), If I try to replicate this behavior using api.query.identity.identityOf() passing no arguments (or empty string) there is no way to make it works. 
The function needs an argument of type (arg: AccountId | string | Uint8Array).
Is the UI using perhaps a derive method (https://github.com/polkadot-js/api/tree/master/packages/api-derive) under the hood ? **Is there a way to retrieve this ARRAY of Option\<Registration\> ? Could someone please provide me an example of how to achieve this via a (@polkadot/api) ApiPromise object call ?**

FYI api.query.identity.identityOf('accountID') is working properly, but I'd really need to get the array of all the identity as in the UI.

![image](https://user-images.githubusercontent.com/25957738/93565989-8cbaa000-f98c-11ea-96a3-7888af6d33d4.png)

**Comment by jacogr** [comment]
https://polkadot.js.org/api/start/api.query.other.html#map-keys-entries

**Comment by ironoa** [comment]
Thanks a lot Jaco,

```
api.query.identity.identityOf.entries()
```

Did the trick for me.

So my code section will look like:

```
const entries = await this.api.query.identity.identityOf.entries()
entries.forEach(([key, exposure]) => {
    const registration = <Option<Registration>> exposure
    console.log(`accountId: ${key.args.map((k) => k.toHuman())}`);
    console.log(`\tregistration:, ${registration.unwrap().judgements} `);
});
```
