### ISSUE TITLE
Imported accounts disappear

### ISSUE THREAD

**Issue by Poggi-Luca** [polkadot-js/apps#3722]
I try to import some accounts in https://polkadot.js.org/apps using Plasm chain, then if I change chain and re-select again Plasm chain, my imported accounts disappear.

Do you know this issue?

Thank you

**Comment by jacogr** [comment]
Import the accounts. Then make sure for those you select (under options) tie to this chain. Accounts are tied by genesisHash. (Available on any network will make it available on all)

**Comment by Poggi-Luca** [comment]
Hey Jaco, thank you for your help!
I knew this function, but not having it enabled I thought everything was ok ........ instead for some reason it was automatically enabled on Dusty.
I can now keep accounts imported on both Plasm and Dusty.
Thank you
