### ISSUE TITLE
Warn when importing via JSON and genesisHash does not match

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#3729]
Either warn or swap to the genesis explicitly (or both)

This avoids users importing an the account disappearing (like in https://github.com/polkadot-js/apps/issues/3722, there has been a couple of reports)

**Comment by Tbaut** [comment]
I'll have a look at this one unless you're working on it already.

**Comment by jacogr** [comment]
No, feel free - I actually forgot to log it explicitly yesterday and just thought about it again when doing https://github.com/polkadot-js/apps/pull/3728 (Really need to stop forgetting to log stuff, big or small)
