### ISSUE TITLE
Ledger account offset difference from 0.58 to 0.59

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#3747]
We have inquiries from several users who imported their Ledger account on 0.58, and now the UI is giving them another address on 0.59. I assume this is because the account offset was null before, and defaulted to 0/0 only in 0.59. How do we help the users get their original address back?

**Comment by jacogr** [comment]
The defaults have always been 0/0, it only allows you to select it now.

**Comment by jacogr** [comment]
Does the Ledger "show address" match up between the 2?

**Comment by jacogr** [comment]
Closing. Feel free to reopen with actual reproduction information. As of now non-reproducible with no extra information as requested.

**Comment by Swader** [comment]
It seems it might be because people followed screenshots on the wiki, and a screenshot there used 1/2 as an example of what's possible. Verifying and will post again if not. Thanks!
