### ISSUE TITLE
Edgeware staking actions and apps pages are throwing errors

### ISSUE THREAD

**Issue by drewstone** [polkadot-js/apps#3752]
After our first runtime upgrade, many apps pages are not entirely compatible with the Edgeware upgrade. I'm investigating, posting an issue for tracking if anyone has quick fixes.

**Comment by jacogr** [comment]
The Edgeware types are still on the older versions - https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/edgeware.ts

At least the StakingLedger here would be outdated now. (ReferendumInfo is probably also an issue for democracy)

**Comment by drewstone** [comment]
Yep, I'm updating right now.
