### ISSUE TITLE
Loaded JSON files accept any password to create account; cannot send funds from this account

### ISSUE THREAD

**Issue by laboon** [polkadot-js/apps#3765]
DESCRIPTION:
User can load JSON file to account with any password.  No matter what they type in, an account will be generated.

However, users will be unable to sign transactions from that account.

TO REPRODUCE:
1. Create a new account on Polkadot-JS
2. Give password 'password'
3. Forget account
4. Load account from JSON file
5. Enter password '123456'

EXPECTED BEHAVIOR:
Error

OBSERVED BEHAVIOR:
Account is loaded into polkadot-JS

----

TO REPRODUCE:
1. Try to send funds from that account
2. Enter correct password

EXPECTED BEHAVIOR:
Funds sent

OBSERVED BEHAVIOR:
Appears as though password is rejected

**Comment by laboon** [comment]
After loading this JSON file with the incorrect password (`123456`), I cannot send from it even using the correct password (`password`).  The UI just freezes momentarily.

If I try to send and enter the incorrect password `123456` it is correctly seen as an invalid password.

Essentially, if you mistype the password when loading the JSON file, you will not be able to send from that account.

**Comment by laboon** [comment]
Even after loading the JSON file with the correct password, I am unable to send any DOT from that account.

**Comment by Tbaut** [comment]
Thanks for the details Bill, taking a look.

**Comment by Tbaut** [comment]
Seeing this PR a little late, that's where things went wrong: https://github.com/polkadot-js/apps/pull/3758/files
