### ISSUE TITLE
Ledger Shows No Encrypted Data Available to Decode

### ISSUE THREAD

**Issue by wpank** [polkadot-js/apps#3768]
When trying to add a Ledger account the following happens: (on runtime 0.8.24)

![ledger](https://user-images.githubusercontent.com/9498646/94278065-af2f5900-ff4a-11ea-9d1f-8fa8a150e6fc.png)

**Comment by TheClarkster** [comment]
I am seeing the same.

**Comment by jacogr** [comment]
All accounts/indexes or some? (Error is for the underlying Ledger libs itself, will check them to see if there has been recent versions)

**Comment by KazzanK** [comment]
Same issue here, yesterday all was fine using Ledger. 
Issue is for All accounts/indexes

**Comment by wpank** [comment]
Yep, I get the same for all accounts/indexes

**Comment by jacogr** [comment]
Exceptionally weird since none of that stuff has been touched at all since the account/index selector went in and the app went through the approval proces. I'll try and bump the official Ledger HQ libs for USB.

**Comment by wpank** [comment]
This started to happen after the runtime upgrade yesterday - another possible reason it's currently borked.

**Comment by TheClarkster** [comment]
> 
> 
> Exceptionally weird since none of that stuff has been touched at all since the account/index selector went in and the app went through the approval proces. I'll try and bump the official Ledger HQ libs for USB.

I can confirm I haven't updated Ledger Live or the app on the Ledger itself.  It worked fine yesterday and isn't today.

**Comment by jacogr** [comment]
Also no actual updates or touching in the apps UI, hence the absolute major confusion :) Will also take a look through the Zonda/Ledger JS libs to see if there is any indication about that error.

(As of right now, I'll update to the latest LedgerHQ libs, not sure it will fix anything, but always good keeping that updated anyway.)

**Comment by KazzanK** [comment]
I also confirm no update done for me nor on Ledger Live or the app on the Ledger itself.
Working all fine yesterday and isn't today.

**Comment by jacogr** [comment]
Can I please ask you ty refresh the UI and retry? The bumps went in. (My Ledger is only available around 90mins from now, so can only check myself afterwards... don't ask...)

**Comment by wpank** [comment]
Just tried and can confirm it now worked.
