### ISSUE TITLE
Setting Specified payment account on Ledger gives 'Value out of range' error

### ISSUE THREAD

**Issue by rhosyn** [polkadot-js/apps#3770]
From account actions:
Change reward destination -> Select 'Specified Payment Account' -> enter address -> click 'Set reward destination' gives the following error:

<img width="335" alt="Screen Shot 2020-09-25 at 6 35 21 PM" src="https://user-images.githubusercontent.com/38064401/94298914-cc6e2280-ff5e-11ea-8162-be043367a8d2.png">

**Comment by jacogr** [comment]
Couple of quick questions -

- has the stash made txs before? 
- which are Ledger accounts? Stash and/or destination?

**Comment by rhosyn** [comment]
- Originally no, the stash has only received a transaction. Since your comment, I've made a small transaction out and re-attempted but I still get the same error. 
- Destination account is not a ledger account (it's a wallet on Polkawallet). Stash & controller accounts are ledger accounts.

**Comment by jacogr** [comment]
Ok, so -

- stash - Ledger, confirmed working
- controller - Ledger, this is the sender of the transaction (error _may_ originate here)
- destination - as long as it is an account added via contacts or as an actual account, should be fine

**Comment by jacogr** [comment]
I am suspecting something weird with the multiple accounts -

What is your stash/controller account and indexes in this case? (Will try to replicate, Just need to know what is shows as, ie. „Ledger 1/2“ in accounts)

**Comment by rhosyn** [comment]
I've set up the ledger stash/controllers with this pattern:
Stash: 0/0
Controler: 1/0

Stash: 0/1
Controler: 1/1

Stash: 0/2
Controler: 1/2

Stash: 0/3
Controler: 1/3

etc.

**Comment by jacogr** [comment]
Perfect. Ok, not tonight, but will try and replicate first thing in the morning.

**Comment by jacogr** [comment]
Ok, have tracked it down, it is a Ledger issue, it does not cater for the latest RewardDestination structures, it only caters for the Stash, Controller and Staked entries, not Account.

- For Kusama https://github.com/Zondax/ledger-kusama/blob/master/app/src/substrate_types.c#L295-L304
- For Polkadot https://github.com/Zondax/ledger-polkadot/blob/master/app/src/substrate_types.c#L303-L312

**Comment by jacogr** [comment]
Closing. Tracking issue on Ledger.
