### ISSUE TITLE
Ledger options not shown in Firefox

### ISSUE THREAD

**Issue by dvdplm** [polkadot-js/apps#3771]
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/18515/94304961-bb2e1180-ff70-11ea-8ba4-9d4d2b19974e.png">

Using FF Nightly at `83.0a1 (2020-09-24) (64-bit)` the options to use a Ledger does not show up (does work in Chrome and on Android).

Maybe FF doesn't support WebUSB?

**Comment by dvdplm** [comment]
Hmm, I guess [it doesn't](https://developer.mozilla.org/en-US/docs/Web/API/USB).

**Comment by jacogr** [comment]
FF doesn’t support WebUSB. U2F is deprecated on Ledger. So no support at all.
