### ISSUE TITLE
UI freeze when loading "Staking overview"

### ISSUE THREAD

**Issue by dvdplm** [polkadot-js/apps#3772]
When the user navigates to the Network/Staking for the first time during a session the UI freezes for a long time (~10sec).

Chrome Canary `Version 87.0.4274.0 (Official Build) canary (x86_64)`.

**Comment by jacogr** [comment]
Sadly... it is what it is. There are continuous improvements, however it is a vet expensive excersise. As the numbers increase on Kusama (which is worse), the amount of info will be dropped.

**Comment by dvdplm** [comment]
So the work of ensuring the UI stays responsive even when processing data is tracked elsewhere?
