### ISSUE TITLE
POLKADOT.JS/APPS SENDING DOT COINS VIA QR code via parity signer

### ISSUE THREAD

**Issue by mariosluc** [polkadot-js/apps#3777]
When I try to send a transaction to another wallet address and sign the transaction via SIGN VIA QR code via parity signer from my phone, get a error down below"

I was able to transfer coins 10 days ago with same QR code.

Any way to resolve

![Screen3](https://user-images.githubusercontent.com/35635488/94344664-d0e21c00-ffee-11ea-91d2-47dbe726b70a.jpg)

**Comment by jacogr** [comment]
You are scanning an address. Read the QR from the signer app, then scan the resulting QR code.

**Comment by mariosluc** [comment]
jacogr, thank you very much for your help!!
