### ISSUE TITLE
(FR) add any address / remember account after unplugging Ledger

### ISSUE THREAD

**Issue by drandreaskrueger** [polkadot-js/apps#3788]
Great function, that "Add Ledger" in '[accounts](https://polkadot.js.org/apps/#/accounts)'. Very easy to use, and comfortable. Just one wish:
### Feature Request: remember account address

When I unplug the Ledger Device, my browser always forgets the related account, not even the address is remembered.

What about: Offering an "**Add read-only account**" to the buttons, then I could simply add the address of _any account that also contains my coins_ (with perhaps in column 'type' as 'read-only' or 'address only'?).  Or when the Ledger is plugged in, and an account had been added via "Add Ledger ... Save", then one more menu (three vertical dots) option right below "Forget this account" - but with a new function "**Remember this account**" (and then in column 'type' saying 'ledger, unplugged' or simply still 'ledger')

Then e.g. my balance and other info is always there, regardless whether I have plugged in the device or not.

Thanks for considering this small enhancement. Best regards.

(P.S.: If the Ledger has already timed out, and is in "vires in numeris / PIN code" mode, and I then try to "Add Ledger ... Save", I get an "Unknown Status Code: 26628" error message. Probably you want to catch that.)

**Comment by Swader** [comment]
When you add a Ledger account to your apps UI, you will have it automatically added to your Address Book (under contacts). You can see info about the account there, including balance.

**Comment by drandreaskrueger** [comment]
You mean here: https://polkadot.js.org/apps/#/addresses ?  

Yes automatically would be good. I have now added my ledger addresses there, manually.

**Comment by Swader** [comment]
It appeared for me automatically, but it may have happened because I renamed my account (clicking on the edit icon in the account's sidebar).

**Comment by anjaw3f** [comment]
Is there a reason why the accounts page does not remember the Ledger account? It remembers all the other accounts that are created with external tools. This is confusing a lot of users.

**Comment by jacogr** [comment]
It is not usable. So remembering it there means it needs to be usable- which means that everything else needs to have the Ledger attachment logic. 

So basically to do the above we need to introduce an account inactive state and consistently handle it in the UI. 

(This one alongside the other open Ledger PRs are quite delayed since atm I don’t have a Ledger anymore - horrible accident involving kids, so none of these can be tested and features can’t be done blind. So while I wait for Ledger no 3, no movement on any features)

**Comment by chevdor** [comment]
Not a solution but it may help people running into the issue. It also will not reach the usability threshold from @jacogr but it works as woraround atm.

As long as you remember the derivation path (0/0, 0/1, ...) of the account(s) created, you can "get them back" by adding them again every time you want to use them. It takes only a few clicks per account, no password and no confirmation on the Ledger.

Cherry on top, the name of the account (if you edited it) and the ⭐  state remains and your account shows up as it never left the accounts' list. It is not permanent but at least we are not in the situation where people are stuck not being able to send transactions.

**Comment by jacogr** [comment]
The linked PR will always remember the accounts. Just needs a round of testing before merging.

**Comment by anjaw3f** [comment]
Jaco, not sure if this should go here, but it's related: Some users are getting confused by the button title "Add Ledger". It sounds like "adding a new (additional) account" to them and I've been getting emails "I don't want to add a new account, I want to access my existing one". It's not a huuuge deal, and I don't have a suggestion for a better name, but thought I'd mention it.

**Comment by jacogr** [comment]
Should not go here - since the issue is closed nobody will look at it again so the request is just lost. (Unless I remember - which I won’t since I’m old)

**Comment by anjaw3f** [comment]
Ah, just noticed the big red CLOSED button :D
