### ISSUE TITLE
AccountId encode fails in contract tab.

### ISSUE THREAD

**Issue by taskooh** [polkadot-js/apps#3803]
I have a trouble while calling method from contract tab.

when the params include AccountId,I selected Bob for example, but he console show the error `Unable to encode address AccountIndex values not allowed 0x`

and cannot send with transaction with proper account.

![image](https://user-images.githubusercontent.com/20131692/94829679-ba502080-0445-11eb-86cf-623588812134.png)

**Comment by jacogr** [comment]
Does a normal transfer work? (The reason for asking is that the Address types may be wrong, so that is just the general test)

**Comment by taskooh** [comment]
> Does a normal transfer work? (The reason for asking is that the Address types may be wrong, so that is just the general test)

Yes, when selecting a account from Extrinsics->balances -> transfer, it is working.

**Comment by jacogr** [comment]
Ok, briefly looked - it seems to be innocent on the actual component (that actual log should not be there, and the error is transparently hndled, not passing up to the caller).
