### ISSUE TITLE
Vested Amount Doesn't Show

### ISSUE THREAD

**Issue by wpank** [polkadot-js/apps#3805]
The following occurred on Kusama:

- Vested amount isn't included in total amount for the account
- You unlock the vested amount
- The vested amount then doesn't show as part of the drop downs

**Comment by jacogr** [comment]
How do you mean "it is not included in the total". The total shows the free & reserved balance from system.account (without doing accounting on it for vesting, etc).

Can you check the system.account details for that account? (free should match up with what is being seen.)

If broken on one, it will be broken everywhere, and I have some vested as well as vested-transfer accounts myself for these checks. (Also on Kusama)

**Comment by jacogr** [comment]
Closing. Feel free to reopen with specifics if needed.
