### ISSUE TITLE
Spanish version of polkadot.js translates DOT to Punto

### ISSUE THREAD

**Issue by anjaw3f** [polkadot-js/apps#3830]
Not sure where to report this, but I don't think the name DOT should be translated :) It should remain DOT in all languages.

**Comment by jacogr** [comment]
Agreed, sadly have no contact with the translators and don't speak Spanish, so the only thing I can do is mark it.

**Comment by jacogr** [comment]
@anjaw3f On which page is it translated?

**Comment by anjaw3f** [comment]
On the accounts page (I noticed it in this image a user sent me). But I actually can't reproduce it - when I change the language on polkadot.js to Spanish, DOT remains DOT. So maybe it's actually not an issue on our end, but some regional settings on their computer. 
![FOTO DE ERROR](https://user-images.githubusercontent.com/70277946/95587829-474d3800-0a4b-11eb-8849-385b2c8fad20.jpg)

**Comment by jacogr** [comment]
So judging by the above, that part is def NOT translated in apps. It gets displayed exactly as received via the RPC. So I think they may have a translate plugin running?

**Comment by jacogr** [comment]
Closing, local issue.
