### ISSUE TITLE
Address book, Event calendar in "apps-routing" don't show up in i18n translation

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#3833]
I had a look but couldn't make sense out of it.
Those files ([here](https://github.com/polkadot-js/apps/blob/master/packages/apps-routing/src/addresses.ts)) in `apps-routing` all look the same. The scanner seems to see the ns `apps-routing`, yet new strings aren't picked up when running `yarn build:i18n`.

**Comment by Tbaut** [comment]
That's solved :rocket:

**Comment by jacogr** [comment]
Re-opening, since it has to be manually added... something is _very_ weird and can't figure it out.

**Comment by Tbaut** [comment]
Ah damn, I've also spent a lot of time digging this before opening the issue :(
