### ISSUE TITLE
seed recovery

### ISSUE THREAD

**Issue by chicco13** [polkadot-js/apps#3878]
when i type in my seed this comes up **Unable to match provided value to a secret URI**

**Comment by Tbaut** [comment]
Can you walk me through what you did to have this error?
where did you type your mnemonic ?

Can you make sure you type it in the mnemonic seed field and that it only contains english words:

![image](https://user-images.githubusercontent.com/33178835/96111956-30db2c80-0ee2-11eb-9bef-8a625c913a0c.png)

**Comment by chicco13** [comment]
Hi this is what comes up it the extension on chrome

**Comment by chicco13** [comment]
15QWJ8Bx2vQViXgBaM4njWkPxcGtHYeiyBHmodcneJkDvZo4 that's my wallet I can't get access to it

Jamil Khadem
khademjamil@gmail.com

**Comment by jacogr** [comment]
You get the above error message while a full 12 words is not entered yet. (Once valid it will disappear)

**Comment by chicco13** [comment]
Jaco 
It’s the  right seed and I’ve got 300 dot on the wallet. I’m not an advanced computer person and my enzyme  wallet won’t come on line. I’m going crazy

**Comment by jacogr** [comment]
Ok, just paste the full 12 mnemonic words, as you got it on creation. That error comes up when it detects less than 12 words (or if it is more and not 15, 21 or 24)

**Comment by jacogr** [comment]
Closing.
