### ISSUE TITLE
Ledger account set on-chain identity error

### ISSUE THREAD

**Issue by Xa52c** [polkadot-js/apps#3883]
identity.setIdentity
Value cannot be printed

**Comment by jacogr** [comment]
Is it displayed on the device? In that can can I suggest you log it with the ledger app itself - not all functions are supported, so not sure about this specific call. 

If it cannot parse vertaub values it may need an adjustment.

**Comment by Xa52c** [comment]
it's not displayed on device. not sure what you mean about logging it with the ledger app?

**Comment by jacogr** [comment]
The Ledger apps are maintained here - 

- Polkadot - https://github.com/Zondax/ledger-polkadot
- Kusama - https://github.com/Zondax/ledger-kusama

**Comment by jacogr** [comment]
Closing.
