### ISSUE TITLE
Ledger account - Clear expired democracy locks error

### ISSUE THREAD

**Issue by Xa52c** [polkadot-js/apps#3884]
utility.batch
Not supported

**Comment by jacogr** [comment]
That is an issue that is logged on the ledger-app itself. Until it gets batch support some of the UI functionality on that device cannot be used. (Payouts are another example)

**Comment by jacogr** [comment]
Support for utility.batch is tracked on the ledger-app here - https://github.com/Zondax/ledger-polkadot/issues/16

**Comment by jacogr** [comment]
Closing, the functionality will be available when the Ledger app has support.
