### ISSUE TITLE
Program the UI for string that is Vec<u8> when calling <proposeBounty> to be a text string

### ISSUE THREAD

**Issue by rrtti** [polkadot-js/apps#3886]
When proposing a bounty and signing `proposeBounty (value, description)` the Description string is `Vec <u8>`

<img width="1574" alt="Screenshot 2020-10-16 at 14 24 04" src="https://user-images.githubusercontent.com/22815262/96258575-808e2680-0fbc-11eb-80cd-259288413a9f.png">

There should be another toggle so that `vec<u8>` could be file upload, bytes, or text string.

**Comment by jacogr** [comment]
Yes, it is unclear -

![image](https://user-images.githubusercontent.com/1424473/96258918-0f02a800-0fbd-11eb-9759-85811d8fff57.png)

That is how `Vec<u8>` works. We don't have a text-entry for them anywhere. So the easiest is to use a text -> hex converter.

**Comment by jacogr** [comment]
Will keep it open, smells like an enhancement for all `Bytes` inputs.
