### ISSUE TITLE
Call submitExtrinsic via curl ?

### ISSUE THREAD

**Issue by yancaitech** [polkadot-js/apps#3907]
On this page
https://polkadot.js.org/apps/#/rpc

Due to the development language I use, I want to call "submitExtrinsic" directly through `curl`, how to do it

**Comment by jacogr** [comment]
Plese direct these issues to the appropriate forumes. This reall doesn't have anything to do with the apps UI or the API. So Riot, Stakoevrflow or the substrate support repos would be a better place.

With that said, just use the RPC - https://polkadot.js.org/docs/substrate/rpc#submitextrinsicextrinsic-extrinsic-hash
