### ISSUE TITLE
erc721 error

### ISSUE THREAD

**Issue by puffanddmx** [polkadot-js/apps#3921]
ALICE made a new () Creates a new ERC721 token contract. (erc721.wasm, metadata)
And ALICE once again made a new ERC721 token contract with a different name, but the following error appeared.
Usually, one person should be able to create erc721 multiple times, but it seems that it can only be created once.
For example, it seems that one account should be able to create multiple times like this: cat1, cat2....
Probably, when an account makes a new contract multiple times in the current structure, it seems that the contract address remains the same. 

you can test it for uploading erc721.wasm, metadata -> then deploy new constructor multiple times with one account.

https://github.com/paritytech/substrate/blob/e81a3160d963456c88ce05b9391103ed405e0851/frame/contracts/src/storage.rs#L169
---------------------ERROR1(second deploy)
Oct 22 22:43:15.042 DEBUG apply_extrinsic: DispatchError    {ext}
Oct 22 22:43:15.042 DEBUG apply_extrinsic: Alive contract or tombstone already exists    {ext}
Oct 22 22:43:15.042 DEBUG apply_extrinsic: PostInfo:     {ext}
Oct 22 22:43:15.042 DEBUG apply_extrinsic: actual_weight=    {ext}
Oct 22 22:43:15.042 DEBUG apply_extrinsic: 87500000    {ext}
Oct 22 22:43:15.042 DEBUG apply_extrinsic: pays_fee=    {ext}
Oct 22 22:43:15.042 DEBUG apply_extrinsic: Yes    {ext}

**Comment by jacogr** [comment]
This is a contracts module issue. You got the nail on the head - an instance with the same params will yield the same address when the node deploy it. Hence the failure you described. 

The only way to do it is to specify different params upon creation.

**Comment by puffanddmx** [comment]
thanks!
