### ISSUE TITLE
Polkadot-JS web page just showing white screen

### ISSUE THREAD

**Issue by laboon** [polkadot-js/apps#3925]
This occurs on https://github.com/polkadot-js/apps in both Chrome and Brave

https://ipfs.io/ipns/dotapps.io/#/explorer seems to be working, or at least displaying the screen - haven't looked very deeply into it.

**Comment by jacogr** [comment]
IPNS is independent. 

Sadly CI broke on the last deploy, it is building a new version which should fixe the issue.
