### ISSUE TITLE
Allow council voters using proxies to change the vote value without going back to the total value

### ISSUE THREAD

**Issue by rrtti** [polkadot-js/apps#3937]
When a user tries to vote for Council from a proxied account and changes the vote value to a different amount than the total, seconds after the value goes back to the total amount in the account, not the value written by the voter. This repeats over and over again. 

Note this does not happen with account not using proxies.

**Comment by jacogr** [comment]
Ahhh... good catch on the proxy thing. It anyway needs some thinking because of the asyn nature.
