### ISSUE TITLE
Not able to see Contract option inside the Developer Dropdown menu

### ISSUE THREAD

**Issue by JeremyConnor** [polkadot-js/apps#3948]
![Screenshot from 2020-10-30 07-44-22](https://user-images.githubusercontent.com/73089748/97652441-5c364d80-1a84-11eb-93d2-5365f17548f2.png)

I have started a local development node using the substrate-node-template, and when I visit the https://polkadot.js.org/apps, after connecting with the localhost, I am still not able to see the Contract Option.

**Comment by Swader** [comment]
The node template does not come with the Contracts pallet built in. To add it, follow instructions [here](https://substrate.dev/docs/en/tutorials/add-contracts-pallet/).

**Comment by JeremyConnor** [comment]
Ohkay! I kind of had a slight hint that I need it. I was following a blog where it totally missed this part or maybe skipped it, which created this doubt. Thanks for clarifying!
