### ISSUE TITLE
Allow selection of reward destination account when creating a stash

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#3954]
When using the UI to bond a new account and selecting a custom reward destination, there should not be a default account that cannot be changed.

Steps:
First, select the button to add a new stash account.
![image](https://user-images.githubusercontent.com/25483142/97784538-9b0cf600-1b9f-11eb-8901-ad48a3298d65.png)

Second, select "Specified payment account" for the destination. At this point, I would expect another drop down selection to choose the account.
![image](https://user-images.githubusercontent.com/25483142/97784566-c42d8680-1b9f-11eb-8894-8f06da01b044.png)

Third, when previewing the transaction, there seems to be some default destination.
![image](https://user-images.githubusercontent.com/25483142/97784580-db6c7400-1b9f-11eb-8d69-8e6fc341fbf7.png)

**Comment by jacogr** [comment]
Ok, have no idea what you mean here?

**Comment by joepetrowski** [comment]
I suppose both.
- Bug: I doubt that this `111...` account is accessible, so sending rewards there by default is essentially burning them.
- Enhancement: Allow users to set their destination via the `+Stash` path.
