### ISSUE TITLE
Treasury doesn't work on Edgeware Mainnet

### ISSUE THREAD

**Issue by yangwao** [polkadot-js/apps#3972]
Any hints on what went wrong? Types are outdated?

![image](https://user-images.githubusercontent.com/5887929/98228882-7b881b80-1f59-11eb-862f-7753f816c8ef.png)

```
RPC-CORE: Unable to decode storage council.proposalOf: entry 1/2: createType(Proposal):: Call: failed decoding finalityTracker.finalHint:: Struct: failed on args: {"hint":"Compact<BlockNumber>"}:: u32: Input too large. Found input with 83 bits, expected 32

polkadot.02.4ad7ee5a.js:1 2020-11-05 11:21:26             DRR: Error: createType(Proposal):: Call: failed decoding finalityTracker.finalHint:: Struct: failed on args: {"hint":"Compact<BlockNumber>"}:: u32: Input too large. Found input with 83 bits, expected 32
```

**Comment by jacogr** [comment]
No, the upgrade moved indices around with the last runtime upgrade.

 So had to put in a hack for council to ignore those entries. Sadly the on-chain data needs to be removed, the best I can do is to patch around this. Hopefully it doesn't happen again, now that indices can be fixed.

**Comment by jacogr** [comment]
Have a HACK that works around the corrupt on-chain entries. Will pull that in and revert my previous hack on the UI-layers that only addressed this issue for council.
