### ISSUE TITLE
Tip closing on Polkadot reveals error after redirect

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#3974]
Repro:

- go to Treasury -> Tips
- close a closeable tip
- redirection reveals following message

![image](https://user-images.githubusercontent.com/1430603/98229717-8db68980-1f5a-11eb-93f0-ef0abd203560.png)

Re-visiting the tips UI by navigating elsewhere and back works, but refreshing the current page does not (error persists).

Edit: verified to be happening on Master as well, not just the released version.

**Comment by jacogr** [comment]
Ummm.... could be caused by https://github.com/polkadot-js/apps/pull/3945

**Comment by jacogr** [comment]
Sheiße despite 2 reports, don't have a trace of this one, so a bit of a nightmare to try and figure out where it sits.
