### ISSUE TITLE
Relocate shared apps packages into @polkadot/ui

### ISSUE THREAD

**Issue by kwingram25** [polkadot-js/apps#3980]
While working on [Canvas UI](https://github.com/paritytech/canvas-ui) I have forked and modified several packages from apps that should be moved into another npm package to be reused in other Substrate/Polkadot React UIs. Having a shared code base for this and other future projects built in React/Semantic UI would make development much easier and reduce the need to duplicate and tweak the original packages. In fact, this is said to be the eventual goal on most of these packages' readme pages.

Packages that could be relocated with little effort:
- [react-api](https://github.com/polkadot-js/apps/tree/master/packages/react-api)
- [react-hooks](https://github.com/polkadot-js/apps/tree/master/packages/react-hooks)

The rest would probably need a styling overhaul to allow customization for different projects - open to discussion on best way(s) to do this
- [react-components](https://github.com/polkadot-js/apps/tree/master/packages/react-components)
- [react-params](https://github.com/polkadot-js/apps/tree/master/packages/react-params)
- [react-query](https://github.com/polkadot-js/apps/tree/master/packages/react-query)
- [react-signer](https://github.com/polkadot-js/apps/tree/master/packages/react-signer)

Also another possible addition could be [react-util](https://github.com/paritytech/canvas-ui/tree/master/packages/react-util), to conntain functions from react-components/util and other frequently used helper functions.

**Comment by jacogr** [comment]
So having looked at this before, it won’t happen until SUI is replaced. (Which is going at a snail‘s pace)

So all of this is some way off and need a lot of rip out elbow grease before. It won’t be done until it is really shareable, which it is not since the actual framework will be dropped.

**Comment by jacogr** [comment]
Closing this as a won't-fix for the reasons above. There are actually some other points at play here as well - like we've done recently wit polyfill moving to common (and wasm is being evaluated to be incorporated there as well), ui itself may actually move to the apps UI. (However the items published there will continue to be published). It is a lot to manage, repo location !== published or not.

As for the above, there are too many inter-dependencies and some listed don't make sense at all, e.g. signer. 

As an aside, for the first time I've looked at the canvas code and truth be told, I'm not exceptionally happy. While still kept under Apache 2, you are seriously breaking section 4c of the license, which states -

"You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and"

Please keep the original copyright in-tact. Adding your own it 100% fine and expected, but throwing away years of work and claiming all as your own own elsewhere is not really in the spirit of OSS, nor why these repos are under apache 2.
