### ISSUE TITLE
Complete moonbeam types to support transactions and extrinsics

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#3986]
in `packages/apps-config/src/api/spec/moonbeam.ts` , add all types to completely support transactions and extrinsics in the interface

This types are in the frontier repo.

@jacogr I will tackle this issue in https://github.com/polkadot-js/apps/pull/3961

it would be great also if we could enable calling the eth specific methods defined in the PR

**Comment by jacogr** [comment]
The RPC methods are some way off - we don't have an infrastructure in api-config atm to actually define them. Happy to accept changes for that, but it should not be for just a specific chain, i.e. the format should be usable by others. (A good example is e.g. Acala, which has the definitions ready-to-go, but no place to put it - there are a number of these chains)

**Comment by jacogr** [comment]
Closing, done.
