### ISSUE TITLE
Ledger support staking with only one account. 2nd one seems to fail

### ISSUE THREAD

**Issue by derfredy** [polkadot-js/apps#3993]
Various users at the Spanish telegram channel seems to have the same issue when staking with their ledgers.

The 1st account goes well, the 2nd fails.

This is the error message from polkadot.js.org/app

![image](https://user-images.githubusercontent.com/23276270/98471737-a6d76880-21ee-11eb-9563-9bff6ba9d0e3.png)

**Comment by jacogr** [comment]
That message comes for the Ledger itself. Explicitly this - https://github.com/Zondax/ledger-polkadot/issues/22

Until Ledger is updated, don't use any destination payouts.
