### ISSUE TITLE
Add rpc methods definitions to apps

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#4000]
In the same spirit as https://github.com/polkadot-js/apps/issues/3986

@jacogr where should I store the rpc method declaration so that other projects can add their own. Probably in app-config in the same fashion as types. Should I create a new folder named 'rpc' in the same folder as bundle, spec and chain?

**Comment by jacogr** [comment]
Yes, that would make sense.

**Comment by joelamouche** [comment]
@jacogr it looks like the rpc field in the ApiPromise constructor takes rpc definitions directly and not an object with definitions for every network. This is a problem because at api instantiation I can't access specName. So that means that we either define all methods for all networks or none. What do you think?

**Comment by jacogr** [comment]
Cannot do on on an all basis :(

So for your specific usecase, which is effectively frontier and quite far spread, happy to inject it for all (by default) until the above is resolved. But it needs a solution on the API-layer, like we have typesBundle and friends.

So would suggest -

- dump it in api-config
- attach it for all instances

(... all for now until it is solved)

**Comment by modbrin** [comment]
I'm following discussed approach with custom rpc, using defs via open-web3/orml-type-definitions/utils/jsonrpcFromDefs. There is an error displaying method part.
![image](https://user-images.githubusercontent.com/9750068/99642147-3802d680-2a5c-11eb-8a60-be8b9b674acd.png)
I observe same behaviour for Moonbeam page however, is that a known problem and is it an issue of rpc definition format?

**Comment by jacogr** [comment]
@modbrin I would suggest logging that as a separate issue along with a specific reproduction. This is not a bug-report issue and makes it more difficult to actually get enhancements done and fix bugs in other areas.

But yes, something is weird, but not for this specific enhancement overview.

**Comment by joelamouche** [comment]
Done in #3961
