### ISSUE TITLE
[tokenDecimals]  The parameter of our chain startup is "tokenDecimals":12", but what is displayed on the apps is wrong, how to fix it

### ISSUE THREAD

**Issue by yuhui1208** [polkadot-js/apps#4004]

**Comment by yuhui1208** [comment]
Our total circulation is 20 million, but it shows 200P on apps

**Comment by jacogr** [comment]
Where is the chain spec properties defined? The UI (and the API and ecosystem) reads the `system_properties` RPC and that value is used for display.

So unless defined in the chain spec, the API and UI will apply a default, since it is unknown.
