### ISSUE TITLE
Fix Verify flow for ethereum signatures

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#4005]
*This problem is related to moonbeam compatibility on polkadot-js*

- [x] The verify function doesn't work because the crypto-util package needed an update on the `signatureVerify` function that would only accept a 36bytes address instead of ethereum compatible 20bytes address
- [ ] The signature function comes from the keyring, which is only compatible with ss58 
 address according to this https://www.npmjs.com/package/@polkadot/ui-keyring . Moreover, the keyring doesn't expose the private key, so we can't use the `secp256k1Sign` function used in the util-crypto tests

**Comment by joelamouche** [comment]
@jacogr see my comment on signature: I think it needs an update on the keyring package, which is private

**Comment by jacogr** [comment]
I don't understand, it basically would men that the exposed sign is incorrect for Ethereum - https://github.com/polkadot-js/common/blob/master/packages/keyring/src/pair/index.ts#L163

**Comment by joelamouche** [comment]
Ok thanks for pointing to me the right part of the code to look at. It looks like the pair type (ethereum) needs to be passed at some point and Im trying to figure out if its during creation or when signing

**Comment by jacogr** [comment]
The pair does know it is an Ethereum type there. (Once loaded on the keyring it will be indicated as ETH)

The issue with those if that I worked a bit in the dark, so very possible both the generation and verifying in that object is wrong.

**Comment by joelamouche** [comment]
This was resolved by #4006 and https://github.com/polkadot-js/common/pull/767
