### ISSUE TITLE
Wrong fee values for sudo_unchecked_weight and set_code

### ISSUE THREAD

**Issue by NachoPal** [polkadot-js/apps#4013]
Hi, from this documentation: https://substrate.dev/docs/en/tutorials/upgrade-a-chain/sudo-upgrade and taking a look also at the comments in the source code, I think that the fees displayed in the UI for `sudo_unchecked_weight` and `set_code` might be wrong.

- For `set_code` is stated that :
> is intentionally designed to consume the maximum weight that may fit in a block

and in the source code, we can see that that's correct.
```
#[weight = (T::MaximumBlockWeight::get(), DispatchClass::Operational)]
pub fn set_code(origin, code: Vec<u8>) {...}
```
also states that:
>set_code is in the Operational class of dispatchable functions, which identifies it as relating to network operations and impacts the accounting of its resources, such as by exempting it from the TransactionByteFee

However, the fees are not `MaximumBlockWeight`. The UI seems to add the size of the file `TransactionByteFee` to `ExtrinsicBaseWeight`

- For `sudo_unchecked_weight` is stated that
> which provides the same capability as the sudo function, but accepts an additional parameter that is used to specify the (possibly zero) weight to use for the call

However, it seems that modifying the value of `_weight` param doesn't affect at all the total fees displayed in the UI before sending the transaction.

**Comment by jacogr** [comment]
The UI doesn't do any additions nor re-implement any logic in terms of fees. The only payment information it displays is from the `payment_queryInfo` RPC, aka https://polkadot.js.org/docs/substrate/rpc#queryinfoextrinsic-bytes-at-blockhash-runtimedispatchinfo

**Comment by NachoPal** [comment]
So `payment_queryInfo` returns a wrong value you mean? Or my assumptions about what should be the fees are wrong?

**Comment by jacogr** [comment]
Yes, the info displayed on the signing screen is directly from the RPC, not calculated in the UI.

(There is a single place where the fee-per-byte is used in the UI and that is on democracy preimage proposals since a per-byte fee is applied for storage in that case, so it gives a pre-warning based on the size of your preimage)
