### ISSUE TITLE
system.ExtrinsicFailed error while deploying the Contract

### ISSUE THREAD

**Issue by JeremyConnor** [polkadot-js/apps#4018]
Earlier I was able to deploy the smart contract, but now after uploading the Smart Contract, when I go on to deploy it, I get an error stating system.ExtrinsicFailed and contract.TransferFailed. Neither do I know the reason of this error and nor do I know how to solve it.
![Screenshot from 2020-11-12 21-10-45](https://user-images.githubusercontent.com/73089748/98962695-e672bd00-252c-11eb-9cf9-cd6b90493da1.png)

![Screenshot from 2020-11-12 21-10-54](https://user-images.githubusercontent.com/73089748/98962706-e7a3ea00-252c-11eb-824d-b9fd6434114b.png)
![Screenshot from 2020-11-12 21-27-13](https://user-images.githubusercontent.com/73089748/98963806-1078af00-252e-11eb-80be-cc8ca8993d15.png)

**Comment by jacogr** [comment]
That comes from the Node itself. I'm nowhere near a contract internals experts to understand why.

**Comment by jacogr** [comment]
Closing. Working as expected (Substrate).

**Comment by JeremyConnor** [comment]
@jacogr I was able to deploy the contract after decreasing the value of endowments. Earlier I was using 1000 and was able to deploy the smart contract. But, after I made few changes to the contract it was deployable only if I set endowments to 100. Can you please explain how does changing endowments affect the deployment of Smart Contract?

**Comment by jacogr** [comment]
No idea. This question is really better for the contracts team.
