### ISSUE TITLE
Publish @polkadot/apps-config or similar

### ISSUE THREAD

**Issue by emostov** [polkadot-js/apps#4021]
I am looking into ways to manage types for `substrate-api-sidecar` as we look to expand to supporting more chains. Naively, looking at `@polkadot/apps-config`, it looks like if that was published to NPM I could just grab the types from there and use them by simply requiring the package.

In order to reduce redundant code maintenance in the ecosystem, I was wondering if you would be open to either publishing `@polkadot/apps-config` as is or creating another package as a centralized place to keep track of chain types?

**Comment by dvdplm** [comment]
@jacogr any thoughts on the above?

**Comment by jacogr** [comment]
It cannot be published as-is, it is very apps-specific, or used to be think at least some of the internal deps have been broken since. Yes, have had thoughts about something like `@polkadot/types-known`.

**Comment by jacogr** [comment]
Closing - https://www.npmjs.com/package/@polkadot/apps-config (just the `.skip-npm` toggle removed. YMMV.)
