### ISSUE TITLE
Make address addition more ethereum compatible

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#4025]
When importing an address from MetaMask using a privatekey, we noticed some things that could be improved:
- Add ‘private key’ instead of 'rawSeed' for ethereum addresses (that wasnt clear to me)
- Make it clear that it needs to start with 0x
- Make sure checkbox is there even when the window is too small (was a problem for oen of our testers)
- when copying address to clipboard, the message shouldnt say "memnonic"

**Comment by joelamouche** [comment]
what do y ou think @jacogr ? Should I go ahead and implement this?

**Comment by jacogr** [comment]
Yes, it makes sense.

**Comment by joelamouche** [comment]
Do you know how to make sure the tick box doesnt disappear?

**Comment by jacogr** [comment]
I honestly don’t understand that one.

**Comment by joelamouche** [comment]
yes me neither. what are you using for responsiveness? I guess this is not urgent

**Comment by jacogr** [comment]
The breakpoints are really simple -

- on tables, there is a media class that hides columns
- on modals the only area that should get hidden is the columns/descriptions on the right

Have really not paid much attention to making sure it works across all, the above simple approach makes it passable. One day, when bored...

**Comment by jacogr** [comment]
Ok, replicated... it sits in the second column on the modal, hence being hidden. Will make a fix for that one.

**Comment by jacogr** [comment]
Closed in #4032
