### ISSUE TITLE
Add warning text when bonding below minimum amount on Polkadot

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#4026]
A lot of users bond DOT below the minimum threshold (currently around 100 DOT), see that they don't earn rewards, and then have to wait 28 days to unbond. The options box when adding a stash should give a warning that bonding below the threshold (maybe with a factor of safety since it's variable) will not result in staking rewards but still lock DOT for 28 days.

**Comment by jacogr** [comment]
Where do we get the 100 DOT? AFAIK it is not on-chain. 

If it is not in the state, it doesn’t have an impact on the UI.

**Comment by joepetrowski** [comment]
I will dig into it more, but off the top of my head you should be able to look at the current solution and see the lowest applied stake?

**Comment by jacogr** [comment]
If on-chain, non-Event, reachable, let me know. Happy to enhance.

**Comment by joepetrowski** [comment]
From a user (haven't been able to test myself):
```
const validators = await api.query.session.validators();
let nominatorStakes = [];
for (validator of validators){
    const derive = await api.derive.staking.query(validator);
    for (const nominatorStake of derive.exposure.others){
        nominatorStakes.push(nominatorStake.value / Math.pow(10,10));
    }
}
nominatorStakes.sort(function(a, b){return a-b});
console.log(nominatorStakes);
```

**Comment by jacogr** [comment]
Not even sure this makes any sense whatsoever, e.g. see Realgar on Polkadot -

![image](https://user-images.githubusercontent.com/1424473/99392193-9eacb680-28db-11eb-8f2a-1b556d0e6a94.png)

1 DOT min.

**Comment by jacogr** [comment]
Closing this since the current election does things in a different way (yet again). Lots of small 1.x DOT amounts bonded.
