### ISSUE TITLE
Cant send my dot coins

### ISSUE THREAD

**Issue by chicco13** [polkadot-js/apps#4027]
Hi 
every time i try to  send this comes  up **balances.transferKeepAlive** could you please tell what it is and how to fix it

please help

**Comment by krzysztof-jelski** [comment]
@chicco13 were you intending to attach some screenshot, perhaps?

**Comment by chicco13** [comment]
Ok will do now

**Comment by jacogr** [comment]
Closing, no additional information provided.

**Comment by chicco13** [comment]
You have not commented on the video I sent I still can not transfer my DOTs

**Comment by chicco13** [comment]
![polka copy](https://user-images.githubusercontent.com/33196679/100128728-5c333d00-2ecc-11eb-9c97-c5347b9e24f7.jpg)

**Comment by jacogr** [comment]
I'm sorry, but scroll up there has been no video and the last comment 8 days ago. Now, after closing, there is a vide uploaded.

**Comment by chicco13** [comment]
Sorry but if you look at the pic I did send a video on the 16th. October

**Comment by jacogr** [comment]
![image](https://user-images.githubusercontent.com/1424473/100130712-59602a00-2e83-11eb-9ef6-116aa3aab878.png)

I'm trying to help you here, there is nothing. Not on this browser, not on FF, not on Safari and not in incognito.

**Comment by chicco13** [comment]
Sorry for ant inconvenience im trying to transfer  138 dot from 16FkyGZMbmooV4BF5FFbLsC3rJMWWNBuFjQ62WBzLc6i4Nvj 
to15QWJ8Bx2vQViXgBaM4njWkPxcGtHYeiyBHmodcneJkDvZo4 and it keeps saying BALANCE.TRANSFER
