### ISSUE TITLE
UI Preventing Extrinsic Submission for `session.setKeys`

### ISSUE THREAD

**Issue by jack-kearney** [polkadot-js/apps#4035]
The UI is preventing submission of `session.setKeys` calls in the [custom extrinsic flow](https://polkadot.js.org/apps/#/extrinsics). I've included a picture of the error below:

<img width="1406" alt="Screen Shot 2020-11-16 at 6 56 44 PM" src="https://user-images.githubusercontent.com/1410750/99322440-f1d02c00-283d-11eb-8819-7603e09c8626.png">

Previously, the "Proof" field could be left blank. Now, if its left blank the button labeled "Submit Extrinsic" is greyed out and there doesn't appear to be a way to submit this.

Would love to know if there's a work-around here. Thanks!

**Comment by jacogr** [comment]
Just enter 0x00 (it gets ignored on the node side).

**Comment by jack-kearney** [comment]
Ah, excellent! I'll give that a go

**Comment by jacogr** [comment]
Closing.
