### ISSUE TITLE
why always stay on "Waiting for authorization from the extension. Please open the installed extension and approve or reject access."

### ISSUE THREAD

**Issue by carltraveler** [polkadot-js/apps#4042]
when I connect to local host by <https://polkadot.js.org/apps/#/settings?rpc=ws://127.0.0.1:994> . and the local nod print out "Accepted a new tcp connection from 127.0.0.1:58628".  but the brower always stay on message  `Waiting for authorization from ...` ". is that a bug? I tried kinds browser

**Comment by jacogr** [comment]
See #4041 - the message is actually misleading and the linked issue aims to address that, since the wait time is for the API (it is done in parallel hence the misleading message)

**Comment by carltraveler** [comment]
so is there any other way I can  connect to my local node? or just wait for patch?

**Comment by jacogr** [comment]
There is no bug, patch, only a misleading message.

As you running a docker image?

**Comment by carltraveler** [comment]
you mean the local 9944 port? but the local node print out "Accepted a new tcp connection from 127.0.0.1:58628" .

**Comment by carltraveler** [comment]
no. I compiled polkadot myself

**Comment by jacogr** [comment]
Check the console if there are any errors, Polkadot is fine since it won't have any type-specific errors. But effectively, when it spins, it means it has issues establishing connection between browser and node.

**Comment by jacogr** [comment]
Closing. (Additionally the UI now accurately actually displays the connection after #4041 )
