### ISSUE TITLE
Special rendering rules for overridden types

### ISSUE THREAD

**Issue by modbrin** [polkadot-js/apps#4046]
Sometimes fields in UI are not displayed correctly, displaying e.g. number field with N-digit limit, therefore values can not be entered  correctly. I suppose this happens for types which override existing built-ins.
Example definitions:
1)
```
AssetId: {
  inner: "[u8; 32]",
  precision: "u8"
}
AssetIdOf: "AssetId"
```
![image](https://user-images.githubusercontent.com/9750068/99549215-7780e280-29ca-11eb-81f7-3a0d8638a6fc.png)
2)
```
AssetId: "[u8; 32]",
AssetIdOf: "AssetId"
```
![image](https://user-images.githubusercontent.com/9750068/99549498-c169c880-29ca-11eb-960b-a6e03e8c78c8.png)

Also in given examples CurrencyId=AssetId will render correctly, AssetId=AnotherTypeForAssetId will render incorrectly

**Comment by jacogr** [comment]
Yes, these are generally tricky, since without seeing the effects first-hand in a debugger (generally with some logs sprinkled in, it is exceptionally difficult to even guess why the detection doesn't quite work as expected). 

The most progress has actually been made with a bunch of testcases against running public RPC nodes. So valid request, however no idea how to even attempt to understand which part of the type detection needs some TLC.

**Comment by jacogr** [comment]
When it cannot figure out the type, it always falls back to pre-encoded hex entry. (That is why the hex in the second case)

**Comment by modbrin** [comment]
@jacogr Expecting pre-encoded hex entry for [u8; 32] is an appropriate behavior. But expecting e.g. 9-digit number, while "inherited" types such as AssetIdOf, CurrencyId, CurrencyIdOf display normally leads to think there is an additional override specifically for "AssetId". Also for the second example there is an error `Struct: failed on asset_a: [u8;32]:: t.subarray is not a function`.

Quick fix for me is to replace AssetId with e.g. CurrencyId in api. Please let me know if I can provide more info or point where I can start investigating to debug it. I would be less worried if it were not for a fundamental type.

**Comment by jacogr** [comment]
The only way to track is to actually check react-params against a node that exhibits the behavior. 

This will be something small to fix, but not easy to track. (It tries to inspect types via creation so it is really following the crumbs with a reproduction)

**Comment by jacogr** [comment]
The specific code that gets used to determine which to show (based on trying to inspect the type) is here - https://github.com/polkadot-js/apps/blob/master/packages/react-params/src/Param/findComponent.ts#L131

**Comment by modbrin** [comment]
@jacogr I investigated suggested code fragment and the problem is the following: Looking at two paths of component resolution
1. `AssetId->AssetId32->Struct{code: [u8; 32]}`
2. `CurrencyId->AssetId->AssetId32->Struct{code: [u8; 32]}`
only 2. works fine.

I can see there are two layers of resolution in `findComponent`, first layer tries to find known component by def and it succeeds if it's exactly "AssetId" as it's present in `componentDef`. After initial lookup, component is returned at this point.
```
const type = fromDef(def);
let Component = findOne(type);
```
CurrencyId is not known in first layer, therefore it proceeds to second layer. Second layer (inside `if (!Component)`) is recursive, but it starts with
```
const raw = getTypeDef(instance.toRawType());
```
which resolves Currencyid to Struct, handling AssetId and other nested types inside properly. Maybe it's as simple as an additional indication of override missing? On code level in polkadot-js type override is handled specifically and it works as expected, this is about component override.

Also we currently provide a running node ([pull/4059](https://github.com/polkadot-js/apps/pull/4059)). Problem can be observed via e.g. `Extrinsics->tradingPair->register` for AssetId. Normal behavior can be observed in `Chain State->tokens->accounts` for CurrencyId.

**Comment by jacogr** [comment]
Cool. Yes, the running node helps a lot As does your investigation here.

**Comment by jacogr** [comment]
Which extrinsics shows this problematic behavior? (Just to aid testing)

**Comment by modbrin** [comment]
Yes, problematic are those which use AssetId,
for extrinsics it's currently:
- mockLiquiditySource.setReserve
- assets.register
- dexManager.initializeDex
- dexapi.swap
- liquidityProxy.swapExactInput
- liquidityProxy.swapExactOutput
- tradingPair.register

for state queries this is:
- mockLiquiditySource.reserves

Let me know if you need testing data for successful usecases, although I believe that a successful submission regardless of it's effect is a passing usecase.

**Comment by jacogr** [comment]
It is fine, as long as it gets to the signer and is valid there, it will be valid. The above it more than enough to try and figure out how to deepen detection.

**Comment by modbrin** [comment]
Thanks a lot!
