### ISSUE TITLE
Extrinsic hash is printed out halfway

### ISSUE THREAD

**Issue by lana-shanghai** [polkadot-js/apps#4055]
Hi! I have successfully sent contract code to the canvas UI using the py-substrate-interface, and it returns an extrinsic hash - fantastic. But, there are 2 problems - 

One, the network search in the UI only allows to search for a block hash, do you think in the future to add functionality to search by extrinsic hash? It would make sense because you might not know the block number or block hash. 

Another, the contract putCode function results in a contract hash. If you upload the contract wasm manually, you can click "Copy" and it copies the hash, but if I am looking in the network explorer page, the hash is printed out 75%. Do you think you add the same "Copy" button there? I'm attaching a screenshot, see the contract.codeStored window: 

<img width="1370" alt="Screenshot 2020-11-20 at 16 55 49" src="https://user-images.githubusercontent.com/31368580/99821377-40d5d400-2b52-11eb-9322-67dd404eb50b.png">

**Comment by jacogr** [comment]
There is no RPC to retrieve by extrinsic hash. The Polkadot wiki does have a section as to why extrinsic hashes are not unique in the system. 

The copy is a good suggestion. Will mark it as an enhancement.

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/apps/pull/4065
