### ISSUE TITLE
Cannot transfer/send 

### ISSUE THREAD

**Issue by gestrada69** [polkadot-js/apps#4056]
Every time I try to send 3/ times so far it keeps telling me "insufficient" balance but it takes the tip.

I can't screenshot the messages because they go away every time I try to.

![Screen Shot 2020-11-21 at 4 02 47 PM](https://user-images.githubusercontent.com/74841658/99890387-85757400-2c13-11eb-83ad-1fa48e2cdd10.png)

**Comment by jacogr** [comment]
It is the check from the node on-chain that reports that.

Check your locked balances (expand the view), that cannot be transferred, only the transferrable portion.

**Comment by gestrada69** [comment]
No that wasn't it. I fixed it.

Thanks.

I also got ripped off by a phishing scam from someone saying they were from your support team. They emptied my ledger.

Totally my fault
-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


Nov 22, 2020, 00:39 by notifications@github.com:

**Comment by jacogr** [comment]
Resolved.
