### ISSUE TITLE
where are private keys of test accounts in local testnet?

### ISSUE THREAD

**Issue by jaslin-W** [polkadot-js/apps#4069]
like alice,bob. where are their private key? I want to use these accounts to transfer in code.
I can't see anything in /tmp/alice/chains/local_testnet/keystore. 
i start polkadot with this command
```
/usr/bin/polkadot --chain=polkadot-local \
    --alice -d /tmp/alice \
    --rpc-external \
    --ws-external \
    --node-key 0000000000000000000000000000000000000000000000000000000000000001
```

**Comment by jacogr** [comment]
They are well-known mnemonics in substrate. It is actually available on the apps UI when connecting to a dev node, just select the dev seed when connected to a local node. 

- if you are using the keyring, the hard derivation path without a mnemonic would auto-insert the dev mnemonic, i.e. `keyring.createFromUri('//Alice')` as per https://polkadot.js.org/docs/api/start/keyring#adding-accounts (known hard paths here, aligning with Substrate, https://github.com/polkadot-js/common/blob/master/packages/keyring/src/testing.ts)

- the mnemonic is specifically `bottom drive obey lake curtain smoke basket hold race lonely fit walk`

**Comment by jaslin-W** [comment]
@jacogr thank you very much!
