### ISSUE TITLE
Custom RPC definitions are not displayed

### ISSUE THREAD

**Issue by modbrin** [polkadot-js/apps#4079]
Following the approach to include custom rpc definitions in https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/rpc/index.ts currently there is a problem displaying them in UI.
![image](https://user-images.githubusercontent.com/9750068/100339795-5d0ec080-2feb-11eb-907e-7fbded3d779e.png)

In this example injected rpc's are generated via [open-web3/orml-type-definitions/utils/jsonrpcFromDefs](https://github.com/open-web3-stack/open-web3.js/blob/master/packages/orml-type-definitions/src/utils/jsonrpcFromDefs.ts)

Problem is reproducible e.g. in Test Networks -> SORA-Substrate -> Developer -> RPC Calls  -> (tradingPair | dexApi | dexManager)

Also there is an rpc field in TypesBundle which seems to be not utilized (new rpc's are not included in list when set), should it be considered as an alternative? https://github.com/polkadot-js/api/blob/b0e7440ca6f1939388f01ed48de93e0f0f36c555/packages/types/src/types/registry.ts#L105
```
export interface OverrideBundleDefinition {
    alias?: Record<string, OverrideModuleType>;
    rpc?: Record<string, Record<string, DefinitionRpc | DefinitionRpcSub>>;
    types?: OverrideVersionedType[];
}
```

**Comment by jacogr** [comment]
On the last question, yes, PRs welcome to extend in that direction. (It certainly would reduce duplication)

**Comment by jacogr** [comment]
The issue comes from here, it is only aware of the well-known RPC types - https://github.com/polkadot-js/apps/blob/master/packages/react-components/src/InputRpc/index.tsx#L60

**Comment by modbrin** [comment]
@jacogr Problem is not resolved fully, components are not switched when choosing list items. Should I create separate issue for this?

**Comment by jacogr** [comment]
This indeed is a regression and something completely seperate. (Regression since we used to have that quite a bit in the past)

**Comment by jacogr** [comment]
No need to log, will see wtf is up now and get in a fix.

**Comment by modbrin** [comment]
@jacogr Selection of rpc is fixed now, however there is yet another problem - selection inside rpc parameters. E.g. `RPC Calls -> offchain -> localStorageGet -> kind` and for custom `RPC Calls -> dexApi -> canExchange -> liquiditySourceType` selecting element resets to default after selection. Same component does work in extrinsics section.

**Comment by modbrin** [comment]
Great, thanks!
