### ISSUE TITLE
Broken Balances in the UI

### ISSUE THREAD

**Issue by gregzaitsev** [polkadot-js/apps#4120]
These steps only work intermittently, sorry. Sometimes US shows wrong balances and transfers wrong amounts.
 
Steps to reproduce (sometimes takes a few iterations before the issue appears): 

1. Open the UI and point it to Kusama network
2. Start a new substrate based dev node locally, e.g. build it from https://github.com/usetech-llc/nft_pallet_v1, then purge-chain and restart as `cargo run -- --dev`.
3. Point the UI to localhost:9944

When the issue is reproduced, this is how we see it:

1. Alice and other dev addresses balances are displayed as 75.5578 MUnit instead of 1.2676 PUnit
2. When I transfer 1 Unit to Ferdie, I only see 59.6046 nUnit arrived.

**Comment by gregzaitsev** [comment]
Last time reproduced today, with 

Apps UI: 0.69.1
API: 2.9.1

**Comment by jacogr** [comment]
That is a types mismatch issue on the specific chain. Ensure that you have the correct types for it attached.

**Comment by jacogr** [comment]
Follow up now that I have a gap, follow this -

https://polkadot.js.org/docs/api/FAQ#on-a-non-current-non-substrate-20-branch-my-balances-are-wrong

And do consider upgrading, 2.0-alpha.6 is ancient. :)

**Comment by jacogr** [comment]
Closing.
