### ISSUE TITLE
 apps can't submit transactions after produced six blocks when "instant-sealing" features enabled

### ISSUE THREAD

**Issue by BeDreamCoder** [polkadot-js/apps#4145]
I found the error when i use the recipes/kitchen-node to test "manual-instant-sealing" feature. **I guess the cause of the error is that "CheckEra aka CheckMortality" of the type "SignedExtra", and the value get from polkadot-apps.** When i annotate  "CheckEra", block produced normally.
 
The steps that error re-occurrence:
1. git clone https://github.com/substrate-developer-hub/recipes.git
2. modify "recipes/nodes/kitchen-node/Cargo.toml", using "weight-fee-runtime" package
![image](https://user-images.githubusercontent.com/27797366/100975600-416e6180-3579-11eb-9295-7634e037b8a5.png)
3.build  "recipes/nodes/kitchen-node"   cmd: WASM_BUILD_TOOLCHAIN=nightly-2020-10-06 cargo build --release -p kitchen-node
4. run kitchen-node,  cmd:   ./target/release/kitchen-node --dev --tmp
5. run substrate-front-end-template to send transfer tx, repos: https://github.com/substrate-developer-hub/substrate-front-end-template
6. error will  re-occurrence after six block, show **InvalidTransaction:badProof**
![image](https://user-images.githubusercontent.com/27797366/100975971-cb1e2f00-3579-11eb-929c-10c1ab9f4493.png)
![image](https://user-images.githubusercontent.com/27797366/100975977-d1141000-3579-11eb-9c9e-686f80583e20.png)

**Comment by atenjin** [comment]
We think this "Bad Signature" error is caused from "api" level, we could create an issue in api later, and provider the test script.

**Comment by jacogr** [comment]
2 questions -

1. What do you mean by annotate CheckEra?
2. The UI above is the front-end template, not apps - so would direct it there. (Have never worked with the UI code, so really don't know what it is doing - that is a separate team to the polkadot-js)

**Comment by jacogr** [comment]
Closing, not apps UI interface.
