### ISSUE TITLE
Uncaught error in Kusama Staking Targets Page

### ISSUE THREAD

**Issue by wpank** [polkadot-js/apps#4152]
![uncaughterror](https://user-images.githubusercontent.com/9498646/101065823-e860f680-3595-11eb-84f1-d3c5dd2cf2ed.png)

Going to the staking > targets page for kusama results in this:

**Comment by jacogr** [comment]
Wtf?

**Comment by jacogr** [comment]
Ok, cannot reproduce, however the above does give hints and I know where it sits. Which browser are you on?

**Comment by wpank** [comment]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/staking/targets

happens to me on chrome somewhat reliably refreshing the page. Chrome v 84.0.4147.89

**Comment by jacogr** [comment]
Ok, so <85.

CI is building, will have support in 12 mins.
