### ISSUE TITLE
Help Menu Text Can't be Read with Dark Theme

### ISSUE THREAD

**Issue by HCastano** [polkadot-js/apps#4153]
I was playing around with the experimental dark theme today (which is great btw) I and I tried clicking the "Help Menu" question mark in the UI. The help menu was then rendered like this:

![Screen Shot 2020-12-03 at 12 27 19 PM](https://user-images.githubusercontent.com/12344623/101065379-17aa4000-3563-11eb-98a9-022eca7142ab.png)

**Comment by jacogr** [comment]
Erk, ok, that needs a fix.

(dark-mode is not perfect, needs some TLC stil, hence the label)
