### ISSUE TITLE
WS connection failed!

### ISSUE THREAD

**Issue by jaslin-W** [polkadot-js/apps#4155]
I'm not sure the problem is about polkadot or polkadot-js
I have made an issue in polkadot.
https://github.com/paritytech/polkadot/issues/2063

I found you have saw some similar problems. Can you give a help? 
Thanks!
@jacogr

**Comment by jacogr** [comment]
It is a config issue on the node, not Polkadot, nor the libraries. 

- which node are you connection to
- how is is running? Local? Docker?

**Comment by jaslin-W** [comment]
```
2020-12-03 03:36:28  👶 Starting BABE Authorship worker    
2020-12-03 03:36:28  Unable to listen on 0.0.0.0:9944    
2020-12-03 03:36:28  Unable to bind RPC server to 0.0.0.0:9944. Trying random port.   
```
i found sometime 9944 bind error.  It is clear that it is not the problem of polk. 
sorry to bother you .
