### ISSUE TITLE
Update Moonbeam types for parachains-v1

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#4158]
Specifically will need to remove the RefCount type

v1 is not yet live but we want to have a branch to on /apps to test it

**Comment by jacogr** [comment]
That is where the typesBundle comes in handy - if you know what the specVersion can be, can already be pre-emptively merged.

**Comment by joelamouche** [comment]
Ha yes, makes sens!

**Comment by joelamouche** [comment]
related to https://github.com/polkadot-js/apps/pull/4011 a pending PR to move types to typeBundle
