### ISSUE TITLE
ws connection stopped all of a sudden

### ISSUE THREAD

**Issue by JeremyConnor** [polkadot-js/apps#4161]
It was working perfectly fine, but all of a sudden since yesterday I am not able to connect to Polkadot UI. I have my substrate node running.
On running ```./substrate-node-template/target/release/node-template --dev --tmp``` It says ```Listening for new connections on 127.0.0.1:9944``` but still the UI cannot connect to local node
![Screenshot from 2020-12-05 18-05-07](https://user-images.githubusercontent.com/73089748/101243213-a4e8c280-3724-11eb-9b39-b3a1744a704e.png)

**Comment by jacogr** [comment]
This is a local issue - the browser cannot connect. Make sure you don't have zombie processes running - it has happened in the past where the node has not shutdown successfully. There is nothing code-wise here, it basically sits between the browser and the node. So the only checks are -

- ensure only 1 process is running
- if all else fails, see if a browser restarts helps

**Comment by JeremyConnor** [comment]
Wouldn't the zombie process be killed upon restarting my device? Because, I tried doing so, but it didn't help

**Comment by jacogr** [comment]
The WS code has not changed since, well, it was written 2 years ago :) It really is a local issue and as to why, have no idea. It seem the browser can reach the port, then gets an "Abnormal Closure", i.e. the connection gets dropped.

**Comment by JeremyConnor** [comment]
Okay, I got it. Thanks for the help!

**Comment by jacogr** [comment]
Sadly in thi case it is not much I'm afraid :(
