### ISSUE TITLE
"Attach Ledger Devices" menu option absent for Polkadot

### ISSUE THREAD

**Issue by toholdaquill** [polkadot-js/apps#4175]
Documentation indicates that there should be a settings option to "attach ledger device" in polkadot.js.org/apps, but this menu option does not appear, making it impossible to use Polkadot with a Ledger Nano S.

![polka](https://user-images.githubusercontent.com/7691259/101513966-c5926180-394a-11eb-8757-04d204ad1021.png)

**Comment by jacogr** [comment]
It is there - 

![image](https://user-images.githubusercontent.com/1424473/101515106-49197600-397e-11eb-9ece-2f4ac8bf46ed.png)

There seems to be a refresh issue if you are on the settings page. So clicking Metadata and then General again does a refresh.

**Comment by toholdaquill** [comment]
When I reopen Chromium, it works this time. Very strange! And confusing for folks who are new to Polkadot. Can you force display a stub menu option that's grayed out, instead of not appearing at all? Any idea what's causing this buggy behavior?

**Comment by jacogr** [comment]
Like I said, refresh when it detects the chain, injects the API (it is not available on all chains, but unlike other pages it is visible even without API). 

That is a guess and won’t  be looking at this anytime soon since there is a workaround as describe above, because of that it is a very low priority. 

As always, PRs welcome. (Page-settings, General)

**Comment by toholdaquill** [comment]
If you make it hard for people to use hardware wallets with Polkadot, then they will use Polkadot /without/ hardware wallets.

The more people who do not use hardware wallets, the less secure the entire Polkadot ecosystem will be.

A buggy frontend that creates friction for secure usage makes this bug report a security issue.

Recommend tagging this bug as security.

**Comment by jacogr** [comment]
Sorry, but this is not security. Please don't mess around and waste time, there is limited - the amount of time I've already had to spend on answering this specific one (after giving a workaround), could have been used to fix it.

**Comment by jacogr** [comment]
Fix with api state checking -

```js
...
const { isApiReady } = useApi();
const showLedger = useMemo(
  // settings is always-on, hence re-check when the API becomes available
  () => isApiReact && isLedgerCapable(),
  [api]
);
...
// instead of isLedgerCapable() && here
{showLedger && (
  ...
)}
``

Hence why the in-page tabs switch works.

**Comment by lumierephoto** [comment]
You need to be using the Chrome browser

**Comment by jacogr** [comment]
Resolved as part of the hooks move in https://github.com/polkadot-js/apps/pull/4195
