### ISSUE TITLE
Judgements are not accounted properly

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#4177]
If an account gets a "Reasonable" from a registrar and a "LowQuality" from another, the UI shows:
![image](https://user-images.githubusercontent.com/738724/101516946-69e2cb00-3980-11eb-99cd-87b8104ba595.png)

**Comment by chevdor** [comment]
#2297 may help addressing the issue

**Comment by jacogr** [comment]
Sadly the above has nothing to do with it - it sit in the api derives.
