### ISSUE TITLE
Linking to polkadot.js.org/apps with a nodeUrl

### ISSUE THREAD

**Issue by raykyri** [polkadot-js/apps#4186]
Is there a way to link to Apps while providing a nodeUrl or chain to connect to?

I thought it may have been possible once, but it doesn't seem to be supported in the endpoint initialization code (e.g. https://github.com/polkadot-js/apps/blob/7ed65ebf7bc3c2eb0ea74dbaa0bb13628a1ce3da/packages/apps-config/src/settings/endpoints.ts)

**Comment by jacogr** [comment]
try `https://polkadot.js.org/apps/?rpc=<insert-full-wss-endpoint-here>`, e.g. this will connect to westend -

https://polkadot.js.org/apps/?rpc=wss://westend-rpc.polkadot.io

**Comment by raykyri** [comment]
Aha, that's exactly what I was looking for, thanks!
