### ISSUE TITLE
Vanity Generator: Public Address does not fit when seed is imported

### ISSUE THREAD

**Issue by jonasW3F** [polkadot-js/apps#4191]
I was using the Vanity generator and I experienced that the browser window could close after a certain time elapsed (say a few hours). Therefore, I did periodically screenshots of the result and I actually found a very nice address (derived with ed25519). However, if I import the seed into the extension, I receive a different public address than the one displayed in the vanity generator (I am on the correct chain). I triple checked that I inserted the correct seed (got always the same "wrong address").

So it seems that there is some part missing to derive the public address as displayed in the vanity generator. The "save" process seems to do some transformations such that the seed actually leads to the correct public address.

Is there any way now to derive the public address I selected from the seed?

**Comment by jacogr** [comment]
The extension always creates sr25519 addresses. The vanity (by default, faster), creates ed25519.

**Comment by jonasW3F** [comment]
Is there a way to change a ed25519 seed to a sr25519 one? The "save" function does so, doesn't it? Even after the creation by ed25519 the save function will lead to the situation that the account is imported into the extension with the "correct" public address. I checked the address format (the seed was created on the polkadot.js Kusama page) and neither the substrate, polkadot or kusama format displays the address which was displayed in the vanity generator.

**Comment by jacogr** [comment]
The underlying crypto is different. apps doesn't convert from one to the other, ed25519 stays ed25519.

The only way to import an ed25519 into the extension is via the JSON imports. So basically the workaround would be -

- add the account via seed in the apps UI (incognito is fine)
- ensure you have ed25519 selected
- make sure it matches
- download JSON
- import JSON into the extension

**Comment by jonasW3F** [comment]
worked like a charm, thank you very much!!
