### ISSUE TITLE
When submitExtrinsic fails, status doesn't go to error

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#420]
To reproduce (at least for me) -

1. Run master + dev chain
2. Submit via Ferdie
3. Error gets thrown and it shows up in console as unhandled

**Comment by ltfschoen** [comment]
@jacogr are you using the "master" branch of the substrate repo https://github.com/paritytech/substrate?

**Comment by ltfschoen** [comment]
@jacogr I just tried it using paritytech/substrate repos "master" branch (latest updated yesterday) by running `./target/debug/substrate --dev` and the polkadot-js/apps repos "next" branch.

In the browser console it displayed the following after I clicked "Sign & Submit" in the modal window.

<img width="898" alt="screen shot 2018-11-08 at 12 59 04" src="https://user-images.githubusercontent.com/6226175/48197664-b51bf100-e356-11e8-8eff-a67d48efff78.png">

And in the substrate node terminal it displayed the following:

<img width="1014" alt="screen shot 2018-11-08 at 12 59 37" src="https://user-images.githubusercontent.com/6226175/48197654-ae8d7980-e356-11e8-9202-e4fa13025360.png">

**Comment by ltfschoen** [comment]
@jacogr I've updated the screenshot in my previous comment so it shows the error

**Comment by jacogr** [comment]
Closed in #422
