### ISSUE TITLE
[Proposal] in the apps/public/locales/zh, "only with an identity" is translated into "只有一个身份",  I think it would be better to replace it with "only show identity", means "只显示拥有身份"

### ISSUE THREAD

**Issue by yashirooooo** [polkadot-js/apps#4200]

**Comment by jacogr** [comment]
Thanks for reporting. 

Generally a PR is appreciated for translation changes (translation.json can be generated via settings -> Translation, making the changes and then download). However having it visible in the list means it can be picked up.
