### ISSUE TITLE
Error when trying to stake from Ledger "utility.batchAll - Unexpected call index"

### ISSUE THREAD

**Issue by lumierephoto** [polkadot-js/apps#4201]
I've tried several times to stake DOT from my Ledger but I keep receiving an error.  I'm able to go through all the screens by selecting the amount of DOT to stake, selecting the nominator, adding the tip, etc. 

I keep getting the same error:  utility.batchAll - Unexpected call index

I'm only staking a small amount of DOT just to test out the staking, but I must admit that the process and UX is much harder than other staking coins like Tezos and Cardano all of which I'm staking safely from my Ledger as well. 

What do you believe the error is referring to?

<img width="464" alt="Screen Shot 2020-12-13 at 10 16 01 PM" src="https://user-images.githubusercontent.com/981541/102040411-58d7f680-3d92-11eb-8c24-7df05df7a53b.png">

**Comment by lumierephoto** [comment]
<img width="464" alt="Screen Shot 2020-12-13 at 10 16 01 PM" src="https://user-images.githubusercontent.com/981541/102040379-49f14400-3d92-11eb-97e7-84d5c5862425.png">

**Comment by jacogr** [comment]
It is not supported on the Ledger via the interface at this point, the tracking issue is here - https://github.com/Zondax/ledger-polkadot/issues/16

You need to use the "+ stash" option for a ledger, see -

- https://wiki.polkadot.network/docs/en/learn-ledger
- https://stakingfac.medium.com/polkadot-ledger-staking-guide-17eac5629217

**Comment by lumierephoto** [comment]
OK, thanks. I will check out the links.
