### ISSUE TITLE
How to package this project

### ISSUE THREAD

**Issue by hero008** [polkadot-js/apps#4215]
build error

**Comment by jacogr** [comment]
It obviously works for the developers and on CI. So you need to be very specific as to what you are doing. Sadly with the issue as logged, I cannot be of any help since you provided no information at all.

**Comment by hero008** [comment]
![image](https://user-images.githubusercontent.com/35803375/102206449-9a3de280-3f07-11eb-9b25-3d22687cc510.png)
How to package the HTML file of local executable code

**Comment by hero008** [comment]
I am a novice thank you

**Comment by jacogr** [comment]
No issues, happy to help, provided there is information to act on :)

You are correct that the above is not Windows compatible. `NODE_ENV=...` syntax works on Linux and MacOs to only pass the environment across for that single command, it won't work as-is on Windows. (Like the set change won't have the desired effect on MacOs/Linux)

Windows build compat is not something that has not been requested, tested or used in the past, so honestly don't know what changes may be required to support it. The set environment may yield the desired effect.

**Comment by hero008** [comment]
![image](https://user-images.githubusercontent.com/35803375/102295747-01e74280-3f87-11eb-9199-aedbf03cb316.png)
![image](https://user-images.githubusercontent.com/35803375/102295796-162b3f80-3f87-11eb-981f-be27b4ed5c25.png)
Run yarn start successfully on MAC, but error is reported when running yarn build
Or how to build it on windows

**Comment by hero008** [comment]
![image](https://user-images.githubusercontent.com/35803375/102318168-dc246280-3fb3-11eb-925b-6413eaad43cb.png)
 error is reported when running yarn build:www
