### ISSUE TITLE
On linix system, it is successfully compiled by yarn start  However, an error is reported when running yarn build  Thank you!

### ISSUE THREAD

**Issue by hero008** [polkadot-js/apps#4224]
![image](https://user-images.githubusercontent.com/35803375/102360094-8d46ef00-3fec-11eb-921f-cbcc679c07bf.png)
![image](https://user-images.githubusercontent.com/35803375/102360172-a3ed4600-3fec-11eb-848a-94884fe7dc8e.png)
![image](https://user-images.githubusercontent.com/35803375/102360230-b8314300-3fec-11eb-8da1-284f2db772f5.png)
![image](https://user-images.githubusercontent.com/35803375/102360270-c5e6c880-3fec-11eb-8b49-78f8f1ddaa7c.png)
![image](https://user-images.githubusercontent.com/35803375/102360291-caab7c80-3fec-11eb-8b81-be8d671c5200.png)

**Comment by jacogr** [comment]
Weird. Not sure why.
