### ISSUE TITLE
Question: Using ui-keyring as local (filesytem) dependency.

### ISSUE THREAD

**Issue by lovesh** [polkadot-js/apps#4225]
I was trying to test Ledger wallet support for dev chain. For that I cloned the [ledger-polkadot-js](https://github.com/zondax/ledger-polkadot-js) repo, made a new app object and was able to use that as a local dependency in the [ledger package of the UI repo](https://github.com/polkadot-js/ui/tree/master/packages/ledger), and add spec name in [index.ts](https://github.com/polkadot-js/ui/blob/master/packages/ledger/src/index.ts#L20) and successfully (checked that it resolves to local package) changed the [ui-keyring](https://github.com/polkadot-js/ui/tree/master/packages/ui-keyring) package's dependency to point to the local ledger package like this `"@polkadot/ledger": "file:/<filesystem path to UI repo>/packages/ledger"`. Now I need to use this ui-keyring package with apps. For this, I pointed [react-components](https://github.com/polkadot-js/apps/blob/master/packages/react-components/package.json)'s ui-keyring dependency to the local ui-keyring package like this `"@polkadot/ui-keyring": "file:<filesystem path to UI repo>/packages/ui-keyring"` but now `yarn build` cannot find that package and gives error 
```
react-components/src/util/checkVisibility.tsx:7:21 - error TS2307: Cannot find module '@polkadot/ui-keyring' or its corresponding type declarations.

7 import keyring from '@polkadot/ui-keyring';

..... more such errors

react-signer/src/util.ts:9:21 - error TS2307: Cannot find module '@polkadot/ui-keyring' or its corresponding type declarations.

9 import keyring from '@polkadot/ui-keyring';
```

The filesystem path is correct as my IDE is able to resolve that (Ctrl+Click) and I see that in `node_modules` directory, the package ui-keyring exists and the type files (`*.d.ts`)  exist.

**Comment by jacogr** [comment]
To test with apps, assuming you have a directory structure like `<ROOT>/{apps, ui}` (i.e. ui and apps on the same level), the recommended way (i.e. how all the repose here are tested with apps pre-merge) it to just execute `yarn polkadot-dev-copy-to apps` in the `ui` folder. That builds the packages and copies them.

**Comment by lovesh** [comment]
That works for me. Thanks. I saw this error message however at the end but I am assuming it's not important.
```
Error: ENOENT: no such file or directory, chmod '<path to apps>/node_modules/@polkadot/ui-keyring/node_modules/mkdirp/bin/cmd.js'
```

**Comment by jacogr** [comment]
I have seen that a couple of times before. Generally a yarn fixes it

but as long as it works, wouldn’t worry.

**Comment by lovesh** [comment]
Got it. If you don't mind, can you briefly explain why the usual way of specifying a local dependency did not work?

**Comment by jacogr** [comment]
No idea. Remember there is a build step. Unless it is linked from the build folder it is unlikely to work.

**Comment by jacogr** [comment]
Closing.
