### ISSUE TITLE
AccountId input field not shown on Moonbase Alpha Chain State app

### ISSUE THREAD

**Issue by JoshOrndorff** [polkadot-js/apps#4226]
When connecting Apps to the Moonbase Alpha testnet, going to the Chain State app, and selecting the system pallet. I cannot see a field to enter the accountId. If you disable the "include option" slider, the "empty" field appears as expected, but it disappears again when disabling.

![image](https://user-images.githubusercontent.com/2915325/102410703-e8fa8380-3fbe-11eb-970d-36540275f340.png)
![image](https://user-images.githubusercontent.com/2915325/102410629-ce280f00-3fbe-11eb-90ba-a20b46889094.png)

**Comment by JoshOrndorff** [comment]
cc @joelamouche

**Comment by jacogr** [comment]
The layout above is completely broken, the option should not overlay the top at all as a start. 

Not sure this is Moonbase related at all, something else is off.

**Comment by jacogr** [comment]
Ok, so I can replicate if I have no accounts or contacts. The AccountInput component doesn't render in those cases.
