### ISSUE TITLE
The signing app/page is no longer working

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#4230]
https://polkadot.js.org/apps/#/signing

![image](https://user-images.githubusercontent.com/738724/102495000-d3946080-4075-11eb-834d-98ebb33d573a.png)

**Comment by jacogr** [comment]
Fallout from https://github.com/polkadot-js/apps/pull/4227 - it should be working atm.

**Comment by chevdor** [comment]
It looks good again
