### ISSUE TITLE
What is the authorization of transfer pop-up authorization transaction? I don't know this process very well

### ISSUE THREAD

**Issue by hero008** [polkadot-js/apps#4238]
![image](https://user-images.githubusercontent.com/35803375/102678872-39075f00-41e6-11eb-93ec-fb92aabb1518.png)

**Comment by jacogr** [comment]
It plays a couple of roles -

- it allows you to verify the details of the transaction you are sending
- it shows the fees associated with the transaction
- it allows you to enter your password (unlocking your account and signing the transaction)

**Comment by jacogr** [comment]
Closing
