### ISSUE TITLE
Cannot see beneficiary and payout due on bounty tab

### ISSUE THREAD

**Issue by rrtti** [polkadot-js/apps#4239]
On bounty tab, the information on beneficiary and payout due does not appear, instead a - is shown:

<img width="1197" alt="Screenshot 2020-12-19 at 08 51 58" src="https://user-images.githubusercontent.com/22815262/102684284-7d3f3300-41d7-11eb-9cc6-6fef1fc55ccf.png">

**Comment by jacogr** [comment]
Weird. This was there. Is it recent in the last day or two or a week old? The reason for asking is that the retrieval has changed, so looking at a culprit.

**Comment by rrtti** [comment]
On both of my laptops since yesterday: I thought of waiting until I saw the "add bounty" button since maybe this was being touched there, but I can still see it.

**Comment by jacogr** [comment]
It is actually what there is in the state, see

![image](https://user-images.githubusercontent.com/1424473/102690469-e76ecc80-4205-11eb-8a34-9ca75393381b.png)

What is missing above is the value, the final recipient is not (yet) available at this stage.

**Comment by krzysztof-jelski** [comment]
Yes, the UI  is consistent with the state. I'd say the UX may be confusing as of now, and we're working on a version where you see just the info relevant to a particular Bounty Status. WIP design can be found here: https://www.figma.com/file/TnSJFgORMMwJAnKRxHHh7W/Bounty?node-id=375%3A121

**Comment by krzysztof-jelski** [comment]
@rrtti are you ok we closed this? Seems nothing can be done here currently.
