### ISSUE TITLE
Uncaught Error Rendering Extrinsic/Event

### ISSUE THREAD

**Issue by danforbes** [polkadot-js/apps#4252]
I am using a [branch of the Node Template](https://github.com/danforbes/substrate-node-template/tree/did/) to interact with the [DID pallet](https://github.com/substrate-developer-hub/pallet-did/tree/36c65ef36c1a1e515c003af09c7f130bf68e8817). When I try to use Apps UI to inspect an `addAttribute` extrinsic or `AttributeAdded` event, it instead renders an error...
![image](https://user-images.githubusercontent.com/2193247/102720841-a03b1700-42ab-11eb-81af-c5a258c39494.png)

Here are my type definitions:
```json
{
  "Address": "AccountId",
  "BlockNumber": "u64",
  "LookupSource": "AccountId",
  "Signature": "Vec<u8>",
  "Attribute": {
    "name": "Vec<u8>",
    "value": "Vec<u8>",
    "validity": "BlockNumber",
    "creation": "Moment",
    "nonce": "u64"
  },
  "AttributeTransaction": {
    "signature": "Signature",
    "name": "Vec<u8>",
    "value": "Vec<u8>",
    "validity": "u32",
    "signer": "AccountId",
    "identity": "AccountId"
  }
}
```

**Comment by jacogr** [comment]
Is there a public endpoint for this? (To inspect metadata and types) the reason for asking is that it actually makes looking at what is missing in the definitions easier.

**Comment by danforbes** [comment]
I believe you should be able to find the node running here https://polkadot.js.org/apps/?rpc=wss%3A%2F%2F/danforbes.playground.substrate.dev/wss#/explorer

**Comment by jacogr** [comment]
Thank you. Will take a peek in the morning after the weekly releases.

**Comment by danforbes** [comment]
@jacogr - I will need to restart the Playground instance, so just let me know when you need to take a look.

**Comment by jacogr** [comment]
How are you sending it?

The extrinsic fails which means it is either the params or the DispatchResult. Since the event is only `Vec` and the same one appears in the extrinsic, it would point to that.

**Comment by jacogr** [comment]
`_initArray` is internal to BN.js, so it would be that one.

**Comment by danforbes** [comment]
> How are you sending it?

I am sending it with this script https://github.com/danforbes/substrate-node-template/blob/did/scripts/src/index.js

Good catch on the block number. I changed that in my types, but it still does not seem to make a difference.

**Comment by jacogr** [comment]
I just meant DispatchInfo decoding on the event side. 

You are also overriding Signature to a Vec type, so the actual extrinsic decoding may fail. 

As a start, remove all types only with Address and LookupSource still applied and send the add since it is only uses base types. (Would have tried, for some reason I can’t compile the template)
