### ISSUE TITLE
Displayed balances are not correct for Moonbeam alpha

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#4256]
the app displays 167.7721MUnit

MetaMask displays 0.0691ETH

The Faucet sent 10 units

**Comment by joelamouche** [comment]
Possibly related to types because our api tests show the same balance as MetaMask but don't inject types the same way

**Comment by joelamouche** [comment]
UPDATE:
changing api instantiation in react-api to :
```

    const polkadotJsTypes = require("./standalone-types.json");

    api = new ApiPromise({ 
      provider, 
      registry, 
      types: polkadotJsTypes,
      // signer, 
      // types, 
      //typesBundle, 
      // typesChain, 
      // typesSpec 
    });
```

With a copy of our test types, shows the correct balance

**Comment by joelamouche** [comment]
uncommenting typesBundle brings the problem back

**Comment by jacogr** [comment]
Your refCount applies to all versions, https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/bundle/spec/moonbeam.ts#L20

**Comment by joelamouche** [comment]
omg how could I not see this *facepalm*

Thank you for your help. Let me make a PR real quick
