### ISSUE TITLE
Installation instructions are unclear

### ISSUE THREAD

**Issue by HeavyFailry** [polkadot-js/apps#4263]
Hello, I'm pretty new.
I didn't understand how to install and keep the desktop app up to date on Ubuntu? Please help.

**Comment by krzysztof-jelski** [comment]
Hi!

You should be good just downloading the [latest AppImage from "Releases"](https://github.com/polkadot-js/apps/releases/download/v0.72.1/Polkadot-JS-Apps-0.72.1.AppImage). Just download it, make it executable, and run. Should notify you about update. If this happens, you just need to restart. New releases come every Monday.

If you can help us with improving the README based on your experience, that would be very welcome.

**Comment by HeavyFailry** [comment]
Thanks @krzysztof-jelski 
I didn't know it's able to update itself.

I've also tried it on MacOS and when put into the `Applications` dir, it can be found and launched via any search, and indicates an icon.
I couldn't find a good way to make the appimage searchable and the icon appear in the apps menu. The only way to launch it is put to some PATH location and run from console, which is not desirable for an UI application.

**Comment by krzysztof-jelski** [comment]
Perhaps you can try `appimaged` (https://github.com/AppImage/AppImageKit). Haven't tried it myself, but the readme claims:
> handles registering and unregistering AppImages with the system (e.g., menu entries, icons, MIME types, binary delta updates, and such).
