### ISSUE TITLE
Ledger Account Type Index selection

### ISSUE THREAD

**Issue by anjaw3f** [polkadot-js/apps#4271]
![Screenshot 2020-12-24 at 13 19 36](https://user-images.githubusercontent.com/70277946/103085571-c1bd3b00-45ea-11eb-83f1-006c22aeb9a3.png)

It seems many users misunderstand "Add account" and mistakenly translate it as "Create a new account". 

Is there any way that we can make clear that if they want to access an existing account, they should use the same account type and index as they did before? 

I'm getting emails, saying "I don't want to add a new account, I want to access the one I already have". It doesn't seem to be 100% clear that that's exactly what they can do here.

**Comment by jacogr** [comment]
Makes sense. Will look at “attach” or something similar.

**Comment by jacogr** [comment]
Closing, changed.
