### ISSUE TITLE
Add "send to council" from bounties

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#4273]
It would do a council proposal with `approveBounty(bountyId)` - at this point council can vote.

threshold is the same as for treasury proposals.

**Comment by krzysztof-jelski** [comment]
How about allowing council members to approve/reject and vote without leaving the Bounties page? Compare https://www.figma.com/file/TnSJFgORMMwJAnKRxHHh7W/Bounty?node-id=368%3A67
What do you think about it?

**Comment by jacogr** [comment]
The issue is that the council members go to the council page for their actions. 

The alternative is that they need to go to bounties and treasury and council to vote. And that mean you lose focus and drop stuff. 

It is the same reason the treasury voting is only under council now - the previous split voting just didn’t work for active council members. 

Once created it shows up under council anyway since it is a council approve/reject, so no need to duplicate.

**Comment by natiwa** [comment]
hey, 

I think that from the user perspective it will be great to have one consistent flow for similar actions. Now, we can vote "Nay" or "Yay" on the modal. Having the same experience for one step earlier (approving or rejecting the bounty/proposal) will make navigating the application intuitive for the user. 

Now it might sound like a lot of changes have to be done, but it may be worth implementing.

**Comment by krzysztof-jelski** [comment]
@jacogr by the way, what was "the previous split voting" you mentioned?

**Comment by natiwa** [comment]
In my opinion, it’s more convenient for the user to have voting visible in these two places. Duplicating actions it’s not a bad thing, it’s making an application more approachable for the user.

**Comment by jacogr** [comment]
So the voting was duplicated in Treasury & Council. (It will always appear in council since it is a council proposal). This was exceptionally confusing -

- council didn't just have  place to vote
- worse, the same votes showed in 2 places and allowed actions

So the slight issue atm is that the council proposal breakdown is a bit generic, so in the case of treasury it should actually just show the value/beneficiary. (And allow a link to the treasury proposal extenally). So there will be some UI duplication.

**Comment by jacogr** [comment]
@natiwa No. As a council member and actual user of this functionality, I respectfully disagree. It is exceptionally confusing. It is not something that should make any comeback.

**Comment by krzysztof-jelski** [comment]
OK, I think that sounds good. Can we just specify exactly what status do we want to show in the Bounties list? Is what we have in designs accurate, or do we need more/less info? 
![image](https://user-images.githubusercontent.com/430616/103287162-18a78380-49e2-11eb-8776-b5d9bc21834e.png)

**Comment by jacogr** [comment]
How do you map from the actual council proposal through to the status above? (Remember that the approval is either a `council.acceptProposal(..inner)` or  `council.rejectProposal(..inner)` - different thresholds in both cases, depending on the actual chain. A failing accept doesn't mean that the bounty is rejected, just that the voting didn't pass)

**Comment by krzysztof-jelski** [comment]
That goes into the "Status" column:
![image](https://user-images.githubusercontent.com/430616/103289240-f95f2500-49e6-11eb-8cfe-602eb97f93f4.png)

Would be one of "Approval under voting", "Rejection under voting", "Curator under voting", "Cancel under voting"... 

Threshold would go just as the second number to `2/4`, no?

**Comment by jacogr** [comment]
Can work. Just bear in mind to keep the duplication to a minimum - the chain-interfaces in council are (like most things in Substrate) not set in stone. So having to maintain the same in 2 different places are an issue.

**Comment by krzysztof-jelski** [comment]
Should be auto-closed via #4320.
