### ISSUE TITLE
Article padding broken

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#4275]
Assuming is after the width adjustments in https://github.com/polkadot-js/apps/pull/4170

![image](https://user-images.githubusercontent.com/1424473/103217434-de25e400-4918-11eb-86fd-acf219e64bb8.png)

(Assuming this is the same in accounts and everywhere where these are displayed?)

**Comment by jacogr** [comment]
The global override clobbers it -

![image](https://user-images.githubusercontent.com/1424473/103218217-bfc0e800-491a-11eb-8418-e4b32cdf0d44.png)

**Comment by MiZiet** [comment]
I think this issue occurs only in `Contracts`. 
The banner is correctly displayed correctly in `Accounts` and `JavaScript` pages
![image](https://user-images.githubusercontent.com/55240109/103225905-3cf45900-492b-11eb-8c1d-6adb40d713af.png)
