### ISSUE TITLE
white page whene  bond more funds  from controller 

### ISSUE THREAD

**Issue by PashaKlybik** [polkadot-js/apps#4277]
browser: firefox 
The problem exists when only the controller account is imported.
Guide to repeat  `staking->accounts->three dot menu - > bond more funds and after submitting tx`

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/11669156/103239352-4d71f700-495e-11eb-976b-a2185d7e3335.png">

**Comment by jacogr** [comment]
Thanks for reporting. 

It should not actually be available in the menu.  It is a stash-only operation. (Not sure why the option is available, there is supposed to be a check for it)

**Comment by jacogr** [comment]
Closed in #4278
