### ISSUE TITLE
apps v0.73.2-1 get “read” error

### ISSUE THREAD

**Issue by iceming123** [polkadot-js/apps#4283]
i called `get (): bool` function in ink! contract instance, get this error:
```
polkadot.02.238a3b3a.js:1 2020-12-29 16:45:11        RPC-CORE: call(callRequest: ContractCallRequest, at?: BlockHash): ContractExecResult:: -32602: Invalid params: invalid type: string "0x00000000000000000000000000000000", expected u128.
```
polkadot.js apps v0.73.2-1

**Comment by jacogr** [comment]
It is an issue on the RPC layer in Subsrate, specifically here -

https://github.com/paritytech/substrate/blob/master/frame/contracts/rpc/src/lib.rs#L82-L83

The `Balance` should allow `NumberOfHex` like the `gasLimit`. (u128/Balance is too large to serialize as a number)

The current version of the API has changed serialization for all > u64 values, hence this issue popping up.

**Comment by jacogr** [comment]
Cause of #4280

**Comment by iceming123** [comment]
than,what can i do? to make it normal.

**Comment by jacogr** [comment]
Substrate needs a fix.

**Comment by iceming123** [comment]
ok, thks
