### ISSUE TITLE
Adjust IdentityIcon background for dark

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#4294]
![image](https://user-images.githubusercontent.com/1424473/103295345-07677280-49f4-11eb-9b31-fc0e6960dc6f.png)

**Comment by jhonalino** [comment]
what kind of adjustment are we looking to do here jacogr?

**Comment by jacogr** [comment]
I'm honestly not quite sure :)

I think a darker gray background for those icons would do the trick. The issue I find (and the dark still has a lot of work left) is that especially at night the white pops out way too much. I def would not drop the background (the the colors are subtle in places), but as it stands the icon background is great on light, but horrible in the dark more.

So my short answer - it needs to be made darker, not exactly sure to where - that will need some playing until it looks "ok". :)

**Comment by jhonalino** [comment]
what do you think of this shades? a little darker or ligther? 

![zoomedin](https://user-images.githubusercontent.com/13143458/105629965-f21b1380-5dfa-11eb-8c7d-44c4b2138e75.png)

![zoomedout](https://user-images.githubusercontent.com/13143458/105629966-f2b3aa00-5dfa-11eb-9501-981335f424bf.png)

what do you think of having a separate theme for polkadot ? so instead of 'polkadot' it be like 'polkadot-dark' for the theme.
that way when updates are needed but only for the dark theme we only need to edit the polkadot-dark theme. this would probably require a refactoring. for the shared parts

thank you very much!

**Comment by jacogr** [comment]
The share about works quite well. I would prefer just having the theme detection inside the `IdentityIcon` itself. 

It is also a bit of work, but really nicely localized since we have the theme property available, see for instance - https://github.com/polkadot-js/apps/blob/master/packages/react-components/src/Table/Foot.tsx#L29

As an aside, just looking at your screenshot the red is also problematic in dark (e.g. Zug Capital/19 overbooked numbers). Small steps, will eventually get to them all and make it pleasing.

**Comment by jhonalino** [comment]
![Screen Shot 2021-01-24 at 5 23 22 AM](https://user-images.githubusercontent.com/13143458/105631672-6dcd8e00-5e04-11eb-9916-906fea4faeb9.png)
![Screen Shot 2021-01-24 at 5 23 39 AM](https://user-images.githubusercontent.com/13143458/105631674-6efebb00-5e04-11eb-8611-5d956b48e830.png)

I've made some updates to the red please let me know what you think. 

thank you for that sample. that's a really nice abstraction 
now I see what you mean about theme detection IdentifyIcon

**Comment by jhonalino** [comment]
btw I removed the rounded border. but here is how it looks. what do you think? do you like to keep it there? 

![Screen Shot 2021-01-24 at 5 31 37 AM](https://user-images.githubusercontent.com/13143458/105631896-9904ad00-5e05-11eb-9b67-0f9adad24c3f.png)

**Comment by jhonalino** [comment]
without border: 
![Screen Shot 2021-01-24 at 5 35 19 AM](https://user-images.githubusercontent.com/13143458/105631998-fa2c8080-5e05-11eb-8e8f-3f2d1dda420f.png)

**Comment by jacogr** [comment]
It looks great on dark - for the border, I would just check the following as well -

- light theme
- InputAddress (e.g. transfer dialog, the icon on the left has some funky alignment)

In both I think it does get used for some effect. Possible for dark we could just make it the same as the new background to not be visible. (Or transparent)

**Comment by jhonalino** [comment]
![Screen Shot 2021-01-24 at 6 16 06 AM](https://user-images.githubusercontent.com/13143458/105633196-10d5d600-5e0c-11eb-83ff-528b39a91d57.png)
![Screen Shot 2021-01-24 at 6 16 24 AM](https://user-images.githubusercontent.com/13143458/105633198-116e6c80-5e0c-11eb-8a8f-1c3bc47e0c78.png)
![Screen Shot 2021-01-24 at 6 17 34 AM](https://user-images.githubusercontent.com/13143458/105633199-12070300-5e0c-11eb-8626-d3f4d29809f8.png)

transparent border looks good! what do you think?

**Comment by jacogr** [comment]
100% agreed.

**Comment by jacogr** [comment]
Closed. Thanks a lot for this.
