### ISSUE TITLE
Specific validator on showing 0% commission on Targets page - actually 100%

### ISSUE THREAD

**Issue by laboon** [polkadot-js/apps#4312]
I have noticed this for one specific validator ( 13AtGSHJaDZrLHELmK6iKAuaAKHcetrH73N2KEb5M5SX1yDR ), but I have not 
 exhaustively looked at all validators to see if there is a pattern. 

According to the API and Polkascan ( https://polkascan.io/polkadot/session/validator/1331-182 ) , this validator has 100% commission, and looking at their transaction history and their validator stats ( https://polkadot.js.org/apps/#/staking/query/13AtGSHJaDZrLHELmK6iKAuaAKHcetrH73N2KEb5M5SX1yDR ) page, this has remained constant.

```
13AtGSHJaDZrLHELmK6iKAuaAKHcetrH73N2KEb5M5SX1yDR.
	Total stake: 2278678.8437396684
	Self stake: 1 DOT
	Address: 1REEV3CUqiMMfRdeTy9apQwXVabcg2TcQhvsVFtusByZ6ga, Stake: 981794.4609750516 DOT
	Address: 16fttU3nadc7KgFwxUqLyyryUiqW5VMbVMpTQ18GzNtbK9Tz, Stake: 1296883.382764617 DOT
	Commission: 100%
	Nominators: 2
```

But the Targets page shows their commission as 0%:

<img width="1129" alt="Screen Shot 2021-01-03 at 4 21 02 PM" src="https://user-images.githubusercontent.com/1417717/103482191-bc78a100-4ddf-11eb-974e-74cfb7a416dc.png">

Note that this validator was also recently slashed in era 215; I don't know if this has anything to do with it but may be relevant.

**Comment by jacogr** [comment]
Yes, it is the slashing. When you are kicked from the set, the preferences are set to 0. You need to re-validate, re-set. (The same applies to slashing and being kicked for being unrespinsive)

**Comment by jacogr** [comment]
See the prefs -

![image](https://user-images.githubusercontent.com/1424473/103482698-90125400-4de2-11eb-823f-c3b853ddd2ff.png)

**Comment by jacogr** [comment]
Closing. All as expected from the state.
