### ISSUE TITLE
Sending >1G from Charlie to Bob fails

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#432]
Using `substrate --dev` and polkadot-js-ui v0.21.0

![image](https://user-images.githubusercontent.com/738724/48285751-e1716380-e463-11e8-9042-47069536e947.png)
 
Sending 1G works, 2G fails, another 1G works, etc...

**Comment by yjkimjunior** [comment]
Hi @chevdor, I wasn't able to recreate your issue. Are you using the latest substrate?

http://recordit.co/NYnSRmwTOL

**Comment by ltfschoen** [comment]
I just tried it with the latest "next" branch polkadot-js-ui v0.21.0, and running a paritytech/substrate node with `./target/release/substrate --dev` that had version `substrate 0.1.0-25641b62-x86_64-macos`, and i was able to send from CHARLIE to BOB the following consecutively without any errors: 1074M, then 1075M, then 1074G, then 1075G, etc. After topping Bob up with more funds Iwas also able to send 2.3P back from BOB to CHARLIE.

Are you still encountering the issue @chevdor ?

**Comment by chevdor** [comment]
Tried again using https://polkadot.js.org/apps/next/#/transfer (0.21.0) and I still see the issue.

<img width="983" alt="screenshot 2018-12-03 at 10 04 33" src="https://user-images.githubusercontent.com/738724/49363783-e46a1780-f6e2-11e8-84d7-c96b0b89b8a1.png">

![image](https://user-images.githubusercontent.com/738724/49363809-f1870680-f6e2-11e8-9da6-c3c2d8f23d41.png)

**Comment by chevdor** [comment]
I did a refresh and opened the dev console to gather logs and in my attempts, it worked.
So there *IS* still something but I did not catch the logs yet. I will try again.

**Comment by chevdor** [comment]
Make sure you use MEGA as unit. I think I forgot to switch back to Mega after the refresh, explaining why my previous attempt did not fail.

![image](https://user-images.githubusercontent.com/738724/49364122-c224c980-f6e3-11e8-8213-c456c690bc38.png)

and the details on the issue:
![image](https://user-images.githubusercontent.com/738724/49364137-d4066c80-f6e3-11e8-9bd8-23912b378bf3.png)

**Comment by chevdor** [comment]
For the sake of proper testing, I also tried in 'incognito' mode and the issue remains visible.
The following maybe relevant: I am using `substrate 0.1.0-ec4407e3-x86_64-macos`

**Comment by ltfschoen** [comment]
@chevdor you're using an old version of substrate. your substrate version includes the git commit number`https://github.com/paritytech/substrate/commits/ec4407e3` of the substrate repo, which is about a month old.

please try fetching the latest version of substrate and then check if you still encounter the same error. these are the steps i follow on macOS:

```
git clone https://github.com/paritytech/substrate;
cd substrate;
git checkout master;
git remote add upstream https://github.com/paritytech/substrate;
git pull --rebase upstream master;
curl https://sh.rustup.rs -sSf | sh;
rustup update nightly;
rustup target add wasm32-unknown-unknown --toolchain nightly;
rustup update stable;
rustup default stable;
cargo install --git https://github.com/alexcrichton/wasm-gc --force;
cargo install --git https://github.com/pepyakin/wasm-export-table.git --force;
brew install openssl; brew upgrade openssl;
brew install cmake; brew upgrade cmake;
rustc --version; cargo --version;
./scripts/build.sh;
cargo run -- --dev purge-chain;
cargo run -- --dev --telemetry --telemetry-url ws://telemetry.polkadot.io:1024
```

**Comment by jacogr** [comment]
It 100% still exists in the current version, it is not a commit issue here at all. 

(As a funny point - @chevdor actually logged the commit-hash issue as part of the version and telemetry in Substrate way-back-when, we should thank him we have it available everywhere - actually started the implementation of it as well, however he was beaten to the punch)

**Comment by ltfschoen** [comment]
i just used the latest version of substrate "master" branch
<img width="753" alt="screenshot 2018-12-06 at 15 37 21" src="https://user-images.githubusercontent.com/6226175/49590792-070f6100-f96d-11e8-946c-d6c57f028046.png">
 `substrate 0.1.0-0e852691-x86_64-macos` using the latest version of the "next" branch of `polkadot-js-ui v0.21.0` using the above approach, and i was able to replicate the error that @chevdor encountered when sending a transaction of 1074 MEGA or greater.

The error shown in the substrate node is shown as:

<img width="1233" alt="screenshot 2018-12-06 at 15 35 35" src="https://user-images.githubusercontent.com/6226175/49590655-b5ff6d00-f96c-11e8-8416-8a8ad90faec3.png">
