### ISSUE TITLE
system.networkState method not found

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#4346]
Kusama and Polkadot do not expose the networkState function in their metadata, but it's callable in RPC. Not sure if that's intended, just thought I'd mention it here.

**Comment by jacogr** [comment]
The unsafe ones are tricky. So what happens is that `rpc_methods` does expose it, however upon calling it fails.

![image](https://user-images.githubusercontent.com/1424473/104019508-f4a32980-51bb-11eb-89b4-9a3584f292bc.png)

See above.

**Comment by jacogr** [comment]
If a fix is important to you, would suggest logging it on substrate itself.

**Comment by jacogr** [comment]
Closing, nothing that can be done to fix this from the JS API side.
