### ISSUE TITLE
Polkadot/Substrate Portal forgot accounts in Windows 10 app

### ISSUE THREAD

**Issue by dows29** [polkadot-js/apps#4348]
I'm use Parity Polkadot v0.8.26 api v3.3.1 apps v0.74.1 on Windows 10 x64 Rus
I new user of Polkadot. I'm download and install app for Windows there days ago. After I add two new accounts in app by Accounts\Accounts menu:
![image](https://user-images.githubusercontent.com/77169854/104053954-3902e980-51fd-11eb-84fd-35f1710817b9.png)

Now if close app and open it one more, app don't remember my accounts. I need push "+Add account", enter my seed phrase and password and restore it from Internet everytime. Is it normal situation or bag?

**Comment by jacogr** [comment]
This certainly sounds incorrect. On the local instance it should remember the accounts between restarts. 

Thanks for reporting.
