### ISSUE TITLE
Desktop App Fails to Connect to Local Node Due to Content Security Policy

### ISSUE THREAD

**Issue by zicklag** [polkadot-js/apps#4349]
Hey there!

I just tried to connect the desktop app Appimage to a local polkadot node started by running `polkadot --dev`, but the app throws a console error because it is apparently configured with a content security rule that requires all websocket connections to be `wss`.

![image](https://user-images.githubusercontent.com/25393315/104079193-5c229e80-51e7-11eb-8130-86a048dd446b.png)
![image](https://user-images.githubusercontent.com/25393315/104079199-65137000-51e7-11eb-976f-e95b43df32cd.png)

**Comment by jacogr** [comment]
Thanks for the report. https://github.com/polkadot-js/apps/blob/master/packages/apps-electron/src/electron/contentSecurityPolicy.ts#L16 wold need to be extended to `ws`.
