### ISSUE TITLE
QR codes in WIP 'dark theme' cannot be reliably scanned due to lack a quiet zone

### ISSUE THREAD

**Issue by s3krit** [polkadot-js/apps#4390]
### Steps to reproduce

1. Set polkadot.js/apps to the WIP dark theme
2. Create a transaction to be signed by a remote account (e.g., transferring of funds)
3. Attempt to scan the QR code (see attached image 1.png)
![1](https://user-images.githubusercontent.com/157807/104454444-27776400-55a6-11eb-8b80-89700f8b877f.png)

### Expected result

parity-signer is able to scan the resulting QR code and sign the transaction

### Observed result

parity-signer (and an other QR code application I attempted to use) was unable to scan the QR code, thus the transaction could not be signed

### Workaround & solution

Current workaround is simply to not use the dark theme (I know it's WIP and experimental). Solution would be to add a quiet-zone around the QR code. Compare attached images 2.png and 3.png - 3.png is in light-mode, and is entirely scannable. [this](https://qrworld.wordpress.com/2011/08/09/the-quiet-zone/) article sums up what size the quiet-zone should be, as a function of the size of the 'module' (i.e., smallest square in the QR code), but in real terms, a white margin of about 10px would likely be fine.

![2](https://user-images.githubusercontent.com/157807/104454451-280ffa80-55a6-11eb-84c2-16428a7a1d82.png)
![3](https://user-images.githubusercontent.com/157807/104454452-28a89100-55a6-11eb-8589-4590b81d2e93.png)

**Comment by jacogr** [comment]
Ahhh, I remember this issue from both the Ethereum wallet as well as the actual extension. A small border does the trick.
