### ISSUE TITLE
Account doesn't hold correct amount of balance

### ISSUE THREAD

**Issue by Sardoniac** [polkadot-js/apps#4405]
Hi there. Just logged into my account on https://polkadot.js.org/apps/#/accounts. It says there 0.00 balance/transferable amount, while on https://polkascan.io/ it shows the expected amount. On https://polkadot.polkastats.io/ it shows only about 50% of the expected amount.

If I try to transfer polkadot on https://polkadot.js.org/apps/#/accounts it shows about 70% of the polkadot to be transferable... wtf is going on???

**Comment by Sardoniac** [comment]
also for Info: I use a Ledger device for my Polkadotaccounts

**Comment by Sardoniac** [comment]
https://polkadot.subscan.io/ also shows the right amount of balance...

**Comment by jacogr** [comment]
Do you have any vested or locked? (Polkascan show the total balance, the transferrable is without vested and without locked). The accounts page has a breakdown of totals when you expand.

i.e. here is a list of 4 addressed I grabbed from the chain that are in various states with the expanded -

![image](https://user-images.githubusercontent.com/1424473/104565699-f3a34980-564c-11eb-85a2-6a7fe8203b04.png)

**Comment by Sardoniac** [comment]
I do have some locked for staking, well almost all, but it doesn't show those too. Neither on the account page, nor on the staking page.

**Comment by Sardoniac** [comment]
on the Network/Staking page it says: "No funds staked yet. Bond funds to validate or nominate a validator" even though

**Comment by jacogr** [comment]
Have you attached the ledger? The staking page will only show when it is actually attached. 

(There is an issue logged here to always make it available, even when unplugged - generally when unplugged, atm, it only shows up under the contacts, not as a full account)

**Comment by Sardoniac** [comment]
well I can only log to the account via the ledger, so usually I keep the Ledger attached during managing my dot account. Everything as per usual, just the balance is off.

Also yesterday evening there seemed to be some issues with the https://polkadot.js.org/. Couldn't log in to my account at all, it wouldn't load the page properly, it just showed: "Waiting to make connection to the remote endpoint and finishing API initialization." 

And today when I logged into the account I had above issues.

**Comment by jacogr** [comment]
The Web3 RPC was decommissioned yesterday, so that may point to the connection error.

It could very well be that it cannot retrieve the balances from the node, i.e. the UI always displays what is on-chain. May be worth a try to just swap to one of the other RPC providers to see if the responses are faster, one of Parity/OnFinality/Patract. (Parity is EU-hosted, Patract in Asia, not sure about the OnFinality location)

**Comment by Sardoniac** [comment]
can you give me a quick info on how to swap the RPC provider? Thank you already for the quick responses

**Comment by jacogr** [comment]
Just the top left, click on the network name - it will allow you to swap providers, see

![image](https://user-images.githubusercontent.com/1424473/104579036-bc886480-565b-11eb-8b96-9cab8abe81ff.png)

(My colors are different here since I'm on a different network currently, in your case it will be the Polkadot pink :)

**Comment by Sardoniac** [comment]
nice, that did the trick for me! Thank you very much <3

**Comment by jacogr** [comment]
It is weird - which RPC node were you on previously? (And now?) Would like to check those against my accounts as well.

**Comment by Sardoniac** [comment]
sure I can do that

**Comment by Sardoniac** [comment]
well now I swapped through all of the 3 available PCRs and now it would display it correctly every time... I guess previously I was on "Parity", since this seems to be the default?

**Comment by jacogr** [comment]
Closing.
