### ISSUE TITLE
Move Vanity App into Accounts App

### ISSUE THREAD

**Issue by yjkimjunior** [polkadot-js/apps#442]
Since generating vanity addresses is entirely for adding an address (unless something went over my head), it should exist right underneath the current addresses app. 
![vanity](https://user-images.githubusercontent.com/10432070/48377423-9ed9a200-e682-11e8-97b5-91ac6f64e5a6.png)

**Comment by jacogr** [comment]
Rather part of accounts app, since the secret keys are to be used there. Some jugging required to make it feel consistent. (However doing this will def. aid in usability overall)
