### ISSUE TITLE
Kusama - Polkadot JS - Ledger Nano X

### ISSUE THREAD

**Issue by mswezey23** [polkadot-js/apps#4434]
First Issue: 
1. I successfully added my account from my ledger nano x. 
2. The balance was initially 0.0; as it should be. 
3. I withdrew from an exchange some KSM. 
4. I confirmed this tx via a Kusama Explorer was indeed successful. 
5. My balance never updated in the Polkadot JS App. Even after a refresh. 

Work Around for the first issue:
I opened up an incognito window and added my ledger account. 
My balance finally was shown! 

Second Issue:
1. I cannot set an on-chain identity for my ledger account. 
2. I get this error trying to sign & submitr: `value cannot be printed`
3. This occurred during the run of the first issue above and after during the workaround run. 

Overall ledger support has a ways to go before becoming user friendly. 

![image](https://user-images.githubusercontent.com/1747669/104823997-f7cd9380-5813-11eb-86f2-58daf3bc4c1a.png)

**Comment by mswezey23** [comment]
I was able to send 1 KSM to another account successfully. 
Afterward, on-chain identity was still not working. Same error.

**Comment by jacogr** [comment]
Ledger itself does not support the identity extrinsic - the error you got was from the Ledger itself. Same with batch calls, the ZondaX team responsible for the Ledger is aware of both issues to extend their support. 

As for the first part, will read though in the morning when fresh. ;)

**Comment by mswezey23** [comment]
Ah, thank you for the quick reply! I'm glad ZondaX is on it! 

For the first part, I believe clearing my Application cache (F12) fixed it as my balances are now being shown and being updated when making transfers. 

I'm setting up to apply to the Kusama thousand validators program. I will if I can figure out a workaround so I'm not blocked on this. Perhaps using the Chrome Extension to set my Identity...If you have any suggestions that would be greatly be appreciated! 

With that, I shall close this issue! Thanks again and have a great weekend.

**Comment by Tbaut** [comment]
> Perhaps using the Chrome Extension to set my Identity

The problem that the account cannot leave the ledger. If ledger doesn't support the identity extrinsic, it means that you will not be able to send it from the ledger. 

Unless you are able to restore this account outside the ledger (which is a security issue), you will not be able to set an identity on it. This has to be supported by the ledger device.

**Comment by mswezey23** [comment]
Thanks for the deeper explanation @Tbaut!

I should have been more concrete with which chrome extension for future people that stumble upon this thread. I meant the Polkadot Chrome Extension (https://polkadot.js.org/extension/). As in using an account generated and stored on my laptop for the Controller account. Then using my Nano X account for the stash account. 

I'll read some more and experiment to see how I can put it together.
