### ISSUE TITLE
Identicon display address does not matched the 'copied' address

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#445]
Using a local node `substrate --dev` and connecting https://polkadot.js.org/apps/next/#/accounts to it.

Go `Create account` and provide a mnemonic (ie `little balcony original cover shoe meadow cargo about series private ability label`).

The identicon will show `1PBrpqr…vGJphf3`
If you click the icon, you will however get an address with different encoding in your clipboard: `5CStiVanvEtyuc1Z1wg2KSFs88phUjaXoQLf1DF8cqEnePnX`

![image](https://user-images.githubusercontent.com/738724/48405678-0c450b80-e733-11e8-9254-c3f21647046e.png)

**Comment by jacogr** [comment]
2 issues actually -

1. When creating a new address via mnemonic, the web-worker doesn't have the correct prefix (different context)
2. For testing accounts, the address is encoded pre-prefix-setting, so it is incorrect.

**Comment by jacogr** [comment]
Closed in #446
