### ISSUE TITLE
Reset explorer url when switching network

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#4454]
If I'm exploring a block on a network and I switch network, the page won't load because the block hash is not present in the new network.

I think it would improve the UX if the app could detect the network change and go back to the main explorer page

**Comment by jacogr** [comment]
The issue is that is breaks other very valid usecases - so for instance, I typically do council actions on one network and the switch to another to do the same. Same with staking. So yes, the explorer is an edge-case (when in a specific block), but probably not worth the effort to address.
