### ISSUE TITLE
Blank box when bonding to a 3rd party account

### ISSUE THREAD

**Issue by HikaruG** [polkadot-js/apps#4470]
### Issue or not ?

I discovered that when I try to bond my stash account's WSD to a controller account I do not own, the selection box becomes a blank box. 

The interesting part is that it is still possible to complete the transaction and bond WSD/DOT. 

**My question is: Is this the desired behavior or not? In other words, can I assume the action of bonding WSD/DOT from an owned account to a 3rd party account possible?**

### Please check the example:
 
here, I bond from my `IMAC-STASH` account to the `5Ca93Fn... `controller account: 

which is not owned by me. 

<img width="1123" alt="with3rdpartyAddress" src="https://user-images.githubusercontent.com/43375172/105483596-6ebfcc00-5ced-11eb-95e4-0d4b22a2e7a1.png">

As soon as I click outside the box, the address disappears, as shown below:
At this timing, if I click the box again, it will act as nothing was written, and it asks me to write an address.

<img width="1129" alt="blankbox" src="https://user-images.githubusercontent.com/43375172/105483633-7c755180-5ced-11eb-82c5-14ff6acc60f3.png">

However, if I "keep" the blank box, it will move on to the 2nd part with the setKeys, and once that's done it will successfully transmit the transaction. 
As you can see on this last screenshot, my IMAC-STASH is now staking using the `5Ca93Fn...` controller account 

<img width="1708" alt="succesfulBond-validator" src="https://user-images.githubusercontent.com/43375172/105483591-6cf60880-5ced-11eb-9504-3ef72bff097d.png">

**Comment by jacogr** [comment]
The apps UI expect you to own the keys. They can be anywhere - locally, extension, Ledger, Parity signer, etc - but it expect you to have access.

I do understand that for people who do know what they are doing, this is a less-than-optimal approach, but it protects the vast majority from shooting themselves in the foot.

The ability to submit via workaround is any issue, that loophole should be closed.

**Comment by HikaruG** [comment]
This was a bug after all, thank you for clearing my doubts.
