### ISSUE TITLE
polkadotjs app shows 'Unit' instead of 'Dot'

### ISSUE THREAD

**Issue by gallak87** [polkadot-js/apps#4481]
Hello, I recently created a wallet using polkadot.js.org + chrome extension. I transferred 492 DOT there a week ago.

Today I logged in, navigated to Accounts page and saw the UI say 4.92 Unit instead of 492 DOT.

![image](https://user-images.githubusercontent.com/7332016/105605648-39a29080-5d64-11eb-8079-03d0a7773f93.png)

I also saw an update to the extension thinking it would fix the UI, but after updating the Account page shows the same thing.

I also verified I am on the right network, Parity, and tried the other 2 networks Finality and Patrac Elara

Is this a UI bug? The only thing I really did today was create a new stash account and controller account in preparation for staking, literally have not done any other action.

**Comment by jiangfuyao** [comment]
Have the same issue.

**Comment by gallak87** [comment]
Looks like this might be the culprit:

https://github.com/polkadot-js/apps/pull/4480/files#diff-62e9c0691b2d40ea985f53bf31fecfebcd8f87fd9f9746bd6bb3d47e862b706fR25

I'll see if i have time today to investigate and put up a PR, unless someone else beats me to it.

**Comment by jacogr** [comment]
Fixed on the API side, the apps UI fix will be up shortly.

**Comment by jacogr** [comment]
Thanks for reporting, always appreciate any issues, even if it is a bug. The fix has been deployed.
