### ISSUE TITLE
On chain identity missing checkmark on UI

### ISSUE THREAD

**Issue by oyuksektepeli** [polkadot-js/apps#4506]
I verified my identity on KSM and DOT, bot seems to be correct on chain but in UI I don't see any green check mark as mentioned guide. 

I don't know if it is UI problem, of verification problem, but it seems verified regarding to below links. 

https://polkascan.io/polkadot/account/1H9BA63pcuGJD8sZY1LAkbVaAAyyMYEHfh2f7KYvfhb1GCh

https://kusama.polkastats.io/account/G87SQii6SEehaimLtAndKKYFK8ohypKNm7E1v8pZ1fsPYXZ

Polkadot
<img width="986" alt="image" src="https://user-images.githubusercontent.com/11184353/105924502-6c43d600-604f-11eb-9d3f-45ad19d589ef.png">

KSM
<img width="895" alt="image" src="https://user-images.githubusercontent.com/11184353/105924605-a90fcd00-604f-11eb-8ac0-0ff84a22a2e6.png">

**Comment by jacogr** [comment]
The Polkascan link also doesn't show verification.

The UI gets the information from the chain state, there are no judgements given. o the registrar has not verified. 

![image](https://user-images.githubusercontent.com/1424473/105953744-fa31b800-6073-11eb-83ce-79999e75c396.png)

**Comment by oyuksektepeli** [comment]
I got message form 3 channel, element, mail, twitter, I signed al of them, all of them returned ilke this identity verified. Registrar is W3F. What should i do?

**Comment by jacogr** [comment]
Please contact them. I'm not even sure who runs it at the W3F so cannot help at all as to "why".

**Comment by oyuksektepeli** [comment]
W3F is creator of Polkadot Project. Where shoul I ask?

**Comment by jacogr** [comment]
The Polkadot Watercooler channel on Element is where I have seen similar queries answered by the W3F. I believe that is also available/synced on Discord for non Element users.

**Comment by Swader** [comment]
Please come talk to us here https://app.element.io/#/room/#polkadot-watercooler:web3.foundation or via support@polkadot.network and we'll help you out.

**Comment by oyuksektepeli** [comment]
I had already come here from there with direction of someone , I am on both Discord and Element, I am stucked.I will write it to there again.
