### ISSUE TITLE
Unable to access Chain State page due to error

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/apps#451]
After running a local Substrate Node using either the `curl https://getsubstrate.io -sSf | sh` with the `substrate-node-new` shell script, or even running a local Substrate Node using the latest 'master' branch. If I then update to the latest 'next' branch and run Polkadot-JS Apps, if I go to http://localhost:3000/#/chainstate it returns the following error:
```
Modules.tsx Uncaught TypeError: Cannot read property 'now' of undefined
```

<img width="683" alt="screen shot 2018-11-16 at 12 20 32" src="https://user-images.githubusercontent.com/6226175/48618537-fedd8a80-e999-11e8-9464-c54c698bd312.png">

**Comment by ltfschoen** [comment]
It's because `timestamp` is undefined in [Line 36 of app-storage/src/Selection/Modules.tsx](https://github.com/polkadot-js/apps/blob/next/packages/app-storage/src/Selection/Modules.tsx#L36), `Api.storage.timestamp.now`, so it crashes when it tries to call `.now` of an undefined value

**Comment by ltfschoen** [comment]
I'm also getting errors when trying to access the Transfer and Extrinsics menu items

**Comment by jacogr** [comment]
It is a Substrate metadata bug, fixed in https://github.com/paritytech/substrate/pull/1129
