### ISSUE TITLE
"Send funds" should not default to an address book entry

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#4518]
I noticed that "Send funds" seems to be taking as default an account from the address book, possibly the lastest one added or used.

I find this behavior quite dangerous as default. This is definitely convenient for testing but I think we should remove this default.

While defaulting to an owned account would be ok (the user can always transfer back), defaulting to an external account can lead to sending funds to the wrong address.

**Comment by jacogr** [comment]
It default to the last of the type. 

So if you for instance selected a sender (which is only accounts) next time for the “account” type it will show the same. 

If you selected something with a “mixed type” (like in recipients) anywhere where the mix type occurs that will be the next. 

Unlikely to be adjusted, but will keep it open.

**Comment by chevdor** [comment]
This is definitely not super hot but I fear some users will "get burned" at some point.

**Comment by jacogr** [comment]
Closing, won't fix. Keeping it open assumes that people expect it to be done "now" and it is not the case. If burning, will look at PRs, but dropping it off the list of stuff "that will be done".
