### ISSUE TITLE
Api.tx.utility undefined

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#4532]
### Reproduce
This error happened trying to use the democracy pallet.

Connect to wss://democracy.kaki.dev

Create an account and get it some tokens. Confirm it appears fine on the account tab.
Submit a democracy proposal. Vote aye with conviction of at least 1x (so your tokens get locked)
After the referendum passes, go back to the accounts tab.
This error pops up:
<img width="1785" alt="Screenshot 2021-01-29 at 12 39 05" src="https://user-images.githubusercontent.com/16758383/106271126-53921680-622f-11eb-9411-2f5300f89510.png">

In Account.tsx:
```
function createClearDemocracyTx (api: ApiPromise, address: string, unlockableIds: BN[]): SubmittableExtrinsic<'promise'> {
  return api.tx.utility.batch(
    unlockableIds
      .map((id) => api.tx.democracy.removeVote(id))
      .concat(api.tx.democracy.unlock(address))
  );
}

**Comment by joelamouche** [comment]
Thanks @jacogr 
What does it mean that a chain doesn't have utility?

**Comment by jacogr** [comment]
https://github.com/paritytech/substrate/blob/master/bin/node/runtime/src/lib.rs#L1011
https://github.com/paritytech/substrate/blob/master/frame/utility/src/lib.rs
