### ISSUE TITLE
Unnominating, unbonding, and unstaking

### ISSUE THREAD

**Issue by protostar210** [polkadot-js/apps#4548]
Somehow by mistake when nominating, I got one that is Inactive.  I thought I unbonded my coins so I can renominate them but nothing seems to work. I can't do anything, all I get is "not enough funds" for whatever I try to do.  Please help me get my coins unjammed and restaked. I greatly appreciate any help offered.

**Comment by jacogr** [comment]
Not enough funds means you possible don’t have enough to pay for the transaction fees. You need to have some funds available to pay for fees. (In general you don’t want to bond all)

since re-nomination operates via the controller, ensure that you have some free funds on it.

**Comment by protostar210** [comment]
I have a DOT for fees in there.  Is that not enough?

**Comment by protostar210** [comment]
I've unbonded and if I could just unstake and restake I would be happy.

**Comment by jacogr** [comment]
You can rebond while the unbonding is still ongoing. (You account action via bond more will allow that, taking from the value being unbounded)

the existential deposit is 1 DOT, so that means that cannot be touched otherwise the account will be removed from the state. So you need to have 1 DOT + enough for fees.

**Comment by protostar210** [comment]
So put more DOT in with that 1 DOT and I will be able to choose another nominator?

**Comment by protostar210** [comment]
I have 24 DOT staked to an Inactive Nominator.  Can't I just unstake that and transfer some over?

**Comment by jacogr** [comment]
It becomes available to cover fees when full umbindend. Until then it is locked and not available for fees or transfers.

**Comment by protostar210** [comment]
I need to pay a fee to get it fully unbinded or how do I do that?

**Comment by protostar210** [comment]
Ahhh, I finally got it.  The staking is a little tricky lol. Thank you for your help.
