### ISSUE TITLE
1002: Verification Error: Runtime error: Execution failed:

### ISSUE THREAD

**Issue by wpank** [polkadot-js/apps#4554]
When trying to do a batch reward claim on Kusama I get the following:

```
utility.batch
1002: Verification Error: Runtime error: Execution failed: ApiError("Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature"): RuntimeApi, Execution failed: ApiError, \"Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature\
```

I suspect this may be an issue with either the rpc node itself, or some polkadot js runtime metadata of some sort.

**Comment by jacogr** [comment]
Quite weird. Did my claims straight after the end of the last era.

**Comment by wpank** [comment]
@jacogr were those claims for Polkadot or Kusama? On Kusama it looks like the 27 runtime is in. I think it might require some new types of some sort added.

**Comment by wpank** [comment]
Also these were the versions at the top right if it helps:

```
Parity Polkadot v0.8.27
api v3.6.5-9
apps v0.77.2-47
```

**Comment by wpank** [comment]
I get a different error when trying it against the Patract Elara node, which is on v0.8.26


> 1002: Verification Error: Execution: Wasm execution trapped: wasm trap: unreachable wasm backtrace: 0: 0x22c9 - <unknown>!rust_begin_unwind 1: 0x2016 - <unknown>!core::panicking::panic_fmt::h6aa2a8f84484b5f7 2: 0x18443a - <unknown>!TaggedTransactionQueue_validate_transaction : RuntimeApi, Execution: Wasm execution trapped: wasm trap: unreachable\nwasm backtrace:\n 0: 0x22c9 - <unknown>!rust_begin_unwind\n 1: 0x2016 - <unknown>!core::panicking::panic_fmt::h6aa2a8f84484b5f7\n 2: 0x18443a - <unknown>!TaggedTransactionQueue_va…

**Comment by jacogr** [comment]
I did both. Polkadot and Kusama. (And a number since the upgrade went in - no additional types for .27, only .28 changes Kusama)

**Comment by wpank** [comment]
Ah, sorry this looks to be my bad.

I was testing out some changes that might go into v0.8.28 and had injected some additional types. I just removed those, refreshed and now it works. Closing.
