### ISSUE TITLE
Unable to send custom balances

### ISSUE THREAD

**Issue by gregdhill** [polkadot-js/apps#4558]
The [BTC-Parachain](https://gitlab.com/interlay/btc-parachain) uses two instances of the `balances` pallet (`PolkaBTC` and `DOT`). When attempting to send `DOT` through the UI (on the accounts page) while connected to `rococo.polkabtc.io` I receive the following error: `TypeError: o.consts.balances is undefined`.

**Comment by jacogr** [comment]
Yes, see https://github.com/polkadot-js/apps/issues/4478

**Comment by jacogr** [comment]
Closing as duplicate on #4478.
