### ISSUE TITLE
Chain State component not rendering

### ISSUE THREAD

**Issue by al3mart** [polkadot-js/apps#4567]
Various users have reported the chain state tab not working in our UI.

I have checked with different network connections and this error is prompted every time 
`Uncaught error. Something went wrong with the query and rendering of this component. i.creator is undefined`

![image](https://user-images.githubusercontent.com/11448715/106506139-8fe0a380-64c9-11eb-8bf5-cc522eb69d59.png)

 Any feedback or early thoughts on it will be welcome, so I can message back with some _wip_ info :)

**Comment by jacogr** [comment]
Against which chain?
