### ISSUE TITLE
Failure when decoding as_multi

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#4568]
![image](https://user-images.githubusercontent.com/738724/106507926-01b9ec80-64cc-11eb-89a7-6c034a3a6ec6.png)

Visible at https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend-rpc.polkadot.io#/explorer/query/0xd33b6afd92883d17ae7f9d04d77da98d769c9dc23b22809a119a619cbee99e48

**Comment by jacogr** [comment]
Seems like we the upgrades on Westend does not actually match with the required numbers. The 48 runtime is supposed to match with the .28 runtime on Polkadot. Somewhere an upgrade was done that does not actually reflect the required outcome as for the runtime version (possible part of the number of rc's in the .28 version).

**Comment by chevdor** [comment]
The second sudo on Westend today was a 'setCode'.

![image](https://user-images.githubusercontent.com/738724/106511512-9fafb600-64d0-11eb-8f1c-d0fe4ab3d2a5.png)

see https://ipfs.io/ipns/westend.dotapps.io/#/explorer/query/4207800

**Comment by jacogr** [comment]
Ahhh, subscan doesn't show that one. Let me check.

**Comment by chevdor** [comment]
I have tested both 3.6.1 and 3.7.1 and I see issues in both. Atm 3.6.1 fails less but both version fail decoding some tx.

**Comment by chevdor** [comment]
If that helps, here is the blockhash: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend-rpc.polkadot.io#/explorer/query/0x29c47c735528342ce4dd3b7e018687f7706b9fc2424c5c30254d91090ae1be9f

**Comment by jacogr** [comment]
Well... https://github.com/polkadot-js/api/pull/3134 does not fix it. The UI does not seem to use the old registry with the correct types for the display decoding.
