### ISSUE TITLE
Error Unbonding Dot Tokens

### ISSUE THREAD

**Issue by tony101010** [polkadot-js/apps#4571]
I have a stash account were i have 57 dot tokens and a controller account that I deposited 1 dot token. After bonding the accounts I staked 50 tokens of the 57 in my stash account. Leaving 7 in the stash not bonded and 1 in the controller.  After reviewing  the process of staking, I decided I would rather not stake. So I proceeded to unbond my 50 tokens. I went through the steps and after clicking the button that says sign the transaction I get the following error: 

1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low

But I do have enough in both account to cover the fees.  Should I be getting this error? I don't thinks so but I am new at this so did I miss something?
Also if I were to do nothing and wait the 28 days that it says my coins are locked. Will they be available again at that point? Thanks for your help.

**Comment by jacogr** [comment]
The 1 DOT in the controller is enough for the existential deposit. However the balance may not fall below this. So you need 1 DOT + enough for fees to make the transaction.

**Comment by tony101010** [comment]
Thx, That worked.
