### ISSUE TITLE
Enhancement request: add a warning when bonding / nominating low number of DOT

### ISSUE THREAD

**Issue by laboon** [polkadot-js/apps#4575]
Currently the minimal nominator is ~ 104 DOT. Many people find themselves bonding and nominating with a small number of DOT, not getting rewards, then asking us for help. They then have to unbond and wait 28 days,

Can we add a small message or notification when bonding (as part of (+) Stash on https://polkadot.js.org/apps/#/staking/actions):

"Note: Nominators are sorted by amount of DOT staked and those with more DOT are prioritized. If you are nominating with a less than 150 DOT, you may not receive staking rewards."

Ideally, it would estimate what the lowest value nominator is in the set for this era, but that would undoubtedly be more complex and error-prone.  A static message would be easier to implement and provide

**Comment by laboon** [comment]
This could either be a static message or pop up if amount is less than 150.

**Comment by jacogr** [comment]
The calculation is in place for all chains. Static messages are never advisable, since it yo-yos up and down.

**Comment by krzysztof-jelski** [comment]
Would it make sense to link to https://polkaview.network/dot?

**Comment by jacogr** [comment]
The above actually has no information the target page doesn't calculate (bear in mind all calculated is not displayed, like the above). Additionally, the above is DOT-specific, links are only for general information, such as explorers that cater for a variety.

The calculation is there, it was actually implemented and then removed when the lowest DOT dropped to < 1 DOT. And then it climbed again.
