### ISSUE TITLE
TAssetBalance in assets pallet

### ISSUE THREAD

**Issue by modbrin** [polkadot-js/apps#4576]
Currently I can observe that assets pallet (actual pallet is custom, but name matches on several chains) resolves `Balance` type as `TAssetBalance` component. In other pallets `Balance` is still resolved normally. Problem is that `TAssetBalance` won't accept decimal places and results in 'cannot convert tx' error.

Can be reproduced e.g.: SORA-staging -> extrinsics -> assets

**Comment by jacogr** [comment]
The UI is not setup to input multiple Balance types at the moment, inclusive of the asset Balance. To input the value the full number representation is to be used. 

It will become a bit more generic after addresses the transfer and management of balances from multiple instances, at that point can have a "real Balance-like input with the correct decimals". At this point the Balance component is only aware of the main Balance type, not multiples where the representation is different.

**Comment by modbrin** [comment]
Does it mean that TAssetBalance will replace Balance component and currently takes input as full number with decimals? I was wondering more why it currently appears only for assets pallet but not the others, as I understand it should come to all balance 
inputs later?

Also I discovered that by default TAssetBalance is u64, that's why it was incompatible in tx decoding with u128 balance, the problem is resolved now.

**Comment by jacogr** [comment]
The base `TAssetBalance` type is `u64` in substrate, so yes, when changed, the type needs to reflect.

In theory, yes, where TAssetBalance is shown, it should be a Balance-like input. But like I mentioned above, this is unlikely to actually happen since the UI has no info on number of decimals on these. So it will stay a normal number input.

**Comment by modbrin** [comment]
Thanks for clarification.
