### ISSUE TITLE
Mnemonic/seed drop-down menu is hidden by the copy button

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#4610]
Not sure if this is on purpose, I just had an email support case of someone not able to import their account with a private key. I realized the dropdown is actually hidden behind the copy button (at least on the lastest FF).
![image](https://user-images.githubusercontent.com/33178835/107019418-eab41c80-67a1-11eb-9fc0-9e2d3b83c210.png)

**Comment by jacogr** [comment]
Clicking on the word "mnemonic" does work. But yes, the layout is weird here.

**Comment by Tbaut** [comment]
Thanks, absolutely, clicking the mnemonic was the trick, but users didn't find it out by themselves.
Wasn't sure if this was a trick to prevent users from using the private key directly
