### ISSUE TITLE
Staking return overflows for large validators stake difference

### ISSUE THREAD

**Issue by modbrin** [polkadot-js/apps#4614]
Encountered following error for staking page:
![image](https://user-images.githubusercontent.com/9750068/107030174-48a42c80-67c1-11eb-8ea6-73c3ea0851b5.png)

Looking into the problem I have found the calculation https://github.com/polkadot-js/apps/blob/edc2c7d84fb062633d9e2d5bcdd7b1de81089bca/packages/page-staking/src/useSortedTargets.ts#L175

Looks like it's because of difference between avgStaked and one lower stake which won't fit js number, with `* Million / Million` correction disabled it doesn't overflow:
![image](https://user-images.githubusercontent.com/9750068/107029901-db909700-67c0-11eb-9155-33eb84d1d8a2.png)

Should this be considered as an unlikely validators setup? Not sure at the moment how to approach the issue, if there are docs regarding return % calculation it would be helpful as well.

**Comment by jacogr** [comment]
It is unlikely, but still a bug. It should have proper protection for this. (Possibly just an upper-limit)
