### ISSUE TITLE
[Contracts] show unexpected character when the return type for contract call is `String`, may contain some decode error.

### ISSUE THREAD

**Issue by atenjin** [polkadot-js/apps#4621]
When using apps to call contract module, may have some error when handle the type of `String`.

e.g. the `ink!` contract like following:
```rust
#[ink::contract]
pub mod flipper {
    use ink_prelude::string::String;
    #[ink(storage)]
    pub struct Flipper {
        value: String,
    }

    impl Flipper {
        #[ink(constructor)]
        pub fn new(init_value: String) -> Self {
            Self { value: init_value }
        }
        #[ink(message)]
        pub fn get(&self) -> String {
            self.value.clone()
        }
// return same value wrapped by `Option<T>`
        #[ink(message)]
        pub fn get2(&self) -> Option<String> {
            Some(self.value.clone())
        }
    }
}
```
In this contract, we store a `String` value when init the contract, and get String value from the contract call `get()` and `get2()`, while the `get` call returns the `String` type directly, and the `get2()` call returns `Option<String>`.

From the apps, the `get` call returns value which is added an unexpected character before the source value, and the `get2()` returns a current value.

For example, when using the contract init with the parameter "qwe", and `get()` call returns "fqwe", which plus "f" character before "qwe", and `get2()` returns a current value "que":
![image](https://user-images.githubusercontent.com/5023721/107116720-305f0b00-68b0-11eb-8d5d-19b096770824.png)

First I think there may be some error in `ink!` , then I using [Europa](https://github.com/patractlabs/europa) to test this case, and find that in Europa log, the value which is set to the contract storage is current:
```bash
seal_set_storage((Some(0x0000000000000000000000000000000000000000000000000000000000000000), Some(0x0c717765))),
```
in this example, it's "0x0c717765", which is the encode value for "qwe" string .

and the returned value for contract call is :
for `get()`
```bash
seal_return((0, Some(0x0c717765))),
```
and for `get2()`
```bash
seal_return((0, Some(0x010c717765))),
```

we could notice the `get() ` return a right value, and the `get2()` return a right value too, which plus "0x01" before the source value for it's the encode value for `Option<...>`.

Thus I make sure this error is not from the ink! part, it's the decode error, or some component render error for "apps".

And the thing could notice that the type "Option<String>" is current, while the type "String" is wrong.

**Comment by jacogr** [comment]
The "f" itself is pretty weird, since not quite sure where it comes from (the compact-length encoding is certainly smaller than that)

Thanks for the reproduction here, will see what the UI itself does with the display.
