### ISSUE TITLE
1002: Verification Error: Litentry

### ISSUE THREAD

**Issue by robinbobbin** [polkadot-js/apps#4626]
I'm trying to send some token to the Litentry app account I just imported into polkadot.js.org, but this message is coming up:

1002: Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: No such variant in _enum MultiSignature")): RuntimeApi, Execution, ApiError, \"Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature\_

I'm new to the space, and I have no idea what to do. Anybody here who can help me?

Thanks a bunch.

**Comment by jacogr** [comment]
See https://polkadot.js.org/docs/api/FAQ#i-cannot-send-transactions-sending-yields-decoding-failures

The API/UI defaults to the Substrate master types, in this case it is `MultiAddress`. If the chain uses a different Address format, the type adjustments like above should be applied in settings -> developer
