### ISSUE TITLE
Don't display era info on unsigned txs

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#4630]
https://github.com/paritytech/substrate/issues/8063#issuecomment-775126693

**Comment by nahuseyoum** [comment]
Does this mean it is not possible to assign an era to unsigned transactions from the runtime?

**Comment by jacogr** [comment]
No, the validity is only for the tx pool. (I know you got that answer, just repeating it here for the future). Displaying "immortal" in this case is actually very misleading, so the UI does not handle the unsigned case correctly.
