### ISSUE TITLE
AccountIndex: Input too large. Found input with 33 bits, expected 32

### ISSUE THREAD

**Issue by tomusdrw** [polkadot-js/apps#4655]
I can't get the PJS apps UI to interact with a custom chain [see runtime definition](https://github.com/paritytech/parity-bridges-common/blob/43336fb80571ca554c526521e5f34af40c8b3c5c/bin/rialto/runtime/src/lib.rs#L162).

[Link to the chain with types definition](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss.rialto.brucke.link&types=eNp9VNtu2zAM%2FZXATy3gAFvWFkVXFFjbhwRrmyId%2BjIMhmIxtjZZ8nQZlgX595G2fIubvonkOeShSGkXPQopmb%2BVOv01ZzaPrqL5%2BcdZFPcDT75Yg8GQvzjDyEow6fSAMju%2FGAY6yqcu2RwYJ%2BcuKpkB5ZJAP9QQR6qh3%2BmiZKm7Hqm5QZR1zEFitHZvJoG%2FzghlRWqPY7jIwHah%2B9rcN4qDjYqlzizCXiENWurQwkFxc4gnJ3ESwD7osHR51Q2x%2FSVJ%2F%2BJdro1wAuxdzlQGIdr4twtOsDpmvxkBq2MtvACTrx8wFA7I0sqCsp4Ed%2BcaGXBoPRtYeeVEQbV7xh67mU6nqBsP%2FSkfzj1E21GPx48II3gGvJ9m3EEf1GYb718LbPZouFaV6lkte1GU2rgOuYvyhjPMEUcGfnthwCY%2FvXViI1LmhFYIXGtN1yRsshGKSfEPeOe1IkNfktctLUviXB82Wy1GO9EXqBaJdZNHZht9ELhnmBdcIqgOohec%2BCuQbAsGDUSnqcYp4RlbJMd3f%2Fl5cvaDTIWvQaVQuSvAA1M96xGsZRk8acS0Lzk4K9TJgscTdJ92%2Fq%2BwrVYfE9WiQkp8n5TmiibQT0sXr9aokBPwnjlGdFM30Lyekz4lngytttlT2n7JrEtSrTbCFMCTqugbNZfejYpK%2FBmQnIECg8cjZCpR4QykIP4ch2nJCeZVabx6R0qwGxUl20rN6OZC4Dk44mgDxL9leLkDaoPoPov9f3dG7Tg%3D)

How to reproduce: Developer -> Extrinsics -> select "bridgeMillau" pallet -> "haltOperations()"

![image](https://user-images.githubusercontent.com/581548/107662267-6a525780-6c8a-11eb-9b04-55dcf5f180e3.png)

Is there anything we are missing in Runtime configuration, or is it something that has more to do with the custom type definition?

Trying to debug right now, but also openining this for visibility. CC @hbulgarini

**Comment by jacogr** [comment]
where is the definition for `halt_operations`?

**Comment by tomusdrw** [comment]
[modules/substrate/src/lib.rs](https://github.com/paritytech/parity-bridges-common/blob/43336fb80571ca554c526521e5f34af40c8b3c5c/modules/substrate/src/lib.rs#L276)

**Comment by tomusdrw** [comment]
I'm assuming it's somehow related to signed extensions / extrinsic creation, but it's actually the same as in `substrate-node` afaict.

**Comment by jacogr** [comment]
This is the issue - `pub type Address = AccountId;` 

The API now defaults to `MultiAddress`, so you need specific `Address` overrides, see https://polkadot.js.org/docs/api/FAQ#i-cannot-send-transactions-sending-yields-decoding-failures for options, but basically it needs this -

```
{
  "Address": "AccountId",
  "LookupSource": "AccountId"
}
```

**Comment by tomusdrw** [comment]
Perfect! I was trying to change `Address` to `AccountId` earlier, but missed the `LookupSource`. Thanks!
