### ISSUE TITLE
WeightTooLow error on normal extrinsic call

### ISSUE THREAD

**Issue by thomivy** [polkadot-js/apps#4664]
I believe this may be an apps issue, as nothing has changed on chain..

On submitting a normal and common approval to an on-chain multisig call, the extrinsic fails and returns `WeightTooLow`, however, it was submitted with the default and recommended max_weight of 0, (per https://github.com/paritytech/substrate/blob/27c03f245e97d24cf33d57740d4111dd28731012/frame/multisig/src/lib.rs#L506 )

Failed Extrinsic:
https://edgeware.subscan.io/extrinsic/0x0fae795a923940d87a799ded8c54365ceb3f9a889350d0fcb588498bf22714b5

There is no clear reason why this extrinsic should fail, we're currently attempting to retry it with a 2 tril weight

**Comment by jacogr** [comment]
How are you submitting it?

**Comment by jacogr** [comment]
`ensure!(call.get_dispatch_info().weight <= max_weight, Error::<T>::WeightTooLow);`

It means the weight of the dispatched call neds to be less than the max_weight supplied. If you supply the max of 0, it will alway fail. Not sure where the "recommended max_weight of 0" comes from. The weight supplied needs to be more than the wrapped extrinsic.

The UI itself does the following for Multisig txs to ensure that the weight passed in is the same as the weight for the wrapped call - https://github.com/polkadot-js/apps/blob/master/packages/react-signer/src/TxSigned.tsx#L115 (it retrieves the weight from the wrapped extrinsic and passes that through)
