### ISSUE TITLE
Pros/cons of Ledger import to apps

### ISSUE THREAD

**Issue by carlmcconnel** [polkadot-js/apps#4668]
Hi.

I want to import my Ledger account to the app without the Ledger. Basically my main driver here is that I want to have a backup of the Ledger (apart from just the seed so it is portable elsewhere), really not looking forward to the day it gets lost.

So just want to confirm the steps -

- on the acount page, create an account
- select the Ledger ed-something option
- select the app I used to create
- account/index
- next, next & create?
- backup.

If I do this in ingognito for the JSON-only can I use it in other wallets? And extension?

**Comment by jacogr** [comment]
Your steps are fine. The "app" selection is just the app that you have on the Ledger, the "account/index" as selected when you attached the Ledger.

Importing this way is no different from adding any non-external account to the UI - basically it just uses the Ledger-compatible derivation paths to create the same seed for the account the Ledger would via the bip39+ed25519 Ledger-method.

I have followed a similar approach to backup securely (so I can restore) and tested it on the extension via the JSON import as well. (And it has been used by a couple of people to derive the same accounts as the Ledger would to unlock funds, i.e. they send some DOT to a KSM app, then added the account on Polkadot using the Kusama app type to get an account the apps UI can use to sign natively)

**Comment by kevinyates987** [comment]
I previously sent DOT to my KSM account, but I only had a KSM app on my Ledger so obviously cannot sign with it. I thusly followed the send recommendation. 

I removed the account from the UI, then added the account with the steps above while connected to Polkadot, basically my settings are to use using the "KSM app" and then the rest of the 0/0 to create the account. checked the address as I know it. And then sent out the DOT. 

Did it on my desktop instance, so didn't feel the need to wait for the unlock Ledger app, was very happy that the wallet has native support for these accounts.
