### ISSUE TITLE
Individual Account Payouts for Ledger Devices

### ISSUE THREAD

**Issue by phaymond** [polkadot-js/apps#4669]
I have multiple accounts managed by my Ledger device staking to a single validator. 

When I go to staking -> payouts -> and select any of the options by time, I get a utility batch error. Will said this is caused by a memory issue with Ledger. I think that's fine but now I can't claim any rewards because I can't individually claim for each account. Is there any way to fix this?

**Comment by jacogr** [comment]
Ledger needs to support batch - sadly the amount of overhead and complexity doing it as once-offs is not something that will be done in the UI. It comes with a huge maintenance costs. 

The good news is that apparently Ledger is close to having batch support. (It is not a memory limitation, but rather a complexity limitation)

**Comment by jacogr** [comment]
Also be aware that you can payout from any account. It does not need to be a stash or controller.

**Comment by phaymond** [comment]
Thanks that's helpful context. I'll try the payout from the other methods you suggested.

**Comment by phaymond** [comment]
> Also be aware that you can payout from any account. It does not need to be a stash or controller.

How do I do that? I see when I select payout I can choose a different account but no matter which account I choose, I still get the utility batch error every single time.

**Comment by jacogr** [comment]
It needs to be a non-Ledger account - the Ledger itself is throwing the batch errors.
