### ISSUE TITLE
Warning of low balance (reaping) when unbonding

### ISSUE THREAD

**Issue by jkell1980** [polkadot-js/apps#4677]
Same account is being used for stash and controller. Account is attempting to send a trx to unbond 40 DOT, has .93067 free and transferable. Fee is .012 yet js shows warning of "the account does not have enough funds to cover the transaction fees without dropping the balance below the account existential amount" warning, which doesn't seem like should apply here. 
![IMG-20210214-WA0002](https://user-images.githubusercontent.com/67924964/108133102-ff39c400-7081-11eb-81ff-f9d3501e1a92.jpg)
![IMG-20210214-WA0005](https://user-images.githubusercontent.com/67924964/108133117-06f96880-7082-11eb-881f-a6a886e3af33.jpg)

**Comment by jacogr** [comment]
This one is weird, the logic looks correct. However in the linked PR strengthened the checks a bit, will keep an eye.

**Comment by nymetva** [comment]
> This one is weird, the logic looks correct. However in the linked PR strengthened the checks a bit, will keep an eye.

Same issue again on this one. This guy is getting the warning too
![received_185845296677741](https://user-images.githubusercontent.com/67924964/111042051-57f24780-8409-11eb-912f-f5dd87e73537.jpeg)
