### ISSUE TITLE
Disabled links/buttons not viewable in dark mode.

### ISSUE THREAD

**Issue by gngchrs** [polkadot-js/apps#4684]
Noticed the disabled links/buttons cannot be viewed in dark mode but can be viewed in the light node.

This is in Network > Staking > Account Actions

<img width="421" alt="Screenshot 2021-02-17 at 14 32 14" src="https://user-images.githubusercontent.com/3910877/108211820-75473500-712d-11eb-8c17-193d71399951.png">

**Comment by jacogr** [comment]
Probably needs to align with accounts where it now drops all disable, i.e. they are not displayed when not available.
