### ISSUE TITLE
Sgc testnet issue!

### ISSUE THREAD

**Issue by Zombieliu** [polkadot-js/apps#4685]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fsubstrate.org.cn%3A4443#/explorer  Missing logo and topbar color but  external  list you can see the logo , it make me very confused !

**Comment by jacogr** [comment]
The issue is the following -

![image](https://user-images.githubusercontent.com/1424473/108221980-a4af6f00-7138-11eb-927d-2e5dffff8599.png)

Since the node name is "substrate Node", it would use that entry to match the logo on-chain.

**Comment by Zombieliu** [comment]
i see ! so, how to change this Substrate Node V2.0.1 ? chainspec? or Runtime config？ or polkadot js ???

**Comment by Zombieliu** [comment]
> The issue is the following -
> 
> ![image](https://user-images.githubusercontent.com/1424473/108221980-a4af6f00-7138-11eb-927d-2e5dffff8599.png)
> 
> Since the node name is "substrate Node", it would use that entry to match the logo on-chain.

i see ! so, how to change this Substrate Node V2.0.1 ? chainspec? or Runtime config？ or polkadot js ???

**Comment by jacogr** [comment]
That is the runtimeVersion, part of the node config. (spec_version, impl_version, spec_name - the spec name is above)

**Comment by Zombieliu** [comment]
> That is the runtimeVersion, part of the node config. (spec_version, impl_version, spec_name - the spec name is above)

OK ！ i get it Thanks !!

**Comment by jacogr** [comment]
Should also work if you add the chain name in here - https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/ui/logos/index.ts#L77

**Comment by jacogr** [comment]
The resolution is `chain name` then `spec name` then empty.

**Comment by Zombieliu** [comment]
> The resolution is `chain name` then `spec name` then empty.

ok i try to change

**Comment by Zombieliu** [comment]
> The resolution is `chain name` then `spec name` then empty.
ok https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fsubstrate.org.cn%3A4443#/explorer  i change the node commit and reset build  Thanks !!!
