### ISSUE TITLE
[BUG] Unable to retrieve the specified block details

### ISSUE THREAD

**Issue by freehere107** [polkadot-js/apps#4691]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend-rpc.polkadot.io#/explorer/query/4340021

**Comment by jacogr** [comment]
Cannot replicate?

![image](https://user-images.githubusercontent.com/1424473/108335754-95313400-71d3-11eb-9db2-e3e79c58e642.png)

**Comment by freehere107** [comment]
Thank you, maybe I reg wrong metadata
