### ISSUE TITLE
When a proxy mapping is not found, it tries to sign with a locked pair

### ISSUE THREAD

**Issue by rrtti** [polkadot-js/apps#4696]
Whenever using proxy to sign on tips, the following msg appears: 

<img width="319" alt="Screenshot 2021-02-18 at 16 40 05" src="https://user-images.githubusercontent.com/22815262/108383428-14415f00-720a-11eb-832d-ef7c63f878fd.png">

It seems no proxy is listed on the signer dialog, but it is when trying to sign other calls (voting on motions for example): it might have to do with the refactoring of the treasury pallet a few weeks ago. It seems proxy checks for the available proxy types and the logic doesn't detect tips.

**Comment by jacogr** [comment]
The signer see it is a proxy, but doesn't actually find an applicable proxy. So then it wrongly tries to get you to sign with the account it doesn't have a key for.

In these cases, it should just explicitly say "hey, I cannot do anything".

**Comment by jacogr** [comment]
Done.
