### ISSUE TITLE
Cannot withdraw all DOT to Binance DOT wallet

### ISSUE THREAD

**Issue by Maslach11** [polkadot-js/apps#4697]
![Untitled-1](https://user-images.githubusercontent.com/79285112/108423706-3c03e780-7249-11eb-9383-8f3d5e250917.jpg)
I can't  send all DOT to the Binance DOT wallet because of having such errors. 
Last time on this sreenshot I tried to send 25.
Help!

> The last option ensure the account is in keep-alive mode. Toggle it off -
> 
> ![image](https://user-images.githubusercontent.com/1424473/108424411-6b125d00-7239-11eb-81d8-db730c64016c.png)
> 
> Then use the toggle all button (visible after the above is toggled) to transfer the full balance.
> 
> Ensure you have no references on the account - votes, keys, identities. (UI will warn if you have references)

I found out what was it. To make a new wallet at Binance I should by some DOT there, right?
![изображение_2021-02-19_003654](https://user-images.githubusercontent.com/79285112/108424719-96517800-724a-11eb-8e74-a246246532c6.png)

**Comment by jacogr** [comment]
The last option -

![image](https://user-images.githubusercontent.com/1424473/108424411-6b125d00-7239-11eb-81d8-db730c64016c.png)

Then use the toggle all. 

Ensure you have no references on the account - votes, keys, identities. (UI will warn if you have references)

**Comment by Maslach11** [comment]
This is a Binance wallet by the way. I mean the latest picture I sent

**Comment by jacogr** [comment]
Sadly not a Binance user. 

I am assuming if they allow you to deposit to a DOT address they provide, you can send it there. (As far as I remember most exchanges allow you to deposit and they provide an address where you should deposit to so it reflects on your account)
