### ISSUE TITLE
SHA512 hash - Linux App image wrong value

### ISSUE THREAD

**Issue by AltCoiFish** [polkadot-js/apps#4713]
-$ cat latest-linux.yml

version: 0.81.1
files:
  - url: Polkadot-JS-Apps-0.81.1.AppImage
    sha512: oIMoSoy2SVTtHQLmuk9XXFHII50W/iahh8ShxqcKpJX/O3wk3Dc8uLRTzds3zo0ELEisse86VgN56PUPydJpaQ==
    size: 89387265
    blockMapSize: 94485
path: Polkadot-JS-Apps-0.81.1.AppImage
sha512: oIMoSoy2SVTtHQLmuk9XXFHII50W/iahh8ShxqcKpJX/O3wk3Dc8uLRTzds3zo0ELEisse86VgN56PUPydJpaQ==
releaseDate: '2021-02-22T10:00:15.479Z

based on the lastest version https://github.com/polkadot-js/apps/releases/tag/v0.81.1 is:

_$ sha512sum Polkadot-JS-Apps-0.81.1.AppImage 
a083284a8cb64954ed1d02e6ba4f575c51c8239d16fe26a187c4a1c6a70aa495ff3b7c24dc373cb8b453cddb37ce8d042c48acb1ef3a560379e8f50fc9d26969  Polkadot-JS-Apps-0.81.1.AppImage

**Comment by jacogr** [comment]
The sha512 is base64 encoded. When I put this in the JS console of the apps UI -

```js
console.log(
  util.u8aToHex(
    hashing.base64Decode(
      'oIMoSoy2SVTtHQLmuk9XXFHII50W/iahh8ShxqcKpJX/O3wk3Dc8uLRTzds3zo0ELEisse86VgN56PUPydJpaQ=='
    ),
    -1, false
  )
)
```

the output is -

`a083284a8cb64954ed1d02e6ba4f575c51c8239d16fe26a187c4a1c6a70aa495ff3b7c24dc373cb8b453cddb37ce8d042c48acb1ef3a560379e8f50fc9d26969`

**Comment by AltCoiFish** [comment]
`The sha512 is base64 encoded. When I put this in the JS console of the apps UI -`

Sounds reasonable, not sure if everyone did know the hash was  `base64` encoded, as I was used to get plain `sha2256` or `sha512` hashes on open-source software. 

Could we add the `base64` information in : `latest-linux.yml` ?

**Comment by AltCoiFish** [comment]
closing it, as this might be helpful for new user checking the `hash` values before downloading it.

**Comment by jacogr** [comment]
That is all part of the Electron packager and it uses that information to manage the auto-updates. So we cannot mess with the format there at all. As much as I also find it weird.

So there should be a one-liner that does sha -> bytes -> base64 that can be clearly documented for checks. Something along these lines -

`$ sha512sum Polkadot-JS-Apps-0.81.1.AppImage | xxd -r -p | base64`
