### ISSUE TITLE
Unable to create an Account via Ledger (Model Nano X)

### ISSUE THREAD

**Issue by Dub27** [polkadot-js/apps#4718]
Hi Support Team,
I recently bought a Nano X with the intention of connecting to Polkadot.
I tried setting up an Account and Polkadot isnt recognising the ledger either when i try on the website or via the extension.
Below are the steps which i took along with screenshots.
Would appreciate if you could provide some feedback. 

Step 1: - Connect Ledger Nano X to Laptop
Step 2: - Installed Polkadot v5.23 on Ledger Live 
Step 3: - Went https://polkadot.js.org/apps/#/explorer    and installed Polkadot{.js} extension for Chrome
Step 4: - Went to Settings and ensured hardware connection was setup for "Ledger via WebUSB"
Step 5: - Went to Accounts & selected "Added Via Ledger"
Step 6:-  Created Account Name "a" and set account type & index to 0 - select save
Step 7:- Once save is selected, it just remains loading (see screenshot below - #7)
Step 8:- Try to create Account via extension - click on extension and select "+" and connect via ledger
Step 9:- Select network Polkadot Relay Chain and select save - same issue - remains in load phase (see screenshot below - #9)

#2
![image](https://user-images.githubusercontent.com/79520486/108848860-6a7f1b00-75d9-11eb-8678-10010d3b6f2f.png)
#4
![image](https://user-images.githubusercontent.com/79520486/108849607-3d7f3800-75da-11eb-837c-33991958554e.png)
#6
![image](https://user-images.githubusercontent.com/79520486/108849650-51c33500-75da-11eb-9de9-ac4119ae4a8f.png)
#7
![image](https://user-images.githubusercontent.com/79520486/108849870-9058ef80-75da-11eb-8a36-55a8b6ce1d41.png)
#8 
![image](https://user-images.githubusercontent.com/79520486/108850030-c39b7e80-75da-11eb-902b-569686b4aea2.png)
#9
![image](https://user-images.githubusercontent.com/79520486/108850064-d1e99a80-75da-11eb-8497-00a0fc98a2d5.png)

Thanks,
R

**Comment by jacogr** [comment]
Which OS? Is your Ledger Live app closed when you try to add it?

**Comment by Dub27** [comment]
Lol - ok working now - in the ledger i had to double click on the polkadot for it to save polkadot ready

**Comment by Dub27** [comment]
i can see the account now in Accounts - literally spent hours over the weekend trying to work it out. Thanks for your help!

**Comment by jacogr** [comment]
Phew. Weird one. Would not have thought that - only have the S, but not having the app open does show an error.
