### ISSUE TITLE
Overflow on tokenSymbol with 5 uppercase characters

### ISSUE THREAD

**Issue by ZentaChainAdmin** [polkadot-js/apps#4720]
Cannot catch the length of chain-Id from JSON file. It overrides the M = million specification. Works well with 4 and 3 symbols.

**Comment by jacogr** [comment]
I am not sure I understand the issue here. The properties has the ss58, token and decimals. 

What configuration are you referring to and what changes?

**Comment by ZentaChainAdmin** [comment]
Yes, I am referring to the  properties I set it as a ss58 and also the decimals. If the "tokenSymbol" has a length of 5 symbols like "CHAIN" the app application drops the M Symbol which is at the beginning.

**Comment by jacogr** [comment]
Unlikely to be fixed, since it has not been not been an issue that has affected more than a single. 

PRs are however welcome.

Will keep this open if somebody wants to pick it up.

**Comment by ZentaChainAdmin** [comment]
I will now close this it was due to by me and the properties section.
