### ISSUE TITLE
Remove "other stake" account list from Staking Overview and load individually on click expand

### ISSUE THREAD

**Issue by rossbulat** [polkadot-js/apps#4727]
The staking section is currently extremely slow and lagging in the browser due to the huge amount of data being requested and processed.

Proposal: Remove the "other stake" account list and have them load on an individual basis when a user clicks to expand.

**Comment by jacogr** [comment]
Own and other values are from the same storage entry, so removing the display adds nothing.

Overhead is actually from commission & identities for the large lists. (Since you need to make at least 2 queries one each to retrieve)

**Comment by rossbulat** [comment]
Your vague comment makes little sense, and you are very incorrect in thinking removing a sheer amount of DOM elements will not speed up performance of the web page.

It is evident that the contributors of this repo are not designers, as has been the case for multiple years. We are now seeing this lack of skill reflect in the usability of the app, with staking almost unusable.

**Comment by jacogr** [comment]
Thanks fo the comment - however, you are incorrect in your point. You are correct it is slow, but you are looking in the wrong places.
