### ISSUE TITLE
FATAL: Unable to initialize the API: createType(BlockLength):: Cannot construct unknown type BlockLength

### ISSUE THREAD

**Issue by polkajunkie** [polkadot-js/apps#4729]
I made this DOT wallet a week ago sinse my PLASM were there and everything was fine as I deposited my DOT into the wallet.
I also tried making a KSM wallet but kept receiving the error (FATAL: Unable to initialize the API: create Type (BlockLength):: Cannot construct unknown type BlockLength) so I just left my KSM where they were but tonight I went to add somore DOT into ny new wallet but know I can't access my new wallet as I'm now receiving this same erro as with the KSM attempt,
(FATAL: Unable to initialize the API: createType(BlockLength):: Cannot construct unknown type BlockLength)
Iv'e never been on github and don't know what to do now!
Can anyone please help this polkajunkie out?
God bless

**Comment by polkajunkie** [comment]
I can't even see my DOT balance but have no problem viewing my PLASM balance.

**Comment by jacogr** [comment]
What are you running? And where?

**Comment by polkajunkie** [comment]
I feel retarded in this form because I can't understand 99% of what you guys are talking about, way over my head but I'll try to explain. I'm running windows 10 if thats what you were wondering and yes it's  https://polkadot.js.org/apps/  the same ( are repo and wallet kinda the same thing?) place I'm storing my PLASM tokens from their LockDrop. I thought since I'm storing my PLASM here I may as well transfer my DOT as well and they transferred fine and my DOT wallet worked great for the entire day last week when I made it! Ive never had any problems with the PLASM wallet but a week later I just cant open the DOT or KSM for that matter! I'm sorry I don't know the lingo and hope you understand what my issue is! When you say repo, is that the proper word to use instead of a wallet?
this is my very first day on github,

**Comment by polkajunkie** [comment]
Hey thanks a million, I copied and paste the link you just sent me and restored my wallet via Jason file and it opened so I now regained access to my DOTS,
THANKS AGAIN FOR THE HELP!!!!!
God bless!!!!

**Comment by jacogr** [comment]
The problem is that if you use the https://apps.plasmnet.io/ link - that is way outdated, so it doesn't have any of the APIs to deal with the current Polkadot or Kusama. 

(It only works with their chain, e.g. Plasm, while the polkadot.js.org is actively updated to all the latest Substrate types)

PS: Welcome to GH :)
