### ISSUE TITLE
Add message that the extension protects you from potential phishing scams

### ISSUE THREAD

**Issue by anjaw3f** [polkadot-js/apps#4735]
Could we add a message on polkadot.js that the extension helps protect users from scams, even if they don't manager their accounts with it? 

Right now a message is displayed that sort of says "Hey you've got the extension installed, but you're not actually using it" if they have no accounts set up in it. We could use this space to add "Well done, you're gonna get an alert every time you're accessing a potential phishing site. This is a great way to protect yourself from scams!" 

The extension is very useful in scam protection and we could promote it more this way. Maybe we could even prompt users to install it, if they haven't already?

**Comment by jacogr** [comment]
It does prompt when not installed - so it would make sense to have the message in both places.
