### ISSUE TITLE
Account Send Issues

### ISSUE THREAD

**Issue by cage17wlc** [polkadot-js/apps#4737]
Hello,

I have tried at least 3 times to send 1 DOT between my two Polkadot accounts. I have signed for these transactions, but the balance never shows that the 1 DOT is in the account I sent it to. Please help me resolve this issue.

Thank You,
Camille

**Comment by jacogr** [comment]
Which errors are displayed? Bear in mind that to create an account, the transferred amount needs to be > existential deposit (and the sending account needs to have at least existential deposit, funds for the fees and the amount transferred)

(existential deposit is currently 1 DOT on Polkadot)

**Comment by cage17wlc** [comment]
Thank you.  The problem has been resolved.
