### ISSUE TITLE
I can't connect my Ledger Nano X to https://polkadot.js.org/apps

### ISSUE THREAD

**Issue by lumierephoto** [polkadot-js/apps#4738]
A couple of months ago I decided to store and stake my Polkadot on the https://polkadot.js.org/apps.

I just logged in and I noticed that I cannot connect my Ledger and I don't have access to my $DOT tokens at the moment which is not good. 

How do I get the app to recognize my Ledger? There must've been some changes that were made on the app side as to why I cannot see my Ledger account.

All of the firmware, software and apps have been updated in Ledger Live.

**Comment by jacogr** [comment]
There has been no Ledger connection changes in the UI, so you can rule that out. 

Don’t have a Nano myself, but possible issues -

- having the Ledger Live open (between the browser and that apps apparently there is only 1 allowed at a time)
- not opening the Kusama/Polkadot/Dock app on the device itself 
- not having selected enabling Ledger in the settings (ie. The option it available)
- having the extension and apps UI both connected to the Ledger (Same as the first issue)
- 
Apart from that cannot give additional pointers as to “why” it may not be a ale or cannot connect

**Comment by lumierephoto** [comment]
• I restarted my computer and tried again with Ledger Live turned off. Still unable to connect
• The Polkadot app is open on my Ledger
• Ledger is enabled in the settings but I'm no longer getting the pop up for connecting my Ledger when I first connect
• I'm not sure how to disconnect the extension as I thought they are supposed to work in tandem with my wallet. I don't want to remove the extension at this point. 

If you aren't that knowledgeable about the Ledger capabilities with the Polkadot app, who can I contact for support? Twitter?

**Comment by lumierephoto** [comment]
<img width="2149" alt="Screen Shot 2021-02-27 at 2 40 10 PM" src="https://user-images.githubusercontent.com/981541/109399934-746f8980-790b-11eb-8205-e10b51598258.png">

**Comment by jacogr** [comment]
There is no auto popup to connect. 

In the accounts page there is a “add ledger” button on the top bar. That will query the Ledger and allow you to add the Ledger account.

**Comment by lumierephoto** [comment]
OK, that was it. I was supposed to add it again. I don't remember having to do that last time. Now I know.
