### ISSUE TITLE
Sgc chain types show issue

### ISSUE THREAD

**Issue by Zombieliu** [polkadot-js/apps#4744]
> 

I just updated the chain types of SGC 

https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/sgc.ts

some people show

![image](https://user-images.githubusercontent.com/50917820/109421698-55f4b580-7a13-11eb-822f-3ad7fcc51427.png)

so, how to solve this problem? 

Is the problem due to a delayed update submission? or other reasons?

**Comment by jacogr** [comment]
It is not a "delayed update" - if you run locally, you will see the same issue.

You `spec_name`, which the types match on, doesn't match `sgc` as defined in https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/index.ts#L113 - it should correctly match the `spec_name` to the types

See 

![image](https://user-images.githubusercontent.com/1424473/109422349-756fec00-79db-11eb-8dac-3074ff66d2f3.png)

**Comment by Zombieliu** [comment]
oh oh oh so  i 

> It is not a "delayed update" - if you run locally, you will see the same issue.
> 
> You `specName`, which the types match on, doesn't match `sgc` as defined in https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/index.ts#L113 - it should correctly match the `specName` to the types
> 
> See
> 
> ![image](https://user-images.githubusercontent.com/1424473/109422349-756fec00-79db-11eb-8dac-3074ff66d2f3.png)

oh oh  So that's it Thanks

**Comment by Zombieliu** [comment]
Thanks you can close this issue . all solve
