### ISSUE TITLE
Polkadot/substrate portal blank screen

### ISSUE THREAD

**Issue by ebron85** [polkadot-js/apps#4748]
Please somebody help this newbie out. Every time I try to load the page up it remains blank. I am using Chrome it says its up to date. I am on a macbook pro. I have sent stock to this account and cant even get to the portal to see if they have arrived!

Thankyou 

![Screen Shot 2021-02-28 at 17 15 44](https://user-images.githubusercontent.com/79803111/109427987-ca682e00-79ec-11eb-9f7e-8904698c438d.png)

![Screen Shot 2021-02-28 at 17 15 05](https://user-images.githubusercontent.com/79803111/109428000-d81db380-79ec-11eb-8ddc-540416b593da.png)

**Comment by ebron85** [comment]
also the same thing is happening with my KEPLR account so I am assuming it is app related

**Comment by jacogr** [comment]
Have not seen that before, and it works (on chrome & FF) for me at the same URL.

Which version of Chrome do you have? (On Version 88.0.4324.192 here, checked via Chrome -> About Google Chrome)
