### ISSUE TITLE
Fix eth private key derivation

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#4752]
Currently, when adding an account from private key in the apps, the key is used as seed to derive a pair using the hd. Instead, it should just create a pair from this private key using keyring.addFromSeed ad tested in https://github.com/polkadot-js/common/pull/909
Please let me know how to add this function in ui-keyring, because it is not exposed yet.

**Comment by jacogr** [comment]
The ui-kering is only to be used with `addFromUri` -

- it can take a mnemonic
- it can take a hex seed

In both cases there is a separate path that is applied for the conversion, see https://github.com/polkadot-js/common/blob/master/packages/keyring/src/keyring.ts#L179-L181

**Comment by joelamouche** [comment]
solved
