### ISSUE TITLE
set validator preferences / reward commission percentage

### ISSUE THREAD

**Issue by Spindler360** [polkadot-js/apps#4768]
Hello geniuses,
according to the description at https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/staking/actions, numbers between 0-100 are allowed. 
However, no decimal numbers such as 0.9 can be entered. 
When I enter 1, I suddenly have 100%. Is this a bug or how can we set below 1%?

Can you please check if this is a bug? Thanks a lot :)

**Comment by jacogr** [comment]
The input there does not accept decimals.

**Comment by jacogr** [comment]
On the first point via the extrinsic tab, select account, staking, set prefs, then for 0.9% enter 9000000, e.g

![image](https://user-images.githubusercontent.com/1424473/109863101-85006680-7c61-11eb-96b5-7da6f1b6833a.png)

**Comment by Spindler360** [comment]
I didn't know the Extrinics page yet. But I found it quickly and got through it well. Thank you very much for your explanation. It helped very well. Cheers my unknown friend🍻
