### ISSUE TITLE
Can't install dependencies on master

### ISSUE THREAD

**Issue by statictype** [polkadot-js/apps#4770]
I cloned the `apps` and `api` repos today for the first time and did a `yarn` in the project root. The yarn installation failed with errors and the node_modules folder was not created. I checked out older release tags and i could do the install, it only happens on master and branches from master.

I have node v14.15.5 and latest yarn. Other colleagues could not reproduce with the same setup.

![Screenshot 2021-03-04 at 15 46 16](https://user-images.githubusercontent.com/42985153/109985298-e6c5dc80-7d04-11eb-95b1-6b9ba3d557d2.png)

Any help would be much appreciated!

**Comment by jacogr** [comment]
Outside of the repos run „yarn —version“ and then do the same inside on of the repos. 

Inside it should be 2.4.1 (yarn berry 2.4.0 had the above issue, hence the update that was applied)

**Comment by statictype** [comment]
For some reason, volta didn't apply the latest version no matter which folder i was trying to set the yarn version.
After uninstalling volta and getting the latest yarn, it works.
Thanks!

**Comment by jacogr** [comment]
yarn berry explicitly actually explicitly configures the version in the repo - 

- yarn config: https://github.com/polkadot-js/apps/blob/master/.yarnrc.yml
- actual 2.4.1: https://github.com/polkadot-js/apps/tree/master/.yarn/releases 

So in principle, everybody installing inside the repo are executing the exact same code, from the repo - no mater what their global config says. So in my case, my global yarn is 1.22.x, however inside the repos it uses the checked-in version as specified in the config file. 

Any tool that ignores/overrides that is doing the wrong thing :(
