### ISSUE TITLE
apps do not work for `sc_consensus_manual_seal` node

### ISSUE THREAD

**Issue by atenjin** [polkadot-js/apps#4776]
For `sc_consensus_manual_seal` node, the block is only packed when receive an extrinsic. But when I wanna use apps to send first extrinsic for a `manual_seal` node (for example  https://github.com/substrate-developer-hub/recipes.git)

I guess apps try to fetch the prev hash for genesis block, then it would cause this error. Thus it could meet for any nodes before the first block not produced.

replay:
```bash
git clone  https://github.com/substrate-developer-hub/recipes.git
WASM_BUILD_TOOLCHAIN=nightly-2020-10-06 cargo build
./target/debug/kitchen-node --tmp --dev
```
types:
```json
{
  "BufferIndex": "u8"
}
```

then apps shows:
![image](https://user-images.githubusercontent.com/5023721/110092401-87370200-7dd4-11eb-8d8e-77e2cbdb5027.png)

**Comment by jacogr** [comment]
Yes, sadly untested - I think I know what can cause this in some cases, especially genesis, so will make a PR to update that, but won't be able to test myself (as it stands have enough nodes compiling).

**Comment by zzcwoshizz** [comment]
This maybe this commit. [https://github.com/polkadot-js/api/commit/e117619e34b505f95ab03f08ef4d1b92c45186f9#diff-0d0a7a9a15d8d00f45682dda390d53cd3f754c6c35a7e0ba47de673a36e00795](https://github.com/polkadot-js/api/commit/e117619e34b505f95ab03f08ef4d1b92c45186f9#diff-0d0a7a9a15d8d00f45682dda390d53cd3f754c6c35a7e0ba47de673a36e00795)

**Comment by jacogr** [comment]
Yeap, that is the one I'm adjusting

**Comment by jacogr** [comment]
Can re-open if still an issue, but hopefully the above solves it.

**Comment by atenjin** [comment]
> Can re-open if still an issue, but hopefully the above solves it.

yes it has fixed, thanks jaco
