### ISSUE TITLE
Not able to connect UI with hosted node

### ISSUE THREAD

**Issue by ayushmishra2005** [polkadot-js/apps#4779]
I am following this https://wiki.polkadot.network/docs/en/maintain-wss to connect https://polkadot.js.org/apps with my node, running on a EC2 instance. I followed every steps, which are mentioned here https://wiki.polkadot.network/docs/en/maintain-wss

Even I am using same example https://wiki.polkadot.network/docs/en/maintain-wss#set-up-a-node

I am getting this `Waiting to make a connection to the remote endpoint and finishing API initialization.`

![image](https://user-images.githubusercontent.com/1575561/110204997-1ce99480-7e9c-11eb-812d-e86ea0e8471b.png)

Please guide me what I am missing here

**Comment by jacogr** [comment]
Since I have not setup these myself, I really cannot comment on the step that is missing. The wss + 9944 looks suspect though, generally in the guides the secure port is 443, but you override it here to 9944 which is the insecure port. (The last link also sets to 443, i.e. the wss port default)

**Comment by ayushmishra2005** [comment]
@jacogr I just checked it is working fine on Firefox. I don't know why it is not working on google chrome.

**Comment by ltfschoen** [comment]
It may be related to this https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org/$161254251955585Bcosj:matrix.parity.io?via=matrix.parity.io&via=matrix.org&via=corepaper.org and this link https://stackoverflow.com/questions/45572440/how-to-access-an-insecure-websocket-from-a-secure-website
I had a similar issue trying to connect using Brave but it worked with Chrome

**Comment by ayushmishra2005** [comment]
Thanks for your reply.
