### ISSUE TITLE
Strange behaviour with numeric values

### ISSUE THREAD

**Issue by ppoliani** [polkadot-js/apps#4780]
I have recently forked the Polkadot repo and integrated the Crowdloan module into the Kusama runtime. I have then used polkadot-launch to run a local network and test the module.

I used the apps UI to create and contribute to a new fund.

<img width="1436" alt="Screenshot 2021-03-06 at 13 07 56" src="https://user-images.githubusercontent.com/1389619/110207673-01bb5c80-7e7d-11eb-977e-edb09f63f289.png">

However, when I query the details of the fund I see slightly different values

<img width="1440" alt="Screenshot 2021-03-06 at 13 07 21" src="https://user-images.githubusercontent.com/1389619/110207686-0ed84b80-7e7d-11eb-9232-8e04d882685d.png">

It looks like all numbers are multiplied by 256.

I'm really struggling to understand what I'm missing here

**Comment by laboon** [comment]
This looks to be a runtime issue, not ann issue with Polkadot-JS.

**Comment by ppoliani** [comment]
Hey @laboon, thanks for your response. The thing is that I'm using the latest `crowdload.rs` module and looking into the code I can't see anything that could hint about that behaviour. 

Do you reckon I should move this issue to the polkadot repo?

**Comment by laboon** [comment]
@ppoliani Yes, that's probably the correct place for it. Good luck, hope they can help figure it out!

**Comment by ppoliani** [comment]
@jacogr could you suggest how I could change the types manually?

**Comment by jacogr** [comment]
Settings -> Developer and add the specific types for your chain. 

(The API types in the apps UI is tracking the next-generation unmerged module since yesterday, so for anything in master or older overrides are to be used)
