### ISSUE TITLE
Blocked validators should not show up as nomination targets

### ISSUE THREAD

**Issue by dvdplm** [polkadot-js/apps#4798]
In the Staking/Targets screen the list of possible nomination targets should probably not include validators that have blocked themselves (nominating them leads to `staking.BadTarget`, leaving users to go through each validator and check their "blocked" status).

As I write this, the most profitable validator is one [`DISC-SOFT-05`](https://kusama.subscan.io/validator/Ht7Y3D5zKnmWSsEuwdLwb9z5n355fGDa5K1Qiuue9KSaSkS?tab=era) and it is blocked.

![image](https://user-images.githubusercontent.com/18515/110541216-57af2f00-811f-11eb-9236-e01ca58cb11a.png)

**Comment by jacogr** [comment]
Yeap, aware of this hole - was hoping there would be time to fi it before people run into it (fixing won't be soon)

**Comment by jacogr** [comment]
It is along with the kicking of nominators in the current version of staking. Basically the validator has more control about letting new joiners in and keeping the status quo.

It is not very visible atm, have not seen many questions, but it will probably raise some eyebrows along the way.
