### ISSUE TITLE
Extrinsics: Every input file is error

### ISSUE THREAD

**Issue by jiangfuyao** [polkadot-js/apps#480]
https://polkadot.js.org/apps/next/#/extrinsics
> Every input files is error! 

**such as** :  contract => create/call,    
consensus =>r emark(remark), 
councilMotions => propose(threshold, proposal), 
and more...

![_ _20181204153923](https://user-images.githubusercontent.com/34789555/49426695-435f8780-f7dc-11e8-97f1-672792118dcd.png)

**But** : Not input files, just input the 0x00, is ok.

**Comment by jacogr** [comment]
What does the node report in these cases? Is this behaviour new, i.e. something that previously worked does not now?

**Comment by jiangfuyao** [comment]
It's my bbq testnet balance not enough.
**so**: need the result echo: The balance is not enough.
And, when have to set extrinsics, output the gas.
