### ISSUE TITLE
Custom types error in PolkaBTC explorer

### ISSUE THREAD

**Issue by savudani8** [polkadot-js/apps#4804]
After having released a new parachain version, the PolkaBTC explorer fails to open and throws `FATAL: Unable to initialize the API: createType(DOT):: Cannot construct unknown type DOT`. (https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbeta.polkabtc.io%2Fapi%2Fparachain#/explorer)

The only relevant thing that changed in the new version is the `spec_version`. Might that be the problem?

**Comment by jacogr** [comment]
In this case it is dependent on the team to update the definitions - https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/polkabtc.ts#L6

Took  quick look and no update for that package available atm.

**Comment by savudani8** [comment]
The type definitions haven't changed, only the `spec_version` did. Does that need to be included in the types you linked above?

**Comment by jacogr** [comment]
Ahhh, ok, the types has a specific limit set there, so it seems to only apply up to version 2 - https://github.com/interlay/polkabtc-types/blob/master/definitions.json#L6

Anything outside of that range is not covered.

**Comment by savudani8** [comment]
Thanks! That fixed it

**Comment by jacogr** [comment]
Closed in #4806
