### ISSUE TITLE
Propose to always show a highlighted badge in a main menu items that has any highlighted badges in its sub-menu items

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/apps#4814]
Proposed changes are highlighted in **bold** text below. I've written some (perhaps unnecessary) context about it all too.

In the first screenshot below when "Settings" main menu is clicked, it displays the selected menu "Settings" on the far left, and shows that its submenu item "Metadata" has a highlighted (1) badge, because I have to click "Update metadata" for it to go away, and that works correctly.
![Screen Shot 2021-03-10 at 8 57 45 pm](https://user-images.githubusercontent.com/6226175/110689863-52dd9e80-8237-11eb-973b-476815102cc1.png)

But it doesn't reveal whether in any of the other main menus their sub-menus that have a highlighted (?) badge, to prompt the user to take action. 
In this instance, the Governance > "Democracy" sub-menu item has a highlighted badge of (2), indicating there are two actions outstanding, but they can't tell instantly (as if it were a push notification that hasn't been pushed up enough levels).
 
Instead they have to first hover over each of the main menus to reveal if any of their associated sub-menus have a highlighted (?) badge (which is easy to do, but users may want the instant convenience of seeing whether there are any outstanding actions at all when they open polkadot.js.org/apps and connected to a chain in their browser tab. 

In this second screenshot, we've hovered over the "Governance" main menu item to reveal that the  "Democracy" submenu item has a highlighted badge of (2):
![Screen Shot 2021-03-10 at 8 58 20 pm](https://user-images.githubusercontent.com/6226175/110689870-553ff880-8237-11eb-9f5c-2ebd187b7ece.png)

**But I think it could better be shown as shown in the following screenshot with the highlighted badge shown next to "Governance" main menu too**, and to be consistent with the "Settings" main menu **it could be better to always have that highlighted (2) badge, even if one of its sub-menus have been selected and are active.**. Sure, the "Settings" main menu doesn't have a sub-menu, but I still think this could be an improvement. What do you think?
![Screen Shot 2021-03-10 at 9 16 18 pm](https://user-images.githubusercontent.com/6226175/110692086-13fd1800-823a-11eb-9c29-69190b72f61f.png)

**So when the user clicks the "Democracy" sub-menu item as shown below, I think it could be better if the "Governance" main menu item still showed the highlighted badge (2) as sketched in red in the previous screenshot**

Then if I select the "Democracy" sub-menu item it becomes active on the left, however, it doesn't show any highlighted badge for the "Democracy overview" sub-menu tab, but I think is fine because it's clear that there are 2x things going on if a user with basic understanding bothers to look at the contents of the page (i.e. 1x proposal no. 26, and 1x referenda no. 27 are open), and we don't want to pollute the page with too many unnecessary highlighted badges.

![Screen Shot 2021-03-10 at 9 28 17 pm](https://user-images.githubusercontent.com/6226175/110693289-62f77d00-823b-11eb-9e84-804879239af0.png)

If you then click the "Dispatch" sub-menu, it correctly shows that there is 1x item (one out of the two actions) in the dispatch queue for proposal 26, as shown below.
![Screen Shot 2021-03-10 at 9 26 12 pm](https://user-images.githubusercontent.com/6226175/110693032-1d3ab480-823b-11eb-87d0-d10def0a5a56.png)

**Comment by jacogr** [comment]
Thanks for the breakdown, however...

This is completely unlikely to be done, this is not a priority and not going to pull it into the nav redesign either. The focus is on functionality with the upcoming launches, not UX. (And this won't change for a long while)
