### ISSUE TITLE
cant transfer

### ISSUE THREAD

**Issue by chicco13** [polkadot-js/apps#4816]
ive been trying for 3 months to transfer my dot into another account please somebody help me

<img width="1260" alt="Screen Shot 2021-03-11 at 9 19 36 am" src="https://user-images.githubusercontent.com/33196679/110711277-ff754b80-824a-11eb-8215-577972405515.png">
<img width="1237" alt="Screen Shot 2021-03-11 at 9 18 11 am" src="https://user-images.githubusercontent.com/33196679/110711292-04d29600-824b-11eb-8893-da1984d6c47d.png">
<img width="371" alt="Screen Shot 2021-03-11 at 9 16 40 am" src="https://user-images.githubusercontent.com/33196679/110711299-08feb380-824b-11eb-95c4-3ae3349fe757.png">
<img width="1119" alt="Screen Shot 2020-12-12 at 2 01 30 pm" src="https://user-images.githubusercontent.com/33196679/110711309-0ef49480-824b-11eb-8fe7-897f617120f6.png">

**Comment by jacogr** [comment]
That error is from Enzyme itself. I would suggest logging with them as to why it is failing - in both cases the error messages are as returned from that extension.

**Comment by chicco13** [comment]
Hi thanks for responding i have left so many emails on their website and they have not responded to any of them

**Comment by jacogr** [comment]
Sadly don’t know the team involved there. 

If you have the mnemonic you can try additing it to either the polkadot-JS extension or the apps UI directly (assuming you disable Enzyme). If the address matches on add the funds will be transferable.
