### ISSUE TITLE
AdBlock blocked connection to ReAlis Network

### ISSUE THREAD

**Issue by Daelon02** [polkadot-js/apps#4817]
Hello everyone, we have a small problem, for some reason the adblock is blocking the connection to the ReAlis node, maybe someone came across this?

**Comment by jacogr** [comment]
It is the `.network` domain. The W3F's endpoints on Polkadot (while they were active) suffered from that issue with uBlock.

**Comment by Daelon02** [comment]
Okey, thanks)
