### ISSUE TITLE
Unable to Transfer PCX

### ISSUE THREAD

**Issue by jaxwayfarer** [polkadot-js/apps#4865]
I am unable to transfer my PCX to another address.  I selected the PCX deposit address for a few different exchanges and each time the transfer fails with the following error messages.  First, I had the keep alive toggle on, then I deselected but the errors persist.   The amount transferrable shows as '0.000' even though none are reserved or locked.  No problems transferring in to the wallet but cannot get any out.  Please help.  Thanks!

![image](https://user-images.githubusercontent.com/79056772/111502139-f3dac680-871b-11eb-8b08-57aa90a5d9f1.png)

![image](https://user-images.githubusercontent.com/79056772/111501734-9e061e80-871b-11eb-8ab1-010637be0239.png)

**Comment by jacogr** [comment]
Which chain is PCX? 

The reason for asking is that for all chains non-Polkadot, Kusama, Westend, Rococo the types are managed by the external teams for those chains.

The above error would point to a type mismatch, so there is a discrepancy between the chain and what types the team provided.

**Comment by jaxwayfarer** [comment]
Thanks.  I went to ChainX's wallet at https://dapps.chainx.org/  and it worked from there.
