### ISSUE TITLE
Custom Header Type Definition not working in Explorer

### ISSUE THREAD

**Issue by itzmeanjan** [polkadot-js/apps#4866]
Hello 👋,

We were attempting to customise header type using 👇 type definition in explorer's **settings/ developer** section

```json
{
        "ExtrinsicsRoot": {
            "hash": "Hash",
            "commitment": "Vec<u8>"
        },
        "Header": {
            "parentHash": "Hash",
            "number": "Compact<BlockNumber>",
            "stateRoot": "Hash",
            "extrinsicsRoot": "ExtrinsicsRoot",
            "digest": "Digest"
        }
    }
```

We used same type definition while initialising `@polkadot/api`  & it worked perfectly fine.

```js
const provider = new WsProvider(WSURI)

    let api = await ApiPromise.create({
        provider, types: {
            ExtrinsicsRoot: {
                hash: 'Hash',
                commitment: 'Vec<u8>'
            },
            Header: {
                parentHash: 'Hash',
                number: 'Compact<BlockNumber>',
                stateRoot: 'Hash',
                extrinsicsRoot: 'ExtrinsicsRoot',
                digest: 'Digest'
            }
        }
    })
```

Though in explorer,  it seems to use standard `H256` definition, instead of `ExtrinsicsRoot`. Error we found in browser console looked like 👇

```text
Struct: failed on extrinsicsRoot: H256:: value.subarray is not a function
...
```

Can you please tell how we're supposed to be using this correctly ?

**Comment by jacogr** [comment]
Do you have a testnet running for this to check? Really no idea off-hand as to "why" (It could be that it makes assumptions and/or using the wrong registry and/or the derives, which this uses, makes incorrect assumptions)

**Comment by prabal-banerjee** [comment]
Hi. We have a node running at `ws://54.160.87.220:8001`, in case you want to check. Thanks.

**Comment by jacogr** [comment]
Perfect, that helps a lot.
