### ISSUE TITLE
I can't stop staking KSM

### ISSUE THREAD

**Issue by GOLDIAMOND83** [polkadot-js/apps#4870]
Can anyone tell me why I can't stop staking? I have been staking for months so I should be able to stop it. With my dot staking I haven't had any problem to stop it.
<img width="689" alt="Captura de pantalla 2021-03-19 a las 12 42 08" src="https://user-images.githubusercontent.com/62560055/111775141-a6439280-88b0-11eb-91a3-b0546294fa62.png">

**Comment by jacogr** [comment]
The "stop" needs to be called from the controller account. It is disabled if the controller is not found as one of your accounts.

**Comment by GOLDIAMOND83** [comment]
Ouuuu...shit!! Exactly!! Great!! The controller account was disabled. I had active Polkadot controller account. Thank you very much @jacogr
