### ISSUE TITLE
Staking inflation calculated as Infinity crashes staking screen

### ISSUE THREAD

**Issue by jak-pan** [polkadot-js/apps#4896]
We have a problem at HydraDX with staking screen https://polkadot.js.org/apps/#/staking

I have been able to follow the issue to staking reward being calculated as Infinity and that crashes the assertion on imuln() when calculating adjusted reward.
 
We are currently in the validator set bootstrapping phase (like Polkadot and Kusama was). We have 3 of our own validators and no era change. Maybe that is the problem? Haven't been able to dig deeper yet.

https://github.com/polkadot-js/apps/blob/ba4d14a836f083d75ee6edda3329060e75e6540d/packages/page-staking/src/useSortedTargets.ts#L171-L176

**Comment by jacogr** [comment]
Seems like the divisor above - `e.bondTotal`

**Comment by jak-pan** [comment]
You killed it 👍🏻 Thank you for being so quick.

**Comment by jak-pan** [comment]
I guess we can close now.

**Comment by jacogr** [comment]
Phew. Sorry about that, was hoping the fixes would solve it.
