### ISSUE TITLE
Stash bonding alarm for stake minimum

### ISSUE THREAD

**Issue by MCFlatliner** [polkadot-js/apps#4897]
Many people dont realise/know that staking requires a minimal amount to receive rewards.

Add alarm message, when too low a minimum is bonded.

This prevents peoples tokens to be unusable for the 28 days unbonding

**Comment by jacogr** [comment]
![image](https://user-images.githubusercontent.com/1424473/111952965-374f7f00-8ae6-11eb-9352-ae322a65975d.png)
