### ISSUE TITLE
No Extrinsics tab on account creation w/o page refresh

### ISSUE THREAD

**Issue by NukeManDan** [polkadot-js/apps#4912]
I open apps without any account setup or injected. It is expected to not see the extrinsics page available in this state. 
I create a new account, but no page appears, until I do a a page refresh. Ideally all hidden functionality for the UI without an account would be watching and update as soon as the accounts existed, injected or otherwise.

**Comment by jacogr** [comment]
It does actually watch - so weird that it doesn't trigger the rendering correctly. Must be localized in the header grouping itself.

**Comment by jacogr** [comment]
On which browser does this happen? Just tested on Chrome Incognito and it appears as expected once the account is created.

**Comment by NukeManDan** [comment]
firefox 86.0 (64-bit)
Ubuntu 20.04

And.... it must have been a blip. I can't reproduce the bug now. Sorry for the ping!

**Comment by jacogr** [comment]
No issues. Always worth a check.
