### ISSUE TITLE
Treasury tab displays incorrectly when tips pallet is missing

### ISSUE THREAD

**Issue by gregzaitsev** [polkadot-js/apps#4915]
In FRAME tips pallet depends on the treasury pallet, but not the other way around, so treasury should work without tips. But the UI requires that either `treasury.tips` or `tips.tips` is present otherwise it displays error: "Uncaught error. Something went wrong with the query and rendering of this component. Cannot read property 'keys' of undefined"

Can be tested on Unique:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftestnet2.uniquenetwork.io#/treasury

**Comment by jacogr** [comment]
There is actually a lot more issues than just not having tips... so fixing the above uncovers a lot more issues :)

**Comment by gregzaitsev** [comment]
Thank you! Not sure what #3351 should have done, but it does not seem to change anything in how the UI treats missing tips field. 

Actually, we tried adding `tips` storage to treasury pallet that does nothing at all, and it fixed the issue. Maybe removing the requirement that `tips.tips` or `treasury.tips` exists in the UI can fix it?

**Comment by gregzaitsev** [comment]
Oh, I see! #3351 is only part of this issue. Alright, I'll just keep waiting :)

**Comment by jacogr** [comment]
The other PR was for the subsequent issue - the tips specifically is in https://github.com/polkadot-js/apps/tree/jg-tips (Well, and then I did some rework there as well...)

(So with the linked branch in, the issue that is in #3351 pops up)

**Comment by gregzaitsev** [comment]
It started working now! Thank you!!!
