### ISSUE TITLE
Staking payout to any account does not allow non-accounts

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#4916]
I can only select an account I've loaded into the extension or Apps as the custom staking payout destination, not a custom account or an account from the address book. It simply reverts to the last used owned account if I tab out after inputting a completely foreign address.

**Comment by jacogr** [comment]
This is by design. It only allows accounts. There is more than enough places where users can shoot themselves in the foot, paying to a random address or addressbook entry is not one that will be additionally added.

**Comment by Swader** [comment]
If I'm a service provider, and I want to pay out into a cold storage of a client without owning their account, I should be able to do this. Should I use extrinsics or a custom implementation in that case?

**Comment by jacogr** [comment]
You can always use extrinsics.
