### ISSUE TITLE
Versions blockchain

### ISSUE THREAD

**Issue by Daelon02** [polkadot-js/apps#4921]
Hi everyone, we have a little question. Where update this value?
![Screenshot_1](https://user-images.githubusercontent.com/63471940/112303536-0d908680-8ca5-11eb-8294-9695b1344c8c.png)

**Comment by jacogr** [comment]
That is the version returned via the `system_version` RPC call. I don't know where that sits in Substrate.

**Comment by Daelon02** [comment]
Thanks
