### ISSUE TITLE
Equilibrium API error

### ISSUE THREAD

**Issue by michalisFr** [polkadot-js/apps#4969]
When trying to connect to Equilibrium one gets this error:
![Screenshot 2021-03-29 at 4 33 15 PM](https://user-images.githubusercontent.com/45905709/112844740-be839080-90ac-11eb-97b4-7d9f7956af4e.png)

Probably something on Equilibrium's side, but I thought it was worth mentioning.

**Comment by jacogr** [comment]
cc @pr0fedt

**Comment by jacogr** [comment]
Seems to be resolved.
