### ISSUE TITLE
Locked funds in stash account, 

### ISSUE THREAD

**Issue by BJK62051** [polkadot-js/apps#4974]
How do I unlock funds in my stash account. It will not let me transfer enough funds to the controller account to cover fees for a transaction. It will not let me unbond the locked account for the same reason. Do I have to purchase more DOT and send to the controller account to make this happen? If so this is bullshit you have my funds tied up for no reason as they are not earing me any staking rewards.

**Comment by jacogr** [comment]
The sending account always needs to have enough free funds to cover the transaction fees. The transaction fees cannot be paid from -

- locked amounts (e.g. bonded funds)
- reserved amounts (e.g. voting in democracy)
- existential deposit (e.g. the 1 DOT required to keep an account active in Polkadot)

If the account does not have fees, you will need to transfer tokens to it. (As above, those tokens cannot be loked/reserved/exitential)

All substrate-based chains has the concept of existential deposits enforced by the chain.
