### ISSUE TITLE
contracts.TransferFailed error during codehash deploy

### ISSUE THREAD

**Issue by AndreiNavoichyk** [polkadot-js/apps#5012]
Hey folks,

The Polkadot.js apps `v0.86.2` does not allow to deploy a Smart Contract correctly. We receive errors.

**Steps:**
1. Go to Developer -> Contracts.
2. Press `Upload and deploy`.
3. Select *.json and *.wasm.
4. Enter `10^9` as initialSupply and `2` as an endowment.
5. Press `Deploy`.
6. Press `Sign and submit`.
6. Success.
7. Press `Deploy` in just deployed codehash.
8. Reenter `10^9` as initialSupply and `2` as an endowment (Is it a new step? Why do we need to reenter the values from step 4?)
9. Press `Deploy`.
10. Press `Sign and submit`.

**Actual result:**
1. system.ExtrinsicFailed and contracts.TransferFailed errors.

**Expected result:**
1. Codehash has been deployed successfully.

The same flow is working on apps version `v0.76.2`.

It looks like a bug. Could you confirm it or point where we are wrong?

**Comment by jacogr** [comment]
Which version of the contracts module? V2 or v3?

The first is the params for the code, the second for the contract instance.

**Comment by AndreiNavoichyk** [comment]
Do you mean `pallet-contracts` version? If yes, it's `2`.

**Comment by AndreiNavoichyk** [comment]
Hey @jacogr.
Any updates here?

**Comment by jacogr** [comment]
No clue. Since Substrate master is on v3 it is horribly trying to backtrack to older versions. 

At this point I think the API will just drop support for trying to support v2 in the next week with the next release - since it adds complexity and lots of overhead trying to support and test.

**Comment by huythanhcere** [comment]
Please provide details of "TransferFailed" the screenshot or the message in it. @AndreiNavoichyk

**Comment by jacogr** [comment]
Closing, support for the older generation contracts V2 (without `instantiateWithCode`) has been dropped.
