### ISSUE TITLE
Don't work Acala Platform

### ISSUE THREAD

**Issue by igorek52** [polkadot-js/apps#5083]
The site does not load. Every time there is an error(

![115026660-70072c00-9ecb-11eb-87d6-e5b7d79c7436](https://user-images.githubusercontent.com/81561208/115027361-4b5f8400-9ecc-11eb-97f0-cd7134710fb6.png)

**Comment by jacogr** [comment]
The above is not hosted on polkadot.js.org, and neither is the error message one that is in the apps UI. 

I would suggest logging it with the specific team.
