### ISSUE TITLE
authorize transaction screen checking fee incorrect warning with proxy setup 

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#5100]
I have two account, A and B.
B is the proxy of A.
A is doing staking.
I want to update nominators of A, via proxy account B.
I have < 1 free DOT on A, but many locked DOT (via staking)
I have ~3 DOT on B.

I am getting this warning. I ignored it and as expected no account is killed during executing transaction.
<img width="1057" alt="Screen Shot 2021-04-20 at 4 51 07 PM" src="https://user-images.githubusercontent.com/1201310/115339310-9b09bc80-a1f8-11eb-9b00-86807c365990.png">

**Comment by jacogr** [comment]
Ummm... even if it checked the incorrect (non-proxy account), it would still be wrong. Will have to re-check this.
