### ISSUE TITLE
Waiting to make a connection to the remote endpoint and finishing API initialization.

### ISSUE THREAD

**Issue by Yzord** [polkadot-js/apps#5107]
My wallet has this issue

_Waiting to make a connection to the remote endpoint and finishing API initialization._

it does this all of a sudden and i can't reconnect it anymore. Any idea?

**Comment by Rezdub** [comment]
Hi I have the same issue. any help ?

**Comment by Rezdub** [comment]
> My wallet has this issue
> 
> _Waiting to make a connection to the remote endpoint and finishing API initialization._
> 
> it does this all of a sudden and i can't reconnect it anymore. Any idea?

hi, I got fixed mine. just on right hand side hosted by finality and click switch . it will work

**Comment by jacogr** [comment]
The Parity hosted RPC nodes have been having trouble in the last 2 days, first on Polkadot now also it seems on Kusama. Switch to another provider, either OnFinality or Patract.

![image](https://user-images.githubusercontent.com/1424473/115502477-4193a300-a275-11eb-9251-a375ea6c09b5.png)
