### ISSUE TITLE
Estimation for contract call gas amount is too low

### ISSUE THREAD

**Issue by cmichi** [polkadot-js/apps#5156]
When executing the method of some contracts the default `Max Gas Allowed` value (the estimated one) is estimated significantly too low.

## How to reproduce

We've found that at least the ink! examples `delegator` and `contract-terminate` are affected. `contract-terminate` is the easiest to reproduce this. I've attached the contract which can be used for deployment here: [contract_terminate.contract.zip](https://github.com/polkadot-js/apps/files/6390415/contract_terminate.contract.zip).

The contract has only one method `terminateMe`, the UI suggests a default `Max Gas Allowed` of 1417, but the contract then fails with `system.ExtrinsicFailed: contracts.OutOfGas`.

It works if the max gas is set manually to 2500.

![screenshot-polkadot js org-2021 04 28-10_51_34](https://user-images.githubusercontent.com/241530/116379622-7c687e80-a813-11eb-8c6a-835711d106e6.png)

## Debugging

We've used [`canvas-node`](https://github.com/paritytech/canvas-node) with the latest Substrate `HEAD`. `canvas-ui` is also affected by this.

It might be that the actual bug is in Substrate, but I don't know how the logic of polkadot-js works here. Might be that we need to move the issue over to Substrate.

**Comment by jacogr** [comment]
On the estimation, it uses the contracts.call and then uses the `gasConsumed` value as the gas passed to the actual execute. So if this is very low (and in this case it seems off by a huge margin), something is really weird in the contracts call RPC.

**Comment by jacogr** [comment]
Logged the actual `gasConsumed` value on this specific contract, it is `1,416,325,397` (The UI adjust this upwards and passes 1,417,000,000 with the mega-gas rounding)

Added a 1% factor above that, it still fails. Even at 10% above, e.g. `1,558,000,000` as well 15% above the `gasConsumed` it still fails.

**Comment by cmichi** [comment]
Thanks @jacogr! I'm cc'ing @athei.

**Comment by jacogr** [comment]
I tried to see if I'm doing something stoopid, but def. do call the read RPC with the selected account, i.e. same one that will execute the actual tx as well.

**Comment by athei** [comment]
Thanks for your investigation. Looks like a a bug in the pallet_contracts then. I will look into it.

**Comment by jacogr** [comment]
Happy to hear I'm wrong, just cannot find out what it is atm. So eyes elsewhere would help - there is an issue "somewhere".

**Comment by cmichi** [comment]
There is https://github.com/paritytech/substrate/pull/8976 now, which should fix this.

**Comment by jacogr** [comment]
Closing, tracked in Substrate.
