### ISSUE TITLE
treasury tip screen responsive sizing issue

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#5162]
<img width="1494" alt="Screen Shot 2021-04-29 at 8 02 50 PM" src="https://user-images.githubusercontent.com/1201310/116519680-e2452b00-a925-11eb-8053-a6edd497fccc.png">

The tip button is completely hidden and no scrolling at all

**Comment by jacogr** [comment]
Yes, the reasons are a bitch and my CSS is nowhere near a level to fix that.
