### ISSUE TITLE
Length is required as Bytes input prefix

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#519]
(As reported by @shawntabrizi )

Bytes currently seems to need the length encoding when the value is entered, i.e. `0x1111` needs to be inputted as `0x081111`. Something is wrong here, since it would seem that the input actually does not need it, or rather the code shows that the intent is to not need it as an input -

- Bytes gets the `withLength` flag here - https://github.com/polkadot-js/apps/blob/next/packages/ui-app/src/Params/Param/Bytes.tsx#L53
- Here is should add it explicitly when the value changes - https://github.com/polkadot-js/apps/blob/next/packages/ui-app/src/Params/Param/BaseBytes.tsx#L70

So it would seem the combination does not quite do what it seems to indicate, i.e. allow the input of hex without the length prefix. Once again check consistency - we need to make 100% sure that we strip on `Bytes` (input and display), `Data` has raw encoded values.

**Comment by jacogr** [comment]
Another option - it could be with the mangling and then creation the type that things are needings to be double-encoded. It may just be worth-while doing the right thing here and returning `Bytes` (constructed via the hex input) instead of a Uint8Array and having the UI worry about prefixing or now.

Either way, just needs to testing, playing and tweaks.

**Comment by jacogr** [comment]
Ok, it _seems_ to indeed to the correct trick when used as a normal value, i.e. as part of `consensus.setCode`. 

<img width="916" alt="polkadot apps portal 2018-12-17 10-36-46" src="https://user-images.githubusercontent.com/1424473/50078591-ae02c100-01e7-11e9-9fc3-a9c5aca3bb16.png">

We do have some issues around the type as a storage param, i.e. original -

<img width="630" alt="polkadot apps portal 2018-12-14 11-02-57" src="https://user-images.githubusercontent.com/1424473/50078513-7dbb2280-01e7-11e9-9149-40a10bcbf4e4.png">

In this case adding `0x081111` does the correct thing, however `0x1111` does not. So _potentially_ it is something with the storage keys and the generation thereof?

**Comment by jacogr** [comment]
Ok, found the culprit. And needs some thinking, basically it lies here 

https://github.com/polkadot-js/api/blob/master/packages/type-storage/src/utils/createFunction.ts#L54

Effectively we "naked encode" the param values. I believe originally we did it this way since we didn't want to inadvertently encode Compact values in here. But basically here it will strip the actual prefix for Bytes, or rather, encode it without - and in the case of the sample key above, it actually expects it.

@amaurymartiny I know I did the above `true`, however can you think of areas where it could impact?

**Comment by jacogr** [comment]
@shawntabrizi Just merged #520 above and it was just built & deployed by CI to the /apps/next endpoint. (And obviously available on the next branch itself after merge - if running locally)

I would just appreciate a check to see if you still need to add the length to the hex string, it should now not be required anymore. (Fixed early this morning, however pulling the fix into the UI lagged a bit between other stuff)

**Comment by shawntabrizi** [comment]
@jacogr Yeah, it looks fixed from my end. I am able to query without adding the lengh encoded prefix using the UI hosted at https://polkadot.js.org

**Comment by jacogr** [comment]
Thank you !
