### ISSUE TITLE
contracts: `Undefined has no properties` when trying to deploy a contract

### ISSUE THREAD

**Issue by athei** [polkadot-js/apps#5203]
I am trying to deploy a contract against substrate master `v3.0.0-302-g7b4d55be8` with `apps v0.90.2-6`. I get the following error when clicking on "Upload & Deploy Code".

> Uncaught error. Something went wrong with the query and rendering of this component. undefined has no properties

**Comment by jacogr** [comment]
Ummm... weird, was still working as f my tests last week. Will pull latest and try to reproduce. I'm assuming any contract?

**Comment by athei** [comment]
> I'm assuming any contract?

Yes. It happens immediately when you click the button. Before one could even select a contract to upload.

**Comment by jacogr** [comment]
Ok, can replicate. Additionally the types are outdated for the API vs what is in the Rust side, so that also needs fixing to get it running smoothly.

**Comment by achimcc** [comment]
I'm receiving a similar error when trying to deploy contracts:

```Uncaught error. Something went wrong with the query and rendering of this component. Cannot read property 'value' of undefined```
