### ISSUE TITLE
Support for Charred Cherry in Settings

### ISSUE THREAD

**Issue by emielvanderhoek** [polkadot-js/apps#521]
Support for Charred Cherry in Settings perhaps including a default hosted node (by Parity).

**Comment by emielvanderhoek** [comment]
(this is for the 'next' version)
https://polkadot.js.org/apps/next/#/settings

**Comment by jacogr** [comment]
PR is open for the settings already in https://github.com/polkadot-js/ui/pull/25, I'm just waiting for the ops team to confirm the hosted node URL. (i.e. confirm that it is up-and-running)

**Comment by jacogr** [comment]
Closed in #522 and verified as deployed. 

(Be aware that there is a logged issue with subscriptions to new headers on Substrate, so the "explorer" on apps/next will shows every 10th block or so - all UIs are currently affected by this. However about from the "non-incrementing" hiccup, the functionality seems ok)
