### ISSUE TITLE
Incorrect ED warning message for account with sufficient balance

### ISSUE THREAD

**Issue by michalisFr** [polkadot-js/apps#5211]
A user has 1.017 DOT transferable in their account but they get a warning that they don't have enough to cover the fees:
![PM5W-Z8n4dYoi7jD2kVWg5ernaNaZLcHew jpg](https://user-images.githubusercontent.com/45905709/117121536-63c11100-ad9d-11eb-9528-00479ce9bdfc.png)

Testing with a manual transfer, however, works fine:
<img width="651" alt="Screenshot 2021-05-05 at 05 11 22" src="https://user-images.githubusercontent.com/45905709/117121570-71769680-ad9d-11eb-9398-739a18539565.png">

<img width="689" alt="Screenshot 2021-05-05 at 05 12 17" src="https://user-images.githubusercontent.com/45905709/117121588-76d3e100-ad9d-11eb-9bcf-e00d0c1b9bd3.png">

<img width="356" alt="Screenshot 2021-05-05 at 05 12 32" src="https://user-images.githubusercontent.com/45905709/117121603-7c312b80-ad9d-11eb-9524-ef47e139c708.png">

The UI shouldn't be displaying this message for balances higher than 1.0156 DOT.

**Comment by jacogr** [comment]
This is by design. Since the amounts are only an estimation, there is a safety factor built into the calculation on the transfer dialog. False positives are always better than false negatives, which results in way more noise.

**Comment by michalisFr** [comment]
Ah, I see. And it seems we're reserving about 0.0171 DOT for fees, just higher than what this guy has. Cool, thanks for clarifying!
