### ISSUE TITLE
Changing networks via top left select

### ISSUE THREAD

**Issue by charliegithubok** [polkadot-js/apps#5223]
When changing networks via the top left selection,, please can you make sure the prefix in settings is also changed to the selected network.

 This nearly cost me losing my funds because I was about to send KSM to my DOT address (thinking the addresses are the same for both networks) - I asked support in Discord Kusama and they said I had to go to settings and set the prefix to Kusama as well to show my Kusama address.

This is very confusing because when you click your account and see the address it shows the DOT address until you change it in settings - and it says 0 KSM next to the DOT address!! - this will make many lose their money or give up trying to recover the funds.

Please fix this.

**Comment by jacogr** [comment]
The UI always respects the user wishes. Set to 

![image](https://user-images.githubusercontent.com/1424473/117396301-f24aa500-aef9-11eb-8844-c5e508ae1fbd.png)

It will change on network selection. When the user explicitly overrides it, it will show in that format. In your case it would seem that you are forcing the UI into a specific display. Swap to the first option if you wish to see network-specific formats when swapped.
