### ISSUE TITLE
"transfer to chain" menu on Rococo can't be found

### ISSUE THREAD

**Issue by jakehemmerle** [polkadot-js/apps#5233]
I've seen a few people over the past few days in the Rococo Matrix channel be unable to find the "transfer to chain" menu on Rococo.

According to the Polkadot wiki instructions [here](https://wiki.polkadot.network/docs/en/build-parachains-rococo#how-to-make-cross-chain-transfers), I'd expect to find this menu under Accounts > Transfer, but instead, I'm just finding the "send funds" menu (same as Accounts and then click 'send' under an account. A photo of the expected "transfer to chain" menu is at the link above.

If this is a wiki instruction issue, let me know where I can find the "transfer to chain" menu and I'll update the wiki instructions accordingly.

**Comment by jakehemmerle** [comment]
Okay. Is there a way to transfer tokens between chains now or has this been totally removed for the time being?

**Comment by jacogr** [comment]
Just some info... As I recall, the pallet used was called "tokenManager" (or token-something), that provided this functionality. 

There will be something added specifically for Statemint (hardcoded to the chain and the relevant ids per relay), at some point.
