### ISSUE TITLE
Error on accounts page

### ISSUE THREAD

**Issue by GamePowerDev** [polkadot-js/apps#5244]
Hello! I noticed recently that certain networks are throwing errors when visiting the accounts page. One place I noticed this is on our network's account page: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fgamepower.io#/accounts

I'm not sure if this is a problem we need to fix in the runtime or something with the polkadot-js apps.

This is the console error I'm seeing:

`
Uncaught (in promise) Error: Unable to decode storage system.account: entry 0:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000000000000010000000000000000000010000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (76 bytes), created 0x0000000000000000010000000000000000000010000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes)
`

**Comment by jacogr** [comment]
It would mean the types for the specific chain needs adjustment. In this case it looks like a missing dual-ref AccountInfo (API default is triple-ref as per Substrate master)

**Comment by GamePowerDev** [comment]
Thanks so much for explaining @jacogr, I'll close now that it is resolved!
