### ISSUE TITLE
Kusama Parachains Tab Fails

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/apps#5283]
<img width="852" alt="image" src="https://user-images.githubusercontent.com/1860335/118296109-96a88a80-b4aa-11eb-87bd-dc545ab2ced8.png">

**Comment by jacogr** [comment]
No idea. Will have to look. Supposed to be the same as Westend, doesn’t seem like it.

**Comment by jacogr** [comment]
This should be fine now, unlike last week, this week we were back to the weekly release schedule. So should be all-ok. (And indeed is for me)

![image](https://user-images.githubusercontent.com/1424473/118598765-e50da000-b7ae-11eb-8fbb-205e4db77404.png)
