### ISSUE TITLE
Accessing `KeyRing` through JavaScript console

### ISSUE THREAD

**Issue by JosephDenman** [polkadot-js/apps#5302]
I'm trying to use the JavaScript console to implement some transfer logic on the SORA blockchain. When I construct my transfer object and run `const keyring = new Keyring();` to create a keyring to import my key into, I get back

```
TypeError: Cannot read property 'key' of undefined
    at eval (eval at <anonymous> (https://polkadot.js.org/apps/main.2a113055.js:19:438769), <anonymous>:20:38)
    at Object.eval (eval at <anonymous> (https://polkadot.js.org/apps/main.2a113055.js:19:438769), <anonymous>:47:67)
    at https://polkadot.js.org/apps/main.2a113055.js:19:438814
```

But this is what https://polkadot.js.org/docs/api/start/keyring suggests I do. Is there a workaround for this?

**Comment by jacogr** [comment]
Only on dev chains, i.e. when running locally. It is not available for live chains since it opens up the opportunity for scammers to send weird scripts to users.

**Comment by JosephDenman** [comment]
Hm. Even if a run a sync node locally and connect to it I see the same error.

**Comment by jacogr** [comment]
It is only available on dev chains. So those run with —dev - this is always disabled for anything love.
