### ISSUE TITLE
Are we allowed to add apps-config spec files to our 3rd party wallets?

### ISSUE THREAD

**Issue by GamePowerDev** [polkadot-js/apps#5305]
Hello!

Our team is creating a wallet for the web3 open grants program and I was wondering if we are allowed to freely use: apps/packages/apps-config/src/api/spec/index.ts within our own 3rd party wallet apps?

I know it's technically possible but I didn't want to over-step the boundaries of the community if the contributors didn't want to allow other wallets to use the spec files.

Thanks!

**Comment by jacogr** [comment]
Yes, you can certainly use it, and if the goal is to add value to our ecosystem, it is great if you do. So couple of options -

- `@polkadot/apps-config` does get published, e.g. stuff like api-sidecar does also use it (which includes all)
- if you do just copy the code just ensure you keep to terms the Apache 2 license (including copyright, license in the copied fil, etc) as per https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

**Comment by GamePowerDev** [comment]
Thanks so much for confirming the use of apps-config. I'll review api-sidecar's implementation of it as well!
