### ISSUE TITLE
Cancel slashes button does not open a Council motion

### ISSUE THREAD

**Issue by rrtti** [polkadot-js/apps#5306]
There seems to be an issue with the button to cancel all slashes if you try to open the motion via `Network tab > Staking > Slashes` on Apps using `Cancel All`. I can sign the call but no motion is opened, and if i check on Polkascan, the only difference with the proposal I opened using the Motions tab by clicking `Cancel slashes` button, is the `threshold`:

1. call from staking tab: `Network tab > Staking > Slashes` and sign the call by clicking on `Cancel all` (not opened and threshold is specified as `0`): [HERE](https://polkascan.io/kusama/transaction/0xe1036dc9d4c15ec76800c31aa0c30dc0a1a386ffedb1995364190f2cc712db9a)
2.  correct call opened from council tab using `Cancel slashes` button (opened - Motion 295): [HERE](https://polkascan.io/kusama/transaction/0xdbf2bed507b8c319d653f1c066248f2611092ed96cfcaee3bd1cfa9fd8572744)

**Comment by jacogr** [comment]
Ok, seems to be a threshold bug, based on the above.
