### ISSUE TITLE
ED shown as 0 for Kusama on UI

### ISSUE THREAD

**Issue by michalisFr** [polkadot-js/apps#5310]
It seems that due to rounding the ED is shown as 0 in the send modal after the reduction in the new runtime:
![Screenshot 2021-05-17 at 1 21 15 PM](https://user-images.githubusercontent.com/45905709/118484754-42a6db80-b720-11eb-9a6a-e9f17ab71987.png)

**Comment by jacogr** [comment]
This is the same issue as in https://github.com/polkadot-js/apps/issues/4928 - for "pre-filled values" they don't (yet) get formatted with the SI. (This is for low amounts, the linked is for high amounts)
