### ISSUE TITLE
Unable to deploy `contract-transfer` example

### ISSUE THREAD

**Issue by cmichi** [polkadot-js/apps#5316]
I'm not sure if this a bug in Substrate or the UI:

* I install the latest `canvas-node`:
`cargo install --git https://github.com/paritytech/canvas-node --force --locked`  
It was synced to Substrate just last week.
* When I deploy `flipper` via the UI it works fine: [flipper.contract.zip](https://github.com/polkadot-js/apps/files/6498295/flipper.contract.zip).
* When I deploy [ink!'s `contract-transfer` example](https://github.com/paritytech/ink/blob/master/examples/contract-transfer/lib.rs) I get `system.ExtrinsicFailed Other` in the UI.
* This is the `.contract` file: [contract_transfer.contract.zip](https://github.com/polkadot-js/apps/files/6498302/contract_transfer.contract.zip). 
* The `canvas` output shows `Failed to submit extrinsic: Transaction pool error: Too low priority (282384687094 > 282384687094)`.

I haven't yet managed to isolate it further. Does the UI supply the nonce?

**Comment by jacogr** [comment]
The nonce is supplied in one of two ways -

- if the `account_nextNonce` RPC is available, it uses that, else
- use `system.account` for the nonce info (which means pending pool transactions are not taken into account)

And yes, the nonce is part of the signed payload.

**Comment by athei** [comment]
This seems unrelated to contracts. So maybe the canvas node is missing the RPC?

**Comment by cmichi** [comment]
I've found the issue! It went back to an import in that contract which is no longer valid in recent Substrate versions.

**Comment by jacogr** [comment]
I still have not been able to figure out, why, in this case, it gets to a weird tx pool error. It now seems even more misleading based on what you describe.
