### ISSUE TITLE
Hi, How can I add my own chain to https://polkadot.js.org/apps

### ISSUE THREAD

**Issue by imstar15** [polkadot-js/apps#5324]
How do I apply?

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/apps/tree/master/packages/apps-config

**Comment by imstar15** [comment]
> See https://github.com/polkadot-js/apps/tree/master/packages/apps-config
> 
> Once a PR is made from the team based on the above, there is some checks on my side to ensure that it is a valid team with an OSS codebase. (In the past some have slipped through the cracks)

Thanks
