### ISSUE TITLE
Where is the text in the'text' field displayed on the website?

### ISSUE THREAD

**Issue by imstar15** [polkadot-js/apps#5329]
```
{
      info: 'crust',
      text: t('rpc.test.crust.network', 'Crust Maxwell', { ns: 'apps-config' }),
      providers: {
        'Crust Network': 'wss://api.crust.network/',
        'DCloud Foundation': 'wss://api.decloudf.com/'
      }
},
```

Where is the text(rpc.test.crust.network) in text displayed on the website?
Can you cut a picture to illustrate it?

**Comment by jacogr** [comment]
![image](https://user-images.githubusercontent.com/1424473/118925724-76138100-b93f-11eb-98c8-b70e9549963a.png)

**Comment by imstar15** [comment]
Where is 'rpc.test.crust.network' displayed?

@jacogr

**Comment by jacogr** [comment]
As above, last line on the screenshot.

**Comment by imstar15** [comment]
> As requested and as pasted above, the last line on the screenshot. Under testnets, Crust.

Got it, thanks!
