### ISSUE TITLE
Sign Message with an External/Attached Extension Account

### ISSUE THREAD

**Issue by danforbes** [polkadot-js/apps#5347]
Is it possible to sign a message with an external/attached extension account, such as an account that's managed with Parity Signer? I'd like to be able to do this for identity attestation, but it's not clear how to use Polkadot-js Apps and the extension to do so. When I click the "Sign Message" button, I get a pop-up from the extension, but there is not a QR code and the only option that is available is "Cancel"; I can see that my webcam activates for a second, but the extension pop-up doesn't seem to be looking for a QR code to scan. I used the Apps UI to update the metadata for the Westend Network and I've confirmed that Apps and the external/attached extension account work as expected for transferring tokens. 

![image](https://user-images.githubusercontent.com/2193247/119230186-07196200-bad0-11eb-8844-1eda5994ac3a.png)

**Comment by jacogr** [comment]
See the issues around this in the extension, there are multiples (including an open PR for at least Stylo to address it).

**Comment by danforbes** [comment]
Is this the best one? https://github.com/polkadot-js/extension/issues/689

**Comment by Tbaut** [comment]
Rather this. https://github.com/polkadot-js/extension/pull/718
Linked to the Signer PR I made to support it.
