### ISSUE TITLE
Kusama staking payouts showing incorrect amount

### ISSUE THREAD

**Issue by mario-purestake** [polkadot-js/apps#5359]
I'm not sure this is a bug on the UI or something more internal, but we have detected that the _Staking>Payouts_ and _Staking>Validator Stats_ sections are not showing the correct amounts for the rewards. If we check the amount received in our account using Subscan or just the `@polkadot/api`, we see that the amount shown on the UI is around 10x times higher than what we actually have received. 

Taking as an example this validator, we see that the UI shows that the amount it received at some point reached 3 KSM. This is only showing the _Validator Stats_ section, as it's the only publicly accessible, but it's also affecting _Payouts_, as said above.

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.api.onfinality.io%2Fpublic-ws#/staking/query/Cd2ewfXdQiaUzTBYKSZTzL7hPuB3nzEKMT2y36zJC9QaEG4

![PolkadotJS Apps screenshot](https://user-images.githubusercontent.com/66425016/119487718-03007500-bd5a-11eb-96f8-bdebe5919b3d.png)

However, if we check Subscan, the rewards are never higher than 0.5 KSM.

https://kusama.subscan.io/reward?address=Cd2ewfXdQiaUzTBYKSZTzL7hPuB3nzEKMT2y36zJC9QaEG4&page=1

![Subscan screenshot](https://user-images.githubusercontent.com/66425016/119487952-49ee6a80-bd5a-11eb-91b1-cdc58fa33fa2.png)

I say that this may be not a problem with the UI because we have also used the Python library `subtrate-interface` and the JS library `@polkadot/api` to retrieve the pending rewards of a validator, and they also showed a value around 10x times higher. On the UI, this bug is also happening for Polkadot (showing rewards of 800-1000 DOTs when it's receiving 80-100 DOTs). However, for both of the libraries mentioned before, it works fine on Polkadot but fails on Kusama and Westend (this one with a different deviation).

Let me know if you need any more examples or information. Thanks in advance :)

**Comment by jacogr** [comment]
It is indeed bug. The issue is that the points for parachain validation are currently allocated to the wrong validators. This will be fixed in the 0.9.3 release & 9030 runtime upgrade.
