### ISSUE TITLE
What version is used for types bundle?

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#5361]
The runtime version is not displayed anymore on the upper left corner.
How do I know which versions number will be used with the types bundle? Anywhere in the code I could console.log?
Thanks in advance

**Comment by jacogr** [comment]
![image](https://user-images.githubusercontent.com/1424473/119598753-d133f080-bde3-11eb-8948-744a7d325ece.png)

- specName - moonshadow
- specVersion - 30

**Comment by joelamouche** [comment]
Ok its back thanks
