### ISSUE TITLE
Asset creation broken

### ISSUE THREAD

**Issue by gdethier** [polkadot-js/apps#5362]
# Setup
- Node: substrate v3.0.0 (api v4.11.2)
- apps v0.91.3-30
- Assets pallet v3.0.0

# How to reproduce
1. Go to Network > Assets
2. Click "Create" button
3. Fill-in required fields at step 1/2

# Observed behavior
An error message appears: "[...] Extrinsic assets.create expects 4 arguments, got 3."

# Expected behavior
No error message appears and I can click on "Next" button in order to go further in the creation process.

**Comment by gdethier** [comment]
Just checked the code, there is indeed a missing argument in the call (max_zombies). I'll prepare a PR.

**Comment by gdethier** [comment]
@jacogr Thanks for your answer!

I am a bit confused: I understand that the problem comes from an "API mismatch" between the installed pallet and what the Polkadot JS app expects. What is not clear to me: which version of the "assets" pallet should be installed to make the Polkadot JS app work out of the box?

More generally: what is the policy for the Polkadot app JS w.r.t. the support of Substrate pallets (e.g., Polkadot JS app supports pallets with version 2.X until Y, then supports pallets with version 3.X until Z, etc.)?

**Comment by gdethier** [comment]
BTW, I see that the problem is "fixed" with version 0.91.3-32 at least: the assets screen does not appear anymore.

**Comment by jacogr** [comment]
The UI tries to support older pallets. However in this case it was never deployed anywhere. No live chains. In that case it only supports chains where deployment is done. 

Supporting older has a huge impact on maintainability, so unless deployed somewhere (which means it can be tested), old support is not done at all. For instance this is a prime example - it basically would need around 25%+ of core code duplication for the different features. It is not worth it.

**Comment by jacogr** [comment]
As for timelines as to older support - I generally give around 3-4 months from Substrate merge (assuming it is already deployed live), before dropping support for old to give chains some time to update. (Which is then a great opportunity to remove all old baggage)

**Comment by gdethier** [comment]
OK, thanks for the clarifications. Closing the issue.
