### ISSUE TITLE
Polkadot UI broken with custom Substrate Runtimes: "Cannot read property 'validators' of undefined"

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/apps#537]
When trying to use a custom runtime with the Polkadot UI, the page fails to load with the following console errors:

```
observable.tsx:79 withObservable:subscribe sessionValidators TypeError: Cannot read property 'validators' of undefined
    at t.default.sessionValidators (Queries.js:150)
    at Object.subscribe (observable.tsx:69)
    at Object.componentDidMount (observable.tsx:57)
    at Ri (react-dom.production.min.js:229)
    at Ai (react-dom.production.min.js:220)
    at Ni (react-dom.production.min.js:219)
    at Ti (react-dom.production.min.js:216)
    at ti (react-dom.production.min.js:214)
    at Object.enqueueSetState (react-dom.production.min.js:134)
    at t.k.setState (react.production.min.js:13)
subscribe @ observable.tsx:79
componentDidMount @ observable.tsx:57
Ri @ react-dom.production.min.js:229
Ai @ react-dom.production.min.js:220
Ni @ react-dom.production.min.js:219
Ti @ react-dom.production.min.js:216
ti @ react-dom.production.min.js:214
enqueueSetState @ react-dom.production.min.js:134
k.setState @ react.production.min.js:13
t @ NamespacesConsumer.js:149
e @ NamespacesConsumer.js:167
(anonymous) @ EventEmitter.js:47
e.emit @ EventEmitter.js:46
(anonymous) @ i18next.js:142
(anonymous) @ i18next.js:246
(anonymous) @ i18next.js:261
(anonymous) @ BackendConnector.js:142
t.loaded @ BackendConnector.js:122
(anonymous) @ BackendConnector.js:229
(anonymous) @ BackendConnector.js:175
(anonymous) @ index.js:84
l.onreadystatechange @ ajax.js:69
XMLHttpRequest.send (async)
t.default @ ajax.js:71
value @ index.js:82
value @ index.js:75
t.read @ BackendConnector.js:168
t.loadOne @ BackendConnector.js:225
(anonymous) @ BackendConnector.js:203
t.prepareLoading @ BackendConnector.js:202
t.load @ BackendConnector.js:208
t.loadResources @ i18next.js:194
r @ i18next.js:260
t.changeLanguage @ i18next.js:266
l @ i18next.js:139
setTimeout (async)
t.init @ i18next.js:151
(anonymous) @ i18n.ts:14
f @ bootstrap:78
(anonymous) @ index.tsx:6
f @ bootstrap:78
(anonymous) @ index.tsx:10
f @ bootstrap:78
t @ bootstrap:45
r @ bootstrap:32
(anonymous) @ main.81990af2.js:1
react-dom.production.min.js:179 TypeError: Cannot read property 'validators' of undefined
    at t.default.sessionValidators (Queries.js:150)
    at Object.subscribe (observable.tsx:69)
    at Object.componentDidMount (observable.tsx:57)
    at Ri (react-dom.production.min.js:229)
    at Ai (react-dom.production.min.js:220)
    at Ni (react-dom.production.min.js:219)
    at Ti (react-dom.production.min.js:216)
    at ti (react-dom.production.min.js:214)
    at Object.enqueueSetState (react-dom.production.min.js:134)
    at t.k.setState (react.production.min.js:13)
xo @ react-dom.production.min.js:179
n.callback @ react-dom.production.min.js:190
da @ react-dom.production.min.js:128
ca @ react-dom.production.min.js:128
Ri @ react-dom.production.min.js:229
Ai @ react-dom.production.min.js:220
Ni @ react-dom.production.min.js:219
Ti @ react-dom.production.min.js:216
ti @ react-dom.production.min.js:214
enqueueSetState @ react-dom.production.min.js:134
k.setState @ react.production.min.js:13
t @ NamespacesConsumer.js:149
e @ NamespacesConsumer.js:167
(anonymous) @ EventEmitter.js:47
e.emit @ EventEmitter.js:46
(anonymous) @ i18next.js:142
(anonymous) @ i18next.js:246
(anonymous) @ i18next.js:261
(anonymous) @ BackendConnector.js:142
t.loaded @ BackendConnector.js:122
(anonymous) @ BackendConnector.js:229
(anonymous) @ BackendConnector.js:175
(anonymous) @ index.js:84
l.onreadystatechange @ ajax.js:69
XMLHttpRequest.send (async)
t.default @ ajax.js:71
value @ index.js:82
value @ index.js:75
t.read @ BackendConnector.js:168
t.loadOne @ BackendConnector.js:225
(anonymous) @ BackendConnector.js:203
t.prepareLoading @ BackendConnector.js:202
t.load @ BackendConnector.js:208
t.loadResources @ i18next.js:194
r @ i18next.js:260
t.changeLanguage @ i18next.js:266
l @ i18next.js:139
setTimeout (async)
t.init @ i18next.js:151
(anonymous) @ i18n.ts:14
f @ bootstrap:78
(anonymous) @ index.tsx:6
f @ bootstrap:78
(anonymous) @ index.tsx:10
f @ bootstrap:78
t @ bootstrap:45
r @ bootstrap:32
(anonymous) @ main.81990af2.js:1
react-dom.production.min.js:219 Uncaught TypeError: Cannot read property 'validators' of undefined
    at t.default.sessionValidators (Queries.js:150)
    at Object.subscribe (observable.tsx:69)
    at Object.componentDidMount (observable.tsx:57)
    at Ri (react-dom.production.min.js:229)
    at Ai (react-dom.production.min.js:220)
    at Ni (react-dom.production.min.js:219)
    at Ti (react-dom.production.min.js:216)
    at ti (react-dom.production.min.js:214)
    at Object.enqueueSetState (react-dom.production.min.js:134)
    at t.k.setState (react.production.min.js:13)
sessionValidators @ Queries.js:150
subscribe @ observable.tsx:69
componentDidMount @ observable.tsx:57
Ri @ react-dom.production.min.js:229
Ai @ react-dom.production.min.js:220
Ni @ react-dom.production.min.js:219
Ti @ react-dom.production.min.js:216
ti @ react-dom.production.min.js:214
enqueueSetState @ react-dom.production.min.js:134
k.setState @ react.production.min.js:13
t @ NamespacesConsumer.js:149
e @ NamespacesConsumer.js:167
(anonymous) @ EventEmitter.js:47
e.emit @ EventEmitter.js:46
(anonymous) @ i18next.js:142
(anonymous) @ i18next.js:246
(anonymous) @ i18next.js:261
(anonymous) @ BackendConnector.js:142
t.loaded @ BackendConnector.js:122
(anonymous) @ BackendConnector.js:229
(anonymous) @ BackendConnector.js:175
(anonymous) @ index.js:84
l.onreadystatechange @ ajax.js:69
XMLHttpRequest.send (async)
t.default @ ajax.js:71
value @ index.js:82
value @ index.js:75
t.read @ BackendConnector.js:168
t.loadOne @ BackendConnector.js:225
(anonymous) @ BackendConnector.js:203
t.prepareLoading @ BackendConnector.js:202
t.load @ BackendConnector.js:208
t.loadResources @ i18next.js:194
r @ i18next.js:260
t.changeLanguage @ i18next.js:266
l @ i18next.js:139
setTimeout (async)
t.init @ i18next.js:151
(anonymous) @ i18n.ts:14
f @ bootstrap:78
(anonymous) @ index.tsx:6
f @ bootstrap:78
(anonymous) @ index.tsx:10
f @ bootstrap:78
t @ bootstrap:45
r @ bootstrap:32
(anonymous) @ main.81990af2.js:1
```

**Comment by jacogr** [comment]
Is the `session` module included in the custom build? That one exposes `session.validators`. Atm (at least until https://github.com/polkadot-js/apps/issues/482 is in), it assumes that some base functionality from Substrate is there, most notably: valances, system, session. (And for app-specific, democracy as well)

The linked issue will start detecting functionality, only making available what is actually in the built chain.

**Comment by shawntabrizi** [comment]
@jacogr I think Bastian recently cleaned up the Substrate Runtime Module to remove some of the extra modules, which may be the case of this problem. Let me take a look and see if I can resolve this issue by including the session module (if it is not included).

Thanks!

**Comment by shawntabrizi** [comment]
Indeed this commit was the issue here: https://github.com/paritytech/substrate-node-template/commit/681feb2637a995cb1561da910c0bfa71d90d02cc

I needed to add all 7 modules back since they are interconnected.

@jacogr can you help me understand the scope for 482? The error here is the UI is assuming that certain modules are implemented for all blockchains trying to use the interface. 482 will modify that to detect the modules which actually are implemented (rather than assuming), and adjust the UI accordingly?

In that world, there would be no need to include these modules for the UI to load properly?

Are there any short term tricks that can be done to the UI to allow it to function without these modules?

**Comment by jacogr** [comment]
You are 100% right on the intent. Initially it will be quite rough - you don't have `balances`, no Transfer app. You don't have `democracy`, no Democracy app, etc. No `session` or `staking`, no Staking app. Once that is in place, it can be fine-tuned to operate with parts missing and parts available. (for instance Transfer available, but fees may not be)

Sadly, there are no shortcuts atm apart from not accessing the functionality around the missing modules - I don't believe it is a huge issue right as of now, since _most_ implementors will add additional modules (keeping the substrate base and possibly removing some, e.g. Polkadot not having contracts). However, it becomes a huge issue when for instance you don't have a `balances` modules (your chain doesn't need it), but something like `Transfer` is available and stuff just breaks. 

So all the issues around these are the first thing on the list for 2019, but things should still be "pretty safe" even without. (But radical tweaks do happen... hence, next up looking at tweaking around all these and the way the API operates throughout.)

**Comment by 0x7CFE** [comment]
> However, it becomes a huge issue when for instance you don't have a balances modules (your chain doesn't need it), but something like Transfer is available and stuff just breaks.

Yes, such scenario fits my `utxo` prototype where I want to get rid of the `balances` module completely.

**Comment by shawntabrizi** [comment]
It is my experience that having the Polkadot-UI is a huge benefit to the developer story for people playing around with Substrate and writing new runtimes. It provides access to many features like events, accessing custom functions, reading storage, etc right out of the box, whereas the bonds ui does require a significant amount of customization to get a similar experience.

It would be good to understand more precisely what would be required to get this compatibility, and if it is reasonable, prioritize the work accordingly. It looks to me that the polkadot-ui will be a valuable tool for new and exploratory developers.
