### ISSUE TITLE
Clarity needed on displaying addresses on website app and polkadot browser extension. Shows different if 'address prefix' is changed and forgotten.

### ISSUE THREAD

**Issue by saadgit** [polkadot-js/apps#5378]
To grasp the whole address display issue regarding,

"is this the right DOT address", or 
"is my KSM address correct", or 
"why my browser app shows different address than browser extension". 

I see that after some guidelines, there is still a UI/UX limitation which makes the users confuse. Here is an example

1. Go to browser App https://polkadot.js.org/apps/#/accounts 
2. Click on your DOT account. It will show the address of the injected account on the right side panel.
3. Right side panel shows address based on 2 things 
    (i)  Selected parachain/network on the top left corner on web app.
    (ii) Selected address prefix in Settings > General > address prefix (make sure its Polkadot Relay Chain)

![polka1](https://user-images.githubusercontent.com/3226154/119811798-c95d7480-bee7-11eb-92a7-97789f7d3dbd.jpg)

From above, the DOT address should be starting with 1xxx . Also check the address on browser extension (if parachain selected is Polka), then it will show the same address. All good.

Now lets switch to another network and see the account address.
1. Go to browser App https://polkadot.js.org/apps/#/accounts 
2. Click on your KSM account . It will show the address of the injected account on the right side panel.
3. Right side panel shows address based on 2 things 
    (i)  Selected parachain/network on the top left corner on web app.
    (ii) Selected address prefix in Settings > General > address prefix

From above, the KSM address should be starting with capital letters but it will be starting with 1xxx . Also check the address on browser extension (if parachain selected is KSM), then it will NOT show the same address and will be showing the address starting with Capital letter. The reason was, we have set the address prefix on website settings to Polkadot

![image](https://user-images.githubusercontent.com/3226154/119812897-f0687600-bee8-11eb-9b5b-9e326fdccc39.png)

From this simple UX limitation of "address prefix" in General Settings on website, users are able to see different addresses for the same account. I faced this problem first hand when withdrawing DOT from Binance to Polkadot.js.org wallet. The address i copied was from browser extension with Polkadot as relay chain but my address prefix was Kusama Relay chain in browser app and I was getting error as invalid address.

**Key takeaway**
1. Selected Relay chain on browser extension should be same as Address Prefix on website (Settings > General > address prefix)
2. Based on selected address prefix on website, the browser extension shows addresses, so make sure before copying the address from browser extension that your browser app setting is also correct.

**Resolution.**
1. When on website, the address display panel, when we click on accounts, should mention the selected "address prefix"
2. When on browser extension, the address should show a warning icon if address prefix is different.

**Comment by jacogr** [comment]
Please do not change the settings. It has one use only - for unreleased networks where you need an address. Networks shakil do is play in the ss58 as per the chain spec.

**Comment by saadgit** [comment]
Well if settings are there and its possible to be changed, then as an enhancement in the app, it should cater for new settings in the browser extension.
