### ISSUE TITLE
Untyped null assignment makes TypeScript narrow variable to null

### ISSUE THREAD

**Issue by joao-paulo-parity** [polkadot-js/apps#5399]
https://github.com/polkadot-js/apps/blob/11276477a0523348c7b143db566622aa32833296/packages/react-components/src/Params/OpaqueCall.tsx#L18

https://github.com/polkadot-js/apps/blob/11276477a0523348c7b143db566622aa32833296/packages/react-components/src/Params/Proposal.tsx#L17

Causes the following errors when type-checking with `strict: true`:

```
TS2322: Type 'string' is not assignable to type 'null'.
TS2322: Type 'Proposal' is not assignable to type 'null'.
```

Either the code can be rewriten in order to not use mutation (would be preferrable I think) or an explicit type annotation can be added at those places like

```
 let proposal: Proposal | null = null;
```

I am using `    "typescript": "^4.3.2",`, same as https://github.com/polkadot-js/apps/blob/11276477a0523348c7b143db566622aa32833296/package.json#L29

**Comment by jacogr** [comment]
`let proposal: Proposal | null = null;` is preferable. Contributions welcome, otherwise it is one of those that will eventually be fixed when it actually bites, i.e. TS complains in the repo.
