### ISSUE TITLE
Support Crowdloan with verifier

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/apps#5402]
Crowdloan can be created with a "verifier" forcing contribution to include a signature that only the owner of the "verifier" private key can provide.

PolkadotJs currently allow to directly contribute to each crowdloan listed, however it is not compatible with a verifier as it is not possible to provide the signature.

Suggestions to fix it:
1. Disable the contribute button if the crowdloan contains a "verifier" assigned (safer)
2. Provide the ability for parachains to setup an "official crowdloan contribution" url in the config (a lot better)

**Comment by jacogr** [comment]
https://github.com/polkadot-js/apps/blob/master/packages/page-parachains/src/Crowdloan/Contribute.tsx#L30

(Potentially also https://github.com/polkadot-js/apps/blob/master/packages/page-parachains/src/Crowdloan/FundAdd.tsx#L44, although it can be done via extrinsics as it stands)
