### ISSUE TITLE
Ledger connection issues on latest Chromium version (91)

### ISSUE THREAD

**Issue by michalisFr** [polkadot-js/apps#5406]
Latest versions of Brave (1.25.68 confirmed) have trouble connecting to Ledger to perform actions, either with a "Device was disconnected" or "Unable to claim interface" errors.

Downgrading to 1.24.86 solves this.

**Comment by michalisFr** [comment]
Apparently this is an issue with Chromium version 91 in general. It's verified on arm64 architecture, unsure about x86_64.

**Comment by jacogr** [comment]
No idea, but nothing I can do, not anything that has changed. This is not the first time we have seen these types of issues - last time it was solvable with going into chrome and switching on some USB setting.

**Comment by michalisFr** [comment]
Yeah. We heard back from Zondax and apparently this is affecting multiple teams. They're in contact with Ledger to figure it out.

**Comment by jacogr** [comment]
Relevant LedgerHQ issue https://github.com/LedgerHQ/ledgerjs/issues/607

**Comment by jacogr** [comment]
For the apps UI try the WebHID option now. (The real solution is a fix from Ledger in this case)

**Comment by gre** [comment]
https://github.com/LedgerHQ/ledgerjs/issues/607#issuecomment-853939348
