### ISSUE TITLE
Change UNIT to WND on Westmint

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#5423]
The UI is displaying native balances as "UNIT". Change to "WND".

Same applies for KSM/Statemine.

**Comment by jacogr** [comment]
That comes from the `system_properties` RPC call. If not specified, it applies `Unit`.

There are no chain/spec-specific overrides.

**Comment by jacogr** [comment]
Westend -

![image](https://user-images.githubusercontent.com/1424473/120594052-a3ccef80-c440-11eb-8e61-9e3fe61c8f6c.png)

Westmint -

![image](https://user-images.githubusercontent.com/1424473/120594104-b9dab000-c440-11eb-8194-872c765c83cd.png)

**Comment by joepetrowski** [comment]
Ah, maybe an issue of running collators off the Shell binary. OK, will see what we can do.

**Comment by apopiak** [comment]
We need to ask devops to adjust the chain specs.

**Comment by jacogr** [comment]
Should only be needed on the RPC node, so roll that out first. (then the rest...)

**Comment by jacogr** [comment]
Closed in above Substrate PR.
