### ISSUE TITLE
Uncaught error. Something went wrong with the query and rendering of this component. Invalid array length

### ISSUE THREAD

**Issue by ayushmishra2005** [polkadot-js/apps#5427]
Opening staking module, gives me below error.

<img width="908" alt="Screenshot 2021-06-03 at 12 15 33 PM" src="https://user-images.githubusercontent.com/1575561/120600000-dccb8b00-c465-11eb-9c02-b825bda957f2.png">

Can someone help me to fix this?

**Comment by jacogr** [comment]
No idea. You would need to debug it against your specific (hidden) chain.
