### ISSUE TITLE
Staking is not working with latest polkadot-js/apps

### ISSUE THREAD

**Issue by ayushmishra2005** [polkadot-js/apps#5468]
I am experimenting with staking and getting below error

<img width="908" alt="Screenshot 2021-06-03 at 12 15 33 PM" src="https://user-images.githubusercontent.com/1575561/120927131-66e15100-c6fd-11eb-9c32-e22651c0a4d2.png">

When I checked UI console, I found this

![120660438-f63ff780-c4a4-11eb-9134-276fc4a98e94](https://user-images.githubusercontent.com/1575561/120927176-8d9f8780-c6fd-11eb-847c-7806e67b23b6.png)

 After spending lot of time on debugging, I found that there is an issue with UI compatibility. Its working fine with https://github.com/polkadot-js/apps/tree/v0.91.2 but not with the latest polkadot-js version. I am using SUbstrate 3.0.0.
 
Can someone please help me to fix this? What should I modify in my type definition?

**Comment by jacogr** [comment]
On the Substrate 3.0 tag -

![image](https://user-images.githubusercontent.com/1424473/120931008-00a20180-c6f0-11eb-8da2-ceb853edbfde.png)

**Comment by ayushmishra2005** [comment]
@jacogr I didn't make any change on the node side. However, it started working automatically with latest polkadotJs-apps changes. I am closing this issue now. And I will debug the root cause separately by comparing release version.
