### ISSUE TITLE
Show commission for next era in the targets tab

### ISSUE THREAD

**Issue by jak-pan** [polkadot-js/apps#5477]
There has been a rising trend in validators trying to fake out on nominators. 
They are changing their commission before the era change / election finishes and then change it back. 

These validators show 0 or 1% commission in targets tab but they are indeed 100%

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-02.snakenet.hydradx.io#/staking/query/7HjntvAskE1RXoGrSz3sHYeEmG6narGjiMhUQVaTa4mAcAbn

**Comment by Manser95** [comment]
7LdiCJo1ECGYpcnzwGoQDX6UwYesPxPZ3cKHE8QKa6fzHk9r
7KbPRv8GeNJbjewoB8YxGaCWUcpkdCdigmwvUjmZC4RygeJN
7J74eqVsSLb4tRA4kVuTTCMKK29FCFGD5KstxuLbwcW7eDHb
7HjntvAskE1RXoGrSz3sHYeEmG6narGjiMhUQVaTa4mAcAbn
7JF1JmEg9B9XgGALfvcQ7yvfvFgy3SbgQLGtv1kZrSJLNDu9
7LWYhYzmgWYAcm9aj1yNkqSuyhD9vpX1gbaHKSTYJu3ziw2j

**Comment by admkowal** [comment]
I think that even if we will show next era commission, this fraud still be possible. After changing commision on era start to 0%, next era commission will be 0%. Then before era ends validator can change commission back to 100% which will take effect. And on new era start he can back to showing 0% values on commision.

I would say that we need to show current commision value. Not commision value that is set by validator and which will take effect after the era change. 

If what I said doesn't make sense just ignore it :)

**Comment by jak-pan** [comment]
> I think that even if we will show next era commission, this fraud still be possible. After changing commision on era start to 0%, next era commission will be 0%. Then before era ends validator can change commission back to 100% which will take effect. And on new era start he can back to showing 0% values on commision.
> 
> I would say that we need to show current commision value. Not commision value that is set by validator and which will take effect after the era change.
> 
> If what I said doesn't make sense just ignore it :)

I think this might actually help more but it would probably have the same effect as the next era settings are fixed in the one before it.

**Comment by hill3141** [comment]
What about a green/red light visual alerting if rolling 3 era mean commission is above some threshold (say 10%).
