### ISSUE TITLE
feat: add ability to export network specifications of to-be-launched parachains

### ISSUE THREAD

**Issue by bjornwgnr** [polkadot-js/apps#5500]
Rationale: Ability to generate keys for not-yet-launched parachains in Parity Signer.

Not sure if possible given full network metadata (i.e. genesis hash) may not be available.

See also [related Parity Signer issue](https://github.com/paritytech/parity-signer/issues/778).

**Comment by jacogr** [comment]
The only mapping in the UI is via the information provided, e.g. these chains are currently known on Kusama -

![image](https://user-images.githubusercontent.com/1424473/121181422-48489a80-c862-11eb-8ef8-33c73942dbed.png)

(All the ones in gray)

As soon as they have wasm on-chain (needed for auctions & cowdloans), it means they actually do have an RPC + genesisHash and it is available on the UI. So basically all those become active when the parachain is registered. At that point the QR is already available for that chain. (Only the ones listed, i.e. where the team has provided info)
