### ISSUE TITLE
Set default Edgeware node to OnFinality

### ISSUE THREAD

**Issue by thomivy** [polkadot-js/apps#5513]
Currently the default Edgeware node is Commonwealth Labs, but their stability is less than OnFinality (or Patract's Elara)

Possible to switch the default so users can connect more readily?

**Comment by jacogr** [comment]
The team should just make a PR and swap the order, whichever is best for them. (First is default)

**Comment by jacogr** [comment]
After https://github.com/polkadot-js/apps/issues/5536 the provider is always randomly assigned. The text ordering does make a difference though (people are inclined to click on "the first", so I would still suggest reaching out to the Edgeware team for a PR on this. 

(Generally I don't touch the providers, leaving it to the teams to manage along with their types - there are too many for me to keep track and not do something the teams didn't intend)
