### ISSUE TITLE
Disable Contribute button for some parachains

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#5530]
For moonbeam, people can't contribute to the crowdloan via the Polkadot.js Apps and they are just wasting money paying for gas fees for a transaction that will fail because they need the key that we provide, that is why people need to do attestation first and then crowdloan, both via our dApps.

Would it be possible to blacklist some parachains for the contribute button?

![image (1)](https://user-images.githubusercontent.com/16758383/121343769-54486100-c923-11eb-8c9f-fa40beac0d4c.png)

**Comment by jacogr** [comment]
The apps UI itself allows you to enter the verifier signature (for crowdloans configured that way).

**Comment by albertov19** [comment]
For Moonriver crowdloan, the foundation is not providing this verifier signature to the contributors. The crowdloan dApp will take care of building the transaction for the users. This explains why users need to pre-register (they do so via a system.remark, that stores a hash of the agreed terms and conditions, KSM address and some other data).

It would be great if the contribute button could be "grayed" out or redirected to the official Moonriver crowdloan dApp (I understand this last part is more difficult). I think this will be useful for other parachain projects.

Thanks in advance

**Comment by jacogr** [comment]
So if the users don't have the signature, they can't provide it which means they cannot contribute. That is fine, no additional logic needed.

**Comment by albertov19** [comment]
Yes, correct. But two things:

1. This is creating a lot of confusion among users who have tried (but failed) to contribute via Polkadot.js Apps
2. Users who try and fail waste some KSM on transaction fees right?

By "graying" out the button, or re-directing them to another site, it will be much clearer for the token holders.

**Comment by jacogr** [comment]
Unless they have a valid `MultiSignature` for the verifier a user cannot submit. 

![image](https://user-images.githubusercontent.com/1424473/121385980-e6fbf680-c949-11eb-9ea7-69a724d10379.png)

**Comment by albertov19** [comment]
Ok you are right. This was not the case with the Relay Chain we were testing this with. I tried it against Kusama and checked that the user can't send the transaction. Thanks for clarifying!
