### ISSUE TITLE
addProxy(delegate, proxy_type, delay) is not supported

### ISSUE THREAD

**Issue by Chralt98** [polkadot-js/apps#5535]
Hey,

I found an issue with the addProxy function which is not supported anymore. I tried it with a ledger device and on the polkadot network. It returns a red "addProxy is not supported" error for me. I assume it has something to do with the newest Polkadot app on the ledger.

**Comment by jacogr** [comment]
I really have no idea on what the Ledger device itself supports. The developer, ZondaX, found here 

https://github.com/Zondax/ledger-polkadot

will have more info around what is supported. (Not everything is, the device does have limited space so it is a bit of a juggling act on their side)
