### ISSUE TITLE
Typing error on the parachains page

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#5554]
On Kusama in parachains page: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/parachains

<img width="620" alt="Screenshot 2021-06-10 at 18 11 04" src="https://user-images.githubusercontent.com/16758383/121559829-3d833680-ca17-11eb-9111-19e31d9eba9a.png">

**Comment by jacogr** [comment]
Weird, cannot reproduce clicking through.

**Comment by joelamouche** [comment]
Ha yes indeed I had leftover types in the dev console 🤦 sorry about that

**Comment by jacogr** [comment]
There is an issue logged to make types specific to a chain - you are not the only dev this happens to, there are at least two of these a week (that I know of, there are no doubt more) where somebody wastes time due to this.
