### ISSUE TITLE
Crowdloan in Network > Parachains > then the crowdloan link shows wrong interface

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#5555]
If you go to Network > Parachains > then the crowdloan link from menu then the + contribute button to get that pop up, you will see this wrong interface:
![image (3)](https://user-images.githubusercontent.com/16758383/121560955-550eef00-ca18-11eb-8fa4-4875c693ed1c.png)

But  if i got to developer > extrinsic > then the crowdloan - contribute it’ll work
![image (2)](https://user-images.githubusercontent.com/16758383/121561059-69eb8280-ca18-11eb-9d34-7f90e00545f8.png)

**Comment by jacogr** [comment]
It actually expects the full `MultiSignature` hex encoded. So in this case, since it is ed25519, it will be `0x0298...` (extra 02 at the start)

**Comment by jacogr** [comment]
No. In this case since the hex is provided, rather not expect the users to know which type of signature it is as well. So it is treated as an opaque properly-encoded blob.

**Comment by joelamouche** [comment]
OKay sounds good
