### ISSUE TITLE
Sudo UI not available for proxies of sudo key

### ISSUE THREAD

**Issue by PierreBesson** [polkadot-js/apps#5584]
The current sudo UI blocks access for users who don't have the sudo key. However this prevents legitimate use by users who have access to a proxy of the sudo key.

![Screenshot-20210614112727-895x215](https://user-images.githubusercontent.com/513471/121870769-a8788a00-cd03-11eb-9608-757c2f4e62e1.png)

Remark: if I add the sudo key to my keystore again, the sudo UI does become available and sudo calls can be successfully executed through the proxy so the only change required would be to stop displaying the warning message for proxies of the sudo key or add a bypass button.

**Comment by PierreBesson** [comment]
I confirm this works after adding a proxied account. So I guess this issue can be closed, if you think this shouldn't be a feature offered by the UI.

**Comment by jacogr** [comment]
Yes, deep queries are not going to be added. The "proxied account" is there to allow you to select and perform operations on any accounts where you only have signer-capabilities with a proxy. So it does exist, just not in the form you expected :) (But has the benefit that you have full access to the account from everywhere, transfers, council, staking, etc.)
