### ISSUE TITLE
Adding outcome table to auction page

### ISSUE THREAD

**Issue by jonasW3F** [polkadot-js/apps#5625]
The auctions are generally very complicated to understand for the average user. Specifically, the fact that a winning bid for a package does not necessarily lead to that project actually winning. And even if you know that it could get quickly too cumbersome to compute the final allocation given the current bids.

Therefore, I suggest adding an "Outcome Table", that shows the distribution of leasing periods to the bidders given the latest bids (as if the auction is ending now). I made a quick sketch of some fictional outcome of the current auction.
![outcome table](https://user-images.githubusercontent.com/67730419/122380500-3b196300-cf68-11eb-8e2a-ae95659ecf59.png)

**Comment by jacogr** [comment]
Sure, it has been logged by Shawn a while ago as part of https://github.com/polkadot-js/apps/issues/4905 - PRs welcome to add it.
