### ISSUE TITLE
Execute dry-run RPC of contract constructor before deployment of contract

### ISSUE THREAD

**Issue by cmichi** [polkadot-js/apps#5629]
In https://github.com/paritytech/ink/issues/821 we found that debug messages which are printed in contract constructors do not appear on the console. Debug messages in functions of an instantiated contract appear though. This is because

>Debugging is not enabled during on-chain execution. Only during RPC calls.

In order to support debug messages in constructors the UI should execute a RPC dry-run of the constructor before deployment of a contract.

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/apps/issues/5338 - would suggest adding extra info there as needed.
