### ISSUE TITLE
Adjust Number Entry

### ISSUE THREAD

**Issue by apopiak** [polkadot-js/apps#5667]
When e.g. opening the modal overlay for creating a transaction that requires entering a number the following behavior is observed:
+ the field is initialized with zero
+ the cursor is automatically placed in the number field, *behind* the zero
+ the field is (potentially) marked red to indicate an invalid value
+ I cannot enter any numbers

This means that I need to delete the 0 to then be able to enter the number I want to enter.
Potential fixes:
+ don't initialize the field (to zero)
+ allow number entry with leading zeros
+ place the cursor before the zero

**Comment by apopiak** [comment]
I think it's still relevant :-D

**Comment by apopiak** [comment]
I think it's relevant.
@jacogr ?

**Comment by maciejnems** [comment]
In our project we also think that this is relevant and could make user experience better. I prepared a small PR (https://github.com/polkadot-js/apps/pull/5963) that could be a solution to this problem. After this change InputBalance doesn't contain zero by default.
