### ISSUE TITLE
Karura shown as current auction leader

### ISSUE THREAD

**Issue by laboon** [polkadot-js/apps#5672]
Karura and not Moonriver is being shown as the winner of the current auction on the Auctions page, but Karura has already won the last auction.

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/parachains/auctions

Looking at the auctions.Winning data, this may not be a UI issue, since I see the Karura fund amount there and not Moonriver's.

<img width="627" alt="Screenshot 2021-06-24 at 10 19 36" src="https://user-images.githubusercontent.com/1417717/123247018-b6d65b00-d4e6-11eb-80f1-9ae2e27ebb2a.png">

**Comment by jacogr** [comment]
2000 is the paraId for Karura.

So when the end period has not yet started, the UI will interleave the crowdloans. (We indeed had a UI issue there right at the start) 

In this case as you have indicated, the UI is using the data from WinningData itself, which seems wrong in this specific case.

**Comment by jacogr** [comment]
Closing, not a UI issue and nothing that can be done here - will be fixed in the next Kusama runtime update.

Relevant runtime PRs that addresses this issue on-chain -

https://github.com/paritytech/polkadot/pull/3346
https://github.com/paritytech/polkadot/pull/3361
