### ISSUE TITLE
Nominator count is incorrect

### ISSUE THREAD

**Issue by michalisFr** [polkadot-js/apps#5696]
Under Staking > Overview the number of nominators is shown as less than 20k but `staking.counterForNominators` shows more than 21k.

New nominators get `error.TooManyNominators` and are confused as to why

![Screenshot 2021-06-26 at 10 55 03 PM](https://user-images.githubusercontent.com/45905709/123524250-94546580-d6d1-11eb-905c-47471302ef9c.png)

![Screenshot 2021-06-26 at 10 46 27 PM](https://user-images.githubusercontent.com/45905709/123524251-961e2900-d6d1-11eb-9a92-4fc97c024750.png)

**Comment by sergeiwallace** [comment]
I got this error! Please fix ASAP! I wasted my precious DOT on failed transactions :/

**Comment by jacogr** [comment]
That is not the total number of system nominators, it is the total number of active nominators. (totals active + inactive are not show)

**Comment by michalisFr** [comment]
Thanks for clarifying @jacogr! What is "active" in this context? More than 20 DOT stake? Or nominating at least one validator in the active set?

**Comment by jacogr** [comment]
The actual number of nominators that are participating in the active set. (That is what you referred to, incorrectly, as a "wrong value" - it has always been the number of nominators participating, since that page is the "active in set" page, both validators and nominators)

**Comment by michalisFr** [comment]
I always assumed this number was the total number of nominators 😄 Never really thought of nominators as "active" and "inactive" TBH, although obviously there are both.

Thanks for the explanation and for making it clearer in the UI @jacogr. Everyone now is interested in the total number for obvious reasons.
