### ISSUE TITLE
Ledger account fails to nominate with staking.TooManyNominators

### ISSUE THREAD

**Issue by iurii-milovanov** [polkadot-js/apps#5697]
Hi There,

Whenever I'm trying to nominate any validator(s) on polkadot.js using my Ledger account (via WebHID on MacOs), my transaction fails with the following error:
`staking.TooManyNominators`
_There are too many nominators in the system. Governance needs to adjust the staking settings to keep things safe for the runtime._

Is that just me, or everyone is experiencing the same now?

- Parity Polkadot v0.9.6
- api v4.16.1
- apps v0.93.2-56

Thanks

**Comment by laboon** [comment]
This is not a UI issue, but rather an expected change to the staking system. See https://polkadot.network/polkadot-and-kusama-staking-changes/

**Comment by XavierEr** [comment]
The UI in https://polkadot.js.org/apps could have prevented new nominators from nominating if the limit has reached. This can help with unnecessary dot wasted for transaction fees.
