### ISSUE TITLE
Unable to Initialize API Using Docker Image

### ISSUE THREAD

**Issue by VincentSaelzler** [polkadot-js/apps#5701]
I am using jacogr/polkadot-js-apps:latest
(digest `8aefb4277a41aa94b1fed68f0576afb4e15c1c8aa9284a83ad4a882f43e6e57b`)

When I navigate to the root page, I get an error message on the top right.
The message is the same for both Kusama and Polkadot (both hosted by Parity)
```
FATAL: Unable to initialize the API: createType(&'static[u8]):: Cannot construct unknown type &'static[u8]
```
When I change to Rococo, there is a similar but slightly different error:
```
FATAL: Unable to initialize the API: createType(BridgedBlockHash):: Cannot construct unknown type BridgedBlockHash
```
Westend, once again, shows a similar but slightly different error:
```
FATAL: Unable to initialize the API: createType(ValidationCodeHash):: Cannot construct unknown type ValidationCodeHash
```

**Comment by jacogr** [comment]
The docker image is outdated, it has not been published in 2 weeks now - and there has been a number of changes in types.
