### ISSUE TITLE
Allow submit transaction in Extrinsics -> Decode page

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#5746]
I want to generate extrinsic via script and submit in polkadot apps using the extension to sign the transaction.

This will allow me to generate the tx with a script and paste the encoded data and have it decoded so I can review it and then sign and send it using polkadot extension.

**Comment by xlc** [comment]
I am trying to implement a button in Decode page that will go to Submission page and fill all the fields but I feel I am going down a rabbit hole and not feeling comfortable to do the change myself because it seems a lot of refactoring required.  

https://github.com/polkadot-js/apps/compare/master...AcalaNetwork:decode-goto-submission?expand=1

**Comment by h4x3rotab** [comment]
It's useful. Sometimes we need to build an extrinsics offline, and want to sign & submit with polkadot.js extension for security reason.
