### ISSUE TITLE
Extra bytes are ignored in Extrinsic -> Decode page

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#5747]
`0x000300` is `system.setCode(0x)` and I can append more hex and getting the same thing.

**Comment by jacogr** [comment]
Yes, it doesn't re-construct the extrinsic to test against the original. Only checking it does do is when decoding goes wrong.

Decoding -

```js
// hex prefix
0x
// system module
00
// setCode
03
// length = 0 (0 >> 2 = 0)
00
// everything after this is ignored
```
