### ISSUE TITLE
Types on Realis.Network

### ISSUE THREAD

**Issue by Daelon02** [polkadot-js/apps#5748]
Hi, we have a little problem, we dont add new types in our blockchain, but in polkadot-js/apps throw error about types. In UI we added all our types
![Screenshot_2](https://user-images.githubusercontent.com/63471940/124278154-947bb780-db4e-11eb-9c9f-4d0f433d4e2f.png)

**Comment by jacogr** [comment]
If you connect to it you can see that your specName is no `realis` as per the mapping -

![image](https://user-images.githubusercontent.com/1424473/124280143-9f334e00-db48-11eb-9f09-b1eae44b30be.png)

(Top left, specName/specVersion)
