### ISSUE TITLE
Support submitting non-mutating contract calls as transactions

### ISSUE THREAD

**Issue by cmichi** [polkadot-js/apps#5751]
The ink! example [`contract-transfer`](https://github.com/paritytech/ink/blob/master/examples/contract-transfer/lib.rs) contains this function:
```
#[ink(message, payable, selector = "0xCAFEBABE")]
pub fn was_it_ten(&self) { … }
```

The notable thing about this function is that it is 
```
"mutates": false,
"payable": true,
```
The `canvas-ui` supports this case, but the `polkadot-js` UI doesn't. There is no way of specifying that the non-mutating, payable call should be executed as a transaction with value:

![payable](https://user-images.githubusercontent.com/241530/124289465-a65f5980-db52-11eb-83bd-d67481bc7a68.png)

We think it makes sense to have `&self` contract messages, which can also be payable. This way one can still have the Rust-guarantees of non-mutation for a function, while having the function receive value.

So it would be great if the UI could support this. Maybe the easiest would be to allow submitting non-mutating calls as transactions?

Here's the contract file: [contract_transfer.contract.zip](https://github.com/polkadot-js/apps/files/6755246/contract_transfer.contract.zip).

**Comment by jacogr** [comment]
Makes sense that it should allow both, not sure why the canvas-ui reference is in here - that has nothing to do with this project, we don't track what they may/may-not do, I'm assuming there may be some overlap in functionality. But certainly other projects don't drive the apps UI.

**Comment by cmichi** [comment]
Thanks for implementing this!

I'm having the following issue though:

* I deploy [contract_transfer.contract.zip](https://github.com/polkadot-js/apps/files/6755246/contract_transfer.contract.zip).
* I expand the messages for that contract and click the `Read` button besides `wasItTen()`.
* The dialog shows up and I enter `10` into `value`.
* The `Execute` button is still greyed out.

If I switch the `message to send` in the dialog to `giveMe` (a mutating message) and then back to `wasItTen()` the `Execute` button becomes activated.

I just tried on the latest published version, which contains your commit.

**Comment by cmichi** [comment]
@jacogr I can't reopen the issue, but have you seen my comment above?
