### ISSUE TITLE
fast track proposal should allow manually override threshold

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#5800]
<img width="754" alt="Screen Shot 2021-07-09 at 6 22 45 PM" src="https://user-images.githubusercontent.com/1201310/125032851-a925f580-e0e2-11eb-95da-a54c73259476.png">

I need to make threshold to 3 to make immediate execution but can't change it

I think in general, threshold should be editable just because parachains may have different requirements

**Comment by jacogr** [comment]
No, it won't be made editable. However in this case we have a missing threshold param in the overrides which means it is not configurable between different chains - 

https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/params/proposalThresholds.ts

i.e. the fast-track option should be added there as well

**Comment by xlc** [comment]
Why it cannot be editable? There are two requirements for fast track: https://github.com/paritytech/polkadot/blob/f9d71f8c7eb1992efefcba17ed530c1440adb224/runtime/kusama/src/lib.rs#L558-L559

Otherwise it need to check voting period and pick the right threshold.

**Comment by jacogr** [comment]
It does check the voting period and picks the correct one.

**Comment by xlc** [comment]
My point is, it could pick the wrong value (e.g. if we did an upgrade and change something, but not yet update here). So it will be helpful to "trust me, I know what I am doing" and override the suggested value.

**Comment by jacogr** [comment]
In that case, there is always the extrinsic page. 

We actually used that form a bit before we had dual-thresholds for the Kusama & Polkadot TC and needed to push through very short periods and it is fine.
