### ISSUE TITLE
Dont use middle `...` fake truncation in UI

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/apps#5803]
Just some personal feedback, there are some areas where the UI does a superficial truncation where some long data, like the code of a chain, has the following look:

```
0xFRONTCODE ... BACKCODE
```

This is something artificial to polkadot js, and when copying this data, you only get the truncated string.

When the browser truncates the data for you, you can still copy and paste the full underlying data:

```
0xFRONTCODEONLY...
```

Having access to the full data can be very helpful, probably more so than reading the last couple of bytes of the value, so I would suggest to not use this artificial truncation.

**Comment by jacogr** [comment]
Beauty is in the eye of the beer holder - so I always compare front and back parts when looking for matches, eg. when re-checking set keys, hashes available, etc. 

So it has been done with my use case in mind.

**Comment by shawntabrizi** [comment]
is it possible to maintain copy functionality of the real underlying item?
