### ISSUE TITLE
storage fee unit estimation for submit preimage is incorrect

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#5808]
<img width="1063" alt="Screen Shot 2021-07-12 at 12 00 51 PM" src="https://user-images.githubusercontent.com/1201310/125213974-cf2cdf00-e308-11eb-95e5-87d68fd1b966.png">

The unit is always `pico` no matter what.

**Comment by jacogr** [comment]
Ummm.... it is the display, the balance component seems to incorrectly show the units.
