### ISSUE TITLE
Apps loading ignores previous set connection

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#5814]
When loading, last round I was on Kusama, it loads Polkadot (incorrectly) but the sidebar selection still shows Kusama (correctly)

Introduced in https://github.com/polkadot-js/apps/pull/5644

**Comment by kukabi** [comment]
I confirm it happening on Safari and Chrome.

**Comment by jacogr** [comment]
Looked. The solution here, simplest, is to swap protocol to light:// and then only use the URL everywhere. 

The Switcher only saves the actual URL. The his is an extra bonus that it is available in the custom box as well.
