### ISSUE TITLE
 a problem establishing an on-chain identity

### ISSUE THREAD

**Issue by SebastianCripto** [polkadot-js/apps#5819]
![Captura de pantalla (524)](https://user-images.githubusercontent.com/82742336/125334259-8df4f900-e321-11eb-941b-b401498eff79.png)

Hello, when establishing an identity, in the "email" section, the last letter of my email does not enter, I suppose it is because there are a limited number of letters that can enter. As you can see in the image, the last letter "m" is missing. My full email is: antoniorodriguezvigiano@gmail.com. I hope there can be a solution.Thanks

**Comment by jacogr** [comment]
The fields are limited to a max of 32 characters on-chain. The only way to store larger values is to not store the data, but rather the hash (which will also be 32 bytes). 

Because of the on-chain runtime limit, the UI also imposes the same 32 character limit.

**Comment by SebastianCripto** [comment]
# @jacogr That's what I thought, thanks, I'll use a shorter email. Thanks again for the quick reply.

**Comment by SebastianCripto** [comment]
@jacogr That's what I thought, thanks, I'll use a shorter email. Thanks again for the quick reply.

**Comment by Swader** [comment]
Related: https://github.com/paritytech/substrate/issues/8888
