### ISSUE TITLE
@polkadot/apps-config

### ISSUE THREAD

**Issue by killbond007** [polkadot-js/apps#5847]
Hello polkadot，
    in version 0.94.2-xx @polkadot/apps-config
i found 
**warning  in ./node_modules/@polkadot/apps-config/api/spec/equilibrium.js
"export 'map' was not found in 'rxjs'**

in apps-config， rxjs not found in package.json ？

**Comment by jacogr** [comment]
It is rxjs related, see https://github.com/polkadot-js/api/issues/3775
