### ISSUE TITLE
How to get a call's components from a call hash?

### ISSUE THREAD

**Issue by joao-paulo-parity** [polkadot-js/apps#5849]
First of all a disclaimer that I don't understand how it works as a whole, so feel free to ignore the non-sensical parts.

Following this code:

https://github.com/polkadot-js/apps/blob/42c5e4ae6c343181f780a29a00b7b71aed6bd744/packages/page-extrinsics/src/Decoder.tsx#L47-L52

It seems that it's possible to dissect the extrinsic's components (hash, arguments, etc) from the call *data*. Is it possible to do the same from a call hash?

i.e. how do I go from this example call hash:

`0xbd31e7e4ca4185cc4427392d589b54c67420ddd0f1a8d621affe29bb6bbd73dd`

which has the following components:

**Decoded call**: `{"callIndex":"0x0001","args":{"_remark":"0x31"}}`
**Encoded call**: `0x00010431`

to the `extrinsicCall` as shown in that code?

**Comment by jacogr** [comment]
Unless it is stored on-chain, no. Hashes are one-way cryptographic operations. So in -> out, non-reversible.

**Comment by joao-paulo-parity** [comment]
The reason why I thought it would be possible, in the first place, is that the hash seems to be deterministic - at least for my local development node - in the sense that the same extrinsic will be hashed to the same value when provided the same arguments. And specifically I want to dissect the arguments from it, not "restore the call" object exactly.

Could you point me to some resources for learning more about how this hashing works? I want to understand how it's processed on the blockchain.

**Comment by jacogr** [comment]
Substrate uses blake2 by default (the 2b variant). https://en.wikipedia.org/wiki/BLAKE_(hash_function)

And yes, it is deterministic, the same input generates the same output.

**Comment by kianenigma** [comment]
You can never go from `hash(data)` to the original `data`, as Jaco said.

Extrinsic hashes are not stored anywhere on chain. 

If you have an extrinsic hash and want to inspect it, your only way is to query a full node for blocks, until you find the block that contains this call hash. Then, you go over the extrinsic of that block and find the one which ash the same has as yours.

**Comment by joao-paulo-parity** [comment]
Searching through the blocks is a interesting suggestion. Thanks for the responses!
