### ISSUE TITLE
"Invalid byte where token is required" when polkadot-js/apps is trying to reach a remote node on a server

### ISSUE THREAD

**Issue by sebastiendan** [polkadot-js/apps#5863]
Hi,

I'm running an instance of substrate-node-template on a private server, with the `--ws-external --rpc-external --rpc-cors all` flags. With this setup, what I usually do to quickly access my node via polkadot-js/apps is running the project locally in docker (to circumvent the ws security errors that the hosted version would raise when trying to connect to a node via a server IP).

Today, I get the following error in my substrate node logs:
```
2021-07-21 14:36:26 Accepted a new tcp connection from ***.***.***.***:34662.    
2021-07-21 14:36:26 WS Error <Http(Token)>: Invalid byte where token is required.    
2021-07-21 14:36:27 Accepted a new tcp connection from ***.***.***.***:45405.    
2021-07-21 14:36:27 WS Error <Http(Token)>: Invalid byte where token is required. 
```

I also tried to access my node through polkadot-js/api and the api-sidecar projects, both are working fine.

**Do you have any idea what's wrong here?**

---
I run the substrate node like so:
```
./target/release/node-template --unsafe-ws-external --rpc-external --rpc-cors all --base-path /tmp/alice --dev
```

**Comment by jacogr** [comment]
https sites can only connect to wss (secure) endpoints.

**Comment by sebastiendan** [comment]
@jacogr Yes, that's exactly why I run my own local instance of polkadot-js/apps instead of using the hosted one.

**Comment by jacogr** [comment]
The above error generally points to a ws vs wss mismatch, i.e. you may have specified the endpoint as wss (secure) while it is ws (insecure). More than that I cannot comment, generally don't run any infrastructure myself.

**Comment by sebastiendan** [comment]
I simply run the docker container like so:
```
docker run --rm -it -e WS_URL=ws://20.89.176.216:9944 -p 80:80 jacogr/polkadot-js-apps:latest
```

I also tried outside of docker, building the app with `yarn` and access `localhost:3000`+specificying the right ws endpoint.

**Comment by jacogr** [comment]
Sorry. Out of my wheelhouse. Cannot help in this case since I don’t run or setup remote nodes.

**Comment by jacogr** [comment]
No, it is not on the apps side.

You are connecting to an insecure websocket - this cannot be done via https. You can only do wss from https sites.

**Comment by sebastiendan** [comment]
Yes, I know this restriction but it doesn't apply to my case, as I'm connecting to my substrate node via localhost (http) which should work with an insecure ws (not wss) endpoint like mine.

If you look at the beginning of this thread, I was testing polkadot-js/apps locally to achieve the same goal (=> reaching an insecure ws endpoint from an insecure http base).

**Comment by jacogr** [comment]
The apps UI uses the same polkadot-JS API. This is not an apps issue. This is a local issue.
