### ISSUE TITLE
Staking Page, Targets Tab

### ISSUE THREAD

**Issue by dxyzab** [polkadot-js/apps#5875]
In the 'nominators' column, there are two numbers. The first number looks like the number of nominators and agrees with the number of  addresses that appear in the Overview Tab for that validator. 

Could some explanation be added for the second number?
![Screen Shot 2021-07-25 at 9 54 59 AM](https://user-images.githubusercontent.com/1844552/126907069-71e44cf0-257a-4846-ab2d-d5529747feff.png)

**Comment by jacogr** [comment]
The second is the total number of people nominating the validator - obviously, Phragmen selects the best from the list to get to the first number of the active nominators for a specific era.
