### ISSUE TITLE
payment.queryInfo unavailable on Statemine

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#5880]
![image](https://user-images.githubusercontent.com/1430603/127151341-b1631909-1bcf-407b-ba3e-e718022fce1f.png)

This happens when trying to use a multisig wallet, seems to work otherwise.

**Comment by Swader** [comment]
@jacogr hate to bother, but a pointer to a workaround if possible or an estimation of fix difficulty would be super appreciated just so we know where we stand

**Comment by jacogr** [comment]
There is no work-around until Statemint has payment_queryInfo, it is used here - https://github.com/polkadot-js/apps/blob/master/packages/react-signer/src/TxSigned.tsx#L123

We need the weight for the multisig call, so without being able to get to it, it will never work.

**Comment by Swader** [comment]
Thank you.
Tracking this here: https://github.com/paritytech/cumulus/issues/542 and will close this
