### ISSUE TITLE
Rendering the details of motion 337 fails 

### ISSUE THREAD

**Issue by hirschenberger** [polkadot-js/apps#5899]
![image](https://user-images.githubusercontent.com/1053180/127734370-e681b500-7e2a-48dc-9f58-89c2089b3c3b.png)

**Comment by jacogr** [comment]
![image](https://user-images.githubusercontent.com/1424473/127760317-4599c9d4-aaa3-45fd-9fb1-ca2607e75887.png)

Are you using IPFS via dotapps.io? That needs a refresh, it will _probably_ update tomorrow.

**Comment by hirschenberger** [comment]
Yes it was an IPFS version.

**Comment by jacogr** [comment]
Sadly it is around 3 weeks old now, there has not been an updated publish to it for that long (it is meant to be weekly)

**Comment by jacogr** [comment]
IPFS version now aligns with master.
