### ISSUE TITLE
Adapt block time to non-babe parachains

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#5910]
## Problem

Currently, block time is computed this way:

```
const blockTime = (
        a.consts.babe?.expectedBlockTime ||
        a.consts.difficulty?.targetBlockTime ||
        a.consts.timestamp?.minimumPeriod.muln(2) ||
        DEFAULT_TIME
      );
```

But for parachains that dont use `babe` nor `difficulty`, and for which `timestamp?.minimumPeriod` doesnt make sens, we need to specify a value.

## Proposal

If the parachainSystem pallet is there, set the blocktime to 12000

**Comment by joelamouche** [comment]
@bkchr what do you think

**Comment by jacogr** [comment]
As the last (prior to default) fallback, sounds sane.

**Comment by joelamouche** [comment]
I would put it before `a.consts.timestamp?.minimumPeriod.muln(2)` because our timestamp.minimumPeriod is not consistant with block time and is set to zero

**Comment by jacogr** [comment]
Don’t believe that is right. Can certainly add a zero check, but no assumptions at this point for parachain fallbacks. Since it means rework.

**Comment by bkchr** [comment]
> I would put it before `a.consts.timestamp?.minimumPeriod.muln(2)` because our timestamp.minimumPeriod is not consistant with block time and is set to zero

Why?

**Comment by joelamouche** [comment]
Sorry I meant it's set to one

**Comment by jacogr** [comment]
It is supposed to be blocktime / 2 for Aura -

```rust
		/// The minimum period between blocks. Beware that this is different to the *expected* period
		/// that the block production apparatus provides. Your chosen consensus system will generally
		/// work with this to determine a sensible block time. e.g. For Aura, it will be double this
		/// period on default settings.
		#[pallet::constant]
		type MinimumPeriod: Get<Self::Moment>;
```

So for aura parachains, should be 6000

**Comment by JoshOrndorff** [comment]
> It is supposed to be blocktime / 2 for Aura

That's true. But Moonbeam is not using Aura.

>  >  timestamp.minimumPeriod is not consistant with block time and is set to <del>zero</del> one
>
> Why?

The Moonbeam runtime is used in multiple different contexts. The most obvious one, and the one @joelamouche is trying to fix here is the parachain context. However our runtime is also used in an instant-sealing node for unit tests, and for development (both our own internal development, and smart contract devs targeting Moonbeam). There is no reason that blocks can't come in very close succession in the instant sealing node.

`pallet_timestamp`'s [own docs](https://github.com/paritytech/substrate/blob/master/frame/timestamp/src/lib.rs#L126-L131) remind us to `Beware that this is different to the *expected* period that the block production apparatus provides.`.

While calculating the expected block time from the min block time may be suitable in some cases (as it is for Aura), that is not the case in general, and is not consistent with the semantics of the `MinimumPeriod` field.

**Comment by JoshOrndorff** [comment]
I'll also share this for context https://github.com/PureStake/moonbeam/pull/250

That's when and why we first lowered our MinimumPeriod.
