### ISSUE TITLE
democracy delegate should allow any accounts

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#5919]
Currently only limit to own accounts.
Isn't the whole point of delegation is that you can delegate your votes to someone else you trusted?

**Comment by jacogr** [comment]
It is, however like a number of places this is limited to accounts since I have enough support overhead from people shooting themselves in the foot.

Extrinsic allows all for power users.

**Comment by xlc** [comment]
This won’t do much real harm and can be easily reverted? 

We do indent to ask everyone to participate governances by delegating their votes, just like most of other eth protocols.

**Comment by jacogr** [comment]
Support-wise, this is a nightmare.

So this scenario is one I've already had to spend countless hours on in support -

- user delegates with 2x conviction
- person delegates votes
- clocks runs out on lock, funds unlocked
- user un-delegates
- now funds are locked again for 2x period and he/she cannot move them

On own accounts the above scenario is still "bad", but at least the saved-stashes normally delegates to a "voting account", so the impact seen in the wild is much less.

Never say never, but as of now, no appetite.

**Comment by xlc** [comment]
- user un-delegates
- now funds are locked again for 2x period (delegated conviction) and he/she cannot move them

this makes no sense and sounds like an issue on Substrate...

**Comment by xlc** [comment]
Ok that's intended behavior (still not making any sense to me) and we don't have enough educational material about this.
