### ISSUE TITLE
Allow to pass negative number for i32

### ISSUE THREAD

**Issue by jerryjren** [polkadot-js/apps#5920]
Hi there,

I'm new to polkadot and substrate. I got an interesting issue, where I have specified i32 as the input parameter in the pallet. But in the UI, seems like I could only enter a positive number, see below. Is any workaround that would allow me to pass a negative number? Thanks in advance, much appreciated.

![Screen Shot 2021-08-05 at 15 18 53](https://user-images.githubusercontent.com/5989009/128285851-41f785fd-58cd-4a88-8a9c-cda37280dc3d.png)

**Comment by jacogr** [comment]
The UI doesn't support it, the number inputs only allow positive values. There is no workaround UI-wise.

**Comment by jerryjren** [comment]
Hi @jacogr , thank you for your reply. Do you know the technical reason why the UI doesn't support it?

Thank again

**Comment by jacogr** [comment]
I have not felt a need to support it, since it never has been a problem for me on the chains I interact with.

**Comment by jerryjren** [comment]
Great. Thanks @jacogr

Do you mind point me to the place where the change needed to enable this functionality?

**Comment by jacogr** [comment]
This is the underlying component - https://github.com/polkadot-js/apps/blob/master/packages/react-components/src/InputNumber.tsx

I would guess (have not looked as of now) that you need to pass an `isUnsigned` flag.

The only issue I foresee is in the max length calcs, i32 is slightly different.

**Comment by jerryjren** [comment]
Thank you @jacogr , much appreciated
