### ISSUE TITLE
Staking app Account Actions shows unnominate for all accounts

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#597]
![screen shot 2019-01-14 at 2 11 22 pm](https://user-images.githubusercontent.com/1201310/51093240-5bc4b800-1806-11e9-81fe-9946f65c930b.png)

It flash Stake and Nominate buttons for brief amount time and all become unnominate for all accounts.

**Comment by jacogr** [comment]
Dangit. Ok, I see what goes wrong here - the defaults coming back from the chain makes it act is if there are values, when there are none. Ok, this is not good.
