### ISSUE TITLE
Unable to load block 293070 of chachacha

### ISSUE THREAD

**Issue by dzhelezov** [polkadot-js/apps#5980]
To reproduce:

- Navigate to [Chachacha Explorer](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ffullnode-relay.chachacha.centrifuge.io#/explorer) of polkadot.js.org/apps
- Go to block hash `0x8b20fd05de5bfa002c50b7f7391524fd59741b1e34a40a54728ad565f8c9f058` (height 293070)

The following error occurs:
```
Unable to retrieve the specified block details. Unable to decode storage system.events:: createType(Vec<EventRecord>):: decodeU8a: failed at 0x020b02089696cec6… on : {"phase":"Phase","event":"Event","topics":"Vec<Hash>"}:: decodeU8a: failed at 0x0b02089696cec65b… on event: {"index":"EventId","data":"Null"}:: Struct: failed on data: (Vec<IdentificationTuple>):: decodeU8a: failed at 0x089696cec65b82ef… on : Vec<IdentificationTuple>:: decodeU8a: failed at 0x9696cec65b82ef8e… on : (ValidatorId,FullIdentification):: decodeU8a: failed at 0xa2f9ad152507b8fa… on : {"total":"Compact<Balance>","own":"Compact<Balance>","others":"Vec<IndividualExposure>"}:: decodeU8a: failed at 0xb8fae0d248983c74… on others: Vec<IndividualExposure>:: decodeU8a: failed at 0xfae0d248983c7445… on : {"who":"AccountId","value":"Compact<Balance>"}:: decodeU8a: failed at 0x6f6e6c696e653a6f… on value: Compact<Balance>:: Balance: Input too large. Found input with 180 bits, expected 128
```

**Comment by jacogr** [comment]
The specific chain does not have the correct historic types. The team behind the chain needs to update them to reflect current/historic.

**Comment by dzhelezov** [comment]
But chachacha is supposed to work w/o any custom types similar to Kusama, isn't it? I can't see how to find the right type overrides.

**Comment by jacogr** [comment]
Kusama, Polkadot, Rococco, Westend all has custom types, based on the spec version that the API injects.

**Comment by dzhelezov** [comment]
I see, thanks for the link!
