### ISSUE TITLE
[Question] How to support several wallets? (wallet selection)

### ISSUE THREAD

**Issue by paulvi** [polkadot-js/apps#5992]
How to support several wallets? 
 
 I have looked at `packages/react-api/src/Api.tsx`
 https://github.com/polkadot-js/apps/blob/master/packages/react-api/src/Api.tsx#L127
 ```
 async function loadOnReady (api: ApiPromise, injectedPromise: Promise<InjectedExtension[]>, store: KeyringStore | undefined, types: Record<string, Record<string, string>>): Promise<ApiState> {
  registry.register(types);
  const { injectedAccounts, properties, systemChain, systemChainType, systemName, systemVersion } = await retrieve(api, injectedPromise);
```

The `retrieve()` will call `getInjectedAccounts(injectedPromise)` that has `const accounts = await web3Accounts();`
So interaction with Wallet start with already injected `web3` API, that means that browser extension should be already installed and enabled for the web site, e.g. trying on https://polkadot.js.org/apps

Is there other place to look to support more/many wallets?

**Comment by jacogr** [comment]
Yes, the apps UI supports the extension as available, hence the call.

**Comment by paulvi** [comment]
Thanks
Closing for now
