### ISSUE TITLE
strange parachain UI after upgrading to polkadot-v0.9.9

### ISSUE THREAD

**Issue by GopherJ** [polkadot-js/apps#5994]
before upgrading, we can see validators & included numbers etc, now cannot see them anymore, but the parachain works as expected
![image](https://user-images.githubusercontent.com/33961674/130469086-02bc2b0e-4d77-4e3b-a57c-505c39576a3b.png)

**Comment by jacogr** [comment]
Apparently somebody thought it was a good idea to rename all the parachain modules. Eg. until 9080 stuff like the scheduler was under `parasScheduler`, now it sits under `paraScheduler`. (Note the missing `s`)

So this broke -

- any API aliasses that are injected
- all the places the UI actually looks

**Comment by GopherJ** [comment]
> `parasScheduler`

I would prefer `parasScheduler` indeed
