### ISSUE TITLE
Calling Propose + vote(Approve) in Technical Committee when opening proposals 

### ISSUE THREAD

**Issue by rrtti** [polkadot-js/apps#6015]
With v9090 on Kusama, proposals can be opened without casting a vote by calling `Propose`. This works for Council, so a councillor can push a proposal to motion without voting, but it does not for TC: when a TC seat opens a proposal, an `Aye` vote should be casted when opening the proposal from that seat as well. Before v9090 the `Propose` call would include auto vote.

We should add this to TC: the suggestion is to fix this in the UI level so a `BatchAll` call can include `Propose` + `Vote(approve)`.

**Comment by jacogr** [comment]
Do we have a link to the Substrate PR that introduced this? I need to get some way of detecting old vs new.

**Comment by jacogr** [comment]
This is not as simple as proposed. To vote we actually need the proposal hash (the one being voted on) as well as the actual id of the proposal. As long as things remain static, proposal not an issue. But basically if something goes into the queue we are back at square 0 and need to re-submit via `batchAll` or just use `batch` and needing to submit the vote anyway.
