### ISSUE TITLE
cannot send, transfer or stake my CFG

### ISSUE THREAD

**Issue by estigan** [polkadot-js/apps#6019]
Created account on portal.chain.centrifuge.io through Clover Wallet
The new account did receive funds however I cannot distribute them to anywhere.
I keep receiving the error message "balances.transferKeepAlive Unable to send transaction."
Can somebody please advise how to fix the issue. Thank you!
 
![CFG not trasferring](https://user-images.githubusercontent.com/87008839/131190604-b6260cc8-52bf-4221-aefb-67f2d19adb54.jpg)

**Comment by jacogr** [comment]
The error message is from Clover Wallet, not the apps UI - https://github.com/clover-network/clover-wallet/blob/591318393f1f6b4e8beed8404315de2fac551e89/lib/services/static-message-factory-service.js#L93

**Comment by estigan** [comment]
thanks, will do so.

**Comment by estigan** [comment]
reported the issue on clover finance github but still no response. Maybe someone from centrifuge has an idea how to fix my problem
