### ISSUE TITLE
Lost DOT balance

### ISSUE THREAD

**Issue by alterkahn** [polkadot-js/apps#6040]
Hello, recently I was sending some DOT via the polkadot.js.org using Chrome browser extension and faced the next issue:

Yesterday I transferred from Binance to my extension address: 14Di8atrGL4eJtkXbnnuPBTA8pALgYbtpShDViFXHYX8nqVY 40.9 DOT, then I started paying to the address of the ACA token sale exactly 40 DOT. The first transaction did not succeed but took the fee of ~0.156 DOT, and the second transaction was successful with the ~same fee, but after this transaction successfully passed my balance on the wallet from which I sent DOTs was completely reset, to zero. I saw there a button "transfer the entire balance", but I definitely did not touch it, and it can be seen via the explorer that exactly 40 DOTs were sent to the token sale wallet: 12WSSs6SRWTTFYQTaE5x43zKKVqbKs55FjirjExQiFi2bXHL.
I'm confused about what happened with the rest of the DOT balance on my wallet, and if I had 1000 DOTs there, they would also be reset to zero? 

Could you please clarify please what was happened with my DOT balance?

**Comment by jacogr** [comment]
When the balance drops below the existential deposit (which is 1 DOT), the account is reaped on-chain. So anything below 1 DOT is treated as dust. 

Since you used 40 DOT it left you with less than existential and the account is as removed by the on-chain logic.

**Comment by alterkahn** [comment]
ah, thank you a lot for the clarification.
