### ISSUE TITLE
Account not visible on polkadot.js

### ISSUE THREAD

**Issue by caneriva** [polkadot-js/apps#6047]
Hello have a problem I hope you can help me.

Since 2 days I have a problem to see my account on the KUSAMA Monriver.
If I switch to another chain my account pops up and it's connect with my extension.
The problem is only if I switch to the KUSAMA Monriver can't see my account. 

What can I do to see my account on Monriver?

**Comment by jacogr** [comment]
Moonriver uses Ethereum style accounts, not Substrate style. The normal Substrate accounts are therefore not visible.

**Comment by caneriva** [comment]
I was on the moonriver crowdsale and I got 340 tokens, and 200 were reserved. On Friday it showed 340 tokens on my account on kusama/moonriver polkadotjs. Now I can't see the account anymore. If I switch to other chains I can still see my acount.
