### ISSUE TITLE
Wrong Proposal Length

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/apps#6059]
I've having more and more of this happening when closing a council or technical committee proposal.
It never happened before (last week the first occurrence I think)
![image](https://user-images.githubusercontent.com/329248/131927623-cd68cc0c-bd6d-4e7a-a045-ae615f0022ad.png)

What is even weirder is that if I retry 4-5 times I end-up having the extrinsic to pass

**Comment by jacogr** [comment]
At least as part of Parity TC seat have seen this before. It was caused by a single RPC provider that was not running the latest node code causing a mismatch in the value returned from the weight RPC.

**Comment by crystalin** [comment]
Thank you @jacogr I'll check with the RPC providers if that is the case. Closing it for now. I'll re-open if needed
