### ISSUE TITLE
Lowest/highest validator/intention display not showing up

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#608]
![image](https://user-images.githubusercontent.com/1424473/51250802-e852b000-1997-11e9-8873-f4ea0bbc0c52.png)

**Comment by alishaagupta** [comment]
Hi I will be working on this issue.

**Comment by jacogr** [comment]
@alishaagupta Thanks. Actually just started as part of the API updates since the underlying derive API is being replaced - sorry, just headed over to assign and then saw your comment.

**Comment by jacogr** [comment]
Seems a bit (???) more involved than initially thought - had some issues with the current derive functions (and then those in the new api.derive). However, added the explicit balance getter in the api PR above (along with lots of cleanups/fixed) and it should move back on track.
