### ISSUE TITLE
Upstream issue with `@sora-substrate/type-definitions` as used by `apps-config`: missing `lodash` import

### ISSUE THREAD

**Issue by jsdw** [polkadot-js/apps#6107]
https://github.com/polkadot-js/apps/blob/652a102f2d323767eeae6b80e1215e6cf53530b4/packages/apps-config/package.json#L27

It appears as if the current version of `@sora-substrate/type-definitions`, which is imported by `apps-config`, imports `lodash` in its index.js/ts file, but doesn't explicitly mention it as a dependency in it's `package.json` file. This has led to https://github.com/PureStake/moonbeam/pull/676 (and then that trickled into https://github.com/paritytech/txwrapper-core/issues/130).

What's the best course of action here?

This `@sora-substrate/type-definitions` package doesn't have an explicit github link or anything, so offhand it's not obvious how to file an issue with the maintainers of that package.

**Comment by jacogr** [comment]
Log it here - https://github.com/orgs/sora-xor/repositories

It would seem I need to start checking the repos for all instead and f just the installed packages.

**Comment by jsdw** [comment]
Thanks; logged!

**Comment by joelamouche** [comment]
Thanks guys :)
