### ISSUE TITLE
`Unable to retrieve the specified block details. -32603:` on Statemine block 656351

### ISSUE THREAD

**Issue by dzhelezov** [polkadot-js/apps#6112]
To reproduce, simply navigate to: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-statemine-rpc.paritytech.net#/explorer/query/0xd15b6bd69b141661b7e071274d670c29e759e63e9ad4892a744207d0f89fb426

Thi issue is similar to https://github.com/AcalaNetwork/Acala/issues/1382#issuecomment-909741211

**Comment by jacogr** [comment]
That is from the node itself, it has nothing to do with the API. There is no levers the API can pull to make this not happen.
