### ISSUE TITLE
Claims page freezes for a specific account

### ISSUE THREAD

**Issue by laboon** [polkadot-js/apps#6158]
A user claimed via Ethereum smart contract (pre-genesis) and apparently needs to attest, as there is no record of his account on the Polkadot chain. However, when the address is entered into the claims page ( https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/claims ) , nothing happens except the "Continue" button disappears. No errors appear in the JavaScript console.

If the attestation is necessary, the user should be given a chance to sign it; otherwise, it should show the textbox for the Ethereum address.

Failing address is 145VGavE2sK4sxxx3nNWaKvZdp8Qf7mDHhh63JFCvvMysYSy

If relevant, corresponding Ethereum address is 0x00554019bc1D942Aef1cBF7Ee6bEcDab99CA91D7 and was claimed here:  https://etherscan.io/tx/0x9fd76b7759b6523c0e8425a6db51540f36f511d58c1fc73562c6cda78625347e

**Comment by jacogr** [comment]
There is no claim on-chain for the Ethereum address -

![image](https://user-images.githubusercontent.com/1424473/134463808-dc449265-cb07-4fdd-9d41-8498c5354eb2.png)
