### ISSUE TITLE
Block details page with xcm related events is broken with createType error

### ISSUE THREAD

**Issue by NachoPal** [polkadot-js/apps#6163]
Related to: https://github.com/polkadot-js/api/issues/3941

```
Unable to retrieve the specified block details. Unable to decode storage system.events:: createType(Vec<EventRecord>):: decodeU8a: failed at 0x0001000000350298… on : {"phase":"Phase","event":"Event","topics":"Vec<Hash>"}:: decodeU8a: failed at 0x350298a6b5c49798… on event: {"index":"EventId","data":"Null"}:: Struct: failed on data: (MessageId,Outcome):: decodeU8a: failed at 0x8861287f7f5610c5… on : {"_enum":{"Complete":"Weight","Incomplete":"(Weight,XcmErrorV0)","Error":"XcmErrorV0"}}:: Unable to create Enum via index 136, in Complete, Incomplete, Error
```

**api**: v6.0.5
**apps**: v0.96.2-3
**cumulus**: polkadot-v0.9.9 branch
**polkadot**: v.0.9.9

**Comment by jacogr** [comment]
Which chain? For non xcm v1 chains you need to set the correct defaults, the API default it to xcm v1. (For instance for Kusama and Westend it is reset to v0, since they have not upgraded)

**Comment by NachoPal** [comment]
It was for `rococo-v0.9.9`. 

I found out that the problem was coming from my types.json. If I don't apply them it works fine.
