### ISSUE TITLE
error when query some Shiden block

### ISSUE THREAD

**Issue by Ljzn** [polkadot-js/apps#6172]
Query shiden block on `polkadot.js.org` https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.shiden.astar.network#/explorer/query/330855

Got this error:

```
Unable to retrieve the specified block details. createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding session.setKeys:: Struct: failed on args: {"keys":"Keys","proof":"Bytes"}:: decodeU8a: failed at 0x40c35282e182360b… on keys: (AccountId,AccountId,AccountId,AccountId):: decodeU8a: failed at 0x0400… on : AccountId:: Invalid AccountId provided, expected 32 bytes, found 2
```

**Comment by akru** [comment]
Hi @jacogr, that looks like type information is correct, but data handling on PolkadotJS and on runtime is different. 
Do you mind UI should crash on data decoding errors like this? 
For wrong encoded data I believe runtime just mark this extrinsic failed.

**Comment by jacogr** [comment]
I had a PR for your suggestion, I closed it on the apps UI and the API is still open, but probably won't make it in at all https://github.com/polkadot-js/api/pull/3885 - since it just masks areas where types are invalid. (And creates larger issues for others)

**Comment by akru** [comment]
That's very useful, thank you @jacogr!

**Comment by Ljzn** [comment]
Hi @akru , 
> For wrong encoded data I believe runtime just mark this extrinsic failed.
but in https://shiden.subscan.io/block/330855?tab=extrinsic I didn't see any extrinsic is failed.

**Comment by Ljzn** [comment]
Hi, @arku . Is this https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/plasm-parachain.ts the right place to add the `{ “Keys”: “AccountId” }`. Could you make a new PR, or I will make one.

**Comment by akru** [comment]
@Ljzn plasm is a bit outdated naming and types is a bit different now, I’ll create new one, no problem.
