### ISSUE TITLE
Fully locked balance shows [object Object]

### ISSUE THREAD

**Issue by andresilva** [polkadot-js/apps#6237]
![balance bug](https://user-images.githubusercontent.com/123550/135872514-c1cea888-fcbc-44b4-b651-9a5d86f69be2.png)

I think the problem is [here](https://github.com/polkadot-js/apps/blob/master/packages/react-query/src/FormatBalance.tsx#L98), but I'm not sure what should be done so no fix from me. :)

**Comment by jacogr** [comment]
Ummm.  Can you PM me the address? Would like to see wtf.
