### ISSUE TITLE
sha512 hash mismatch

### ISSUE THREAD

**Issue by Kebis024** [polkadot-js/apps#6256]
Maybe I am doing something wrong but the sha512 has doesn't seem to match up? File size is good and download the file to twice and get the same thing. Any ideas? 

sha512sum ./Polkadot-JS-Apps-0.96.1.AppImage 
3bda402d4d40851f1d6a183d473cf436eec4a7d1ba6788d8ff90d928a34ff3fc12e721834b9846b87d0f11984f281b149032b22196392f6dc707d357e7d6cefb  ./Polkadot-JS-Apps-0.96.1.AppImage

From the yml file..
version: 0.96.1
files:
  - url: Polkadot-JS-Apps-0.96.1.AppImage
    sha512: O9pALU1AhR8dahg9Rzz0Nu7Ep9G6Z4jY/5DZKKNP8/wS5yGDS5hGuH0PEZhPKBsUkDKyIZY5L23HB9NX59bO+w==
    size: 100256501

**Comment by jacogr** [comment]
The packager outputs the sha512 in base64. Here is an old issue on the topic - https://github.com/polkadot-js/apps/issues/4713

Scroll down in that issue for a one-liner that allows you to verify in one step, it should be 

`sha512sum Polkadot-JS-Apps-0.96.1.AppImage | xxd -r -p | base64`

**Comment by Kebis024** [comment]
Okay yep that works thanks for your reply!
