### ISSUE TITLE
Refresh countdown indicator for status updates

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#628]
It will be good to have a button to refresh the node info app. Otherwise refresh the page is slow (needs to call metadata and do other works, just do refresh node status)

**Comment by jacogr** [comment]
Node info polls/updates every 10 seconds for updated health, peer & extrinsic information.

**Comment by jacogr** [comment]
A countdown display could be useful, but probably won't add an explicit manual refresh.
