### ISSUE TITLE
Display issues on Polkadot-JS IPFS

### ISSUE THREAD

**Issue by anaelleltd** [polkadot-js/apps#6288]
Parachain tab is not up-to-date and gives inconsistent info.

On the IPFS Apps:
![PJS_CloudDOT](https://user-images.githubusercontent.com/44770354/137186806-32f7e831-9914-4f65-80ac-ff0f56be3b97.JPG)

On the non-IPFS Apps:
![PJS_DOT](https://user-images.githubusercontent.com/44770354/137186837-571af9c3-b11f-4de6-b40c-d7f41ea4254e.JPG)

**Comment by jacogr** [comment]
Indeed. The PRs only gets deployed (once merged) to the polkadot.js.org site - the IPFS site needs a manual release & update. The update to take the leaseOffset into account was only merged an hour and a bit ago, before the proposals were submitted. 

TL;DR So it will continue that way until at least next week Monday
