### ISSUE TITLE
Statemine block#917004 can not load

### ISSUE THREAD

**Issue by wliyongfeng** [polkadot-js/apps#6292]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpub.elara.patract.io%2Fstatemine#/explorer/query/917004

![image](https://user-images.githubusercontent.com/2264908/137268431-247e0441-e755-4d7d-9066-3a50db910404.png)

Maybe a bug of @polkadot/api?

**Comment by jacogr** [comment]
This is an Elara issue, see https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-statemine-rpc.paritytech.net#/explorer/query/917004

(A different RPC)

Will disable Elara for now until this is fixed, which I'm assuming needs an upgrade.
