### ISSUE TITLE
Possible enhancement - show derivation path

### ISSUE THREAD

**Issue by ekowalsk** [polkadot-js/apps#6310]
Maybe we could show the derivation path in apps (if possible) as it is in extension
![image](https://user-images.githubusercontent.com/30404388/137472506-fdc6dbee-8375-4b5a-beb6-7b44e4fa9c48.png)

**Comment by jacogr** [comment]
I'm sure we used to for the inside-apps derived accounts... I could be dreaming.

**Comment by joelamouche** [comment]
Makes sens to me! But imo priority is adding correct derivation to the extension
