### ISSUE TITLE
Karura 231979 can not be decoded 

### ISSUE THREAD

**Issue by wliyongfeng** [polkadot-js/apps#6313]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkarura-rpc-0.aca-api.network#/explorer/query/231979

![image](https://user-images.githubusercontent.com/2264908/137494789-9a31f781-23b0-4702-b775-55a47f72106e.png)

Other endpoints also tried, same error, I think this maybe a problem of the api or karura types?

**Comment by jacogr** [comment]
Closing, not much I can do with this on this layer.
