### ISSUE TITLE
Hardware stop staches on polkdaot account - error TXN...

### ISSUE THREAD

**Issue by quiz7** [polkadot-js/apps#6321]
Hi, 

I try to stop and unbound polkadot nomination, I use a ledger X wallet.
Aftre clicking "sign and submit " button in the "authorize transaction" dialog, the following error is raised : 
staking.chill
Txn version not supported

can you help me ? 

Thanks

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/apps/issues/6304

This is related to the Ledger app itself. Both Kusama & Polkadot had upgrades this week to runtime 9100 & 9110. Here is the details for the Ledger app updates -

Polkadot - Zondax/ledger-polkadot#100
Kusama - Zondax/ledger-kusama#104

**Comment by quiz7** [comment]
Thanks, understood.
The following message of ledger team seems to say that the bug is only on ledger live and that polkadot.js is an alternative solution during this outage. I undestrand it is more an ledger core issue. 

https://support.ledger.com/hc/en-us/articles/4404413984913-Polkadot-DOT-temporary-outage?support=true****

Rgds
