### ISSUE TITLE
UX fail: no hint in settings that you can't use firefox with ledger

### ISSUE THREAD

**Issue by gilescope** [polkadot-js/apps#6346]
I get that there's technical reasons for it not being possible at the moment, but I should get a greyed out "manage hardware connections" button with a not supported in this browser message. Otherwise people get puzzled that they're doing something wrong when they follow the instructions from ledger on how to use polkadot.js with ledger.

**Comment by jacogr** [comment]
PRs welcome, as always if this creates a massive issue for you.
