### ISSUE TITLE
Windows 10 report virus Trojan:Win32/Bulta!rfn of installer.exe

### ISSUE THREAD

**Issue by Disco7** [polkadot-js/apps#6350]
Hi devs,
Windows 10 report virus Trojan:Win32/Bulta!rfn 
Path: AppData\Local\polkadot-apps-updater\installer.exe
its Ok?

**Comment by jacogr** [comment]
It doesn't sound ok. The binaries for the installers are built on GitHub's CI infrastructure (see here https://github.com/polkadot-js/apps/blob/master/.github/workflows/push-master.yml#L49-L87) so unless that has been compromised, it is unlikely that the distributed binaries would be affected, i.e. it never leaves that environment.

Having said that, rather be safe than sorry - if a false positive, it is still horrible.
