### ISSUE TITLE
Decode failed at event from electionProvideMultiPhase

### ISSUE THREAD

**Issue by Daelon02** [polkadot-js/apps#6353]
![image](https://user-images.githubusercontent.com/63471940/138109274-052ad4a3-30fe-4835-a30c-1ec2e7338bff.png)
And this problems always when drop this event

This problem substrate pallet

**Comment by jacogr** [comment]
The types for the chain is incorrect. Could be CompactAssignments.

This issue should not be in existence when using metadata v14 (like the latest Substrate & Polkadot)
