### ISSUE TITLE
Uncaught error problem on Kusama's Parachains section

### ISSUE THREAD

**Issue by WolfgangAres** [polkadot-js/apps#6435]
Hi everyone, sorry if it is a stupid question but, when I try to enter the parachain section in Kusama I get this error. How can I solve this problem?
![image](https://user-images.githubusercontent.com/93330815/139266555-a2ac450a-569c-4638-8c6a-89e17dbd8031.png)

**Comment by tunch34** [comment]
The problem persists in Chrome, Edge and FF.

**Comment by WolfgangAres** [comment]
Problem also exists on Brave too

**Comment by jacogr** [comment]
Please provide the full error details. As described above, "me too" comments doesn't help in resolving since this is not reproducible.  If it was reproducible, it would have been fixed. (After #6447 above, there should be extended error information displayed, which _may_ help, which was previously only available in the developer tools console inside the browser)

**Comment by WolfgangAres** [comment]
![image](https://user-images.githubusercontent.com/93330815/139525672-8b411f73-aaa1-46b9-a91d-449785429f10.png)

**Comment by jacogr** [comment]
Brilliant, that gives something to look at (still opaque, but makes the haystack smaller...)

**Comment by seydikarin** [comment]
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

a is undefined
QPa/</</</</t<@https://polkadot.js.org/apps/main.5d9b5176.js:19:548124
QPa/</</</<@https://polkadot.js.org/apps/main.5d9b5176.js:19:548104
QPa/</</<@https://polkadot.js.org/apps/main.5d9b5176.js:19:548078
QPa/</<@https://polkadot.js.org/apps/main.5d9b5176.js:19:548362
ci@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:362817
ui@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:363271
useState@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:369167
83426/t.useState@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:650665
QPa@https://polkadot.js.org/apps/main.5d9b5176.js:19:546557
ii@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:362043
Ui@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:371561
zi@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:370895
Ws@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:417367
_l@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:401368
Pl@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:401296
Sl@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:401157
ml@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:398144
qo/<@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:347965
46475/e.unstable_runWithPriority@https://polkadot.js.org/apps/other.01.8006c99e.js:2:160443
$o@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:347742
qo@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:347912
Ko@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:347845
dl@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:395529
Mi@https://polkadot.js.org/apps/react.01.4ee3bd2f.js:2:367341
Vua/</<@https://polkadot.js.org/apps/main.5d9b5176.js:19:133310

**Comment by jacogr** [comment]
There could possibly be an improvement now. It is now attempting to mask the issue. 

https://github.com/polkadot-js/apps/blob/master/packages/page-parachains/src/Overview/useValidators.ts#L21-L22

The weird thing it seems that some validator assignments are invalid which is the root cause based on the traces, how it gets there would be the real fix, not just bypassing and not resulting the the error.

**Comment by tunch34** [comment]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpub.elara.patract.io%2Fkusama#/parachains

Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

Cannot read properties of undefined (reading 'toString')

TypeError: Cannot read properties of undefined (reading 'toString')
at $Pa (https://polkadot.js.org/apps/main.f5631ac4.js:19:547615)
at https://polkadot.js.org/apps/main.f5631ac4.js:19:549074
at Array.forEach (<anonymous>)
at https://polkadot.js.org/apps/main.f5631ac4.js:19:548951
at https://polkadot.js.org/apps/main.f5631ac4.js:19:549327
at ci (https://polkadot.js.org/apps/react.01.0f0282b2.js:2:362817)
at ui (https://polkadot.js.org/apps/react.01.0f0282b2.js:2:363271)
at Object.useState (https://polkadot.js.org/apps/react.01.0f0282b2.js:2:369167)
at t.useState (https://polkadot.js.org/apps/react.01.0f0282b2.js:2:650665)
at aOa (https://polkadot.js.org/apps/main.f5631ac4.js:19:547892)

**Comment by tunch34** [comment]
I can view the parachain page, but none of the crowdloans I've joined are visible.
