### ISSUE TITLE
Allow user to manually enter node url/ip in settings

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#644]
It will be good if user can enter url/ip of their node in the settings. Maybe popup some warning if trying to access ws endpoint from https UI.

**Comment by jacogr** [comment]
So would suggest -

- selection for pre-defined vs custom
- custom allows entry into input 
- validation checks for ws:// (loclahost/127.0.0.1 only) or wss:// prefixes
- save this to localstorage along with setting (pre/custom)
- inject URL upon startup (apps)

**Comment by maxwellfoley** [comment]
submitted a PR here: https://github.com/polkadot-js/apps/pull/657

**Comment by jacogr** [comment]
Closed in #657 - thanks a million!
