### ISSUE TITLE
Display source account name on the submit transaction screen

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#645]
Currently it only display the source address without name, I often need to cancel to check which account was selected

Another UX feedback, hover to show more information is fine, but have panel expanded and push everything else is annoying to me. Especially when I like to move mouse to where my eyes are (reading long hex is not easy for human), the hover and expand effect destroys my focus.

**Comment by jacogr** [comment]
Agreed on both - I'll get the second one in today, playing with options there.
