### ISSUE TITLE
XCM reserve transfer AccountId32 type not correctly represented

### ISSUE THREAD

**Issue by brenzi** [polkadot-js/apps#6455]
When I try to do a downward reserve transfer with XCM, it seems that AccountId32 of the beneficiary at the destination parachain isn't correctly represented in js/apps:

![screenshot-polkadot js org-2021 10 31-12_00_48](https://user-images.githubusercontent.com/10366175/139579716-83e77805-df3e-472b-83fc-d9316a1d22fa.png)

**Comment by brenzi** [comment]
caused upstream

**Comment by jacogr** [comment]
It is correct, the Rust types define it as a `[u8; 32]`.

You can paste an address in there and it would be converted correct - it is just not selectable via dropdown.

**Comment by jacogr** [comment]
Closing, as per metadata definitions. (The UI has some helpers, i.e. you can paste an ss58 into the fields and it would be converted, but apart from that it is not something that we can override here)
