### ISSUE TITLE
Feature Request: Bags-List Pallet

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/apps#6460]
Recently, we've deployed a new pallet to our chains called [`pallet-bags-list`](https://github.com/paritytech/substrate/tree/master/frame/bags-list). This will act as a backend for the staking/election system in the future and will be able to sort nominators from most-stake to least-stake. More information about this, including the deployment schedule, can be found [here](https://docs.google.com/document/d/1RMoTpvXyoudMeVTRJ-a6p9XDpdCfUovRapJINZJB4hI/edit?usp=sharing). Moreover, this script is a pretty good example of how bags are iterated, and how you should check if they need a rebag or not. 

I propose a very basic UI to be created for this pallet due to two reasons: 

1. it encourages people getting informed and educated about this pallet and its role,
2. which is necessary because in any chain that has more nominators than it can support in election, users might need to fix their positions in/within bags to have a higher chance of receiving staking rewards.

---

I am not sure if my input on the design of the page is needed. Nonetheless, I propose the following simple components to exist: 

**Banner**: A banner to explain briefly what bags-list are, what they do, and emphasize that this is for advance users. I can help with the final paragraph that is used for this. 
**Your Bag + Check**: A component that, for each local stash account, shows which bag it belongs to. Also, it would show if any of your accounts need to be rebagged or not. An example of this count be found [here](https://github.com/paritytech/polkadot-scripts/blob/d3d16403c747af906fb918ec7ee7c3f61b165cb4/src/services/bags.ts#L18). 
**All Bags**: Lastly, we could have a component that just list all bags, similar to [this](https://github.com/paritytech/polkadot-scripts/blob/d3d16403c747af906fb918ec7ee7c3f61b165cb4/src/services/bags.ts#L49) CLI tool. The members of each bag need to be queried at first. Each bag could have a `load` button. Additionally, a `load all` could load the entire data.  

I think this page can first exist under `Developer`, and once final move to a new tab under `Staking` page. 

--- 

Feel free to reach out to me in DM or here for more info or a more detailed description.

**Comment by Nick-1979** [comment]
Hello, 
I have some issue with staking these days after last Polkadot upgrade, I have staked more than minNominated and has no oversubscribed validators, but my accountId does  not exist in the top nominators fetched via "api.query.staking.erasStakers.entries(currentEra)". I think I need a rebag, If I am mistaken please let me know. If this is the case, is it possible to do rebag via polkadot,js,org or I should call "api.tx.bagsList.rebag(MyAccoundId)" myself.

Thank you

PS: I asked the similar question on Element but no answers yet!

**Comment by kianenigma** [comment]
@jacogr as this is now in production, we're starting get to get some questions about it, and the lack of UI for it is causing issues for polkadot stakers. Can you evaluate this, and let me know if and when it can happen?

**Comment by kianenigma** [comment]
also an update: `rebag` is the name of the operation that you would do to go from one bag to another (potentiall better one). But you can also manually change your position within a bag, called `put_in_front_of`. @emostov is working on adding this functionality as well to the `polkadot-scripts repo. Once there, it should be easy to port this as well to the UI.

**Comment by jacogr** [comment]
It is in the queue, so it is tracked.
