### ISSUE TITLE
Unable to detect valid account in the UI

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/apps#6475]
This is for Moonbeam, using H160 account and scale_info types.
All interactions (council propose, add a proxied account...) are disabled even having the valid account.

This seems to be related to the case sensitivity, as the Account is displayed with mixed case, but when retrieving the council list the address (the same) appears in lower case.

![image](https://user-images.githubusercontent.com/329248/140177875-322c2cdd-0e7c-43fa-b90b-0829cbd78304.png)
See my account in the council.

![image](https://user-images.githubusercontent.com/329248/140177999-aec91310-ce94-424c-9e3f-93214597c8b5.png)
See the council propose button disabled

(This is a UI issue as I can propose the motion/external using the extrinsics)

**Comment by jacogr** [comment]
Indeed. Will be ok after the H160 -> AccountId20 conversion.

(The issue atm is everywhere, e.g. sudo as well since the inputs are not recognized as an address-format)

**Comment by crystalin** [comment]
Thank you @jacogr ,
On our side we are preparing dedicated types on the runtime:
https://github.com/PureStake/moonbeam/pull/926

**Comment by jacogr** [comment]
Brilliant. Since there is a path already, the API PR that J submitted can be adjusted to that and merged. (So the JS side will be ready)

**Comment by crystalin** [comment]
@jacogr some other issues are also related to Balance where it appears as u128 (requiring all the decimals) in some inputs, do we have to also make dedicated types for those ?

**Comment by jacogr** [comment]
There are some overrides on the UI for these (in extrinsics), but they will all be removed, e.g. see balances.transfer where it _should_ display as a Balance input - generally they are incorrect and the UI cannot actually determine if it is an on-chain value or not, it guesses. 

(For instance, if you look at chains with assets, they are incorrectly displayed as a Balance input)

There is no 100% correct in all-cases solution for this atm.
