### ISSUE TITLE
Creating a proxy should notify about deposit BEFORE a user creates one

### ISSUE THREAD

**Issue by gilescope** [polkadot-js/apps#6476]
When creating a proxy we tell people about the small fee but not the 20 dot+ deposit that gets reserved. We need to be upfront about that as it's a non-trivial amount of money for many people. (They can undo it after the fact if they don't like it, incurring two sets of tx fees, but that's obviously not ideal.)

It's at the bottom of a very long page on proxies at the moment: https://wiki.polkadot.network/docs/learn-proxies

It could be calculated but some fixed text would probably be fine saying it's reserving at least 20 dot or X ksm (with a link to read more maybe?).

**Comment by jacogr** [comment]
The reserved amount is shown on the modals -

![image](https://user-images.githubusercontent.com/1424473/140260193-4ab0348f-971f-4fd6-aba6-b506de983c81.png)

**Comment by gilescope** [comment]
Ah ok - I did see that and didn't know what it was, so I created it via developers / extrinsics which didn't seem to have that parameter.
 
Alas the current text didn't mean much to me (as a polkadot newbie). This is a good opportunity to try and make the text clearer.

Rather than:
```
The amount that is reserved for the proxy based on the base deposit and number of proxies
```
something like this would have been helpful:
```
The 'reserve balance' is the amount that will be locked on the proxied account to create the proxy. 
If you destroy this proxy, this money will be unlocked and again usable by the proxied account. 
(The amount that is reserved for the proxy based on the base deposit and number of proxies)
```
(For me 'reserved' doesn't really mean much to me. Locked I can understand. I'm sorry if there's some nuance between locked and reserved that I don't understand yet - are those terms interchangable?)

But that's still not good enough because I would read it and wonder what a 'base deposit' is? 

How would you define what a 'base deposit' is? or can we link to a definition of it?

**Comment by jacogr** [comment]
Yes, obviously the extrinsics page has no warnings, it is contextless and just shows what is on-chain.

PRs welcome if it is confusing for you.
