### ISSUE TITLE
Add logo for Polkadot Shell

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#6480]
Currently the UI is only showing the owner, but does not recognize this para as "Shell". Add info that this is the Shell parachain.
![image](https://user-images.githubusercontent.com/25483142/140294178-d840e142-3fe7-4ca2-9099-fb52a8e70ddb.png)

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/apps/pull/6481 (it needs an RPC endpoint in all cases)

Well, the fact that CI publish doesn't work and it is not visible is an entirely other issue.
