### ISSUE TITLE
Address book and multisig account fails to appear after added to second chain

### ISSUE THREAD

**Issue by bacchist** [polkadot-js/apps#6486]
I added several accounts to my address book and created a large (7 of 12) multisig on Kusama. After repeating the process on Polkadot, the multisig and address book entries failed to load on Kusama. Others have also reported the same behavior.

**Comment by jacogr** [comment]
It is expected. With the same addresses and resulting Derivate address it will appear as one account and only be available where created. 

It is not advised to share addresses across chains.
