### ISSUE TITLE
Add a warning msg on crowdloans tab 

### ISSUE THREAD

**Issue by rrtti** [polkadot-js/apps#6505]
If contributors have 5.5 DOT and contributed 5 to crowdloan A,  the remaining 0.5 DOT get burned due to the existential deposit. Is it possible to add a warning msg reminding users of the existential deposit before they sign?

**Comment by DrW3RK** [comment]
Right! Adding a keep-alive check like balance transfers would be even more resourceful than just a warning message (but can be a good place holder before it is implemented). Here is the issue raised earlier today regarding the same - https://github.com/polkadot-js/apps/issues/6499

**Comment by joepetrowski** [comment]
Should account for tx fees as well. The worse thing that seems to happen is that a user contributes `balance - 1` to a crowdloan, expecting 1 DOT on their account to keep it alive. Since the fee is taken pre-dispatch, they end up with something like 0.995 DOT reaped.

**Comment by Dexer125** [comment]
> Should account for tx fees as well. The worse thing that seems to happen is that a user contributes `balance - 1` to a crowdloan, expecting 1 DOT on their account to keep it alive. Since the fee is taken pre-dispatch, they end up with something like 0.995 DOT reaped.

Yes, it happened to me and I'm really mad about it. It's a lot.

**Comment by pmensik** [comment]
A lot of members of the Polkadotters community have encountered this as well. Problem is that Polkadot JS is really too technical for most of the folks out there. This should be fixed as soon as possible otherwise people will keep losing money.
