### ISSUE TITLE
Verification Error

### ISSUE THREAD

**Issue by transxask** [polkadot-js/apps#6508]
command:
```
# Compile Polkadot with the real overseer feature
git clone https://github.com/paritytech/polkadot
cargo build --release

# Generate a raw chain spec
./target/release/polkadot build-spec --chain rococo-local --disable-default-bootnode --raw > rococo-local-cfde.json

# Alice
./target/release/polkadot --chain rococo-local-cfde.json --alice --tmp

# Bob (In a separate terminal)
./target/release/polkadot --chain rococo-local-cfde.json --bob --tmp --port 30334

```

the error is reported when all interface are invoked in apps
```
balances.transferKeepAlive
1002: Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: "validate_transaction", parameter: "tx", error: Error { cause: None, desc: "Could not decode `MultiAddress`, variant doesn't exist" } }): RuntimeApi, Execution failed: ApiError, FailedToConvertParameter { function: \"validate_transaction\", parameter: \"tx\", error: Error { cause: None, desc: \"Could not decode `MultiAddress`, variant doesn't exist\" } }
```

**Comment by jacogr** [comment]
See https://polkadot.js.org/docs/api/FAQ#i-cannot-send-transactions-sending-yields-decoding-failures

**Comment by transxask** [comment]
> See https://polkadot.js.org/docs/api/FAQ#i-cannot-send-transactions-sending-yields-decoding-failures
I know I should add '{"Address": "MultiAddress", "LookupSource": "MultiAddress"}'. However, when I run the latest version of Rococo, the '/ Settings /developer' in apps can not be found. I don't know where to set it

**Comment by transxask** [comment]
> > See https://polkadot.js.org/docs/api/FAQ#i-cannot-send-transactions-sending-yields-decoding-failures
> > I know I should add '{"Address": "MultiAddress", "LookupSource": "MultiAddress"}'. However, when I run the latest version of Rococo, the '/ Settings /developer' in apps can not be found. I don't know where to set it

This is the definition of address in Rococo: `pub type Address = sp_runtime::MultiAddress<AccountId, ()>;`

**Comment by transxask** [comment]
And the following error occurred when I executed the transaction directly on the Kusama network
```
balances.transferKeepAlive
1002: Verification Error: Runtime error: Execution failed: Other("Wasm execution trapped: wasm trap: unreachable\nwasm backtrace:\n 0: 0x2de7 - <unknown>!rust_begin_unwind\n 1: 0x2b34 - <unknown>!core::panicking::panic_fmt::h3ab5417155b7ba3b\n 2: 0x304c97 - <unknown>!TaggedTransactionQueue_validate_transaction\n"): RuntimeApi, Execution failed: Other, \"Wasm execution trapped: wasm trap: unreachable\\nwasm backtrace:\\n 0: 0x2de7 - <unknown>!rust_begin_unwind\\n 1: 0x2b34 - <unknown>!core::panicking::panic_fmt::h3ab5417155b7ba3b\\n 2: 0x304c97 - <unknown>…
```

**Comment by jacogr** [comment]
Connect to a chain not on metadata v14 and clear your types. You have an override for address. (In v14 chains the settings is not available, types come via metadata - Address overrides are very problematic though)

**Comment by transxask** [comment]
> Connect to a chain not on metadata v14 and clear your types. You have an override for address. (In v14 chains the settings is not available, types come via metadata - Address overrides are very problematic though)

Does this mean that polkadot-js/apps cannot be used in any metadata14 chain?

**Comment by jacogr** [comment]
Polkadot/Kusama/Statemine/etc. are all on v14 - it works correctly.

In your case you probably have some incompatible types injected in the developer section which needs to be cleared first. (As you rightly said that section is not available on v14 chains, since, like here, it just creates havoc)

**Comment by transxask** [comment]
> Polkadot/Kusama/Statemine/etc. are all on v14 - it works correctly.
> 
> In your case you probably have some incompatible types injected in the developer section which needs to be cleared first. (As you rightly said that section is not available on v14 chains, since, like here, it just creates havoc. Hence the suggestion to connect to a pre-v13 chain and then clear them)

According to your suggestion, the problem has been solved here. Thank you！
