### ISSUE TITLE
Polkadot JS Apps page unresponsive 

### ISSUE THREAD

**Issue by DrW3RK** [polkadot-js/apps#6517]
![image](https://user-images.githubusercontent.com/86818441/140663288-a961f561-90ee-465e-bb57-cfa572b2bb30.png)

Several users have reported they have trouble opening https://polkadot.js.org/apps/#/explorer - the page just freezes. After interacting with them, it is identified that a browser extension called DarkReader is the issue.

https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en

I was able to replicate this issue. After installing the DarkReader extenstion, I was unable to open Polkadot JS apps page. Was wondering why/how a browser extension would render Polkadot JS apps unresponsive. Any insight is appreciated!

**Comment by jacogr** [comment]
This needs to be referred to the extension developer, the apps UI is certainly very far from optimal, but if an extension changes the pages, it shouldn't break them. If it does, it means it is doing something it really should not.

**Comment by DrW3RK** [comment]
Understood! Closing the issue.
