### ISSUE TITLE
Figure out how to support multiple runtime versions for the same parachain (types)

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#6533]
For a parachain like moonriver, which changed over the time from a pre 900 (pre automatic scale info) runtime that needed type injection to a post 900 that automatically deduced type from the parachain, how do we handle both in the apps?
Most api calls will just use the latest runtime version, but what if I want to explore older blocks? Will the api know these blocks are from an older runtime and request types from injected types?

**Comment by jacogr** [comment]
This is for Kusama, effectively for the metadata v14 branch onwards the types are empty, for older it is populated - https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/kusama.ts

(Although both Polkadot/Kusama there has a little "bug", the v14 onwards should be completely empty, I left it as-is initially meaning to come back and remove, never did, will do so now)

**Comment by joelamouche** [comment]
So are you saying we should still inject the types as we used to, but have an empty types object for post metadata14 runtime versions?

**Comment by jacogr** [comment]
100%

**Comment by crystalin** [comment]
@jacogr we should make it so that when no types are injected matching the runtime version it takes the automatic node types  no? Instead of having to provide emtpy types.

**Comment by jacogr** [comment]
So when you do minmax: [900, undefined] with types: {} it injects nothing for runtime 900+

**Comment by crystalin** [comment]
Yes I understood the idea :)
I was just mentioning that not providing types in some cases is clearer/easier than empty types. Nothing really important :)
