### ISSUE TITLE
Polkadot.js - Extrinsic Balance Bug?

### ISSUE THREAD

**Issue by ngx3** [polkadot-js/apps#6536]
I'm trying to add a proxy, but it doesn't allow me to, only telling me it's an issue with Extrinsic Failed balances. I have 2 DOT in each account, main and proxy... so I'm not sure why it's not allowing me to make a transaction.

proxy.addProxyinblocksystem.

ExtrinsicFailedbalances.InsufficientBalancebalances.

Withdrawbalances.Deposit (x3)treasury.Depositextrinsic event

Is this happening to anyone else?

**Comment by jacogr** [comment]
On the proxy screen addition screen (accessible via accounts) it shows the reserved balance for the chain - you need to have that amount available to create a proxy. The amount, as indicated, will be reserved and non-transferrable until the proxy is destroyed.

**Comment by ngx3** [comment]
But with the proxy, that 20 DOT cannot be used for anything, is that right? And only the balance from the main account will be counted towards anything?

My second question is, how is a proxy destroyed? Or, how are funds moved from the second account without having an extrinsic balance.

**Comment by jacogr** [comment]
No, it cannot be used. It is reserved on-chain, to be returned when the proxy is cleared. It is on the account being proxied, i.e. "main account" as named it.

**Comment by Saniaab** [comment]
Hello .  I sent 9,9692999973 DOT to the exchange, they did not reach the exchange please fix the error
0x63ce41053347eba1c9e5bdcb7b94363ccca22a6a1ef88eebe5011850d9ecf3ed

**Comment by jacogr** [comment]
Speak to the exchange. If it reflects on an explorer, it is in their court.

**Comment by Saniaab** [comment]
ok thanks!
