### ISSUE TITLE
Camera access to add account

### ISSUE THREAD

**Issue by RED29** [polkadot-js/apps#6542]
When entering an account via QR, the website shows that there is no device found. This is only when I use my own ipfs node with the know hash: QmRCxbPqnJcZN1khQ2xw15q3DRn3h6f6ZVPJQAwVMQTVe3

I know it might related to how IPFS works. But can someone point me why the camera on the device is working with:

1. The hash QmRCxbPqnJcZN1khQ2xw15q3DRn3h6f6ZVPJQAwVMQTVe3 via ipfs provided with Cloudflare, Pinata.

And why it is NOT working with my own node:
2. Same hash / content: QmRCxbPqnJcZN1khQ2xw15q3DRn3h6f6ZVPJQAwVMQTVe3 like dappnode and more

**Comment by jacogr** [comment]
It is only enabled on https, not http. It is a browser restriction, see https://stackoverflow.com/questions/52759992/how-to-access-camera-and-microphone-in-chrome-without-https

**Comment by RED29** [comment]
Thanks for pointed me out. This makes sense!
