### ISSUE TITLE
cannot deploy ink 3.0.0-rc6 contract

### ISSUE THREAD

**Issue by sharkygg** [polkadot-js/apps#6544]
hi, we cannot deploy ink 3.0.0-rc6 contract on apps, when add .contract file, get errors

PortableRegistry: 1: Error extracting {"path":[],"params":[],"def":{"composite":{"fields":[]}},"docs":[]}: Cannot read properties of undefined (reading 'toString')

**Comment by jacogr** [comment]
Is that using the latest master of contracts? The rc-6 format has changed, the first version didn't correct encode for scale-info v1.
