### ISSUE TITLE
Polkadot UI does not recognize form input if it is not freshly typed

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/apps#656]
When using the Polkadot UI to submit extrinsics, you may be asked to submit data like hashes or balances.

When you switch between different function calls, the data in those fields will persist, however the UI does not recognize that the field is updated. 

For example, I could submit a hash with function call 1. Switch to function call 2. The hash is still there in the input, but submitting a transaction submits a hash of `0x00000...`

Seems like there is a javascript `onchange` happening to update the value used in calls, and since the field is not updated, then it is not used...

**Comment by jacogr** [comment]
I marked it as fixed, but couldn't quite reproduce your error, so cannot verify 100% - something is very weird in your case. This has been problematic in the past, however if the method changes all values are reset and it _should_ properly re-render. However there is a corner-case which I did fix in the above PR, hopefully that is related to what you are seeing.
