### ISSUE TITLE
Have two types of AccountId in a blockchain

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#6592]
We want to use both AccountId32 and AccountId20 in our crowdloan pallet (https://github.com/PureStake/crowdloan-rewards/blob/main/src/lib.rs) which is why we defined AccountId (set to AccountId20) and RelayChainAccountId (set to AccountId32) - here https://github.com/PureStake/moonbeam/blob/dfe363bac66e68cff2ecb25ac710c11a880e0875/runtime/moonbase/src/lib.rs#L773.

Right now, all 32 addresses are being displayed in the app as 20 addresses.

We suspect this might be the problem:
https://github.com/polkadot-js/apps/blob/cd352e5bcf083e9703a9c6bb854e0a626c9cce7a/packages/react-params/src/Param/findComponent.ts#L48

**Comment by girazoki** [comment]
Is there any news about this?

**Comment by jacogr** [comment]
As always, PRs welcome - this is probably (not sure, hence marked as "needs investigation") quite something to implement. 

For myself, as everything logged it apps, it is marked, it is in the queue, no promises as to when I can take a look or even when it can have a solution.

**Comment by User-8D** [comment]
Hey mate

Were any changes made 2 weeks ago?

I have 2 wallets that need to change MOVR rewards location from native to
metamask generated and this needs the ability to change one address to the
KSM contribution source.

The funny thing is, I changed one, got tired, went to bed, went to change
the other next afternoon and the error messages are now there even when all
the fields are blank

Cheers

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/apps/pull/8752
