### ISSUE TITLE
Contract transaction dry-run should happen every time an input is changed

### ISSUE THREAD

**Issue by cmichi** [polkadot-js/apps#6603]
Our automated test suite `ink-waterfall` found this:

* Deploy [proxy.contract.zip](https://github.com/polkadot-js/apps/files/7597198/proxy.contract.zip) from Alice.
* This stores Alice as a privileged account in the contract.
* Open the dialog for executing the contract call `change_forward_address`. 
* Alice is pre-selected by the UI as the default "call from account", the gas value is estimated at `213` based on the RPC dry-run.
* Select Bob instead, the estimated gas value will stay at `213`
* If the transaction is then executed it will fail due to `OutOfGas`. This is because the logic is different if the sending account is not the privileged account.

I'm not sure if a dry-run happens if any of the other input parameters is tweaked. The ideal behavior would be that a dry-run is executed when any of the inputs is modified.

**Comment by jacogr** [comment]
Agreed. It should re-execute on change. (This is slightly problematic for number Inputs, but can be debounced)

**Comment by jacogr** [comment]
Closing.

Based on my reading here it will re-calculate gas usage on each param change, including sending account e.g. `accountId` and indeed debounced (hence the `db*` prefixes on the values) as mentioned above -

https://github.com/polkadot-js/apps/blob/ce86da7f6f12605ad72a9584c56319ca58868014/packages/page-contracts/src/Contracts/Call.tsx#L63-L76
