### ISSUE TITLE
Uncaught error - creating a new asset

### ISSUE THREAD

**Issue by metmirr** [polkadot-js/apps#6604]
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

```
createType(Call):: Call: failed decoding assets.create:: Struct: failed on args: 

{"id":"Compact<AssetId>","admin":"LookupSource","min_balance":"TAssetBalance"}:: Struct: failed on min_balance: u64:: u64: Input too large. Found input with 65 bits, expected 64
```

**Comment by jacogr** [comment]
On which chain?

**Comment by metmirr** [comment]
It was my custom chain so I thought it's a bug in the apps.
