### ISSUE TITLE
Statemine default address format set to Substrate, should be same as Kusama

### ISSUE THREAD

**Issue by laboon** [polkadot-js/apps#6633]
From convo with Joe P. on Matrix -

Bill | W3F: Is it just me, or has the default address format on Statemine changed from Kusama to Substrate?
joe: showing that way for me too
joe: just a UI bug though, it should be kusama

**Comment by jacogr** [comment]
It retrieves it via the syetm_properties - there is a deployment bug, it is not set -

![image](https://user-images.githubusercontent.com/1424473/144745467-646579ea-68a5-4b4c-8997-170e04a33f64.png)

Actual message retriaved -

`{"jsonrpc":"2.0","result":{"tokenDecimals":12,"tokenSymbol":"KSM"},"id":21}`
