### ISSUE TITLE
Bug: balances overflow 

### ISSUE THREAD

**Issue by Veniamin** [polkadot-js/apps#6649]
Steps to reproduce

1) Navigate to the polkadot or kusama Accounts tab.

2) Make an attempt to transfer 1.10000 mili tokens.

3) In the signing transaction, 1.10000 will be changed to 110,000 (x10 more tokens).

In chains with 9 decimals, 4 digits after the dot (polkadot.js shows 4 digits while reading storage) is enough for overflow. So, copy pasting from the storage can lead to errors.

**Comment by jacogr** [comment]
The signing dialog doesn't apply decimal formatting for any transaction. (Neither does the storage pages).

**Comment by Veniamin** [comment]
The value in signing dialog is x10 of original value. But if I try to send 1.10 mili - everything will be fine

**Comment by Veniamin** [comment]
![image](https://user-images.githubusercontent.com/736337/145407629-ee4930b0-7e59-42e0-b9b3-4fc24ea4e06e.png)
![image](https://user-images.githubusercontent.com/736337/145407683-f5732b80-ff99-4594-af63-9ab00f5b1354.png)
while correct value should be
![image](https://user-images.githubusercontent.com/736337/145407757-9a5ea475-ff27-4224-942c-4617d32a0ecd.png)

**Comment by Veniamin** [comment]
In our chain we have balances with 9 decimals and for example copy pasting of "1.1851 mTOKEN" leads to error.
