### ISSUE TITLE
Possible to run this UI and backend component on my own infrastructure?

### ISSUE THREAD

**Issue by timmolter** [polkadot-js/apps#6650]
Hello, can I run polkadot-js and its supporting services myself to "index" the polkadot blackchain? Something like what polkascan.io provides: give it an account and it lists the TX history for example: https://polkascan.io/polkadot/account/16ZL8yLyXv3V3L3z9ofR1ovFLziyXaN1DPq4yffMAZ9czzBD I'd like to download and install such an explorer on my own infrastructure. And I don't necessarily need the UI, but only a REST API. I looked through the various repos here, but didn't find clear answers.

Is there an "indexer" component that polls a DOT node, populates a DB, and provides an API to clients needing information such as account TX history, current block chain height, account balances etc.?

**Comment by jacogr** [comment]
The apps UI has no back-end infrastructure, no REST and no database - it retrieves everything real-time from RPC nodes via the polkadot-js API.

Explorers such as Subscan/Polkascan is more of what you are after. I know Polkascan has everything open-sourced and available, their indexes, database structure and the front-end code.
