### ISSUE TITLE
The extension link for the chrome store is incorrect

### ISSUE THREAD

**Issue by BulatSaif** [polkadot-js/apps#6652]
## Description 
The link to chrome extension store is not working: 
- https://chrome.google.com/webstore/detail/polkadot%7Bjs%7D-extension/mopnmbcafieddcagagdcbnhejhlodfdd

The link present on folowing pages:
1. https://polkadot.js.org/apps/#/accounts
2. https://polkadot.js.org/extension/

- ![Screenshot from 2021-12-09 19-53-52](https://user-images.githubusercontent.com/24387396/145443094-7477378d-0ad9-4f7e-97c9-383836b58f5c.png)
- ![Screenshot from 2021-12-09 20-12-59](https://user-images.githubusercontent.com/24387396/145443938-882159d3-5574-4cab-94bd-a67c0e04f9d2.png)

## Expected results:
Chrome extension store page

## Actual results
![Screenshot from 2021-12-09 20-06-18](https://user-images.githubusercontent.com/24387396/145443485-6420b85a-d235-4b5e-a278-cddb79188f36.png)

**Comment by jacogr** [comment]
Thank you for logging, it is tracked here - https://github.com/polkadot-js/extension/issues/913

**Comment by jacogr** [comment]
Closing, see the extension tracking issue, specifically this update - https://github.com/polkadot-js/extension/issues/913#issuecomment-990880912
