### ISSUE TITLE
Invalid block time - missing expectedBlockTime for non babe chains.

### ISSUE THREAD

**Issue by 1devNdogs** [polkadot-js/apps#6664]
## Problem description.

For the [Subspace network](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftest-rpc.subspace.network#/explorer) the `expectedBlockTime` const is defined as _6000_ . 

We have `expectedBlockTime` const defined in our `subspace` module. The current implementation only considers this const if `babe`  is available.  

As we do not use `babe,` the block time fallback to `a.consts.timestamp?.minimumPeriod`, which is _500_, finally rendering 1s.

https://github.com/polkadot-js/apps/blob/b00a040eae579859ffad81252ac7c683d8728761/packages/react-hooks/src/useBlockTime.ts#L30-L37

## Possible solution.

A possible solution could be to look up over available consts and return the `expectedBlockTime` if it is found. 
This way, the current implementation should not be affected and will cover any other chain using _expectedBlockTime_ from another module.

```typescript

function extractExpectedBlockTime (consts: QueryableConsts<ApiTypes>): u64 & AugmentedConst<ApiTypes> {
  return Object.keys(consts)
    .map((section) => consts[section].expectedBlockTime)
    .find((blockTime) => blockTime || false) as u64 & AugmentedConst<ApiTypes>;
}
.....
      const expectedBlockTime = extractExpectedBlockTime(a.consts);
      const blockTime = (
        // Babe, or chains using expectedBlockTime
        expectedBlockTime ||
        // POW, eg. Kulupu
        a.consts.difficulty?.targetBlockTime || (

```

I have this modification in [here](https://github.com/subspace/polkadot-js-apps/commit/996ede588f1a5291d7500b7d8f4c746a4ad2be58).
I checked if there was a negative impact for other chains and it seems to be working fine. Any help is appreciated.

Cheers!.

**Comment by jacogr** [comment]
In this case the same modification as for Kulupu would apply, i.e. something specific to the runtime, so the modification would look something like -

```js
const blockTime = ( 
   // Babe 
   a.consts.babe?.expectedBlockTime ||
   // POW, eg. Kulupu 
   a.consts.difficulty?.targetBlockTime || 
   // Subspace
   a.consts.subspace?. expectedBlockTime || ( 
 ```
