### ISSUE TITLE
Outdated types are loaded before metadata

### ISSUE THREAD

**Issue by gregdhill** [polkadot-js/apps#6676]
Whenever I connect to a new chain, `polkadot-js/apps` (presumably) loads the outdated types [here](https://github.com/polkadot-js/apps/tree/master/packages/apps-config/src/api/spec) instead of using the new runtime metadata. The UI eventually loads the correct types after some time but in the meantime most queries are invalid and extrinsics are inoperable.

**Comment by sander2** [comment]
Related to https://github.com/polkadot-js/apps/issues/6562 - if you go to settings->metadata the correct metadata is immediately loaded

**Comment by gregdhill** [comment]
I think this is still an outstanding issue (cc: @jacogr).
