### ISSUE TITLE
Teleporting KSM to Statemine is not working for new accounts.

### ISSUE THREAD

**Issue by anaelleltd** [polkadot-js/apps#6679]
Hi there,

I'm reporting this issue on behalf of 4+ people who tried to **send an ED for their Statemine accounts**.
Teleporting does not go through, even after submitting the transaction on the Polkadot-JS Apps and extension. No extrinsic hash and no change of balance occur.

Please advise on this matter.
Thanks! :)

**Comment by laboon** [comment]
Can you provide some more information? I teleported 0.05 KSM from Kusama relay chain to Statemine via Polkadot-JS App on Tuesday and it worked fine. See balances (Deposit) in this block - https://statemine.subscan.io/block/1334165?tab=event

**Comment by anaelleltd** [comment]
Thanks Bill.
To be honest, I am not quite sure what the problem is. Transfers work for some people and not for others.
It might have something to do with the amount they are trying to send (i.e < 0.05 KSM). Hard to tell from my end. 😐

**Comment by Tehxman116** [comment]
Hey I'm one of the people having this issue. I teleported some KSM 3 times from Kusama relay chain to Statemine via Polkadot-JS App and only one of them has arrived in my Statemine account. Both KSM and Statemine accounts were recently created.

**Comment by anaelleltd** [comment]
> Hey I'm one of the people having this issue. I teleported some KSM 3 times from Kusama relay chain to Statemine via Polkadot-JS App and only one of them has arrived in my Statemine account. Both KSM and Statemine accounts were recently created.

Great! Thank you for the on-chain data, as it has been hard to obtain these from newbie users! 🙏🏿

**Comment by makinsan** [comment]
Just experienced this same issue. Tried to teleport 0.05 KSM relay chain to Statemine using Polkadot JS and it hasn't arrived. Has anyone identified what's causing the issue?

**Comment by Tehxman116** [comment]
I just created a new KSM account on the Polkadot.js extension rather than the app. I then went to https://dotapps.io/?kusama and and tried to teleport again and this time it was successful! So anyone having issues give that a go :)

**Comment by makinsan** [comment]
Thanks @Tehxman116 . I actually just realised that all this time, I was checking the 'Statemint' blockchain rather than Statemine! User error!

**Comment by DrW3RK** [comment]
This issue might be directly related to the unaccounted teleport fee from Kusama to Statemine 
https://github.com/polkadot-js/apps/issues/6742

**Comment by anaelleltd** [comment]
Thank you very much for these findings, @DrW3RK! 🥇 
The previous issue of teleport minima whereby you could not send less than 0.00002KSM has also been resolved.
