### ISSUE TITLE
Add selectable examples to js console

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#668]
Port the examples (promise), from https://polkadot.js.org/api/ to the js console accessible via http://localhost:3000/#/js 

(The current default code included is basically a port of https://polkadot.js.org/api/examples/promise/02_listen_to_blocks/ - init skipped since we already have an instance of the api configured and passed-in)

To make this usable (off the top of my head) -

- Add top-level selector to swap between the samples, dropdown is fine
- Add examples in app-js/snippets
- ... make sure they all work :)

That is the first step to pre-select. ~~When anything edited, add it to a "Recent" (or something properly named) entry and allow selection thereof. Save these into localstorage. (If available and user comes back, load that one as the default and select it - so we always come back to the user code)~~
(EDIT SD: Moved to https://github.com/polkadot-js/apps/issues/685)

After this we should have -

- a nice toolset of available examples (we can edit/clarify the above quite a bit, even add some more - there are gaps, i.e. no derive atm, which should also go into the api examples)
- ~~have a way for the user to access his last-edited code~~

It moves us closer to having the interface sort-of usable and adding value to actual "I just want-to-play" coders. It is not a replacement for anything resembling building real-apps, but nice as a testing and checking env.

**Comment by Stefie** [comment]
Closing. Remaining todo's moved to:
https://github.com/polkadot-js/apps/issues/685 and
https://github.com/polkadot-js/apps/issues/692
