### ISSUE TITLE
Split js Editor/Output areas into tabs

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#670]
This makes https://github.com/polkadot-js/apps/issues/668 more usable as well

Create 2 tabs, one for the editor (taking up the full-screen real-estate available) and one for the Output component, once again taking up all space. (IT would be cool if this could auto-scroll to the bottom as well as output is added)

Additionally, when we execute, clear the console so each execution starts fresh. (Auto-swap to "Output" when execute, would work well here)

**Comment by Stefie** [comment]
Closing in favour of: https://github.com/polkadot-js/apps/issues/692
