### ISSUE TITLE
Chain type modification

### ISSUE THREAD

**Issue by ArseniiPetrovich** [polkadot-js/apps#6706]
We are building a Frontier-based chain, and running the Polkadot.JS to perform operations on the chain. Recently we made some super minor chain adjustments, but the Polkadot.JS started to interpret our chain as Substrate, instead of Ethereum. We tried to investigate, but we have no understanding on how Polkadot.JS currently determines which network type it is. We have tried to dig through the issues on this repo and found a couple likehttps://github.com/polkadot-js/extension/issues/758 that gives a foggy idea that this somehow connected with the Genesis metadata, but it would be great if you could clarify things a bit more by answering the following questions:
1) Where in Substrate/Polkadot.JS this ChainType is defined?
2) How can we force Polkadot.JS to think about our chain as of Ethereum compatible chain

Also any insight into how Polkadot.JS identifies the network details and how we do modify it will be much appreciated❤

**Comment by jacogr** [comment]
It is actually harcoded based on specname. 

PRs welcome to extend - https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/settings/ethereumChains.ts#L6
