### ISSUE TITLE
Account page redesign feedback

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/apps#671]
Relates to user feedback here https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org/$1549062202142806JJnlI:matrix.org?via=matrix.org&via=matrix.parity.io&via=cryptonomic.tech&via=t2bot.io

Currently when the browser window width  is less than < 1280px, it shows across two rows as shown below, with opportunities to improve the second row (i.e. reduce the left padding, align it to the left, reduce the width so the 'using my account' selection box doesn't have so much whitespace between the identicon and the address.

<img width="1227" alt="screen shot 2019-02-02 at 10 44 54 am" src="https://user-images.githubusercontent.com/6226175/52155731-4a215280-26d8-11e9-9695-67367191d1c5.png">
 
And when the browser width becomes more than > 1280px, there are opportunities to also reduce the width so the 'using my account' selection box doesn't have so much whitespace between the identicon and the address, and aligning the labels to the left (whilst having both selection boxes being vertically aligned.

<img width="1271" alt="screen shot 2019-02-02 at 10 44 44 am" src="https://user-images.githubusercontent.com/6226175/52155804-c0be5000-26d8-11e9-85ef-dbec54ddbfc5.png">

**Proposed wireframes**

<img width="1227" alt="not-split" src="https://user-images.githubusercontent.com/6226175/52156093-45f63480-26da-11e9-9fba-c2e4065b0683.png">

<img width="1271" alt="split" src="https://user-images.githubusercontent.com/6226175/52156095-4989bb80-26da-11e9-8574-adf281b790c7.png">

**Comment by burrrata** [comment]
In addition it would be great if the left side image with Account ID, Balance, and Transactions was bigger. Making the font bigger would help, and/or splitting the space equally between the account data section on the left and the account selection/password/key section on the right (in the side by side example).
