### ISSUE TITLE
Applied slashes are not displayed on staking pages

### ISSUE THREAD

**Issue by paradox-tt** [polkadot-js/apps#6715]
With reference to the captioned topic please see example:

- https://kusama.subscan.io/extrinsic/10598526-0?event=10598526-5
- EfK27sX89DpagD3TCF4hF4rGZ1CnCGtYZvo94HZLU3GQuMj

There are several others including 5 x Zug Capital validators that were slashed recently and none have the slashing icon associated with them.

**Comment by jacogr** [comment]
The UI doesn't have a database to store the information - it only displays what is currently in the state. For what you are asking for -

- the events needs to be monitored
- they need to be stored in a database
- they need to be displayed

The apps UI only relies on the information that is available on-chain, in storage. Once a slash is applied, this information is not on-chain. (The on-chain storage is available before the slash is applied).

**Comment by paradox-tt** [comment]
I understand the perspective, for some reason I thought this existed before.  For now, we'll have to rely on third parties to maintain a history of slashes.

**Comment by paradox-tt** [comment]
Hey @jacogr,

I was informed that this displayed the slash icon providing that the validator has renomination 'required'.  Can this implementation work?

**Comment by jacogr** [comment]
It only gets displayed while there are slashes - 

- Kusama 7 days (unless council steps in)
- Polkadot 28 days (unless council steps in)

If nominations do get dropped, it does alert the user as to that fact. However the icon can't and won't display unless it is retrieved from the chain state (during the above periods.) The UI doesn't try to "make up info" it shows what is on-chain only.

**Comment by paradox-tt** [comment]
Looks like I'll close this one again, thanks for taking the time to respond.
