### ISSUE TITLE
Recover seed from browser data?

### ISSUE THREAD

**Issue by lostkey33** [polkadot-js/apps#6717]
I'm not sure this is the best place for this, please redirect me if I'm wrong.

Earlier this year my house was flooded. I lost a lot of things, including my seed phrase for the polkadot.js extension. I had most of my savings on it.
I was using a Macbook that also died in the flood, but a technician was able to recover data from the SSD. I have all the data from the Chrome browser I was using the Polkadot.js extension on.

With Metamask there is a way to recover the seed prase using the browser data: 
https://metamask.zendesk.com/hc/en-us/articles/360018766351-How-to-use-the-Vault-Decryptor-with-the-MetaMask-Vault-Data
I didn’t find such guide for Polkadot.js extension, so I’m asking you: is it possible?
I’m also not a very technical person so I would appreciate some help if it’s indeed possible.

**Comment by jacogr** [comment]
The mnemonic phrase itself is not stored, only the derived secret/private key. However with the password you can unlock the wallet.

**Comment by lostkey33** [comment]
Ok thank you.

I did try to recreate the browser from the files but I run into some errors.

Could you tell me how to retrieve the private key (on mac os), it may be easier this way.

**Comment by jacogr** [comment]
To extract, it needs to be decoded with the password for the wallet. So use the "Restore JSON" functionality in either the apps UI or the extension and add the password, it will decrypt it.

**Comment by lostkey33** [comment]
I understand, thank you. My problem is that I don't have a JSON file to restore. 

What I have is the password to unlock the extension, and the browser files, which look like this (screenshot) : https://ibb.co/f0rWsqY

If the private key is stored in the browser then I suppose there is a way to extract it from those files, I just don't know how.

**Comment by Usergithub99** [comment]
It is possible to do it from the browser, the process is a bit long, but it can be done.

**Comment by lostkey33** [comment]
Any chance you could detail the steps?

**Comment by Usergithub99** [comment]
Yes, sure
iam.tester.ok@gmail.com
