### ISSUE TITLE
Transaction history

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/apps#672]
User feedback suggested showing transaction history on the Account page. It may also be suitable to show it elsewhere or in its own dedicated menu item tab

Relates to feedback here: https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org/$1549062367143418SmNJt:matrix.org?via=matrix.org&via=matrix.parity.io&via=cryptonomic.tech&via=t2bot.io

**Comment by jacogr** [comment]
Closing. This is in the realm of explorers. (There is no way to reliably get this from the node without replaying all blocks, and storing it on a DB. Additionally archive node is required. )

We will integrate a link to Polkascan when that is operational.
