### ISSUE TITLE
params: initValue: createType(VerifierData):: DoNotConstruct: Cannot construct unknown type VerifierData

### ISSUE THREAD

**Issue by NoCtrlZ** [polkadot-js/apps#6729]
I implemented my own pallet and I would like to test interacting [`substrate-node-template`](https://github.com/substrate-developer-hub/substrate-node-template) with `polkadot-js`.

I forked `substrate-node-template` and imported my own pallet as following.
https://github.com/mmagician/zkPlonk-testing-v3/tree/main/pallets/zk-test

When I ran `substrate-node-template` and sent extrinsics from `polkadot-js` ui, the error `params: initValue: createType(VerifierData):: DoNotConstruct: Cannot construct unknown type VerifierData` happened.
It seems I need to define the types that I use my own pallet to `types.json`

I defined the types inside of api create method as following according to official [documentation](https://polkadot.js.org/docs/api/start/types.extend/) but it didn't work.
```
  const api = await ApiPromise.create({ provider,
    types: {
      "VerifierData": "AccountId",
    } });
```

I think following `types.json` is really good example but I defined `types.json` in my runtime directory but it didn't work.
https://github.com/airalab/robonomics/tree/master/vendor/evercity

Where should I define the type?
Thank you!

**Comment by SotaWatanabe** [comment]
@jacogr happy new year! Hope you are doing well. Could you take a look at this issue when you have time?
