### ISSUE TITLE
Add icon for new extension to metadata updating dropdown

### ISSUE THREAD

**Issue by AndreiEres** [polkadot-js/apps#6739]
Could you please say me where I can add a new icon to update this component there https://polkadot.js.org/apps/#/settings/metadata?
![image](https://user-images.githubusercontent.com/27277055/147481976-bce41284-c8f5-4099-abdb-f25e579d5f16.png)

**Comment by jacogr** [comment]
It is a mess ... https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/ui/logos/index.ts#L704-L706
