### ISSUE TITLE
Kusama to Statemine teleport - Destination transfer fee incorrect

### ISSUE THREAD

**Issue by DrW3RK** [polkadot-js/apps#6742]
The destination transfer fee at Statemine is 0.004 KSM. Currently, the Apps UI displays 10.6666 micro KSM with an assumption that it is 1/10th of Kusama's fee for the same transaction which is 106.6666 micro KSM

It is fair to update the field highlighted below so that the users do not get mislead 

![image](https://user-images.githubusercontent.com/86818441/147553581-a0876492-d5e0-432a-ad2b-826b3ba939ac.png)

I tested this out with multiple teleports from Kusama to Statemine. You can check the teleport transaction of 0.005 KSM  made below on Kusama
https://kusama.subscan.io/extrinsic/10704414-3

and the balance received at Statemine is just 0.001 KSM
https://statemine.subscan.io/extrinsic/1417828-0?event=1417828-1

**Comment by DrW3RK** [comment]
On a different note, the math all adds up for Statemine to Kusama teleports. I teleported 0.005 KSM from Statemine to Kusama and received 0.0048933 KSM. The destination fee displayed on Polkadot JS Apps is accurate 

![image](https://user-images.githubusercontent.com/86818441/147555406-7fb1f822-e53b-4420-994c-b9d775a34300.png)

Like I mentioned earlier, the teleports from Kusama to Statemine have unaccounted fee which needs to be displayed to the users to be fair

![image](https://user-images.githubusercontent.com/86818441/147555514-6a88e590-c4dd-4f9f-acb5-aeb294e7334e.png)

**Comment by jacogr** [comment]
These are not supposed to be accurate, they are estimations. I belobe the best course of action would be to remove it altogether since there are no xcm fee estimator. 

Will make a PR to remove it complete.

**Comment by jacogr** [comment]
Closing, removed in #6745. (Can be re-surrected when we have xcm estimations cross-chain)
