### ISSUE TITLE
Adding custom balance pallets in the accounts page

### ISSUE THREAD

**Issue by nud3l** [polkadot-js/apps#6744]
We are using the orml-tokens pallet for all our token needs on the kintsugi and interlay networks. I think we can show a custom token balance on the accounts page using the `derive` approach. However, I'm not sure how to go about doing that. Is there an example to achieve this?

Essentially, I just want the "KINT" balances to be displayed there:

![image](https://user-images.githubusercontent.com/14966470/147574411-ede08bfd-916a-4ff1-bcd0-ba4154515546.png)

To add some information, the balance I'd like to add can be queried via `api.query.tokens('address', {'Token: 'KINT'})`

**Comment by jacogr** [comment]
The balances page only displays the native balances. (eg. `balances` pallet or a renamed balances pallet)

**Comment by nud3l** [comment]
Ok, thanks! I think Equilibrium did that when I browsed through the files. I will ask them directly.

**Comment by jacogr** [comment]
Sorry I'm not of much help here - I believe it is only the `derive.balances.all` that needs adjustment. (And yes, after looking, you are correct, seems to be Equilibrium)

**Comment by nud3l** [comment]
Ok, thanks! One relate question: is it possible to enforce an ordering of the "TokenSymbol"? On chain we have the following enum:

```rust
    pub enum TokenSymbol {
        DOT("Polkadot", 10) = 0,
        INTERBTC("interBTC", 8) = 1,
        INTR("Interlay", 10) = 2,

        KSM("Kusama", 12) = 10,
        KBTC("kBTC", 8) = 11,
        KINT("Kintsugi", 12) = 12,
    }
```

Apps will always take the first element as the main currency, however, in our case, we'd like to set KINT as the primary currency and INTR for the Interlay network. I saw that it's being fetched via the `api.registry` but it's a bit unclear to me how I could modify this.

**Comment by jacogr** [comment]
Where do you want to enforce ordering?

**Comment by nud3l** [comment]
Where does it get the `system_properties` from? Is that defined on-chain or somewhere in JS world? I am aware of the ss58 prefix being defined on chain (here for Kintsugi: https://github.com/interlay/interbtc/blob/master/parachain/runtime/kintsugi/src/lib.rs#L234), but not really sure where the tokenSymbol would be set.

Essentially, what I am trying to do is tell polkadot.js to use not the first element in this enum:

```rust
    pub enum TokenSymbol {
        DOT("Polkadot", 10) = 0,
        INTERBTC("interBTC", 8) = 1,
        INTR("Interlay", 10) = 2,

        KSM("Kusama", 12) = 10,
        KBTC("kBTC", 8) = 11,
        KINT("Kintsugi", 12) = 12,
    }
```

But the last one. I thought that maybe I could achieve this by injecting custom ordering within apps.

**Comment by jacogr** [comment]
the properties is an RPC. It returns the properties section in the chainspec.

**Comment by gregdhill** [comment]
@jacogr would it be possible to also support "Send" using derives? The "Accounts" page currently crashes with the error `api.consts.balances is undefined` when I try to open the modal.
