### ISSUE TITLE
3 dots in UI issue - Chrome v. Firefox

### ISSUE THREAD

**Issue by btcmacroecon** [polkadot-js/apps#6768]
Im just playing around with Westend and I have to ask if there is any explanation for the lack of consistency across Firefox and Chrome for example? I set up account in Chrome, I got seed phrase. But whenI go to Chrome to even use the product - cause it doesn't work in Firefox, I go to Chrome and address isn't there like it is in Firefox. I realize a major flaw in Firefox,in that there is no backup like with the 3 dots, like it used to, and therefore when I merely try to get a json file created, and option isn't there, it makes it so I am unable to add a json over at Chrome because there is no option in the 3 dots, like it used to. What is the work around and why is this so inconsistent and please dont say it's my browser. Just seems dangerous with the inconsistency and on top of that layer is confusion. :0

Also....
ssue is with the UI and 3 dots (in comparing Chrome and FF) and the fact that there is no backup (to get json) option in the UI in FF, yet it's there in Chrome.

**Comment by jacogr** [comment]
It is there, only appearing for accounts created inside the UI, i.e. none for accounts from QR, via Ledger or via extension -

![image](https://user-images.githubusercontent.com/1424473/147855127-7a67b8c5-18d1-4c11-818f-37f6ff03976f.png)

**Comment by btcmacroecon** [comment]
JACO, thanks for that. In this test run, I went back to the extension and still so no way to get my JSON for the account I set up in the extension apparently, and as discussed, not seeing BACKUP option in the 3 DOTS in the UI itself. To me this seems risky for users in general. I was playing around in test for Westend, so was never really overconcerned about backup JSON, but if it's not in the UI itself, and I am not finding the option in the browser extension, this still seems confusing to me, the user. I want to make sure nobody's grandma gets confused with this technology. Either where would I get my JSON after the fact or how can there be consistency for a greater user experience, for all grandmas?

**Comment by jacogr** [comment]
The extension manages the accounts. Those are not exposed to the app, hence there is no backup. Doing so would mean that any site you visit with the extension would have access to your full encrypted account. 

So, yes, this is intentional.
