### ISSUE TITLE
Decoding old blocks after metadata change

### ISSUE THREAD

**Issue by sander2** [polkadot-js/apps#6793]
We have some problems decoding some old blocks (e.g. [this one](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkintsugi.api.onfinality.io%2Fpublic-ws#/explorer/query/2502)) that is likely caused by the metadata being incorrect for that block. In this particular block we weren't on metadata v14 yet, so we do not care about this particular block. However, it got us to wonder, now that we are on metadata v14, if we make changes in the future that change the metadata, will we still be able to decode the blocks that we are producing right now? That is, when decoding a block, does polkadotjs use the metadata at the time of that block, or does it always use the newest?

**Comment by jacogr** [comment]
Anything past metadata v14, would be decodable- the metadata specifies all the types. 

Prior to v14 you need to manage the types on a per runtime basis. Here is an example of the types for Kusama that allows decoding back to genesis - https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/kusama.ts

(as mentioned above, after the metadata v14 update, no changes required anymore, all is specified in the metadata)

**Comment by sander2** [comment]
Thank you, that is what I was hoping for!
