### ISSUE TITLE
Can't send GLMR from Polkadot.js to any address

### ISSUE THREAD

**Issue by Luiispg** [polkadot-js/apps#6821]
Hi all. I hope you can help me with an issue im having:
I contributed with DOTs to Moonbeam parachain and to get the reward it asked me for an ETH address. I used one I have in Coinomi.

The problem begins when they dropped the rewards and when I check in Coinomi I haven't reveived anything to my ETH account. (I think because Coinomi doesn't support Moonbeams token)
Then I tried to use that address in Polkadot.js  using the "add from QR" (because I don't know any other way to use that account) and then I CAN SEE that I got the GLMR reward in that account.
Then im trying to  send that GLMRs to my Binance account but it asks me for a QR sign when I try to transfer the funds and I don't know how to solve this problem. I tried all possible and different things but no one works. (I think the problem is that my account looks like "type=external, not "inyected" and that's why it asks me for a QR signature. When I try to scan the QR address I see only a error: "Non-signature, non-hex data received from QR, Data contains "0x.............................................." instead of a hex-only signature. Please present the correct signature generated from the QR presented for submision.

I think I will lost my funds in a "ghost ETH address" maybe? :(
I wish you could help me...

![20220112_064434](https://user-images.githubusercontent.com/97611240/149158586-96fe8fab-032d-4b1b-a876-35dc959b578d.jpg)

**Comment by jacogr** [comment]
The add from QR is for accounts on the Parity Signer hence it asks for a QR code - in that case the keys are kept on the Parity Signer device, ie. the signing happens there.

Assuming you are connected to the Moonbeam chain you can either add the account via mnemonic or add it to the extension (once again via mnemonic) and it will be usable inside the application.
