### ISSUE TITLE
Can't vote using Proxies and Conviction

### ISSUE THREAD

**Issue by albertov19** [polkadot-js/apps#6838]
## Issue Description

Token holders can't really vote using Proxy accounts. This is true either via the Democracy Tab UI, or using the `proxy.proxy` extrinsic.

### Via Democracy Tab UI

The main issue I see here is that token holders can't really select an account that was added to the Address Book (the main account for example). Therefore, even if the signer does detect that the main account has a compatible proxy, one can't select the main account where origins are stored.

![image](https://user-images.githubusercontent.com/64150856/149757634-474baf11-581f-433c-be7e-6d4d9a9d4388.png)

If you import the main account, the flow does work. But importing the main account is what it is trying to be prevented.

### Via Extrinsic

The extrinsic menu does not offer the tab to select the conviction.

![image](https://user-images.githubusercontent.com/64150856/149757879-88ca376e-b5fe-482b-a84d-2894a23178e5.png)

**Comment by albertov19** [comment]
In the example I mentioned, the Proxy account is imported and is listed as an account. I mentioned the address book for the Main account, so that it is not imported (therefore still being offline) but I can set the origin account still being the "Main account" and then initiate the signer where I can send the extrinsic with the proxy.

**Comment by jacogr** [comment]
In the example logged, the proxied account is not an account, it is an address - to have it behave as a "proxied account", the address needs to be added with the "+ Proxied" option in the UI. Only added accounts are listed in dropdowns. Once added via "+ Proxied" via address it would appear and can be used. (The same would apply to everywhere the address type is used)

**Comment by albertov19** [comment]
Let me start over. We have a "Main account" and a "Proxy ccount". If both are imported as accounts (not addresses). I can easily vote with conviction using the proxy.

![image](https://user-images.githubusercontent.com/64150856/149764855-57c3e131-3c98-460c-9f79-aa0f2a29cf8a.png)
![image](https://user-images.githubusercontent.com/64150856/149764885-07f2c964-2c54-4cf3-aeef-3dd8d59d67fa.png)
![image](https://user-images.githubusercontent.com/64150856/149764903-6f55994d-bf04-496a-adeb-9766a81b4e05.png)

Next, I've removed the "Main Account", as this would be the normal setup for a collator for example, the main account is secured offline, and use proxies to interact with the chain. In this scenario, I can't vote with the "Proxy Account" with conviction. I tried adding the "Main Account" in the address book (just trying different things), or manually inputting the address of the "Main Account":

![image](https://user-images.githubusercontent.com/64150856/149765288-718be07f-2102-4205-80b2-6b06485a5837.png)

As mentioned before, via `proxy.proxy` is also not possible, even tho the `real: AccountID20` (Moonbeam) can be set as an account in the address book:

![image](https://user-images.githubusercontent.com/64150856/149765408-5b0dbd5b-0ee3-46a6-8ce0-230d021be40e.png)

Sorry for the naming confusion before.

**Comment by albertov19** [comment]
Ahhhhh I understand now! So you would have to add the "Main account" with the "+ Proxied" option in the Accounts tab?
