### ISSUE TITLE
Apps crashes for odd reason (can't find parameter creator)

### ISSUE THREAD

**Issue by drewstone** [polkadot-js/apps#6840]
We have built some pallets and are trying to simply check data of certain storage methods or even pallet contents. When we go to some specific pallets or methods, the Apps UI crashes:
```
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

Cannot read properties of undefined (reading 'creator')

TypeError: Cannot read properties of undefined (reading 'creator')
at https://polkadot.js.org/apps/main.6d198cdd.js:19:721497
at https://polkadot.js.org/apps/main.6d198cdd.js:19:721959
at https://polkadot.js.org/apps/main.6d198cdd.js:19:23140
at https://polkadot.js.org/apps/main.6d198cdd.js:2:13268299
at https://polkadot.js.org/apps/main.6d198cdd.js:2:13268343
at Il (https://polkadot.js.org/apps/react.01.48024d32.js:2:360833)
at t.unstable_runWithPriority (https://polkadot.js.org/apps/other.01.1362c26b.js:2:144977)
at $o (https://polkadot.js.org/apps/react.01.48024d32.js:2:301517)
at Tl (https://polkadot.js.org/apps/react.01.48024d32.js:2:360296)
at ml (https://polkadot.js.org/apps/react.01.48024d32.js:2:351824)
```

The errors occur when clicking entire pallets:
![image](https://user-images.githubusercontent.com/13153687/149872187-a363cb06-8b93-42ed-8f90-1a2e29df7267.png)

Or when we click certain methods:
![image](https://user-images.githubusercontent.com/13153687/149872214-b5041095-0046-444f-a296-3b77f7094d31.png)

Is there any idea how to resolve these issues int the pallet?

**Comment by jacogr** [comment]
That does seem like an issue with something not being handled correctly. Do you have a public URL to check against? (It is the only way to step through)

**Comment by jacogr** [comment]
Thank you.
