### ISSUE TITLE
Inability to submit extrinsics in chains that uses custom/modified block header - Bad Signature Error

### ISSUE THREAD

**Issue by mateuszaaa** [polkadot-js/apps#6855]
Hi!

I'm developer of Mangata parachain (https://parachains.info/details/mangata_finance). I've run into some problems when working with most recent version of polkadot-js/apps. Looks like since version `v0.96` the tab `settings->Developer` is gone. My understanding is, that now the `TypeInfo` thing is used (https://github.com/paritytech/scale-info) and the information about the custom types should be propagated automatically. That  seems to work for all the types other than core types or at least it doesnt work for the `Header` of the block. As a result when extrinsic is submitted it is rejected with error "Transaction has a bad signature".  Not sure how hard it can be to fix, but **would be great to re-enable settings->developer tab**.

![](https://i.imgur.com/7aN8osl.png)

If i use self-hosted older version of ui that has `settings->Developer` after injecting `Header` definition

![](https://i.imgur.com/0wualO7.png)

it works as before

![](https://i.imgur.com/NxTVHg4.png)

I manage to create minimal failing scenario...

How to reproduce:
* introduce new field in block header - https://github.com/paritytech/substrate/compare/master...mateuszaaa:bug/block_header_modification_unsupported?expand=1
* build the `node-template` from substrate repository 
```
cargo run --release --bin node-template -- --tmp --dev
```
* go to https://polkadot.js.org/apps/
* connect to local node `localhost:9944`
* try to submit any extrinsic

**Comment by jacogr** [comment]
Like you correctly observed, the types in the metadata doesn't take into account the RPC definitions, i.e. it only applies to the runtime types, not those used by RPCs. (This is on the roadmap to eventually expose inside the `rpc_methods` call, but at this point it is only names, no types)

For customized chains, it is recommended to add any additional RPC types definition into apps-config.

**Comment by mateuszaaa** [comment]
>it is recommended to add any additional RPC types definition into apps-config

Could you elaborate a little more? Where can i find this apps-config thing ?

**Comment by mateuszaaa** [comment]
ah i see, you mean that https://github.com/polkadot-js/apps/tree/master/packages/apps-config

**Comment by mateuszaaa** [comment]
@jacogr did small experiment 
here is my attemt to inject custom types
https://github.com/polkadot-js/apps/compare/master...mateuszaaa:feature/inject_custom_header?expand=1

but it still fails with localy hosted apps instance.

In the same time below script works

```
async function main () {
  // Instantiate the API
  const wsProvider = new WsProvider('ws://127.0.0.1:9944')
  const api = await ApiPromise.create({
    provider: wsProvider,
    types: {
      Header: {
        parentHash: "Hash",
        number: "Compact<BlockNumber>",
        stateRoot: "Hash",
        extrinsicsRoot: "Hash",
        digest: "Digest",
        count: "BlockNumber"
      }
    },
  })

  await api.isReady;

  console.log("connected")

  const keyring = new Keyring({ type: 'sr25519' });
  // Add Alice to our keyring with a hard-deived path (empty phrase, so uses dev)
  const alice = keyring.addFromUri('//Alice');
  const bob = keyring.addFromUri('//Bob');
  const ferdie = keyring.addFromUri('//Ferdie');

  console.log(await getNonce(alice.address))
  
  let alice_nonce = await getNonce(alice.address);
  let bob_nonce = await getNonce(bob.address);
  console.log(`ALICE NONCE: ${alice_nonce}`);
  await api.tx.balances.transfer(bob.address, 1).signAndSend(alice, {nonce: alice_nonce++})

}

main().catch(console.error).finally(() => process.exit());

```
