### ISSUE TITLE
Transaction is successful but getting invalid notification in pop up

### ISSUE THREAD

**Issue by s-h-ubham** [polkadot-js/apps#6857]
In a simple transfer between accounts, the amount is being transferred and also event is getting emitted but the notification pop up shows invalid **(balances.transferKeepAlive invalid)** error as shown in screenshot.

Polkadot explorer for transaction failure:
![Polkadot explorer for transaction failure](https://user-images.githubusercontent.com/98087338/150521788-e1fff5c2-84ba-4239-acf1-6455b8ba0b48.png)

Log for the failed transaction above:
![Log for the failed transaction above](https://user-images.githubusercontent.com/98087338/150522275-e05559fe-69cd-4aca-a3d7-a45f22b643a0.png)

**Comment by jacogr** [comment]
The UI only reports what the node RPC reports, aka it doesn't make up the status.
