### ISSUE TITLE
MAX_VOTES in council candidats election

### ISSUE THREAD

**Issue by Nick-1979** [polkadot-js/apps#6869]
I have a question about MAX_VOTES that an account can have while votes to council candidates.

It is hard coded as 16 [here](https://github.com/polkadot-js/apps/blob/5174f5ffbecf583d6b9d47d07c46ae777e0032f9/packages/page-council/src/Overview/Vote.tsx#L21)

Is it a rule of Polkadot relay chain or just a limit by the code developer or something? 

Thank you

**Comment by jacogr** [comment]
See https://github.com/paritytech/substrate/blob/master/frame/elections-phragmen/src/lib.rs#L130

**Comment by Nick-1979** [comment]
That's great! Thank you very much.
