### ISSUE TITLE
Bug with chain state query with multiple same items 

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#687]
![screen shot 2019-02-11 at 4 23 40 pm](https://user-images.githubusercontent.com/1201310/52545051-7431ed80-2e19-11e9-89ab-60f8c16f22d1.png)

The Plus button is disabled which is wrong. If the value on the right AccountId is changed, the value on the left is changed as well (some incorrect reuse). If the value on the left AccountId is changed, the Plug button get enabled and it then functional correctly.

decl storage of Topics `type Topic = U256;`:
```
Topics: map (T::AccountId, T::AccountId) => Vec<Topic>;
```

**Comment by jacogr** [comment]
Will take a look, something is really weird and obviously very wrong.

**Comment by jacogr** [comment]
@xlc Could you give https://github.com/polkadot-js/apps/issues/687 a try please? (I hacked-in support into my runtime and it _seemed_ to do the right thing)

**Comment by xlc** [comment]
Yes it fixes the issue.

**Comment by jacogr** [comment]
Thanks, will get it in shortly.
