### ISSUE TITLE
Targets page: sorting order does not always correspond to the chevron direction.

### ISSUE THREAD

**Issue by citizen4371** [polkadot-js/apps#6884]
STR: 
1) Go to Network -> Staking -> Targets
2) Wait for the list of validators to appear
3) Click once on any sorting header (total stake, own stake, etc.) Notice that validators list is still unsorted.
4) Click on the same header again. Now the validators list is sorted but in the opposite order from what the chevron direction.
5) Wait for some time until the component is re-rendered due to props change, now the order of the list and the chevron direction should be aligned.

Validators are not sorted immediately when the header is clicked, sorting is only applied on the next re-render of the Targets component. This is due to `setSorted(sort(sortBy, sortFromMax, filtered));`  not triggering the re-render, as the result of `sort` is the same array as `filtered` that is passed there (`Array.prototype.sort()` sorts in place).

I could do a small PR to fix this issue, WDYT ?

**Comment by jacogr** [comment]
PRs are always appreciated :)
