### ISSUE TITLE
Robonomics parachain chain state digitalTwin doesn't show data

### ISSUE THREAD

**Issue by Vourhey** [polkadot-js/apps#6888]
On Robonomics Parachain
Going to `Chain State -> digitalTwin -> digitalTwin(u32): ..` returns `<none>` but data about digitalTwin is expected

![image](https://user-images.githubusercontent.com/709124/151171465-739063d2-6a9c-4c62-962e-3d5ca93a5de5.png)

Other functions work well. What should I do?

**Comment by Vourhey** [comment]
It seems that behaves as expected since an empty twin is basically `none`. Adding some data to twin it now shows data

**Comment by jacogr** [comment]
It decodes the response as received correctly - screen on the left, response on the right (1 entry in the BTreeMap, `1 << 2` = 4, i.e. the first byte)

![image](https://user-images.githubusercontent.com/1424473/151172318-1b677553-5c33-4041-988b-50d800277ffb.png)

**Comment by jacogr** [comment]
An `Option` is either `None` (displayed as `<none>`) with no data or `Some` (displayed as the contents) with data.
