### ISSUE TITLE
Unable to connect to Zeitgeist testnet since v0.103.1

### ISSUE THREAD

**Issue by Robiquet** [polkadot-js/apps#6889]
When I try to connect to https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbp-rpc.zeitgeist.pm#/explorer
I get the following error:
`API/INIT: Error: FATAL: Unable to initialize the API: Unhandled: Unable to create and validate type from RangeInclusive<u128> (info=RangeInclusive)
    at a.#Z (polkadot.01.6c62701a.js:1)`
![image](https://user-images.githubusercontent.com/4950844/151182067-e9e9b41f-5b71-431d-a0d0-9b66a30b72ad.png)
If I run v0.102.1 locally I am able to connect to: http://localhost:3000/?rpc=wss%3A%2F%2Fbsr.zeitgeist.pm#/explorer

**Comment by sea212** [comment]
This seems to affect only chains that do not have the types in the metadata yet (i.e. Substrate < `polkadot-v0.9.11`).
The problem is caused by the `@polkadot/types` package. Version `7.5.2-0` still works, while all versions above, including the latest `7.5.2-6` don't.
