### ISSUE TITLE
Unable to clear expired democracy locks using proxy account with just Governance permissions

### ISSUE THREAD

**Issue by hitchhooker** [polkadot-js/apps#6892]
![image](https://user-images.githubusercontent.com/15621959/151259962-43f9da62-0a83-4bfb-8447-1101eebd48ef.png)

UI does not somehow register that there is existing democracy proxy set for the wallet. If permission for proxy is set to Any, proxy is recognized and used.
Probably something to do with call being batch call and not recognizing it as pure governance/democracy call.

**Comment by jacogr** [comment]
Not sure the proxy checks deep inspects batches. Would need to check, it has been quite some time.
