### ISSUE TITLE
Polkadot JS Apps blankscreen issue

### ISSUE THREAD

**Issue by DrW3RK** [polkadot-js/apps#6900]
![image](https://user-images.githubusercontent.com/86818441/151709979-4c70d91a-639a-4641-bd87-5108e221fff0.png)

My assumption is that this issue is due to an older version of Firefox. If anyone can confirm it, that would help mitigate this issue.

**Comment by jacogr** [comment]
Here is the list of versions that do support private fields - https://caniuse.com/?search=private%20class%20fields

**Comment by DrW3RK** [comment]
Thanks for the link. I will request the user to update to a version that works.
