### ISSUE TITLE
Moonbeam prefix not available in address prefix dropdown

### ISSUE THREAD

**Issue by purestakeoskar** [polkadot-js/apps#6910]
Under the settings page, the `moonbeam` prefix is not available, but selected as default. So after having changed the default prefix i can no longer change back to moonbeam.

#### Before changing defaults
![image](https://user-images.githubusercontent.com/45081138/151980089-7d89b7ac-5096-4ba0-ab97-ec238c087f61.png)

####  After changing defaults
Moonbeam not available in the list
![image](https://user-images.githubusercontent.com/45081138/151980242-c4e0faca-1918-4d53-bfc0-ecf488c5107e.png)

**Comment by jacogr** [comment]
"Default for the connected node", means the RPC node that is connected to. In this case "1284" is what the RPC reports. Changing back to "default for node" should return it.

**Comment by purestakeoskar** [comment]
The default is set to substrate when i press save and reload. To me there is no way to get back to Moonbeam.
![image](https://user-images.githubusercontent.com/45081138/152010818-0dd8a5e7-5ea4-4d1f-841a-85f5591aa826.png)

**Comment by jacogr** [comment]
The list doesn't contain the full ss58-registry, rather only the specific chains that accounts can be associated to in the apps UI world, i.e. with known genesis.
