### ISSUE TITLE
 author_rotateKeys method not found #3576 

### ISSUE THREAD

**Issue by Sarah2022** [polkadot-js/apps#6917]
How and where to change the RPC safe unsafe flag?

**Comment by jacogr** [comment]
On the client, run it with the `--help` flag to see the available cli options. Adjust as needed.

**Comment by Sarah2022** [comment]
following the guide:

https://medium.com/sora-xor/how-to-run-a-sora-testnet-node-a4d42a9de1af
Does not work on Kusama either
