### ISSUE TITLE
App-JS Follow up tasks

### ISSUE THREAD

**Issue by Stefie** [polkadot-js/apps#692]
Follow-Up tasks from https://github.com/polkadot-js/apps/pull/684

- [x]  Adjust font-size on `Output` & `Editor` https://github.com/polkadot-js/apps/pull/697
-  [x] change default width of columns from 50|50 to 60|40 https://github.com/polkadot-js/apps/pull/697
- [x] Put `resizable` attribute on `Editor` instead of `Output`
- [x]  Potentially move npm module links from `Intro` back to code comments

**Comment by jacogr** [comment]
I think 12px and 60% works (well, at least on my 13")

(May want to adjust the line height to 18px as well, both for the gutter and editor portion)

**Comment by Stefie** [comment]
Fixed by https://github.com/polkadot-js/apps/pull/703
