### ISSUE TITLE
Stalking targets page : Slow at retrieving nominators

### ISSUE THREAD

**Issue by muddlebee** [polkadot-js/apps#6943]
https://cloudflare-ipfs.com/ipns/dotapps.io/#/staking/targets

![Screenshot 2022-02-08 at 4 13 13 AM](https://user-images.githubusercontent.com/8139783/152885053-e55f4bb5-11d0-45de-87bb-69523585355a.png)

**Comment by muddlebee** [comment]
Okay so upon analysis, this is taking more time to load actually. I wonder where the issue is on application layer or protocol layer? 🤔

**Comment by jacogr** [comment]
It needs to retrieve the whole list in chunks (limited to 1k at a time by the RPC), so it is not a "speedy" operation at all.

**Comment by muddlebee** [comment]
@jacogr any way this can be fixed? Happy to take a stab at this. If you point me to the repo/resource 👀
