### ISSUE TITLE
We have green and red but no amber when submitting transactions

### ISSUE THREAD

**Issue by gilescope** [polkadot-js/apps#6952]
This kind of result along with a utils batch where all of the contents did not get done successfully would be great if we could have an amber warning instead of the misleading green that happens presently.

```
polkadotXcm.Attempted
Execution of an XCM message was attempted. 
XcmV2TraitsOutcome

{
  Incomplete: [
```

This would give people more trust in the system and improve ease of use immensely.

**Comment by jacogr** [comment]
Please add comments on this to https://github.com/polkadot-js/apps/issues/3072
