### ISSUE TITLE
Use Latest `MultiLocation`/`MultiAsset` in Teleport Construction

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#7021]
Teleport currently uses `V0` arguments. It should use `V1` `dest`, `beneficiary`, and `assets`, e.g.

![image](https://user-images.githubusercontent.com/25483142/155298591-dbb4d149-2a7a-4f40-9106-43e580af4487.png)

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/apps/issues/6922
