### ISSUE TITLE
Calendar Events on Polkadot Network incorrect

### ISSUE THREAD

**Issue by DrW3RK** [polkadot-js/apps#7045]
![image](https://user-images.githubusercontent.com/86818441/155698696-122b34dc-cee1-44b3-be45-53e0d584bb8a.png)

We are in lease period 6 on Polkadot, with the start of lease period 7 scheduled around March 11th. The calendar does not show an event for that. Instead, it shows the start of lease period 8 on April 1st (The actual start of LP8 is around 3rd June)

CC: @rrtti

**Comment by jacogr** [comment]
Only thing I can think of is that it is related to the new scheduler. (The only changes made to support that was on the API layer, nothing has been changed on the UI to cater for new structures that are available)
