### ISSUE TITLE
feature request: Support for nomination pools

### ISSUE THREAD

**Issue by emostov** [polkadot-js/apps#7076]
https://github.com/paritytech/substrate/pull/10694 will introduce a MVP for nomination pools.   To facilitate a decent UX with the the initial iteration of pools I think it would help to have the following features:

- _List pools_: list the pools similarly to how the apps UI currently lists validators. This could show the pools stake, the pools admin (linking to any identities of the admin), and maybe have a dropdown that shows its nominations. This could also display warnings for if 1) the pools stake is higher than the min staked validator since this would lead to suboptimal rewards, 2) the pool does not have enough bonded to make it into the next election, 3) the pool has no valid nominations.
- _Join a pool_: if the user is not part of a pool, allow them to join one. This could be an option along side each pool when its listed. See the `join` extrinsic.
- _Claim payout_: if the user has some unclaimed rewards, allow them to claim. See the `claim_payout` extrinsic.
- _Unbond_: If a user is part of a pool, allow them to unbond. See the `unbond_other` extrinsic
- _Withdraw unbonded_: If the unbending duration has elapsed since when the user has unbonded, allow them to withdraw unbounded funds. See the `withdraw_unbonded_other` extrinsic.

Bonus features:

- _Create a pool_: allow a user to to create a pool. See the `create` extrinsic. 
- _Nominate_: allow a pool admin to nominate. The `nominate` extrinsic.
- _Pool performance history_: this would basically be the equivalent of what ever stats can be displayed about a nominator, since the pool has an underlying account nominating.

**Comment by kianenigma** [comment]
We are happy to try and find another contributor for this one to take it off your plate if you are certain that you won't have time for it anytime soon, since it is relatively time-sensitive. But I can imagine the whole process being both faster and smoother if you do it yourself? let me know what you think!

**Comment by jacogr** [comment]
There are a couple of issues here -

1. the branch doesn't build (for me)
2. unsure about how much changes are still going in (assuming it can be run)
3. there are no active external contributors (trying to find a raw body is a recipy for disaster)
4. "time sensitive" - what does that mean? (It is not merged, not in for-merge review)

Happy to take a look if there is a working PR which is not changing daily.

**Comment by emostov** [comment]
Thank you for taking the time to look into this! The feedback about events is very appreciated.

To address your 2nd and 4th point I can just write an update here once I am confident its stable.
