### ISSUE TITLE
MaxNomination constant missing in 9.17

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/apps#7078]
Unfortunately, as explained in [this SO question](https://substrate.stackexchange.com/questions/539/constant-maxnominations-is-removed-from-the-kusama-runtime-starting-from-9170), I accidentally removed this metadata constant. It will be added back in the next release (9.18). I suppose the UI for submitting nominations MUST rely on this. Temporarily, it should be hardcoded to 24 for Kusama and 16 for all other chains.

**Comment by jacogr** [comment]
The UI does not fail if it is not present, i.e. it allows chains to not specify it.

**Comment by kianenigma** [comment]
Okay, since this was an abrupt change, I wanted to give you a heads up. Feel free to close if no action is needed.

**Comment by jacogr** [comment]
Closing, no action needed at this point.
