### ISSUE TITLE
Load pending staking payouts for max eras never works

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#7085]
It always crashed and retried with 2 days. Tried all public nodes and our own private nodes for Kusama and none of it works.

**Comment by xlc** [comment]
I think the issue is that polkadot.js attempts to sending too many requests and causing some trouble on the RPC side and disconnected and crashed the page.

The simple solution is to avoid query all the eras but in multiple batches.

The solution to the root cause could be have some local rate limiting on requests and in some case use get storage instead of subscribe storage.

**Comment by xlc** [comment]
The trick doesn't work for me. Could be because I have multiple staking accounts therefore very high loads than usual.

**Comment by jacogr** [comment]
Closing. Derive has additional chunking added in the previous release.
