### ISSUE TITLE
Updating sub-identities doesn't load the previously set ones correctly

### ISSUE THREAD

**Issue by Nexus2k** [polkadot-js/apps#7097]
Issue:
When updating sub-identities it seems that the address on the left is always just one of the existing ones (e.g. last one) and the sub names however are correct.

Expected  behaviour:
The addresses should be populated by a identity lookup or something.

Actual behaviour:
The address for all sub identities is the same.

Reproduction steps:
- Have an address with an identity
- Set sub-identities with that address for at least two different addresses
- Sign the transactions
- Try updating the sub-identities by again using the "Set sub-identitites" function
- You will see that the addresses don't match the actual sub names as they are on-chain right now
- Signing the transaction like this will clear on of the sub-identities as the addresses in the form are not the old ones.

**Comment by jacogr** [comment]
The is actually a long-running issue, but has never been logged so slipped off the radar. Thanks for taking the time and making sure it is in the queue.
