### ISSUE TITLE
1002: Verification Error: Runtime error: Execution failed

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/apps#7101]
If I go to https://polkadot.js.org/apps, update to the latest metadata, switch to Polkadot network https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/accounts, and then try to transfer funds to a different account, i get errors below when trying with keep alive checks and without keep alive checks. where sender account has a balance above the existential deposit even after deducting the amount to be transferred.

the versions shown in the browser are:
Parity Polkadot v0.9.17
api v7.10.1
apps v0.107.2-14

```
balances.transferKeepAlive
1002: Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed WASM backtrace: 0: 0x2ceb - <unknown>!rust_begin_unwind 1: 0x295e - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349 2: 0x3e8ac0 - <unknown>!TaggedTransactionQueue_validate_transaction : Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed WASM backtrace: 0: 0x2ceb - <unknown>!rust_begin_unwind 1: 0x295e - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349 2…


balances.transfer
1002: Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed WASM backtrace: 0: 0x2ceb - <unknown>!rust_begin_unwind 1: 0x295e - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349 2: 0x3e8ac0 - <unknown>!TaggedTransactionQueue_validate_transaction : Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed WASM backtrace: 0: 0x2ceb - <unknown>!rust_begin_unwind 1: 0x295e - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349 2…
```

**Comment by jacogr** [comment]
That is an error from the runtime.

**Comment by ltfschoen** [comment]
i tried switching connection from Polkadot vis Parity to Polkadot via Dwellir and also Polkadot via OnFinality, but i still get the same error with each connection

i tried updating to the latest Brave browser, but even after that i still get the same error

**Comment by ltfschoen** [comment]
it is working again with:

Parity Polkadot v0.9.17
api v7.10.1
apps v0.107.2-17
