### ISSUE TITLE
Avoid hardcoded MAX_NOMINATIONS

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#7109]
https://github.com/polkadot-js/apps/blob/87ca5cc7dba58cb92e3c2045005de6894bb157b5/packages/page-staking/src/constants.ts#L4

I remember I was able to nominate up to 24 validators for Kusama via polkadot apps but no longer possible.

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/apps/issues/7078

**Comment by xlc** [comment]
I guess there isn't anything can be done now other than wait for new version so closing.
