### ISSUE TITLE
Unable to read Uniques assets for account

### ISSUE THREAD

**Issue by jsidorenko** [polkadot-js/apps#7119]
I was trying to get the NFTs list for a particular account and spot that issue:

If I don't set the `instanceId`, I'm getting all the items that the account has within the collection.
<img width="901" alt="image" src="https://user-images.githubusercontent.com/5252494/157078345-230ae275-ce47-4e48-a8a7-ab5596a28c0e.png">

And here is the result when I add the `instanceId` value:
<img width="900" alt="image" src="https://user-images.githubusercontent.com/5252494/157078671-6e578897-d9fa-4803-a55b-18aae181baf7.png">

**Comment by jsidorenko** [comment]
It doesn't bug me, it scares me :)

but now I see why it works/shows this way, it all good then

**Comment by jacogr** [comment]
`Null` has no renderer - if at least it had something for `isDisabled` (static display), it could show `Null` or something similar.

See https://github.com/polkadot-js/apps/blob/33955437cc946575b6138b919dc6c845826c04d9/packages/react-params/src/Param/Null.tsx#L8-L17

**Comment by jacogr** [comment]
The apps UI actually hides an underlying issue in the API where `None` internally wraps a `Null`, so there is no handling of `Option<Null>` there at all.
