### ISSUE TITLE
Zero commission validators are displaying on Polkadot.JS after Minimum Commission was applied.

### ISSUE THREAD

**Issue by paradox-tt** [polkadot-js/apps#7126]
Dear Polkadot.js team,

As shown in the image below, it appears that some validators are still appearing on the targets and overview pages with 0% commission.    This is after the fact that a minimum commission of 3% was applied to the chain and all non-compliant validators were forced to adhere.

![ZeroCommission](https://user-images.githubusercontent.com/79228812/157270763-fd06e9e0-b10d-4fff-a4aa-57458495091f.png)

Queries to the backend show that there aren't any non-compliant validators.  Perhaps the error lay with my queries?  A further note, when I try to forceApplyMinCommission them I get an error a 'not stash' error.  Is it possible these validators are chilled or force chilled?

Regards,
Will | Paradox

**Comment by jacogr** [comment]
![image](https://user-images.githubusercontent.com/1424473/157273870-2f3a3a32-72a3-4707-a8c3-dc3ddfee6afd.png)

**Comment by jacogr** [comment]
And something is weird, I checked the addresses and they appear in session.validators -

![image](https://user-images.githubusercontent.com/1424473/157274738-5a2d2e86-ca5f-41d5-bf43-aed7e4d10599.png)

**Comment by kianenigma** [comment]
But lots of possibilities, they could have proxy etc.

**Comment by paradox-tt** [comment]
It seems they may have been forced to chill, perhaps due to an offline event

https://kusama.subscan.io/extrinsic/11717342-0?event=11717342-1

https://kusama.subscan.io/extrinsic/11713752-0?event=11713752-1

https://kusama.subscan.io/extrinsic/11718539-0?event=11718539-2

https://kusama.subscan.io/extrinsic/11718539-0?event=11718539-1

I consider an event to be force-chilled when there's no extrinsic hash associated with the event.  I suppose you guys might know better than me if it was actually forced.

**Comment by jacogr** [comment]
So the UI works exactlty as expected here - 

- shows the validators from the session
- shows the commission at that point
