### ISSUE TITLE
Extrinsic submission failing to decode fields correctly

### ISSUE THREAD

**Issue by leonardocustodio** [polkadot-js/apps#7135]
Hello,

We have a metadata like the following:

```
{
  "MintToken": {
    "callIndex": "(u8, u8)",
    "recipient": "MultiAddress",
    "assetId": "Compact<u128>",
    "tokenId": "Compact<u32>",
    "amount": "Compact<u128>",
    "unitPrice": "Compact<u128>",
    "tokenDescriptor": "Option<TokenDescriptor>"
  },
  "TokenDescriptor": {
    "cap": "Option<TokenCap>"
  },
  "TokenCap": {
    "_enum": {
      "SingleMint": "Null",
      "Supply": "Balance"
    }
  }
}
```
For some reason polkadot.js doesn't let us to set the cap enum neither the supply value:

![image](https://user-images.githubusercontent.com/5619696/157702654-a3eb95ae-e86d-4f1e-909a-ab72ec93d29e.png)

```
apps v0.108.2-5
api v7.11.2-1
```

Best wishes,
Leonardo

**Comment by jacogr** [comment]
Since you are using metadata v14, the types you detailed above is not needed - it doesn't get used.

Do you have a chain to look at to reproduce?
