### ISSUE TITLE
account is nominating,but staking page not show my account is nominating.

### ISSUE THREAD

**Issue by jiangfuyao** [polkadot-js/apps#714]
## version
```
Alexander #338,326
parity-polkadot v0.3.14
polkadot-js-ui v0.23.25
```

## issue
My account is nominating, but staking page didn't to show It's nominating.
![_ _20190214174841](https://user-images.githubusercontent.com/34789555/52778585-4a7aff80-3081-11e9-97d1-bddd8108fc5c.png)

**to query**
![_ _20190214174031](https://user-images.githubusercontent.com/34789555/52778617-5f579300-3081-11e9-9ff4-ecdea457c137.png)

**Use js to query balance**  
```javascript
const addr = '5GfWeNe33QeyzVMV2uENuvSXLVfVXCiuLvfEP6WCDHADZhen';

console.log('free:', await api.query.balances.freeBalance(addr))
console.log('reserved:', await api.query.balances.reservedBalance(addr));
```

**js output:**    

```
free: 16922115578560693
reserved: 0
```
so it's really is nominating.

### Another issue:
When I am nominating(by query), but can to stake & unstake, and the staking page can show my account is Next Up.

**Comment by jacogr** [comment]
In this case we cannot unnominate - so basically -

- display the nominator
- have unnominate grayed out

**Comment by jacogr** [comment]
In this specific case, the actual issue is/was an incorrect display in the state query, fixed via https://github.com/polkadot-js/apps/pull/716

Basically the account displayed above is the default accountId (publicKey all 0)
