### ISSUE TITLE
Txn version not supported about ledger

### ISSUE THREAD

**Issue by Sikolopo** [polkadot-js/apps#7148]
Txn error 
tried to restore access through secret phrases on the official site (gives another wallet) + trust vallet - (it does not show my dots)
do not know what to do ((((( 

ledger 2.0.2
dot 10.9160.1
writes that everything is the latest version

**Comment by Sikolopo** [comment]
The main thing is that after restoring by the phrase is another empty address 
but other coins all restore (trust wallet) 
Help ((!

**Comment by jacogr** [comment]
If you get Ledger tx not supported, it means the Ledger software on the device itself needs to be updated.

If you wish to add a Ledger mnemonic to the apps UI, there is a specific "Ledger-compatible" option in account creation. (Assuming you are on a Ledger-compatible network and Ledger support is enabled). Basically the last option in this dropdown under Advanced options -

![image](https://user-images.githubusercontent.com/1424473/158008735-37dec184-66d6-43d0-b51a-9a5ebd2cd98e.png)

**Comment by Sikolopo** [comment]
> If you get Ledger tx not supported, it means the Ledger software on the device itself needs to be updated.
> 
> If you wish to add a Ledger mnemonic to the apps UI, there is a specific "Ledger-compatible" option in account creation. (Assuming you are on a Ledger-compatible network and Ledger support is enabled). Basically the last option in this dropdown under Advanced options -
> 
> ![image](https://user-images.githubusercontent.com/1424473/158008735-37dec184-66d6-43d0-b51a-9a5ebd2cd98e.png)

When I insert my phrase from the Ledger, it gives out a completely different ID and it's blank 
Also when I select no ledger 
<img width="740" alt="Снимок экрана 2022-03-12 в 10 43 35" src="https://user-images.githubusercontent.com/101439877/158009102-246866e0-29e7-4958-8dfa-ebecc739edf2.png">

**Comment by Sikolopo** [comment]
Looking very hard for a solution ((((

**Comment by jacogr** [comment]
As suggested above, you need to select the L:edger account type (the derivation is not compatible with the default Substrate/Polkadot defaults, so it is a special type). See -

![image](https://user-images.githubusercontent.com/1424473/158015899-2ffb058a-b4bf-48da-bea3-1c0d282d8647.png)

Ledger support needs to be enabled and you need to be on a Ledger-compatible chain for it to show up.

**Comment by Sikolopo** [comment]
<img width="1037" alt="Снимок экрана 2022-03-12 в 18 29 13" src="https://user-images.githubusercontent.com/101439877/158024281-364edcf7-4f26-4e1b-9eba-8d3ab0893731.png">
my seting Q_Q

**Comment by Sikolopo** [comment]
ledger does not give an offer to update the dot
need this Polkadot 11.9170.x

**Comment by RononDex** [comment]
I am having the same issue, I can not manage or do anything with the DOT on my ledger atm
