### ISSUE TITLE
Adjust staking with new staking interfaces

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#715]
The current interfaces for stake/unstake and nominate/unnominate is going to be completely replaced

https://github.com/paritytech/substrate/pull/1782

As a first step, keep it simple - don't yet allow multiple nominators, will log that seperately as soon as fully understood. (So v1 is just a replacement for the current functionality in an as-is manner)

Related to #714

**Comment by Kianenigma** [comment]
Note that this might emerge again once [this](https://github.com/paritytech/substrate/pull/1915) reaches here. Specially regarding the initial state.

**Comment by jacogr** [comment]
Closing, all remaining issues logged seperately, as it stands the base functionality is in place after #856
