### ISSUE TITLE
Allow sharing of snippets

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#719]
Basically like the Typescript playground -

- add base-64 encoded hash to URL
- read this on load
- copy to clipboard

**Comment by Stefie** [comment]
A quicker first-step implementation would be to just share the `value` property of the pre-baked examples in the url and pass that as the `value` to the dropdown on `componentDidMount`

**Comment by jacogr** [comment]
Yes, agreed. The sharing for me it more for custom examples, i.e. write something, share with others.

**Comment by Stefie** [comment]
Ah ok, got it.
