### ISSUE TITLE
Chain state  pallet - "balances account" doesn't show balance

### ISSUE THREAD

**Issue by nakata5321** [polkadot-js/apps#7198]
# Problem 
I was trying to get account balance on "polkadot.js.org". In Chain state `balances`-> `account` pallet doesn't show balance of account

![image](https://user-images.githubusercontent.com/55352168/159264613-b63d0000-3491-4b35-b04b-d9bd465287e2.png)
However, this balance have account and I can see it in Chain state `system`->`account` in `data` part.
![image](https://user-images.githubusercontent.com/55352168/159264974-1b165f1e-af2f-475e-8a3c-f37381e228ba.png)

 # Reproduce
Go to Chain state[[page](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.rpc.robonomics.network%2F#/chainstate)
and choose `system` -> `account` and press plus button.
Then choose `balances` -> `account` on Chain state page and press plus button again.

# System information
Firefox browser -version 97.0 (64-bit)
airalab-robonomics v1.8.4
api v7.13.1
apps v0.110.1

**Comment by jacogr** [comment]
As expected. Balances are not stored in balances.account in the default Substrate. The system.account entry allows for one write updating the nonce and balance changes. 

(Obviously depending on chain it could be stored there, the default config just moves the storage for the write optimization)
