### ISSUE TITLE
Usability issues with Transfer in polkadot.js.org 

### ISSUE THREAD

**Issue by gilles437** [polkadot-js/apps#7207]
Transfer funds 

1 - Send to address looks like a dropdown, when you click on the arrow, it shows the addresses you have in your js-extention, and it's not obvious to see that you can simply paste an address if you don't read the documentation.

<img width="693" alt="Screenshot 2022-03-22 at 16 50 10" src="https://user-images.githubusercontent.com/28502710/159529668-f6ae4648-b2d9-4d5f-b2eb-e6a7077e50ce.png">

Suggestion: Make it look as en empty field, with no default, and keep the drop down arrow that shows the existing addresses. Also, no need to add the sender address in the send to dropdown

2 - Plain Text explanations are not necessary and get the attention of the user for something supposed to be obvious
For example, the first line says:
The transferred balance will be subtracted (along with fees) from the sender account.
<img width="363" alt="Screenshot 2022-03-22 at 17 38 18" src="https://user-images.githubusercontent.com/28502710/159530087-387f2674-97d6-420c-bf3e-f4d8bd2204c0.png">

Suggestion: The explanation should be displayed when mouse over a "?" 

3 - The dropdown menu in the amount section, showing 12 different units of quantity is in my opinion unnecessary. First, not everybody knows what is a nano or a peta or a zeta, and second, why providing complicate units when users can type any amount in the box.
<img width="696" alt="Screenshot 2022-03-22 at 17 37 22" src="https://user-images.githubusercontent.com/28502710/159529907-9a32d9e7-4305-4cef-b810-915ded8595e2.png">

Suggestion: Reduce the list to Milli DOT and Kilo DOT. Given that the price of a small transfer is 15.6 millidots today.

4 - When I click on "Make transfer", the authorize page appears, showing the from address, but not the to address.

Suggestion: Add the to address below the from address
<img width="1055" alt="Screenshot 2022-03-22 at 17 38 51" src="https://user-images.githubusercontent.com/28502710/159530208-d04979a7-13fe-4070-8ec4-9bde998eac69.png">

**Comment by shawntabrizi** [comment]
> Also, no need to add the sender address in the send to dropdown

What do you mean here?

**Comment by jacogr** [comment]
The last suggestion is a wontfix - not going to go and add either specific transaction detection or build in the params components that decodes all into the signer. 

As for the first point, the empty default is certainly breaking my specific workflow completely by always requiring a click in all address selections. (This applies everywhere an address is used, so also a wontfix from me)

**Comment by gilles437** [comment]
> > Also, no need to add the sender address in the send to dropdown
> 
> What do you mean here?
> 
<img width="688" alt="Screenshot 2022-03-22 at 18 11 18" src="https://user-images.githubusercontent.com/28502710/159537436-26c69332-2542-4515-9732-75a6c5fb43d7.png">

So as you can see, in the dropdown there is the address of the "send from account", which is impossible, the sender cannot be the receiver also, so to my opinion the account of the sender should be removed from the drop down menu. 

> > 4 - When I click on "Make transfer", the authorize page appears, showing the from address, but not the to address.
> 
> I believe this is a "generic" authorize transaction pop up you are seeing.
> 
> If you click the drop down to the transaction information, you will see the address, but not well formatted.
> 
> <img alt="image" width="1072" src="https://user-images.githubusercontent.com/1860335/159534355-1a8b4229-3e10-48c8-8d60-987b55018525.png">
> 
> I think it makes sense when you know its a transfer, to have a transfer specific pop up with custom formatting, so this is a good idea

Yes, using the same format as the 



> > Also, no need to add the sender address in the send to dropdown
> 
> What do you mean here?

<img width="688" alt="Screenshot 2022-03-22 at 18 11 18" src="https://user-images.githubusercontent.com/28502710/159538601-ee46d724-713b-407c-9942-939f0fc0c5b8.png">

the "Send From Account"  appears as a possible option when opening  the drop down, which is not possible, the sender cannot be the receiver.  

> 
> > 4 - When I click on "Make transfer", the authorize page appears, showing the from address, but not the to address.
> 
> I believe this is a "generic" authorize transaction pop up you are seeing.
> 
> If you click the drop down to the transaction information, you will see the address, but not well formatted.
> 
> <img alt="image" width="1072" src="https://user-images.githubusercontent.com/1860335/159534355-1a8b4229-3e10-48c8-8d60-987b55018525.png">
> 
> I think it makes sense when you know its a transfer, to have a transfer specific pop up with custom formatting, so this is a good idea

Yes, using the same format as the sender box

**Comment by gilles437** [comment]
> > > Also, no need to add the sender address in the send to dropdown
> > 
> > 
> > What do you mean here?
> 
> <img alt="Screenshot 2022-03-22 at 18 11 18" width="688" src="https://user-images.githubusercontent.com/28502710/159537436-26c69332-2542-4515-9732-75a6c5fb43d7.png">
> 
> So as you can see, in the dropdown there is the address of the "send from account", which is impossible, the sender cannot be the receiver also, so to my opinion the account of the sender should be removed from the drop down menu.
> 
> > > 4 - When I click on "Make transfer", the authorize page appears, showing the from address, but not the to address.
> > 
> > 
> > I believe this is a "generic" authorize transaction pop up you are seeing.
> > If you click the drop down to the transaction information, you will see the address, but not well formatted.
> > <img alt="image" width="1072" src="https://user-images.githubusercontent.com/1860335/159534355-1a8b4229-3e10-48c8-8d60-987b55018525.png">
> > I think it makes sense when you know its a transfer, to have a transfer specific pop up with custom formatting, so this is a good idea
> 
> Yes, using the same format as the
> 
> > > Also, no need to add the sender address in the send to dropdown
> > 
> > 
> > What do you mean here?
> 
> <img alt="Screenshot 2022-03-22 at 18 11 18" width="688" src="https://user-images.githubusercontent.com/28502710/159538601-ee46d724-713b-407c-9942-939f0fc0c5b8.png">
> 

> 
> > > 4 - When I click on "Make transfer", the authorize page appears, showing the from address, but not the to address.
> > 
> > 
> > I believe this is a "generic" authorize transaction pop up you are seeing.
> > If you click the drop down to the transaction information, you will see the address, but not well formatted.
> > <img alt="image" width="1072" src="https://user-images.githubusercontent.com/1860335/159534355-1a8b4229-3e10-48c8-8d60-987b55018525.png">
> > I think it makes sense when you know its a transfer, to have a transfer specific pop up with custom formatting, so this is a good idea
> 




> The last suggestion is a wontfix - not going to go and add either specific transaction detection or build in the params components that decodes all into the signer.
> 
> For the explanations, they won’t go since it is consistent in all modals. Just having the (?) like we used to killed my support queue. Prefer not doing that again. (Explanations can certainly be expanded and reworked)
> 
> As for the balance size, you are suggesting chain specific logic (chains have very different setups), which is a maintenance nightmare.
> 

I think this functionality is pretty unique, and I don't know another example of it. I am not saying it's bad, but it is moo much irrelevant information for a specific blockchain, in this case DOT, which is the main case. So I was suggesting a way to simplify it, but I agree that if other chains have other proportions in terms of the price of the token, then this suggestion is not appropriate. 
On the other side, if we look at other blockchains wallets (cosmos, binance, ethereum ), amounts are specified in numbers only, there are no units as far as I know, so maybe staying with this "standard" would be more appropriate.

> As for the first point, the empty default is certainly breaking my specific workflow completely by always requiring a click in all address selections. (This applies everywhere an address is used, so also a wontfix from me)


Ok, maybe adding a help text saying "Paste your address here" would make it more clear that the user can enter an address, rather than only choosing from the dropdown?

**Comment by shawntabrizi** [comment]
>  Send to address looks like a dropdown, when you click on the arrow, it shows the addresses you have in your js-extention, and it's not obvious to see that you can simply paste an address if you don't read the documentation.

Maybe a good compromise is leave the default account there, but add to the drop down a selector which is "Send to a custom address" which makes it obvious that this is a text field that you can type into.
