### ISSUE TITLE
Display issue in the Account page of polkadot.js.org

### ISSUE THREAD

**Issue by gilles437** [polkadot-js/apps#7208]
Account page 

1 - In Accounts section, balance does not refresh and shows empty, not 0 but empty, while it's not. There are DOTs on both account in reality.
When refreshing the page, balance shows up correctly.

<img width="1367" alt="Screenshot 2022-03-22 at 17 40 49" src="https://user-images.githubusercontent.com/28502710/159530667-1d2d0fbf-6912-4745-ab96-b0603bf680e8.png">

**Comment by jacogr** [comment]
Can only think of a network glitch. Weird indeed since I’ve never run I to it.

**Comment by gilles437** [comment]
This is indeed a problem related to network glitch.

I have 2 Wifi networks around me and depending on where I am, I may reconnect to another network.
So I guess this created the conditions of the bug finding.

But I could reproduce it just by shutting down the wifi on my mac for one minute.
So here is the sequence:

1. Go to one of the governance topics, let's say Democracy
2. Turn off your Wifi
3. Wait 20-30 seconds and go to Accounts->Accounts. The balances should show empty. 
4. Turn on Wifi 
5. The balances still shows empty

This sequence works most of the time, not always though

Other than that by doing these tries I have encountered other issues, like having the page stuck forever with this message:

<img width="1381" alt="Screenshot 2022-03-23 at 12 00 48" src="https://user-images.githubusercontent.com/28502710/159684952-6bd48480-600e-4d5b-9df3-bc7f444a4b88.png">
