### ISSUE TITLE
Webpack errors on separate project mirroring apps.

### ISSUE THREAD

**Issue by drewstone** [polkadot-js/apps#7210]
I'm building a project with webpack 5 and down to one final error. I'm following the CSS webpack configuration in polkadot/apps to the tune of:
```
{
  include: /node_modules/,
  test: /\.css$/,
  use: [MiniCssExtractPlugin.loader, require.resolve('css-loader')],
},
```

I still get the following error when running the app. I am using much the same webpack configuration files as are in this repo.
```
ERROR in ../ui-components/src/styles/global.css 2:5
Module parse failed: Unexpected token (2:5)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| html,
> body {
|   margin: 0;
|   padding: 0;
 @ ../ui-components/src/UIProvider.tsx 1:0-29
 @ ../ui-components/src/index.ts 8:0-29 8:0-29
 @ ./src/App.tsx 4:0-54 19:38-48
 @ ./src/index.tsx 3:0-24 5:107-110

webpack 5.70.0 compiled with 1 error and 16 warnings in 12821 ms
```

I've tried many combinations with no success. This error continues to persist. Any ideas how to debug?

**Comment by jacogr** [comment]
You rule above only applies to css files in node_modules, not those in your source tree.
