### ISSUE TITLE
The setting custom didn't work

### ISSUE THREAD

**Issue by jiangfuyao** [polkadot-js/apps#722]
Set myself node ws, didn't work

**Comment by jacogr** [comment]
Cannot quite replicate -

- stated substrate with `--ws-port 9988`
- node doesn't connect
- changed setting to `ws://127.0.0.1:9988`
- node connects

<img width="700" alt="polkadot apps portal 2019-02-17 08-18-43" src="https://user-images.githubusercontent.com/1424473/52909683-cf863480-328c-11e9-9d8f-3921fb60558d.png">

**Comment by jacogr** [comment]
Issue is ws from an https host. With the connection dialog (and entry) display that it is not possible. 

- ws is allowed when running locally (either UI or node)
- when deployed on https can only connect to non-local wss

Check protocol of where UI is running and apply logic
