### ISSUE TITLE
no icon in `https://polkadot.js.org/apps`

### ISSUE THREAD

**Issue by JimYam** [polkadot-js/apps#7240]
hey,  there is no icon for the Listen Network in `https://polkadot.js.org/apps`. What is the reason for this？
![noicon](https://user-images.githubusercontent.com/96558044/160238199-3e665d10-5599-4e37-aaf9-3eea8d8f0bb9.png)

**Comment by jacogr** [comment]
The code has instructions - https://github.com/polkadot-js/apps/blob/eb23271930d8f748cab95f37590e8da3931041f4/packages/apps-config/src/ui/logos/index.ts#L560-L563

**Comment by JimYam** [comment]
> The code has instructions for the setup -
> 
> https://github.com/polkadot-js/apps/blob/eb23271930d8f748cab95f37590e8da3931041f4/packages/apps-config/src/ui/logos/index.ts#L560-L563
> 
> Please test changes locally when making PRs.

Thank you very much. I will try my best to check the code before submitting it, but because I am not a front-end developer, there may be errors
