### ISSUE TITLE
Proposal/discussion to update the SS58 format long description tooltip.

### ISSUE THREAD

**Issue by chrisdcosta** [polkadot-js/apps#7251]
In the settings page the the tooltip for the SS58 format describes the format as follows: 

`Prefix indicates the ss58 address format in this network, it is a number between 0 ~ 255 that describes the precise format...`

This refers to the original format for the SS58Prefix being of type `u8`. This has now been changed to `u16` type allowing for more values to be created.

I propose to change the text to read:

`Prefix indicates the ss58 address format in this network, it is a 16-bit integer that describes the precise format...`

However, this impacts many already translated files and so it cannot be globally updated in english without creating inconsistencies with the translated versions.

**Comment by jacogr** [comment]
It sounds spot-on.

That is fine. If untranslated, the English version will show.

PRs really welcome.

**Comment by chrisdcosta** [comment]
Ok I will work on it.

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/apps/pull/7277
