### ISSUE TITLE
Cannot connect to Rococo using polkadot.js.org

### ISSUE THREAD

**Issue by PierreBesson** [polkadot-js/apps#7252]
I am unable to connect to Rococo (`https://rococo-rpc.polkadot.io`), I have the following error:

I am able to reproduce in both Chrome and Firefox with the latest version of the extension and in private browsing mode.

```
FATAL: Unable to initialize the API: PortableRegistry: 76 (bp_messages::DeliveredMessages): Error extracting {"path":["bp_messages","DeliveredMessages"],"params":[],"def":{"composite":{"fields":[{"name":"begin","type":8,"typeName":"MessageNonce","docs":[]},{"name":"end","type":8,"typeName":"MessageNonce","docs":[]},{"name":"dispatch_results","type":77,"typeName":"DispatchResultsBitVec","docs":[]}]}},"docs":[]}: PortableRegistry: 77: Error extracting {"path":[],"params":[],"def":{"bitSequence":{"bitStoreType":2,"bitOrderType":78}},"docs":[]}: Unexpected bitOrder found as bitvec::order::Msb0
```

![image](https://user-images.githubusercontent.com/513471/160382309-51eed473-b8bb-4ed6-8c11-9be7b035bb4f.png)

**Comment by jacogr** [comment]
Should be fixed, there was an issue logged earlier for it.

**Comment by jacogr** [comment]
For future reference, it was this one - https://github.com/polkadot-js/api/pull/4699
