### ISSUE TITLE
Account page crash. cannot reading properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by JayJay1024** [polkadot-js/apps#7261]
![image](https://user-images.githubusercontent.com/21007682/160593741-338fc8f6-b653-4704-ace2-bd3e4419eb80.png)
![image](https://user-images.githubusercontent.com/21007682/160593778-446afee6-748e-4933-873f-e2d1b6ccb6cf.png)

**Comment by jacogr** [comment]
Closed in #7262
