### ISSUE TITLE
Enable usage of proxy accounts without access to target wallet

### ISSUE THREAD

**Issue by hitchhooker** [polkadot-js/apps#7278]
https://www.youtube.com/watch?v=-JfQ2vCipWU&t=51m50s
@shawntabrizi speaking about this idea of creating proxies for other people to do things on your behalf, but currently it ain't possible to interact with polkadot.js UI, if the proxy target wallet is not added to the browser/wallet-extension even there is proxy link already created for the said wallet. 
Tried adding proxied target wallet in address book as a work around, but that does not seem to work out either.

**Comment by jacogr** [comment]
If you have an proxy account that proxies a specific address, just use "+ Proxied" - it checks that address entered against your accounts, if you have the proxy available it can be added.

(I have 5+ accounts where I don't have access to the private keys myself, only the proxy)
