### ISSUE TITLE
display issues in the votes summary of the democracy dashboard listings

### ISSUE THREAD

**Issue by gilles437** [polkadot-js/apps#7304]
Here are 2 display issues in the governance system:

**Problem**: The current display is difficult to read and can be confusing
**Suggested change**: Replace the current voters summary with a graphic visual, for a example a donut, showing the percentage of Aye/Naye for each vote.

![Screenshot 2022-04-05 at 11 05 03](https://user-images.githubusercontent.com/28502710/161719777-37ab00b0-b3b9-4b9d-85d1-9d9671b5a640.png)

**Problem**: The current display distorts the whole display of the page when clicking on the arrow in the votes column
**Suggested change**: Replace the current display of voters with a modal showing the voters in a table, with a detailed summary of amounts voted.

![Screenshot 2022-04-05 at 11 07 09](https://user-images.githubusercontent.com/28502710/161720026-217d2d2f-da5f-4c41-80d9-0b58575cf197.png)

**Comment by gilles437** [comment]
The display of a check icon aside the Vote button is misleading because it gives the impression to the user that he already voted.

![Screenshot 2022-04-11 at 13 43 12](https://user-images.githubusercontent.com/28502710/162733069-f208d336-0a2e-45b0-8afd-e27c5c2225f0.png)

In addition, the same check icon is used in the current UI where the user has to choose between Aye and Nay

![Screenshot 2022-04-11 at 13 42 57](https://user-images.githubusercontent.com/28502710/162732915-0a497d9a-8b33-4634-8c8e-06d34c25f49f.png)

This check icon appears at different places in the Governance module:

1. In The Democracy section of Governance
2. In the Council->Motions section of Governance
3. In the Council->Overview of Governance, in the header Summary section.

As part of the modifications done in the Governance module, and to generalise changes that were applied in this fix, here is a summary of places where the icon "check" should be  replaced.

**Comment by gilles437** [comment]
@Jaco, I am about to submit some changes, but I have some issue with a new module that I added named react-table-scrollbar.
When I try to install this module

npm i --save-dev @types/react-table-scrollbar

 I have an error saying that:

<img width="920" alt="Screenshot 2022-04-11 at 14 16 23" src="https://user-images.githubusercontent.com/28502710/162737479-0dbe74a6-9d62-478e-af78-b8a571b1c6bb.png">

Do I need to add the module differently?

**Comment by jacogr** [comment]
If you have a better `fa-*`, it is welcomed.

**Comment by gilles437** [comment]
Here is a nice one:

<img width="490" alt="Screenshot 2022-04-11 at 18 05 36" src="https://user-images.githubusercontent.com/28502710/162783143-d587a93a-a188-480a-909b-b1013b928c69.png">

**Comment by jsidorenko** [comment]
How about using the right panel to display the voters and maybe some other useful info?

**Comment by jsidorenko** [comment]
I mean the one that appears when you click on an account

**Comment by gilles437** [comment]
The plan is to use the inline expand arrow similar to what we have in the Bounties page, on click on the right arrow, an inner box opens to show more info, which in this case will display the links to the external apps and also display the description of the referendum

<img width="1390" alt="Screenshot 2022-04-12 at 13 50 16" src="https://user-images.githubusercontent.com/28502710/162954423-3e5b1c8d-26e1-4284-91bf-9bcfbea280c1.png">
<img width="1382" alt="Screenshot 2022-04-12 at 13 50 24" src="https://user-images.githubusercontent.com/28502710/162954478-0892a0e5-3ba8-40c3-93f7-c2f05307efcd.png">

**Comment by jsidorenko** [comment]
I mean to display the voters list: 
<img width="258" alt="image" src="https://user-images.githubusercontent.com/5252494/162956543-1feda741-16be-4622-97cd-c75857f4c1d0.png">

**Comment by gilles437** [comment]
well, the voters now appear in a reduced scroll-able table, with the same level of information, and it doesn't take the whole page as before, which is the problem we are trying to solve.  

<img width="1376" alt="Screenshot 2022-04-12 at 14 19 09" src="https://user-images.githubusercontent.com/28502710/162961053-d583fefe-3aee-4edb-9efe-c20ccd9e1587.png">

clicking on any of the voters in this list will open the modal window on the right to display information about the voter itself, just like before.

<img width="1365" alt="Screenshot 2022-04-12 at 14 20 09" src="https://user-images.githubusercontent.com/28502710/162961336-52dd04bd-79ec-4804-be5d-b6b15a31fb15.png">

So I think that we keep the general mode of operation and I don't see additional information regarding the users that we could add.

**Comment by jacogr** [comment]
Closing.
