### ISSUE TITLE
Unable to inject accounts for Moon* chains

### ISSUE THREAD

**Issue by ekenigs** [polkadot-js/apps#7317]
On chains Moonbeam, Moonriver, and Moonbase Alpha accounts can't be injected from the extension.

Warning in the console:
<img width="1725" alt="Screenshot 2022-04-06 at 10 18 31" src="https://user-images.githubusercontent.com/15612217/162032676-db4b930a-aee4-491f-81b8-d3ef443a6068.png">
It's coming from here: https://github.com/polkadot-js/ui/blob/master/packages/ui-keyring/src/Keyring.ts#L303

Error that is getting overwritten by warning:
<img width="394" alt="Screenshot 2022-04-06 at 10 20 04" src="https://user-images.githubusercontent.com/15612217/162032873-1b1c9efd-9713-4fe7-9cf3-484dfc4e3326.png">
It's coming from here: https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/secp256k1/expand.ts#L16

My assumption is that it's after this change https://github.com/polkadot-js/wasm/releases/tag/v5.1.1
* Swap from libsecp256k1 to secp256k1 (this aligns with the Substrate use)

**Comment by jacogr** [comment]
It should only inject the non-ed25519 and non-sr25519 accounts. In my case have a single account created for Moonbeam, but have 3 others exposed to all chains as well. Only the secp256k1 account gets injected, the others are warned about -

![Polkadot:Substrate Portal 2022-04-07 15-12-14](https://user-images.githubusercontent.com/1424473/162196350-d0d0131a-fe01-49ff-bb50-17e11eeb39c4.jpg)
