### ISSUE TITLE
Calculate treasury deposits with proposalBondMaximum

### ISSUE THREAD

**Issue by Nick-1979** [polkadot-js/apps#7336]
Hello,

While submitting a treasury proposal, it seems that  "proposalBondMaximum" needs to be considered too. am I right?

Thank you

![proposalBondMaximum](https://user-images.githubusercontent.com/46442452/162568457-296886d9-e29e-47a0-9c97-f318dff9adc1.jpg)

**Comment by Nick-1979** [comment]
oh my bad, thank you for moving

**Comment by jacogr** [comment]
It is still valid, the max bond is a very recent introduction (so may be worth a PR to adjust)

**Comment by Nick-1979** [comment]
was closed mistakenly
