### ISSUE TITLE
Parachain status

### ISSUE THREAD

**Issue by Nick-1979** [polkadot-js/apps#7347]
hello,

Shouldn't the Pichu label be "winner" instead of "ended"?
![image](https://user-images.githubusercontent.com/46442452/162668464-c30ab5d4-2602-499d-bef1-ad07c290d500.png)

**Comment by jacogr** [comment]
Look at the `slots.leases(2102)` the address (decoded) is `109,111,100,108,112,121,47,99,102,117,110,100,69,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0`

For the crowdloan the address (decoded) is `109,111,100,108,112,121,47,99,102,117,110,100,54,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0` (`54,8,0,0` is 2102)

It only is wrong for this recent one.

The only thing I can think of is that it is related to the recent tried_index to fund_id, but will need to check the Rust code again.
