### ISSUE TITLE
Change "Second" button and "Seconded" column on the public proposals queue

### ISSUE THREAD

**Issue by rrtti** [polkadot-js/apps#7351]
We should change the word "Second" and "Seconded" on the public proposals queue on democracy tab to "Endorse" and "Endorsed" - we think it would make the seconding action more intuitive, as users endorse a proposal if they agree with it to make it to referenda queue faster.

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/apps/pull/7360
