### ISSUE TITLE
substrate node runtime upgrade setCode: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Bart200c** [polkadot-js/apps#7371]
api v8.0.1
apps v0.112.2-11
x.compact.wasm size: (3,698,475 bytes)

do wasm runtime upgrade:
Extrinsics -> sudoUncheckedWeight(call, weight) -> system -> setCode

Is a polkadot-js's bug or something wasm runtime wrong ?

error Log:
![image](https://user-images.githubusercontent.com/103230129/163208429-0cd59bbc-09f2-4044-961d-ce2bc853fb08.png)

**Comment by Bart200c** [comment]
Do sign and submit:

```
sudo.sudoUncheckedWeight
createType(ExtrinsicPayload):: createType(ExtrinsicPayloadV4):: Struct: failed on method: Bytes:: Maximum call stack size exceeded
```

**Comment by jacogr** [comment]
Cannot replicate with a 6.1MB file, upgrading a local node, on https://polkadot.js.org/apps/

**Comment by Bart200c** [comment]
YES, It works with *.compact.compressed.wasm (700kb)
