### ISSUE TITLE
page not display on safari

### ISSUE THREAD

**Issue by rustbomber** [polkadot-js/apps#7373]
it is work on Firefox and chrome, but not work on safari. 

always  Initializing connection....., and report error at  console .

![image](https://user-images.githubusercontent.com/437330/163361355-c9959d00-4b56-45fe-b065-b3ad4bba77d0.png)

my env:
- Operating system:  MacOS Monterey 12.3.1 (21E258), MacBook Pro (13-inch, 2016, Two Thunderbolt 3 ports) 
- safari: Version 15.4 (17613.1.17.1.13)

**Comment by jacogr** [comment]
It works on e.g. `wss://rpc.polkadot.io`, but not on the `ws://127.0.0.1:9944` domain. In this case it seems like the Safari https -> ws (insecure sockets) is stricter than Chrome/Firefox which does allow it. This is the problematic log (last line) -

![image](https://user-images.githubusercontent.com/1424473/163400658-acc9004f-f95d-4ba5-a819-601a3bf17b19.png)

There is nothing code-wise that apps can do, it is security policy. For workarounds -

1. Run the apps UI locally (i.e. clone it and run it)
2. Place the node behind a nginx proxy (which feels like overkill, obviously required for hosted services, but...)
3. Don't use Safari for local nodes
4. There _might_ be a preference that can be set to allow this, unsure about it

**Comment by rustbomber** [comment]
@jacogr Thank you for your reply, I will use Firefox first.
