### ISSUE TITLE
Voting period calculation problem

### ISSUE THREAD

**Issue by jiangfuyao** [polkadot-js/apps#743]
Now is use `api.derive.democracy.referendums()`'s `result.end` minus the `bestBlockNumber` it's right;  
The UI-apps Voting period, no longer provides an accurate end-of-voting period

**Comment by jacogr** [comment]
voting period is useless info since it overlaps with launch (and gives the wrong info), should be removed.

**Comment by jacogr** [comment]
<img width="1280" alt="polkadot apps portal 2019-02-21 10-26-51" src="https://user-images.githubusercontent.com/1424473/53158150-3ecc9300-35c3-11e9-9ad0-5c47be6d33db.png">
