### ISSUE TITLE
how to withdraw funds

### ISSUE THREAD

**Issue by Chambers-Chambers** [polkadot-js/apps#7435]
how do i withdraw funds for polkadot.js? Ive tried moving 1 DOT but i believe it dissapeared so i am afraid to send DOT directly to Coinbase in fear of losing the funds. Or do i need to send the funds to my metamask then to coinbase? any info is appreciated--much thanks

**Comment by jacogr** [comment]
There are no tricks - it simply sends the transaction to the blockchain when you use the transfer modal. In the case of transfers if the destination wallet has no funds in it, you need to ensure the amount is > 1 DOT - it is the runtime existential deposit, i.e. the minimum amount needed for any account to exist on the blockchain.

**Comment by Chambers-Chambers** [comment]
how do i use the transfer modal. when i click send; it only allows me to
transfer from the sender to the receiver but their the same address, how do
i make it my metamask wallet

**Comment by jacogr** [comment]
You click the dropdown and select the recipient.

**Comment by Chambers-Chambers** [comment]
got it, i didn't realize i had connected just that wallet and was
attempting to send it to another wallet.--much thanks
