### ISSUE TITLE
Multisig extrinsics result in MaxWeightTooLow failures

### ISSUE THREAD

**Issue by arjanz** [polkadot-js/apps#7453]
It seems since last runtime upgrade on Kusama multisig extrinsic result  in `MaxWeightTooLow` failures, probably because `max_weight` is set to 0:

Example: https://kusama.subscan.io/extrinsic/12420311-2

```
[
  {
    name: "threshold",
    type: "U16",
    type_name: "u16",
    value: 2
  },
  {
    name: "other_signatories",
    type: "Vec<[U8; 32]>",
    type_name: "Vec<AccountId>",
    value: [
      "0x76d0986d0043241fe80a7b7e82a024cef404255a21966558620db27d0330c963",
      "0x847e5385aead67f3926d5355a2a2273f5830bb91cf3a8fbb7fd5784d28b67975"
    ]
  },
  {
    name: "maybe_timepoint",
    type: "option<pallet_multisig:Timepoint>",
    type_name: "Option<Timepoint<BlockNumber>>",
    value: {
      height: 12420308,
      index: 3
    }
  },
  {
    name: "call",
    type: "WrapperOpaque<Call>",
    type_name: "OpaqueCall",
    value: {
      call_index: "0403",
      call_module: "Balances",
      call_name: "transfer_keep_alive",
      params: [
        {
          name: "dest",
          type: "sp_runtime:multiaddress:MultiAddress@203",
          value: {
            Id: "0x76d0986d0043241fe80a7b7e82a024cef404255a21966558620db27d0330c963"
          }
        },
        {
          name: "value",
          type: "compact<U128>",
          value: "8000000000000"
        }
      ]
    }
  },
  {
    name: "store_call",
    type: "Bool",
    type_name: "bool",
    value: false
  },
  {
    name: "max_weight",
    type: "U64",
    type_name: "Weight",
    value: 0
  }
]
```

**Comment by jacogr** [comment]
Probably this PR that broke it? https://github.com/paritytech/substrate/pull/10662

**Comment by shawntabrizi** [comment]
> Probably this PR that broke it? [paritytech/substrate#10662](https://github.com/paritytech/substrate/pull/10662)

Seems really unlikely. This should be a just a syntax change, with nothing actually changing underneath

**Comment by jacogr** [comment]
The only other thing then is if the weight comes back as 0 via paymentInfo - since it actually explicitly queries that.

**Comment by jacogr** [comment]
If all the RPC nodes have not been updated.... then it would make sense. Since the RPC calls into the runtime, have seen this multiple times that when the 2 mismatch, issues do pop up. (Generally this however throws an exception, not an invalid weight)
