### ISSUE TITLE
Sub.id link not redirecting properly

### ISSUE THREAD

**Issue by Cornrob** [polkadot-js/apps#7485]
When on polkadot.js.org I click to ID, I'm redirected to a link like this: sub.id/#/address but it only leads me to the sub.id search page; to get to the right place I need to erase the # and one / to have the link like sub.id/address and then I reach the correct place.

**Comment by jacogr** [comment]
Thank you, will remove it then since I'm not sure where the team intended it to go or if it was changed in the meantime. (As with all the links these are contributed by the teams themselves, so don't have insights into the correct locations)
