### ISSUE TITLE
Firefox Table Render Bug

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/apps#7497]
On the tips page I am seeing:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/1860335/166140467-a0c66b61-3f41-4382-ab98-abe683e37a23.png">

This appears on Firefox, but seems to have no issue on Chrome.

**Comment by jacogr** [comment]
Chrome is the same -

![image](https://user-images.githubusercontent.com/1424473/166184868-1550602c-f328-4e4a-9bac-e9722e765277.png)
