### ISSUE TITLE
Xcm msg hyperlinks

### ISSUE THREAD

**Issue by gilescope** [polkadot-js/apps#7510]
Now that https://github.com/polkadot-js/apps/pull/7507 is merged, here's the moonshot:

We can see on kusama here a message to statemine but without decoding it we can not be sure what the message contains:
![Screenshot from 2022-05-03 09-10-21](https://user-images.githubusercontent.com/803976/166425953-081533af-1713-4c63-b5cc-572d265684df.png)

In a perfect world that `encoded` would be a hyperlink that would open a new tab pointing to  https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fstatemine-rpc.polkadot.io#/extrinsics/decode/0x010209523239ac0d682a3e38682096d742b4eb14c96f77c66e954cb15e9b0a5cb6b7

We would need some code to interpret the xcm a bit and map the parachain id to an appropriate ws address but if we did this then my mum could understand what's going on by just clicking through the link.

I can't do this alone, I am going to need help, but this really shines a light on XCM and makes it more understandable as to what people are looking at (which improves security). I would love some pointers. I think that the code I need to look at might actually be in https://github.com/polkadot-js/api ...?

**Comment by gilescope** [comment]
I see LinkOption has paraId on it so that's fine. Just a question of finding a way to inject a hyperlink at the right bit.

**Comment by jacogr** [comment]
This is possible, but it is a shyteload of work. 

Neither the API not the Apps UI has any idea of what they are decoding or displaying. Especially in the API, it is just a generic holder that decodes stuff - oblivious to the outside world.

In this case, it is super tricky UI wise - 

1. You need to understand the tx you are dealing with
2. You need to know the exact param order (and the various runtime versions that may change)
3. Extract destination chain
4. Look for the XcmDoubleEncoded type (assuming this has _not_ been renamed - a number of chains always have their own type implementations)
5. Pass params to the Struct decoder and render (you actually want a specialized extrinsic decoder for this type, assuming you know the pallets it operates on)
