### ISSUE TITLE
Voting with default vote amount in Democracy tab will always fail due to insufficient funds

### ISSUE THREAD

**Issue by ghzlatarev** [polkadot-js/apps#7514]
Currently when you go to the Democracy tab and vote on a referendum, the default vote value is the Max Balance of the account with x0.1 conviction. 
This will always fail with `pallet_democracy::InsufficientFunds` because the transaction fee will use up some of the balance. 
![max_votre](https://user-images.githubusercontent.com/45011053/166459029-19131c8b-13cf-4b21-aa6a-07d9cb9d21c7.PNG)

**Comment by jacogr** [comment]
It does always ensure that the default is either 

- (a) the existing locked balance, or
- (b) the voting balance minus the existential

In your case it would seem the existential is exceptionally low - in that case, yes, it won't succeed

**Comment by jacogr** [comment]
It would depend on the fees - if the fees going to be > ED, this ED check is not enough and for those edge cases we would need to explicitly query the payment info, assuming it is available, and subtract in addition. (Which is not very ergonomic from either a coding, maintenance or UX perspective at all)

**Comment by ghzlatarev** [comment]
Ah yes of-course that makes sense. The fees are indeed more than the ED.
