### ISSUE TITLE
Use snappy to compress share links

### ISSUE THREAD

**Issue by Stefie** [polkadot-js/apps#752]
Use Snappy to compress the `code` strings before converting them the base64 for the share-links. 
https://github.com/zhipeng-jia/snappyjs

**Comment by rossbulat** [comment]
Yes, this looks possible with TextEncode and TextDecode, that converts the code block string into a buffer which can then be compressed with Snappy.

Will test shortly.

**Comment by Stefie** [comment]
Hi @rossbulat , thanks for your interest! 
I was working on this yesterday evening and just didn't quite finish it and therefore didn't open a PR (which I just did). I should have assigned the ticket to me to make that clear.

**Comment by rossbulat** [comment]
Hi @Stefie , no problem, great it has been implemented.
