### ISSUE TITLE
Pools metrics not shown properly when not set

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/apps#7520]
The pools are now deployed to westend and we have not yet set any values for any of the min/max storage items, and the UI could perhaps do a slightly better job at rendering those `0`. plus, the join button seems to be missing. 

<img width="1728" alt="Screen Shot 2022-05-04 at 12 03 15" src="https://user-images.githubusercontent.com/5588131/166671702-424785dc-51d9-41dc-adf5-5f91eed3aeeb.png">

**Comment by jacogr** [comment]
Weird about "Join".
