### ISSUE TITLE
Events are not displayed in explorer

### ISSUE THREAD

**Issue by shelvenzhou** [polkadot-js/apps#7524]
The latest polkadot.js app does not display many recent events in explorer. 

E.g., I send an event with `system.remarkWithEvent`, which is included in [block](https://polkadot.js.org/apps/#/explorer/query/0x860f518693459188a6608523c8c5de770423bdcd9aa580de4ccee6a3a5fcbaf9).
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/5029067/166700600-8f128f93-90c5-4136-9daa-392aa4f569f2.png">

While there is no events observed  in `recent events`.
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5029067/166700737-56a5c4af-d3af-4b54-8714-78cd3a0be37c.png">

**Comment by jacogr** [comment]
The recent events applies filtering, e.g. none of `system.*`, etc. The full rules here - https://github.com/polkadot-js/apps/blob/df915e38afacf94b0a8297850c5c92a35d06af52/packages/react-query/src/Events.tsx#L37-L47

Without filters , it is overwhelming.

**Comment by TomaszWaszczyk** [comment]
@shelvenzhou Have you solved the issue? Does it work for you?

**Comment by shelvenzhou** [comment]
Yes, thanks!

发件人: Tomasz Waszczyk ***@***.***>
日期: 星期二, 2022年5月31日 09:30
收件人: polkadot-js/apps ***@***.***>
抄送: Shunfan Zhou ***@***.***>, Mention ***@***.***>
主题: Re: [polkadot-js/apps] Events are not displayed in explorer (Issue #7524)

@shelvenzhou<https://github.com/shelvenzhou> Have you solved the issue? Does it work for you?

―
