### ISSUE TITLE
i128 field doesn't accept negative number

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#7536]
The worse part is that I craft the tx with js code, enter it to extrinsic decode section, now I need to go to submission section and it removes the negative sign and changed my tx. Glad I checked it before submitting it.

Should also assert the tx doesn't get altered when change from Decode to Submission tab

**Comment by jacogr** [comment]
Since you went from decode -> submit - any chance to share the tx as well? (Just to ensure round-tripping works 100% in these cases as well)

As for the negatives, cannot recall, but will probably require "some" surgery.

**Comment by xlc** [comment]
On Acala parachain `0x0c0200aa66ae1c82621f3439a821974bfd285885ed2a513fc7ed660aa10dcf50161c7a000001ffffffffffffffffffffffffffffff`
