### ISSUE TITLE
[encointer] can't decode block if it contains a tx payed with a non-native asset.

### ISSUE THREAD

**Issue by clangenb** [polkadot-js/apps#7545]
See: https://github.com/encointer/encointer-parachain/issues/127

The reason here is that `polkadot-js/api` does not generate the signed extensions on the fly; the `AssetId` of the `OnChargeAssetTxPayment` is hardcoded to `Option<Number>`, while we have `Option<CommunityIdentifier>`.

On the client side, I solved this with the following code-block:

```
const api = await ApiPromise.create({
  ...options({
    types: configOverride.types !== null ? configOverride.types : {}
  }),
  signedExtensions: {
    ChargeAssetTxPayment: {
      extrinsic: {
        tip: 'Compact<Balance>',
        assetId: 'Option<CommunityIdentifier>'
      },
      payload: {}
    }
  },
  provider: provider
});
```

As far as I know, I can no longer set custom types in polkadot-js/apps. So how can I get this change there?

**Comment by clangenb** [comment]
Yes (taken from the linked issue above):

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.api.encointer.org#/explorer/query/0xfb56d3ad3451d25a213a90c14fffa06cfedd177389f1fa697bc2786de369cf8f

Thanks for tackling this!

**Comment by jacogr** [comment]
No firms plans to look at this. (There may be some work medium-term, most-probably not comprehensive, as time permits)

**Comment by pifragile** [comment]
I am trying to solve the extrinsic decoding issue by adjusting our [config](https://github.com/encointer/polkadot-js-apps/blob/7da84a012992cd07cff064988d2c08cf6c265fd3/packages/apps-config/src/api/spec/encointer-para.ts#L9) to the following:

```
const definitions: OverrideBundleDefinition = {
  types: [
    {
      // on all versions
      minmax: [0, undefined],
      types: {
      // ...all types
      }
    }
  ],
  signedExtensions: {
    ChargeAssetTxPayment: {
      extrinsic: {
        tip: 'Compact<BalanceType>',
        assetId: 'Option<CommunityIdentifier>'
      },
      payload: {}
    }
  }
};
```

But I still get the same errors (as in this [block](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.api.encointer.org#/explorer/query/1570076)):
```
Unable to retrieve the specified block details. createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [57, 119]/[57,119]
```

Any advice @jacogr?

**Comment by pifragile** [comment]
Thanks a lot, the pre-build step did the trick!

**Comment by pifragile** [comment]
@jacogr can i also hook this config to the [testnet](https://github.com/encointer/polkadot-js-apps/blob/7da84a012992cd07cff064988d2c08cf6c265fd3/packages/apps-config/src/endpoints/testing.ts#L161)?
