### ISSUE TITLE
add IPFS CID identifier on all the types of governance requests

### ISSUE THREAD

**Issue by gilles437** [polkadot-js/apps#7547]
**Problem**: In the current situation, there is very few contextual information regarding the different types of governance requests stored onchain. External forums like Polkassembly or Dotreasury provide some offline descriptions or chats functionalities, but these offchain contents could be modified at any moment because they are centralised. Therefore this compromises the authenticity of these informations.

Solution: Provide an IPFS functionality for every type of governance request (proposal, treasury, tip, bounty), by adding a CID field in every request submission window (proposal, treasury, tip, bounty).

This modification would involve:
1. A modification of the Democracy pallet with the addition of a CID field for every type of proposal.
2. A modification of the UI by
a.  adding the CID field in the submission windows

Example: 

![Screenshot 2022-05-06 at 12 24 48](https://user-images.githubusercontent.com/28502710/167199285-b5fadad3-41c1-4f6b-8788-440d00ad12d3.png)

b. Adding the icon of a file in the description of the proposal. On click, the file will be downloaded on the user's desktop.

Example:

  
![Screenshot 2022-05-06 at 12 39 15](https://user-images.githubusercontent.com/28502710/167199372-1afa79f4-bf68-4804-a651-477a5fe2a75e.png)

3. A modification of the documentation explaining the new added CID field for every type of proposal.

**Comment by jacogr** [comment]
Where is the Substrate PR for this? Good idea, but really would suggest not having it here until in Substrate - the apps UI will always follow what is in there (obviously with old/new fallback detection)

**Comment by gilles437** [comment]
I will add a separate PR for Substrate.

**Comment by lucasvo** [comment]
@gilles437 thanks for taking this idea further! I'm wondering if there is a structured info standard that should be used for this. If we standardized on a few fields could help with actually rendering this within the UI (e.g. we could use Markdown and render the file from IPFS inline).

I wonder where we would add this on the backend side, to the preimage or to the council motion calls and democracy proposals?

I think it would be good to also get feedback from other governance portals (opensquare, polkassembly etc.)

**Comment by gilles437** [comment]
I added a forum discussion on the topic:

https://forum.parity.io/t/adding-files-to-democracy-proposals/920
