### ISSUE TITLE
Why has Extrinsic -> Decode submission been removed?

### ISSUE THREAD

**Issue by brenzi** [polkadot-js/apps#7552]
I don't get the rationale behind
https://github.com/polkadot-js/apps/pull/7512

This was a very practical feature. How shall we submit encoded calls now if we want to sign them from the browser extension?

just run the last commit before that (454b6883997aebd4e82a24533823994951927435) ourselves?

**Comment by jacogr** [comment]
Decode fully fills in all details on the submission tab.

**Comment by brenzi** [comment]
very nice, actually. this way it is even possible to edit the entries if needed.
