### ISSUE TITLE
Nomination Pools - Pools tab doesn't show unless a stash exists

### ISSUE THREAD

**Issue by paradox-tt** [polkadot-js/apps#7556]
Hello,

I am experimenting with the use of Nomination Pools on WestEnd and I believe that there is a counter intuitive logic with the UI. 

In order to see the Pools tab as shown below I needed to create a Stash.  

![image](https://user-images.githubusercontent.com/79228812/167453315-6f7f5876-9bcf-4b2c-b080-23883c416e70.png)

Nomination Pools doesn't require bonded funds and operates using transferable funds.  I suggest allowing view of the Pools tab without the need for a Stash present.

**Comment by paradox-tt** [comment]
Confirmed.

**Comment by jacogr** [comment]
It was indeed an issue, messy copy-and-paste from `Bags` logic seems to have caused it. Thanks for reporting anyway, first report of this preceded this specific one by a bit.
