### ISSUE TITLE
The Democracy page reported an error

### ISSUE THREAD

**Issue by 99Kies** [polkadot-js/apps#7576]
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/45918704/168409881-4e70f1a5-19a2-4e08-be0e-78394bc18582.png">

**Comment by 99Kies** [comment]
This bug appeared on the `Democracy` page when I submitted an `external proposal` through parliament.

**Comment by 99Kies** [comment]
This bug will end when the proposal is put to the referendum.

**Comment by jacogr** [comment]
The apps UI needs the `utility` pallet for democracy. Will add a check to not show the page at all it when `utility.batch` is not available.
