### ISSUE TITLE
set_storage interface requires JSON key-value file

### ISSUE THREAD

**Issue by rphmeier** [polkadot-js/apps#758]
Ideally I would be able to edit it as a list in-UI if I wanted to.

**Comment by jacogr** [comment]
Related to the app-extrinsics, specifically `consensus.setStorage` (only used by admins to change state entries). We added the JSON upload of k/v pairs to aid in making it simpler (and before the days of being able to handle arrays and Tuples...)

**Comment by Stefie** [comment]
The solution I'm implementing in #794 could still work. I could even try to turn the <Editor /> into a UI component

**Comment by jacogr** [comment]
These should not be edited by hand. It is hex storage entries. What should happen is that the KeyValue component render a selectable storage key with a (based on type) value. Effectively we need an Array that displays the same type of entry components we have in the chain state queries.

allowing JSON editing here is asking for trouble. The JSON upload already assumes you know what you are doing - getting it wrong can brick the chain.

**Comment by jacogr** [comment]
Probably, after typing out the above... not quite "easy-as-pie" :) The UI here worries me a bit as wel since we have 2 parts -

- entering the key - which is the same work that happens in `app-storage`
- entering the value (based on key type)

And then over an above this we have the Array wrapping.

**Comment by Stefie** [comment]
Do you happen to have an example JSON file at hand? :

**Comment by jacogr** [comment]
The input that go there, would look something like this -

```json
{
      "0x2ec6e5652282d579398fb8fdfa531ef6": "0x0000000000000000",
      "0x4664fb5d4e16f894df23cadb3faaa9a6": "0x04000000",
      "0xfc2dc4b8bb0b9ca8f01a73a726f7c7f5": "0x00e1000000000000",
      "0xd437fe93b0bd0a5d67d30d85d010edc2": "0x40420f00",
      "0x3a617574683a00000000": "0x4bd3620064cda1f4cf405bf9ab565c9bad69446034c48884ffc5363a5286b145",
      "0x99e2aba8a2b7c8ccba2d740fb86adb0c": "0x00",
      "0x52b963fbdb3d6e1b03808fc20071f07f": '0x0027060000000000",
      "0xdfaac108e0d4bc78fc9419a7fcfa84dc": "0x104bd3620064cda1f4cf405bf9ab565c9bad69446034c48884ffc5363a5286b1453a92077b16fbb87972be7ebaf1b7e70f5b4fac9636c136936a28d0fb494d1ed4ca8feb6f870330cdaea24e49c2f850b66729340cab164aea86c0a782ddecf57adcb83e46917c3c0ca35b9a18a32ba6d3912b6d50ab2bd382341d2e4fd2e6946f",
      "0x2b89d3b6f46fc8a3aee48c9cb06d7670": '0x0010a5d4e80000000000000000000000",
      "0x934302c5ec4cb4f73a395e2184ab0aa6": '0x00e40b54020000000000000000000000",
      "0x3a6772616e6470613a617574683a03000000": "0xdcb83e46917c3c0ca35b9a18a32ba6d3912b6d50ab2bd382341d2e4fd2e6946f0100000000000000"
}
```

Simply the xxhash key value with the SCALE-encoded value. (Hence, no manual editing, those are generated, not manually entered)

**Comment by rphmeier** [comment]
I don't think it's much simpler to build a JSON document locally and then upload it to the browser. Odds are the value I'm editing is specified in the metadata anyway and I want the new value to conform to that type

**Comment by jacogr** [comment]
100% - the only simple way is to "select key" (like in the chain state app) and then enter the value for the key. 

(UI wise a bit of a nightmare to get it clean-looking, but the simplest fool-proof way to specify these without having some encoding magic somewhere)
