### ISSUE TITLE
Decode => Submission changed the extrinsic

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#7584]
On Karura `0x8d01043f0208680300030101001ede3700000000000000000000000001010000a138149b391f0000000000000000010100004f8c34e814020000000000000000010100002cf61a24a2290000000000000000010000f4448291634500000000000000008101`

Some fields are lost when switching from Decode to Submission page.

**Comment by jacogr** [comment]
Interesting - seems like an `Option` issue, but weirdly the last one does populate.
