### ISSUE TITLE
CuratedGrandpa::set_voters proposal doesn't allow editing the list properly

### ISSUE THREAD

**Issue by rphmeier** [polkadot-js/apps#759]
To reproduce:
  - checkout commit f1d3d98 of polkadot (https://github.com/paritytech/polkadot/pull/162)
  - run a local chain
  - UI: extrinsics -> sudo -> curatedGrandpa::set_voters
  - try to add multiple items and tweak the u64 parameters

The Rust signature is `fn set_voters(origin, voters: Vec<(T::SessionKey, u64)>)`

**Comment by jacogr** [comment]
Sheiße - something is borked with the Array + Tuple.

**Comment by jacogr** [comment]
<img width="538" alt="polkadot apps portal 2019-02-27 16-52-40" src="https://user-images.githubusercontent.com/1424473/53503337-27ecdb80-3ab0-11e9-810d-ccd0b3f701e9.png">
<img width="651" alt="polkadot apps portal 2019-02-27 16-52-13" src="https://user-images.githubusercontent.com/1424473/53503338-27ecdb80-3ab0-11e9-9d6e-4fdcc23a7f95.png">

**Comment by rphmeier** [comment]
nice, thanks
