### ISSUE TITLE
Buggy multisig approval dialog

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#7592]
We have encountered an issue on Acala yesterday that the Approve button on mulitsig dialog is disabled and can't find a way to have it enabled. No relevant error in console. Not able to reproduce it anymore.

Another issue is that when on final approval, I can enter call data and the dialog will decode it, but after few seconds, the decoded call data will disappear and replaced by the input box. Pasting the same call data won't work. Delete it will make the box red and enter call data will work again, except it will again be replaced after few more seconds.

**Comment by jacogr** [comment]
The first was an issue with the 0.115.1 deployment, 0.115.2 has a fix for it.

On the second, ensure your data matches your hash - however cannot replicate myself.
