### ISSUE TITLE
Where is the fast Track button?

### ISSUE THREAD

**Issue by 99Kies** [polkadot-js/apps#7599]
Experimental environment: 
local parachain - polkadot-v0.9.19

My `next external proposal` is `SuperMajorityAgainst ` rule, it should show the fast Track button, but I don't show it here.
![image](https://user-images.githubusercontent.com/45918704/168798074-58a4a521-2e15-4a2e-aecc-b45ab0592c3a.png)
![image](https://user-images.githubusercontent.com/45918704/168798436-379155d7-3a13-4b6f-b458-8e4d214d6476.png)

> Standalone chain do not have this problem.

**Comment by jacogr** [comment]
The difference between your chains in that the one has the `utility` pallet, the other doesn't. It uses batch transactions, so needs the utility pallet.
