### ISSUE TITLE
[Feature] Support displaying block date

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/apps#7602]
Most blockchain have the inherent `timestamp.set`. Even if it can't be fully reliable, I think using it to display the block date/time would be great.
We could use the space under the block number:
![image](https://user-images.githubusercontent.com/329248/168934840-5b984ec9-7e21-438d-a60f-d1b10d55e84b.png)

**Comment by jacogr** [comment]
It is displayed to the right of the timestamp.set extrinsic.

**Comment by jacogr** [comment]
As an aside, the space under the block number is meant to display the author, I think there is an issue on Moonbeam/Moonriver where it doesn't pull the special chain-specific logic through to display that. See e.g. Westend -

![image](https://user-images.githubusercontent.com/1424473/168972622-326fa13a-ae49-4410-bb33-8c831129f1e0.png)

**Comment by crystalin** [comment]
> It is displayed to the right of the timestamp.set extrinsic, last column, e.g. on Moonriver see the bottom-right column for `18/05/2022, 08:04:00` -
> 

Ho, I never saw it before :)
Thank you, closing this ticket

**Comment by jacogr** [comment]
It is relatively new, only space I could squash it in - certainly not perfect, but there.
