### ISSUE TITLE
The problem with SubWallet Extension

### ISSUE THREAD

**Issue by saltict** [polkadot-js/apps#7605]
Hello @jacogr !

I was shocked to realize that `subwallet-js` is blocked in `@polkadot/apps`.

After lookup reason, I found that because a mistake in my commit on SubWallet Extension repository. We need to pushlish packages build to NPM for other project so we changed package name from `@polkadot/extension-xxx` to `@subwallet/extension-xxx`. In this process copyright headers are being changed as unwanted result.

With all our sincerity we always respect what you and your team have done for the community and we're very sorry about this problem.

We haved rollbacked all header in the packages we reused or copied in this [commit](https://github.com/Koniverse/SubWallet-Extension/commit/093dc9efa57739898e1c96dd219d51c6711c55ca)

We hope you and your team are not bothered by this issue and SubWallet is back on Polkadot{.js} App soon.

Wish you all best and thanks for reading.

**Comment by jacogr** [comment]
Let me clarify -

I'm 100% over-the-moon when teams build on the extension. It is _exactly_ what it started out for, i.e. a scaffold that allows others to innovate. It is certainly very limited in functionality, so there is massive room for teams to build on and shoot out the lights. In the longer term is usage of the extension itself drops to close to 0 and the code re-use sky-rockets, it means it did what it set out to do and the ecosystem is stronger as a result of it - which is where we want to be.

I've had to deal with a massive number of teams (there are still a huge number of "knowns" out there), that take the work and pass it off as their own - and this is an issue that is prevalent everywhere, not only affecting polkadot-js, but also things like Substrate and, well, most OSS stuff out there in the wild. 

I understand attribution is always quite difficult but in OSS it is important to acknowledge where it comes from, for instance see [this](https://github.com/polkadot-js/wasm/blob/4c3537d869e79acf7710603369cd99fa09bf9de3/packages/wasm-util/src/fflate.ts#L1-L16) and [this](https://github.com/polkadot-js/ui/blob/700b04e2eceeeb89ed143412e4e40740c3cfb96e/packages/ui-shared/src/icons/polkadot.ts#L1-L8) where parts of polkadot-js build on the code that others have produced. Especially in small and growing communities like ours. So there are certainly always very valid reasons as to "why" it is just the "how".

I'll look into the above and revert the block.

**Comment by jacogr** [comment]
The above commit was probably a bit heavy-handed, see [here](https://github.com/Koniverse/SubWallet-Extension/blob/b840a0cd5a1f4f7f352e07a37b7379af37c52c3e/packages/extension-base/src/background/KoniTypes.ts#L1) - that certainly is your code 100%. Like I mentioned above, it is really not easy making sure both the original authors and the people doing the heavy lifting from that point on are all treated equally.

The above seems fine, will make a PR.

**Comment by saltict** [comment]
Thank you very much.
