### ISSUE TITLE
The era progress information for Westend seems to be wrong.

### ISSUE THREAD

**Issue by IkerAlus** [polkadot-js/apps#7607]
The era progress information for Westend network under Network -> Staking tab is consistently over 100%.
![Screenshot 2022-05-18 at 10 51 04](https://user-images.githubusercontent.com/34474035/168998951-39ffcf9e-4c00-4ab0-a92a-434cfa80fb02.png)

The same behaviour is shown connecting from any node but it looks like it only happens for Westend.

**Comment by jacogr** [comment]
Yes, there has been issues where it didn't change due to validator selection not working. The teams are looking at the chain itself to figure out what the issue is.

**Comment by jacogr** [comment]
Both staking.eactiveEra and staking.currentEra has moved again, it is now unstuck from the `5,130` where it was when this was logged (despite epoch changes), as of now it incremented to `5,131` and it seems moving again. So whatever was done, I'm guessing [this sudo call](https://westend.subscan.io/extrinsic/10897472-2) worked and got it unstuck.

**Comment by kianenigma** [comment]
This situation can happen IFF the chain moves to an emergency condition where the election/staking have failed to trigger a new era. In this case, new sessions are created, but no new era is created, thus no new validator set is also chosen and we stick with the old set. 

This is why the duration of the era is prolonged. 

To fix this, these calls/info can be used:

https://github.com/paritytech/substrate/blob/6386eea9ecf33bd43e6ea319cfae27e18d32fdf3/frame/election-provider-multi-phase/src/lib.rs#L120
https://github.com/paritytech/substrate/blob/6386eea9ecf33bd43e6ea319cfae27e18d32fdf3/frame/election-provider-multi-phase/src/lib.rs#L935
https://github.com/paritytech/substrate/blob/6386eea9ecf33bd43e6ea319cfae27e18d32fdf3/frame/election-provider-multi-phase/src/lib.rs#L1039
