### ISSUE TITLE
Support options to modify chainType

### ISSUE THREAD

**Issue by dnjscksdn98** [polkadot-js/apps#7613]
I'm currently working on building a blockchain based on Substrate and using polkadot.js/app to connect to my running node.
And it's a EVM compatible blockchain so I'm also referencing Moonbeam related codes for develop usage.

But I found out that when I connect to Moonbeam with polkadot.js/app, at the settings/metadata page, the "chain type" was set to "ethereum". So I searched this repository to find any options that I can change my nodes chain type from "substrate" to "ethereum".

And I found out that only the pre-defined chain specs are defined to "ethereum".
https://github.com/polkadot-js/apps/blob/5e7f20c79f38d275b6e1cf071990c03cc6ea68a4/packages/apps-config/src/settings/ethereumChains.ts#L6
```
export const ethereumChains = [
  'moonbase',
  'moonbeam',
  'moonriver',
  'moonshadow'
];
````

https://github.com/polkadot-js/apps/blob/fc7434cbb4653e0042b25ac27da464a98b3bf131/packages/react-api/src/Api.tsx#L148
```
const isEthereum = ethereumChains.includes(api.runtimeVersion.specName.toString());
```

So I suggest that if there could be any support for "chain type" selection. Similarly to tokenDecimals or tokenSymbols, not for only pre-defined chains.

**Comment by jacogr** [comment]
This really is very specific to a small number of chains - having this configurable in the UI will lead to more support queries since people will start messing around. I would rather suggest you make a PR for your specnames.
