### ISSUE TITLE
RPC call uses lowercase parameter name

### ISSUE THREAD

**Issue by gregdhill** [polkadot-js/apps#7645]
See the example in https://github.com/interlay/interbtc/issues/612

We have an RPC call which uses a `CurrencyId` argument, note the capitalized "Token" enum variant (see [here](https://github.com/interlay/interbtc/blob/95f2ea983de086d7cc53cb6469efae681831ccad/primitives/src/lib.rs#L493)). I can only assume `polkadot-js` uses the lowercase of this string which results in the "Invalid params" error as the correct capitalization works as expected. We do not have any issues with extrinsics or reading the chain state.

**Comment by jacogr** [comment]
As per the Substrate de-facto standard, all properties over RPC are camel-cased. As an example from Substrate (see the serde macro) -

```rust
/// Health struct returned by the RPC
#[derive(Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Health {
	/// Number of connected peers
	pub peers: usize,
	/// Is the node syncing
	pub is_syncing: bool,
	/// Should this node have any peers
	///
	/// Might be false for local chains or when running without discovery.
	pub should_have_peers: bool,
}
```

**Comment by gregdhill** [comment]
Thanks for the detailed answer @jacogr, much appreciated!
