### ISSUE TITLE
Governance front-end issues

### ISSUE THREAD

**Issue by ghzlatarev** [polkadot-js/apps#7657]
Hi I found a couple of small issues with the Governance tab:

* In my setup there's a Technical Committee with 1 member who fast-tracks an external proposal. The member uses the `fast-track` button in the Governance tab with `Submit Aye vote with proposal`. Then even though the proposal is successfully fast-tracked we get a `technicalCommittee.ProposalMissing` warning, which is confusing. As if the member tried to vote twice. Only happens with the button and with `Submit Aye vote with proposal`
* Second thing is that when you use the `fast-track` button you can't seem to be able to modify the `threshold`. It's just decided for you dependent on the amount of people in the `pallet_collective` instance, and since there's a configurable mininum threshold in the Runtime, the front-end value might not always be appropriate.

**Comment by jacogr** [comment]
1. Can certainly disable the vote for 1 member only.
2. It is configurable, see https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/params/proposalThresholds.ts (that would need to mirror what is on the runtime)

**Comment by ghzlatarev** [comment]
Ok I see, for 2 can I make it `>1/2` ? The configuration in my runtime is simple majority.
