### ISSUE TITLE
Detect (initial) default settings via URL

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#766]
- *.polkadot.io - Polkadot theme, Alexander default
- substrate-ui.parity.io - Substrate theme, Dried Danta default
- substrate-ui-light.parity.io - Substrate theme, DD default, light mode
- polkadot.js.org - keep as-is? (or Substrate theme, Alexander default?)

**Comment by gabreal** [comment]
https://github.com/polkadot-js/apps/pull/767 this is the ci file for the substrate-ui and substrate-ui-light host rules for kubernetes. They are already in place and also the domain name aliases are set up accordingly.
