### ISSUE TITLE
Innacurate bond information during treasury proposal submission

### ISSUE THREAD

**Issue by valentunn** [polkadot-js/apps#7660]
While submitting the most recent proposal on behalf of Nova Wallet, which was for 4400 KSM, we only had 3.3 KSM locked as a deposit.
However, Polkadot.JS shows that there is a 5% bond, which does not comply with what we experienced during proposal submission.
I would also add that we personally discovered this after buying extra KSMs, which were not needed in the end, so this incorrect info might cause some issues for others too
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/70131744/171029347-efbef0f7-d3ad-499d-89df-fb298da1f151.png">

**Comment by jacogr** [comment]
It doesn't (yet) take the newly added `proposalBondMaximum` into account. It is logged, see https://github.com/polkadot-js/apps/issues/7336 so the logic still need to be adjusted to `min(proposalBondMaximum, 0.05 * amount)`

It is indeed set at 3.3KSM for Kusama currently -

![image](https://user-images.githubusercontent.com/1424473/171380328-7d95623f-29c6-4957-a815-f1b6f2b92db5.png)
