### ISSUE TITLE
Unavailable chain endpoints for Polkadex

### ISSUE THREAD

**Issue by atharen** [polkadot-js/apps#7669]
I am stuck on `https://polkadot.js.org/apps/?rpc=wss://mainnet.polkadex.trade#/addresses` with the _Initialising Connection_ loading animation.

Specifically `API-WS: disconnected from wss://mainnet.polkadex.trade: 1006:: Abnormal Closure`

I attached console logs for running it on both [Edge](https://github.com/polkadot-js/apps/files/8812639/edge-polkadot.js.org-1654071623001.log) and [Chromium](https://github.com/polkadot-js/apps/files/8812587/chromium-polkadot.js.org-1654072014206.log)

It might be related to #7551, but it **might be an issue to be brought up with the Polkadex team** (_not sure where ideally to post_), as I checked with [Elixxir](https://explorer.xx.network/#/addresses) and the [Parity's Polkadot](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/addresses), and they are both relatively instant.

**Comment by jacogr** [comment]
The issue you linked is the local health checks that run twice a day - it comments to all endpoints and checks them, logging an issue if they are unavailable. I then remove them from the list if they appear 3 times consecutively.

RPCs are managed by the teams themselves, so their operations could be up-and-down. (The only real control I have here is to disable it, based on the auto-checks, if the problems persist)

**Comment by atharen** [comment]
Yeah, thought it might end up being something like that. Checked on their Discord, and the [team themselves](https://discord.com/channels/859180272335323166/892806819074961428/976175844013785118) recommended using another node.

_Closing this as effectively resolved..._

**Comment by jacogr** [comment]
Will keep an eye on it as well.
