### ISSUE TITLE
Block details page shows extrinsic hash but not extrinsic data

### ISSUE THREAD

**Issue by gilescope** [polkadot-js/apps#7694]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/explorer/query/10000000

When I expand the timestamp extrinsic there's a copy button for the extrinsic's hash.
Would be really cool if there was a copy button for the extrinsic's data (so then I can dump it in the decode extrinsic's page)

**Comment by jacogr** [comment]
Interesting that you linked a historic block, which is exactly the reason why the info is not there - extrinsics needs to be decoded using their specific at-the-time metadata, this is the specific types as well as the specific indexes. As soon as the runtime changes, there is 0 guarantee that the extrinsic is decodable using the current metadata, i.e. as used in the extrinsics pages. So it would be a toin-toss if this works or not.

(This is the exact same reason the specVersion is inside the signed payload, thus invalidating any transaction that have been created with older versions as soon as an upgrade takes place)

**Comment by gilescope** [comment]
Agreed you do have to use the right metadata to decode. Ideally chains
should indicate the block numbers when the metadata changes. But looking on
my phone at the latest block I see the same that there’s the extrinsic hash
but not the extrinsic data displayed.

Spec version is in the block header and defines the metadata version? Nice
- will find and make use of that.

**Comment by jacogr** [comment]
We are missing each other - we cannot decode and then submit old transactions. It can only be done for the current runtime.

**Comment by jacogr** [comment]
Closing based on #7720 0
