### ISSUE TITLE
Can't Register Parachain ID on Rococo

### ISSUE THREAD

**Issue by DappGuy** [polkadot-js/apps#7729]
it wont let us register a parachain id on rococo the nextFreeId is "3,026" and its already taken from Bajun Network

"system.ExtrinsicFailed registrar.AlreadyRegistered" when tx is submitted

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/parachains/parathreads

**Comment by jacogr** [comment]
The id is indeed taken -

![image](https://user-images.githubusercontent.com/1424473/173217193-2889b1af-e23e-49e7-9c55-e141bad8ea73.png)

This means you would need sudo intervention to fix the slots. See here for a previous occurence of the same - https://substrate.stackexchange.com/questions/1418/provided-next-available-para-id-is-already-registered

The best place to report this would be on https://github.com/paritytech/subport/issues

**Comment by DappGuy** [comment]
Thank you but we cant open a issue on subport other then a Rococo Slot Request which we need the para id for. i will try stack exchange

**Comment by jacogr** [comment]
Seems to be all ok now -

![image](https://user-images.githubusercontent.com/1424473/173230939-3c46299a-46c0-4a79-9944-d513f42afcc4.png)

**Comment by DappGuy** [comment]
thanks man
