### ISSUE TITLE
Settings App - Custom type definition JSON upload Feedback 

### ISSUE THREAD

**Issue by yjkimjunior** [polkadot-js/apps#776]
Under `https://polkadot.js.org/apps/#/settings/developer`, upon uploading a custom type definition json, there is no Status feedback to let you know whether it was successful or not. Although it does log it in the console.

**Comment by jacogr** [comment]
It does show the types in the upload box (as determined), but yes, more feedback would be good. (At least a status message that pops up and says "ok" or "it failed")
