### ISSUE TITLE
network not listed anymore

### ISSUE THREAD

**Issue by 2075** [polkadot-js/apps#7763]
- [x] Other

hey there!

we just learned that zero network is not listed anymore under testnets, is there a reason for that?
thanks for a heads up!

* **What is the current behavior and expected behavior?**

This area does not list our network anymore:

<img width="311" alt="image" src="https://user-images.githubusercontent.com/1140449/174603761-410d0882-b370-4ab5-921f-c09e493447fc.png">

💡 here it is noted as disabled: https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/endpoints/testing.ts
but the endpoint is available: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Falphaville.zero.io#/explorer

**Comment by jacogr** [comment]
Check the comments here - it was unavailable for 4 consecutive attempts to reach it - https://github.com/polkadot-js/apps/issues/7753

(checks run every 12 hours, so that is 2 days)

If it recovered (most probably due to a restart or manual intervention), feel free to raise a PR to re-enable.

**Comment by 2075** [comment]
yes, read it, our monitoring did not show any issues, but will do a pr also adding more nodes by other operators. maybe a notification would help, as the network node operators would be known.

**Comment by jacogr** [comment]
PRs welcome to add that functionality. See this test that run to check endpoints - https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/ci/chainEndpoints.spec.ts

This is not a monitoring solution, it is assumed that RPC providers do have monitoring in-place and will act on downtime. 

This is a check to pick up endpoints that have been abandoned - after 4+ issues logged (2+ days), it gets removed before I have to deal with a flood of support issues out of my control. There are obviously hiccups that this does pick up, i.e. some endpoints may throw up an issue - however after 1 it doesn't get removed, neither after 2, issues happen, only after a continuous stream of them. (A single ok check does rest things on my side, i.e. down, down, up and the next check "down" means I count it as a single)

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/apps/pull/7769
