### ISSUE TITLE
Connect button for multiple wallet extensions

### ISSUE THREAD

**Issue by SaltyCucumber** [polkadot-js/apps#7779]
Currently if user has multiple dotsama wallet extensions installed, there will be multiple popups appearing at the same time
asking for permission to grant access to polkadot.js/apps. Meaning the dapp connects to all available extensions at the same time automatically without user's action.
A suggestion to add a "connect" button, that will show a popup with supported wallets and possibility to not only connect, but to download as well if user doesn't have one.
Here is an example of such button:
https://connect.subwallet.app/#/welcome
![Screenshot 2022-06-21 at 16 03 49](https://user-images.githubusercontent.com/748932/174805946-eebcb03a-5de8-4be1-83e3-d4b8d459c52a.png)

Do we want such functionality and if yes, then should this be a separate reusable library complete with UI or we just use the
basics of @subwallet/wallet-connect, and create our own component for the UI part.

Currently there are multiple variants already made, there is one by @rossbulat in https://paritytech.github.io/polkadot-staking-dashboard/#/overview @talisman-connect/wallets is used there, we can use this instead of subwallet.
There is one by RMRK team https://github.com/rmrk-team/substra-hooks/tree/master/packages/dotsama-wallet-react it requires some additional libs though.

**Comment by shawntabrizi** [comment]
@jacogr can @SaltyCucumber work on building a custom solution for Polkadot JS Apps?

**Comment by SaltyCucumber** [comment]
Taking into account what was discussed here, this is what I'm planning to do (subject to change if something unexpected pops up in the process):
- use extensions/index.ts as the source of truth on what we support, from this source the list will be formed, this will allow others to add extensions in future, for now I'll add the polkadot extension + talisman.
- ditch all the libs, instead just use our own implementation, from what I've seen most solutions are custom made anyway, only minor methods are taken from libs
- create a dropdown when connect is clicked (good for web and mobile), less space taken, not a "popup that will trigger another popup", something that Jaco mentioned doesn't want to be happening, hence the dropdown will fit here like a glove.

**Comment by SaltyCucumber** [comment]
@jacogr I was looking for a method to just check if dapp is authorized in extension, but can't seem to find one.
the `pub(authorize.tab)` triggered by `.enable` immediately calls for a popup which is what I don't want to happen,
so do you know a method to get a simple true/false response to a "is this dapp authorized" question or a new `pub(authorize.isAuthorized)` should be created for this functionality?
That would be route A.

Route B is we leave everything as is and on polkadot-js/apps I turn off automatic connection to all available extensions and
instead go through a list of supported extensions and check localstorage for previously enabled extensions (list of names)
if any are found - automatically connect to them.
This approach will prevent multiple popups + support automatic connection for previously used extensions + require user's action to connect to "new" extensions. The only down side versus route A would be that if user manually removes authorization for the dapp from all extensions, then multi-popups will appear in this case. Route A would be able to prevent this, but probably requires more changes across many packages.

What do you think?
