### ISSUE TITLE
Support for flatpak installation

### ISSUE THREAD

**Issue by flipchan** [polkadot-js/apps#7781]
As a feature request it would be cool if polkadot-js electrum app. Flatpak is an easy way to run sandboxed apps for the desktop. It runs all applications in a separate namespace for added security. 

There are several other flatpak apps that are electrum based. It also makes it easy to update and install on multiple linux based desktops.

Links:
https://flathub.org
https://www.flatpak.org/
https://docs.flatpak.org/en/latest/
https://docs.flatpak.org/en/latest/first-build.html

**Comment by jacogr** [comment]
There are already AppImage for Linux that is packaged on each release - https://github.com/polkadot-js/apps/releases/tag/v0.116.1. 

With that in mind, it is unlikely that we will do the same in yet another format for a platform where we already have support.

**Comment by flipchan** [comment]
would it be possible to add an extra yaml file to support this? seems to be pretty straight forward then users can just `flatpak install github.com/polkadot-js`(with similar context)

**Comment by jacogr** [comment]
Closing. Sadly, I cannot add another format for an already-supported platform (as explained above) - especially one where I cannot test it.
