### ISSUE TITLE
Staking Targets page shows incorrect information

### ISSUE THREAD

**Issue by DrW3RK** [polkadot-js/apps#7794]
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/86818441/175540796-f213859b-e437-4860-adeb-93f96b9e1088.png">

There seems to be a UI issue when displaying returns and the stake of the lowest staked validator

**Comment by laboon** [comment]
Note that this works on the IPFS version of the page.

**Comment by michalisFr** [comment]
It seems like "Other stake" is fetched properly.

Also, in both versions some validators are missing their own stake.

**Comment by laboon** [comment]
All of the "weird" validators showing strange stake / returns are ones that are active NEXT session, but NOT active THIS session.
