### ISSUE TITLE
Unable to query balance/system storage for an arbitrary account in the interface

### ISSUE THREAD

**Issue by IkerAlus** [polkadot-js/apps#7796]
In Polkadot.js interface, if I have no account added for the specific chain, the interface does not allow me to query the balance of any account by `AccountId32`. It disallows the field with the message "No accounts are available for selection." See the image below.

<img width="1416" alt="Screenshot 2022-06-24 at 17 56 43" src="https://user-images.githubusercontent.com/34474035/175574067-5fb1d31e-a492-407c-87c8-1798656a189a.png">

However, if I have an account added in the chain, the interface allows me to select the added account and also input any `AccountId32` string.

  - [ x] Bug report
  - [ ] Feature request
  - [ ] Support request (please bear the comments above in mind)
  - [ ] Other

* **What is the current behavior and expected behavior?**

I expect that regardless of having an account added, I can query any account in the chain by providing the specific `AccountId32` string.

**Comment by jacogr** [comment]
Just Paste the address you want in there and it will be accepted.

**Comment by IkerAlus** [comment]
I understand the rationale behind disabling it completely. I just found it confusing that the `AccountId32` string input is allowed (for any account) when you add a (unrelated) account.

Feel free to close this issue.
