### ISSUE TITLE
Question: is there any way to run ui-keyring in javascript console?

### ISSUE THREAD

**Issue by muddlebee** [polkadot-js/apps#7804]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request (please bear the comments above in mind)
  - [ ] Other

* **What is the current behavior and expected behavior?**

Trying to run the utility from https://polkadot.js.org/docs/ui-keyring in javascript console, not able to do so.
Looks like currently only the @api library is supported?

**Comment by jacogr** [comment]
It has limited support - basically it is only available when connected to a dev node. (On live chains you don’t want random code to be able to possibly access your keys)

**Comment by muddlebee** [comment]
Hmm makes sense...
I was thinking of submitting an idea for an independent JS console, where we can custom run and save all our workflows and test polkadot js stuff.. 

here, https://github.com/w3f/Grants-Program. 

Do you think it will be a good project for someone who wants to implement it?

**Comment by muddlebee** [comment]
for substrate we have a nice online playground https://paritytech.github.io/substrate-playground/docs/

**Comment by jacogr** [comment]
Some other API interfaces that I'm aware of (mostly from the "prior art" link on the first) -

https://github.com/btwiuse/subshell
https://github.com/halva-suite/halva
https://github.com/cennznet/cli
https://github.com/compound-finance/gateway/tree/develop/chains
https://github.com/cryptolab-network/polkadot-api-cli

**Comment by muddlebee** [comment]
great stuff. thanks appreciate it 👍

**Comment by jacogr** [comment]
Closing, sadly won't be actioned in non-dev (security concerns), but there are other options.
