### ISSUE TITLE
custom rpc does not show

### ISSUE THREAD

**Issue by tdelabro** [polkadot-js/apps#7844]
I'm running Polkadotjs destop app v0.116.1, on macos.

I added new rpc calls to my pallet, and runtime.
They show if I list the rpcs.
<img width="1687" alt="Screenshot 2022-07-08 at 01 35 27" src="https://user-images.githubusercontent.com/34384633/177888728-bf9fb07c-421f-42da-a0da-2b411c4a8d7e.png">
`supersig_getAccountSupersig` that's mine

But I would like to have it appear on this menu:

<img width="481" alt="Screenshot 2022-07-08 at 01 35 33" src="https://user-images.githubusercontent.com/34384633/177888763-1613d608-6e20-409b-b41d-6043dccd7710.png">

Is there a way to do that ?

**Comment by jacogr** [comment]
https://substrate.stackexchange.com/questions/2210/custom-rpcs-not-decorated

**Comment by jacogr** [comment]
Closing, answered.
