### ISSUE TITLE
Help : Unable to get last @apps-config version in npmjs

### ISSUE THREAD

**Issue by killbond007** [polkadot-js/apps#7859]
It is possible to publish the last @apps-config version in npmjs ?
 It will be helpful we can use logo/name in this package.

**Comment by jacogr** [comment]
It only gets published to npm now on stable releases - we will cut a version today.

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/apps/pull/7860

**Comment by jacogr** [comment]
https://www.npmjs.com/package/@polkadot/apps-config/v/0.117.1
