### ISSUE TITLE
Polkadot-js-apps 0.117.2 does not run

### ISSUE THREAD

**Issue by pablonardone** [polkadot-js/apps#7873]
The latest release of "Polkadot-JS-Apps-0.117.2.exe" does not run on Windows. At launch it shows the next dialog box:
 

![polkadot_error](https://user-images.githubusercontent.com/27935551/178890082-95636569-0cab-4b5e-85b3-503783384b9e.png)

The platform I am using is Windows 10 Pro 64 bits

**Comment by jacogr** [comment]
Fixed in https://github.com/polkadot-js/apps/releases/tag/v0.117.3

Since 0.117.2 is not running, it won't auto-update, so you would need to download it again from the above release. (It tested that process on my side and indeed 0.117.3 does launch and operate correctly now)
