### ISSUE TITLE
Developer Tab -> RPC calls : "Response is too big: Exceeded max limit 15728640"

### ISSUE THREAD

**Issue by muddlebee** [polkadot-js/apps#7877]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

At "Developer" tab for RPC calls, getting the below error after the call is made

![Screenshot 2022-07-14 at 7 33 41 PM](https://user-images.githubusercontent.com/8139783/179001678-bc0d25eb-a32f-4773-bde0-5e0d003c37df.png)

**Comment by jacogr** [comment]
That is from Substrate RPC. There is a limit on the Node RPC for sizes.

**Comment by muddlebee** [comment]
opened an issue here https://github.com/paritytech/substrate/issues/11842

**Comment by jacogr** [comment]
Closing in favor of the linked Substrate issues (where the message originates).
