### ISSUE TITLE
Make block query accepts block number

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#789]
Currently in order to get the details of the next block of a particular block (investigate why a node stop syncing at particular block), I need to get block hash by number using RPC calls in toolbox section, and then query the block hash in the explorer section.

It will be good if block query tab accepts block number and perform the get block hash by number for me.

**Comment by jacogr** [comment]
Allow the "hash query" to take a blocknumber as well. When number detected, do lookup for hash, display.
