### ISSUE TITLE
Can't access 'number' property in app-js editor

### ISSUE THREAD

**Issue by Stefie** [polkadot-js/apps#790]
It seems like using `number` as an object key is somehow blocked/ filtered out in codeflask. Maybe that's general behaviour.

Run this code for demo:
https://polkadot.js.org/apps/#/js/share/rwLYY29uc3QgbGF0ZXN0ID0gYXdhaXQgYXBpLnJwYy5jaGFpbi5nZXRGaW5hbGlzZWRIZWFkKCk7Cgk3EGJsb2NrARMEZXJmPAAJIAAoCWMQKTsKCgoBPSBvbGUubG9nKCcdRAgnLCAdDiwpCgovLyBCcm9rZW5iMwAULm51bWJlOjoADRUJQRh3b3JraW5nZkIANGV4dHJpbnNpY3NSb290NoQAAC42HQAEKQo=

**Comment by jacogr** [comment]
This works -

```js
console.log('blockHeader.number', blockHeader.blockNumber)
```

Basically, internally the object has `blockNumber`, while the JSON has `number` (this is displayed in the serialization). In the API can make an alias to return either.

**Comment by Stefie** [comment]
Nice, thanks for the quick fix!
