### ISSUE TITLE
Are apps-config beta packages no longer available on NPM?

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/apps#7937]
I did notice on NPM the most recent BETA version for `@polkadot/apps-config` is `0.116.2-24`. I was just wondering if that is intended. I see the most recent beta version via the repo is `0.118.2.32-x`. Just wanted to bring this up to see if it is an issue or intended. 

Running `npm view @polkadot/apps-config versions` also shows those beta versions are not available in the registry.

Please feel free to close if this is extra noise.

**Comment by jacogr** [comment]
Not noise, a valid question. The betas are now “publish on demand” on all repos. Stable releases go out as normal. (It should be ok with a weekly publish, not running far behind - although this week I skipped a release on apps since there was not much action)

**Comment by TarikGul** [comment]
> Not noise, a valid question. The betas are now “publish on demand” on all repos. Stable releases go out as normal. (It should be ok with a weekly publish, not running far behind - although this week I skipped a release on apps since there was not much action)

Ahh okay that makes perfect sense, thanks for the explanation. 

I found a reasonable solution for our users to still have the advantages of apps-config and their types without having to have apps-config intrinsic to our repo (Therefore avoiding any dep issues). It's basically just a simple helper package that will generate a JSON typesBundle file for specific chains or exchanges that they can then inject into our apps via an env-path. So I was contemplating whether or not we should have the latest beta or stable when generating those files. But using the most recent stable totally makes sense in this case. Really, thanks again 🙏 !

**Comment by TarikGul** [comment]
Will close since this is resolved!
