### ISSUE TITLE
Adding proxy on Moonbeam generates error

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/apps#7951]
Using the proxy overview (add proxy from account page), when adding a Ethereum address, it instantly crash with:
![image](https://user-images.githubusercontent.com/329248/182225146-c5f68c7a-ab0c-488d-bac2-f670de101b58.png)

**Comment by jacogr** [comment]
Cannot quite replicate using "Add proxy" from the 3 vertical dots.

**Comment by crystalin** [comment]
Quite easy to reproduce on my side
https://recordit.co/yoJiMHvxPn.gif

**Comment by jacogr** [comment]
So, you are pasting an address. That won't work, it needs to be an account. (There is certainly an issue here - something just doesn't handle that condition where an unknown account is passed. Will put in a fix, to just handle the case of not-an-account with an appropriate error)
