### ISSUE TITLE
Rpc types no longer recognised

### ISSUE THREAD

**Issue by gregdhill** [polkadot-js/apps#7963]
**I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

**What is the current behavior and expected behavior?**

Console shows "Not decorating unknown runtime apis" for all custom RPCs, but definitions are imported.

See: https://github.com/interlay/interbtc-types/blob/master/definitions.json

**What is the motivation for changing the behavior?**

It should be easier for end-users to interact with the Interlay / Kintsugi RPCs.

**Please tell us about your environment:**

  - Version: v0.119.2-19-x
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by gregdhill** [comment]
See also: https://github.com/interlay/interbtc/issues/621

**Comment by jacogr** [comment]
Runtime API !== RPC calls.

Runtime APIs are those exposed for using in `state_call` and exposed on `api.call.*`. RPCs are those decorated on `api.rpc.*`, e.g. `api.rpc.btcApi` which is decorated (at least on the interlay parachain on Polkadot)

**Comment by gregdhill** [comment]
Thanks @jacogr, is there a guide for migrating these type definitions? Is this the reason `polkadot-js/apps` can no longer recognize the input types for RPC calls?

**Comment by jacogr** [comment]
Which RPC input types is wrong? I commented on the linked issue - the UI displays the type, as linked, as defined in the definitions.

**Comment by gregdhill** [comment]
Take for example this call on [Kintsugi](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fapi-kusama.interlay.io%2Fparachain#/rpc):
![image](https://user-images.githubusercontent.com/12613821/183108383-29253c49-50c4-45cf-8bcb-377ed1f5721a.png)

**Comment by jacogr** [comment]
Ok, with that example I can have a look.

**Comment by jacogr** [comment]
This is the issue on that one - https://github.com/interlay/interbtc-types/blob/bb448280cfba1ad585eb78880a94a5c0840a195b/definitions.json#L4-L6 -

```js
{
    "types": [
        {
            "minmax": [
                0,
                100
            ],
```

The specVersion on the chain is at 1017000 - which is higher than the max of 100, so it is never applied. (You can use max of `null` or `undefined` for no end)
