### ISSUE TITLE
-32602: Unknown SS58 address format

### ISSUE THREAD

**Issue by 99Kies** [polkadot-js/apps#7966]
I ran into this problem while testing a new parachain.

```
balances.transferKeepAlive
-32602: Unknown SS58 address format `129`. ` `To support this address format, you need to call `set_default_ss58_version` at node start up.
```

![image](https://user-images.githubusercontent.com/45918704/183276955-03534b39-1c23-4b03-992e-0e450a52ca57.png)

**Comment by jacogr** [comment]
Duplicate on SE.

**Comment by 99Kies** [comment]
@jacogr Sorry, what does SE mean?

**Comment by 99Kies** [comment]
I solved the problem because 129 was not registered.
https://github.com/paritytech/ss58-registry/blob/main/ss58-registry.json
