### ISSUE TITLE
Unknown SS58 address format that is already in registry

### ISSUE THREAD

**Issue by arrudagates** [polkadot-js/apps#7994]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
Getting `Unknown SS58 address format` error for prefix 7031, which has been in the registry for some time now: https://github.com/paritytech/ss58-registry/blob/main/ss58-registry.json#L986

* **What is the motivation for changing the behavior?**
The bug should be fixed, otherwise the prefix is unusable from polkadot.js apps

* **Please tell us about your environment:**
Same issue occurs in current deployment and local run of the master branch

  - Version: Latest deployed and latest master
  - Environment: Deployed and local

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Error message?

**Comment by arrudagates** [comment]
> Error message?
> 
> The apps UI doesn’t throw these errors, nor check against the registry. Your error lies elsewhere, non UI.

This is what I get:
```
-32602: Unknown SS58 address format `7013`. ` `To support this address format, you need to call `set_default_ss58_version` at node start up.
```
So you're saying this is not actually in the UI? I see the error mentions I need to call `set_default_ss58_version` but I'm not sure where/how.

**Comment by jacogr** [comment]
That error is from the RPC node, not the UI.

**Comment by arrudagates** [comment]
> That error is from the RPC node, not the UI nor anywhere in the JS stack.
> 
> Check you runtime config and packages there and that it pulls the latest Rust packages for the ss58 management.

I know this is definitely the wrong repo for this issue now that you informed me that it's not related to the p.js apps ui, but do you have any more info on what Rust packages I should be looking for? I have looked through everything and can't find any posible causes for the issue.

**Comment by jacogr** [comment]
Substrate itself pulls in the ss58 registry.

**Comment by arrudagates** [comment]
I see, substrate (master and latest polkadot-vxxx) is stuck on a very old version of ss58-registry, I had to add a patch in my manifest and `cargo update`
