### ISSUE TITLE
Support multiple queries in a single withCall

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#800]
This has 2 parts to it, the apps `ui-app` part and the API part (the latter should be done first and logged seperately from this, this is more the meta issue)

Apps -

We want to be able to make calls to retrieve multiple values in one, for instance if we currently want to query the balances for `Alice` and `Bob`, we would currently do

```js
withCalls(
  ['query.balances.freeBalance', Alice],
  ['query.balances.freeBalance', Bob]
)
```

At the very least this is problematic since we cannot really pull in multiple params and adjust the number of queries based on the input. Additionally it just explodes code-wise. So we want to be able to do stuff (syntax needs tweaking, example only)

```js
withCalls(
  ['query.balances.freeBalance', Alice, Bob, Dave, ...]
)
```

The second part that touches the API is the optimisation of the calls. 

The `state_storage` subs can support multiple keys per subscription. Currently we are only doing a single subscription for each query even when we know from the use side that we need to do multiples in a row. Doing multiples in one-go can reduce and optimise the load/number of subs greatly on both sides. 

Even if at first we only implement this via the same type, maybe even `api.query.balances.freeBalance.multi(Alice, Bob, Dave, ...)` it will drop a lot of the use and can be used to make thing more optimal, for instances in the case of `api.derive.*`

cc @siman

**Comment by siman** [comment]
This is a really needed enhancement! For example, this will make possible loading a list of balances by account ids and then sort that list of accounts by their balance. Right now I don't even know how to do this with a current approach when I need to get balance in a sub-component (a Row) but how parent component (a List) can sort its rows? Only a Row knows its balance.

**Comment by amaurymartiny** [comment]
I'm only commenting on the 2nd part. The `.multi` sounds good, it's clear on what it does (principle of least surprise), so I'm okay with this addition.

But as you said, it's only on one storage key, so I won't help in most derive.* where the storage keys are different, e.g. I can't do a multi-subscription to:
```
api.query.balances.freeBalance(Alice)
api.query.system.accountNonce(Alice)
```
both in one subscription.

I'd see something like:
```javascript
api.query.multi(
  api.query.balances.freeBalance(Alice),
  api.query.system.accountNonce(Alice)
).then/subscribe()
```

The freeBalance example above would be slightly more verbose:
```javascript
api.query.multi(
  api.query.balances.freeBalance(Alice),
  api.query.balances.freeBalance(Bob),
  api.query.balances.freeBalance(Dave),
)
```
so we could still add the `query.balances.freeBalance.multi` syntax as a shorthand. But I think the `query.multi()` one is more important.

**Comment by amaurymartiny** [comment]
@siman Concerning your message, a possible solution would be to let your parent component fetch the balances of everyone,
```javascript
withCalls(
  ['query.balances.freeBalance', account1],
  ['query.balances.freeBalance', account2],
  // ...
)
```
sort them, and pass the balances to each Row component via prop. Though the proposed enhancement will indeed make things cleaner.
