### ISSUE TITLE
Remove deprecated Centrifuge standalone chain on Polkadot.js Apps & Extension

### ISSUE THREAD

**Issue by lucasvo** [polkadot-js/apps#8012]
Both the extension and the apps can remove support for the retired standalone chain. Block production on the network has halted and there are no ways to submit any new transactions or do anything with the network for that matter.

**Comment by jacogr** [comment]
Normally the team themselves submit these PRs to manage their networks, but since I was in there anyway to disable unreachable endpoints, removed the providers.
