### ISSUE TITLE
After BABE changed to RRSC, explorer does not show the author

### ISSUE THREAD

**Issue by thirteenggh** [polkadot-js/apps#8035]
![image](https://user-images.githubusercontent.com/32699199/186058540-552d4eaa-7ca1-4221-9e70-5dc033382355.png)

**Comment by jacogr** [comment]
That would be expected. Each consensus algorithm has a different way to get the author information. So a first step would be to check the logs for which mechanism was used - with a unknown mechanism, the it won’t know which approach to take.
