### ISSUE TITLE
Rework Polkadot theme to include official Polkadot color palette 

### ISSUE THREAD

**Issue by Stefie** [polkadot-js/apps#804]
Emily from Web3 just sent me the finalized color palette with the official Polkadot colors.
Before starting we need to agree on one of the font-color/ background combinations on the second page of the pdf.

[20190212_Polkadot_Color_Palette.pdf](https://github.com/polkadot-js/apps/files/2957465/20190212_Polkadot_Color_Palette.pdf)

**Comment by rossbulat** [comment]
Good time to introduce [Styled Theming](https://github.com/styled-components/styled-theming) with this updated colour scheme?

Establish themes first: { theme: 'substrate' | 'polkadot' }

Then later: {mode: 'light' | 'dark' } (a dark mode would be very sleek) 

With the introduction of [variants](https://github.com/styled-components/styled-theming#themevariantsname-prop-themes) to the prior themes for easy configuration.

**Comment by jacogr** [comment]
Marked <meta> - to be split.

**Comment by Stefie** [comment]
I extracted the theme colors (primary/ secondary + grey shades) from the pdf when I was playing around with different theming options for next.js.

[polkadot.txt](https://github.com/polkadot-js/apps/files/3067287/polkadot.txt)
[substrate.txt](https://github.com/polkadot-js/apps/files/3067289/substrate.txt)

**Comment by jacogr** [comment]
Closing. Will be moving away from the Polkadot-own colors. (And only have a single overall theme)

**Comment by edisinovcic** [comment]
HI, guys is pallete available public?
Is this one official pallete? https://github.com/polkadot-js/apps/files/2957465/20190212_Polkadot_Color_Palette.pdf

**Comment by Stefie** [comment]
Hi @edisinovcic , I passed your question on to our communications team and the Design team from the Web3 Foundation. The Polkadot color pallete seems to be outdated, but they'll provide you with an updated one. // cc @iggyweb3

**Comment by edisinovcic** [comment]
> Hi @edisinovcic , I passed your question on to our communications team and the Design team from the Web3 Foundation. The Polkadot color pallete seems to be outdated, but they'll provide you with an updated one.
> 
> // cc @iggyweb3

Tnx :)

**Comment by a13xndra** [comment]
@edisinovcic the colors are going to be updated soon, but that's the only to use for now.
