### ISSUE TITLE
signAndSend: error: Error: createType(ExtrinsicSignature):: Unable to create Enum

### ISSUE THREAD

**Issue by BeroBurny** [polkadot-js/apps#8068]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

If I'm used integrated wallet for singing transaction should send founds but it fails wit error
`signAndSend: error: Error: createType(ExtrinsicSignature):: Unable to create Enum via index 17, in Ed25519, Sr25519, Ecdsa` and index is not the same on every run

* **Additional notes**
We create signatures like in Polkadot js extension

https://github.com/polkadot-js/extension/blob/884c89bddac69df455c54a59e0f3a867d61a0b4c/packages/extension-base/src/background/RequestBytesSign.ts#L20

our implementation
https://github.com/ChainSafe/metamask-snap-polkadot/blob/07e4c4c20c605757aa3984c5ba2f2f47f7e41761/packages/snap/src/rpc/substrate/sign.ts#L54

* **What is the motivation for changing the behavior?**

I'm tasked to integrate snap wallet into polkadot.js apps

* **Please tell us about your environment:**

  - Version: `master` branch
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

**Comment by jacogr** [comment]
You are signing a transaction - when the signature is a MultiSignature type, you would need to pass an additional flag to the keyring sign request.

**Comment by BeroBurny** [comment]
@jacogr Thanks a lot for the help :smile: got tunnel visioned and stuck on the wrong path.
