### ISSUE TITLE
get the list of all parachains, with their name and id , using polkadot.js API

### ISSUE THREAD

**Issue by gilles437** [polkadot-js/apps#8069]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ X] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

I am writing an app, the Runtime Exporter, which is a reporting, monitoring and alerting tool for any parachain. 
I am writing the app in typescript using polkadot.js API.
With the purpose of providing clear information to the user, I am trying to get the list of all the parachains per ecosystem (Polkadot, Kusama), with the id and the name of the parachain as a response, and don't see any way to do that programmatically. There is a query named api.query.paras.parachains() but it gives only the list of ids, without the name.

* **What is the motivation for changing the behavior?**

It will be easier for monitoring tools and any application that looks at all the parachains at a time to have this information available programmatically.

A parameter in the same function paras.parachains() specifying that a verbose response is required, would add the name associated with the same id of all the parachains as a reply. 

* **Please tell us about your environment:**

  - Version: latest
  - Environment:

    - [ X] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ X] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
The API will only return what in on-chain in the runtime storage. The parachain metadata itself is not stored on the relay.
