### ISSUE TITLE
Planned ParaId Change on Westend

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#8118]
See https://github.com/paritytech/polkadot/pull/5985

**Comment by jacogr** [comment]
Do you have an indication as to "when"? Can make a PR and just keep it up there until such time. (Literally 1 line change)

**Comment by joepetrowski** [comment]
Target would be late next week (around 21-23rd Sep) after we have the Polkadot genesis chain spec ready as a final pre-referendum test.
