### ISSUE TITLE
I can't call the rpc interface through `apiAt`.

### ISSUE THREAD

**Issue by 99Kies** [polkadot-js/apps#8127]
```javascript
// success call
const unsub = await api.rpc.payment.queryInfo("0x280402000b9051f13e8301", "0x84fcedcc36cd9ed195b6829c44b8edb6561d58333226b2f8d25e87ffde99e4ef")
console.log(unsub)

// fail call
const apiAt = api.at("0x84fcedcc36cd9ed195b6829c44b8edb6561d58333226b2f8d25e87ffde99e4ef"")
const unsub = await apiAt.rpc.payment.queryInfo("0x280402000b9051f13e8301")
console.log(unsub)
```

![image](https://user-images.githubusercontent.com/45918704/190305574-4f715a3d-a398-4b43-95e0-567976a4ade3.png)
![image](https://user-images.githubusercontent.com/45918704/190305590-d99255ff-0523-4096-94bb-d9eab1bec5da.png)

**Comment by jacogr** [comment]
Yes, the `apiAt` interfaces are limited to that which changes when metadata changes - so this is events, errors, runtime calls, extrinsics & storage. 

RPCs itself are not specified with metadata, rather it is decorated once only on the normal `api.rpc.*` interfaces.

**Comment by 99Kies** [comment]
Will apiAt be supported later to achieve this function? @jacogr I found that this apiAt is used in the subquery architecture.
