### ISSUE TITLE
Add the Totem Rococo Stagex Network

### ISSUE THREAD

**Issue by chrisdcosta** [polkadot-js/apps#8144]
This issue is related to a forthcoming pull request to add the Totem Rococo Stagex Parachain websocket information to Polkadotjs Apps.

**Comment by chrisdcosta** [comment]
Related to pull request:
https://github.com/polkadot-js/apps/pull/8145

**Comment by jacogr** [comment]
Closing. (Assuming the linked PR did that trick). As always, the best way to add these is just to make a PR with the [correct apps-config changes](https://github.com/polkadot-js/apps/tree/master/packages/apps-config).
