### ISSUE TITLE
Support nested `Option`s

### ISSUE THREAD

**Issue by NunoAlexandre** [polkadot-js/apps#8150]
* **I'm submitting a ...**

  - [x] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Currently the app doesn't handle nested Options well.
Note on this first screenshot how "Location" is a nested `Option` of `MultiLocation` and when it's toggled on (second screenshot), it doesn't allow for a location to be inserted.
#### 1
![Screenshot 2022-09-20 at 13 32 24](https://user-images.githubusercontent.com/7075260/191260300-4cebcd5f-aa02-4921-b275-c1d64e91842a.png)
#### 2
![Screenshot 2022-09-20 at 13 32 32](https://user-images.githubusercontent.com/7075260/191260305-f03a5614-d66e-4680-96a2-9a82ccd0170e.png)

* **What is the motivation for changing the behavior?**

a) It's currently impossible to call `ormlAssetRegistry::update_asset` through the PolkadotJS UI app; 
b) There's no reason not to support nested Options where they clearly are used sensibly in a case like this

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [x] Other

**Comment by jacogr** [comment]
Tracked as part of https://github.com/polkadot-js/apps/issues/2233 (if there is additional info to add, I would suggest doing it there so there is one single issue to cover all)

**Comment by NunoAlexandre** [comment]
A duplicate indeed, my bad! The other issue is open for over 2 years tho. Closing either way. Thanks
