### ISSUE TITLE
Prepare for Weights v2

### ISSUE THREAD

**Issue by KiChjang** [polkadot-js/apps#8188]
With paritytech/substrate#12277 merged, we now need to ensure that the frontend can display the new `Weight` structure appropriately.

Some extrinsics won't have migrated yet, and will continue to use a wrapper struct called `OldWeight(u64)`.

**Comment by jacogr** [comment]
This is first - https://github.com/polkadot-js/api/pull/5251 (quite a bitch since contracts need a lot of TÖC to cater for old and new)

Before the above is in and available on a release, not much the UI can do.

**Comment by pepoviola** [comment]
> With [paritytech/substrate#12277](https://github.com/paritytech/substrate/pull/12277) merged, we now need to ensure that the frontend can display the new `Weight` structure appropriately.
> 
> Some extrinsics won't have migrated yet, and will continue to use a wrapper struct called `OldWeight(u64)`.

Hi @KiChjang, just for tracking purpose. This is the cause of the failure for this job: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/1903873 

Thanks!

**Comment by jacogr** [comment]
The UI itself is now robust enough to support both chains with weight v1 and those with weight v2. However, v2 won't work until we have had an API upgrade. (As soon as a release is cut there, aka master branch of API works, but unreleased)
