### ISSUE TITLE
issues with transfering GLMR from my polkadot waller

### ISSUE THREAD

**Issue by graham455** [polkadot-js/apps#8189]
Hello,

I'm trying to transfer some GLMR tokens from Polkadot.js to another wallet and I am keep getting this error:

balances.transferKeepAlive createType(ExtrinsicSignature):: Expected input with 65 bytes (520 bits), found 66 bytes

any advise?

**Comment by jacogr** [comment]
Which network is GLMR? (Native token or asset? Sorry there are a lot of parachains, so I really don't know off-hand which token is where) How are you transferring? Is the wallet internal or external? Have you injected any specific developer types?

**Comment by graham455** [comment]
Thanks for asking.
  I am on the Polkadot j.s website on the moonbeam parachain. I am trying to send GLMR (Moonbean Token) from my Moonbeam (EXTENSION)  injected js.wallet to another wallet but get  
"balances.transferKeepAlive createType(ExtrinsicSignature):: Expected input with 65 bytes (520 bits), found 66 bytes" in a red box.

**Comment by graham455** [comment]
<img width="960" alt="Screenshot GLMR wallet" src="https://user-images.githubusercontent.com/68194419/193469952-f52a481e-9b1d-47c2-90eb-9fc982400f6c.png">

**Comment by jacogr** [comment]
The extension currently cannot sign transactions for Moonbeam networks. There is an open issue and pull-request which will be available when a new release is made.

**Comment by graham455** [comment]
Thank you. But
1. Open issue, means it's an issue not resolved.
2. A pull-request is an open-issue you are working on?
3. Which all means I can not do anything ATM until an update is applied enabling the moonbeam extension to sign transactions?
4. Will I be informed when it's fixed or do I keep trying until it's fixed? And any idea when this issue will be resolved?
With kind regards Graham Alder


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jacogr** [comment]
1. Open issue - it means it is tracked
2. Pull request - this means that is code that resolves the issue
3. Indeed, it has never been operational for the Moon* chains
4. The extension stores auto-updates the browser on new releases, you can also track all releases here - https://github.com/polkadot-js/extension/releases

There is no indication yet of when the next release will be, since it contains a number of enhancements, they need to be properly tested. Tentatively, most probably end-Oct to mid-Nov a new release should hit the stores.

**Comment by graham455** [comment]
👌 thank you so much for info. Much appreciated.  I fully, almost,  understand now. Not selling, no problem.
Regards graham 😀 👍

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
