### ISSUE TITLE
Disabled text selection on disabled input fields prevents users to select & copy output

### ISSUE THREAD

**Issue by lucasvo** [polkadot-js/apps#8212]
In many places the UI renders outputs in input fields that have text selection disabled (at least in firefox linux) which means copying anything from these outputs is impossible. For example on the extrinsic decode page:

![screen_2022-10-06-14-18-58](https://user-images.githubusercontent.com/31727/194338384-60a2d2f7-d2a5-49ba-8941-3af17498c84b.png)

**Comment by lucasvo** [comment]
@jacogr would it work to just change them to `readonly` instead of `disabled`

**Comment by TorstenStueber** [comment]
@jacogr I think that the actual problem is the CSS setting `pointer-events: none` for these input fields. If I turn this off, then indeed I can select the text also with Firefox.

**Comment by jacogr** [comment]
Quite possible without [looking at thh docs](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) (after you mentioned it) was not even aware that those exist as a CSS property. 

Will happily merge a PR to remove those, so if it makes it better, all good.

**Comment by jacogr** [comment]
SUI is actually being dropped - there are 2 components still that use it, so at best it is an ongoing effort. (And as you noticed, once we don't use the components anymore, we also need to still get rid of the styles as we use them). So I don't want to spend too much effort in swapping over.

With that in mind the best course of action is an override here for the specific styles - PRs for that would be welcome.
