### ISSUE TITLE
Support on UI for Option <customType> 

### ISSUE THREAD

**Issue by kabaneridev** [polkadot-js/apps#8236]
* **I'm submitting a ...**

  - [x] Bug report
  - [x] Feature request

* **What is the current behavior and expected behavior?**
Current behaviour: Polkadot Apps UI doesn't support custom types, like `Option <BoundedString>` so due that, we can't submit extrinsics using Extrinsics, because it think there is some file to upload, once it is just custom type `<BoundedString>`. It works if this is not Option (look at palletName), but if its Option => after toggling "file upload" and entering text, the `Submit Transaction` button is greyed out and can't submit extrinsic.

The `BoundedString` is just `BoundedVec<u8, MAX_LENGTH>`.  It only accepts the exact bounded vector's length, no more no less

![Screenshot 2022-10-14 at 10 21 11](https://user-images.githubusercontent.com/48051231/195798683-ce35b638-338c-43f6-90ac-71db93869faa.png)

* **What is the motivation for changing the behavior?**

It would be great to have support for Options so the UI would display nicely and we could actually use it properly. Right now we need to use JS console if there is any custom type wrapped into Option.

  - Version:
Parity Polkadot v0.9.29
api v9.5.1
apps v0.121.2-102-x
  - Environment:
    - [x] Browsers
     - Chrome, Firefox

**Comment by jacogr** [comment]
Sadly the Option/Upload overlap, the same thing happens with eg. `Option<Option<...>`, so the root cause is exactly the same issue as - https://github.com/polkadot-js/apps/issues/2233

**Comment by jacogr** [comment]
Closing, tracked in #2233

**Comment by jacogr** [comment]
When a U8a is passed in, it needs to be correctly encoded in SCALE. So for Option + Vec, it needs to be -

1. 1/0 for some/none
2. compact length
3. data

There will be no additions done to the API, since anything Uint8Array is always meant to be SCALE based on the API logic. Breaking that contract breaks the world.
