### ISSUE TITLE
Decode and encode `sudo` calls

### ISSUE THREAD

**Issue by dzmitry-lahoda** [polkadot-js/apps#8245]
I'm submitting a feature request to allow encode/decode sudo calls easily.

Currently if I want to issue `sudo` call I have to type all message manually.

It is very slow and error prone for big XCM messages. 

Would be awesome that I can decode and encode `sudo` calls same way I do not `sudo` operations.

As safety measure some visual element could alert on danger of sudo call executing decoded extrinsic and ask for double confirmation  in this case.

**Comment by jacogr** [comment]
No idea what the request is here - the extrinsic tab just has the fields, so it can be filled.

**Comment by dzmitry-lahoda** [comment]
If I have hex encoded extrinsic string, can I execute it as sudo?

**Comment by jacogr** [comment]
No, the sudo page does not have the complexity that the decode allows. It is not intended to be added either. 

There is certainly a gap to have Call-types allow either drop-down or hex input, for this PRs are welcome.
