### ISSUE TITLE
Delete element using Delete keyboard key

### ISSUE THREAD

**Issue by dzmitry-lahoda** [polkadot-js/apps#8249]
**I'm submitting a feature request about deleting XCM entries using Delete keyboard button**.

Decode message  https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpicasso-rpc.composable.finance#/extrinsics/decode/0x2900010100020c000400000000070010a5d4e81300000000070010a5d4e80006010700e8764817183c01d0070000

Open Submission tab.

Select XCM instruction.

<img width="943" alt="image" src="https://user-images.githubusercontent.com/757125/196467046-12f39503-678e-47db-b965-d6f2000d5ba8.png">

Press Delete. 

Expected that element was deleted.

Actual is that nothing happens.

It would be very useful to make typing complex XCM messages easier. 

Currently I can delete only last instruction. I cannot delete instruction in the middle nor I can use keyboard to craft XCM fast.

I am using latest https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpicasso-rpc.composable.finance#/extrinsics

I am on Windows 11 in 

```
Brave is up to date
[Version 1.44.112 Chromium: 106.0.5249.119 (Official Build) (64-bit)](https://brave.com/latest/)
```

**Comment by jacogr** [comment]
There are no keyboard-specific overrides. In this case since the messages are created dynamically based on metadata, it would mean huge complexity in hook for any child elements to bubble to "some top element". This is not complexity that we would want.
