### ISSUE TITLE
Better UX for add and delete of elements in complex XCM message

### ISSUE THREAD

**Issue by dzmitry-lahoda** [polkadot-js/apps#8250]
**I'm submitting a feature request to improve add and delete buttons crafting complex XCM message**.

Decode message  https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpicasso-rpc.composable.finance#/extrinsics/decode/0x2900010100020c000400000000070010a5d4e81300000000070010a5d4e80006010700e8764817183c01d0070000

Open Submission tab.

Navigate to add and delete buttons. 

It is hard to get what it will add or delete. 

Consider moving it to one of the places.

Option A. Move the left with outline to be same as deleted element.

<img width="1483" alt="image" src="https://user-images.githubusercontent.com/757125/196469793-096c14e7-baa5-43f0-bc93-4d06aa572386.png">

Option B. Consider moving buttons to element with which collection will be added and to element which will be removed 

<img width="1483" alt="image" src="https://user-images.githubusercontent.com/757125/196470355-b818ae3c-8526-45dd-8fab-22a916f6cf28.png">

Option C. Move delete to the last element as Delete deletes last element.

It would be very useful to make typing complex XCM messages easier. 

I am using latest https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpicasso-rpc.composable.finance#/extrinsics

I am on Windows 11 in 

```
Brave is up to date
[Version 1.44.112 Chromium: 106.0.5249.119 (Official Build) (64-bit)](https://brave.com/latest/)
```

**Comment by jacogr** [comment]
Overlapping is an issue (see the endless issues with nested-Option). There is no specific overrides on a per-message types, rather Vectors are just handled in a generic fashion.
