### ISSUE TITLE
Sudo missing? (0.9.29+)

### ISSUE THREAD

**Issue by evilrobot-01** [polkadot-js/apps#8257]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
 The **Sudo** menu option on the **Developer** menu disappears when using with local `substrate-node-template` at `polkadot-v0.9.29` and `polkadot-v0.9.30`. Switching back down to `polkadot-v0.9.28` restores functionality.

  I also see "Unable to decode storage system.events:: createType(Vec<FrameSystemEventRecord>):: decodeU8a: failed at 0x00000000000000001c6c090000000002… (index 0/1)" error on the **Block details** page, as reported in #8197 , but it seemed that may be have been said to be fixed on `master` now?

* **What is the motivation for changing the behavior?**
  **Sudo** should still be accessible after updating substrate-node-template.

* **Please tell us about your environment:**
   - Fresh clone of `substrate-node-template`, switching to various tags.
   - Fresh clone of `polkadot-js/apps`, using `master` branch (commit 07c3b33) as I had seen some work had been done with regards to the above mentioned issue

  - Version:
    - polkadotjs/apps: `master` branch (commit 07c3b33) 
    - substrate-node-template: polkadot-v0.9.29+
    - Firefox: 105
    - Node: v18.10
    
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
What is in runtime/lib.rs of node template? The UI detects based on availability of the `sudo` module in the metadata.

**Comment by evilrobot-01** [comment]
https://github.com/substrate-developer-hub/substrate-node-template/blob/6c701fa6109693a955bb1fa317d8b724634e0fa7/runtime/src/lib.rs#L268 and https://github.com/substrate-developer-hub/substrate-node-template/blob/6c701fa6109693a955bb1fa317d8b724634e0fa7/runtime/src/lib.rs#L293

The only pertinent changes from the 0.9.28 tag seem to be the changing to RuntimeEvent and RuntimeCall: https://github.com/substrate-developer-hub/substrate-node-template/commit/6c701fa6109693a955bb1fa317d8b724634e0fa7#diff-0ec06ea58bd455f09ce6b3bb4c2c1c0d37bda51c1e1be2151c560c9c973959ec
