### ISSUE TITLE
Unable to decode storage system.events after upgrading node template to 0.9.30 release

### ISSUE THREAD

**Issue by lana-shanghai** [polkadot-js/apps#8259]
Hi, I am bumping into this issue with both running `polkadotjs/apps` locally, and using the `polkadot.js.org` page with the substrate node template (with 0.9.28 everything works well):

<img width="841" alt="Screenshot 2022-10-20 at 17 17 08" src="https://user-images.githubusercontent.com/31368580/197005855-80c241bb-1891-4bf3-adc0-c05a5687a454.png">

Browser Google Chrome, node version
```
npm version
{
  'polkadot-apps': '0.121.2-110-x',
  npm: '8.19.1',
  node: '16.17.0',
  v8: '9.4.146.26-node.22',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.7',
  openssl: '1.1.1q+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022a',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```

**Comment by jacogr** [comment]
The issue with Substrate (spec_name “node”) and the template (spec_name “node_template”) is that the API only tracks master. So for these it explicitly applies a weight override to use the latest v2. 

Basically it means that older versions of those with the matching spec_name won’t work. There is most probably already a fix applied in api master that will also downgrade types based on detection (current releases versions only upgrade with detection - so without a downgrade the v2 weights are always applied to any “spec_name == node”)
