### ISSUE TITLE
Error while initiating multisig transactions on Polkadex

### ISSUE THREAD

**Issue by michalisFr** [polkadot-js/apps#8261]
* **I'm submitting a ...**

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

An error occurs when trying to initiate multisig transactions on Polkadex. I believe this started after the recent runtime upgrade on the chain, but hadn't tried any multisig txs recently before that. The metadata in the extension is updated.

This one is for a `staking.bondExtra` extrinsic:
![Screenshot 2022-10-20 at 9 35 51 PM](https://user-images.githubusercontent.com/45905709/197034075-7a246692-1f5c-4e50-8c27-a9220b6de1db.png)

while this one for a simple `balances.transfer`:
![Screenshot 2022-10-20 at 9 42 41 PM](https://user-images.githubusercontent.com/45905709/197034171-29a0a288-dfb5-44cc-a322-12e7bc8858fd.png)

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version: Chrome Version 106.0.5249.119 (Official Build) (x86_64)
  - Environment:

    - [ ] Node.js
    - [X] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by michalisFr** [comment]
I managed to do it manually through the extrinsics page however

**Comment by jacogr** [comment]
This is very unlikely to be fixed. This is the issue -

- the chain itself has migrated to WeightV2
- multisig is still using old weights (no migration to the new structure, unlike elsewhere on-chain)

The logic in the UI says:

- if the chain used WeightV2, multisig calls gets weight v2
- else, supply weight v1

In this case there is a discrepancy between the two.

**Comment by jacogr** [comment]
Ummm, it could also be because their "specName" is "node", which is the default value for the Substrate kitchensink runtime. (For the kitchensink runtime the Weights track Substrate master, so it is set at V2 for all runtime calls, RPC calls)

**Comment by michalisFr** [comment]
Thanks @jacogr and apologies for the late reply. I have notified the Polkadex team about this issue.

**Comment by jacogr** [comment]
It _may_ be better after the last API upgrade since there were some tweaks to weight upgrades/downgrades. So it could have solved itself.

However, even if solved for now, it will probably happen again in the future in various places since the types for Substrate are identified by the "node" `specName` and those always track master. (While most extrinsic/storage types come from metadata, where things touch RPCs, runtime calls or have special handling, there are still type definitions)

**Comment by michalisFr** [comment]
Nope, I'm afraid not.
