### ISSUE TITLE
Feature request: Submit Transaction button on Decode page

### ISSUE THREAD

**Issue by sander2** [polkadot-js/apps#8294]
This is a feature request. 

### What

I would like for the decode page to contain a "Submit Transaction" button, in the same way that the Submission tab has.

### Why

We commonly share links to the decode page ([example](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpublic-rpc.pinknode.io%2Fkusama#/extrinsics/decode/0x00030400)) in order for other people to submit extrinsics. The current process to do so is:

- click the link
- click `submission`
- click `Submit Transaction`

For some reason, many people find this confusing, and some back and forth is often required to clarify what exactly they need to do. If the feature request is implemented, the process is simplified to:

- click the link
- click `Submit Transaction`

An additional benefit is that it's less likely for third party submitters to accidentally change one of the fields, since the `decode` tab is read-only.

**Comment by jacogr** [comment]
Click from Decode to Submit and the decoded tx information will be filled for submission.

**Comment by sander2** [comment]
> Click from Decode to Submit and the decoded tx information will be filled for submission.

Thanks I do realize that (as mentioned in the issue itself), but for some reason when we communicate this to third parties they always find it confusing. This feature request is really only to turn the 3-step process into a 2-step process. It's only a minor improvement but it'll help make the process just a tiny bit easier

**Comment by jacogr** [comment]
It is actually a major overhaul, so it is not a "minor improvement".

**Comment by sander2** [comment]
> It is actually a major overhaul, so it is not a "minor improvement". There used to be similar functionality that was a major pain to maintain, was very confusing due to the account/etc selection and duplicated. It will be not be put back due to those reasons.

Understood, thanks.

**Comment by jacogr** [comment]
There may be a “redirect to” option here that can make it more “intuitive”. Something like a “go to submission” button. 

That allows no duplication and makes it more “in your face” as opposed to “hidden functionality”

**Comment by sander2** [comment]
That could be something to consider, yea. Anyway, I only opened this issue because (not being experienced with the code base) I expected this to be a trivial improvement to add. Seeing that it's not trivial, we just need to document the process more clearly on our side, and that's ok
