### ISSUE TITLE
Decode error when submitting a proposal for Gov v2.

### ISSUE THREAD

**Issue by hbulgarini** [polkadot-js/apps#8304]
Hello! We are trying the new Gov v2 with the release v0.9.31 (branch v0.9.31-rc6) and when we try to submit a proposal the following decoding error appears (happen with all tracks):

`
react.01.c7be39f7.js:2 Uncaught Error: createType(Call):: Call: failed decoding referenda.submit:: Struct: failed on args: {"proposal_origin":"{\"_enum\":{\"system\":\"FrameSupportDispatchRawOrigin\",\"__Unused1\":\"Null\",\"__Unused2\":\"Null\",\"__Unused3\":\"Null\",\"__Unused4\":\"Null\",\"__Unused5\":\"Null\",\"Void\":\"SpCoreVoid\",\"__Unused7\":\"Null\",\"__Unused8\":\"Null\",\"__Unused9\":\"Null\",\"__Unused10\":\"Null\",\"__Unused11\":\"Null\",\"__Unused12\":\"Null\",\"__Unused13\":\"Null\",\"Council\":\"PalletCollectiveRawOrigin\",\"TechnicalCommittee\":\"PalletCollectiveRawOrigin\",\"__Unused16\":\"Null\",\"__Unused17\":\"Null\",\"__Unused18\":\"Null\",\"__Unused19\":\"Null\",\"__Unused20\":\"Null\",\"__Unused21\":\"Null\",\"__Unused22\":\"Null\",\"__Unused23\":\"Null\",\"__Unused24\":\"Null\",\"__Unused25\":\"Null\",\"__Unused26\":\"Null\",\"__Unused27\":\"Null\",\"__Unused28\":\"Null\",\"__Unused29\":\"Null\",\"__Unused30\":\"Null\",\"__Unused31\":\"Null\",\"__Unused32\":\"Null\",\"__Unused33\":\"Null\",\"__Unused34\":\"Null\",\"__Unused35\":\"Null\",\"__Unused36\":\"Null\",\"__Unused37\":\"Null\",\"__Unused38\":\"Null\",\"__Unused39\":\"Null\",\"__Unused40\":\"Null\",\"__Unused41\":\"Null\",\"__Unused42\":\"Null\",\"Origins\":\"KusamaRuntimeGovernanceOriginsPalletCustomOriginsOrigin\",\"__Unused44\":\"Null\",\"__Unused45\":\"Null\",\"__Unused46\":\"Null\",\"__Unused47\":\"Null\",\"__Unused48\":\"Null\",\"__Unused49\":\"Null\",\"ParachainsOrigin\":\"PolkadotRuntimeParachainsOriginPalletOrigin\",\"__Unused51\":\"Null\",\"__Unused52\":\"Null\",\"__Unused53\":\"Null\",\"__Unused54\":\"Null\",\"__Unused55\":\"Null\",\"__Unused56\":\"Null\",\"__Unused57\":\"Null\",\"__Unused58\":\"Null\",\"__Unused59\":\"Null\",\"__Unused60\":\"Null\",\"__Unused61\":\"Null\",\"__Unused62\":\"Null\",\"__Unused63\":\"Null\",\"__Unused64\":\"Null\",\"__Unused65\":\"Null\",\"__Unused66\":\"Null\",\"__Unused67\":\"Null\",\"__Unused68\":\"Null\",\"__Unused69\":\"Null\",\"__Unused70\":\"Null\",\"__Unused71\":\"Null\",\"__Unused72\":\"Null\",\"__Unused73\":\"Null\",\"__Unused74\":\"Null\",\"__Unused75\":\"Null\",\"__Unused76\":\"Null\",\"__Unused77\":\"Null\",\"__Unused78\":\"Null\",\"__Unused79\":\"Null\",\"__Unused80\":\"Null\",\"__Unused81\":\"Null\",\"__Unused82\":\"Null\",\"__Unused83\":\"Null\",\"__Unused84\":\"Null\",\"__Unused85\":\"Null\",\"__Unused86\":\"Null\",\"__Unused87\":\"Null\",\"__Unused88\":\"Null\",\"__Unused89\":\"Null\",\"__Unused90\":\"Null\",\"__Unused91\":\"Null\",\"__Unused92\":\"Null\",\"__Unused93\":\"Null\",\"__Unused94\":\"Null\",\"__Unused95\":\"Null\",\"__Unused96\":\"Null\",\"__Unused97\":\"Null\",\"__Unused98\":\"Null\",\"XcmPallet\":\"PalletXcmOrigin\"}}","proposal":"{\"_enum\":{\"Legacy\":\"{\\\"_alias\\\":{\\\"hash_\\\":\\\"hash\\\"},\\\"hash_\\\":\\\"H256\\\"}\",\"Inline\":\"Bytes\",\"Lookup\":\"{\\\"_alias\\\":{\\\"hash_\\\":\\\"hash\\\"},\\\"hash_\\\":\\\"H256\\\",\\\"len\\\":\\\"u32\\\"}\"}}","enactment_moment":"{\"_enum\":{\"At\":\"u32\",\"After\":\"u32\"}}"}:: Struct: failed on proposal: {"_enum":{"Legacy":"{\"_alias\":{\"hash_\":\"hash\"},\"hash_\":\"H256\"}","Inline":"Bytes","Lookup":"{\"_alias\":{\"hash_\":\"hash\"},\"hash_\":\"H256\",\"len\":\"u32\"}"}}:: Unable to create Enum via index 69, in Legacy, Inline, Lookup
    at p (polkadot.01.00feeb10.js:1:173005)
    at $.createTypeUnsafe (polkadot.01.00feeb10.js:1:255374)
    at o (polkadot.01.00feeb10.js:1:467975)
    at a (polkadot.01.00feeb10.js:1:93359)
    at main.325782f4.js:2:2320298
    at main.325782f4.js:2:2317295
    at Object.De (react.01.c7be39f7.js:2:104870)
    at Ze (react.01.c7be39f7.js:2:105024)
    at react.01.c7be39f7.js:2:124884
    at Ir (react.01.c7be39f7.js:2:124978)
`

<img width="840" alt="Screen Shot 2022-11-03 at 14 29 55" src="https://user-images.githubusercontent.com/12089572/199733913-35e2814d-1415-461c-bfdb-9d8b4f264d1a.png">

Please note that preimage submission works as expected but the submit proposal breaks.

CC: @rrtti @oshakarishvili

**Comment by jacogr** [comment]
Yes, aware of it - have a branch locally that should adjust, currently testing since Fri. (The preimage adjustment PRs has create untold nightmares)

**Comment by hbulgarini** [comment]
> Yes, aware of it - have a branch locally that should adjust, currently testing since Fri. (The preimage adjustment PRs has create untold nightmares)

Thanks! just for curiosity is the issue related to this PR? https://github.com/paritytech/substrate/pull/11649

**Comment by jacogr** [comment]
Indeed. So preimages went from hash -> enum. (Affects governance 2, as well as previous versions of democracy, which took a bit of priority).

In this case I should have pushed the fix for the submission already, but things snowballed a bit. (So the preimage submission part works, but not using them - display is actually fine as well)
