### ISSUE TITLE
Error: Unable to authorise transaction (locked key pair)

### ISSUE THREAD

**Issue by jamesbayly** [polkadot-js/apps#8309]
- [x] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

I'm trying to submit a `utility.batchAll` transaction using the Javascript tool in the Developer tab. 
I'm signing it using an injected account from the PolkadotJS extension

my code looks something like this
```
const sender = 'xxx' // The public address of our Account;

// Create a extrinsic, transferring randomAmount units to Bob.
const calls = [];
... // we construct a valid batchAll call here
let batch = api.tx.utility.batchAll(calls);

// Sign and Send the transaction
await batch.signAndSend(sender, ({ events = [], status }) => {
  if (status.isInBlock) {
    console.log('Successful with hash ' + status.asInBlock.toHex());
  } else {
    console.log('Status of transfer: ' + status.type);
  }
});
```

I would have though that I can sign and send this using my account but i get the below error? No prompt to unlock my PolkadotJS account either

![image](https://user-images.githubusercontent.com/46693720/199869713-7e9df028-5c0a-40de-8cbf-fb8555bf9032.png)

* **Please tell us about your environment:**

  - Version: 
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Currently the JS tab does not actually deal with the extensions. The issue is that the JS there runs in a completely different context, so it doesn't hook into the main UI.

On dev nodes (and only dev nodes), the keyring is injected, so you can use that, however for production/testing/etc. chains there are no hooks to the main sending functionality. (Doing so would mean that you can send unsuspecting users snippets to execute that would transfer funds)

**Comment by jamesbayly** [comment]
That makes sense, I could argue that people might want an "dangerous" mode where they could execute scripts with within the extension context - it could be hidden behind a setting that is disabled by default. Most users will understand the risks they are taking with executing malicious scripts but there's always some that wont...

Even if there is no desire to allow this, can I make a suggestion for some documentation about this or a note on the page to the above effect when the context is not a dev node?
