### ISSUE TITLE
Not able to vote in referenda tabs on Polkadot.js Apps (Gov2 testing)

### ISSUE THREAD

**Issue by rrtti** [polkadot-js/apps#8323]
When opening a referendum and trying to vote on it during/after preparation phase, I am unable to find the vote button: 

<img width="1379" alt="Screenshot 2022-11-07 at 19 05 25" src="https://user-images.githubusercontent.com/22815262/200383775-9f117de9-e440-43de-bb8f-3d25c083fad9.png">

<img width="1390" alt="Screenshot 2022-11-07 at 19 05 43" src="https://user-images.githubusercontent.com/22815262/200383825-83da433a-f7dc-4410-abc1-87563cfdd18c.png">

When heading to Extrinsics tab to vote on the referendum

<img width="1357" alt="Screenshot 2022-11-07 at 19 07 41" src="https://user-images.githubusercontent.com/22815262/200384184-2324d138-3a9f-418c-8804-079a871a17b0.png">

this error msg comes up:

<img width="284" alt="Screenshot 2022-11-07 at 19 07 51" src="https://user-images.githubusercontent.com/22815262/200383884-671a764e-9cb9-444d-9191-a1e669c4f6ce.png">

Pretty sure you are on it :) but flagging here to know if this is expected until Gov2 is up and running or if we need to fix the issue beforehand. Thanks as always, Jaco!

**Comment by jacogr** [comment]
The second message is weird though…

**Comment by jacogr** [comment]
The flow is weird. You first need to place a deposit. Once done, it can go into decoding. Once in deciding, you can vote.
