### ISSUE TITLE
Node selection is wrongly highlighted

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#834]
It should have the same color as the rest of the page.

<img width="1428" alt="Polkadot:Substrate Portal 2019-03-23 18-13-59" src="https://user-images.githubusercontent.com/1424473/54869357-86e3fe80-4d97-11e9-9152-42f2d80ab1eb.png">

**Comment by Stefie** [comment]
Which color / part of the node selection field do you mean? I don't really see anything off here...

**Comment by jacogr** [comment]
Look at the background surrounding the field - it is white. Transparent would solve it, i.e. so it fits in with the rest of the fields where it does not sit in a white box.
