### ISSUE TITLE
Council motions page broken when there's no staking pallet

### ISSUE THREAD

**Issue by onnovisser** [polkadot-js/apps#8349]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

The Motions tab of the Council page renders an error when there's no staking pallet on the chain it's connected to.
Example: [Council page on Centrfifuge parachain](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ffullnode.parachain.centrifuge.io#/council)
Error:
```
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

can't access property "slashDeferDuration", n.consts.staking is undefined
21460/Bd</<@https://polkadot.js.org/apps/main.64ca8087.js:2:1734492
rl@https://polkadot.js.org/apps/react.01.0e3116ae.js:2:181360
xc@https://polkadot.js.org/apps/react.01.0e3116ae.js:2:201484
52967/wc/<@https://polkadot.js.org/apps/react.01.0e3116ae.js:2:198086
S@https://polkadot.js.org/apps/other.01.178a13cf.js:2:185264
I@https://polkadot.js.org/apps/other.01.178a13cf.js:2:185795
77830/t.exports@https://polkadot.js.org/apps/other.01.178a13cf.js:2:44958
@https://polkadot.js.org/apps/other.01.178a13cf.js:2:58827
b@https://polkadot.js.org/apps/other.01.178a13cf.js:2:58684
m@https://polkadot.js.org/apps/other.01.178a13cf.js:2:58706
```

I see the Motions tab renders the [useAvailableSlashes](https://github.com/polkadot-js/apps/blob/9e5fa6a3532187716c12a564814f812e0fcb1f37/packages/page-council/src/Motions/Slashing.tsx#L33) hook, which had a [change earlier today](https://github.com/polkadot-js/apps/blob/84828204694d65cd9ee737de18c737e16b77824a/packages/react-hooks/src/useAvailableSlashes.ts#L43), looking up a constant on the staking pallet, assuming it to be available.

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Sorry about that, will get a fix in.
