### ISSUE TITLE
Got "-32603: Unknown error occurred:" While transfer my KLP via polkadot.js.app

### ISSUE THREAD

**Issue by devilrayzl** [polkadot-js/apps#8351]
I want to transfer my KLP（kulupu）token via https://polkadot.js.org/apps

 and I got error like below:

`-32603: Unknown error occurred: Client, Application, UnknownBlock, State already discarded for BlockId::Hash, 0xf7a99d3cb92853d00d5275c971c132c074636256583fee53b3bbe60d7b8769ba`

What wrong with the tool?

**Comment by jacogr** [comment]
That error is from the RPC node itself, not the app.

Generally RPCs nodes are run in archive mode (the above has pruning, which is very weird). I would suggest using a different RPC node.
