### ISSUE TITLE
Contracts: Weights V2 support

### ISSUE THREAD

**Issue by ascjones** [polkadot-js/apps#8364]
Deploying and calling contracts should support passing `prrof_size` for weights V2, currently it only supplies the legacy 1 dimensional `execution_time` part of the weight.

**Comment by ascjones** [comment]
Linking to https://github.com/polkadot-js/api/issues/5255

**Comment by andabak** [comment]
Hello here @jacogr - are there any estimates when would this issue be addressed? 

I am aware there is a PR for this with many asking when will it be reviewed (and hopefully merged) https://github.com/polkadot-js/apps/pull/8538

Thank you for your answer.

**Comment by ascjones** [comment]
This may have already been fixed, since we are able to use it again for contracts see https://github.com/paritytech/ink-waterfall/commit/6b4a59e998429ca5113b0485bdb0edfb06c8ee70.

Not sure what the relevant PR is though.
