### ISSUE TITLE
Update democracy UI to work with delegation

### ISSUE THREAD

**Issue by JoshOrndorff** [polkadot-js/apps#838]
Delegation went into the democracy module with https://github.com/paritytech/substrate/pull/1827 The UI does not handle this correctly. When Alice delegates to Bob, then Bob votes, only Bob's tokens show.

**Comment by jacogr** [comment]
UI never catered for this as far as I recall. 

It hasn't kept up to speed with the democracy module evolution. I believe the votes are only counted based on the voter balance and the delegation is not queried nor looked at at all

**Comment by jacogr** [comment]
The (erm, horrible) vote calculation - https://github.com/polkadot-js/apps/blob/master/packages/app-democracy/src/Referendum.tsx#L56-L88

**Comment by jacogr** [comment]
Replaced by #940 (Trying out a new format for the issues to explain things a bit better - hopefully captured all the information in there properly)
