### ISSUE TITLE
Runtime call `rococoFinalityApi` configuration

### ISSUE THREAD

**Issue by bkontur** [polkadot-js/apps#8395]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

![image](https://user-images.githubusercontent.com/8159517/203283172-cd58fe59-8c38-481f-9e88-84b1c86c7685.png)

I would like to ask, where is `rococoFinalityApi` configured in polkadot.js?

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-bridge-hub-rpc.polkadot.io#/runtime

**Comment by jacogr** [comment]
https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/finality/runtime.ts

**Comment by bkontur** [comment]
ok, cool, thank you,
and if I want to change or add new methods, 
should I just update and modify that file? and create PR?

**Comment by jacogr** [comment]
Indeed, if there are missing methods (or a new version of a runtime interface), it should be added there. PRs are always welcome and greatly appreciated.

**Comment by bkontur** [comment]
I will continue

**Comment by bkontur** [comment]
@jacogr 
please, how can I remove `stale` label?

**Comment by jacogr** [comment]
Don't worry too much about this issue -

1. it is framed as a question
2. it is in the wrong repo (easy mistake to make)

Just submit a PR against the api repo if you need to add more, no need to keep this one open.
