### ISSUE TITLE
Proxy account for Ledger does not sign OpenGov voting transaction on PolkadotJS Apps

### ISSUE THREAD

**Issue by anaelleltd** [polkadot-js/apps#8408]
* **I'm submitting a ...**

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

I'm having an issue with voting on Gov2.0/OpenGov referenda with a proxy on Polkadot JS Extension for a ledger account via PolkadotJS Apps. 
The transaction is shown as submitted on PJS Apps, but it doesn't appear in Subscan and the vote is not ultimately counted. 
Last time I voted with this setup was 4 days ago, and I had no issue then. 
Please investigate this bug. 🔍

* **Please tell us about your environment:**
 - Version: Latest release of Polkadot JS Extension
 - Environment: Windows 10 OS
 - [X] Browser  Chromium

**Comment by jacogr** [comment]
The apps UI only handles the tx until submission. Ledger/Proxy is not handled any differently to any other txs.

Does the Ledger app support the new transactions as of yet? (I know there is limited space on the devices, so not all txs are supported, so also need to ensure that the latest firmware is available on the device)

**Comment by anaelleltd** [comment]
Thanks for the clarifications, @jacogr.
I had to install the Kusama XL App on Ledger and made the call to vote directly from the Ledger account. This worked.

However, when I tried to use the proxy account to make the call, I got the following message:
![Ledger Proxyerror](https://user-images.githubusercontent.com/44770354/203719550-154d3841-6c3a-41e7-822a-2050dfd91b26.JPG)

Not sure where the issue lies, but it is clearly the case that the (Non-transfer) Proxy isn't doing what it should do.

**Comment by jacogr** [comment]
CallFiltered - that is from the runtime itself. So it seem that (currently) it doesn't allow wrapped proxy calls. (Can only be confirmed by looking at the runtime config, e.g https://github.com/paritytech/polkadot/tree/master/runtime/kusama)

**Comment by anaelleltd** [comment]
I don't see the new pallets ConvictionVoting and Referenda in this list: https://github.com/paritytech/polkadot/blob/master/runtime/kusama/src/lib.rs#L984
So, I will just have to wait until they are integrated into Proxies. 

Thanks for the info! 🙏🏿

**Comment by jacogr** [comment]
Expect chaos ;)

**Comment by jacogr** [comment]
See https://github.com/paritytech/polkadot/pull/6366 for the PR adding runtime support.

**Comment by jacogr** [comment]
Closing. (This is runtime related so should be tracked there - however I believe the latest runtimes do have support now)
