### ISSUE TITLE
Unable to upload an ink! contract

### ISSUE THREAD

**Issue by donhuanvn** [polkadot-js/apps#8427]
Right now! I am unable to upload an ink! contract which is even an flipper contract (as hello-world contract project of ink!). I informed an error like on web UI of apps

![Screenshot from 2022-11-27 11-06-25](https://user-images.githubusercontent.com/43272387/204118759-e90a80e4-c5d2-494c-9bed-7a60626cf114.png)

createType(Call):: Call: failed decoding contracts.instantiateWithCode:: Struct: failed on args: {"value":"Lookup115","gas_limit":"Lookup82","storage_deposit_limit":"Option<Compact<u128>>","code":"Bytes","data":"Bytes","salt":"Bytes"}:: Struct: failed on gas_limit: Compact<u64>:: Unable to construct number from multi-key object

**Comment by xiaozeplus** [comment]
hello, I met the same problem just like you, have you solved it?

**Comment by donhuanvn** [comment]
As a temporary solution, I use an older version of apps: https://github.com/polkadot-js/apps/tree/v0.121.1
