### ISSUE TITLE
Unable to decode storage system.events

### ISSUE THREAD

**Issue by yashirooooo** [polkadot-js/apps#8431]
RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.events:: createType(Vec<EventRecord>):: Vec<EventRecord>:: Decoded input doesn't match input, received 0x0c0000000000000090d29d090000000002000000010000000f0629aea6020000000000000000000000000000010000000001032000c0769f0b00000000000000 (64 bytes), created 0x0c0000000000000090d29d090000000002000000010000000f0629aea6020000…000000000000000000010000000001032000c0769f0b00000000000000000000 (67 bytes)

**Comment by yashirooooo** [comment]
with api version 9.7.1

**Comment by jacogr** [comment]
Which chain, which block?

**Comment by yashirooooo** [comment]
> Which chain, which block?
> 
> EDIT: This doesn't seem to be related to the apps UI since that is on 9.9.4 atm. So also, which environment (since it is logged in the apps repo)

This is my own local chain based on substrate 3.0.0, the error occurs in the block that contains cross-chain transactions.

**Comment by yashirooooo** [comment]
> For custom chains, you most probably need to apply custom types. The JS API only tracks Polkadot & Kusama types by default and manages those definitions. (For Substrate, it is always Substrate master itself).
> 
> Also check in on the recent Weight updates, e.g. for those the most recent API versions are required. (And per the api repo and the CHANGELOG there)

![image](https://user-images.githubusercontent.com/51014425/204698176-94108ff9-cb88-4a87-88b2-8d7d88cb05bc.png)
![image](https://user-images.githubusercontent.com/51014425/204698252-ac4a440f-3f11-4ef4-a209-1e66c9566b87.png)
![image](https://user-images.githubusercontent.com/51014425/204698707-5f7f8676-a39f-4fcd-bfff-631c3e9b251a.png)

But this happens in the event of the system in the event of an error, there is no parsing error when the transaction is successful

**Comment by jacogr** [comment]
Mismatched historic types in case of errors. Typically DispatchError, where the structure has changed in Substrate. 

For instance on Kusama/Polkadot there is an override to point to the old types for historic blocks (based on the runtime version where it went live) - https://github.com/polkadot-js/api/blob/7b5b8745a2af68f365987caccd922d01c813304f/packages/types-known/src/spec/kusama.ts#L13

The same would need to apply to other chains, depending on when the conversion of old -> new took place.
