### ISSUE TITLE
Fast-track button on pop-up is always disabled

### ISSUE THREAD

**Issue by laboon** [polkadot-js/apps#8440]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Even if a valid Technical Committee account exists and valid parameters are entered, the button to submit a fast-track remains disabled. It should be enabled once valid parameters are entered and if the account is a valid TC account.

Issuing the extrinsic from the same account and same parameters via the Extrinsics tab seems to works, which makes me think the issue is on the UI side.

* **What is the motivation for changing the behavior?**

To be able to submit fast-track requests without issuing raw extrinsics.

* **Please tell us about your environment:**

  - Version: Parity Polkadot v0.9.33, api v9.9.4, apps v0.122.3-61
  - Environment: Tried on Chrome and Brave

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Which chain? (e.g. Polkadot is is available for me as a TC signatory)

**Comment by laboon** [comment]
> Which chain? (e.g. Polkadot is is available for me as a TC signatory)

I tried this on Polkadot. Not sure if this is relevant to the fix or not.
