### ISSUE TITLE
Named scheduled tasks not showing their names on Event Calendar

### ISSUE THREAD

**Issue by laboon** [polkadot-js/apps#8442]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Named scheduled tasks (such as `auctlpNNN`, for the named auction events) are no longer showing on the Event Calendar. Rather, a hexadecimal string is displayed. See attached image below.

This happens on both Polkadot and Kusama.

* **What is the motivation for changing the behavior?**

See names of named scheduled tasks

* **Please tell us about your environment:**

Web browser ( Checked on Brave and Chrome ) 

api v9.9.4
apps v0.122.3-62

Checked on Polkadot and Kusama; same behavior on both

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

<img width="924" alt="Screenshot 2022-11-29 at 11 16 40" src="https://user-images.githubusercontent.com/1417717/204515499-7d9b814b-7ef8-4cd3-9a81-0a1250affae4.png">

**Comment by jacogr** [comment]
Yes, this is known - it also shows up that way in the actual Democracy -> Dispatch queue. (Yet another bounded call conversion issue.) 

It will probably only be fixed alongside https://github.com/polkadot-js/apps/issues/8340 & https://github.com/polkadot-js/apps/issues/8339 (going to merge it into the first)

**Comment by jacogr** [comment]
Closing in favor of #8340 (which received a specific comment on this)

**Comment by jacogr** [comment]
Just an update. With the new scheduler, the name/id is actually hashed. So it is non-reversible. See

```rust
fn schedule_named(
		id: Vec<u8>,
		when: DispatchTime<T::BlockNumber>,
		maybe_periodic: Option<schedule::Period<T::BlockNumber>>,
		priority: schedule::Priority,
		origin: T::PalletsOrigin,
		call: CallOrHashOf<T>,
	) -> Result<Self::Address, ()> {
		let call = call.as_value().ok_or(())?;
		let call = T::Preimages::bound(call).map_err(|_| ())?.transmute();
		let name = blake2_256(&id[..]);
		Self::do_schedule_named(name, when, maybe_periodic, priority, origin, call).map_err(|_| ())
	}
```

This is due to the move of the id field to `[u8; 32]` to be bounded.
