### ISSUE TITLE
Account "disappears" from display after being added by Parity Signer 5.0.0

### ISSUE THREAD

**Issue by laboon** [polkadot-js/apps#8465]
- [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Accounts created by Parity Signer 5.0.0 don't stay on the Accounts screen after refresh/re-starting browser.

TO REPRODUCE:
0. Ensure you are using Parity Signer 5.0.0. Generate a new account.
1. Add account via "Add via QR" on Polkadot-JS App (https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/accounts)
2. Scroll to bottom of page and notice new account is the last account listed
3. Refresh screen
4. Scroll to bottom of page again

EXPECTED BEHAVIOR:
Account exists on Accounts Page

OBSERVED BEHAVIOR:
Account does not exist on Accounts page

Note: I looked at localStorage and saw that the address of the added account was there; it just wasn't being displayed for some reason.

Previous accounts were added with v4.5.3 and work fine.

* **What is the motivation for changing the behavior?**

Ensure that accounts can be used after restart

* **Please tell us about your environment:**

  - Version:
Parity Polkadot v0.9.33
api v9.9.4
apps v0.122.3-70

  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

**Comment by laboon** [comment]
I tried this with two different computers and had the same result.

**Comment by laboon** [comment]
Confirmed that new accounts created and added with v4.5.3 work.

**Comment by jacogr** [comment]
If it is still in storage but gone after a refresh, check the genesisHash. It could very well be that there has been some changes that are not catered for. (If incompatible changes, would need to have a rethink on these, since we can only support one style of QR at a time)

**Comment by laboon** [comment]
This only seems to occur on Kusama, and only on certain computers. There's also a report on Reddit on something similar happening: https://www.reddit.com/r/Polkadot/comments/zj81zb/accounts_keep_disappearing/

I'll check the genesis hash on the different computers today and get back to you, thanks.

**Comment by laboon** [comment]
It looks like the genesis hash on the computer where it's disappearing is showing the Polkadot genesis hash, not the Kusama one, even though we created a Kusama account. So this makes sense, it is likely a Parity Signer problem. I'm going to check with the people whose computer it doesn't work on today, and will close this if that is the case.

**Comment by jacogr** [comment]
Weird. I tested 5.0 with Polkadot accounts and all was ok. Will also import some for Kusama.
