### ISSUE TITLE
Diacritics not fully supported when displaying an account identity

### ISSUE THREAD

**Issue by Marcin-Radecki** [polkadot-js/apps#8498]
* **I'm submitting a ...**

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

At the moment characters with diacritics are not fully supported, and not displayed correctly, e.g. `ö` character is missing.

The issue affects at least the Accounts tab, and all places where an account's identity is displayed. 

![image](https://user-images.githubusercontent.com/3909333/206186903-0cbc2611-ce91-40ff-a146-7ad460ddb886.png)

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version: apps v0.122.3-85
  - Environment: Ubuntu 20.04

    - [ ] Node.js
    - [X] Browser (Firefox 107.0 (64-bit))
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
All unicode is removed - unless an identity is verified. This is by design to -

- protect against spammers
- not having a Joseph's technicolor dreamcoat (unless verified)
