### ISSUE TITLE
New slashing logic not working

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/apps#8505]
Seems like https://github.com/polkadot-js/apps/issues/8298 is not really fixed. 

See the recent slashes on kusama: 

<img width="1728" alt="Screenshot 2022-12-09 at 01 26 34" src="https://user-images.githubusercontent.com/5588131/206602175-2ddaf70c-8903-48ca-8d86-4814e46ef314.png">
<img width="1728" alt="Screenshot 2022-12-09 at 01 26 42" src="https://user-images.githubusercontent.com/5588131/206602183-8b1c740a-0b69-4801-84b6-f7d5a01a05aa.png">

**Comment by jacogr** [comment]
That is beyond weird, the last batch did show.
