### ISSUE TITLE
Kusama era countdown is wrong

### ISSUE THREAD

**Issue by GopherJ** [polkadot-js/apps#8511]
![image](https://user-images.githubusercontent.com/33961674/206829511-44095e50-58fc-4f8b-994c-c3bc4c9e442a.png)

**Comment by jacogr** [comment]
There has been no new validator selection, at this point eras are stuck. This is due to a large slashing event. Referendum 16 aims to resolve the on-chain issue.

**Comment by kianenigma** [comment]
Yes this is all expected.

**Comment by jacogr** [comment]
Closing, asked & answered.
