### ISSUE TITLE
Parameters with two or more nested `Option` types can't be supplied

### ISSUE THREAD

**Issue by sea212** [polkadot-js/apps#8528]
* **I'm submitting a ...**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

When calling an extrinsic, any parameter with a type that has at least two nested `Option` enums cannot be supplied. Two screenshots will follow, that show the parameter in apps before it is enabled and after it is enabled.

Before enabling:
![cannot_provide_data_before_include_option](https://user-images.githubusercontent.com/15378334/207324030-98939170-ac39-4fe7-b30b-d1b957cc565b.png)

After enabling:
![cannot_provide_data](https://user-images.githubusercontent.com/15378334/207324067-e86dcbc6-0443-4eb5-89f1-cbdb9fe73a03.png)

* **What is the motivation for changing the behavior?**

Providing extrinsic parameters is a core functionality that should work properly.

* **Please tell us about your environment:**
  - Version: v1.122.2
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

**Comment by jacogr** [comment]
It is tracked here https://github.com/polkadot-js/apps/issues/2233

**Comment by jacogr** [comment]
Closing as duplicate to clear the queue since it is already tracked (although it has not had eyes on or hands on the keyboard for a very long time now).
