### ISSUE TITLE
Look Inside `DispatchWhitelistedCallWithPreimage` Preimages

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#8543]
**I'm submitting a ...**

  - [ ] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

**What is the current behavior and expected behavior?**

There are a few connected things here that relate to the `WhitelistedCaller` track and the two referenda that are needed to pass something on it (one with the Fellowship and one with the public).

Some quick pseudocode (can see actual code in [opengov-submit](https://github.com/joepetrowski/opengov-submit)). We have some proposal. In a non-whitelist referendum, this would be the preimage, and its hash would be voted on in the referendum.
```js
let proposal = doSomething();
let proposalHash = hash(proposal);
```

But in a whitelisted referendum, we actually have a Fellowship referendum to _whitelist_ the call and a public referendum to _dispatch_ it.
```js
let whitelistCall = whitelist.whitelistCall(proposalHash);
let dispatchCall = whitelist.dispatchWhitelistedCallWithPreimage(proposal);
```

The _hashes of these two calls_ are the referenda being voted on, and therefore it is their preimages that need to be noted. Of course, they both "contain" the `proposal` in either a hash representation or a nested call, but `proposalHash` will never be registered as a preimage.

So we end up with a situation where it looks like these hashes correspond to some unknown preimage (ignoring the first one):
![image](https://user-images.githubusercontent.com/25483142/207790254-4b51f370-8c0f-4e02-afc2-bedf2480cc4f.png)

Let's look at `0xbcc...`. Here is its preimage:
![image](https://user-images.githubusercontent.com/25483142/207790657-5bf7e5dd-cc44-478a-be58-713d2732f4a2.png)

We even see that it has been requested, but is lacking a preimage or known length:
![image](https://user-images.githubusercontent.com/25483142/207790855-3090a7a0-148d-42b1-86fd-5772e62aaf8b.png)

However, the preimage is "there", under `0x6c8...`, it is just nested inside the dispatch call.
![image](https://user-images.githubusercontent.com/25483142/207791071-52357ac9-098a-41a0-8b2a-6adb926fb9e4.png)

And this `0x6c8...` is the referendum actually being voted on.
![image](https://user-images.githubusercontent.com/25483142/207791320-856ddb2c-8077-49e8-9407-9fddb47a1487.png)

So the preimage that has been whitelisted is on-chain, it is just wrapped in another call, obviously giving it another hash. When there is a whitelisted hash with no obvious preimage, the UI could look inside preimages that are specifically `DispatchWhitelistedCallWithPreimage` to see if the provided call is the one that is whitelisted.

**What is the motivation for changing the behavior?**

This would make it easier to track referenda that correspond to whitelisted calls, for example to know that the preimage for a whitelisted call has actually been noted on-chain.

**Comment by jacogr** [comment]
I was having similar thoughts yesterday when going through your latest proposal (the issue there was that the subsquare link didn't have all the info and the UI didn't make it easier). However, instead of going through it on a type basis (which then needs to be maintained), my thought was to actually show the hash for any `Call` types. So it ends up being generic instead on a per-inspection basis.

**Comment by jacogr** [comment]
Basically this (somewhat rough atm) -

![image](https://user-images.githubusercontent.com/1424473/207795518-f877d9af-dcdf-4790-b8d6-d50b2afb2dd2.png)
