### ISSUE TITLE
gov2 referenda decision curve graphs with date and time instead of blocknr

### ISSUE THREAD

**Issue by brenzi** [polkadot-js/apps#8572]
- [ ] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

The new decision curves for referenda are amazing! Yet, I think block numbers are not human readable and should only be supplemental information. UX would be much better if the x-axis would show date and time estimates.

**Comment by jacogr** [comment]
It is tricky on the axis. For past blocks you basically need to have the real timestamp (which is expensive to get), so estimations are not correct. For future, it can be calculated, but depending on when blocks come in would need a redraw.

The best middle-ground is most probably to just add it to the tooltip -

- for past blocks, no timestamp
- for future blocks, blockNumber + timestamp (estimated) + delay (i.e. 1 day 5 hrs)
