### ISSUE TITLE
gov2 referanda decision curve graphs could indicate confirmation phase ahead of start and estimated enactment time

### ISSUE THREAD

**Issue by brenzi** [polkadot-js/apps#8573]
- [x] Feature request

The graph no visualizes the time when the referendum will likely enter the passing state at current support. To indicate the confirmation period for the given track, another shaded area could be drawn starting at the estimated time the passing state starts to the end of the confirmation period. Even before a passing state has been reached

finally, indicating the estimated enactment blocknr, date and time would be massively helpful for submitters

**Comment by jacogr** [comment]
This will be displayed once we have https://github.com/polkadot-js/apps/issues/8566 - at that point can see if it makes sense to (additionally) add the displayed info to the graph.

I do think the shaded "confirmation period" could add value, i.e. not just the time-ticking as per the linked issue.

**Comment by jacogr** [comment]
Closing this for the graph part. The additional info display is tracked in the linked issue.
