### ISSUE TITLE
Color is not reflecting for our parachain

### ISSUE THREAD

**Issue by ashi20192020** [polkadot-js/apps#8580]
Hi,

Our testnet parachain Ethos has just onboarded on PolkadotJs. Here is the link https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fethos.jur.io#/explorer

We have made changes at all required places. Here is PR https://github.com/polkadot-js/apps/pull/8571

I thought color would get reflected once it would become live.  Can somebody please help?

**Comment by jacogr** [comment]
The chain is detected as a local testnet. This is the same reason why the "dev accounts" are available. So the default color is always applied to dev chains.

The detection checks for -

- is the chain type Development, or
- is the chain type Local, or
- does the chain have "Testnet" is the name (there h\is some historical reasoning behind this one, not 100% sure it is applicable at the end of 2022)

The checks are done here - https://github.com/polkadot-js/apps/blob/45aaccf699b7a9ccf75890040685ddf49154f14e/packages/react-api/src/Api.tsx#L188

In this case the specific deployment matches 2 of the above criteria - it is `Local` and contains `Testnet`
