### ISSUE TITLE
Why this type can not be decode?

### ISSUE THREAD

**Issue by AurevoirXavier** [polkadot-js/apps#8591]
> https://substrate.stackexchange.com/questions/6219/why-this-type-can-not-be-decode

I didn't get any helpful answers from StackExchange.
So, I open an issue here.
Sorry for this.

Is there any way to decode this? Thanks.
I don't know how to make my front end works.

**Comment by jacogr** [comment]
So the “Bytes” part of the input means that is come back in the metadata as “Vec<u8>”. (The “(Vec<DepositId>)” is the type name. 

You didn’t specify a chain or the actual code link, so cannot quite comment further. 

The first would indicate (with metadata retrieval) the actual type definition, ie. You can see what is returned and linked (also in the UI). The second will show the actual definition from Rust.

**Comment by AurevoirXavier** [comment]
> You didn’t specify a chain or the actual code link, so cannot quite comment further.

The original definition: https://github.com/darwinia-network/darwinia-2.0/blob/08b703a75e657a120b6701a5781bdbbd88e6a617/pallet/deposit/src/lib.rs#L59

The associated type: https://github.com/darwinia-network/darwinia-2.0/blob/08b703a75e657a120b6701a5781bdbbd88e6a617/pallet/staking/src/lib.rs#L66

And it was used in this storage item: https://github.com/darwinia-network/darwinia-2.0/blob/08b703a75e657a120b6701a5781bdbbd88e6a617/pallet/staking/src/lib.rs#L128

It's a little bit like `NegativeImbalance` in Substrate. Maybe you are familiar with that.

**Comment by jacogr** [comment]
Which network is this? (You guys have a couple, hence asking - would like to pull the metadata and look at the type definitions in the metadata alongside)

**Comment by jacogr** [comment]
Ok, all good. Cann see the reason from the first link. 

`pub type DepositId = u8;`

So it will treat it as the normal `Vec<u8>` handling in the apps UI, e.g. as a `Bytes` type.
