### ISSUE TITLE
Legacy conviction voting lockups displaying for OpenGov

### ISSUE THREAD

**Issue by adamsteeber** [polkadot-js/apps#8597]
* **I'm submitting a ...**

  - [x] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Currently, the UI displays legacy lockup periods based on a constant of `115200` blocks (8 days) from `api.consts.democracy.voteLockingPeriod`. [According to these substrate code comments](https://github.com/paritytech/substrate/blob/master/frame/conviction-voting/src/conviction.rs#L43), this should be specific to each track depending on the respective track's `enactmentPeriod`.

I believe the issue comes from the `createOptions` function [found here](https://github.com/polkadot-js/apps/blob/master/packages/react-components/src/ConvictionDropdown.tsx#L26).

* **What is the motivation for changing the behavior?**

Many voters vote with no conviction because they are being misled about the duration of the lock ups. If users knew that a 6x conviction vote only locked their tokens for 32x the enactment period (as little as ~6 hours for an enactment period of 10 minutes), they may be motivated to increase their conviction.

* **Please tell us about your environment:**

  - Version:
    - api v9.10.3
    - apps v0.122.3-145

  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Yes, it is incorrect. Do also look at this - https://github.com/paritytech/substrate/blob/master/frame/conviction-voting/src/lib.rs#L460-L463
