### ISSUE TITLE
Failed to query StorageMap with BoundedVec as its key type

### ISSUE THREAD

**Issue by kaichaosun** [polkadot-js/apps#8612]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Currently, if the key of StorageMap is `BoundedVec`, the query result of storages in `Chain State - Storage` page returns unknown with key provided. 

The expected behavior is when provided with correct key the result should be data storage corresponding to the key.

Note: when not provide key, all the result is returned which is expected.

* **What is the motivation for changing the behavior?**

There is use cases to use polkadot.js/apps to query storage map with key type is BoundedVec.

* **Please tell us about your environment:**

Reproduce: compile [a substrate chain](https://github.com/kaichaosun/play-substrate), the [storage code](https://github.com/kaichaosun/play-substrate/blob/master/pallets/poe/src/lib.rs#L41)
Submit poeModule -> createClaim extrinsic with `0x01`
Query poeModule -> proofs with `0x01`.

Error in console:
```
react_devtools_backend.js:4012 2022-12-23 18:44:46             VEC: Unable to decode on index 0 createType(Lookup121):: Bytes: required length less than remainder, expected at least 258, found 3
```

  - Version: Substrate polkadot-v0.9.30
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [x] Other

**Comment by jacogr** [comment]
Is there a running chain that exhibits this that I can point the UI to?

**Comment by kaichaosun** [comment]
@jacogr here it is https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fplay-substrate.threechain.xyz#/explorer

**Comment by jacogr** [comment]
This is the PR that introduced the breakage - https://github.com/polkadot-js/apps/pull/8336

Basically the input key is encoded as `Option<Bytes>`
