### ISSUE TITLE
Not being able to close finalised motions

### ISSUE THREAD

**Issue by oshakarishvili** [polkadot-js/apps#8638]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* The motions are not able to be closed via council > motions 

It is not possible (from any user nor from Council) to sign a call and close already closed/approved motions on Polkadot. ![image](https://user-images.githubusercontent.com/71079600/209667301-6554f1a7-f7ac-424f-9819-3277a3272d19.png)

  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

Thanks!

**Comment by GuruKathryn** [comment]
Having the same problem with 3 different runtime versions tested running as a local production node (substrate Kitchen Sink, no changes) - one from August, one from the first week of December and one with all changes up to January 2nd. This is one of several problems with the JS that we are experiencing. Tried clearing the browser and restarting the JS, errors became more complex. Are we missing something simple here? Operator error?
