### ISSUE TITLE
Storing accounts client side

### ISSUE THREAD

**Issue by faboweb** [polkadot-js/apps#870]
It looks like you guys are creating accounts client side in the browser and store them in local storage (encrypted). Is that considered safe? Is that only available on testnets?

**Comment by jacogr** [comment]
So couple of steps -

- waiting on external QR signer integration, which then becomes default
- waiting on (thee are 2 WIP) bowser extensions for signer integration
- storing will only be available for desktop app (as available)

For a non-value-bearing testnet, it works, but no way this method is going to survive until network launch.
