### ISSUE TITLE
Decoding encoded call with Balance type breaks in submission tab

### ISSUE THREAD

**Issue by arrudagates** [polkadot-js/apps#8736]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

After the introduction of formatted balance in the extrinsics page, the interaction between `Decode` and `Submission` tab is now broken, if you try and decode a call that contains a balance type where the amount is below a base unit, it will be displayed correctly in the `Decode` tab with the appropriate unit (e.g. micro)**
![image](https://user-images.githubusercontent.com/30242466/211314556-df5cc4a0-20e4-4118-b8dd-052f6ea62c22.png)

But when you switch to the `Submission` tab to send the extrinsic, the balance type fields get messed up by resetting to the base unit. This is not just a visual issue, as it's evident in the call data that the fields were actually changed.
![image](https://user-images.githubusercontent.com/30242466/211314756-9167855d-6427-4cb9-8652-a777437822e2.png)

**Although they get displayed with the correct unit, they also get trimmed out of relevant digits, example: 27241615 will become 27.2416 micro units rather than 27.241615 micro units, but this appears to be only a visual issue, so it's not affecting usage.

* **Please tell us about your environment:**

  - Version:
      api v9.11.1
      apps v0.122.3-242

  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

**Comment by jacogr** [comment]
Do you have a specific encoded call + chain as a testcase?

**Comment by jacogr** [comment]
Reproduction here - https://github.com/polkadot-js/apps/issues/8743#issue-1526960713
