### ISSUE TITLE
Can't click multisig pending approvals

### ISSUE THREAD

**Issue by andresilva** [polkadot-js/apps#8759]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Whenever a multisig account has a pending approval a tooltip shows this information. I can't click on the link to view pending approvals as the tooltip disappears when I try to hover it. 

[Screencast 2023-01-11 11:07:43.webm](https://user-images.githubusercontent.com/123550/211791237-4649f028-c23f-4c0d-bf0f-7632f16367c5.webm)

I'm using Firefox, haven't tested on other browsers.

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser - Firefox
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Fuck. Same happens with proxies as well.
