### ISSUE TITLE
Fill extrinsic submission form from hex decoded call

### ISSUE THREAD

**Issue by bkontur** [polkadot-js/apps#8761]
* **I'm submitting a ...**

  - [X] Feature request

* **What is the current behavior and expected behavior?**
Lets say I have decoded hex call e.g.: `0x00081448656c6c6f` it is `system::remark_with_event('Hello')`, and I want to submit this extrinsic via `polkadot.js.org/apps` or if I have a very long long complicated decoded call. How could I easily do that now?

Under menu "Extrinsic -> Decode" we can insert hex decoded call and it displays the whole calls. Maybe easiest solution could be to add here button "Go to submission", where the form will refilled according to the hex decoded call.

![image](https://user-images.githubusercontent.com/8159517/211807338-7c87549a-a271-49e8-999a-53866652e0c6.png)

* **What is the motivation for changing the behavior?**
e.g. easier testing or supporting ...

**Comment by jacogr** [comment]
Just click on the submission tab after decoding.

**Comment by bkontur** [comment]
wow, thank you, how come I've never realised that :D :D :D
