### ISSUE TITLE
`Governance -> Council` Can't render component(s)

### ISSUE THREAD

**Issue by peterwht** [polkadot-js/apps#8788]
* **I'm submitting a ...**

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
After proposing a motion on the Governance -> Council -> Motion page, and refreshing the page, the following error is thrown and the Motion page is not rendered properly. 
```
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

can't access property "preimages", o.query.democracy is undefined
41014/k_<@https://polkadot.js.org/apps/main.b398f24e.js:2:2014472
Sa@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:151026
Cl@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:207985
bc@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:196969
vc@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:196897
mc@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:196758
ic@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:193565
oc@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:192120
S@https://polkadot.js.org/apps/other.01.4dbc5763.js:2:184902
I@https://polkadot.js.org/apps/other.01.4dbc5763.js:2:185433
77830/t.exports@https://polkadot.js.org/apps/other.01.4dbc5763.js:2:44937
@https://polkadot.js.org/apps/other.01.4dbc5763.js:2:58808
m@https://polkadot.js.org/apps/other.01.4dbc5763.js:2:58665
w@https://polkadot.js.org/apps/other.01.4dbc5763.js:2:58687
```
Also, on Governance -> Council -> Overview, the council members balances show "0.0" (which is incorrect). 
<img width="1778" alt="Screen Shot 2023-01-13 at 11 32 10 AM" src="https://user-images.githubusercontent.com/23270067/212393756-448de3db-bcf8-4b96-9c5e-b70fa89a7b31.png">

When pressing the dropdown arrow next to the account, the following error is thrown:
```
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

can't access property "map", a() is undefined
41014/CF</r<@https://polkadot.js.org/apps/main.b398f24e.js:2:1751404
41014/CV</y<@https://polkadot.js.org/apps/main.b398f24e.js:2:1665899
Qa@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:155407
83426/t.useMemo@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:449535
41014/CV<@https://polkadot.js.org/apps/main.b398f24e.js:2:1665887
Sa@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:151026
Bs@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:162647
Cl@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:208852
bc@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:196969
vc@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:196897
mc@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:196758
ic@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:193565
lc@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:193954
Uo@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:134872
52967/rc/<@https://polkadot.js.org/apps/react.01.dd20e7c4.js:2:191506
```
The expected behavior is that motions are displayed on the Motion page, and that the Councillors accounts are properly displayed.

Oddly, yesterday (Jan. 12th, 2023), the Motions page was working fine. However, the Overview page was showing the accounts incorrectly.

* **Please tell us about your environment:**

Chain info:
- Local chain, deployed via zombienet
- has pallet-collective (Council)
- has pallet-membership
- No pallet-democracy
- has pallet-preimage
- follows `polkadot-v0.9.30`

Computer info:
- MacOS 12.6
- Browsers used: Firefox Dev Edition, Brave Browser (same results on both)

I am not using a local version of Polkadot.js. I am connecting to the local chain via polkadot.js.org/apps

**Comment by jacogr** [comment]
Council (governance 1) is tied to the usage of democracy, specifically the for the use of preimages.

You are welcome to submit a PR to break that dependency, but it is not something I will do since there are no actual chains in that format (as of yet). 

Votes are from the phragmen elections pallet.

**Comment by peterwht** [comment]
Thank you for the quick reply!

Before today, the Motion tab was working great, without democracy. We are working (with) a chain that will use a simplified governance.  I.e., Council but no Democracy.

Am I right to assume that the following commit is what started causing the issues today?
https://github.com/polkadot-js/apps/commit/20bc11708d52a968ef387262747f51a142fa859a

**Comment by jacogr** [comment]
I believe so, yes. So in your case it _might_ be as simple as 

https://github.com/polkadot-js/apps/commit/20bc11708d52a968ef387262747f51a142fa859a#diff-34833ff74c0746db8d25a7d82ef9e06a997137340a5136c1437a357b369e623cR34

`api.query.democracy.preimages` -> `api.query.democracy?.preimages` (Obviously this can only be verified against a cn actual chain)

(The above was made for proposals on Acala, Karura, Polkadot, Kusama ... others not quite showing up)

**Comment by peterwht** [comment]
Perfect. I appreciate that.

I will clone polkadot.js and see if that change fixes it locally.

**Comment by peterwht** [comment]
Just opened a PR with two small changes. Everything seems to work as expected for chains with and without Democracy.

**Comment by jacogr** [comment]
Closing. The linked PR was merged, thank you for that. (Please do keep them coming or ask if you do find incompatibilities with configs that are not found elsewhere)

**Comment by peterwht** [comment]
PR was locked. So I will continue conversation here. 

I got the chance to check just now. The Motion page only displays the proposal hash. Not the entire proposal.

![Screen Shot 2023-01-16 at 10 53 18 AM](https://user-images.githubusercontent.com/23270067/212740374-96f9067e-a63c-4b9e-9a32-840bb4dc89e2.png)

**Comment by peterwht** [comment]
I guess it is worth mentioning that we do not expect that preimages will always be used for motions. So, the preimage hook is not (always) going to pull the proposal. Sometimes causing just the proposal hash to be displayed.
