### ISSUE TITLE
Mobile menu toggle -> hide / show on scroll

### ISSUE THREAD

**Issue by rossbulat** [polkadot-js/apps#880]
The menu toggle is currently overlaying content in addition to the tabs when they are scrolled:

<img width="190" alt="Screenshot 2019-04-02 at 21 45 48" src="https://user-images.githubusercontent.com/13929023/55407531-b31a2f00-5590-11e9-8339-09183b082edc.png">
<img width="175" alt="Screenshot 2019-04-02 at 21 45 29" src="https://user-images.githubusercontent.com/13929023/55407537-b44b5c00-5590-11e9-901c-a44118aee289.png">

Proposed solution:

* the icon to be hidden by default
* scroll up the page, icon shows
* scroll down the page, icon hides
* wrap the icon in a HOC that injects this behaviour, HOC could potentially be used elsewhere in the future.

Not dissimilar to the behaviour in this jQuery implementation: http://jsfiddle.net/mariusc23/s6mLJ/31/

**Comment by rossbulat** [comment]
Combine behaviour with tabs in #879

**Comment by jacogr** [comment]
Closing as part of issue cleanups, the overlays are not applicable anymore.

<img width="491" alt="Polkadot:Substrate Portal 2019-06-04 17-56-17" src="https://user-images.githubusercontent.com/1424473/58894354-2277e080-86f2-11e9-874b-134b5850ac0e.png">
<img width="498" alt="Polkadot:Substrate Portal 2019-06-04 17-55-58" src="https://user-images.githubusercontent.com/1424473/58894355-23107700-86f2-11e9-8c88-63dd1c4d7de8.png">
