### ISSUE TITLE
Polkadot js app is connecting to WSS with invalid TLS certificate

### ISSUE THREAD

**Issue by 3h4x** [polkadot-js/apps#8834]
- [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Using polkadotjs with wss://dev.net.t3rn.io works
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fdev.net.t3rn.io#/collators

But dev.net.t3rn.io is simple CNAME to ws.t0rn.io, where ws.t0rn.io endpoint doesn't have valid TLS certificate for dev.net.t3rn.io

Console logs doesn't show anything too.

I would expect that polkadot.js either won't work or will show that TLS certificate is not matched.

* **Please tell us about your environment:**

My testing setup is chrome and wscat.
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fdev.net.t3rn.io#/collators

<img width="1096" alt="Screenshot 2023-01-17 at 14 47 10" src="https://user-images.githubusercontent.com/6998565/212915266-ce9e6344-c667-44e9-bd09-34edfe069983.png">

**Comment by jacogr** [comment]
There is nothing we do with TLS. The wss connection is made straight with the built-in browser `WebSocket` object.

I would suggest that the deployment gets updated.
