### ISSUE TITLE
Decoder no longer accepts full blobs

### ISSUE THREAD

**Issue by carlosala** [polkadot-js/apps#8837]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Until 9c4cbfcd67311b97a7aa7def48b315b2b7eda2c2, we were able to input in the decoder a full transaction blob, which included both `Call` and also spec version, tx version, etc.
Now, it only accepts the `Call` hex-encoded type.

* **What is the motivation for changing the behavior?**

It'd help us in order to test the Ledger integrations, as we test directly the whole blobs that get to the Ledger to see which call is in it and if we are parsing properly.

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by carlosala** [comment]
[This](https://github.com/polkadot-js/apps/blob/5eec74f1172ac0f94e8e6ce0678c4c771117b1dc/packages/page-extrinsics/src/Decoder.tsx#L77) is the problematic line, as obviously decoded is only using the first part of the blob, and not all the characters.

**Comment by jacogr** [comment]
If you follow the logic there -

1. it first tries to decode as an extrinsic, if that fails
2. try to decode as a call

The line you pointed to is when both fails.

To, here is an actual recent transaction - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot.public.curie.radiumblock.co%2Fws#/extrinsics/decode/0x05030016991bfe44c8dce7569a74ce7a168fb2d4d176e90e754d4e8a92d26d4870dc600740b149df12

**Comment by jacogr** [comment]
Ahhh, I see what you mean - you want to pass extra characters in. That is quite problematic. (And ended up in the previous position where we ended up decoding invalid stuff without knowing about it... which is why the check was added)

**Comment by carlosala** [comment]
@jacogr for us would be quite interesting to be able to do it. If it makes a lot of trouble, we'd try to make some workaround

**Comment by jacogr** [comment]
We need strict checks. 

If you wish to also supply transaction payloads, we would need an explicit decoding step for that in the above code block. (Also strictly failing like the others if the end result is problematic)

**Comment by carlosala** [comment]
Ok, thanks for the clarifying explanation. We'll go for it

**Comment by jacogr** [comment]
It would be interesting to have a payload decoder in there - it can also display extra info from the actual payload, as submitted.

**Comment by carlosala** [comment]
That would be amazing!!!

**Comment by jacogr** [comment]
This _may_ do the trick (will obviously need testing against actual payloads)...

```js
try {
          // cater for an extrinsic input...
          decoded = api.tx(hex);
          // cater for an extrinsic input
          const tx = api.tx(hex);

          // ensure that the full data matches here
          assert(tx.toHex() === hex, 'Cannot decode data as extrinsic, length mismatch');

          decoded = tx;
          extrinsicCall = api.createType('Call', decoded.method);
          isCall = false;
        } catch {
          try {
            // attempt to decode as ExtrinsicPayload
            const payload = api.createType('ExtrinsicPayload', hex);
            
            extrinsicCall = api.createType('Call', payload.method.toHex());
            isCall = false;
            
            assert(payload.toHex() === hex, 'Unable to decode data as ExtrinsicPayload');
          } catch {
            // attempt to decode as Call
            extrinsicCall = api.createType('Call', hex);

            // ensure we used all bytes (as we did above)
            assert(extrinsicCall.toHex() === hex, 'Unable to decode data as Call, length mismatch in supplied data');
          }
        }
```

**Comment by carlosala** [comment]
That does not make it I think.
Blobs that ledger sign are built as follows
```typescript
Buffer.from(payload.toU8a(true)).toString('hex')
```
where payload is a `ExtrinsicPayload` type

**Comment by carlosala** [comment]
obviously then we need to add the `0x` at the beginning

**Comment by carlosala** [comment]
I tried that in development and does not work I think. Could you give it a try? You can get correct blobs in https://github.com/Zondax/ledger-polkadot/blob/6f5b914f811ababa599c0b18fb860b247a7db0c9/tests/testcases_previous.json

**Comment by carlosala** [comment]
which are for polkadot 9340, the current version

**Comment by jacogr** [comment]
Arg, yes, now I see the `toU8a(true)` - this is different from the "normal" `ExtrinsicPayload` usage where the method is actually length-prefixed. So we actually need 2 steps for that version -

0. try and normal `ExtrinsicPayload` (passed to every _except_ Ledger), if not ...

1. just parse as a call
2. add a call length
3. re-parse again to ensure everything is there
4. check if all is ok
