### ISSUE TITLE
Account for Alliance Migration in UI

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#8841]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Expected: Show the Alliance members on the Collective Parachain

Current: Hanging on
![image](https://user-images.githubusercontent.com/25483142/213229600-c5ab212d-5237-40c1-8d67-46100f808da3.png)

* **What is the motivation for changing the behavior?**

I imagine that the cause of this problem is https://github.com/paritytech/substrate/pull/12730

**Comment by jacogr** [comment]
Not quite a bug - an enhancement for the new pallet. (Really unsure when I'll be able to get to take a look at this)
