### ISSUE TITLE
Improve balance input field - allow decimal, change w/dropdown

### ISSUE THREAD

**Issue by kwingram25** [polkadot-js/apps#886]
Some improvements I'm going to work on for the balance input field used in most places, open to feedback:

- Default to DOT instead of confusing femto, milli etc.
- Change to incrementable number input (defaulting to increment of 1?)
- When changing units with a number already inputted, calculate the number in the new unit and automatically change it
- Allow decimal use (possibly only on DOT or above to avoid confusion? potential issues over diff uses of , and .)

**Comment by jacogr** [comment]
It looks spot-on. InputNumber/InputBalance have been some of my personal bugbears, they work, but boy, do they try hard to make it as difficult as possible for users. 

If we can swap the input type there to a number (and allow huge inputs >2.53 -1 without crashes, it will be absolutely great as well - hacking your own, like it is, just ends up being, er, non-optimal.)
