### ISSUE TITLE
[Nominate Selected] button greyed out

### ISSUE THREAD

**Issue by dcolley** [polkadot-js/apps#8889]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

As a token holder, I want to nominate validators using polkadot.js/apps

* **What is the motivation for changing the behavior?**

  - Checkboxes are not visible
  - Nominate selected is greyed out

![image](https://user-images.githubusercontent.com/1845970/215324566-d242076f-6358-42e8-83a8-3a640c95755a.png)

* **Please tell us about your environment:**
Chrome 109.0.5414.119 on macOs 13.2

  - Version:

![image](https://user-images.githubusercontent.com/1845970/215324671-bebe4057-58d3-4776-9c67-12869076409a.png)

  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by dcolley** [comment]
Also tested on Safari and Firefox - same issue

**Comment by dcolley** [comment]
It seems pjs now needs the user to create a Nominator account (with corresponding controller) for this feature to work.
This is a new behaviour - we have nominated validators in the past and we don't "Nominator" accounts set up

**Comment by jacogr** [comment]
It need a controller for nominations.  

(It is not new behavior - staking has been stagnant and unchanged for the last 6+ months with only minor fixes to cater for new runtimes)

**Comment by dcolley** [comment]
thanks for the clarification!
