### ISSUE TITLE
PolkaStats not longer offering Westend block explorer

### ISSUE THREAD

**Issue by JuanCDe** [polkadot-js/apps#8903]
* **I'm submitting a ...**
  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
For each account in the [Account tab](https://polkadot.js.org/apps/#/accounts) several block explorers are listed under "external links".

PolkaStats is linked to inspect the account on the Westend network, but this site is not currently offering any Westend block explorer, leading to a dead end.

![image](https://user-images.githubusercontent.com/107199769/215812464-5ae49e08-54c5-450c-8461-4c4b1d61df17.png)

  - Environment:

    - [ ] Node.js
    - [X] Browser
    - [ ] Other (limited support for other environments)

**Comment by jacogr** [comment]
The specific teams are meant to mange these - will remove it completely due to not being maintained by the team.
