### ISSUE TITLE
Issue with recent Polkadot.js update on SNOW Network

### ISSUE THREAD

**Issue by sharma66mahesh** [polkadot-js/apps#8926]
- [x] Bug report

* **What is the current behavior and expected behavior?**
* The new version of the [polkadot.js UI](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fsnow-rpc.icenetwork.io#/explorer) pointing to SNOW Network RPC node throws error while displaying a block that has an ink contract deployed. Additionally, it seems to be unable to decode system events.

It was working fine until the last release of polkadot-js/apps v0.123.1. 
Digging in, looks like the issue started to show up after the polkadot-js/apps started using @polkadot-js/api v9.13.1.

  - Version: > v0.123.1
  - Environment:
    - [x] Browser

![Screenshot from 2023-01-31 12-38-58](https://user-images.githubusercontent.com/24717327/215689004-ecc97870-e2e6-4446-a8bb-d62424b7e3d7.png)
![Screenshot from 2023-01-31 12-39-04](https://user-images.githubusercontent.com/24717327/215689014-5dbf1056-c03f-4efe-b266-b6ee94f0e0b0.png)

**Comment by jacogr** [comment]
Taking a quick look at the chain types, this would seem to be an old Weight 1.5 (weight mid-point conversion) chain. If that is the case, it could be that this would alleviate the issue - https://github.com/polkadot-js/api/pull/5465

**Comment by sharma66mahesh** [comment]
Thanks for taking a look at this issue.
The PR seems to have fixed the issue with parsing system events.

However, there seems to still be the issue with ink contracts. 
To reproduce, you can try to go to [this link](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fsnow-rpc.icenetwork.io#/contracts) and try to deploy an ink contract

The following error messages can be seen in the browser console, as the browser window goes blank
![image](https://user-images.githubusercontent.com/24717327/216572849-8100d89e-9bf8-4861-b75f-3ce4aeebc467.png)

**Comment by jacogr** [comment]
There is nothing that can be done on that. Basically we have a `Compact<struct>` definition which previously we hacked around for 1.5.
 
![image](https://user-images.githubusercontent.com/1424473/216597554-247df727-2040-4a77-a74a-811f4c43b243.png)

`Compact<*>` is only supported on numbers - in the case of `Weight 1.5` it is applied on a structure.

**Comment by jacogr** [comment]
Closing. For 1.5 chains the `Weight1.5` seems to be rendered as `Weight1` now, e.g.

![Uploading image.png…]()
