### ISSUE TITLE
[Bug] Proxied account not using proxy account for signature

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/apps#8990]
Hi Jaco, this is a bug that seems to have started 1 or 2 days ago I think.

Currently, when submitting a transaction from "proxied" account, it doesn't suggest to use the proxy account anymore (connected through Talisman). on the UI, it doesn't show the proxy when proposing to sign.
Instead it tries to sign with the "proxied" account and generate this error:
`Cannot sign with a locked key pair`

It fails in almost all the transactions panels (extrinsics, ~~governance~~, preimages,....) **except** in the ~~"preimages"~~ "council-motion" panel and "governance-vote" where it correctly picks the proxy and is able to sign correctly

**Comment by jacogr** [comment]
Does it show something like this in the console? 

`Not adding address <some address here>, not in correct format for chain (requires 32-byte publickey)`

**Comment by crystalin** [comment]
No, nothing in the console :(

**Comment by crystalin** [comment]
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/329248/217868353-486cfc62-931a-45c0-b1dc-3eb4b5876c36.png">

**Comment by jacogr** [comment]
Very weird. (Cannot reproduce either with my proxies)

**Comment by crystalin** [comment]
I think keeping the filter can be fine but putting an indicator that the proxy cannot be used (so the user knows, and the dev can update the filter list, zhich I would have done if I knew there was one)

**Comment by crystalin** [comment]
I also apologise cause I didn't realised I added a limited proxy and thought I was using the any

**Comment by jacogr** [comment]
I have removed the filter at this point. 

It is (currently) an absolute nightmare to keep the list updated - and that is on the networks that I do track, let alone the others which I cannot test.
