### ISSUE TITLE
Invalid publicKey provided  while adding multisig account

### ISSUE THREAD

**Issue by AurevoirXavier** [polkadot-js/apps#9032]
* **I'm submitting a ...**

  - [ ] Bug report
  - [x] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Successfully created a multi-sig account on the H160 accountid based network.

* **Please tell us about your environment:**

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpangolin-rpc.darwinia.network#/accounts

**Comment by jacogr** [comment]
Can you just walk me through exactly what you did? (Lacking some info above)

**Comment by AurevoirXavier** [comment]
> Can you just walk me through exactly what you did? (Lacking some info above)

Yep. Open the link that I provided. And click the add multisig. Then I got this error.

Here, click the create.
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/16152305/219284006-9cc631c2-9998-456d-b6b9-1e72e4a71074.png">

**Comment by jacogr** [comment]
This seems to be the exact issue as per https://github.com/polkadot-js/apps/issues/9209, aka for AccountId20 chains.

https://github.com/polkadot-js/apps/issues/9209

(Seems it took me a while to put 2 and 2 together here)

The long and the short of it is that at this point it won't quite work. Underlying we are using this logic https://github.com/polkadot-js/common/blob/4f5029118eb003041ff6c39c8336893a18590aee/packages/util-crypto/src/address/keyMulti.ts#L16-L23 to generate a blake2 32-byte hash which is then passed through. So couple of issue here -

- we don't have a configurable hasher (assuming the chains use a different one for this functionality - not sure how it all ties up)
- really have no idea what the pallet does if it does receive a 32 byte hash to go to a 20-byte AccountId

So at this point, it is quite obvious that the multisigs, as done, doesn't work on non-AccountId32 chains. Hence [this PR to disable it](https://github.com/polkadot-js/apps/pull/9211) until there is some solution and we actually figure out how the logic ties together in other chains.
