### ISSUE TITLE
post-css loader spamming console

### ISSUE THREAD

**Issue by rossbulat** [polkadot-js/apps#904]
This module spams the console when `apps` loads up. Is there a way to stop this behaviour?

<img width="1119" alt="Screenshot 2019-04-07 at 19 18 04" src="https://user-images.githubusercontent.com/13929023/55682762-53de6500-596a-11e9-9efe-cc6e33623f50.png">

**Comment by jacogr** [comment]
Irritating, it started randomly at some point. But useful in that it provides a constant reminder to get rid of `*.css` :)

**Comment by jacogr** [comment]
Closing, not worth fixing since we are moving all components away from app-specific CSS. (And the other imports such as semantic-ui does not need postcss, so the plugin will fall away. At most if will be a cosmetic short-term fix)
