### ISSUE TITLE
MultiSig transaction error during on-chain identity setups

### ISSUE THREAD

**Issue by anaelleparity** [polkadot-js/apps#9052]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [X] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
A project team attempted to register an on-chain identity for their multisig account with 3/5 signatures. All signatures were validated, but the call is still pending and throwing an error.
https://kusama.subscan.io/multisig_extrinsic/16729732-4?call_hash=0xd39ef8b7cfa0a6d3b643a200a90ae44f43ca1065cccb0a19a4c60f86f04db272

This is the complete error:
**createType(Call):: Call: failed decoding identity.setIdentity:: Struct: failed on args: {"info":"{"additional":"Vec<(Data,Data)>","display":"Data","legal":"Data","web":"Data","riot":"Data","email":"Data","pgpFingerprint":"Option<[u8;20]>","image":"Data","twitter":"Data"}"}:: decodeU8aStruct: failed at 0x00197066c661646742d7361666172692… on info (index 1/1): {"additional":"Vec<(Data,Data)>","display":"Data","legal":"Data","web":"Data","riot":"Data","email":"Data","pgpFingerprint":"Option<[u8;20]>","image":"Data","twitter":"Data"}:: decodeU8aStruct: failed at 0x6166617269444141768747470733a226… on legal (index 3/9): {"_enum":{"None":"Null","Raw":"Bytes","BlakeTwo256":"H256","Sha256":"H256","Keccak256":"H256","ShaThree256":"H256"}}:: Unable to decode Data, invalid indicator byte 97**

Please advise on how to support them.
Thank you! :pray:

**Comment by jacogr** [comment]
They need to be explicit.

1. How was call generated? (Exact steps)
2. Where does it fail? (Exact steps)
3. The actual explicit call data that fails.

The above doesn't help at all since it sadly misses all the critical information.

**Comment by anaelleparity** [comment]
Thanks for the follow-up, @jacogr. 
In the end, we figured out that the 3rd signatory did not submit the Multisig call data to finalise the transaction. Instead, the original call sender was trying to finalise the multisig transaction with a 4th signature, which threw the above error. :weary:
