### ISSUE TITLE
Aband color does not work

### ISSUE THREAD

**Issue by octavei** [polkadot-js/apps#9053]
in productionRelayKusama.ts

```
{
    homepage: 'https://a.band',
    info: 'aband',
    paraId: 2257,
    providers: {
      'Aband DAO': 'wss://rpc-parachain.a.band'
    },
    text: 'Aband',
    ui: {
      color: '#7358ff',
      logo: chainsAbandPNG
    }
  },
```
wo found color is `#7358ff` here.
but in [https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-parachain.a.band#/explorer](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-parachain.a.band#/explorer) ,
the color no change.
![1](https://user-images.githubusercontent.com/120352928/220807299-6a245057-0a80-435b-b8dd-11303f776ea5.png)

**Comment by jacogr** [comment]
All chains identified as development chains are always the default color. In this case the chain is configured as "Local" (not "Live").

![image](https://user-images.githubusercontent.com/1424473/220822615-fa79fe4f-1832-469e-a257-9cbddb2b2837.png)

**Comment by octavei** [comment]
I get it, thank you.
