### ISSUE TITLE
UI for submitting referenda using "inline call"

### ISSUE THREAD

**Issue by olanod** [polkadot-js/apps#9062]
* **I'm submitting a ...**

  - [ ] Bug report
  - [x] **Feature request**
  - [ ] Support request
  - [ ] Other

The referenda pallet added support for inlining ([bounded](https://github.com/paritytech/substrate/pull/11649)) calls to avoid having to submit a pre-image as an initial step. Most proposals for example are treasury spends that can fit within the bounds of what *inline* allows.

In the referenda section of the governance tab people can already submit proposals in a convenient way without having to craft the extrinsic manually, this process can be made even easier by supporting inline calls and not requiring the creation of a pre-image.

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/apps/issues/8447 (which is quite a bit broader, since it also would allow all-in-one step preimage submission if you prefer that)

**Comment by jacogr** [comment]
Closing since it is tracked elsewhere.
