### ISSUE TITLE
Make withApi generic over its ApiContext

### ISSUE THREAD

**Issue by yjkimjunior** [polkadot-js/apps#912]
Proposal: make withApi generic over its ApiConsumer by letting it accept a consumer that implements the ApiContext wrapper as parameter. This would be mainly to ease integration of dependent reactive components used in apps such as ui-reactive in external applications (in my case substrate-light-ui).

https://github.com/paritytech/substrate-light-ui/pull/178
#913

* Also requires changes upstream to pass down the generic consumer

<pre>
// Copyright 2017-2019 @polkadot/ui-api authors & contributors
// This software may be modified and distributed under the terms
// of the Apache-2.0 license. See the LICENSE file for details.

import { ApiProps, Subtract } from '../types';
import { DefaultProps } from './types';

import React from 'react';
import { assert } from '@polkadot/util';

import { ApiConsumer } from '../ApiContext';

export default function withApi <P extends ApiProps> (Inner: React.ComponentType<P>, defaultProps: DefaultProps = {}, <b>ApiConsumerWrapper: ApiConsumerType = ApiConsumer</b>): React.ComponentType<any> {
  return class WithApi extends React.PureComponent<Subtract<P, ApiProps>> {
    render () {
      return (
        <ApiConsumerWrapper>
          {(apiProps?: ApiProps) => {
            assert(apiProps && apiProps.api, `Application root must be wrapped inside 'rx-react/Api' to provide API context`);

            return (
              // @ts-ignore Something here with the props are going wonky
              <Inner
                {...defaultProps}
                {...apiProps}
                {...this.props}
              />
            );
          }}
    </ApiConsumerWrapper>
      );
    }
  };
}
</pre>

**Comment by jacogr** [comment]
If this helps allowing `ui-api` to be moved to the `ui` repo and used in both Rx & Promise, sure, good idea.

**Comment by jacogr** [comment]
Closing, @amaurymartiny implemented a different approach. (@yjkimjunior Happy to re-open if we need to)
