### ISSUE TITLE
No "Extrinsics" item in "Developer" menu without accounts

### ISSUE THREAD

**Issue by arty-name** [polkadot-js/apps#9172]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

When accessing Polkadot apps without a wallet extension or without an account on the current blockchain, the "Developer" menu does not include the "Extrinsics" item. 

This section can be still accessed when including `#/extrinsics` in the URL. The functionality is naturally limited but is usable to an extent, like decoding extrinsics. I believe this section should be directly accessible even without having a wallet with an account on the current blockchain.

* **What is the motivation for changing the behavior?**

Reiterating the point above: the functions which work without an account should still be accessible.

* **Please tell us about your environment:**

  - Version: apps v0.124.2-150 @ https://polkadot.js.org/apps/
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
It is certainly expected. If you don't have accounts, you can't send transactions. Hence no extrinsics.

**Comment by arty-name** [comment]
As a developer I mostly use this section to investigate extrinsics, and only rarely to send transactions, hence my disappointment
