### ISSUE TITLE
Moonbeam: create multisig button fails with "Invalid publicKey provided" error

### ISSUE THREAD

**Issue by Agusrodri** [polkadot-js/apps#9209]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

I've added `pallet-multisig` to ***Moonbeam***, ***Moonriver*** and ***Moonbase*** runtimes. From the `Extrinsics` tab in PolkadotJs UI, you can interact with the pallet without any issues. 

![image](https://user-images.githubusercontent.com/71607254/226947521-a6226a2d-627b-4385-9172-244c75aae78d.png)

The problem appears when you try to create a new multisig account from the `+ Multisig` button. After you select the desired accounts to be part of the new multisig account and press `+ Create`, an ***"Invalid publicKey provided"*** error is thrown.

![image](https://user-images.githubusercontent.com/71607254/226950558-0a7dc195-c8ef-4c0b-8516-a9ac1441ba8c.png)

![image](https://user-images.githubusercontent.com/71607254/226950263-3fab0971-4eba-4e9d-8228-998d0cb68fa3.png)

>Here is a link to a local node for you to try the whole process: 
https://polkadot.js.org/apps/?rpc=wss://fork.moonriver.kaki.dev%23/explorer#/explorer

* **What is the motivation for changing the behavior?**

I guess this is due to some incompatibility in PolkadotJs UI between `ETH-type` addresses and `Polkadot-type` addresses. Without the possibility of creating a multisig account from the `+ Multisig` button, we are in front of a bad user experience as the user has to manage to create it only interacting with the pallet directly.

* **Please tell us about your environment:**

      Version: api v10.1.3; apps v0.124.2-177
      Environment:
        - Browser: Chromium Version 111.0.5563.66 (Official Build) (64-bit)

**Comment by jacogr** [comment]
Seems like both an oversight and a simple fix. 

(The fork RPC does indeed help a lot - without being to test/verify it is up for a bad time)
