### ISSUE TITLE
More Dots bounded than in the balance

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#927]
The account `5F7BJL6Z4m8RLtK7nXEqqpEqhBbd535Z3CZeYF6ccvaQAY6N` has more bounded DOTs than available.

![image](https://user-images.githubusercontent.com/33178835/55733673-85186d00-5a1e-11e9-8edd-439ad94adfb6.png)

From the chain state:
staking.ledger: Option<StakingLedger>: 
`{"stash":"5F7BJL6Z4m8RLtK7nXEqqpEqhBbd535Z3CZeYF6ccvaQAY6N","total":"0x00000000000000000023829049fb9940","active":"0x00000000000000000023829049fb9940","unlocking":[]}` which is 9,995180413000000000×10¹⁵

balances.freeBalance: Balance
`9994663904165956`

**Comment by jacogr** [comment]
No a UI issue though - the UI only reports the details the chain provides. (For both these it is a straight display of the on-chain values)

**Comment by xlc** [comment]
The total/active part includes nominated DOTs so it can be higher than stash account balance. If there is an issue, it is the UI is not clear enough.

**Comment by jacogr** [comment]
Not quite correct, quoting from the Rust code -

```
pub struct StakingLedger<AccountId, Balance: HasCompact, BlockNumber: HasCompact> {
	/// The stash account whose balance is actually locked and at stake.
	pub stash: AccountId,
	/// The total amount of the stash's balance that we are currently accounting for.
	/// It's just `active` plus all the `unlocking` balances.
	#[codec(compact)]
	pub total: Balance,
	/// The total amount of the stash's balance that will be at stake in any forthcoming
	/// rounds.
	#[codec(compact)]
	pub active: Balance,
	/// Any balance that is becoming free, which may eventually be transferred out
	/// of the stash (assuming it doesn't get slashed first).
	pub unlocking: Vec<UnlockChunk<Balance, BlockNumber>>,
}
```

to here active & total is just for the stash, not including nominations. I'm assuming you are referring to `staking.stakers` (Which is `Exposure` rather than ledger)

And yes, the `+ nominator balances` for the overall total is not active yet, there is an issue logged to add that.
