### ISSUE TITLE
Waiting count and display doesn't quite match up

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#935]
Goal:

Ensure that all on-screen information match up.

Background:

There seems to be, in some cases, a mismatch of the actual "next up" validators that appear and the count displayed. How this happens (a simple subtract as I recall), not sure, however pictures don't lie - 4 displayed, however the count shows 3:

![image](https://user-images.githubusercontent.com/1424473/55833685-6ac2ba00-5b18-11e9-80a4-2a81160f33ce.png)

Actions:

- Check logic for display of both the list and the count
- Ensure that the source information is correct
- Make any adjustments needed to ensure it will always be correct going forward

This is either a 1-line fix or a rabbit hole.

**Comment by Stefie** [comment]
Is that still a thing? I can't reproduce with Alex or a local node

**Comment by jacogr** [comment]
That is the issue - it is sporadic. I think there may have been an improvement since we swapped the calls to multi, but ... well, it was a once-off, two-off occurence. So where there is smoke, there is fire. No idea if there is still fire since there was never a reliable way to get it to break.

**Comment by jacogr** [comment]
Closing. Th nextUp count is now calculated based on the number of items in the list.
