### ISSUE TITLE
"Hashbar" UX Concept

### ISSUE THREAD

**Issue by rossbulat** [polkadot-js/apps#937]
Presented in this issue is my take on how to display hashes globally.

So current issues I am seeing are:
- Large circular icons for each user account take up lots of space, make it hard to align or place hashes anywhere
- User icons contain lots of colours making it hard to distinguish one user from the next
- Full hash is not displayed, having to click on the icon to copy to clipboard to obtain the full hash.

### Proposed Solution
A responsive bar design, that
(a) can be applied to any layout, 
(b) header and footer friendly, 
(c) row and column friendly, 
(d) with the ability to embed buttons such as click to copy, 
(e) ability to maintain uniqueness for each user, 
(f) ability to recycle the design for other types of hash: blocks, extrinsics etc...
(g) ability to display either as standalone or inline, with labelling above or alongside the hash

Here is my proposed design in a range of variants:

#### Variant 1: Short hash / no embedded buttons
![shortHash](https://user-images.githubusercontent.com/13929023/55859919-abb4e000-5ba5-11e9-9228-1afc72732b5d.jpg)

* The colours assigned to a user's dots have been spread out as a bottom bar. Each color taking 50% less space than the previous. Giving precedence to 1 or 2 colours taking up majority of width will make a hash more distinguishable than if all colours were displayed equally.

* Polkadot icon demonstrates this is a user account hash. This icon could be replaced with others depending on the type of hash - in which case the coloured bar could also be removed.

* The bar width can be responsive: XX..XX is just as acceptable as XXXXXXX...XXXXXXX

Here are a couple more variants of a hash bar:

#### Variant 2: Longer hash
![longerHash](https://user-images.githubusercontent.com/13929023/55860376-a99f5100-5ba6-11e9-87d2-2a17981a75a0.jpg)

#### Variant 3: Embedded click to copy button
![withClickCopy](https://user-images.githubusercontent.com/13929023/55860416-c2a80200-5ba6-11e9-9a1a-e6a0c24a9f97.jpg)

Here's a few ways this could be applied to the current staking designs (boxes 1 - 3 demonstrate various placements, box 4 is the current design):

![hashConcept1](https://user-images.githubusercontent.com/13929023/55860474-e8350b80-5ba6-11e9-80a5-3fc3cee569e4.jpg)

* We are free to adopt a row or column based layout
* Very complimentary to media queries and changes to layout depending on screen size
* We are able to give precedence to the stash account, while the  controller and session could be housed in smaller hash bars.

## Other Functionalities

* To determine how many characters are displayed, we could adopt a HOC like `react-measure` to determine how many characters can fit inside a bar. Alternatively we could hardcode the amount of characters to display as a prop.

* The hash bar inner content would be sized in `em`, so the size of the bar dictates the size of the inner content, allowing us to resize the bar to match any layout.

* On `:hover`, the user account icon could transition from greyscale to the account's unique colours.

* Clicking a hash bar could pop up the entire hash, not dissimilar to the following illustration:

![hashConcept2](https://user-images.githubusercontent.com/13929023/55860574-20d4e500-5ba7-11e9-9a4e-4b0237a9d211.jpg)

Interested to get feedback and thoughts on this.

**Comment by jacogr** [comment]
So, we are in 2019 and still use "hashes" - actually addresses. The immediate reaction, as much as you dislike the icons, they are not going to be removed - if anything, the addresses should be removed. The icons are _actually_ the unique identifier and consistent across the ecosystem.

**Comment by rossbulat** [comment]
Hmm, the problem with the icons though in addition to what's mentioned above is that they are not human readable, I wouldn't look at the same one twice in a list and recognise it to be the same account, which is an issue provided the purpose of them is a visual cue

**Comment by jacogr** [comment]
So, apps is not moving to a custom implementation that is not standard across the ecosystem. Click around, look at: telemetry, substrate-ui, substrate-light-ui, Parity hardware signer, polkawallet, .. any app where an icon is displayed.

This is an ecosystem standard, so take this to the W3F, get an implementation there and acceptance there, and it will be happily added as an icon type to polkadot-js/ui, until then, a very clear and resounding "won't fix". (And there are certainly optimisations that can be done in apps to make thing better, going down an own route is not one of them)

**Comment by jacogr** [comment]
- To clarify, the icon standard for Polkadot is the "little dotty icons", as introduced by Gav.
- jidenticon is the standard for substrate

**Comment by rossbulat** [comment]
OK, worth the discussion with the W3F.

I wouldn't call it a separate route, it is more of an abstraction that is better suited to the dense UI of apps. I am in favour of keeping the polkadot icon, which is why it is still included in the proposed design. 

In any case I won't pursue this further for apps.
