### ISSUE TITLE
Convert label help hover to react-tooltip

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#938]
Goal: 

Get a consistent and standard implementation of all tooltips, instead of custom solutions for different places.

Background: 

We started using react-tooltip in https://github.com/polkadot-js/apps/pull/929 and it more of a flexible "standard" solution.

Actions:

- in ui-app/Labelled convert the custom help-on hover to use react-tooltip
- We don't want to pass through any more details than we already have
- All placement information is to happen in the component itself
- Verify that it is working and wraps longer text to an acceptable limit (and doesn't have artefacts like in the screenshot)

![image](https://user-images.githubusercontent.com/1424473/55871396-cf1e6180-5b8a-11e9-8c90-29fe137898fa.png)

**Comment by rossbulat** [comment]
There are conflicts with the `ui` class attached to `modal` that create some odd behaviour on the tooltip.

May be a good time to revisit the modal and strip out what is not needed.

**Comment by Stefie** [comment]
Are we moving away from Semantic UI React? It has a Popup/ Tooltip component 
https://react.semantic-ui.com/modules/popup/

**Comment by jacogr** [comment]
With #938 we can swap - honestly, initially when implementing the help hovers used the SUI version and it just looked completely off, hence went for a quick-and-dirty own version there. Once in an own component can play around with it again. 

react-tooltip is not the easiest to use (in my mind), but with some tweaks seem to fit slightly better. (Nothing that some additional css magic cannot fix, with the above PR it is a single place and we can certainly drop the other dep)

**Comment by Stefie** [comment]
Ok, I need to change it in app-js, then! I remember having some issues with the SUI <Popup> there anyways, so changing it could be a good idea anyways! :)

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/apps/pull/1050
