### ISSUE TITLE
Add extra info and help to critical apps

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#946]
Goal:

We want to make the app itself as self-explanatory as possible, which means aligning all different sections to provide at-the-fingertip information to all users.

Background:

The staking app has been leading the way is making it simpler to understand what is going on and by providing help for all of the input fields via "(?)".

Actions:

(For all of: democracy, transfer, accounts & addresses)

- Add "(?)" `help` property to all input fields, with relevant information that explains the use
- Add a help overlay (as the `/#/staking` and `/#/contracts` apps has)
- The help overlay should have a layman description of the app and what you can aim to achieve - additionally it should describe any terms that are used and not part of common-day vocabulary

**Comment by Tbaut** [comment]
Taking a stab at it.

**Comment by Tbaut** [comment]
I wonder if there is a need for a help overlay for the transfer, account and addressed apps. They seem quite self explanatory to me. The democracy needs one as there is a lot shown and very few call to actions (thus few `(?)` explaining what can be done).

**Comment by jacogr** [comment]
Transfer itself is actually not as self explanatory as it seems ;) ie. It only doe the native chain token, it does calculations on fees, you could drop your account, etc. at least here just some basic info would help. (And form a base of what is elsewhere)

For Accounts - things like the different crypto types and keeping stuff out of the public is important as well. 

Addresses - probably not much, apart from that it also saves recents and just allows quick access. 

Do 100% agree that none of these are overly complex though and just some “light pointers” does the trick... hopefully ;)

**Comment by jacogr** [comment]
Edit: for accounts as well - derivation paths, those are entirely non obvious. Hard, soft (only sr25519) and the optional triple-slash password. 

Strangely enough, had not had too much queries around these as of yet...

**Comment by yuhui1208** [comment]
when i make a transfer,How do I get events about transfer extrinsic, i only get the 'system.ExtrinsicSuccess' event, can not get 'balances.Transfer' event???
