### ISSUE TITLE
latest release 0.131.1 has no downloads

### ISSUE THREAD

**Issue by core-code** [polkadot-js/apps#9492]
the latest release 0.131.1 has only source code downloads, making it hard to find executable binaries. is this on purpose? will binaries come later?

**Comment by core-code** [comment]
thanks there.
could you mark '0.131.1' as pre-release as long as it has no binaries so that the official "latest release" linked from the main github page does have downloads?

**Comment by jacogr** [comment]
0.131.1 will never have binaries - binaries are only added in the release process on CI. (There is no manual process for this)

**Comment by core-code** [comment]
> 0.131.1 will never have binaries 

then it should not be marked as "latest release"?

**Comment by jacogr** [comment]
It is indeed the latest.

**Comment by core-code** [comment]
it may be the latest but it is unobtainable because there are no binaries.

marking a release as "latest" that cannot be used, breaks all your downstream users, both automated (Homebrew, MacUpdater, etc) as well as manual (actual users trying to download something executable).

@suschizu please remove the polkadot-js-apps cask as we are getting errors here every 3 hours
