### ISSUE TITLE
approveAsMulti/ asMulti transaction hangs indefinitely without submission

### ISSUE THREAD

**Issue by adamsteeber** [polkadot-js/apps#9551]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

To update vote delegations on my multisig, I have to undelegate and redelegate votes with the new delegated balance. When initializing the undelegate multisig call with `approveAsMulti`, the transaction hangs in the "broadcast" state indefinitely without actually being submitted to the network. The encoded call data I use to undelegate is: `0x18043c140200001402010014020a0014020b0014020c0014020d0014020e0014020f00140214001402150014021e0014021f00140220001402210014022200`. Sometimes it will submit after a long time but most of the time it just hangs forever. If it does manage to get submitted, the `asMulti` call to execute the transaction has the same problem. Same problem also occurs when I attempt to redelegate with the following encoded call data: `0x18043c1401000000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c07000000000000000000001401010000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c070000000000000000000014010a0000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c070000000000000000000014010b0000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c070000000000000000000014010c0000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c070000000000000000000014010d0000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c070000000000000000000014010e0000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c070000000000000000000014010f0000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c07000000000000000000001401140000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c07000000000000000000001401150000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c070000000000000000000014011e0000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c070000000000000000000014011f0000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c07000000000000000000001401200000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c07000000000000000000001401210000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c07000000000000000000001401220000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c0700000000000000000000`

[You can see a successful attempt here if you'd like to try to reproduce the issue.](https://kusama.subscan.io/multisig_extrinsic/18256499-3?call_hash=0x1b1486d09ac0fe6d57b877ca4a36a77851e73d70ecbf892b433aa256901efc06)

[Here is a link to a screen record of the issue.](https://photos.app.goo.gl/FV8F4J8umevsFnyr5) This call was [successfully submitted](https://kusama.subscan.io/extrinsic/0xe62f3e5dec4c4b24dc5b3422c5aa2884420ee2f485abd855245f14f2c7355a4e) after ~3 minutes but I'm having trouble finishing the transaction with the `asMulti` call since it just hangs forever.

* **What is the motivation for changing the behavior?**

My hypothesis is that the weight is causing the issue since it is quite large. Perhaps there's some frontend logic that gets caught up with large weights? Or maybe there's something fundamentally wrong with the multisig call itself? Maybe I shouldn't use `forceBatch`?

* **Please tell us about your environment:**

  - Version: v0.131.5-19
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
There is no batch weight logic applied to the extrinsics tab. It just submits as the user inputs it. If overweight, it would certainly fail.

(Batch logic for splitting if applied where the UI itself creates batches, e.g. in staking payouts)

**Comment by adamsteeber** [comment]
I guess I'm confused because when I query the weight of the call with:

```
const sender = 'EQpz7J49eVyU881vz7MFSMpwJmpURXLEqiEp9zjiXzeZrXu'

const hex = '0x18043c1401000000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c07000000000000000000001401010000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c070000000000000000000014010a0000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c070000000000000000000014010b0000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c070000000000000000000014010c0000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c070000000000000000000014010d0000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c070000000000000000000014010e0000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c070000000000000000000014010f0000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c07000000000000000000001401140000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c07000000000000000000001401150000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c070000000000000000000014011e0000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c070000000000000000000014011f0000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c07000000000000000000001401200000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c07000000000000000000001401210000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c07000000000000000000001401220000bc486ed2f394da6e6b58b130687b48d3d19f756ba6d0655d37bf58ff0f59f9740600388d7e8c0700000000000000000000'
const extrinsicCall = await api.createType('Call',hex);
const { method, section } = await api.registry.findMetaCall(extrinsicCall.callIndex);
const extrinsicFn = await api.tx[section][method];
const info = await extrinsicFn(...extrinsicCall.args).paymentInfo(sender);

console.log(`weight=${info.weight.toString()}`);
```

I get `weight={"refTime":1298484283652,"proofSize":27454470}` which is below the maximum normal extrinsic weight of 1,500,000,000,000. This is also the weight indicated in the `approveAsMulti` call. It seems to be the correct weight for the batch... Is this still too big because it would push the block over maxBlock since mandatory reftime in each block usually hits ~750,000,000,000, effectively setting the maximum extrinsic reftime to ~1,250,000,000,000? Is that why it hangs - because it's waiting for a block small enough to fit the large call?

**Comment by jacogr** [comment]
The fact that it does get included means you are below, the fact that it "takes a long time" seems like it waits until there is enough space.
