### ISSUE TITLE
[Bug] Staking Historic Results graphs not rendering

### ISSUE THREAD

**Issue by JelliedOwl** [polkadot-js/apps#9567]
* **I'm submitting a bug report related to the staking historic results graphs**

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

I've been seeing this for a while, but I think it's intermittent - and I didn't see an issue about it already (sorry if I missed one).  When I try to view a validator's "historic results" graphs, some of them aren't rendering.  Currently I'm seeing it for the era points graph, but I think I've seen it on other graphs at various times.

Here's an example:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.api.onfinality.io%2Fpublic-ws#/staking/query/CrTPV874i4VNTjkCfQbGpPT338dhyu27w6poWrKuZZpEz17
<img width="1113" alt="Screenshot 2023-06-10 at 16 18 57" src="https://github.com/polkadot-js/apps/assets/80860490/916c07ad-4b06-4096-b471-283bd60a0382">

I've tried for a few validators on a few different end points, and it looks consistent.

* **Please tell us about your environment:**

Seen on polkadot.js.org/apps and cloudflare-ipfs.com/ipns/kusama.dotapps.io

I'm using Google chrome (114.0.5735.106 (Official Build) (x86_64)) on MacOs Ventura 13.4.

**Comment by jacogr** [comment]
Sadly, there is nothing that can be done here - it is actually related to a chart plugin that is in-use, see https://github.com/polkadot-js/apps/issues/8745

I have tried in the past to try and work-around their code, with some success (i.e. it is slightly better), but there is literally nothing that I can come up with additionally to try and work around this. (And no replacement plugins for the functionality either)

**Comment by JelliedOwl** [comment]
Thanks Jaco.  Sorry - despite searching, I clearly missed at least 2 previous issues on this. :-(
