### ISSUE TITLE
Incorrect ideal staking rate on Kusama and Polkadot

### ISSUE THREAD

**Issue by jonasW3F** [polkadot-js/apps#9612]
* **I'm submitting a ...**

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

The ideal staking rate is shown as 75% on Polkadot and 45% on Kusama. Both values are incorrect. The ideal staking rate is calculated [here](https://github.com/paritytech/polkadot/blob/2d840ffb2f778831faef07eb4cbd50ce66eeac1f/runtime/common/src/impls.rs#L76) by using [all active parachains](https://github.com/paritytech/polkadot/blob/2d840ffb2f778831faef07eb4cbd50ce66eeac1f/runtime/polkadot/src/lib.rs#L554) with an ID greater or equal than 2000 (i.e., no system parachains). 

It seems to me the Polkadot tab does not at all calculate the proper ideal staking rate, while the Kusama tab might still use the (outdated) calculation of using the number of auctions (that keeps counting up even if slots expire), pushing it to the minimum of 45% 

Based on my calculations the ideal staking rate right now should be 53.5% on Polkadot (43 parachains) and 55% on Kusama (40 parachains).

**Comment by jonasW3F** [comment]
ah, sorry for that and thanks for fixing it.

**Comment by jacogr** [comment]
It is not "fixed" - it will probably still be while until I get some time to add tests to the Rust codebase to compare and then check/merge the linked PR. Unless there is proven consistency between the 2, cannot merge it. 

(This is what was done on the initial implementation of the subsequently changed inflation calcs - port logic, add tests to compare between Rust/JS, compare, tweak, merge)
