### ISSUE TITLE
Simple staking app

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#97]
- Allows users to stake/unstake
- Allows a view of current validators + their balances
- Allows a view of current intentions (i.e. accounts wishing to stake) + their balances
- indication if any current accounts are validators and/or has the intention to stake (this probably goes on accounts/addresses as well)

**Comment by palevoo** [comment]
@jacogr hey, I would to contribute here, as part of the interviewing process, if thats cool

**Comment by jacogr** [comment]
Any and all PRs are always welcome, small, medium, big :) Feel free to ask for clarification to expand, the idea is very "light" atm.

**Comment by jacogr** [comment]
@palevoo Any help needed? Clarifications? Pointers?

**Comment by jacogr** [comment]
Put together a get-started example this morning, it could be useful as well - https://github.com/polkadot-js/apps/tree/master/examples
