### ISSUE TITLE
Allow filtering in staking overview (by type)

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#971]
Goal:

Allow the user to have a better view of the information presented.

Background:

In https://github.com/polkadot-js/apps/pull/965 some really basic filtering was introduced for the accounts section of staking. We need to expand this to filter the ever growing list of validators. (This is related to https://github.com/polkadot-js/apps/issues/951, but an basic no-frills addition to use already-available information for a up-front filter)

Actions:

- Add a filter
- Pass through the filter to the actual validators rendered
- Suggestions for filter categories:
  - All validators/intentions (default)
  - Stashes with no nominators
  - Stashes with nominators
  - Stashes with no warnings
  - Stashed with warnings
  - Stashes that my accounts nominate

**Comment by Stefie** [comment]
Solved with @Lowhearth 's PR that got merged this morning.
