### ISSUE TITLE
Improvements to Childbounties IDs

### ISSUE THREAD

**Issue by anaelleparity** [polkadot-js/apps#9735]
**I'm submitting a ...**

  - [ ] Bug report
  - [X] Feature request
  - [ ] Support request
  - [ ] Other

**Current behavior**
At the moment, curators have to manually check for childbounties IDs before and while creating/awarding a childbounty on Polkadot-JS apps, which has 2 implications:
- Curators are always indirectly competing with each other when using childbounties IDs in their calls
- Curators are always at risk of having complex time-consuming calls get rejected at the last minute

**Some comments/suggestions**
The current childbounties IDs system is suitable for a setup with 1 or 2 bounties, but very inefficient when there are 8+ bounties, as is the case on Polkadot at the moment.
- Could childbounties IDs be tied to their parent bountyID, rather than be shared across all bounties?
- Having a separate system for Childbounties IDs tied to their parent bounty ID would help curators and the community gain a better overview of childbounties-related data (i.e how many, for which bounty, how often, recurrent implementers profiles/recurring beneficiaries, etc.)

Thanks.

**Comment by anaelleparity** [comment]
Edit: I have been advised that this is a FRAME issue. 
This issue has been forwarded here: https://github.com/paritytech/polkadot/issues/7557

**Comment by jacogr** [comment]
There is nothing the UI can do on this - it reads the chain state and displays as-is.

(There is obviously a long-standing enhancement logged here and in the queue for someday to actually add child bounty functionality, the apps UI does not have support for it, PRs to add the functionality welcome)
