### ISSUE TITLE
Add the ability to second in democracy app

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#976]
Goal:

We want the democracy app to be fully comprehensive for all actions that can be taken.

Background:

Currently voting can take place, and there is the potential to submit proposals via https://github.com/polkadot-js/apps/issues/975. The only major addition is to second a proposal.

Actions:

- As proposals pop-up, allow for the ability to second (like we would vote)
- select account, value, submit

**Comment by jacogr** [comment]
@ltfschoen I'm assuming with your current work we can unassign this one?

**Comment by ltfschoen** [comment]
> @ltfschoen I'm assuming with your current work we can unassign this one?

Yes, got stuck on this one, happy for someone else to finish it off due to the circumstances
