### ISSUE TITLE
Display documentation for state queries on hover

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#977]
Goal:

Expand the information available for the chain state app by providing access to the full documentation from the metadata.

Background & Actions:

This is the same as in https://github.com/polkadot-js/apps/issues/969 - the same applies, just for a different app. Pull meta from selection, display as part of the app help hover. (Or alternatively, we can have a details section like we have for the extrinsics and events in the block explorer)

**Comment by Tbaut** [comment]
Done in https://github.com/polkadot-js/apps/pull/1247
