### ISSUE TITLE
Kusama staking issue

### ISSUE THREAD

**Issue by Anthonyl3** [polkadot-js/apps#9822]
Hello there,

I sent my tokens to this validator APERTURE MINING 🎂/01
and now I can't seem to transfer them back out.  What I wanted to do is stake my tokens but somehow I sent it to the validator.  It's showing the coins are there but I don't know how to transfer them back out.  Could someone help me out.  

Much appreciated.  

Anthony

<img width="415" alt="Screenshot 2023-08-26 at 12 23 03 AM" src="https://github.com/polkadot-js/apps/assets/143251487/c348acfd-6f00-49e7-88e1-d9947080aa54">

* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [x] Other

**Comment by jacogr** [comment]
You will need to contact the validator and ask him to send it back to you. 

You made a transfer, which means the tokens is now in his control.

**Comment by Anthonyl3** [comment]
I contacted the validator and he was able to reverse the funds for me quickly.  Thanks for your help.  I was able to stake it properly by bonding instead of send.
