### ISSUE TITLE
Cleanup account modals, very dated, very ugly

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#985]
Goal:

Make the UI pleasant.

Background:

Currently the account modals work, but are ugly-as-sin.

<img width="748" alt="Polkadot:Substrate Portal 2019-04-11 21-31-54" src="https://user-images.githubusercontent.com/1424473/55987253-6675d880-5ca1-11e9-9d38-db3259bb9c65.png">
<img width="561" alt="Polkadot:Substrate Portal 2019-04-11 21-31-34" src="https://user-images.githubusercontent.com/1424473/55987254-6675d880-5ca1-11e9-93a8-e6c1a87bed40.png">
<img width="570" alt="Polkadot:Substrate Portal 2019-04-11 21-33-29" src="https://user-images.githubusercontent.com/1424473/55987285-7a213f00-5ca1-11e9-96db-a470c1b0cba7.png">

Enough said?

Actions:

- Make it informative & actually pleasing
- Some additional information would be required as well - i.e. on "forget", just indicate that the state is still on-chain, just this browser won't have access to it anymore

**Comment by jacogr** [comment]
@yjkimjunior @Tbaut @chevdor I wanted to put this up as a bounty, but realised is it way, way under-specified. All I know is that, well, it is ugly. Some thoughts on specifics to make it more informative?

**Comment by chevdor** [comment]
Hi @jacogr ,

I don't find the UI ugly at all here.

First I would say that the address in those dialogs should NOT be truncated.

Since the FORGET is a critical/scary thing :) 
I would include an alert box to explain what happens and especially how can we get back the account later on. This time it probably should not be a (?) but text directly visible.
I would include in the explanation that an account with a 0 balance is not always something to trash (see session accounts for instance).

I find seeing the balance and the number of tx very useful. Seeing info such as: Am I validating, nominating, etc...  would be nice as well.

I remain confused with FORGET being blue and CANCEL being red...

**Comment by jacogr** [comment]
Those are good points - is this an active session account, active stash, active controller, ...

**Comment by Tbaut** [comment]
My 2cts:
- I find the modal at account creation somehow unaesthetic, the others are ok IMHO.

- Modal at account creation can be smaller by removing the account image & info, the user has had the ability to see these info before. We can focus the message on the account backup, aligning the content to the left might make it a little nicer.
![image](https://user-images.githubusercontent.com/33178835/57105867-3bc0f200-6d2c-11e9-9442-3d41f89e871a.png)

 - >First I would say that the address in those dialogs should NOT be truncated.

    Really?, does any non robot check the characters beside the couple first and last? Also I don't think "forget" is a super big deal since accounts are backed-up at creation.

- What makes them look a little weird I guess is:
  - the identicon is super big
  - the content is cantered
- What's probably missing is the name

For the record I gave it a shot but couldn't come up with something nice. Whether it's centered / on the left didn't change much, it's still meh..
![image](https://user-images.githubusercontent.com/33178835/57106971-1aadd080-6d2f-11e9-9614-5e1871e3b481.png)

**Comment by yjkimjunior** [comment]
I agree with @chevdor, the modals do their job and are consistent with the overall theme.

My 2cents for enhancements:
1. Double check on Forget button click -> "Are you sure? ..." + clarify that the account state will remain onchain + a reminder about the backup file they generated to regain access to it.
2. The forget button should really not be blue, but this is really a symptom of the little flexibility offered by the Button.Group component, but rewiring all that would be a lot of pain for not so much reward...so I would propose (1). 
3. I agree with @Tbaut that the ability to actually see the whole address is not as important as being able to verify it's correct, and I'd bet most non-robots would do that by doing a "copy + find", so maybe the happy medium here is to make a more obvious 'copy address' button than hovering over the identicon, regardless of whether it's the full or short address displayed?
4. The left align looks nice.

**Comment by chevdor** [comment]
> Really?, does any non robot check the characters beside the couple first and last? Also I don't think "forget" is a super big deal since accounts are backed-up at creation.

Yes, I do copy the address for instance and add it to my password manager. Seeing it in full (we have room here) allows me to double check that whatever landed in my clipboard *is* the address.
