### ISSUE TITLE
`Balances::transfer` will be removed

### ISSUE THREAD

**Issue by ggwpez** [polkadot-js/apps#9854]
Just a heads-up that there will be a breaking change to the balances pallet here: https://github.com/paritytech/polkadot-sdk/pull/1226

Two calls will be ~~renamed~~ removed:
- `transfer` -> `transfer_allow_death`
- `set_balance_deprecated` -> `force_set_balance`

Feel free to close if this will be handled automatically, just wanted to ensure that you are not surprised by it 😄 

cc @juangirini

**Comment by jacogr** [comment]
It has been handled for a while, https://github.com/polkadot-js/apps/blob/0366991f685a80147f46eb69a23285acb15bc6b7/packages/react-components/src/modals/Transfer.tsx#L222-L228 (

After this PR when the new extrinsics went in - https://github.com/polkadot-js/apps/pull/9221)

**Comment by juangirini** [comment]
@jacogr just to triple check, do `set_balance_deprecated` -> `force_set_balance` follow the same fashion?
