### ISSUE TITLE
Joystream: staking inflation is wrong

### ISSUE THREAD

**Issue by traumschule** [polkadot-js/apps#9860]
For the Joystream chain staking `Overview` displays inflation as 4.2% while in fact 1.1% would be correct (at 11% staked).

The reason is that [default parameters](https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/params/inflation.ts#L25) are used: 2.5% .. 10%

[Joystream runtime parameters](https://github.com/Joystream/joystream/blob/master/runtime/src/lib.rs#L517) set range between .75% .. 3% at 50% staked.

**Comment by jacogr** [comment]
The team would need to provide a PR to update the parameters - there is way too many chains for a single person (me) to track and update all parameters.

TL;DR Happy to review and merge a PR

**Comment by traumschule** [comment]
Yes, i created that issue for our team :) We'll link the PR later.
