### ISSUE TITLE
Apps wallet: existence of Council not correctly detected

### ISSUE THREAD

**Issue by TorstenStueber** [polkadot-js/apps#9914]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

The council of the [Pendulum parachain](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-pendulum.prd.pendulumchain.tech#/explorer) is not correctly detected anymore:
- the governance menu does not have an entry for Council anymore
- when changing `#/explorer` in the url to `#/council`, then it will change back immediately and the following console message displays: "Redirecting from route "/council" to "/explorer", missing the following APIs: ["query.council.prime"]"

However:
- Pendulum has a Council
- the API `query.council.prime` does indeed exist
- the apps wallet correctly detected that Pendulum has a council until recently
- this still works on the IPFS version of the apps wallet: https://cloudflare-ipfs.com/ipns/dotapps.io/#/council

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TorstenStueber** [comment]
@jacogr can you help here? This is now also broken on the IPFS version and makes it impossible to submit council motions on Pendulum right now – a very serious issue for us.

**Comment by TarikGul** [comment]
Okay so for the most part I have it sorted. Basically the module is being supplied as `generalCouncil` but resolved to `council` with an override it seems. 

Why this is an issue? Well PJS is using `api.registry.getModuleInstances` in both the api and apps to get the module it's trying to reach and failing. 

So this is going to be a 3 part fix, I need to apply the fix to the api derive for council's, then apply and add the api release downstream to apps on thursday as well as the councils fix to apps for routing.

I do have it all working locally though which is a good sign
