### ISSUE TITLE
UI becomes unresponsive for development chain

### ISSUE THREAD

**Issue by rajdeep7Singh** [polkadot-js/apps#9963]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

**Current Behavior**: UI becomes unresponsive. In my case happens when a referenda is about to leave decision period (seconds left), i have modified trackInfo locally. Attaching screenshots for the bug.

<img width="1509" alt="Screenshot 2023-10-19 at 11 32 59 PM" src="https://github.com/polkadot-js/apps/assets/42423438/0e3fe5d6-7a08-4536-bc03-610a19ffdca8">

<img width="756" alt="Screenshot 2023-10-19 at 11 33 24 PM" src="https://github.com/polkadot-js/apps/assets/42423438/f26735d4-8d93-4338-a67d-42a8c3badff5">

**expected Behavior**:  It should be responsive.
<!---

**Comment by rzadp** [comment]
The same still happens - both Firefox and Chrome, also on most recent `polkadot-sdk` release built locally.

**Comment by hemantwasthere** [comment]
Hey, I would like to work on this issue

**Comment by TarikGul** [comment]
I need to confirm this by reproducing it locally, but @hemantwasthere If you are able to reproduce it, and have the bandwidth, all the help is appreciated :)

**Comment by hemantwasthere** [comment]
@TarikGul Okay I'll try then

**Comment by rzadp** [comment]
Hey @hemantwasthere, did you have any luck with this?

**Comment by rzadp** [comment]
Hey, I poked around myself, consistently reproduced the issue, and proposed a fix: https://github.com/polkadot-js/apps/pull/10690

cc @TarikGul
