### ISSUE TITLE
One or more of the libs use old util dependency

### ISSUE THREAD

**Issue by dudo50** [polkadot-js/apps#9971]
* **I'm submitting a issue**
One or more of your repositories uses old util dependency resulting into unmet peer warning when we install @polkadot/apps-config

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

<img width="751" alt="Screenshot 2023-10-20 at 22 43 02" src="https://github.com/polkadot-js/apps/assets/55763425/dafdb823-cbbf-4800-96ac-339b27e679d8">

Shoud not throw these warnings

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Those are the actual 3rd party dependencies.

Depending on your config, I would suggest you use `resolutions` in yarn (which is what apps does) or `overrides` in npm to pin the versions to latest.

Alternatively log the issue with the upstream libs where it originates, this is not something controlled here.
